### ISSUE TITLE
Renaming namespaces

### ISSUE THREAD

**Issue by catester** [0xd4d/dnSpy#10]
Is it possible to add "Rename Namespace" feature?

**Comment by 0xd4d** [comment]
It is, might do it later this week.

**Comment by catester** [comment]
Great, thanks. Do you think this would have any side-effects? I guess when you rename a Type, all references in the assembly are updated automatically, right? Also what about custom attributes? I stumbled upon below comments on [this page](http://blog.muonlab.com/2011/08/01/how-to-modify-net-types-names-and-namespaces-inside-compiled-assemblies-using-mono-cecil/) about doing this with Mono.Cecil:

> I know this is an incredibly old post but I tried doing this today and it failed on updating the references to types that were used in custom attributes. I’m investigating why and I’ll post here if I find out.

> That’s a bit strange. Merely enumerating over the Attributes and their Constructor arguments was enough to update the references so that when I saved the assemblies the references had been updated!

I hope this is not the case also with dnLib. Also I hope this feature can be supported in command line too for bulk renaming easily.

**Comment by 0xd4d** [comment]
If you rename a type in asm A that is referenced from asm B, then you must rename the reference in asm B too. This is not something dnSpy will do for you.

**Comment by catester** [comment]
Yes, I know that I was only talking about all references within the same assembly.
