### ISSUE TITLE
Obfuscated literals naming rules and clarification

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#1002]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)
one of latest (a week or so)

- What version did you use?
dnSpy v5.x.x

- Write down all steps needed to reproduce this issue. Also attach any needed files.
question:
I'm wondering why dnSpy in some cases shows obfuscated variables (or members/classes/etc) names
as \u1234  and in other cases - not?
here is an example of what I"m talking about

**expected behavior - represent  all non-legal chars as \u1234**
in this case end-user might have a possibility to easily identify vars of different types in a routine as well visually differentiate symbols in a left tree-view
Treeview is a special case - sometimes it shows "?", sometimes \u1234 also pay attention to hint - it shows yet another stuff!

example:

![obf_naming](https://user-images.githubusercontent.com/765343/49008947-d9aa0280-f177-11e8-9380-13ef65e4f597.png)

![obf_naming2](https://user-images.githubusercontent.com/765343/49009004-03632980-f178-11e8-88a7-7b6a91541834.png)

**Comment by 0xd4d** [comment]
It can't possibly know which characters are supported by your font. Here's the code that decides if it should escape it or not: https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy.Contracts.Logic/Decompiler/IdentifierEscaper.cs#L110

Some similar code exists in the decompiler too.

**Comment by greenozon** [comment]
Well, I"m using default font settings, which are:
font named "Consolas"

I'm still wondering why all these vars are named as a strange symbol [?]    (question mark inside)
is it some kind of issue rendering the symbol using "Consolas"
also I"m wondering if all these [?] have same unicode value or not?

also hint window uses different rendering output (not [?], why?)

here is what I"m talking about:

![obf_naming3](https://user-images.githubusercontent.com/765343/49013059-272c6c80-f184-11e8-946b-2f30f8fc84b3.png)

**Comment by greenozon** [comment]
One more question (to understand what's going on):

if we inspect the 2nd picture in 1st post (internal enum)
it has lots of values, right?
and we see for example 
\u170D,
then we have 4 values not escaped as \u (why?)
it is obvious that values of these 4 non-escaped are \u170E - \u1711
then we have \1712

**Comment by 0xd4d** [comment]
```C#
char.GetUnicodeCategory('\u170E') == OtherLetter
```

Google `U+170E` for the letter.

Tooltips use a different font.

**Comment by greenozon** [comment]
You are right, 
all these kind of \u17xx are of type OtherLetters
but... after inspecting looks like this is a huge big set of letters (really big!) 
http://prntscr.com/ln4nnq
from here

List of Unicode Characters of Category “Other Letter”
Name: | Other Letter
Number of Entries: | 121,212 
https://www.compart.com/en/unicode/category/Lo


I doubt any PC will have that full set available as well as these kind of symbols are pretty much very similar,
so my  vote would be to remove support of 

case UnicodeCategory.OtherLetter:


Please consider this option and this will really make reading obfuscated code much much more user friendly!

**Comment by 0xd4d** [comment]
No that would escape a lot of valid characters such as all chinese symbols.

**Comment by greenozon** [comment]
Do you mean you could name class/function/variable using chinese letters?

Maybe we talking about different cases
my ask was for compiler tokens only (not a pure strings)

**Comment by greenozon** [comment]
Amazing!
and sad
at the same time

thanks for clarifications.
Closing this question thread.
