### ISSUE TITLE
Cannot debug a release of a game!

### ISSUE THREAD

**Issue by DanteMele** [0xd4d/dnSpy#1003]
I used dnSpy, 64/32-bit, v5.0.7. The game is Bad Piggies from Rovio, version 1.5.1, 32-bit application and is built off Unity 4.2.1f4, I used the correct version modified mono DLL and tried to debug the game, but the game doesn't load and dnSpy doesn't fetch any debugging information!

![image](https://user-images.githubusercontent.com/30186527/49048490-ca36b380-f18f-11e8-9abc-65b8f452f3df.png)

Any advice on help on making this work? I'm specifically trying to find out what encrypts and decrypts a save.

**Comment by piratesephiroth** [comment]
did you read the wiki? you have to attach the debugger when the game is running

**Comment by DanteMele** [comment]
I tried, dnSpy doesn't pick anything up while its running or says "player already running".

**Comment by 0xd4d** [comment]
Restore the game and follow the wiki again. Make sure you copy the correct mono.dll file (check version, and also use the correct bitness (32-bit or 64-bit depending on if this is a 32-bit or a 64-bit game)).

If it doesn't work show any error messages or other info that could be useful to figure out what's wrong.

**Comment by DanteMele** [comment]
Ok I did that and it worked after I applied the ENV variables, but I cannot find the function that decrypts save files...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 0xd4d** [comment]
Closing it since you can debug it.
