### ISSUE TITLE
Editing Code contaning DLL references as “embedded resources” (see Costura) doesnt seem to work

### ISSUE THREAD

**Issue by rlesch** [0xd4d/dnSpy#1006]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
latest 5.0.9.0
- Write down all steps needed to reproduce this issue. Also attach any needed files.

While trying to edit/recompile code that references dlls as (compressed) embedded resources (by Costura), dnspy claims missing assemblyreferences / namespaces.
Even just opening and (re)compiling a method/class w/o any changes doesnt work, dnspy alwas mocks about missing references. 

![error](https://user-images.githubusercontent.com/45274733/49199019-33881380-f396-11e8-986f-25bd8ed05536.jpg)

![error2](https://user-images.githubusercontent.com/45274733/49199089-74802800-f396-11e8-8763-d9ea8fd4a336.jpg)

**Comment by rlesch** [comment]
Thanks for the answer!
so, see if i got it right (_noobalarm_): if i got all the code in one File, where even the dlls/ressources, besides the references, are embedded within the file (made possible by Costura), i either have to extract(*) them from that file, or pray that that file comes from an open source project? 

*(just saw that dnspy lets me save those embedded ressources, but how do i decompress them?)

**Comment by 0xd4d** [comment]
Seems like you got it working so closing it.

**Comment by rlesch** [comment]
> Seems like you got it working so closing it.

yes
, with il spy+plugin though. but woudnt it be cool, if dnspy could do that, too? :)

**Comment by 0xd4d** [comment]
Feel free to write an extension to do it.

**Comment by rlesch** [comment]
@0xd4d dont get me wrong, totally understand if its not in the scope of the project itself! 
just wanted to clearly clarify if an direct implementation could be considered or not. thats all.  
makes ofc more sense as extension esp due to the low demand. 
if itd be my field of expertise id alrdy implemented something and not asked :)


thanks for the taking the time to answer! appreciated!

(maybe the issue + infos here could be of help for someone else. )

**Comment by 0xd4d** [comment]
Yes it's because it's too specific, it only works with one type of packer. If it was more generic or supported many other things it would be a different matter. But that's a lot of work.

**Comment by Nemirtingas** [comment]
Went into this too, I ended making a lil extension as you suggested. It can't repack via the Context Menu right now, I'd like to load in-memory the extracted module to allow inline editing but that sounds tricky.
Here's my code: https://gitlab.com/Nemirtingas/Fody.Costura.Extractor.Extension
