### ISSUE TITLE
Decompile & compile errors

### ISSUE THREAD

**Issue by KyKyIIIKuH** [0xd4d/dnSpy#1011]
- What version did you use?
v5.0.10

- Write down all steps needed to reproduce this issue. Also attach any needed files.
1. File -> Open
2. I select the Assembly-CSharp.dll file
3. Choose {}
4. Going into MainMenu
5. I find the next line
"WWW purchaseBuy = new WWW (SettingsManager.ServerURL [0] + "PurchaseBuy.php", purchaseBuyForm);"
6. I click change method
7. Change " SettingsManager.ServerURL [0] + "PurchaseBuy.php" " to "http://lokalhost/PurchaseBuy.php"
8. I click to compile

An example of what happened to the code.
 It was:
1. string result = null;
2. ! Result.StartsWith ("error")

It became:
1. CS $ <> 8__locals1.result = null;
2. ! CS $ <> 8__locals1.result.StartsWith ("error")

because of this, the code is not compiled
What should be done to prevent this from happening?

File DLL
https://drive.google.com/open?id=1rFeIUPNRfi_00xQB7BBzhiTOpJ8PDOTp

**Comment by 0xd4d** [comment]
Looks like the code was compiled with eg. mcs but dnSpy uses Roslyn, and they generate different code. The decompiler doesn't seem to be able to handle that new code so it still shows some compiler generated names (eg. `<CS$<>......`).

If it's a very simple change you could try the IL editor instead since it doesn't recompile the whole thing.

**Comment by 0xd4d** [comment]
Since you didn't include all files I was unable to repro this and can't investigate further.

**Comment by KyKyIIIKuH** [comment]
added missing files
https://drive.google.com/open?id=1rFeIUPNRfi_00xQB7BBzhiTOpJ8PDOTp

**Comment by 0xd4d** [comment]
This is only a problem if you need to edit the method again. If you do you can simply fix the mistakes, this is what I did which worked for this particular method:

- `CS$<>8__locals1.result = null;` => `string result = null;`
- Use search and replace to remove all `CS$<>8__locals1.` (include the `.` too)
- Remove `CS$<>8__locals1 = null;` at the end of the method
- Remove `MainMenu.<>c__DisplayClass0_0 CS$<>8__locals1 = new MainMenu.<>c__DisplayClass0_0();`
