### ISSUE TITLE
'', hexadecimal value 0x06, is an invalid character.

### ISSUE THREAD

**Issue by Bluscream** [0xd4d/dnSpy#1017]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
5.0.9 from the link above (x64 on windows 10 pro x64)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
1. get [AGodZilla.zip](https://github.com/0xd4d/dnSpy/files/2682414/AGodZilla.zip) and open AGodZilla.exe in dnspy
2. use "File" -> "Export to Project"
3. It will give you an error:
![image](https://user-images.githubusercontent.com/3318223/50039405-4bb48f80-0032-11e9-8e6f-a7b346552e55.png)

**Comment by 0xd4d** [comment]
This assembly is obfuscated so you should deobfuscate it first.

**Comment by Bluscream** [comment]
So dnspy can only read plain code

**Comment by InlineAsm** [comment]
No dnspy can read the obfuscated source just fine. It can just not write illegal characters in a project file.

**Comment by 0xd4d** [comment]
The compiler would also not be able to parse the files since they contain random chars in type/member names instead of valid C# identifier chars.

**Comment by Bluscream** [comment]
> No dnspy can read the obfuscated source just fine. It can just not write illegal characters in a project file and it shouldn't because the project file would be useless.

So the executable i just decompiled is not executable?
