### ISSUE TITLE
How i can fix this

### ISSUE THREAD

**Issue by Broti** [0xd4d/dnSpy#1019]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)- What version did you use?

v5.0.10 (x46)
- Write down all steps needed to reproduce this issue. Also attach any needed files.
I dont know:
![screenshot_29](https://user-images.githubusercontent.com/45824264/50053826-94a43b00-013b-11e9-83ab-5a9d90404881.png)

LANG:German

**Comment by 0xd4d** [comment]
It just says that must rerun ngen.exe if the assembly is in the GAC. If you've edited some Unity assembly, it's 100% not installed in the GAC.

**Comment by Broti** [comment]
ok Thanks

Am So., 16. Dez. 2018 um 14:31 Uhr schrieb 0xd4d <notifications@github.com>:
