### ISSUE TITLE
Arabic left-to-right characters

### ISSUE THREAD

**Issue by CarlSchou** [0xd4d/dnSpy#102]
As seen [here](http://i.imgur.com/9HI69Uf.png) some arabic characters will mess up viewing of resources etc

**Comment by 0xd4d** [comment]
Can you copy and paste it?

**Comment by CarlSchou** [comment]
شمذمخشعنجقتارجزادلابفيذشقمبكصرجتليمبغفكجيظكدوتذززكاغعحولفدثلقوذكعافيصهاسبظرصظشعذفخهزردوههانذثغمهجاعهوعفبيسضصففنخفظثثبصرمثلوصرهشبسسعظوكرازجذهوففععقطذهصدمطدكتكغكوثذجببعصوزثعظشسزوخصجاخخضض

This string completely flips the amount of bytes to the left of the string as seen [here ](http://i.imgur.com/c188MdE.png)

**Comment by 0xd4d** [comment]
Should be fixed by abf91cddf4aac999a6cd6d280c42ce9b6f565026
