### ISSUE TITLE
Anyway to decrypt Unity encrypted files(not sure if it's actually encrypted) 

### ISSUE THREAD

**Issue by ATLaptic** [0xd4d/dnSpy#1022]
In the latest update for a game the developers made all of the types gibberish, I thought this was a game specific problem, then I saw another post or #940 having a similar thing and had no problem with it. Is there any program or feature in dnspy I can use to get past this or did the developers just spam on their keyboard. 
![weirder](https://user-images.githubusercontent.com/45983100/50191299-1f269f00-02e2-11e9-83e6-9369a2877d38.PNG)

**Comment by UlyssesWu** [comment]
You are not a big fan of Mr.0xd4d. You should try [de4dot](https://github.com/0xd4d/de4dot) ;)

**Comment by 0xd4d** [comment]
It's been obfuscated so use de4dot as said by @UlyssesWu to get some easier to remember names instead of random chars.

**Comment by ATLaptic** [comment]
Thanks :)
