### ISSUE TITLE
System.MissingFieldException: Field not found

### ISSUE THREAD

**Issue by RetiredQQ** [0xd4d/dnSpy#1024]
- What version did you use?
Version 5.0.65
- OS
Windows 10 Enterprise 2016 LSB
- Error
> http://oi64.tinypic.com/2znubdw.jpg
> I tried reinstalling all .NET Framework but still got this issue and other dnSpy build but still it wont work.

**Comment by 0xd4d** [comment]
Sounds like you don't have .NET Framework 4.7.2 installed. Get it from here: https://dotnet.microsoft.com/download/dotnet-framework-runtime

**Comment by RetiredQQ** [comment]
Solved. Currently Win 10 LSB is only supported .Net Framework 4.6.2

**Comment by 0xd4d** [comment]
You probably edited app.config. That won't work and can lead to crashes.

Time to update your OS?

**Comment by RetiredQQ** [comment]
Yupp it's fixed after I updated my OS thanks.
