### ISSUE TITLE
Thanks.

### ISSUE THREAD

**Issue by CoolOppo** [0xd4d/dnSpy#1026]
Hey sorry if this is wasting your time, just wanted to say THANK YOU!!!! All your work is seriously cool and is an inspiration for me as a programmer. I've been following the stuff you have put out for years and it's crazy to see you still going at it full speed. Seriously impressive stuff and I'm very grateful for everything you have done. That's all, keep up the great work, everything you do it very cool.

**Comment by 0xd4d** [comment]
Thanks, glad you like it!

**Comment by Kein** [comment]
Gonna use the opportunity to say thanks too. dnSpy was a damn invaluable tool for a few years :P
