### ISSUE TITLE
Command Line - How to search for a string in current member?

### ISSUE THREAD

**Issue by phamquangbaoplus** [0xd4d/dnSpy#1027]
Hello,

I run dnSpy.exe  file-path --select 0x06000262

Then how to search for a string in current member (0x06000262) in Command?

Some things like that: 

dnSpy.exe  file-path --select 0x06000262 --find string

Please tell me how to do it!

Thanks.

**Comment by phamquangbaoplus** [comment]
My mine is search for a full string like "PlayerPrefs.SetInt("TOTAL_BALL", 50);"

**Comment by phamquangbaoplus** [comment]
Great if DnSPY can replace string from Command

**Comment by 0xd4d** [comment]
It can't search for decompiled text, just type names, member names, strings etc.

**Comment by 0xd4d** [comment]
Wiki link, but I think you found it already: https://github.com/0xd4d/dnSpy/wiki/Command-Line-Arguments
