### ISSUE TITLE
Unicode in baml isn't shown correctly

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#1034]
v5.x.x

There is a problem with unicode characters that dnSpy does not show correctly.

![image](https://user-images.githubusercontent.com/14368203/50573475-7477ab80-0dcc-11e9-8a14-32b76eae7436.png)

//edit: Search problem solved (see edit). "Match whole words" needs to be unticked although I've searched for a whole word.

**Comment by 0xd4d** [comment]
How do I repro this?

**Comment by Symbai** [comment]
I believe its not unicode issue but that the character relies on a font embedded in a dll, which dnspy cannot display as it hasn't loaded the font. I've attached the dll, please take a look at it and let me know if there is anything you can do for it.

[repro.zip](https://github.com/0xd4d/dnSpy/files/2719690/repro.zip)

**Comment by 0xd4d** [comment]
If it requires you to install a font to view those chars you have to install it. There's nothing dnSpy can do about that.
