### ISSUE TITLE
How to ref dnlib now?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#1035]
Now, dnSpy use sdk project, and use nuget for dnlib.
If I create a new project in dnSpy solution, how to ref dnlib?

In the past, right click solution 'dnSpy' and create a new WinForm project, ref dnlib.csproj
When I update, there's no dnlib.csproj, so my plugin can't comipled, should I ref ../Debug/dnlib.dll?

**Comment by UlyssesWu** [comment]
I don't understand. Why can't you just use nuget to get dnlib on your WinForm project?

> PM> Install-Package dnlib

**Comment by CreateAndInject** [comment]
Do you mean:
1.Right click References, select 'Manage Nuget Packages.
2.Click 'Browse', input 'dnlib', and install dnlib 3.1

If I do it like this, when dnlib update to 3.2, can my project auto update to 3.2?

![1](https://user-images.githubusercontent.com/2529999/50585747-72d3e380-0eb1-11e9-9320-67903f2c523f.png)
![2](https://user-images.githubusercontent.com/2529999/50585754-78312e00-0eb1-11e9-90c2-18bcb309d2a0.png)

**Comment by UlyssesWu** [comment]
Just ignore "packages" folder in git (find a default `.gitignore` file for VisualStudio will help). Or switch to `PackageReference` if you're using VS2017.

> If I do it like this, when dnlib update to 3.2, can my project auto update to 3.2?

No, it will not be updated automatically. But you can install/update/uninstall it with nuget package manager.

**Comment by CreateAndInject** [comment]
I don't want to add unnessesary chagnes, I want to keep accordance with the author try my best.

I use PackageReference like this, but failed build also:
![4](https://user-images.githubusercontent.com/2529999/50587389-b41bc180-0eb8-11e9-8123-8ea940a0da9e.png)

**Comment by 0xd4d** [comment]
If you use the new SDK style projects you'll get that dnlib ref (and others) for free if you reference one of the dnSpy assemblies.

**Comment by Tianjiao** [comment]
My working build
`<PackageReference Include="dnlib" Version="3.1.0" />`

**Comment by CreateAndInject** [comment]
But how to use SDK projects?

I can't find the option to create sdk project in Visual Studio 2017.

**Comment by Tianjiao** [comment]
SDK is different from project. Say, you target netstandard2.0, then VS2017 will add it to you.
If you wanna reference your own project, just right-click on the main project, then select Add-Reference...

**Comment by 0xd4d** [comment]
> I can't find the option to create sdk project in Visual Studio 2017.

Just create a .NET Core app or a .NET Standard lib. Then edit the csproj and change TargetFramework to net471.

**Comment by CreateAndInject** [comment]
If I don't use sdk project, it can works with:
`<PackageReference Include="dnlib" Version="3.1.0" />`

I try to use:
```
<Import Project="..\..\..\DnSpyCommon.props" />
<PackageReference Include="dnlib" Version="$(DnlibVersion)" />
```
I will get the error:
`Your project file doesn't list 'win' as a "RuntimeIdentifier". You should add 'win' to the "RuntimeIdentifiers" property in your project file and then re-run NuGet restore.`

**Comment by Tianjiao** [comment]
> Just create a .NET Core app or a .NET Standard lib. Then edit the csproj and change TargetFramework to net472.

Not have to. Can be target to net472 from beginning. See pic
![netframework2](https://user-images.githubusercontent.com/1756057/50592502-55ae0d80-0ecf-11e9-95d0-75b54d667f84.png)


Change TargetFramework is not as easy as in config. Use the code analyzer beforehand.

Edit the config file needs a good editor. I use Atom myself.

**Comment by Tianjiao** [comment]
> I will get the error:
> `Your project file doesn't list 'win' as a "RuntimeIdentifier". You should add 'win' to the "RuntimeIdentifiers" property in your project file and then re-run NuGet restore.`

Add this line into the PropertyGroup of your TargetFrameworks
    `<RuntimeIdentifiers>win7-x64;win7-x86</RuntimeIdentifiers>`

**Comment by 0xd4d** [comment]
> Not have to. Can be target to net472 from beginning. See pic

That doesn't create a new SDK style project file, at least with VS 15.9.

@CreateAndInject

It's impossible to help you without more info such as your project file. Have a look at dnSpy's csproj files and you'll know what I use.

**Comment by Tianjiao** [comment]
> That doesn't create a new SDK style project file, at least with VS 15.9.
My bad. You're right.

I know what @CreateAndInject mean by the error message. He just lack of RuntimeIdentifier setting in his config. Maybe gives more time?

**Comment by CreateAndInject** [comment]
I can not build with:`<RuntimeIdentifiers>win7-x64;win7-x86</RuntimeIdentifiers>`
I can build with:`<RuntimeIdentifiers>win</RuntimeIdentifiers>'

But there're some problems:
1. There's no IntelliSence with dnlib types.
2. There's no dnlib icon in references and some warings with other references:
![9](https://user-images.githubusercontent.com/2529999/50594854-31efc500-0ed9-11e9-80df-d2ea6c2657b9.png)


What I mean is how to use the generic csproj format(not new sdk project) to ref dnlib.

I create ConsoleApp1(.net framework 4.7.2) in Extensions\Examples folder

Edit ConsoleApp1.csproj:
add 2 lines:
<Import Project="..\..\..\DnSpyCommon.props" />
<PackageReference Include="dnlib" Version="$(DnlibVersion)" />

It can't build
add another line after <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>:
<RuntimeIdentifiers>win</RuntimeIdentifiers>

It works now, but there're 2 problems as above.

**Comment by 0xd4d** [comment]
dnSpy uses the new SDK style projects, so you should to or you will get problems as you've already noticed. This is not a dnSpy issue, but a VS issue.

**Comment by Tianjiao** [comment]
Did you put
`using dnlib.DotNet;`
in the beginning of your code to use Intellisense?

If you use old csproj, set Version="3.1.0"
If you use sdk style csproj, you may add dnlib ref in VS2017, VS2017 will generate csproj for you.

**Comment by 0xd4d** [comment]
Another problem is that VS caches stuff in .vs and obj dirs that sometimes cause problems.

Seems like it works now.

**Comment by CreateAndInject** [comment]
It works with
`<PackageReference Include="dnlib" Version="3.1.0" />`
not
`<PackageReference Include="dnlib" Version="$(DnlibVersion)" />`

Maybe it's enough.

**Comment by 0xd4d** [comment]
It's because you're using the old csproj format which uses the old VS project system and it doesn't support that.
