### ISSUE TITLE
Ctrl + F5 Request

### ISSUE THREAD

**Issue by TheProxyRE** [0xd4d/dnSpy#1037]
When doing assembly invoking it should prompt us some warning message if file extension is not .exe
for example i accidentally executed malware even when it was renamed as .bit because i was working in parralel with visual studio and i clicked ctrl + f5 on dnspy and than it executed malware on my pc

**Comment by 0xd4d** [comment]
Do you want to send a PR for this?

You should also use a VM or some other computer to analyze malware.

**Comment by TheProxyRE** [comment]
Hmm i'm not into malware industry im creating deobfsucators and it happened that only test example i had was malware and i guess i was lazy to create vm for it. Happily assembly that was loaded into dnspy was corrupted so no damage was dealt but i think people should be aware that this can happen

**Comment by 0xd4d** [comment]
Yes I marked it as up for grabs if you want to fix it.

Ctrl+F5 and F5/F9 should check if it has an exe extension and aks if you want to debug/start it if it has no exe extension.

**Comment by SilentHammerHUN** [comment]
If I understood what you wanted correctly, here it is: https://github.com/0xd4d/dnSpy/pull/1046
