### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by GianisTsol** [0xd4d/dnSpy#1038]
linux support?

**Comment by 0xd4d** [comment]
No it's Windows only.

**Comment by Tianjiao** [comment]
You could try dnSpy without debugging feature on Linux/macOS, using Mono Runtime.
In fact, each system has its own Ring0 debugger.
Although dnlib has some PInvoke, dnSpy doesn't use them in decompiling.

**Comment by TheProxyRE** [comment]
Since dnspy is ported to .net core (https://github.com/0xd4d/dnSpy/tree/netcore3.0?files=1) I think you should be able to use console decompiler option but g r full gui you have to wait for wpf support for Linux in .net core

**Comment by flarn2006** [comment]
@0xd4d I'm pretty sure he knows it's Windows-only, hence why he posted this issue. :p
