### ISSUE TITLE
BAML

### ISSUE THREAD

**Issue by jayo2005** [0xd4d/dnSpy#104]
Is it possible to edit Baml. I've tried with no success

**Comment by 0xd4d** [comment]
It's not possible with the UI, but AFAIK, the BAML decompiler does have a writer so you could write your own code to do it.

**Comment by jayo2005** [comment]
Have you any information on the writer for the baml decompiler. I can save the raw baml from dnspy and open it it notepad++. It is unreadable in notepad++ but  I can change date formats and colours as those are readable. I can upload the edited baml the with dnspy and everything works. I just need a way to make the baml file fully editable. Ive decompiled the file and loaded it in visual studio but have to many errors to make a successful build. Ive designed the xaml the way I want it in visual studio and used msbuild but when I load the baml with dnspy it doesnt work. I think I just have to many errors in the decompiled code. If I can edit the baml with dnspy I would not need visual studio at all as the changes I am making are very small like removing effects on images  etc....

**Comment by 0xd4d** [comment]
See the BAML decompiler source code on how to edit it. A tip is also to have a look at the BAML disassembly (right-click and pick disassembly BAML).

**Comment by jayo2005** [comment]
I can't figure out how to edit the baml file at all. can you help?

**Comment by 0xd4d** [comment]
No, you have to study the code yourself until you understand it or ask someone else. I don't have time to help anyone use the code in dnSpy.
