### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by sndcode** [0xd4d/dnSpy#1043]
- What version did you use?
6
- Write down all steps needed to reproduce this issue. Also attach any needed files.
Download from buildserver , unzip to folder.
Start .exe 
https://puu.sh/CszMn/5972097796.png

**Comment by 0xd4d** [comment]
I've pushed a fix, let me know if it worked, you can get it here once it's built: https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts
