### ISSUE TITLE
Cannot open assembly explorer

### ISSUE THREAD

**Issue by CLAVIGERC3** [0xd4d/dnSpy#1047]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
v6.0.1

- Write down all steps needed to reproduce this issue. Also attach any needed files.
From fresh download, opening either the x86 or default executable results in no assembly explorer being open by default. Attempts to open via View > Assembly Explorer or the keyboard shortcut do not work.

**Comment by 0xd4d** [comment]
Maybe you dragged it all the way to the left so it's not visible even when it's open? You can try dragging it to the right again. Or you can also delete the old dnSpy.xml file from `%APPDATA%\dnSpy`

**Comment by CLAVIGERC3** [comment]
Dragging it to the right worked but there were only about 3 pixels of a column that were grabbable. Would it be possible to have a tab showing the open windows?

**Comment by 0xd4d** [comment]
Anything is possible it just requires someone to write it.

**Comment by B1GG5** [comment]
ctrl+alt+l opens the explorer
