### ISSUE TITLE
dnspy crash with a lot of string (protect) - solved with last build

### ISSUE THREAD

**Issue by T5ive** [0xd4d/dnSpy#1048]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
- 5.0.9.0
- Write down all steps needed to reproduce this issue. Also attach any needed files.
some .exe or .dll have protected with a lot of string for crash dnspy.
can add some option for decrease strings?

**Comment by 0xd4d** [comment]
Can you try the latest version?

**Comment by SilentHammerHUN** [comment]
Also attach the file that does this, so 0xd4d can have a look...
