### ISSUE TITLE
modify names of local variable and argument

### ISSUE THREAD

**Issue by tfrist** [0xd4d/dnSpy#1050]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
The latest version 6.0.2
- Write down all steps needed to reproduce this issue. Also attach any needed files.
I dont find a to modify names of local variable or argument like showing in the uploaded screenshot, whose names are obfuscated. so I need to modify them to meaningful. just like modifying function name.
![untitled](https://user-images.githubusercontent.com/232435/51285065-9a8f7500-19a2-11e9-8a6f-f089c5a60ed7.png)

Thanks.

**Comment by 0xd4d** [comment]
Locals are stored in the PDB file so won't be saved unless it has a PDB file (unlikely).

**Comment by 0xd4d** [comment]
You can edit locals in the IL editor and the args by editing the method (right click the method name and edit method)

**Comment by tfrist** [comment]
I'll try your way. Thanks 0xd4d

**Comment by tfrist** [comment]
sorry. I solved it myself, I need to save to module and reopen it.
