### ISSUE TITLE
Is there something wrong with variable name ,I find some Non-visible characters

### ISSUE THREAD

**Issue by yzpopulation** [0xd4d/dnSpy#1055]
![image 1](https://user-images.githubusercontent.com/12810531/51545282-9b417300-1e9c-11e9-8ab6-0672c7762af2.png)
The reason seems to be because>>>>[CompilerGenerated]

**Comment by 0xd4d** [comment]
What's the char? Paste this in the C# REPL, replace 'x' with the char you copy from the code.

```C#
((ushort)'x').ToString("X4")
```

**Comment by yzpopulation** [comment]
![image 2](https://user-images.githubusercontent.com/12810531/51680790-af60ae00-201d-11e9-8108-dbdf6289d542.png)

**Comment by 0xd4d** [comment]
It's http://www.fileformat.info/info/unicode/char/1782/index.htm so it seems the font doesn't support it and doesn't show anything.

**Comment by 0xd4d** [comment]
Actually it's supported as seen in your picture, you didn't show the same field as shown in the first picture.

**Comment by yzpopulation** [comment]
![image 3](https://user-images.githubusercontent.com/12810531/51688314-42eeaa80-202f-11e9-9419-c9f7a08d9877.png)
internal new bool  =>1708
private new spr\u19E7 ᜇ=>1707
internal bool ᜆ=>1706
Font is Consolas

**Comment by 0xd4d** [comment]
I can only reproduce invisible chars if I use Lucida Console, not Consolas.

**Comment by yzpopulation** [comment]
My first pic use NSimSun

**Comment by 0xd4d** [comment]
It repros with that font too. It doesn't repro with some other fonts so this seems to be a font issue not dnSpy issue.

**Comment by yzpopulation** [comment]
How do I modify the software for the current font to make him like this?
![image 4](https://user-images.githubusercontent.com/12810531/51688983-b2b16500-2030-11e9-8271-ae47e1710933.png)
ᜆ It seems \u170E
ᜆ It seems \u170F
ᜆ It seems \u1710
ᜆ It seems \u1711

**Comment by 0xd4d** [comment]
There's no such option, perhaps it could be useful. You can patch it yourself and compile it: https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy.Contracts.Logic/Decompiler/IdentifierEscaper.cs#L105
