### ISSUE TITLE
How can I run it in .net 4.0 only? Do you have a branch with .net 4.0 version?

### ISSUE THREAD

**Issue by davilimaalves** [0xd4d/dnSpy#1056]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?

- Write down all steps needed to reproduce this issue. Also attach any needed files.

**Comment by davilimaalves** [comment]
I use .net 4.0 and I want to integrate with a decompiler that runs on .net 4.0

**Comment by 0xd4d** [comment]
It only supports .NET Framework 4.7.2 or later and .NET Core 3.0.
