### ISSUE TITLE
Change locals value debug time

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnSpy#1057]
- What version did you use?
v6.0.2
- Write down all steps needed to reproduce this issue. Also attach any needed files.
I can't change value like: string, int value.

**Comment by 0xd4d** [comment]
Do you have a repro?

**Comment by 0xd4d** [comment]
.NET Framework or .NET Core, debug or release?

**Comment by bprg** [comment]
.NET Framework , Debug

**Comment by 0xd4d** [comment]
I can't repro it. It works as expected.

You can't change decompiler generated variables. You also can't change variables that have been optimized away, you'll get some message like this if that's the case:

`num	Cannot obtain value of the local variable or argument because it is not available at this instruction pointer, possibly because it has been optimized away.`

**Comment by bprg** [comment]
I don't have problem with change locals value in VS, I did not have this problem in the old version of DnSpy, Please see this screencast.

[Screencast.zip](https://github.com/0xd4d/dnSpy/files/2792391/Screencast.zip)

**Comment by 0xd4d** [comment]
Update your OS and restart it, delete `%APPDATA%\dnSpy\dnSpy.xml`, download dnSpy again and unpack it to a new directory.

**Comment by bprg** [comment]
I've repair .NET Framework but the problem was not resolved,
My OS is update : Win 10 Enterprise Ver 1809 OS Build 17763.195

**Comment by 0xd4d** [comment]
17763.292 is latest version see https://docs.microsoft.com/en-us/windows/windows-10/release-information

Test dnSpy in a VM, does it work?

You can also try reinstalling your OS and see if that helps. I don't know what else to do.

**Comment by 0xd4d** [comment]
BTW, have you tested 32-bit dnSpy too?

**Comment by bprg** [comment]
I've install latest version 17763.292 on VM still the problem was not resolved also test 32-bit not works.

**Comment by 0xd4d** [comment]
Which old version worked? Does this 6 month old build work: https://ci.appveyor.com/project/0xd4d/dnspy/builds/17794027/artifacts

**Comment by bprg** [comment]
This version still not work, I did it in old versions but I do not remember the version.

**Comment by 0xd4d** [comment]
You can try compiling it yourself, here are some versions:

6ed77d45b 3.0.0

d46b0d8e1 4.0.0

cd7dfdf60 4.5.0

e1f3426d0 5.0.0

**Comment by bprg** [comment]
Is hard to compile old version because I do not know which version of the library is compatible with old versions.

**Comment by 0xd4d** [comment]
This should work when you're in the dnSpy folder. Replace `XXXXX` with the commit hash, eg. `6ed77d4`, see above

```sh
git checkout XXXXX
git submodule update
```

Now you can build it.

**Comment by 0xd4d** [comment]
1.5 is ancient, try compiling 3.0 above.

**Comment by bprg** [comment]
dnSpy Ver 3.0.2 works but Ver 4.5.2 not works.

**Comment by 0xd4d** [comment]
Can you test these:

- 64b36984: https://ci.appveyor.com/project/0xd4d/dnspy/builds/21907815/artifacts
- cd7dfdf6: https://ci.appveyor.com/project/0xd4d/dnspy/builds/21907799/artifacts

**Comment by bprg** [comment]
Both did not work.

**Comment by 0xd4d** [comment]
Not reproducible.
