### ISSUE TITLE
Please add dump and watch possibility for internal static class members

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [0xd4d/dnSpy#1058]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
lastest build
- Write down all steps needed to reproduce this issue. Also attach any needed files.
In following situation debugger does not give any opportunity to watch on internal class structure created in ctor.
Small example : 
```
internal class Class1
{
    static Class1()
    {
      Class1.byte_0 = new byte[]
      {
        1,
        2,
        3,
        4,
        6
      }
      for (int i = 0; i < Class1.byte_0.Length; i++)
      { 
        Class1.byte_0[i] = (byte)((int)Class1.byte_0[i] ^ 238);
      }
    }
  internal static byte[] byte_0;
}
```

During execution such constructor in locals will be only variable "i" and currently no opportunity to look on changes in Class1.byte_0 during execution.

**Comment by 0xd4d** [comment]
Use the watch window and add the expression, eg. `Class1.byte_0`. If it complains, add the namespace too.

**Comment by jpVm5jYYRE1VIKL** [comment]
Yes. it is works, thanks. Is it possible somehow automatically detect such class members because manually addition sometimes little bit long and tedious job.

**Comment by 0xd4d** [comment]
That's what the autos window should do, once I add the code.
