### ISSUE TITLE
Decompile error - Object reference not set

### ISSUE THREAD

**Issue by jayo2005** [0xd4d/dnSpy#106]
I am getting an error decompiling a file.

description = Decompile BAML, Exception message: Object reference not set to an instance of an object.

**Comment by 0xd4d** [comment]
Email me the file and I'll have a look. The email address can be found in Help -> About

**Comment by 0xd4d** [comment]
Should be fixed in [the latest build](https://ci.appveyor.com/project/0xd4d/dnspy/build/artifacts)
