### ISSUE TITLE
getting stuck at decompiling a class

### ISSUE THREAD

**Issue by tfrist** [0xd4d/dnSpy#1060]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
v 6.0.2
- Write down all steps needed to reproduce this issue. Also attach any needed files.
I uploaded the screenshot of when it gets stuck.  It happens when you click on "Class1", "Class2" or others. The target file is inside file "CrachMe-J4-cleaned.zip". 

![untitled](https://user-images.githubusercontent.com/232435/51704782-c1ffc680-1fce-11e9-9a7d-ea22a1ad9048.png)
[CrackMe-J4-cleaned.zip](https://github.com/0xd4d/dnSpy/files/2793354/CrackMe-J4-cleaned.zip)

**Comment by 0xd4d** [comment]
Click each method in Assembly Explorer until it takes too long to decompile it. Switch to IL view and check how big that method is.

**Comment by tfrist** [comment]
Hi 0xd4d,
I did not debug it. just did static analysis.   I don't know how to switch IL view. 
Today I debugged it, cause I know there is a "Edit IL Instruction" in popup menu item, it probably is what you said IL view, sorry i'm newbie to dnSpy.  I set a break on a function (in Main function, Line 33 Class2.smethod_0(Class3.int_0,2);) who causes stuck too.  Once it breaks and I press "F11" to step into it where I can switch to IL view, but now dnSpy runs to "Not Responding".  see my uploaded screenshot.Thanks.
![not_responding](https://user-images.githubusercontent.com/232435/51767234-9691e000-2091-11e9-999b-5127838ecbcd.png)

**Comment by tfrist** [comment]
I also tried this, "Edit method body" from popup menu, after a short while I got this exception message
![exception1](https://user-images.githubusercontent.com/232435/51767550-9c3bf580-2092-11e9-8322-5a238ca6e2b4.png)
.

**Comment by tfrist** [comment]
One function "Class2.smethod_1(int)" who causes stuck.  However, after performing "Edit Method Body" on it, the IL code window finally appears, which takes long time (about 25 secs). The last line number is 31297.
Does this one count a huge function?
![fun_body](https://user-images.githubusercontent.com/232435/51768475-49b00880-2095-11e9-8a87-a6bd930026ae.png)

**Comment by 0xd4d** [comment]
Yes that's a pretty big method, and could possibly explain the problems you're having.

**Comment by 0xd4d** [comment]
Use the IL editor if it's a big method like this.
