### ISSUE TITLE
Viewing source code

### ISSUE THREAD

**Issue by EricWal** [0xd4d/dnSpy#1062]
Hello, is this kinda of issue?

- I use version v6.0.3 which is the latest version.

- Each time when I try open the "Assembly-CSharp.dll" with dnSpy it doesn't open source code of the "-" contents such as game methods and classes, instead it show up only 1 class which is called "<Module>" and it supposed to be more than that.

Like seen in the following picture:

![capture](https://user-images.githubusercontent.com/18052628/51748816-a247cb80-20be-11e9-9956-32097b407aa3.PNG)

Kind regards.

**Comment by 0xd4d** [comment]
what happens if you change the language from C# to IL, do you see all classes?

**Comment by EricWal** [comment]
Thanks for reply,

When I change the language from C# to lL i still cannot see the hidden classes. 

As seen in this picture:
![capture](https://user-images.githubusercontent.com/18052628/51756066-34f16600-20d1-11e9-9a2f-29b988144af2.PNG)

Kind regards.

**Comment by 0xd4d** [comment]
Select the "-" namespace, do you see any classes?

**Comment by EricWal** [comment]
No, i don't see any classes in lL mode.

**Comment by 0xd4d** [comment]
That means the developers know how to use the `namespace` keyword. :smile:

The class you're looking for is in another namespace.

**Comment by EricWal** [comment]
Thanks for reply sir,

One Last thing regarding search feature, since it doesn't show game methods do you mean i should use dnSpy with different dll file other than `Assembly-CSharp.dll`?

is that what you meant with your previous reply about anther namespace?  

I appreciate your time.
Kind regards.
