### ISSUE TITLE
Don't delete published releases

### ISSUE THREAD

**Issue by pravic** [0xd4d/dnSpy#1063]
Otherwise those, who are subscribed to "Release only" notifications, won't be able to "Mark as read" them.

**Comment by 0xd4d** [comment]
Seems like a github bug, you should contact them.

**Comment by SylwesterZarebski** [comment]
I would also like to have access to old releases. Now only way to download old release is searching through web to find some not really trustable sites.

What is the reason to delete old releases?

**Comment by LuisTAC** [comment]
First of all, thanks for making this great tool available for us all.
Having access to old releases would be greatly appreciated! Right now I need a .NET Framework 4.7 compatible version and downloading from other sites isn't really a possibility.

**Comment by 0xd4d** [comment]
Use the .NET Core 3.1 builds instead, eg dnSpy-netcore-win64.zip
