### ISSUE TITLE
CompositionFailedException when running dnSpy

### ISSUE THREAD

**Issue by xoofx** [0xd4d/dnSpy#1065]
Hey,

i'm trying to build from the latest master and run dnspy from VisualStudio, but I'm hitting the following assert `CompositionFailedException`

![image](https://user-images.githubusercontent.com/715038/51774352-4a2abc80-20f2-11e9-80ae-c92c92d5df07.png)

Is it a known issue or Am I doing something wrong?

**Comment by 0xd4d** [comment]
Not sure what's happening here because both impls are in the same assembly and works for me (TM). What's the error in the `[0]` element?

Could you delete all obj and bin dirs or re-clone it to a new dir? Also try removing `%LOCALAPPDATA%\dnSpy`

**Comment by xoofx** [comment]
Ok, I clean and rebuild everything and it is working... likely I hadn't done a full rebuild and it was missing some extensions that don't have a direct project reference.

**Comment by 0xd4d** [comment]
Tools -> Options -> Projects and Solutions -> Build and Run -> uncheck "Only build startup projects and dependencies on Run"

That will make sure all extensions are also built if you press F5. Otherwise VS will only build dnSpy.exe.

**Comment by xoofx** [comment]
Yeah I know, but I rarely develop with libs requiring dynamic plugins, so I prefer the default, I just need to be careful with dnspy! 😅
