### ISSUE TITLE
System.InvalidProgramException error

### ISSUE THREAD

**Issue by DaftOdyssey** [0xd4d/dnSpy#1066]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
dnSpy v6.0.3 32 - Bit
- Write down all steps needed to reproduce this issue. Also attach any needed files.
1. Go to module -> .cctor and place a breakpoint just after the first call 
![image](https://user-images.githubusercontent.com/8892812/51813933-6a878200-227e-11e9-9d18-adf9806b1e25.png)

2. Debug the exe and open module from memory
3. Go again in module -> .cctor and nop the two first calls 
Results:
![image](https://user-images.githubusercontent.com/8892812/51813985-b20e0e00-227e-11e9-8dea-661201be3b52.png)

4. Saved module using these settings:
![image](https://user-images.githubusercontent.com/8892812/51813871-1aa8bb00-227e-11e9-8b28-cd14e6e3f105.png)
Get this error after saving:
![image](https://user-images.githubusercontent.com/8892812/51814095-46787080-227f-11e9-9754-cbb30d5a4cc2.png)

5. I open the new module, and I get this error after debugging:
![image](https://user-images.githubusercontent.com/8892812/51814142-80497700-227f-11e9-98ae-f4a0679d305f.png)

**Comment by 0xd4d** [comment]
Looks like Decrypt() contains invalid IL or references some bad metadata or something. What does the IL look like. Verify that it's valid.

**Comment by sanjeevspr** [comment]
i m also facing this issue after edit the dll
