### ISSUE TITLE
GUI render issues (.net core)

### ISSUE THREAD

**Issue by PascalKoe** [0xd4d/dnSpy#1067]
Hello,
the GUI disappears or makes weird zooms. Could trigger this problem easily by selecting text with the mouse or hover over the assembly editor. Sometimes even the whole GUI went dark gray until resized the window. The .NET 4.7.? version works fine for me so far.
Thanks for your awesome work!
Pascal

Version: dnSpy v6.0.3 (.NET Core) 64bit
OS: Win 10 Education 10.0.17763 Build 17763
System: Intel Core i9-9900k using Intel UHD Graphics 630 (Driver 24.20.100.6291)

![image](https://user-images.githubusercontent.com/15944057/52087721-7fc81d80-25aa-11e9-8c05-a6925855c14a.png)
![image](https://user-images.githubusercontent.com/15944057/52087835-c87fd680-25aa-11e9-9ab3-7728799b8dea.png)

**Comment by 0xd4d** [comment]
That's weird. I can't repro it though.

Does it always happen when you select text? Or just randomly?

What about the treeview, does it always happen when hovering over something or just randomly?

**Comment by 0xd4d** [comment]
BTW, it looks like a WPF for .NET Core bug

**Comment by PascalKoe** [comment]
When selecting text it happens at least 60% of the time in the form of flickering while dragging the mouse but I can't find any specific way when it always happens. When using the keyboard to select text I wasn't able to observe this bug. Another thing I noticed is that when selecting text within a line this never happens.

In the tree view I noticed if you are hovering slow up and down there is no problem but if you go up and down over two (or more but then fast) entries repeatedly it happens quiet consistent.

The only completely consistent place I've found so far is the option window. The controls which have some sort of hovering effect consistently disappear but only if they aren't in a Group Box(?) like seen in the picture. Again the treeview in the options window is the same as the Assembly Explorer.

The items in the menu bar go away when hovering and going back and forth. The elements which don't have any hovering effect (deactivated buttons or the dividers don't suffer).

When a drop down menu of the menu bar is open hovering between the menu bar doesn't do anything as well as hovering back and forth within the drop-down menu

The tab controls also vanish when hovering back and forth.

And yes probably a bug of WPF for .NET Core. Do you know any other applications that already use WPF with .NET Core so I can test if they suffer the same problem on my system?

Going to test on a different windows installation with the same hardware...

![](https://user-images.githubusercontent.com/15944057/52149634-aa2edf00-266d-11e9-9888-2697255c025c.png)

![](https://user-images.githubusercontent.com/15944057/52148571-68e90000-266a-11e9-9a94-aeec3b0a47d6.png)

**Comment by 0xd4d** [comment]
I only know of one: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/releases

I think it uses .NET Core 3.0 Preview 1.

**Comment by 0xd4d** [comment]
Closing this one since it's a .NET Core bug.
