### ISSUE TITLE
Attach dialog doesn't show .NET Framework 1.1

### ISSUE THREAD

**Issue by rweijnen** [0xd4d/dnSpy#1068]
I know that .NET 1.1 isn't officially supported as not much people use it anymore but unfortunately I need to troubleshoot old .NET 1 applications (without source) and dnSpy is the best tool available to do it.

The attach process dialog however doesn't show .NET 1 processes, only v2 and higher, is it possible to change this or add an option to manually enter a PID ?

**Comment by UlyssesWu** [comment]
See #843 #618 .

.NET 1.1 is not supported.

**Comment by 0xd4d** [comment]
Even if you hack dnSpy it probably won't work since the debugger APIs won't work correctly if called by managed code.

https://blogs.msdn.microsoft.com/jmstall/2004/11/02/problems-for-a-managed-debugger-for-v1-1/

If you can create a loader (targetting .NET 2 or 4) that calls the entry point, you could debug it.

**Comment by rweijnen** [comment]
Strangely enough the debugger appears to work fine if I launch the same exe via the Debug Start Process option but I'm just missing the attach option. You are quite right that the debugger might fail or work imperfectly later on but anything is better than nothing at this point for me. Loader might be a good alternative but I guess the application will then work with the v2 runtime instead and might behave differently? If there would be a quick hack to attach to v1 process or as I mentioned manually enter pid that would be a great option!

**Comment by 0xd4d** [comment]
I have zero plans to support .NET Framework 1.x. The source is there so you could add that support yourself if you need it and the workaround doesn't work.
