### ISSUE TITLE
Missing compiler required member 'System.Security.Permissions.SecurityPermissionAttribute..ctor'

### ISSUE THREAD

**Issue by 241d2** [0xd4d/dnSpy#1069]
- What version did you use? 6.0.3 from Artifacts

- Write down all steps needed to reproduce this issue. Also attach any needed files.
When I edit any methods example OnCreate(), I always get following errors

```
Severity	Code	Description	File	Line
Error	CS1729	'MethodImplAttribute' does not contain a constructor that takes 1 arguments	main.g.cs	33
Error	CS0656	Missing compiler required member 'System.Security.Permissions.SecurityPermissionAttribute..ctor'		
```
I tried adding this code https://github.com/0xd4d/dnSpy/issues/759#issuecomment-371488617 but still error 

The dll is Xamarin based though...

[assemblies.zip](https://github.com/0xd4d/dnSpy/files/2824655/assemblies.zip)

**Comment by 241d2** [comment]
I don't know how shouldor where to write that but I ended up removing generated code and it works. Game still work fine
```
[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.Synchronized)]
		protected static int GetFastToken(global::Gameloft.Aspects.FastTokenKey fastTokenKey, int level)
		{
			return default(int);
		}
```

**Comment by 0xd4d** [comment]
The method above is synchronized so if you remove the attribute, it won't be synchronized anymore and could crash at runtime. Here's the attribute:

```C#
using System;
using System.Reflection;
using System.Runtime.InteropServices;

namespace System.Runtime.CompilerServices
{
	[AttributeUsage(AttributeTargets.Constructor | AttributeTargets.Method, Inherited = false)]
	public sealed class MethodImplAttribute : Attribute
	{
		public MethodImplAttribute(MethodImplOptions methodImplOptions) { }
		public MethodImplAttribute(short value) { }
		public MethodImplAttribute() { }
	}
}
```
