### ISSUE TITLE
Strange OpenFileDialog

### ISSUE THREAD

**Issue by TheProxyRE** [0xd4d/dnSpy#107]
SInce i installed custom theme on my Windows7 openfiledialog is strange

http://prntscr.com/aoru0q

Whindows theme i use: http://zainadeel.deviantart.com/art/Shine-2-0-for-Windows-7-172671190

**Comment by 0xd4d** [comment]
dnSpy just doesn't modify the dialog in any way, it just calls a standard .NET Framework method to show it. There could be a registry setting that is corrupted or it's just your new theme that's buggy.
