### ISSUE TITLE
Crash when opening the CallStack window - TypeResolveException

### ISSUE THREAD

**Issue by MoaidHathot** [0xd4d/dnSpy#1070]
I'm attaching dnSpy v6.0.3 to a UWP app to catch an exception. Then when dnSpy breaks on the line that throws the exception, I try to view the CallStack window, which in return causes dnSpy to crash.

It opens a lot of windows about TypeResolveException before it crashes.
![image](https://user-images.githubusercontent.com/8770486/52175751-37c71780-27b1-11e9-9ec9-9285d13c2b3b.png)

The CallStack window was opened by me before attaching to the process.

Architecture: x64
dnSpy version: v6.0.3.
App Type: UWP (x64)
Note: Does not reproduce with dnSpy 4.x

**Comment by 0xd4d** [comment]
It's probably because the assembly resolver can't find the WinMD assemblies.

**Comment by MoaidHathot** [comment]
Thanks for your quick response :)
Sometimes this window will keep appearing (more than 7 times at the same time) before dnSpy crashes.
The Issue is marked as Up for grabs, which is great. Could you please elaborate more on what is needed to fix this issue? I would like to help and implement it if I can.

Thanks!

**Comment by MoaidHathot** [comment]
Ok, I'll try it. Thanks!

**Comment by 0xd4d** [comment]
This has already been fixed.
