### ISSUE TITLE
Feature: filter in output window

### ISSUE THREAD

**Issue by dnet** [0xd4d/dnSpy#1071]
The output window is a sink used by many incoming streams of information, including

 - unhandled exceptions
 - starting and exiting threads
 - loading .Net assemblies
 - printing text from breakpoints

I found the latter use-case quite useful, however, all the other sources including those above can drone out that one or two lines I really care about. There are multiple solutions for this problem, for instance, such sources could each have a button on the toolbar right above the output window to toggle them. Or a single text box would be simple and versatile, as one could add a unique string to the printed text in the breakpoints and enter that common substring into the filter box.

**Comment by 0xd4d** [comment]
Right-click inside it to open the context menu and you can disable those messages you don't want to see.
