### ISSUE TITLE
Attach to Process not decompiling/showing any thing!

### ISSUE THREAD

**Issue by GameHackerPM** [0xd4d/dnSpy#1075]
I was trying the "Attach to process" feature, when I attached to .net running program, it didn't decompile the file and show me the codes so I can navigate/put breakpoints ..etc! I don't know if that is a bug or just a missing feature, but would assume that the behavior should be what I'm saying, when I attach to a process, it should decompile the file itself so I can put breakpoints in it ...etc!

![image](https://user-images.githubusercontent.com/7836215/52532975-7753ad80-2d35-11e9-8c0e-8abec44ce0d2.png)

Version used: v6.0.3 latest build!
OS: Windows 10

Thanks.

**Comment by 0xd4d** [comment]
When you attach to a process, it only attaches to it. It doesn't open all modules. If you want to open all modules, go to Debug -> Windows -> Modules and then right-click in it and click 'open all modules'.

**Comment by GameHackerPM** [comment]
Thanks, didn't know that! ^^ Closed <3
