### ISSUE TITLE
compile error without any edits!

### ISSUE THREAD

**Issue by newbreedsoftware** [0xd4d/dnSpy#1079]
dnSpy version: v4.0.0

So I am facing an error when I  simply decompile a class file and try to compile it back together without making any changes! Any suggestions/ideas would be much appreciated.

Youtube video: https://youtu.be/m0cWrA8fxks
![blah](https://user-images.githubusercontent.com/28799062/53055357-3efe4e80-345c-11e9-8d59-d0a6580035c9.jpg)

**Comment by 0xd4d** [comment]
Try the latest version

**Comment by newbreedsoftware** [comment]
> 
> 
> Try the latest version

I feel stupid for not thinking of that first! Thank you for your help, updating to v6.0.3 resolved my issue,
