### ISSUE TITLE
Debug shows nothing

### ISSUE THREAD

**Issue by Lord-Mustang** [0xd4d/dnSpy#1082]
- Version v5.0.5

I'm trying to debug a Unity release build. I've replaced mono.dll with the patched .dll, 64bit. I need to use the Unity (Connect) method for debugging, because the application cannot be run by running the executable. I've also added the environment variable and kept the port to default.

Debugging seems to work fine. There's no connection errors while the game is running, but there is no output in the 'locals' viewport either. Am I doing something wrong?

**Comment by Lord-Mustang** [comment]
I have now updated to v6.0.4 and converted the game to debug build. Using Attach to process (Unity) I can attach fine, but again no output in the locals window unfortunately.

**Comment by 0xd4d** [comment]
You can only see locals if the app is paused and if the current method has locals.
