### ISSUE TITLE
Resizing bug

### ISSUE THREAD

**Issue by AHOHNMYC** [0xd4d/dnSpy#1083]
v6.0.3

I'm not good at description, just look at the bottom of these screenshoths.
Text is cutted, and if we resize window in points where cursor located (drag down on 1st image. Or drag up on 2nd image), subwindow continue losing it's bottom.

![](https://user-images.githubusercontent.com/24810600/53292643-8d9e4680-37d6-11e9-8218-d9cf920d3c99.png)

![](https://user-images.githubusercontent.com/24810600/53292642-8d05b000-37d6-11e9-9918-d64f31bafe7a.png)

**Comment by 0xd4d** [comment]
Looks like a WPF bug/feature.

**Comment by AHOHNMYC** [comment]
Hm. I have tried same on VS2019, which is build on WPF.
In first case, subwindow resized correctly with main window without glitches.
In second case, instead of instant subwindow resizing VS showed me small separator window (like [this](//wpf-tutorial.com/panels/gridsplitter)).
It looks like more expected behavoiur.

**Comment by 0xd4d** [comment]
When you drag the tool window up/down, WPF code executes and resizes the window. Send a PR if you think it's important to fix.
