### ISSUE TITLE
less of bug, more of "what do i do"

### ISSUE THREAD

**Issue by Wubly** [0xd4d/dnSpy#1085]
i accidentally closed the windows and i don't know how to get them back. what do i do?

**Comment by 0xd4d** [comment]
If it's Assembly Explorer: View -> Assembly Explorer (or Ctrl+Alt+L)

**Comment by 0xd4d** [comment]
You can also try deleting/renaming dnSpy.xml in this dir: %APPDATA%\dnSpy
