### ISSUE TITLE
Cannot recompile Steam Game ..Starcrawlers..using/because of Boo.Lang.Dll

### ISSUE THREAD

**Issue by peddroelm** [0xd4d/dnSpy#1087]
any hope with this ? from  Steam game  Starcrawlers using .. 

[assembly: AssemblyVersion("2.0.9.5")]
[assembly: AssemblyTitle("boo - an extensible programming language for the CLI")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("boo - an extensible programming language for the CLI")]
[assembly: AssemblyCopyright("(C) 2003-2007 Rodrigo Barreto de Oliveira")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyDelaySign(false)]
[assembly: AssemblyKeyFile("../src/boo.snk")]
[assembly: AssemblyKeyName("")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: RuntimeCompatibility(WrapNonExceptionThrows = true)]

```
	// Token: 0x02000CCB RID: 3275
	[global::System.Runtime.CompilerServices.CompilerGenerated]
	[global::System.Serializable]
	internal sealed class $CreateList$14409 : global::Boo.Lang.GenericGenerator<object>
	{
		// Token: 0x06004432 RID: 17458 RVA: 0x0002FD02 File Offset: 0x0002DF02
		public $CreateList$14409(global::System.Collections.Generic.List<global::Effect> e, global::UI_EffectLongList self_)
		{
		}

		// Token: 0x06004433 RID: 17459 RVA: 0x0002FD18 File Offset: 0x0002DF18
		public override global::System.Collections.Generic.IEnumerator<object> GetEnumerator()
		{
			return default(global::System.Collections.Generic.IEnumerator<object>);
		}

		// Token: 0x040051E2 RID: 20962
		internal global::System.Collections.Generic.List<global::Effect> $e$14417;

		// Token: 0x040051E3 RID: 20963
		internal global::UI_EffectLongList $self_$14418;
	}
}

```

dnSpy (6.0.3.0)
	Copyright (C) 2014-2019 de4dot@gmail.com

	dnSpy.Debugger.DotNet (6.0.3.0)
	Copyright (C) 2014-2019 de4dot@gmail.com
	.NET Debugger

	dnSpy.Debugger.DotNet.Mono (6.0.3.0)
	Copyright (C) 2014-2019 de4dot@gmail.com
	Debugger (Mono, Unity)

	dnSpy.Scripting.Roslyn (6.0.3.0)
	Copyright (C) 2014-2019 de4dot@gmail.com
	Scripting

	dnSpy.Debugger (6.0.3.0)
	Copyright (C) 2014-2019 de4dot@gmail.com
	Debugger

	dnSpy.AsmEditor (6.0.3.0)
	Copyright (C) 2014-2019 de4dot@gmail.com
	Assembly editor

	dnSpy.Analyzer (6.0.3.0)
	Copyright 2011-2014 AlphaSierraPapa for the SharpDevelop Team
	Analyzes assemblies

	dnSpy.Debugger.DotNet.CorDebug (6.0.3.0)
	Copyright (C) 2014-2019 de4dot@gmail.com
	Debugger (.NET Framework, .NET Core)

	dnSpy.BamlDecompiler (6.0.3.0)
	Copyright © Ki 2015
	BAML decompiler

	dnSpy.Decompiler.ILSpy (6.0.3.0)
	Copyright 2011-2014 AlphaSierraPapa for the SharpDevelop Team
	ILSpy decompiler

**Comment by 0xd4d** [comment]
Make sure boo.lang.dll is found. All refs should be in the same folder as the file you're editing or you can drag and drop them to assembly explorer.
