### ISSUE TITLE
Can't decompile class

### ISSUE THREAD

**Issue by DecodeMehh** [0xd4d/dnSpy#1088]
- What version did you use?
6.0.3
- Write down all steps needed to reproduce this issue. Also attach any needed files.
I was trying to open a class (obfuscated)
![issue](https://i.imgur.com/DFnSCRw.png)

**Comment by greenozon** [comment]
Looks like you hit similar case as I have got recently - 
#1086

**Comment by DecodeMehh** [comment]
> Looks like you hit similar case as I have got recently -
> #1086
> 
> BTW, what is the SW that draws these funny big points to the left? (over class tree view panel)

I used the tool ShareX to make this screen.

**Comment by ddf420** [comment]
Can you use any PE detectors to tell what obfuscator the assembly uses? Normally, most obfuscated assembly can be decompiled by dnspy.

**Comment by xsilent007** [comment]
@DecodeMehh Can you upload the assembly you opened in dnSpy? I'll try to have a look maybe...

**Comment by 0xd4d** [comment]
It's not possible to repro it without more info.
