### ISSUE TITLE
[Feature Request] Compare 2 assemblies decompiled to find what was changed

### ISSUE THREAD

**Issue by veso266** [0xd4d/dnSpy#1089]
Hi What I would realy like to see in dnSpy would be a way to compare 2 net assemblies to find what function was patched/changed, something like you can do with Beyond Compare but for Decompiled files

Thanks for creating a great program and Best Regards

**Comment by Symbai** [comment]
Is already requested https://github.com/0xd4d/dnSpy/issues/719

**Comment by 0xd4d** [comment]
Dupe
