### ISSUE TITLE
Can add "break on return" like "Execute till return" in OllyDbg?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#109]
Can add "break on return" like "Execute till return" in OllyDbg?

by the way, in dnSpy, Step Over = 跳出, Step Out = 逐过程
it should be:Step Over = 逐过程, Step Out = 跳出

**Comment by 0xd4d** [comment]
What's wrong with just Step Out?

If you wish to fix those translations, then use https://crowdin.com/project/dnspy

**Comment by CreateAndInject** [comment]
Sometimes there are so many returns in one method, so I want to know which one the method returned from.

**Comment by UlyssesWu** [comment]
I'm sorry for that translation. It's a mistake by me. I will remove that wrong translation.

**Comment by UlyssesWu** [comment]
I've modified [those translations](https://crowdin.com/translate/dnspy/all/en-zhcn#q=Step+Over) and I guess it would be correct in next version.

也欢迎你对翻译的不当之处作出修改。

**Comment by 0xd4d** [comment]
Step Out is close enough, so I'm closing this.
