### ISSUE TITLE
Debugger - View static values

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#1090]
When debugging and stepping through code that accesses a static property like this:

```
if (!MyStatic.Static.MyProperty || flag)
{
	...
}
```
Where MyStatic is declared as this
```
public new static MyStatic Static
{
	get
	{
		return (MyStatic)MyStatic.Static;
	}
	internal set
	{
		MyStatic.Static = value;
	}
}
```
I cannot see / change the value of MyProperty in locals window. Step into does not help as it steps over the getter. Is there a way to achieve this or if not, can this be added?

**Comment by greenozon** [comment]
Locals is for local vars only!
have you tried Watch window?

example: 
http://prntscr.com/mvflns

**Comment by 0xd4d** [comment]
Watch window can do this.
