### ISSUE TITLE
Anti anti-debug conflict?

### ISSUE THREAD

**Issue by BeHappy559** [0xd4d/dnSpy#1094]
When I use dnspy's anti anti-debug function, the program can't be debugged properly. Is it because the hide peb>BeingDebugged member conflicts with clr? The version is 6.0.3!
If so, can you try to provide dnspy plugin development?
 Let me write the plugin in C language, thank you!

**Comment by XenocodeRCE** [comment]
"- Write down all steps needed to reproduce this issue. Also attach any needed files."

Where is the needed file ? We can't reproduce it, at least i cant

**Comment by BeHappy559** [comment]
I found the problem, because the ZwSetInformationThread function hides the debugging information, can increase the hook of this function?

**Comment by 0xd4d** [comment]
Reopen when you have a repro.
