### ISSUE TITLE
Internal debugger error: Cannot see local variables

### ISSUE THREAD

**Issue by BrunoMCBraga** [0xd4d/dnSpy#1095]
Hello, 

I have seen this reported before and i have disabled breakpoints as suggested on other issues. Still no luck. The sample:

f7e317641a147679ce74fb3a2edd23378ebd3f3afff0595946d0c0536fd0454a : https://www.virustotal.com/#/file/f7e317641a147679ce74fb3a2edd23378ebd3f3afff0595946d0c0536fd0454a/detection

Version: 6.0.3

Simply loading this sample on dnspy and debug it, nothing is shown on Local Variables window. Reports internal error.

Thanks in advance

**Comment by 0xd4d** [comment]
I can't repro anything without a binary.

You can debug dnSpy itself (either in VS or dnSpy) and break when an exception is thrown and post the stack trace here.

**Comment by BrunoMCBraga** [comment]
You don't have access to VT?

**Comment by piratesephiroth** [comment]
virustotal isn't a file hosting service

**Comment by BrunoMCBraga** [comment]
http://s000.tinyupload.com/index.php?file_id=51325686318192718376

**Comment by BrunoMCBraga** [comment]
Password is infected.

**Comment by 0xd4d** [comment]
Do you have the stack trace?

**Comment by BrunoMCBraga** [comment]
I am not sure how can the stack trace help more than loading the binary directly on dnspy and see the variables window showing errors :/

**Comment by 0xd4d** [comment]
start dnSpy. Debug a new dnSpy exe. Go to exception settings in dnSpy copy 2 and enable every exception. Debug the malware in the 2nd dnSpy copy. You should see some exception getting thrown somewhere.

**Comment by BrunoMCBraga** [comment]
Ok. WIll do.

**Comment by 0xd4d** [comment]
Did you get the stack trace?
