### ISSUE TITLE
Unity (Connect) couldn't connect to debugged process

### ISSUE THREAD

**Issue by thijmen321** [0xd4d/dnSpy#1096]
I've been having trouble getting Unity debugging to work. Using the `Unity (Connect)` feature, "one or more errors" keep appearing.

![](https://totally-not.a-sketchy.site/4rn4RVp.png)
![](https://totally-not.a-sketchy.site/9jEq7Su.png)

I've tried using both dnSpy .NET Core and .NET 4.7.2, version 6.0.3. I have replaced mono.dll, with the correct version (Unity 5.6.2). I'm on Windows 10 v1809 and I'm not running any anti-virus. I've also tried:
 - Setting firewall rules or disabling it altogether
 - Using different ports by creating the environment variable named `DNSPY_UNITY_DBG` with value `--debugger-agent=transport=dt_socket,server=y,address=127.0.0.1:<port>,defer=y,no-hide-debugger`

None of that has seemed to do anything, any help would be appreciated.

**Comment by 0xd4d** [comment]
Make sure the process is started and also that it isn't paused (switch to it to give it keyboard focus). Also verify that it's listening on that port.
