### ISSUE TITLE
Internal debugger error with dnspy v 6.0.3

### ISSUE THREAD

**Issue by moviedreamer** [0xd4d/dnSpy#1099]
Hello,

I'm trying to use **dnSpy v 6.0.3** to debug an obfuscated program (**xxx**) with ConfuserEx and I get this error "_Internal debugger error_" in Local variables. I follow the following steps:

Do you have any idea how can I get the local variables? 

I'm using **dnSpy v 6.0.3** on Windows 10

The steps needed to reproduce this issue are:

     - open the obfuscated program.exe in dnSpy
     - set a BP in .cctor of module
     - launch it

**Comment by piratesephiroth** [comment]
did you do this

https://github.com/0xd4d/dnSpy/wiki/Making-an-Image-Easier-to-Debug

**Comment by moviedreamer** [comment]
would you please explain more in detail what I'm supposed to do?

**Comment by moviedreamer** [comment]
and here is the screen shot:
<img width="868" alt="dnspy-error" src="https://user-images.githubusercontent.com/10474280/54776454-748b8880-4c10-11e9-9c7c-7a4af14ceeab.PNG">
any help would be highly appreciated

**Comment by 0xd4d** [comment]
You're not the first one with this problem when debugging some obfuscated binaries so please search the issues.

**Comment by moviedreamer** [comment]
thanks for your answer. I've googled but without success, Do you know how can I search the issue and where to find a fix for this issue?

Thanks in advance

**Comment by 0xd4d** [comment]
Click the issues tab at the top.

**Comment by elmagekmosaad** [comment]
i have this proplem too
