### ISSUE TITLE
Double to Int convert exception in SessionSettings

### ISSUE THREAD

**Issue by UlyssesWu** [0xd4d/dnSpy#11]
When I launch(not the first time) DnSpy 1.0.1.0 I get a Exception like this:
> System.Exception: 223.69811320754718 is not a valid Int32 value.

Can be solved by modify %AppData%\Roaming\dnSpy\dnSpy.xml.

    <BottomPaneHeight>223.69811320754718</BottomPaneHeight>

Issue in ICSharpCode.ILSpy.SessionSettings:
Line 58:

    this.TopPaneSettings.Height = FromString((string)doc.Element("TopPaneHeight"), 200);
    this.BottomPaneSettings.Name = FromString((string)doc.Element("BottomPaneName"), string.Empty);
    this.BottomPaneSettings.Height = FromString((string)doc.Element("BottomPaneHeight"), 200); 

I think "200" should be "200.0", otherwise it is parsed as a int rather than a double. And an Exception was threw so wasn't catched by `catch(FormatException)` .

P.S. dnSpy is great!

**Comment by 0xd4d** [comment]
Good catch. But weird. That's never happened to me, they're always saved as integers.
