### ISSUE TITLE
Using as a library

### ISSUE THREAD

**Issue by Velocity-** [0xd4d/dnSpy#1100]
Is it possible to use dnSpy as a library to embed it into a tool, for example to modify a binary in an automated fashion and then spit out a modified variant of it?

I know I can dig through the code but I figured I should also just ask to see if there was anything specially made for these use cases. Thanks!

**Comment by InlineAsm** [comment]
To modify a .net assembly you could use DnLib which is what DnSpy uses and is from the same author.
https://github.com/0xd4d/dnlib
