### ISSUE TITLE
Can I set the entrypoint?

### ISSUE THREAD

**Issue by Sonic-The-Hedgehog-LNK1123** [0xd4d/dnSpy#1102]
- What version did you use?
6.0.4

Is it possible to set/change the entrypoint of an .exe assembly?

**Comment by SlowLogicBoy** [comment]
![image](https://user-images.githubusercontent.com/3121637/55055725-98195d80-506c-11e9-812f-0a76168572f2.png)

**Comment by Sonic-The-Hedgehog-LNK1123** [comment]
I must have overlooked it, I had looked in that dialog, oops.
