### ISSUE TITLE
Strange behavior with "Merge with assembly"

### ISSUE THREAD

**Issue by Sonic-The-Hedgehog-LNK1123** [0xd4d/dnSpy#1103]
- What version did you use?
6.0.4
- Write down all steps needed to reproduce this issue. Also attach any needed files.

Select the .exe in dnSpy, select "Merge with assembly..." select dependent .dll --> error: "cannot merge because it's a dependency" 
![Error](https://user-images.githubusercontent.com/46045820/55078713-08d76e80-509b-11e9-8d47-f3efd3fc5635.png)

As stated above, if I try to merge the .dll with the .exe I get the above error. however, if I select the .dll first, and try to merge the .exe with the .dll, so, do it the other way around, it merges without any problems.

**Why this strange behavior?**

**Comment by 0xd4d** [comment]
Use ILMerge if you want to merge any assembly.
