### ISSUE TITLE
[Feature request] Option to disable tooltips

### ISSUE THREAD

**Issue by danielmmmm** [0xd4d/dnSpy#1105]
(dnSpy 6.03)

While tooltips are useful in many occasions, they can also be distracting.

In the assembly explorer, the tooltips show the exact same information the user already sees without tooltips. At least, the mousover only reacts when the mouse cursor is hovering over content.
In the search results field, however,  tooltips are shown for the current row, independently of where in that row the mouse cursor is.

**Comment by 0xd4d** [comment]
The tooltips now show more info in assembly explorer. An option to disable tooltips doesn't seem to very useful.
