### ISSUE TITLE
Debugger alters behavior of AllocHGlobal / FreeHGlobal

### ISSUE THREAD

**Issue by 0x0ade** [0xd4d/dnSpy#1106]
Using dnSpy 6.0.4, both x86 and x64, `Marshal.FreeHGlobal` can throw an `COMException` with the error code `0x80070006` (`E_HANDLE`). Running the same code in other environments doesn't trigger that.

I verified that the pointer passed to `FreeHGlobal` is the same as what I received from `Marshal.AllocHGlobal`, and that it's not freed more than once.

What's weird is that too little memory is allocated by the program in the first place. It then writes past the allocated memory. This works "fine" when it clearly shouldn't, and it - somehow - only burns down once it tries to free the allocated memory.

This only occurs when starting the program via dnSpy's debugger. Attaching the debugger to a running instance even before `AllocHGlobal` doesn't trigger this.

I'll try to create a minimal test case as soon as I can.

By the way, thank you for dnSpy and your other fantastic projects!

**Comment by 0xd4d** [comment]
Do you have a small repro?

There's no code in dnSpy that should cause this. Most likely the OS enables extra memory alloc/free checks when the program is run under a debugger.

You can try disabling the anti-anti-debug checkboxes in the debugger settings (top 3 check boxes).

**Comment by 0x0ade** [comment]
I'm sorry that I still don't have a small repro case. Unfortunately the smallest I've got is building an outdated version of MonoMod (https://github.com/0x0ade/MonoMod/commit/f7274158bcfd4582504039020997a01add9044ae) and running its unit tests via dnSpy. I'll try to extract a small repro out of it this week though.

> There's no code in dnSpy that should cause this. Most likely the OS enables extra memory alloc/free checks when the program is run under a debugger.

That's what I assumed - this is pretty much undefined behavior anyway. It just surprised me (and a few others) that running it via dnSpy's debugger altered the behavior of `FreeHGlobal`, even though it probably shouldn't be all that surprising.

> You can try disabling the anti-anti-debug checkboxes in the debugger settings (top 3 check boxes).

I've tested this with the options enabled and disabled. `FreeHGlobal` fails no matter what.

**Comment by poizan42** [comment]
When a process is launched with DEBUG_ONLY_THIS_PROCESS / DEBUG_PROCESS then the debug heap is switched on. You can disable this by setting the environment variable _NO_DEBUG_HEAP to "1"

**Comment by 0xd4d** [comment]
Seems like an OS feature, so not much I can do about it.

**Comment by 0xd4d** [comment]
Reopening, dnSpy should set _NO_DEBUG_HEAP=1
