### ISSUE TITLE
Debugging or Attaching to Steam Game fails

### ISSUE THREAD

**Issue by DewiMorgan** [0xd4d/dnSpy#1107]
> Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

> **- What version did you use?**

6.0.4.0

(downloaded today from main download page: latest build link says updated 9 days ago, so assuming they are the same: did not redownload from above link)

> **- Write down all steps needed to reproduce this issue. Also attach any needed files.**

**Summary**

I am attempting to debug Steam version of game "60 Seconds!" (64 bit, Unity 5.6.3, 60seconds.exe file version 5.6.3.59581)

I am unable to attach, nor to successfully convert to a debug build.

I suspect this is related to closed question #678 but I could not see on that question any solution that I have not covered in my existing steps.

Are there any known solutions, or am I doing anything obviously stupid? 

**First attempt:**
Following instructions at: https://github.com/0xd4d/dnSpy/wiki/Debugging-Unity-Games#debugging-release-builds
Replaced file `D:\Games\Steam\SteamApps\common\60 Seconds!\60Seconds_Data\Mono\mono.dll` with:
`Unity-debugging-5.x.zip Unity-debugging/unity-5.6.3/win64/mono.dll`

In dnSpy, clicking Debug->Start Debugging brought up window prefilled with correct executable `D:\Games\Steam\SteamApps\common\60 Seconds!\60Seconds.exe` and working directory.

Clicking OK brought up the black game screen, overlaid with the in-app message:

> We are sorry, but 60 Seconds! was not able to start properly. If the problem persists, please contact Robot Gentlemen at [their support email]. 

This is quickly replaced with another message:

> 60 Seconds! Steam edition uses Steam services and needs to be launched from Steam. Please start the game again from Steam in offline or online mode.

[Edited to note: these messages are displayed even if I do not replace the mono.dll. They're just a thing the game does, which means I can't debug using the mono.dll replacement.]

Conclusion: I can't launch the Steam version of their executable directly. For most issues, I'd just say "screw Steam", and just try debugging the DRM-free version from GoG, but I'm trying to debug what I think is a bug I've found with one of their Steam achievements, so I kinda need to debug the Steam version :(

So I think I need to attach to it, which means converting it into a debug build. OK.

**Second attempt:**
Following instructions at: https://github.com/0xd4d/dnSpy/wiki/Debugging-Unity-Games#turning-a-release-build-into-a-debug-build

Unity Download Archive, clicked Unity 5.x tab (after first failing to see it and trawling the LTS archives and Google looking for stuff older than two years - I'm dim.) -> Unity 5.6.3 -> Downloads (Win) -> Unity Editor 64-bit.

Backed up `D:\Games\Steam\SteamApps\common\60 Seconds!\60Seconds_Data and ...\60 Seconds!\60Seconds.exe`

Installed, then copied the three folders (Managed, Mono, Resources) from `D:\Program Files\Unity-5.6.3\Editor\Data\PlaybackEngines\windowsstandalonesupport\Variations\win64_development_mono\Data` to `D:\Games\Steam\SteamApps\common\60 Seconds!\60Seconds_Data`, selecting to overwrite 15 files.

Copied the file `D:\Program Files\Unity-5.6.3\Editor\Data\PlaybackEngines\windowsstandalonesupport\Variations\win64_development_mono\player_win.exe` to `D:\Games\Steam\SteamApps\common\60 Seconds!\60Seconds.exe` - this changes the exe from (64 bit, file version 5.6.3.59581) to (64 bit, file version 5.6.3.4124).

Running that program did not bring up the game screen, but rather what I think is a Unity error dialog (not ctrl-C copy-pastable, but with the main error text in a text-area that can be selected and copied): 

> Error
> Failed to initialize player
> Failed to load PlayerSettings (internal index #0).
> Most likely data file is corrupted, or built with mismatching
> editor and platform support versions.

**Third attempt:**
I thought perhaps I needed to replace the mono.dll file with your debugger one, so I tried that again, replacing the new file `D:\Games\Steam\SteamApps\common\60 Seconds!\60Seconds_Data\Mono\mono.dll` with
`Unity-debugging-5.x.zip Unity-debugging/unity-5.6.3/win64/mono.dll`

But in that case, starting it gave the error dialog (standard windows error dialog, so ctrl-C copied all its contents including title and button, as below):

> Oops!
> 
> The game crashed.
> The crash report folder named "2019-03-31_225240" next to game executable.
> It would be great if you'd send it to the developer of the game!
> 
> OK   
>

**Comment by 0xd4d** [comment]
You don't need to convert it to a debug build to attach to it. Just replace the mono.dll, like you already did, and then start debugging (combobox: `Unity (Connect)`), use default port 55555.

**Comment by DewiMorgan** [comment]
Aha! I'm an idiot once again! I'd been clicking "Debug" -> "Attach to process (Unity)" instead of "Debug" -> "Start Debugging" -> "Unity (Connect)"!

It worked!

In my day job, I don't even have an environment in which I can debug my own code. Given that, being able to attach a debugger to third party programs is absolutely mindblowingly wonderful to me. It means I'm going to be making better bug reports for stuff I'm beta-testing, write better documentation for wikis, and you've opened up a whole new world of moddability and fan-patchability for me!

Thank you so much.
