### ISSUE TITLE
Missing patched Unity files for 2018.3.0

### ISSUE THREAD

**Issue by DewiMorgan** [0xd4d/dnSpy#1108]
Question: are there plans to update `Unity-debugging-2018.x.zip`?

I see related issues #1032 and #1073, while both reporting the outdated zipfile, both ended up being resolved in other ways.

Trying to debug a project that uses 2018.3.0, that file contains only up to 2018.2.8.

I see that the source is available for later versions, so I did have a bash at compiling `https://github.com/0xd4d/dnSpy-Unity-mono/tree/master/unity-2017.3.0-mbe`, but after installing cygwin, visual studio, mono for windows and a bunch of other stuff as described at https://www.mono-project.com/docs/compiling-mono/windows/ I still failed to make it compile under cygwin, failed to find the msvc\run-msbuild.bat file, and failed to successfully compile using msbuild.exe.

It's 1:30am, I tried and failed. I don't anticipate any easy success there, so I'll likely only try again if it's confirmed that there are no plans to update `Unity-debugging-2018.x.zip`.

**Comment by 0xd4d** [comment]
Read the README, it explains how to compile the code.

**Comment by 0xd4d** [comment]
https://github.com/0xd4d/dnSpy-Unity-mono

**Comment by DewiMorgan** [comment]
Thank you - I was being blind and didn't see the README text way at the bottom of that page, nor the README file in the repo.

For those who come after me reading that README, some clarifications: 

"Supporting a new Unity version for Dummies" section of the readme is likely not needed, but if you do:
uwpatcher outputs dates in US format.
gitk is some UI thing for git. You can instead do:
got log --before=d1/mm/yyy --after=d2/mm/yy
...where the two dates are the day before and after the one you specified, also in US format.
Plus, the last uwpatcher line just hung for me anyway, even after moving the existing folder out the way.

Instead, I think the only important bit you need is the section:
"Building mono.dll & mono-2.0-bdwgc.dll"

The sln files it refers to are not in the individual folders, but rather in the root of the repo.

Maybe need to get Win 10 SDK 10.0.16299.0 or nearest possible from 
https://developer.microsoft.com/en-us/windows/downloads/sdk-archive
...and install. I did this, not sure if it was necessary: the alternative is to rightclick the sln and retarget to whatever SDK version came with your editor. But whether that will work for you I don't know.

Change solution configurations dropdowns at the top of the IDE to "Release" (not sure if this is correct for debugging, but I'm off to bed) and pick x64/x86 as needed.

Rightclick the project folder for the version you want, and click "build".

It'll stick the resulting dll file in a "builds" subfolder off the the root of the repo.

**Comment by Luckz** [comment]
So the solution for people who don't want to install VS & Unity Editor is to nicely ask others for compiled DLLs?

**Comment by DewiMorgan** [comment]
Well, ideally not...
I see four options, in order of best to worst for the community.

1) 0xd4d builds all the dlls. I suspect there's some reason this has not happened, since they seem otherwise very proactive and responsive and helpful on all issues.
2) Someone forks and does it. This saves 0xd4d the work, so they can focus on more important work on dnSpy, but bears the risk of them running into whatever problem that 0xd4d ran into.
3) Everyone compiles their own. Means maximum work from everyone, but arguably minimum risk.
4) A friendly person compiles individual ones on demand for askers. This means more work for both the askers and the friendly. It also means far greater risk for the askers, as the DLLs are not then visible to the community; the "friendly person" may distribute malicious DLLs without being easily exposed.

I guess I'm willing to attempt option 2, if there's interest: but I've a lot on my plate and it would likely take me weeks. @0xd4d do you have an opinion on this? Would you prefer I did not, or that I took some other approach?

**Comment by 0xd4d** [comment]
The zip files have been updated.

**Comment by DewiMorgan** [comment]
That works too! Thank you! :)
