### ISSUE TITLE
Unable to type # in interactive C# with azerty keyboard layout

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [0xd4d/dnSpy#111]
When trying to type a '#' in the interactive C# window using the azerty keyboard layout, it will open another tab called "Memory 3", and will not type the '#' sign in the Interactive C# window. This makes it impossible to manually type in any special commands such as #help or #clear, but the character can be copied manually.

To press the # character on an azerty keyboard, you have to hold the Alt key and press the 3 (above the main part of the keyboard, not numpad obviously) key. 

I checked the keyboard shortcuts on the wiki [here](https://github.com/0xd4d/dnSpy/wiki/Keyboard-Shortcuts), and it seems that ctrl+alt+3 open the Memory 3 window. I am, however, not holding the control key. Maybe it makes a difference, but I am pressing the AltGr key instead of Alt, otherwise I'm unable to type the # character.

**Comment by 0xd4d** [comment]
I tested pressing Alt Gr:

FRA:
```
DeadCharProcessedKey=None ImeProcessedKey=None Key=LeftCtrl KeyStates=Down SystemKey=None Modifiers=Control
DeadCharProcessedKey=None ImeProcessedKey=None Key=RightAlt KeyStates=Down SystemKey=None Modifiers=Alt, Control
```

DE
```
DeadCharProcessedKey=None ImeProcessedKey=None Key=LeftCtrl KeyStates=Down SystemKey=None Modifiers=Control
DeadCharProcessedKey=None ImeProcessedKey=None Key=RightAlt KeyStates=Down, Toggled SystemKey=None Modifiers=Alt, Control
```

EN:
```
DeadCharProcessedKey=None ImeProcessedKey=None Key=System KeyStates=Down, Toggled SystemKey=RightAlt Modifiers=Alt
```

For some reason Ctrl+Alt is sent when Alt Gr is pressed, so it gets translated as Ctrl+Alt+3 which is show memory window 3.

https://en.wikipedia.org/wiki/AltGr_key

> To allow the specific functionality of AltGr when typing non-English text on such keyboards, Windows allows it to be emulated by pressing the Alt key together with the Control key:

> Therefore, it is recommended that this combination not be used as a modifier in Windows keyboard shortcuts as, depending on the keyboard layout and configuration, someone trying to type a special character with it may accidentally trigger the shortcut,[5] or the keypresses for the shortcut may be inadvertently interpreted as the user trying to input a special character.

**Comment by 0xd4d** [comment]
I've switched the shortcuts from Ctrl+Alt+DIGIT to Ctrl+Shift+DIGIT
