### ISSUE TITLE
An ICorDebug instance couldn't be created

### ISSUE THREAD

**Issue by T3rry7f** [0xd4d/dnSpy#1111]
When I attach a Silverlight OOB process which is run with slllaugcher.exe command , the debugger always show me this error ,but i can attach and debug it the other day.I don't konw  how it is caused,I tried to change the version of Silverlight but useless.

**Comment by 0xd4d** [comment]
Silverlight isn't supported. I'm pretty sure it's dead. Feel free to hack the code to support it.

**Comment by T3rry7f** [comment]
Solved. Just replace the dbgshim.dll with a correct version .
