### ISSUE TITLE
Request: automatically append 'Attribute' suffix to search inputs

### ISSUE THREAD

**Issue by glenn-slayden** [0xd4d/dnSpy#1112]
- What version did you use?  dnSpy v6.0.4 (.NET Framework)

Request:

For a feature request, it would be great if the search results includes types whose name is the specified search text PLUS the word "Attribute" as a suffix, since this is a CLI convention for classes that can define metadata attached to other classes.

The search results should return the (distinct) union of all types found with either the suffixed- or non-suffixed search text, and it would also be nice to be able to easily turn the "Attribute"-suffixing feature on and off at will.

**Comment by 0xd4d** [comment]
Is this really needed, it should find the attribute type even without `Attribute` since it doesn't match whole words by default, eg. search for `AssemblyCopyright` and it will find `AssemblyCopyrightAttribute`

**Comment by 0xd4d** [comment]
No reply so closing it. It will find the attribute if you search for the name without `Attribute`.
