### ISSUE TITLE
Fully Qualified Types?

### ISSUE THREAD

**Issue by fdncred** [0xd4d/dnSpy#1117]
This is question, not a bug - perhaps a feature request. Is there an option to resolve all types to a fully qualified type?
This is what it does now.
```cs
public class Director : Director
{
}
```
This is what I'd like to see.
```cs
public class SomeNamespace.SomeClass.Director : SomeOtherNamespace.SomeOtherClass.Director
{
}
```
This would help with the disassembly of an entire project when you try to recompile it.
Thanks for your great work!!!

- What version did you use?
6.0.3

**Comment by 0xd4d** [comment]
There's no UI checkbox, but you can compile it yourself and change the default value to true here: https://github.com/0xd4d/ILSpy/blob/ilspyv2/ICSharpCode.Decompiler/DecompilerSettings.cs#L279

**Comment by fdncred** [comment]
I'll give that a try and see what happens. Thanks for the advice.

**Comment by fdncred** [comment]
This worked perfectly. Thank you so much! Might I be so bold to ask that you please make this a configurable option in some future release?

**Comment by 0xd4d** [comment]
I'll mark it as up for grabs, should be easy to fix for anyone who wants to do it.

Find all refs: `UseDebugSymbols` (see the file above), and add the code for `FullyQualifyAllTypes`. There should be one ref in a [xaml file](https://github.com/0xd4d/dnSpy/blob/master/Extensions/ILSpy.Decompiler/dnSpy.Decompiler.ILSpy/Themes/wpf.styles.templates.xaml)
