### ISSUE TITLE
Search not finding each occurence?

### ISSUE THREAD

**Issue by Hexogenx** [0xd4d/dnSpy#1118]
Using 6.0.4 64-bit

When searching, not all occurences are found/displayed. Is there something I'm missing?

![image](https://user-images.githubusercontent.com/49176996/56447599-8a709400-6309-11e9-9fd5-0ceb09387570.png)

**Comment by 0xd4d** [comment]
I only see one field reference so what exactly is the problem here?

**Comment by Hexogenx** [comment]
I am using the search function to find every occurence of "tier2chance". The search function returns one result, that "tier2chance" was found in RoR2.ChestBehaviour. What I am currently showing in the code section is an occurrence of "tier2chance" in RoR2.SceneDirector, which is not found when I just search for it. I don't know if this is expected behaviour, it just feels unintuitive to search for something but not find every place where it actually is. I guess since the tier2chance in SceneDirector is on the component5 object, it is not returned in a search?

**Comment by 0xd4d** [comment]
Use the analyzer to find all uses of a field/member.
