### ISSUE TITLE
Recompile failed with either vs or dnspy internal editor

### ISSUE THREAD

**Issue by ddf420** [0xd4d/dnSpy#1121]
I tried to decompile a software (Touhou Launcher) and add a line of code, but DnSpy shown me numerous weird errors (in screenshot
)DnSpy V6.0.4

![dnSpy_BjmZIA3RIB](https://user-images.githubusercontent.com/42910674/56671461-44d81080-66e7-11e9-9ac0-06d5c846c21f.png)

**Comment by 0xd4d** [comment]
See this issue https://github.com/0xd4d/dnSpy/issues/694

You can delete those lines
