### ISSUE TITLE
why do I have 5.0.4?

### ISSUE THREAD

**Issue by Bluscream** [0xd4d/dnSpy#1122]
How is the latest version 4.7.2 but my dnSpy shows 5.0.4?

![image](https://user-images.githubusercontent.com/3318223/56730288-de3f0b00-6757-11e9-9821-eb90d83df0f9.png)

**Comment by Bluscream** [comment]
nvm I just tested it and the version shown on github/appveyor does not match the actual version

**Comment by 0xd4d** [comment]
4.7.2 is the .NET Framework version.

**Comment by Bluscream** [comment]
How would one check if theres a new version without downloading it then?

**Comment by 0xd4d** [comment]
Click the `Watch` button above and select `Releases only` and you should get notified by github when a new version is released.
