### ISSUE TITLE
Using dnSpy from another C# app

### ISSUE THREAD

**Issue by Bluscream** [0xd4d/dnSpy#1123]
I have the following in mind:

1. Using dnspy's code to open two assemblies internally (one from a unity game and one is a mod)
2. Checking if function X that is called from mod assembly exists in game assembly
3. returning a detailed error if not

Is it possible (hard)?

**Comment by 0xd4d** [comment]
You need a .NET assembly reader eg. https://github.com/0xd4d/dnlib

**Comment by 0xd4d** [comment]
If you don't want to automate it you could of course use the analyzer. Find the method declaration, right-click its name and select `Analyze` or `Ctrl+Shift+R` then expand the `Used By` node. Make sure all assemblies that can call that method has been loaded in assembly explorer.

**Comment by Bluscream** [comment]
I will migrate this issue there; thanks

**Comment by 0xd4d** [comment]
You can use the analyzer, so check my edited post above.

**Comment by Bluscream** [comment]
I want it to happen without user interaction.

**Comment by XenocodeRCE** [comment]
Better use dnlib directly, no need to use that enormous project. Result will be done in less than 20 lines of code
