### ISSUE TITLE
Dnspy Autocomplete Is Stupid

### ISSUE THREAD

**Issue by Chris-Is-Awesome** [0xd4d/dnSpy#1124]
So I've been using dnspy for a few months, lately started working on a debug console with someone for a game called Ittle Dew 2.

However, today it started messing up for both of us. To the point where it's nearly unusable.

It's autocomplete feature has decided to restructure code across all scripts to what it sees as "more optimal". And because of that, it will actually sometimes completely prevent us from writing code.

In one of our situations, we had a GameObject variable that we assign a bit later, in the same function though. It was working fine for days, until dnspy decided that the if in `if (gameObject1.name == gameObject2.name)` was not important, so it changed that code to `gameObject1.name == gameObject2.name` instead. (this example is what's linked below) That's when we realized dnspy was being stupid.

After restarting, thinking that's the fix for everything, it turns out it completely renamed ALL variables across ALL 800+ scripts to non-descriptive names like "gameObject1", "localPosition", or "component" instead of the names we had assigned. And it restructured all the code, like changing lists we made to dictionaries and changing how objects are assigned to the list/dictionary.

It's become practically unusable. So please, allow disabling autocomplete entirely. Just allow us to disable all "smart" features so in the case of dnspy being dumb, we don't get locked out of writing code.

From this point on, dnspy is refusing to work with us. It started affecting both of us at the same time and reinstalling/reopening scripts, nothing fixes it. Unless this issue is fixed, we'll have to change our way of coding to match dnspy's opinions on "best practices" to avoid issues of it rewriting our code. And we'll have to get used to not having names for variables other than things like "gameObject27".

Below are 2 code files. The first is the code we wrote, the second is the code dnspy thinks we wrote.

[Our code](https://github.com/0xd4d/dnSpy/files/3124509/code1.txt)
[Our code after dnspy compile](https://github.com/0xd4d/dnSpy/files/3124512/code2.txt)
A video showing exactly what happens: https://youtu.be/kvpJ_N5e3hc
Notice in that video, an error was generated when I attempted 2nd compile. That error was dnspy's doing, due to it removing the highlighted if

**Comment by sunriseiscool** [comment]
Install Visual Studio?

**Comment by Kirides** [comment]
What you call "Autocomplete" is called compilation.
It's the process of taking human written C# and form CIL

DnSpy then takes the CIL and decompiles it back to C#
After this point, anything could've happend to your code.
Unused variables "suddenly missing", variables in a different order, names mangled
You will never know what happens to your code, until you compile it. (Or you know the exact ins and outs of the used compiler)

**Comment by 0xd4d** [comment]
As already explained, you're not working with source code but decompiled code (ILSpy decompiler engine) so it won't look exactly the same way as your original code.
