### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by LightAndDarkKlumpi** [0xd4d/dnSpy#1125]
Okay im in version 6.0.4 and i have a problem... im trying to hack a bit of ravenfield and stuff but i have a problem the code in there like
using System;
using System.Collections.Generic;
using UnityEngine;
it says that UnityEngine is not found BUT IT GOT CREATED BY THE CREATORS THEMSELF WTF?

**Comment by sunriseiscool** [comment]
no it wasnt
drag UnityEngine.dll into dnSpy aswell as your other bins

**Comment by 0xd4d** [comment]
If dnSpy can't find the other files in the same folder as the original file, you'll get errors so put them in the same folder or do what @sunriseiscool said and drag them all to assembly explorer.
