### ISSUE TITLE
Cant pass "this" as a argument

### ISSUE THREAD

**Issue by X606** [0xd4d/dnSpy#1126]
- What version did you use?
v6.0.4

- Write down all steps needed to reproduce this issue. Also attach any needed files.
1. Create a method that takes in a class as one of its arguments.
2. Go To that class, and try to call that method from one of the methods in it.
3. It gives you the following error: Reference to type 'UpgradeDescription' claims it is defined in 'Assembly-CSharp', but it could not be found

**Comment by 0xd4d** [comment]
Try saving the assembly first and reloading it and see if that helps. When editing an assembly, it passes the saved file to the compiler.

**Comment by 0xd4d** [comment]
I assume that fixed it so I'm closing this.

**Comment by Hi-ImKyle** [comment]
Reopening this as I have this issue and saving/reloading doesn't help.
