### ISSUE TITLE
Feature: Integrates the dnSpy into Visual Studio

### ISSUE THREAD

**Issue by totpero** [0xd4d/dnSpy#113]
Hello,
Will be nice if you integrate dnSpy in Visual Studio like:
https://visualstudiogallery.msdn.microsoft.com/8ef1d688-f80c-4380-8004-2ec7f814e7de
or
https://visualstudiogallery.msdn.microsoft.com/95789cdb-08f9-4dae-9b2f-fc45a452ad77/

**Comment by 0xd4d** [comment]
Not likely to ever happen.
