### ISSUE TITLE
Question on watch of variable in mixed mode assembly

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#1130]
- What version did you use?
6.0.4

- Write down all steps needed to reproduce this issue. Also attach any needed files.
I"m trying to inspect some module scope variable inside mixed mode assembly,
for some reason it is not possible, e.g.:

![image](https://user-images.githubusercontent.com/765343/57390115-4237e980-71c4-11e9-8f5d-f91f94b8464c.png)

are there any other steps/hints to do this?

**Comment by 0xd4d** [comment]
It uses Roslyn's C#/VB expression evaluators and they don't support it. They only accept valid C#/VB syntax.

**Comment by 0xd4d** [comment]
You can use reflection (in the watch window) to get/set the value.
