### ISSUE TITLE
Obfuscated dll can't open on 6.0.4 but can open on 4.5.2

### ISSUE THREAD

**Issue by libDataso** [0xd4d/dnSpy#1131]
- What version did you use?
6.0.4 x.x.996

- Write down all steps needed to reproduce this issue. Also attach any needed files.
I came across a game dll that couldn't be opened on 6.0.4 but when I tried to open on old copy of dnspy 4.5.2, it can be opened and noticed straight away that it is obfuscated. The old dnspy can't save dll due to Uint16 error.
Same problem on latest version of de4dot it just report it is not PE. older commit of de4dot work and detect Reactor but ERROR 4 times.

[DZMainAssembly.zip](https://github.com/0xd4d/dnSpy/files/3162309/DZMainAssembly.zip)

**Comment by libDataso** [comment]
After spending hours checking out for last commit that could read the file using bitbucket software, I found out that the issue is related to this commit https://github.com/0xd4d/dnSpy/commit/5f36e03c5c2767b606db7855759b04e6f4519f32

I'm not much familar with the PE images so i don't know what code to change. pretty sure it's PE and blob images related 

My trick was to save the dll from dnspy in order to be able to deobfruscate but i got an error "File error: Can't read one UInt16" which I believe the reason why old de4dot returned ERROR 4 times. not sure if it was already fixed in later commit from that

Please take a look. Whould be nice if it was fixed on de4dot too

**Comment by 0xd4d** [comment]
It's an update to dnlib, don't have time to check now. BTW, the easiest way to find the commit is to use `git bisect`.

**Comment by libDataso** [comment]
Take your time :)
I'm quite new to git stuffs

**Comment by 0xd4d** [comment]
Should be fixed with the latest dnlib build which you can build yourself or download from https://ci.appveyor.com/project/0xd4d/dnlib/builds/24713444/artifacts

Get the nupkg file, rename it to zip and extract `lib\net45\dnlib.dll` to your dnSpy/de4dot dir and it should work.
