### ISSUE TITLE
*question*

### ISSUE THREAD

**Issue by kelvinwop** [0xd4d/dnSpy#1132]
just a question, not an issue:

dnspy color scheme is awesome, how do I copy it to vs/vscode?

**Comment by xsilent007** [comment]
dnSpy's color theme was inspired by Visual Studio... I'm not sure what you mean...

**Comment by 0xd4d** [comment]
The colors dnSpy uses are in `Themes\*.dntheme' so just add those colors to VSCode.

**Comment by Aceba1** [comment]
[Visual Studio Code : Customizing a color theme](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme)
