### ISSUE TITLE
Graphical memory view

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#1133]
For static analyzing, especially when the assembly is heavily obfuscated, a graphical view would help a lot. Is there something like that in dnSpy already?

![a](https://user-images.githubusercontent.com/14368203/57708108-506c8680-7658-11e9-822a-a5e1ed6c59c0.jpg)

**Comment by 0xd4d** [comment]
No, but the decompiler will already show you the blocks. I don't see how that IDA view is better.

**Comment by 0xd4d** [comment]
Doesn't seem to be very useful, closing it.
