### ISSUE TITLE
How do I use the Debugger?

### ISSUE THREAD

**Issue by Chris-Is-Awesome** [0xd4d/dnSpy#1134]
I'm new to reverse engineering and only now looked into debug process in Dnspy

I'm modding a Unity game, I replaced the mono.dll and from what I can  tell from output messages and thread events, it's attached to Dnspy.

I'm just wondering how I can see things like Unity console messages? What window would they show up in? Because I made a Debug.Log statement in Update that I'm not seeing output to any window.

What do all the debug windows do?

I went through issues to see if my question was answered and there were only questions on _how to start debugging_. And I wasn't able to find any videos showing off the debug feature.

Thanks!

**Comment by 0xd4d** [comment]
AFAIK older Mono versions don't support sending debug log messages to the debugger so try Console.WriteLine()

**Comment by Chris-Is-Awesome** [comment]
It's Unity 5.3.5, which I remember uses Debug.Log from back when I used that version.

But I tried both Debug.Log() and Console.WriteLine() and neither showed anything in locals window (which I assume is where that would be outputted?

**Comment by 0xd4d** [comment]
If it uses mono.dll it's the old Unity, so you should see no messages from Debug.Log(). Any messages should be shown in the Output window.
