### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by Sora92** [0xd4d/dnSpy#1135]
![Untitled](https://user-images.githubusercontent.com/40660392/58171480-c9925c00-7c9e-11e9-9dd4-e58e3d21204a.png)
![Untitled1](https://user-images.githubusercontent.com/40660392/58171485-cbf4b600-7c9e-11e9-943b-cc68e578556c.png)
Could someone tell me how to delete that text without getting lots of errors
Thanks
And i am sorry if i should not have posted here
Thanks again

**Comment by gmastergreatee** [comment]
Open the il code for each of those lines and then delete them one by one.

**Comment by Sora92** [comment]
> Open the il code for each of those lines and then delete them one by one.

Could you pls help me edit it because after i did what you said i deleted everything

**Comment by 0xd4d** [comment]
Looks like all assembly references can't be found. Make sure they're in the same folder as the file you're editing.

Create a better issue title next time you open an issue.
