### ISSUE TITLE
Errors exist in the composition

### ISSUE THREAD

**Issue by ecniVcinimoD** [0xd4d/dnSpy#1136]
I just did the following:

git clone --recursive https://github.com/0xd4d/dnSpy.git
(from GitBash)

I updated my Visual Studio to the latest:  15.9.12 (Visual Studio Professional 2017; it reports .NET Frameowk Version 4.7.03190) and opened dnSpy.sln

I set dnSpy (Set as Startup Project) instead of dnSpy-x86.

I hit run and watched the build output - no errors reported.

When the code starts to execute I get the following exception:

Microsoft.VisualStudio.Composition.CompositionFailedException
  HResult=0x80131500
  Message=Errors exist in the composition.
  Source=Microsoft.VisualStudio.Composition
  StackTrace:
   at Microsoft.VisualStudio.Composition.CompositionConfiguration.ThrowOnErrors()
   at dnSpy.MainApp.App.CreateExportProviderFactorySlow(Resolver resolver) in C:\Git_Repos\dnSpy\dnSpy\dnSpy\MainApp\App.xaml.cs:line 205
   at dnSpy.MainApp.App.InitializeMEF(Boolean readSettings, Boolean useCache) in C:\Git_Repos\dnSpy\dnSpy\dnSpy\MainApp\App.xaml.cs:line 134
   at dnSpy.MainApp.App.<>c__DisplayClass14_0.<.ctor>b__0() in C:\Git_Repos\dnSpy\dnSpy\dnSpy\MainApp\App.xaml.cs:line 97
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

So the build was fine but I'm getting a run-time problem.  I went through some of the projects (including ConvertToNetstandardReferences ) and made sure the NuGet downloads looked OK.  This was spurred by an odd message I got when Visual Studio first loaded all the projects in the solution:

Error occurred while restoring NuGet packages: The operation failed as details for project ConvertToNetstandardReferences could not be loaded.
Time Elapsed: 00:00:09.9515940
========== Finished ==========

Any suggestions?  When I google this run-time error I don't see a clear solution.  Do I simply have my exception handling setting set too tight?

I have downloaded the binary and have been using that for precisely what I need but I want to add an option to "Detach All" when the Form closes so that I can dynamically add a running dnSpy instance from my application and programmatically close dnSpy without also closing my application.  I can already tell dnSpy does exactly what I want but now I need to be able to edit/compile/run a modified version.

Thanks!

**Comment by 0xd4d** [comment]
Delete %LOCALAPPDATA%\dnSpy

**Comment by ecniVcinimoD** [comment]
I deleted the folder you suggested and I insured the RecycleBin was emptied.  Then I opened Visual Studio and ran dnSpy.

I get exactly the same error as I noted above.

What am I doing wrong?

**Comment by 0xd4d** [comment]
The exception object should have more info, especially one of its properties.

**Comment by 0xd4d** [comment]
Eg. $exception.Errors[0][0].Message, check all available Message props in those collections.

**Comment by ecniVcinimoD** [comment]
dnSpy.Bookmarks.DotNet.DotNetMethodBodyBookmarkLocationSerializer.ctor(dbgMetadataService): expected exactly 1 export matching constraints:
    Contract name: dnSpy.Contracts.Debugger.DotNet.Metadata.DbgMetadataService
    TypeIdentityName: dnSpy.Contracts.Debugger.DotNet.Metadata.DbgMetadataService
but found 0.

**Comment by ecniVcinimoD** [comment]
dnSpy.Bookmarks.DotNet.DotNetTokenBookmarkLocationSerializer.ctor(dbgMetadataService): expected exactly 1 export matching constraints:
    Contract name: dnSpy.Contracts.Debugger.DotNet.Metadata.DbgMetadataService
    TypeIdentityName: dnSpy.Contracts.Debugger.DotNet.Metadata.DbgMetadataService
but found 0.

**Comment by ecniVcinimoD** [comment]
dnSpy.Bookmarks.DotNet.BookmarkFormatterServiceImpl.ctor(dbgMetadataService): expected exactly 1 export matching constraints:
    Contract name: dnSpy.Contracts.Debugger.DotNet.Metadata.DbgMetadataService
    TypeIdentityName: dnSpy.Contracts.Debugger.DotNet.Metadata.DbgMetadataService
but found 0.

**Comment by 0xd4d** [comment]
Make sure you compile all projects, including the debugger extensions.

**Comment by ecniVcinimoD** [comment]
This is the Errors[0][0], then Errors[0][1], then Errors[0][2] output

**Comment by ecniVcinimoD** [comment]
Yay!  I explicitly did a "Build" on Extensions/dnSpy.Debugger and now it runs.

Is there something in the "Build All" that causes that project to get skipped?

OK, now for the easy part (I hope):  Can I add a call to "DetachAll" from the App_Exit method?  If so what syntax would that involve?  I need to programmatically stop dnSpy but I don't want it to close the application from which I am opening/calling it.

**Comment by 0xd4d** [comment]
If you want a quick hack fix, have a look at class `DebuggerImpl` and its `AppWindow_MainWindowClosing()` method.

**Comment by ecniVcinimoD** [comment]
Fantastic suggestion!  I have now made my local version do exactly what I needed (call DetachAll when closing dnSpy).

One last question (because you've been so incredibly helpful so far, sorry):  I also need to remove the last assembly added (my main application compiles the user script every time they run it; the debugger is launched if the user asks, and at the end of the run the assembly is useless since a new one will be generated on their next "Run").  If I don't remove the assembly then multiple runs by the user keeps showing an ever-increasing list of assemblies, only one of which is current.

Where can I intercept the form closing and remove the last opened assembly?

**Comment by 0xd4d** [comment]
Just use `--dont-load-files` command line switch and it won't load anything in assembly explorer.
