### ISSUE TITLE
Error in search assemblies

### ISSUE THREAD

**Issue by Arsenal88** [0xd4d/dnSpy#1137]
I tried to use search assemblies in dnSPY
When I clicked on it or click (Ctrl +Shift+K) nothing happened and couldn't see it 

I remove the old version and use a new on the same thing

How can I fix it?

<img width="793" alt="55" src="https://user-images.githubusercontent.com/51047081/58380216-e1bfef00-7fae-11e9-9db7-d6f72de03aae.PNG">

**Comment by 0xd4d** [comment]
It' has 0 size, just drag it back up or close dnSpy, delete %APPDATA%\dnSpy\dnSpy.xml
