### ISSUE TITLE
Can't pass "this" as an argument

### ISSUE THREAD

**Issue by Hi-ImKyle** [0xd4d/dnSpy#1138]
- What version did you use?
dnSpy v6.0.4 (64 and 32 bit)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
Any method that takes a instance of a class, passed through as "this" says that the type of "this" claims it is in the current assembly but could not be found.

#1126 old issue. So it's open.

Screenshots: [One](https://i.imgur.com/Zk83btx.png) [Two](https://i.imgur.com/9rCPAte.png)

I'd do it in IL but I don't know IL enough
EDIT: I figured out the IL code for it, so that's fine. The this issue needs fixing though I think.

**Comment by 0xd4d** [comment]
Is `ThisTest()` method defined in another assembly that references the assembly you're editing?

If so, a workaround is to change that method from taking a `Player` class to `object` and you can then cast it to `Player` in that method.

Can you provide a full repro, i.e., exact steps and any assemblies?
