### ISSUE TITLE
dnspy ERROR: call another class in same namespace 

### ISSUE THREAD

**Issue by taitang96** [0xd4d/dnSpy#1139]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
v6.0.4
- Write down all steps needed to reproduce this issue. Also attach any needed files.
![image](https://user-images.githubusercontent.com/28817849/58420332-33ec3780-80b7-11e9-8962-76968736418e.png)
![image](https://user-images.githubusercontent.com/28817849/58420382-53836000-80b7-11e9-8fe5-02366953ffb7.png)

Hi guy I have an issue with dnspy, when i click on edit class C# in dnspy. if it's same namespace. it won't called a method in another class in same namespace. :( anyone can help about solving it

**Comment by 0xd4d** [comment]
Write down all steps needed to reproduce this issue. Also attach any needed files.
