### ISSUE TITLE
dotnet version too high,can this program support 2.x-4.x

### ISSUE THREAD

**Issue by ohyeah521** [0xd4d/dnSpy#114]
My os is win7, install dotnet 3.5 ,but dnSpy can not run on my system. I hate to install all versions dotnet runtime. can this program support  dotnet3.5?

This application requires one of the following versions of the .NET Framework:
 .NETFramework,Version=v4.6

Do you want to install this .NET Framework version now?

**Comment by linquize** [comment]
No, you only need to install .NET 4.6, you do not need every version 4.0, 4.5, 4.5.1, 4.5.2

**Comment by 0xd4d** [comment]
No, I will not support .NET 3.5, I just recently switched to .NET Framework 4.6. :sunglasses:

Install SP1, then install .NET Framework 4.6.
