### ISSUE TITLE
Type of conditional expression cannot be determined because there is no implicit conversion between 'xxx' and 'xxx'

### ISSUE THREAD

**Issue by mrkenzy19** [0xd4d/dnSpy#1141]
- What version did you use? 6.0.4 

- Write down all steps needed to reproduce this issue. Also attach any needed files.
In Damage method inside BattleUnit, when you edit and compile even without any changes, you will get this error
I don't understand what it means, i believe it's dnspy bug.

```
Severity	Code	Description	File	Line
Error	CS0656	Missing compiler required member 'System.Security.Permissions.SecurityPermissionAttribute..ctor'		
Error	CS0173	Type of conditional expression cannot be determined because there is no implicit conversion between 'System.Collections.Generic.List<Sh.Settings.ChangeHealthAbility.Types.Feature>' and 'System.Collections.ObjectModel.ReadOnlyCollection<Sh.Settings.ChangeHealthAbility.Types.Feature>'	main.cs	25

```

![image](https://user-images.githubusercontent.com/24647715/58507085-2efbb680-8191-11e9-86c5-7780ed9d1fcd.png)

**Comment by 0xd4d** [comment]
Attach all required files

**Comment by mrkenzy19** [comment]
Sorry I forgot, i was sleepy yesterday
Here you go: 
[Managed.zip](https://github.com/0xd4d/dnSpy/files/3231245/Managed.zip)

**Comment by Dendraspis** [comment]
Iterate through the list and add each item to the destination list separately. This is an **Implicit Type Conversion** issue and **not** a dnSpy problem.

**Comment by 0xd4d** [comment]
Sometimes you have to fix the decompiler output, so add a cast to shut up the compiler:

```diff
-IList<ChangeHealthAbility.Types.Feature> list = (extension == null) ? new List<ChangeHealthAbility.Types.Feature>() : extension.FeaturesList;
+IList<ChangeHealthAbility.Types.Feature> list = (extension == null) ? (IList<ChangeHealthAbility.Types.Feature>)new List<ChangeHealthAbility.Types.Feature>() : extension.FeaturesList;
```

**Comment by mrkenzy19** [comment]
Alright thanks very much
