### ISSUE TITLE
issue with singleton pattern

### ISSUE THREAD

**Issue by bazickoff** [0xd4d/dnSpy#1142]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?  v6.0.4

- Write down all steps needed to reproduce this issue. Also, attach any needed files.

I think there is a problem with singleton
the first image is the decompiled code 
the second image is the original code

the code should be: " `GameManager.Instance `"  instead of   
"` SingletonComponent<GameManager>.Instance.` "

![Screenshot_1](https://user-images.githubusercontent.com/22309093/58514012-198e8880-81a1-11e9-9282-2b68333150f7.png)
![Screenshot_2](https://user-images.githubusercontent.com/22309093/58514017-1dbaa600-81a1-11e9-8c3e-2096c29daad6.png)

**Comment by 0xd4d** [comment]
It's impossible to reproduce this without more info.

**Comment by bazickoff** [comment]
all related files 

[original files.zip](https://github.com/0xd4d/dnSpy/files/3229870/original.files.zip)
[decompiled files.zip](https://github.com/0xd4d/dnSpy/files/3229871/decompiled.files.zip)
