### ISSUE TITLE
Idea: sorting of inheritance order

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#1144]
- What version did you use?
6.0.5

- Write down all steps needed to reproduce this issue. Also attach any needed files.

when saving project I've noticed that sometimes decompiling engine puts inheritance in different order
eg:

![image](https://user-images.githubusercontent.com/765343/58746676-8e93e380-8469-11e9-9a70-c8fc4f88d53b.png)

the idea is to sort this order as well
and add it into already existing Options setting, eg:

![image](https://user-images.githubusercontent.com/765343/58746663-4674c100-8469-11e9-80d9-cf1f7f2780fa.png)

**Comment by 0xd4d** [comment]
Fixed
