### ISSUE TITLE
MonoDevelop/VS4Mac integration?

### ISSUE THREAD

**Issue by knocte** [0xd4d/dnSpy#1145]
Would be great to have a MD/VS4Mac add-in.

**Comment by 0xd4d** [comment]
I don't have time to do it, and also I don't use either of those programs.

**Comment by Therzok** [comment]
@0xd4d Would you be willing to accept contributions?

**Comment by 0xd4d** [comment]
dnSpy uses ILSpy v2 decompiler engine, it would probably make more sense to add an ILSpy VS4Mac extension.
