### ISSUE TITLE
Dnspy freezing for a long when saving file

### ISSUE THREAD

**Issue by CursedSheep** [0xd4d/dnSpy#1146]
[CrackKM_3_e.zip](https://github.com/0xd4d/dnSpy/files/3246410/CrackKM_3_e.zip)

- What version did you use?
>Dnspy 6.0.5

- Write down all steps needed to reproduce this issue. Also attach any needed files.
> Steps for problem to occur
1. drag the file i provided to dnspy
2. modify file/ do nothing
3. save file.
then dnspy just freezes when saving. mabye.

**Comment by 0xd4d** [comment]
It's obfuscated, so very likely that it won't work unless you first clean it. I couldn't repro the freezing, but a lot of exceptions are thrown because of invalid metadata when saving the file.
