### ISSUE TITLE
Ability to debug short living processes

### ISSUE THREAD

**Issue by SylwesterZarebski** [0xd4d/dnSpy#1148]
#### What version did you use?
dnSpy v6.0.4 (.NET Framework)

#### Write down all steps needed to reproduce this issue. Also attach any needed files.
I have a program, which execute (Process.Start) another program. Second one is short living and crashes occasionally. I want to debug second one, but i have no possibility to attach to it, because it lasts fraction of seconds to crash.

It should be some option:
- automatic attach to process by path/name/whatever (like ReAttach extension to VS),
- or automatic attach to child process.

PS. Unfortunately, i can't use VS with ReAttach, because it need to be done on other machine.

**Comment by 0xd4d** [comment]
Automatic attaching to child processes isn't possible unless perhaps if native debugging is enabled, which dnSpy doesn't do.

You can try setting dnSpy to the jit debugger, see https://github.com/0xd4d/dnSpy/issues/757

**Comment by 0xd4d** [comment]
You can write an extension or add some class to dnSpy if you want a hack fix.

You need `AttachableProcessesService` (MEF-import it), just call it in a loop. If you know it's a .NET Framework app (and not .NET Core), use `PredefinedAttachProgramOptionsProviderNames.DotNetFramework` as `providerNames` to speed up the method call.

```C#
// gets loaded at startup
[ExportAutoLoaded]
class hack {
hack(AttachableProcessesService attach) {
//...
start();
}
void start() { ... }
}
```

**Comment by SylwesterZarebski** [comment]
I'm afraid, i have not sufficient knowledge to mangle with extensions or internals of dnSpy, but thanks, maybe later :-).

**Comment by 0xd4d** [comment]
Try this hack, add it to some assembly eg. dnSpy.Debugger

```C#
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Threading.Tasks;
using dnSpy.Contracts.Debugger;
using dnSpy.Contracts.Debugger.Attach;
using dnSpy.Contracts.Extension;

namespace dnSpy.Debugger {
	[ExportAutoLoaded]
	class Hack : IAutoLoaded {
		readonly AttachableProcessesService attachableProcessesService;

		[ImportingConstructor]
		Hack(AttachableProcessesService attachableProcessesService) {
			this.attachableProcessesService = attachableProcessesService;
			StartAsync();
		}

		async void StartAsync() {
			var attachedProcesses = new HashSet<(int pid, RuntimeId)>();
			const int DELAY_MILLISECS = 100;
			var processNames = new string[] {
				// wildcards can be used too
				"MyProcess.exe",
			};
			int[] processIds = null;
			var providerNames = new string[] {
				// Assume it's .NET Framework only to speed it up
				PredefinedAttachProgramOptionsProviderNames.DotNetFramework,
			};
			for (;;) {
				var processes = await attachableProcessesService.GetAttachableProcessesAsync(processNames, processIds, providerNames);
				foreach (var process in processes) {
					if (!attachedProcesses.Add((process.ProcessId, process.RuntimeId)))
						continue;
					process.Attach();
				}
				await Task.Delay(DELAY_MILLISECS);
			}
		}
	}
}
```

**Comment by SylwesterZarebski** [comment]
Thanks, is it supposed to be compiled as new dnSpy binary (from this repository) or single project?

**Comment by 0xd4d** [comment]
Just compile everything yourself. Or you can just edit a compiled dnSpy (dnSpy.Debugger.x.dll - `Add Class (C#)`)
