### ISSUE TITLE
Save Option for Module

### ISSUE THREAD

**Issue by TheProxyRE** [0xd4d/dnSpy#115]
I would like to reccomend save option in context menu for ModuleDef because it could be useful for saving some encrypted modules in some packers/obfuscators like CC net Shield that dump module in runtime http://prntscr.com/aspd8n as .netmodule and to add support for System.Reflection.Module/Assembly, ModuleDef, AssemblyDef Save in locals and byte save for some classes like System.IO.Stream etc..

**Comment by 0xd4d** [comment]
You can break on Assembly.Load/LoadFrom and then save the byte[] to disk or right-click the module in the Modules window and save it.

**Comment by TheProxyRE** [comment]
It dont use assembly.Load that is the problem it dump it somehow inside assembly with WriteProcessMemory and not using byte[] it use some MemoryStream  or something like that
and my windbog is having problems loading that file i use so cant dump .netmodule with it

**Comment by 0xd4d** [comment]
The module should still be visible in the Modules window. Have you tried saving it here? If that fails, you can always select the module in Assembly Explorer and pick File -> Save Module.

**Comment by TheProxyRE** [comment]
Thanks Save Module Worket perfectly :D you can close issue now
