### ISSUE TITLE
How to keep the constants?

### ISSUE THREAD

**Issue by Erquint** [0xd4d/dnSpy#1151]
By default (or on my installation) dnSpy optimizes away all references to constants by substituting them with literal values in C# code view, including even new ones I may add.  
This gets cumbersome when I decide to change a constant and have to hunt and replace all those literals.  
Especially since you can't properly search for literals.  

I'm unable to find a way to prevent this happening as soon as I submit an edit to the code.  
How can I disable this behavior?

**Comment by InlineAsm** [comment]
Constants are replaced by the compiler at compile time for performance reasons. There is no way the decompiler can know whether the literal value in the IL is from the constant or just has the same value as the constant. So what you ask for can't be done.

If you want to be able to change the value and reflect the changes you could consider to change the constant to a static readonly field and use a field reference instead of a constant value.

**Comment by 0xd4d** [comment]
Yes, public/internal readonly fields (or properties) is the solution. You can create a new `Constants` class and reference it from any other class.

**Comment by Erquint** [comment]
Can I search for the matching literals across the project/file?  
I need some way to routinely replace all instances quick.  
The problem is that unless I already know where the constant is being evoked, I can only randomly stumble my way to find them them.  
Can some UI helper be implemented to streamline hunting them down?  
Or allow searching for literals like "1729576238ul".

**Comment by SlowLogicBoy** [comment]
![dnspyNS](https://user-images.githubusercontent.com/3121637/59423211-5f229680-8dda-11e9-90be-a41d6029b231.gif)

**Comment by Erquint** [comment]
That's a string. I mean, for example, a ulong.

**Comment by 0xd4d** [comment]
You can search for constants, it says `Number/string` in the combobox

**Comment by Erquint** [comment]
Hm, weird. Definitely had issues searching for numbers but not when I just tested it again.  
>Yes, public/internal readonly fields (or properties) is the solution.  

Is that gonna be safe in terms of keeping the internal flow and logic intact when reverse-engineering?  
Gotta say I'm far from an expert on .NET. Asking because of how strict C# is with its scoping, typing, etc.  
>You can create a new Constants class and reference it from any other class.  

Is there an example you can reference of doing that properly?
