### ISSUE TITLE
Adding new variables in existing method (nothing changes after press compile button)

### ISSUE THREAD

**Issue by Ultimate2k** [0xd4d/dnSpy#1153]
- What version did you use?
dnSpy v6.0.5

I try to add new variables in existing method (by clicking Edit Method), for example: 
I would like to add 2 String variables in method, like this:
String a ="";
String b ="123";

When I click "compile" button it gets back to prevoius state (like nothing has been changed), but it works perfectly when I just edit or delete some variables/methods. I don't know why I can't add (not edit) my own variables in a method. 

Does it affect only me (some bug) or it's  not possible to do it this way?

It would be nice if someone could help me.

**Comment by 0xd4d** [comment]
If you never use those locals, either the compiler doesn't create them or the decompiler doesn't show unused locals.

**Comment by Ultimate2k** [comment]
Ok. Thanks for your response :)
