### ISSUE TITLE
Include namespace and class name when tab hovered

### ISSUE THREAD

**Issue by ewwink** [0xd4d/dnSpy#1155]
![dnspy-hover](https://user-images.githubusercontent.com/760764/59139964-a87d7b00-89c1-11e9-883d-a44694d7574b.jpg)

Version: 6.0.4

**Comment by Dendraspis** [comment]
...&& assembly && (filepath || filename)

The reason while the full path is better: sometimes you compare two different versions of an assembly, so they have the same name and also filename.

**Comment by 0xd4d** [comment]
Fixed in latest build. Assembly name isn't shown since the filename is shown instead which should be enough.
