### ISSUE TITLE
Unity 2019.1.4f1

### ISSUE THREAD

**Issue by Dopepigeon** [0xd4d/dnSpy#1157]
Unity 2019.1.4f1 not supported right now?

**Comment by PermaNulled** [comment]
Provide more detail? 
What exactly is the issue you're having with that version of Unity?
Are you saying that because he didn't provide a dll for it? 
Have you tried converting it to a debug build using the steps mentioned in the wiki?
What version of dnSpy are you using?

**Comment by 0xd4d** [comment]
I've uploaded compiled 2019.x files now, including the other missing files. You also need the latest build of dnSpy since the older versions can cause the 2019.x unity game to hang if you start it from dnSpy (and don't attach/connect to it)
