### ISSUE TITLE
Cannot edit with invalid code. (Different Issue Read Below)

### ISSUE THREAD

**Issue by Fahd64x** [0xd4d/dnSpy#1158]
- dnSpy v6.0.5(Latest right now)

I know a simiar issue is fixed but it is a bit different then that.
The file which I am trying to edit, when opened the first time in dnSpy had correct code. I made some changes and then saved and closed it. The next time I open it, it shows code different then the first time. The class name is faulty. It is: 
<PrivateImplementationDetails><b7745fd9-78d2-409e-8226-ffa71a29420d_netmodule>
The code when the file opened the first time was more better but the next time I opened the file, it was bad(in terms of programming, not syntax). Like if the compiler had lost its intelligence.

**Comment by 0xd4d** [comment]
Did you forget to add a repro?

**Comment by Fahd64x** [comment]
Um... what do you mean?

**Comment by 0xd4d** [comment]
```
- Write down all steps needed to reproduce this issue. Also attach any needed files.
```

**Comment by Fahd64x** [comment]
While capturing the steps another problem has happened. I have a backup file, fortunately. I think I should send you a video as it would be very complex for you to understand screenshots and hard for me to take them. What do you think? Do you need the Video?

**Comment by Fahd64x** [comment]
May I send you a video?

**Comment by 0xd4d** [comment]
I prefer text, it's searchable and it's faster than watching a video.
