### ISSUE TITLE
[Feature Request] Extended tooltips in Assembly Explorer 

### ISSUE THREAD

**Issue by Dendraspis** [0xd4d/dnSpy#1160]
For my the "tooltips" in the Assembly Explorer are really annoying because they provide the same information as the text they belong to.
It would be nice to get more informations - for example the name of the assembly and the filepath. When using a lot of assemblys, the search and the analyzer I often end up not knowing in what assembly I'm currently looking, so that would be a nice addition. 
At the moment I have to _clone_ the tab, click a class in the Assembly Explorer and collapse it down to the assembly with the left arrow key to get this information without losing the view/code in the opened tab.

Or is there a better way I failed to find?

**Comment by 0xd4d** [comment]
Fixed in latest build. Assembly name isn't shown since the filename is shown instead which should be enough.

**Comment by GSPP** [comment]
I was about to suggest this feature and was happy to see it done already. Now using the latest build.
