### ISSUE TITLE
Export project with resources that has space in name

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#1162]
- What version did you use?
6.0.5

- Write down all steps needed to reproduce this issue. Also attach any needed files.
If an assembly has a resource that has spaces in its name, then VS can't find such a resource.
dnSpy as well as project has resource wtih %20 in it's name, but seems VS does not like it.

dn:

![image](https://user-images.githubusercontent.com/765343/59375337-98192780-8d56-11e9-83e7-456290298596.png)

vs:

![image](https://user-images.githubusercontent.com/765343/59375368-a6ffda00-8d56-11e9-8709-e82d111cb2f0.png)

![image](https://user-images.githubusercontent.com/765343/59375388-af581500-8d56-11e9-91c6-7aa5c073a410.png)

**Comment by 0xd4d** [comment]
Do you have a repro?

**Comment by greenozon** [comment]
yes
https://www.sendspace.com/file/t1ovla

**Comment by 0xd4d** [comment]
You can attach the file here

**Comment by greenozon** [comment]
ОК

[space_res.zip](https://github.com/0xd4d/dnSpy/files/3287395/space_res.zip)

**Comment by greenozon** [comment]
Here is another sample with lots of %20 issues in resource names

![image](https://user-images.githubusercontent.com/765343/59627754-a9dc3f80-9147-11e9-82ce-0b9d2a38960b.png)
[%20_err.zip](https://github.com/0xd4d/dnSpy/files/3298355/20_err.zip)
