### ISSUE TITLE
Crash on startup v6.0.5

### ISSUE THREAD

**Issue by mcpiroman** [0xd4d/dnSpy#1164]
Occures both on v6.0.5 release .net Core x64 and last CI build .net framework.

<details> 
  <summary>Stacktrace from .net core</summary>

> System.IO.FileFormatException: Invalid file format. ---> System.IO.FileFormatException: Invalid file format.
> 
>    at MS.Internal.Text.TextInterface.Native.Util.ConvertHresultToException(Int32 hr)
> 
>    at MS.Internal.Text.TextInterface.FontList.get_Item(UInt32 A_0)
> 
>    at MS.Internal.Text.TextInterface.FontList.FontsEnumerator.get_Current()
> 
>    at MS.Internal.FontFace.PhysicalFontFamily.MapGlyphTypeface(FontStyle style, FontWeight weight, FontStretch stretch, CharacterBufferRange charString, CultureInfo digitCulture, Int32& advance, Int32& nextValid)
> 
>    at MS.Internal.Shaping.TypefaceMap.MapByFontFaceFamily(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, IFontFamily fontFamily, FontStyle canonicalStyle, FontWeight canonicalWeight, FontStretch canonicalStretch, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Boolean nullFont, Double scaleInEm, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Boolean ignoreMissing, Int32& nextValid)
> 
>    at MS.Internal.Shaping.TypefaceMap.MapByFontFamily(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, IFontFamily fontFamily, CanonicalFontFamilyReference canonicalFamilyReference, FontStyle canonicalStyle, FontWeight canonicalWeight, FontStretch canonicalStretch, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Double scaleInEm, Int32 recursionDepth, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Int32& nextValid)
> 
>    at MS.Internal.Shaping.TypefaceMap.MapOnceByFontFamilyList(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, FontFamily[] familyList, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Double scaleInEm, Int32 recursionDepth, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Int32& nextValid)
> 
>    at MS.Internal.Shaping.TypefaceMap.MapByFontFamilyList(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, FontFamily[] familyList, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Double scaleInEm, Int32 recursionDepth, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Int32& nextValid)
> 
>    at MS.Internal.Shaping.TypefaceMap.MapItem(CharacterBufferRange unicodeString, CultureInfo culture, Span itemSpan, SpanVector`1& cachedScaledTypefaceIndexSpans, Int32 ichItem)
> 
>    at MS.Internal.Shaping.TypefaceMap.GetShapeableText(CharacterBufferReference characterBufferReference, Int32 stringLength, TextRunProperties textRunProperties, CultureInfo digitCulture, Boolean isRightToLeftParagraph, IList`1 shapeableList, IShapeableTextCollector collector, TextFormattingMode textFormattingMode)
> 
>    at MS.Internal.Shaping.GlyphingCache.GetShapeableText(Typeface typeface, CharacterBufferReference characterBufferReference, Int32 stringLength, TextRunProperties textRunProperties, CultureInfo digitCulture, Boolean isRightToLeftParagraph, IList`1 shapeableList, IShapeableTextCollector collector, TextFormattingMode textFormattingMode)
> 
>    at System.Windows.Media.TextFormatting.TextCharacters.MS.Internal.TextFormatting.ITextSymbols.GetTextShapeableSymbols(GlyphingCache glyphingCache, CharacterBufferReference characterBufferReference, Int32 length, Boolean rightToLeft, Boolean isRightToLeftParagraph, CultureInfo digitCulture, TextModifierScope textModifierScope, TextFormattingMode textFormattingMode, Boolean isSideways)
> 
>    at MS.Internal.TextFormatting.TextStore.CreateTextLSRuns(TextRunInfo runInfo, IList`1 textEffects, CultureInfo digitCulture, Int32 offsetToFirstChar, Int32 stringLength, Int32 uniformBidiLevel, TextFormattingMode textFormattingMode, Boolean isSideways, Int32& lastBidiLevel)
> 
>    at MS.Internal.TextFormatting.TextStore.CreateLSRuns(TextRunInfo runInfo, IList`1 textEffects, CultureInfo digitCulture, Int32 offsetToFirstChar, Int32 stringLength, Int32 uniformBidiLevel, TextFormattingMode textFormattingMode, Boolean isSideways, Int32& lastBidiLevel, Int32& textRunLength)
> 
>    at MS.Internal.TextFormatting.TextStore.CreateLSRunsUniformBidiLevel(SpanVector runInfoVector, SpanVector textEffectsVector, Int32 runInfoFirstCp, Int32 ichUniform, Int32 cchUniform, Int32 uniformBidiLevel, TextFormattingMode textFormattingMode, Boolean isSideways, Int32& lastBidiLevel)
> 
>    at MS.Internal.TextFormatting.TextStore.FetchLSRun(Int32 lscpFetch, TextFormattingMode textFormattingMode, Boolean isSideways, Plsrun& plsrun, Int32& lsrunOffset, Int32& lsrunLength)
> 
>    at MS.Internal.TextFormatting.LineServicesCallbacks.FetchRunRedefined(IntPtr pols, Int32 lscpFetch, Int32 fIsStyle, IntPtr pstyle, Char* pwchTextBuffer, Int32 cchTextBuffer, Int32& fIsBufferUsed, Char*& pwchText, Int32& cchText, Int32& fIsHidden, LsChp& lschp, IntPtr& lsplsrun)
> 
>    --- End of inner exception stack trace ---
> 
>    at MS.Internal.TextFormatting.TextMetrics.FullTextLine.FormatLine(FullTextState fullText, Int32 cpFirst, Int32 lineLength, Int32 formatWidth, Int32 finiteFormatWidth, Int32 paragraphWidth, LineFlags lineFlags, FormattedTextSymbols collapsingSymbol)
> 
>    at MS.Internal.TextFormatting.TextMetrics.FullTextLine..ctor(FormatSettings settings, Int32 cpFirst, Int32 lineLength, Int32 paragraphWidth, LineFlags lineFlags)
> 
>    at MS.Internal.TextFormatting.TextFormatterImp.FormatLineInternal(TextSource textSource, Int32 firstCharIndex, Int32 lineLength, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak, TextRunCache textRunCache)
> 
>    at MS.Internal.TextFormatting.TextFormatterImp.FormatLine(TextSource textSource, Int32 firstCharIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak, TextRunCache textRunCache)
> 
>    at System.Windows.Controls.TextBlock.MeasureOverride(Size constraint)
> 
>    at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
> 
>    at System.Windows.UIElement.Measure(Size availableSize)
> 
>    at System.Windows.Controls.DockPanel.MeasureOverride(Size constraint)
> 
>    at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
> 
>    at System.Windows.UIElement.Measure(Size availableSize)
> 
>    at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
> 
>    at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
> 
>    at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
> 
>    at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
> 
>    at System.Windows.UIElement.Measure(Size availableSize)
> 
>    at System.Windows.Controls.Border.MeasureOverride(Size constraint)
> 
>    at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
> 
>    at System.Windows.UIElement.Measure(Size availableSize)
> 
>    at System.Windows.Window.MeasureOverrideHelper(Size constraint)
> 
>    at System.Windows.Window.MeasureOverride(Size availableSize)
> 
>    at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
> 
>    at System.Windows.UIElement.Measure(Size availableSize)
> 
>    at System.Windows.Interop.HwndSource.SetLayoutSize()
> 
>    at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
> 
>    at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
> 
>    at System.Windows.Window.SetRootVisual()
> 
>    at System.Windows.Window.SetRootVisualAndUpdateSTC()
> 
>    at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
> 
>    at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
> 
>    at System.Windows.Window.CreateSourceWindowDuringShow()
> 
>    at System.Windows.Window.SafeCreateWindowDuringShow()
> 
>    at System.Windows.Window.ShowHelper(Object booleanBox)
> 
>    at System.Windows.Window.Show()
> 
>    at dnSpy.MainApp.App.OnStartup(StartupEventArgs e) in C:\projects\dnspy\dnSpy\dnSpy\MainApp\App.xaml.cs:line 556
> 
>    at System.Windows.Application.<.ctor>b__1_0(Object unused)
> 
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
> 
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

</details>

<details> 
  <summary>Stacktrace from .net framework (similar to above)</summary>

> System.IO.FileFormatException: Input file or data stream does not conform to the expected file format specification. ---> System.IO.FileFormatException: Input file or data stream does not conform to the expected file format specification.
> 
>    at MS.Internal.Text.TextInterface.Native.Util.ConvertHresultToException(Int32 hr)
> 
>    at MS.Internal.Text.TextInterface.FontList.get_Item(UInt32 A_0)
> 
>    at MS.Internal.FontFace.PhysicalFontFamily.MapGlyphTypeface(FontStyle style, FontWeight weight, FontStretch stretch, CharacterBufferRange charString, CultureInfo digitCulture, Int32& advance, Int32& nextValid)
> 
>    at MS.Internal.Shaping.TypefaceMap.MapByFontFaceFamily(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, IFontFamily fontFamily, FontStyle canonicalStyle, FontWeight canonicalWeight, FontStretch canonicalStretch, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Boolean nullFont, Double scaleInEm, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Boolean ignoreMissing, Int32& nextValid)
> 
>    at MS.Internal.Shaping.TypefaceMap.MapByFontFamily(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, IFontFamily fontFamily, CanonicalFontFamilyReference canonicalFamilyReference, FontStyle canonicalStyle, FontWeight canonicalWeight, FontStretch canonicalStretch, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Double scaleInEm, Int32 recursionDepth, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Int32& nextValid)
> 
>    at MS.Internal.Shaping.TypefaceMap.MapOnceByFontFamilyList(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, FontFamily[] familyList, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Double scaleInEm, Int32 recursionDepth, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Int32& nextValid)
> 
>    at MS.Internal.Shaping.TypefaceMap.MapByFontFamilyList(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, FontFamily[] familyList, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Double scaleInEm, Int32 recursionDepth, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Int32& nextValid)
> 
>    at MS.Internal.Shaping.TypefaceMap.MapItem(CharacterBufferRange unicodeString, CultureInfo culture, Span itemSpan, SpanVector`1& cachedScaledTypefaceIndexSpans, Int32 ichItem)
> 
>    at MS.Internal.Shaping.TypefaceMap.GetShapeableText(CharacterBufferReference characterBufferReference, Int32 stringLength, TextRunProperties textRunProperties, CultureInfo digitCulture, Boolean isRightToLeftParagraph, IList`1 shapeableList, IShapeableTextCollector collector, TextFormattingMode textFormattingMode)
> 
>    at MS.Internal.Shaping.GlyphingCache.GetShapeableText(Typeface typeface, CharacterBufferReference characterBufferReference, Int32 stringLength, TextRunProperties textRunProperties, CultureInfo digitCulture, Boolean isRightToLeftParagraph, IList`1 shapeableList, IShapeableTextCollector collector, TextFormattingMode textFormattingMode)
> 
>    at System.Windows.Media.TextFormatting.TextCharacters.MS.Internal.TextFormatting.ITextSymbols.GetTextShapeableSymbols(GlyphingCache glyphingCache, CharacterBufferReference characterBufferReference, Int32 length, Boolean rightToLeft, Boolean isRightToLeftParagraph, CultureInfo digitCulture, TextModifierScope textModifierScope, TextFormattingMode textFormattingMode, Boolean isSideways)
> 
>    at MS.Internal.TextFormatting.TextStore.CreateTextLSRuns(TextRunInfo runInfo, IList`1 textEffects, CultureInfo digitCulture, Int32 offsetToFirstChar, Int32 stringLength, Int32 uniformBidiLevel, TextFormattingMode textFormattingMode, Boolean isSideways, Int32& lastBidiLevel)
> 
>    at MS.Internal.TextFormatting.TextStore.CreateLSRuns(TextRunInfo runInfo, IList`1 textEffects, CultureInfo digitCulture, Int32 offsetToFirstChar, Int32 stringLength, Int32 uniformBidiLevel, TextFormattingMode textFormattingMode, Boolean isSideways, Int32& lastBidiLevel, Int32& textRunLength)
> 
>    at MS.Internal.TextFormatting.TextStore.CreateLSRunsUniformBidiLevel(SpanVector runInfoVector, SpanVector textEffectsVector, Int32 runInfoFirstCp, Int32 ichUniform, Int32 cchUniform, Int32 uniformBidiLevel, TextFormattingMode textFormattingMode, Boolean isSideways, Int32& lastBidiLevel)
> 
>    at MS.Internal.TextFormatting.TextStore.FetchLSRun(Int32 lscpFetch, TextFormattingMode textFormattingMode, Boolean isSideways, Plsrun& plsrun, Int32& lsrunOffset, Int32& lsrunLength)
> 
>    at MS.Internal.TextFormatting.LineServicesCallbacks.FetchRunRedefined(IntPtr pols, Int32 lscpFetch, Int32 fIsStyle, IntPtr pstyle, Char* pwchTextBuffer, Int32 cchTextBuffer, Int32& fIsBufferUsed, Char*& pwchText, Int32& cchText, Int32& fIsHidden, LsChp& lschp, IntPtr& lsplsrun)
> 
>    --- End of inner exception stack trace ---
> 
>    at MS.Internal.TextFormatting.TextMetrics.FullTextLine.FormatLine(FullTextState fullText, Int32 cpFirst, Int32 lineLength, Int32 formatWidth, Int32 finiteFormatWidth, Int32 paragraphWidth, LineFlags lineFlags, FormattedTextSymbols collapsingSymbol)
> 
>    at MS.Internal.TextFormatting.TextMetrics.FullTextLine..ctor(FormatSettings settings, Int32 cpFirst, Int32 lineLength, Int32 paragraphWidth, LineFlags lineFlags)
> 
>    at MS.Internal.TextFormatting.TextFormatterImp.FormatLineInternal(TextSource textSource, Int32 firstCharIndex, Int32 lineLength, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak, TextRunCache textRunCache)
> 
>    at MS.Internal.TextFormatting.TextFormatterImp.FormatLine(TextSource textSource, Int32 firstCharIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak, TextRunCache textRunCache)
> 
>    at System.Windows.Controls.TextBlock.MeasureOverride(Size constraint)
> 
>    at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
> 
>    at System.Windows.UIElement.Measure(Size availableSize)
> 
>    at System.Windows.Controls.DockPanel.MeasureOverride(Size constraint)
> 
>    at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
> 
>    at System.Windows.UIElement.Measure(Size availableSize)
> 
>    at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
> 
>    at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
> 
>    at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
> 
>    at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
> 
>    at System.Windows.UIElement.Measure(Size availableSize)
> 
>    at System.Windows.Controls.Border.MeasureOverride(Size constraint)
> 
>    at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
> 
>    at System.Windows.UIElement.Measure(Size availableSize)
> 
>    at System.Windows.Window.MeasureOverrideHelper(Size constraint)
> 
>    at System.Windows.Window.MeasureOverride(Size availableSize)
> 
>    at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
> 
>    at System.Windows.UIElement.Measure(Size availableSize)
> 
>    at System.Windows.Interop.HwndSource.SetLayoutSize()
> 
>    at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
> 
>    at System.Windows.Window.SetRootVisual()
> 
>    at System.Windows.Window.SetRootVisualAndUpdateSTC()
> 
>    at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
> 
>    at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
> 
>    at System.Windows.Window.ShowHelper(Object booleanBox)
> 
>    at dnSpy.MainApp.App.OnStartup(StartupEventArgs e) in C:\projects\dnspy\dnSpy\dnSpy\MainApp\App.xaml.cs:line 549
> 
>    at System.Windows.Application.<.ctor>b__1_0(Object unused)
> 
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
> 
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

</details>

**Comment by 0xd4d** [comment]
Have you tried this on another computer? The stack trace doesn't contain any dnSpy methods except App.xaml.cs

**Comment by mcpiroman** [comment]
Well, nevermind I guess. Several other .net applications I ran also crash at startup. It seems to be something on my side and to be wpf related.

**Comment by 0xd4d** [comment]
Check your font files, seems like you have some corrupt font file.

**Comment by mcpiroman** [comment]
It was indeed problem with fonts, namely corrupted font cache data. It affected all WPF applications. Following  
[this](https://recoverit.wondershare.com/erase-data/how-to-clear-font-cache-on-windows.html) and [this](https://www.thewindowsclub.com/rebuild-font-cache-in-windows) articles solved the issue for all applications.
