### ISSUE TITLE
Cannot edit code by using editor

### ISSUE THREAD

**Issue by mrcas** [0xd4d/dnSpy#1166]
I am using dnspy version v6.0.5

When i use the editor to edit code and recompile, there are errors like this:

Severity	Code	Description	File	Line
Error	BC30002	Type 'Global.System.Diagnostics.DebuggerNonUserCode' is not defined.		
Error	BC30002	Type 'Global.System.Diagnostics.DebuggerNonUserCodeAttribute' is not defined.		
Error	BC30002	Type 'Global.System.Diagnostics.DebuggerNonUserCodeAttribute' is not defined.		
Error	BC30002	Type 'Global.System.Diagnostics.DebuggerNonUserCode' is not defined.		
Error	BC30002	Type 'Global.System.Diagnostics.DebuggerNonUserCode' is not defined.		
Error	BC30002	Type 'Global.System.Diagnostics.DebuggerNonUserCode' is not defined.		
Error	BC30002	Type 'Global.System.Diagnostics.DebuggerNonUserCode' is not defined.		
Error	BC30002	Type 'Global.System.Diagnostics.DebuggerNonUserCode' is not defined.		
Error	BC30002	Type 'Global.System.Diagnostics.DebuggerNonUserCode' is not defined.		
Error	BC30002	Type 'Global.System.Diagnostics.DebuggerNonUserCode' is not defined.		
Error	BC30002	Type 'Global.System.Diagnostics.DebuggerNonUserCode' is not defined.		
Error	BC30260	'Loadnum' is already declared as 'Public LoadNum As UILabel' in this class.	main.g.vb	507

How can i fix them?

**Comment by 0xd4d** [comment]
> How can i fix them?

Provide a repro or no-one can help you.

**Comment by mrcas** [comment]
> 
> 
> > How can i fix them?
> 
> Add a repro if you need help.

Do you mean the target? or the capture image of the error?

**Comment by 0xd4d** [comment]
```
- Write down all steps needed to reproduce this issue. Also attach any needed files.
```

**Comment by mrcas** [comment]
Hi,

Here is the files

https://drive.google.com/drive/folders/17Zlm140MNFwuvP8CG2xTswlqvEKDt7kt?usp=sharing

I attached the video capture and dll file.

**Comment by 0xd4d** [comment]
Attach all files here (drag and drop), and write down all the steps to reproduce this.

**Comment by mrcas** [comment]
Hello,

I attach the dll file to reproduce. Here are the steps:

1. Drag the dll files to dnspy
2. Open and try to edit any method in the file.
3. Save it and got the erorr.

[Assembly-CSharp.zip](https://github.com/0xd4d/dnSpy/files/3365587/Assembly-CSharp.zip)

**Comment by 0xd4d** [comment]
That's one file, all files are needed since it also references other files which are needed.

**Comment by mrcas** [comment]
Hello,

Here are all the files. Sorry for my mistake.

[Attached.zip](https://github.com/0xd4d/dnSpy/files/3365872/Attached.zip)

**Comment by 0xd4d** [comment]
- Right click and choose `Add Class (Visual Basic)...` and copy and paste the missing attribute:
```VB
Imports System
Imports System.Runtime.InteropServices

Namespace System.Diagnostics
	<AttributeUsage(AttributeTargets.[Class] Or AttributeTargets.Struct Or AttributeTargets.Constructor Or AttributeTargets.Method Or AttributeTargets.[Property], Inherited := False)>
	Public NotInheritable Class DebuggerNonUserCodeAttribute
		Inherits Attribute

		Public Sub New()
		End Sub
	End Class
End Namespace
```
- Save the module (File -> Save Module...)
- Reload the file (File -> Reload All Assemblies)
- Edit any method you want without any errors

**Comment by mrcas** [comment]
Hello,

Thank you so much. It works!!!
