### ISSUE TITLE
Please make it possible to load all assemblies from a folder and its subfolders

### ISSUE THREAD

**Issue by kocsisketto** [0xd4d/dnSpy#1169]
I have a big folder structure, something like this:

- MyRootFolder
-- Folder1
--- SubFolder11
---- MyAssembly1.dll
---- MyAssembly2.dll
--- SubFolder12
---- MyAssembly3.dll
---- MyAssembly4.dll
...

The whole tree contains a lot (about 1.000) assemblies.
Is it possible to add the whole tree in 1 step? Otherwise it is quite hard to add all the assemblies 1 by 1. Unfortunately I cannot modify the folder structure (to copy all the assemblies to 1 common folder), because another application reads the folder hierarchy in a special way.

**Comment by Symbai** [comment]
For some reason you can drop folders into the assembly list but for another reason it does nothing. I believe a check if the dropped object is a folder and then recursively walk through it should be good idea. Or don't allow folder drag drop at all.
