### ISSUE TITLE
Building .NET Core

### ISSUE THREAD

**Issue by stevemk14ebr** [0xd4d/dnSpy#1170]
- What version did you use?
Latest netcore3.0 branch

What is the intended workflow to build all projects targeting only .NET core, such that they could run on linux.

**Comment by 0xd4d** [comment]
This is a WPF application so it's for Windows only. To build it on Windows, have a look in the `build.cmd` file (netcore3.0 branch)

**Comment by stevemk14ebr** [comment]
Is the UI the only major blocking portion? I'm only interested in the de compiler being usable, if there's no hard dependencies i could strip that out into a command line application.

**Comment by 0xd4d** [comment]
There's dnSpy.Console.csproj you could compile, although I haven't tested it on .NET Core so don't know if it works.

**Comment by stevemk14ebr** [comment]
I followed your build script, confusingly msbuild wasn't in the path and referenced a 4.xx version, had to add the visual studio one instead for 16.xx for restore to work. Once i did that though the dnSpy.Contracts.Logic, dnSpy.Decompiler, and dnSpy.Decompiler.ILSpy.Core all built correctly into .dlls target for .netcore 3. This allowed me to simply add references to them in my own .NET core project and i gutted some of the code from the console app + console colorizer output and the result is a nice decompiler command line app for Unix!
