### ISSUE TITLE
Trying to debug .exe

### ISSUE THREAD

**Issue by MrFearLess98** [0xd4d/dnSpy#1172]
Greetings everyone,
This is the first time i use dnSpyv6.0.5(64 bit).
I am trying to debug .exe file,the problem is after debugging no result for the source code.
I check the hex editor but i read first that:
"**This program cannot be run in DOS mode.**"
![Capture](https://user-images.githubusercontent.com/52073639/59922675-f7072c80-9439-11e9-97b3-257bfcd20da4.PNG)
PS: I debug this file on dnSpyv6.0.5(32 bit) but i took the screenshot in dnSpyv6.0.5(64 bit).
Is there any possible way that i can reach the source code of this file ?

Thank you !

**Comment by Symbai** [comment]
You can only debug .NET files and yours look like it isn't. The text you mention is part of the standard executable header in windows, you can ignore this as it has nothing to do with your issue.

**Comment by MrFearLess98** [comment]
> You can only debug .NET files and yours look like it isn't. The text you mention is part of the standard executable header in windows, you can ignore this as it has nothing to do with your issue.

I got your point,but where can i debug this file to get the source code ?

**Comment by Symbai** [comment]
If it's not a .NET file it's impossible to get its source code without discussing the 0,001% where it still is (for example if its written in any other language that compiles at the time, such as Java, rather than compiles ahead of time, such as Delphi, C++, Assembly, etc.pp.)

**Comment by MrFearLess98** [comment]
As you mentioned before it's not .NET file. So no way to get the code. Anyway, thank you very much.
