### ISSUE TITLE
Restart as dnSpy-x64 / dnSpy-x86

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#1175]
In "attach to process" window the info label at the bottom could have a new button next to it to restart dnSpy in the different bitness. This saves some time when noticing the target process is not listed because it has a different bitness.

Quick paint demonstration of what I was thinking about:
![image](https://user-images.githubusercontent.com/14368203/59980154-5a7f8e80-95e1-11e9-9279-e11b71b94283.png)

**Comment by AndnixSH** [comment]
great idea!

**Comment by DeStilleGast** [comment]
I recognized this issue, I use dnSpy from the context menu and I always let it start the 64-bit version.
I thought that it could be a extension/plugin, so I made one (not as the same on your quick paint, but it works):
https://github.com/DeStilleGast/dnSpy-restart-as

**Comment by Symbai** [comment]
Nice, do you think you can add this to the attach to process window instead? Or if only in the main menu, then put it into the "File" menu? Also I would make sure to keep the arguments passed into dnSpy and start the other bitness version with it. I think that's what dnSpy does on its "Restart as admin".

**Comment by DeStilleGast** [comment]
I can look if I can move it under the File menu, but I cannot promise to add a button on that screen (not sure if you can add buttons on dialogs via extensions).

Are you sure that there is a function to restart as admin, I cannot find it

**Comment by DeStilleGast** [comment]
I am able to move it to the File menu:
![afbeelding](https://user-images.githubusercontent.com/3677706/60207640-a1c28500-9856-11e9-850b-5838770422a3.png)

do you like it ?

**Comment by Symbai** [comment]
> Are you sure that there is a function to restart as admin, I cannot find it
Hm I thought there was one 🤔

> do you like it ?
It's perfect, thanks!

**Comment by DeStilleGast** [comment]
I found a working way to add a button on the dialog (yes, it's done possibly in the most hacky way)
![](https://raw.githubusercontent.com/DeStilleGast/dnSpy-restart-as/master/img/img3.png)

everything is on my repo
