### ISSUE TITLE
Location with known extensions for dnSpy

### ISSUE THREAD

**Issue by DeStilleGast** [0xd4d/dnSpy#1178]
It would be nice to see some extensions/plugins that are easy to grab, perhaps in the wiki ?

This way can people share and find extensions more easy.

(just an idea, nothing more)

**Comment by Symbai** [comment]
How many extensions you already saw for dnSpy? I only found two via google, which both are posted in questionable places which I definitely think is not a great idea to link it here. And one on VS markplace, but that's it. Unless someone else correct me but I believe there aren't many public extensions. So there is nothing to update in the wiki. Either dnSpy offers already enough or it's too complicated to write an extension for it. If you are looking for a specific feature missing you can create a request here. If you don't have something specific missing but rather looking for some improvements you don't know already... maybe there are none? Although some suggestions have been made but yet again, I haven't found any extension that deals with them. So I'm not sure what should be written into the wiki at all.

**Comment by DeStilleGast** [comment]
I have found 3, but that doesn't matter. you can setup requirements or test it first before it gets "approved" to get in the (wiki extension) list.

about the point that there are not much public extensions, maybe because there no central place to show them off, I do believe that there are more extensions, and I would like to try and play with them.

I do have tried to make my own extension but it is currently far too complicated for me at the moment.

**Comment by 0xd4d** [comment]
```sh
$ find . -type f -name '*.x.dll' | wc -l
9
```

There used to be a wiki page but it was never updated so I removed it.

**Comment by 0xd4d** [comment]
I think this has been answered.
