### ISSUE TITLE
Kill thread

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#1179]
It would be great to kill a specific thread via right click on it if possible

**Comment by 0xd4d** [comment]
There's no ICorDebug API to kill managed threads, the only way would be to use eg. `TerminateThread` which will probably lead to all sorts of problems or call `Thread.Abort()` (safer but still bad). You can do that from the watch window if you really want to abort a thread.

**Comment by 0xd4d** [comment]
.NET Core doesn't support `Thread.Abort()`

**Comment by Symbai** [comment]
Ok, no problem, thanks!
