### ISSUE TITLE
Get memory location

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#1181]
When debugging an application, it would be nice to get the memory location of a specific property or method in a debugging process. I know that's its possible from some other tools that debug .NET applications, such as squalr, and it was incredibly useful. Just wish that it's implemented into dnSpy, unless it already exists and I'm missing it.

**Comment by glenn-slayden** [comment]
Resolved physical memory addresses will be subject to invalidation via GC movement. How do you expect the requested feature to behave in this regard?

**Comment by Symbai** [comment]
I have no expectation to this behave as it's not relevant for me. It's unlikely GC touches static properties and move them around in memory. It's unlikely GC touches methods when they are used, which is, the moment when I need such a memory location. The moments when GC deals with something is the moment when the subject is out of my interest. I said unlikely because there might be situations where this happens and such, but what's the point in this? I would see the memory at the given address has been altered by the GC, then I'm just getting the new address.

But to be able to get the memory location at all... that is something this request is about. At the moment I have to do manual changes to the object's property when the breakpoint got hit and search for them in memory in order to get its location. But I know that tools like squalr uses the .NET debugger to print out the location address directly. So it would save a lot of time and deals with static properties where the method I'm using doesn't work. And you cannot attach two .NET debuggers so I cannot use both tools at the same time. Which again brings me back to my request.

**Comment by 0xd4d** [comment]
What is the address of a method or property? The IL code? The metadata? The jitted code? The memory viewer (while debugging) can be used to go to a metadata token or IL body. The disassembler or call stack can be used to get the jitted address of a method.

**Comment by Symbai** [comment]
The jitted code for a method. On a static property its the location that holds the value.

**Comment by 0xd4d** [comment]
`Alt+8` opens the disassembler or right-click inside a jitted method to see the disassemble command, or `Ctrl+Alt+C` to open the call stack which shows the native address by default.

**Comment by Symbai** [comment]
I've tested it, works fine for my purpose. What about static properties? I cannot place a breakpoint there and open the disassembler.

**Comment by 0xd4d** [comment]
If the property has a getter/setter with a body, set a BP. If it's an auto implemented property, set a BP on `get` or `set` keywords. If the method/accessor has already executed you can just right click somewhere in the body (or on get/set) and disassemble it.

**Comment by Symbai** [comment]
This doesn't work most of the time. Although it has a getter / setter, it's never accessed by those. The breakpoint never hits. In such cases I've noticed that it's getting accessed directly by a memory address instead of calling the getter. 

Also when setting a breakpoint to the getter for creating a demonstration at this moment I've received this error message:

```
---------------------------
dnSpy
---------------------------
System.ObjectDisposedException: Cannot access a disposed object.

Object name: 'WpfTextViewLine'.

   at dnSpy.Text.Formatting.WpfTextViewLine.get_TextTop() in C:\projects\dnspy\dnSpy\dnSpy\Text\Formatting\WpfTextViewLine.cs:line 121

   at dnSpy.Text.Editor.GlyphTextMarkerServiceMouseProcessor.AddPopupContent(IWpfTextViewLine line, IGlyphTextMarker marker, FrameworkElement popupContent) in C:\projects\dnspy\dnSpy\dnSpy\Text\Editor\GlyphTextMarkerServiceMouseProcessor.cs:line 523

   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

```

**Comment by 0xd4d** [comment]
@Symbai Open a new issue, I can't repro it. You can also try the latest build and see if you can repro it again.

If the BP isn't hit, it's probably because the method has been inlined. Make sure the code isn't optimized (start it from dnSpy, and make sure you didn't uncheck 'suppress jit optimization' in the debugger settings.
