### ISSUE TITLE
Unclear usage of --member-order console parameter

### ISSUE THREAD

**Issue by tr808axm** [0xd4d/dnSpy#1182]
**Used version: `v6.0.5`**

I want to change the order of fields, methods, nested classes etc. in the decompilation and have figured out how to do it in the GUI. However, I want to use the console application and set an order for that.

When using the `dnSpy.Console.exe` application, a `--member-order (String)` option is displayed in the help manual but it does not show how to specify the order and neither throws any errors nor has any observable effect when used.

I have searched the source code and found the [definition of the parameter](https://github.com/0xd4d/dnSpy/blob/860fe7baa378e0aec445304809998a607edee823/dnSpy/dnSpy.Contracts.Logic/Decompiler/DecompilerOptionConstants.cs#L65) as well as [a serialization of the order](https://github.com/0xd4d/dnSpy/blob/840e826e6d2ec08e565b52077f22a69122533102/Extensions/ILSpy.Decompiler/dnSpy.Decompiler.ILSpy.Core/Settings/CSharpVBDecompilerSettings.cs#L235), but they do not seem to be connected.

In the settings XML file of the GUI application, the order is saved in four attributes `DecompilationObject[0-3]` ([code](https://github.com/0xd4d/dnSpy/blob/840e826e6d2ec08e565b52077f22a69122533102/Extensions/ILSpy.Decompiler/dnSpy.Decompiler.ILSpy/Settings/CSharpDecompilerSettingsPage.cs#L84)).

How do I use the parameter or is it even implemented?

**Comment by 0xd4d** [comment]
`GetMemberOrder()` concatenates the strings so a valid value is `tfepm` = nested types, fields, events, properties, methods

**Comment by tr808axm** [comment]
I have tried using
```
dnSpy.Console.exe --member-order pfmet -o C:\path\to\output-folder C:\path\to\file.dll
```
and fields are still at the end of the file. Is that intended?

**Comment by tr808axm** [comment]
I think the problem is that the `member-order` option is never parsed in the [`Program.cs` file](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy.Console/Program.cs#L442).

**Comment by 0xd4d** [comment]
Try `--src-order false`, it overrides the other option. Also use the .NET Framework build since I haven't tried dnSpy.Console.exe on .NET Core yet.

**Comment by 0xd4d** [comment]
It's `--no-src-order`

**Comment by tr808axm** [comment]
Alright, that does work. This should maybe be somewhere in the documentation.

Thank you, awesome work! 👍
