### ISSUE TITLE
Search methods in mixed mode assembly

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#1189]
- What version did you use?
dnSpy v6.0.5 (.NET Framework)

- Write down all steps needed to reproduce this issue. Also attach any needed files.

try to search for any method in mixed mode assembly

nothing found, but method(s) are inside, e.g.:

![image](https://user-images.githubusercontent.com/765343/60333230-215c6b00-99a1-11e9-8a15-07fa4efee7c9.png)

**Comment by 0xd4d** [comment]
Check your search options, maybe you enabled 'match whole words'

**Comment by greenozon** [comment]
**Bingo!**

I"ll leave it here as a hinter for upcoming questions like mine :)

![image](https://user-images.githubusercontent.com/765343/60388346-aab29100-9ab8-11e9-96da-0e108f1b3b63.png)
