### ISSUE TITLE
no foregrounding of dnSpy when breaking and option is set

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#1190]
- What version did you use?
dnSpy v6.0.5 (.NET Framework)
x86

- Write down all steps needed to reproduce this issue. Also attach any needed files.
dnSpy does not appear at front of all other windows when breakpoint being hit

this option is set as True:

![image](https://user-images.githubusercontent.com/765343/60335939-b19dae80-99a7-11e9-955f-5a288563ab55.png)

**Comment by 0xd4d** [comment]
Works for me (TM) so provide more info

**Comment by 0xd4d** [comment]
It repros with x86, I tested x64.

**Comment by 0xd4d** [comment]
VS can steal focus from any window. dnSpy can only do it if it's being debugged.

**Comment by greenozon** [comment]
Yeah, 
it's on x86  .net exe

I"m not having opened up VS

so why it works @x64  && !x86 :)

**Comment by 0xd4d** [comment]
See my two previous replies, it's not about x86 vs x64.

If you figure out how VS does it, send a PR or post it here.

**Comment by greenozon** [comment]
OK, pardon me, I didn't get your idea before...

**Comment by 0xd4d** [comment]
I got it to work, will add a commit later, assuming it still works.
