### ISSUE TITLE
Squares in class names and methods name

### ISSUE THREAD

**Issue by HamedOv** [0xd4d/dnSpy#1191]
- What version did you use?
6.5.0

- Write down all steps needed to reproduce this issue. Also attach any needed files.
On Assembly Explorer and in Code editor there are some squares instead of the method names:
```
// Token: 0x06000264 RID: 612 RVA: 0x00022324 File Offset: 0x00020524
		internal static void ᜀ(Func<string, bool> A_0)
```

these kinds of apps created in language like Persian or Arabic and it seems that this is the source of problem(using non standard character as I guess)
Here is another sample:
```
// Token: 0x0200003B RID: 59
	internal static class ᜀ
	{
		// Token: 0x0600025D RID: 605
		[DllImport("dwmapi.dll", PreserveSig = false)]
		public static extern void DwmEnableComposition(bool A_0);

		// Token: 0x0600025E RID: 606 RVA: 0x0002195C File Offset: 0x0001FB5C
		[STAThread]
		private static void ᜀ(string[] A_0)
		{

```
I would be very thankful if you take a look and improved this very nice application.
Thanks,

![Untitled](https://user-images.githubusercontent.com/39281068/60381103-8cbb4100-9a64-11e9-9660-12c7bf1f935b.png)

**Comment by HamedOv** [comment]
Also there are some problem in strings:
```
A_0.Where(SG.Shell.ᜀ.ᜆ).SingleOrDefault<string>();
							string text;
							SessionManager.Session[ucWindowSwitcher.b("臌ꃎ뛐臒냔Ꟗ뛘꧚꧜", a_)] = !string.IsNullOrEmpty(text);
							num = 7;
							continue;
```
I shows in East Asia language and I'm pretty sure it must be in Persian.

Thanks again,

**Comment by InlineAsm** [comment]
Your application is not written in Persian or Arabic. It is obfuscated so it's harder to read. Try to use De4Dot on your assembly to see if it recognizes the obfuscator and make things readable again.

**Comment by HamedOv** [comment]
Thank you so  much,
