### ISSUE TITLE
[help] patching mono-2.0-bdwgc.dll  

### ISSUE THREAD

**Issue by BothOfUsTogether2** [0xd4d/dnSpy#1193]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts) ok!

- What version did you use? release one

- Write down all steps needed to reproduce this issue. Also attach any needed files. ...-->

hello, how you doing? :)

I'm trying to debug a game for long time that compiled with unity with the mono-2.0-bdwgc.dll and doesn't have Unity.dll but no success.

I'm trying to debug with dnSpy without success:
1. Debug the exe (game process) - doesn't show any modules
2. attach process - the game process isn't listed there.

I followed everything here https://github.com/0xd4d/dnSpy/wiki/Debugging-Unity-Games
The game uses version 2019.1.3 and you didn't add it because it's too big, same question you told to compile this: https://github.com/0xd4d/dnSpy-Unity-mono
I did and also a reason I post issue here because I can't post on that repo

I downloaded the Unity Editor of exact version (2019.1.3) and inside the win32 directory(game and assemblies are 32 bit) I copied the UnityPlayer.dll and move it into game folder and also copied WindowsPlayer.exe and renamed it to the game name.

Example of UnityPlayer.dll

![(JPEG Image, 741 × 523 pixels)](https://user-images.githubusercontent.com/52379406/60398841-8c569f00-9b65-11e9-93a6-2a1afd4cf814.jpeg)
hence it's 2019.1.3

1. i cloned the repo https://github.com/0xd4d/dnSpy-Unity-mono (i had to wait so much for it to finish...)
1. i cloned the repo https://github.com/Unity-Technologies/mono.git
2. ran git checkout unity-2019.1 inside mono repo
3. ran C:\Users\user\Source\Repos\dnSpy-Unity-mono\src\umpatcher\umpatcher\bin\x86\Release\net472> .\umpatcher.exe 2019.1.3 3a543c233aa42c6a5c786118747d73140745427b C:\Users\user\Downloads\gitim\mono C:\Users\user\source\repos\dnSpy-Unity-mono
then i saw it downloading unity-2019.1.3 folder but then i stopped because it says error:
Git commit failed with error code 128 (Repo: C:\Users\user\Downloads\gitim\dnSpy-Unity-mono)

and there is where i stuck.
software i also used is viusal studio 2019/

someone tried same thing but did;nt know how to compile unity project he had VS2017..

can you please help?
PS: there is no vmono-2.0-bdwgc.dll iof version 2019.1.3 n git repo

**Comment by 0xd4d** [comment]
`Attach to Process (Unity)` is for debug builds only. You probably don't have a debug build so you should press `F5` and select debug engine `Unity` (to let dnSpy start the game) or `Unity (connect)` (if the game has already started).

> I copied the UnityPlayer.dll and move it into game folder and also copied WindowsPlayer.exe and renamed it to the game name.

Doesn't sound like it's a Unity game. You don't need to copy any Unity exe files.

**Comment by BothOfUsTogether2** [comment]
> `Attach to Process (Unity)` is for debug builds only. You probably don't have a debug build so you should press `F5` and select debug engine `Unity` (to let dnSpy start the game) or `Unity (connect)` (if the game has already started).
> 
> > I copied the UnityPlayer.dll and move it into game folder and also copied WindowsPlayer.exe and renamed it to the game name.
> 
> Doesn't sound like it's a Unity game. You don't need to copy any Unity exe files.

I've tried that and this is the result:
![image](https://user-images.githubusercontent.com/52379406/60400419-1f023880-9b7c-11e9-96fc-e3ed93302810.png)

as i mentioned before the game doesn't have Unity.dll but it has mono-2.0-bdwgc.dll 
you also said that newer Unity uses that dll here;
![image](https://user-images.githubusercontent.com/52379406/60400447-68528800-9b7c-11e9-84d5-426d92a6e80f.png)

my concern is to patch that dll so i will able to debug with dnSpy but that didn't work for some reason.
++ .Net assemblies like Assembly-CSharp aren;t encrypted.

**Comment by 0xd4d** [comment]
You have to compile the 2019.1.3 version of mono-2.0-bdwgc.dll and overwrite the existing file. Otherwise debugging won't work.

**Comment by BothOfUsTogether2** [comment]
> You have to compile the 2019.1.3 version of mono-2.0-bdwgc.dll and overwrite the existing file. Otherwise debugging won't work.

How and what do you mean to overwrite the existing file? can you elaborate about it please? I can't find solution dnSpy-Unity-mono-V40.sln tho


I followed this : https://github.com/0xd4d/dnSpy-Unity-mono
but on last it gave me an error
 Git commit failed with error code 128 (Repo: C:\Users\user\Downloads\gitim\dnSpy-Unity-mono)

my setup:
Windows 10
VS 2019

**Comment by 0xd4d** [comment]
> How and what do you mean to overwrite the existing file? can you elaborate about it please?

`mono-2.0-bdwgc.dll`

> I can't find solution dnSpy-Unity-mono-V40.sln tho

If you can't see it it means you didn't use the correct branch. Read the README again.

**Comment by 0xd4d** [comment]
I've uploaded compiled 2019.x files now, including the other missing files. You also need the latest build of dnSpy since the older versions can cause the 2019.x unity game to hang if you start it from dnSpy (and don't attach/connect to it)
