### ISSUE TITLE
New to Unity modding, issues setting up dnSpy

### ISSUE THREAD

**Issue by Cont3mplation** [0xd4d/dnSpy#1194]
Hi, just on my way to getting started with some basic unity modding, and heard about dlspy. Just installed the newest version to date, and got it installed and running. However, when I try to view the game's assembly.dll file, opening it in dnspy,  all I can see is the PE section with all of the headers and text data, rather than the game files themselves. There's a good chance I'm being dumb and have missed something, any help appreciated

**Comment by BothOfUsTogether2** [comment]
which game?
which dll?
please supply info
also read this: https://github.com/0xd4d/dnSpy/wiki/Debugging-Unity-Games
if the game has the file "mono-2.0-bdwgc.dll" and version >2018 unfourtantely there are no patched DLL and the instructions isn't working .. follow this issue and hope for good https://github.com/0xd4d/dnSpy/issues/1193
