### ISSUE TITLE
Old version of IlSpy?

### ISSUE THREAD

**Issue by Bartolomeus-649** [0xd4d/dnSpy#1197]
Could it be so that dnSpy uses a rather old version of ILSpy? I haven't found anywhere where it say which release of ILSpy that's used with dnSpy.

I see a lot of issues in the decompiled code i dnSpy that seem to not be there in the latest release of ILSpy.

**Comment by 0xd4d** [comment]
It's the latest 2.x release. See https://github.com/0xd4d/dnSpy/issues/936 if you want to send a PR.
