### ISSUE TITLE
The watched variable cannot removed

### ISSUE THREAD

**Issue by Ruskonert** [0xd4d/dnSpy#1199]
I using your .Net disassembler, dnSpy, running on Windows 10 x64 build 17134. it has been a great help in my work. Thank you all the time 👍 

However, while using various functions, there was Watch View that can be seen in IDE such as Visual Studio. I was able to find the following bugs using it:
![image](https://user-images.githubusercontent.com/32599113/60766986-e4ece580-a0eb-11e9-974c-0c20792d79e3.png)

It noticed that the bug was already registered in the previous issue, it seems to have the same symptoms in this version as well. When debugging was terminated, it remained in the list-box, and the variable name was empty, but it still could not be cleared.

There's no big trouble to use, But it is still annoying. I hope this bug is resolved as soon as possible.

Thanks :)

**Comment by Ruskonert** [comment]
using version: v6.0.5

**Comment by 0xd4d** [comment]
You can only add/remove from the watch window while debugging and the program is paused.

**Comment by 0xd4d** [comment]
Latest build has the fix for the missing text in the name column (it was a regression caused by new nullable reference types code).

It's also possible to remove expressions when you're not debugging.

**Comment by Ruskonert** [comment]
Thanks for your hard! 👍
