### ISSUE TITLE
Lastest version can't set the breakpoint

### ISSUE THREAD

**Issue by congviet** [0xd4d/dnSpy#12]
Lastest version can't set breakpoint, please check this ploblem. thanks

**Comment by 0xd4d** [comment]
Can't reproduce. Breakpoints work here without a problem.

**Comment by congviet** [comment]
Yes, i run dnspc.exe, the ploblem removed. Can you add context menu "Open new tab Ctr+T" in Search  and Analyris windows? thanks.

**Comment by 0xd4d** [comment]
Shift+DblClick
