### ISSUE TITLE
Propose of "Go To Disassembly" in disassembly view

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#1200]
What's the propose of the "Go To Disassembly" context menu item in the disassembly view? No matter where I click on it, it simply does nothing. At first I thought I could click on a call and jump to its disassembly but that didn't worked. Then I clicked nowhere and this context menu item still shows up.

**Comment by 0xd4d** [comment]
Set next statement also does not work in disasm viewer. Not sure if it's worth fixing.

**Comment by Symbai** [comment]
If it doesn't work and there is no intend to make it work I would simply hide it, unless that's what you meant with "not worth fixing it".
