### ISSUE TITLE
Is it possible to split part of an assembly ?

### ISSUE THREAD

**Issue by chucklu** [0xd4d/dnSpy#1205]
- What version did you use?
v6.0.5

- Write down all steps needed to reproduce this issue. Also attach any needed files.
I have an assembly, I want to split part of it.
![image](https://user-images.githubusercontent.com/3004057/61290143-b9f64600-a7fd-11e9-9ac9-cbdd721beb88.png)
For example, I have a library contains one interface and one implementation, and I want to split the interface into an independent new library. Then I can reference the new library with interface and implement it.

**Comment by 0xd4d** [comment]
No, your only option is to write some code to do that.

**Comment by chucklu** [comment]
OK, thanks for your confirmation.
