### ISSUE TITLE
Option `Single-click expands nodes` is invalid in Analyzer window.

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#1206]

**Comment by 0xd4d** [comment]
This option is in `Assembly Explorer` in the settings so it's no surprise. ;)

**Comment by CreateAndInject** [comment]
When I analyze something, there're a few results, I want to view one of results, so I double-click it, but dnSpy expands at the same time, the node may move to make sure sub nodes are visible, so the second click may click something other, so I want to disable it.

**Comment by CreateAndInject** [comment]
![1](https://user-images.githubusercontent.com/2529999/61318153-fbefae00-a836-11e9-8c31-aa275b99cef8.png)
I want to double-click the last node `InternalCreateDirectoryHelper`

![2](https://user-images.githubusercontent.com/2529999/61318268-3f4a1c80-a837-11e9-936d-f925e1f4ecba.png)
TreeView move the scrollbar to ensure the subnodes visible. so the node under the mouse is `Uses` not `InternalCreateDirectoryHelper`

Expected Behavior : double-click `InternalCreateDirectoryHelper`
Actual Behavior : single-click `InternalCreateDirectoryHelper` and single-click `Uses`
That's why I want to disable it.
