### ISSUE TITLE
Upgrade ICSharpCode.Decompiler.dll file

### ISSUE THREAD

**Issue by chucklu** [0xd4d/dnSpy#1208]
- What version did you use?
v6.0.5

- Write down all steps needed to reproduce this issue. Also attach any needed files.

Try to decompile the following exe file and got a crash error
> The exe file was packed in a zip file now.
> [Hearthbuddy.zip](https://github.com/icsharpcode/ILSpy/files/3387656/Hearthbuddy.zip)

The error was fixed [here](https://github.com/icsharpcode/ILSpy/issues/1570) , located in  ICSharpCode.Decompiler.dll

I have tried to replace the new version of  ICSharpCode.Decompiler.dll, and dnSpy show the following error.
![image](https://user-images.githubusercontent.com/3004057/61357120-4cecba00-a8aa-11e9-9a2b-cf7248efc975.png)

**Comment by 0xd4d** [comment]
There was no crash at all when decompiling that file. Provide more info.

You can't take any file and replace existing files. There are API changes etc.

**Comment by chucklu** [comment]
@0xd4d  I tried again and can not reproduce it now.
Not sure, maybe I mix the experience using ILSpy and dnSpy, sorry for that.
