### ISSUE TITLE
Tooltip for numeric constants with hex representation

### ISSUE THREAD

**Issue by GSPP** [0xd4d/dnSpy#1209]
When hovering the mouse over an integer constant in the decompiler window there should be a tooltip showing both decimal and hex representation. A motivating case is in `BitOperations.cs` of .NET Core 3:

![image](https://user-images.githubusercontent.com/12032350/61367585-3a638800-a88c-11e9-8b44-af7ef416c1c3.png)

These constants appear much less magical when expressed as hex.

This feature could be extended with other interesting information. For example, float numbers could be shown as sign, exponent and mantissa. Integers could be shown in binary.

For enums there already is a tooltip showing the hex representation. It should the decimal representation as well.

**Comment by 0xd4d** [comment]
Could you show an example of tooltips for floats/doubles?

Integers:
```C#
Base 2: 0001_0010_0011_0100_0101_0110_0111_1000
Base 8: 2215053170
Base 10: 305419896
Base 16: 12345678
```

**Comment by GSPP** [comment]
I was thinking something like the output of this IEEE float decoder: https://www.h-schmidt.net/FloatConverter/IEEE754.html
