### ISSUE TITLE
Support removing attributes prior analysis

### ISSUE THREAD

**Issue by AxDSan** [0xd4d/dnSpy#121]
Lately I've seen that whenever I analyse an assembly that is surrounded with [DebuggerHidden] or any of the other attributes, it will obviously do what it's meant to do, prevent the debugger from stepping through, or completely "jump" a section (in case of DebuggerHidden) is there a possibility to add a feature that could enable us to remove these attributes prior analysis, I know there is the Edit Method feature which allows... editing the method, duh, and it has the Custom Attrs tab which enables to Add Change or Delete attributes, however even with such feature I've had no success trying to remove those special attributes.

**Comment by 0xd4d** [comment]
dnSpy's debugger currently ignores those attributes so you don't need to do a thing. It will step into anything.

**Comment by AxDSan** [comment]
Ok i get it now, everything has to do with the assembly being obfuscated,
it does indeed steps through methods with those attributes when it's
deobfuscated. Thanks
