### ISSUE TITLE
Show stacktrace in unhandled exception dialog

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [0xd4d/dnSpy#1212]
I'm debugging a Unity DLL injector and the injected DLL crashes without being handled anywhere. dnSpy catches this, displays the error type and message, and opens a tab with the crash location, but doesn't show a stacktrace.

Screenshot of current behavior:
![current unhandled exception dialog](https://i.imgur.com/t4N3N00.png)

Proposed behavior:
Allow expanding the dialog to show the stack trace in a textbox with a monospace font, behind an expander that looks like this:
![expander example](https://i.stack.imgur.com/uOJIR.png)

**Comment by 0xd4d** [comment]
The stack trace isn't shown since the call stack can already show it.

**Comment by HoLLy-HaCKeR** [comment]
In my use case I can only get this dialog to appear by killing the debuggee, because I'm blocking the UI thread from within my plugin and it wouldn't get unblocked otherwise. Once it's killed I can't use the call stack window anymore. I guess that makes it a problem on my end so I'll fix the plugin to use async/await or something.
