### ISSUE TITLE
Can't see locals

### ISSUE THREAD

**Issue by CursedSheep** [0xd4d/dnSpy#1214]
- V6.0.5

- 1. Drag the file that i provided in to dnspy.
2. open the debugger and execute file.
3. it shows nothing in output, locals, and breakpoints doesn't work even in the first function that will be executed.
[VoteBot - A toplist voting bot-cleaned-cleaned9.zip](https://github.com/0xd4d/dnSpy/files/3413697/VoteBot.-.A.toplist.voting.bot-cleaned-cleaned9.zip)

**Comment by 0xd4d** [comment]
Which method doesn't show locals? I can't repro this.

**Comment by CursedSheep** [comment]
Any method.

**Comment by 0xd4d** [comment]
Since I can't repro it, but you can: test it on some other machine, install latest windows updates, install .NET Framework 4.8, use latest dnSpy build.

**Comment by CursedSheep** [comment]
oh, i have .NET 4.8 installed already and i am also using the latest dnspy build. i don't really know why dnspy doesn't give any output but im guessing its some another antidebug technique.

**Comment by 0xd4d** [comment]
This is not reproducible. Try it on some other machine.
