### ISSUE TITLE
dnspy Crash whit latest compiled Iced Library

### ISSUE THREAD

**Issue by Deltafox79** [0xd4d/dnSpy#1218]
Hi I have compiled latest **dnspy** of **Commits on Jul 21, 2019**  and latest **Iced** of **Commits on Jul 19, 2019** 

After replace new iced.dll into dnspy folder DnSpy Crash whit this error :

![Immagine](https://user-images.githubusercontent.com/2518850/61634007-a715c280-ac90-11e9-8abe-7aa8d1da8b71.jpg)

Regards

**Comment by 0xd4d** [comment]
You can't just replace any DLL with a newer version because there can be breaking API changes. That's what you're seeing.

**Comment by Deltafox79** [comment]
You're right, but I've done it so far, obviously respecting the version number of the references. I just wanted to let you know in anticipation of whether and when you will update the support for the latest versions of dnlib and iced on dnspy ​​.. because I don't think it has meaning not to update external libraries if they are not implemented and updated in a project that uses them. Thanks anyway for your releases.
