### ISSUE TITLE
zh-CN Translation issue: Remove incorrect translations

### ISSUE THREAD

**Issue by UlyssesWu** [0xd4d/dnSpy#1220]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
Latest build

- Write down all steps needed to reproduce this issue. Also attach any needed files.

I have noticed some issues about the recent zh-CN translations added by @l329978214 . The most specific one is that he added shortcut keys for almost all translations he made, even though there were no shortcut key in original text. Here is the example:

![dnspy-trans-issue](https://user-images.githubusercontent.com/4312781/61728261-73798c00-ada7-11e9-8e37-16c9fbe67bb0.png)

Almost all "Create ..." are assigned to C as shortcut key, which is unnecessary and troublesome.

For most of his translation, he also voted down for the correct one to make sure his translation will be choosed.

I believe these kind of translations made by him should be removed, and hope he would be banned for translation.

**Comment by 0xd4d** [comment]
I've sent this user a message.

**Comment by 0xd4d** [comment]
Should be fixed now.
