### ISSUE TITLE
Double clicking in the analyzer opens the tree view

### ISSUE THREAD

**Issue by pardeike** [0xd4d/dnSpy#1222]
When double clicking through many nodes in an analyzer result to show them in the current tab it opens the subnodes (Used by + Uses) for every row double clicked. I loose the current row and have to move the mouse several rows down to skip the subnodes and that is really annoying.

Right click on a closed node and choosing Show Reference in Method keeps the node as it is but I rather want a shortcut or double click.

**Comment by 0xd4d** [comment]
Try the latest build, there's an option to not expand the nodes when single clicking, if that's what you want.

**Comment by pardeike** [comment]
Not really. I fixed it and are about to send you a pull request for ICSharpCode.TreeView.

**Comment by pardeike** [comment]
Try building dnSpy with https://github.com/0xd4d/ICSharpCode.TreeView/pull/1

**Comment by 0xd4d** [comment]
The option I mentioned does exactly what you want. It doesn't expand the child nodes when you double click a node.

**Comment by pardeike** [comment]
I downloaded dnSpy v6.0.5 (.NET Core) and I cannot find that option for the life of me. You have hidden it well!

**Comment by pardeike** [comment]
Found it, it's in the Assembly Explorer pane called "Single click expands nodes". Tried it, even restarted dnSpy and made sure its off. Does not change the behaviour.

**Comment by pardeike** [comment]
https://youtu.be/jq4PJnN5f2c

**Comment by 0xd4d** [comment]
It's in the latest build, and it works for me, nothing gets expanded when I double click a node.

**Comment by 0xd4d** [comment]
That's an Assembly Explorer option, not an Analyzer option!

Get the latest build or build it yourself from source, right click inside the Analyzer window and you should see the option. There's not enough options to warrant a dialog box.

**Comment by pardeike** [comment]
In 6.0.5, when I right-click in the empty Analyzer window, I only get Copy(dimmed), Show Token and Syntax Highlight(checked). Once I right-click a method and choose Analyze I get the first node in the Analyzer window, right-clicking in the empty space below gives me a bit more options but none of them related to single click or anything option related. It seems that I get the context menu of the first preselected node and when I expand the calling nodes, I get the same options in the right-click when I click on those as well. 

In case you mean in the Options dialog, there is no Analyzer section or pane there in 6.0.5. So how do I find that option?

**Comment by pardeike** [comment]
Btw, I even looked in my source-compiled version and it is of course identical with the 6.0.5 release.

**Comment by 0xd4d** [comment]
Compile from master, if you don't see the option you're not compiling the current master. Try `git pull`

**Comment by pardeike** [comment]
I think I was under the impression that I build from your repo but I used an old fork of mine - sorry!
