### ISSUE TITLE
Unable to compile latest build Commits on Jul 27, 2019 

### ISSUE THREAD

**Issue by Deltafox79** [0xd4d/dnSpy#1224]
Hi I'm unable to compile Latest version of Dnspy Commits on Jul 27, 2019 .. Have 166 Error

I use VS 2019 whit latest Patch and have netcore 3.0 installed...

![Immagine2](https://user-images.githubusercontent.com/2518850/62011998-a2657880-b180-11e9-9ef0-34cd8063740f.jpg)

Any Fix?

**Comment by 0xd4d** [comment]
Use the latest version of VS, which is 16.2

**Comment by Deltafox79** [comment]
Thank you I will try I was not notified of the update.. Sorry
