### ISSUE TITLE
Hard to search string

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#1225]
When we analyze an assembly, the most thing we want to search is string, but the string is in the end of the combobox, and the shortcut(Ctrl+L) is hard to press use one hand.
I think the order should be:
Number/String
All of the below
......
And the shortcut is Ctrl+S

**Comment by 0xd4d** [comment]
The latest build remembers the selected search type so you don't even have to press Ctrl+L.

keyboard shortcuts: https://github.com/0xd4d/dnSpy/issues/243
