### ISSUE TITLE
Issue with code after compiled

### ISSUE THREAD

**Issue by Sillymonkey** [0xd4d/dnSpy#1226]
i tried to edit the method but the compiler failed. It's ok because the program I'm working it is huge and lot of classess, referrences. So I switched to IL instruction. The program assigns a datetime var with another var. I tried to edit it with 

`this.datetime_4 = new DateTime(2020,12,31);` into IL code.

Compiled success! but when I ran into the code it gave me an exception:

```
InvalidProgramexception Error Message: Common Language Runtime detected 
invalid program
```

**Comment by xsilent007** [comment]
What did you replace in the IL code, please clarify.

**Comment by Sillymonkey** [comment]
> What did you replace in the IL code, please clarify.

Here is it

![EditCshartp](https://user-images.githubusercontent.com/1243270/62378220-88f07200-b56e-11e9-90c7-a2b4b9a1b718.png)
![EditIL](https://user-images.githubusercontent.com/1243270/62378221-8a219f00-b56e-11e9-9657-68b9edd0ce8e.png)
![OriginalCSharp](https://user-images.githubusercontent.com/1243270/62378222-8aba3580-b56e-11e9-8e11-303407b43d65.png)
![OriginalIL](https://user-images.githubusercontent.com/1243270/62378225-8aba3580-b56e-11e9-8fb6-82426c86941a.png)

**Comment by 0xd4d** [comment]
`????????` is the token of the ctor you called and it's not known until you save the file.

**Comment by devops-technisian** [comment]
I am still having this issue. Even after saving the files, parts of the offset token show up as `??????` and I believe this is giving me a CRL Error and detects it as an invalid program. Thank you for you help.
