### ISSUE TITLE
Start dnSpy via command line with predefined file list possible?

### ISSUE THREAD

**Issue by dma7** [0xd4d/dnSpy#1229]
I'm using dnSpy 6.0.5

I'd like to start dnSpy with a specific context (i.e. list of assemblies) from command line. Is it possible? 

I've seen that dnSpy stores it's recent context in C:\Users\<username>\AppData\Roaming\dnSpy\dnSpy.xml, so I could generate that file via Powershell prior to start of dnSpy. 

Is there a better solution in place?

**Comment by Symbai** [comment]
Yes, you can simply use the inbuilt command line arguments: https://github.com/0xd4d/dnSpy/wiki/Command-Line-Arguments

**Comment by dma7** [comment]
I guess you mean the very first one "--settings-file <filename>"?

If so, looking into the settings file, I see there some twenty "section" elements, each one with a different GUID. Underneath one of them, I see the files loaded. Is there any description of the format available? Or an example for a minimal settings.xml?

**Comment by Symbai** [comment]
No, i meant this one https://github.com/0xd4d/dnSpy/wiki/Command-Line-Arguments#usage allowing you to start dnSpy with a list of assemblies which you asked for. You may combine it with this one `--dont-load-files / --no-load-files` to avoid dnSpy loading the last used files (although I haven't tested it if it works together).
