### ISSUE TITLE
Incorrect using statement syntax for VB

### ISSUE THREAD

**Issue by LightningDragon** [0xd4d/dnSpy#123]
`Using Dim fileStream As FileStream = File.Open(path, FileMode.Open, FileAccess.ReadWrite)`

Should be.

`Using fileStream As FileStream = File.Open(path, FileMode.Open, FileAccess.ReadWrite)`

`Using Dim` will give you "Error	BC30201	Expression expected."

**Comment by ViRb3** [comment]
I think you should report this to ILSpy team instead, because they maintain the decompiler engine.

**Comment by LightningDragon** [comment]
You talking about https://github.com/icsharpcode/ILSpy or is there a specific repo for the engine?

**Comment by ViRb3** [comment]
Yes, that should be it. You might want to confirm that the same issue exists with the original ILSpy before reporting.

**Comment by LightningDragon** [comment]
I gave it a test and it does. I'll open an issue over there in a bit.
