### ISSUE TITLE
No dnspy.exe

### ISSUE THREAD

**Issue by Ultrasnowstar** [0xd4d/dnSpy#1230]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
0xd4d
- Write down all steps needed to reproduce this issue. Also attach any needed files.
I downloaded the zip file and there was no dnspy.exe in the folder once it was extracted

**Comment by 0xd4d** [comment]
There's a whole bunch of files so search for `dnSpy.exe`.
