### ISSUE TITLE
"Instruction operand is null" for unobfuscated code.

### ISSUE THREAD

**Issue by CaioFrancisco** [0xd4d/dnSpy#1238]
Q - What version did you use?

A - 6.0.5.0 - Binary

Q - Write down all steps needed to reproduce this issue. Also attach any needed files.

A - There's a game called Duskers. I'm trying to mod it but there's an error "Instruction operand is null" that doesn't let me save the modified code. And no, there isn't any other error. I've checked with de4dot any kind of obuscation, but it doesn't find any, or he doesn't find one of the supported ones. There's a high chance of being code's fault. I've decompiled it and Visual Studio refused recompile the .dll, maybe because the code was made in 2017/2016. Anyway, i'm gonna send the .dll for analysis.

[Assembly-CSharp.zip](https://github.com/0xd4d/dnSpy/files/3484000/Assembly-CSharp.zip)

I appreciate any kind of cooperation.

**Comment by wwh1004** [comment]
BootScreen.LaunchBios (MDToken:0x060022CC) contains invalid operand (callvirt  <null>)

**Comment by 0xd4d** [comment]
Already answered.
