### ISSUE TITLE
"The new data is not an image" Error on image resources

### ISSUE THREAD

**Issue by InochiPM** [0xd4d/dnSpy#1245]
- What version did you use?
Version 6.0.5

Trying to change a resource that is clearly an image file but dosn't have the .image extension, when trying to change them i get this error. 
<img width="399" alt="Screen Shot 2019-08-15 at 10 39 10 PM" src="https://user-images.githubusercontent.com/13459080/63139837-b9dc9800-bfad-11e9-8bbf-0d6431c55618.png">

it doesn't matter what i change the extension to it will never replace the resource.

**Comment by InochiPM** [comment]
It never did this before when i changed resources before, i edited a while program with all of its resources and now i cant even change a single one at all.

**Comment by 0xd4d** [comment]
How do I reproduce this, does it happen with every image or just a few, if so attach an image here.

**Comment by nxrighthere** [comment]
@0xd4d I've encountered this problem with `dnSpy-netcore-win64.zip`, but `dnSpy-net472.zip` works fine (the latest version).

Here are a sample application and an image: [foldermonitor.zip](https://github.com/0xd4d/dnSpy/files/4273321/foldermonitor.zip)

Open the application, navigate to _Resources\NodeSoft.FolderMonitor.frmMain.resources‎_, try to replace the `$this.Icon`.

**Comment by 0xd4d** [comment]
This happens because the types (`Bitmap`/`Icon`) have moved to a new assembly in .NET Core.

**Comment by nxrighthere** [comment]
Nice, thanks.
