### ISSUE TITLE
C# Interactive error.

### ISSUE THREAD

**Issue by congviet** [0xd4d/dnSpy#1246]
I use the lastest build dnSpy x.x.1085 and get the error.

![image](https://user-images.githubusercontent.com/7296897/63205648-c3f7b700-c0d1-11e9-9618-320ecfa90018.png)

How can i fixed this problem? thank

**Comment by 0xd4d** [comment]
I can't reproduce this. Did you add some extra files to the dnSpy dir or some extension or something?

**Comment by congviet** [comment]
Yes, i add some extension. I try remove some extension and the errors don't display. Thanks
