### ISSUE TITLE
Collapse TreeView Nodes doesn't work if some subnode is selected.

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#1247]
The reason may be dnSpy select the node again.

I think dnSpy should select the root node or select nothing after Collapse TreeView Nodes.

**Comment by 0xd4d** [comment]
It's working as expected. Close all the other nodes that you've opened to clean it up. Collapsing everything isn't very useful, but if you want to do that, press HOME then collapse everything.

**Comment by CreateAndInject** [comment]
When analyzing a program, I will analyze so many methods to find the logic, when I find the final method, I want to know which assembly the method in, so I want to Collapse TreeView Nodes to go to the current assembly node.

**Comment by 0xd4d** [comment]
Hold down the Left Arrow key in assembly explorer or hover over the tab and read the tooltip.
