### ISSUE TITLE
error while compiling changes to assembly attributes while solving Decompiler generated variables can't be evaluated

### ISSUE THREAD

**Issue by reverser69** [0xd4d/dnSpy#1250]
- What version did you use?
6.0.5

- Write down all steps needed to reproduce this issue. Also, attach any needed files.
trying to solve Decompiler generated variables can't be evaluated and I found a way. when conducting it another problem rose up.

Line Error	BC30516	Overload resolution failed because no accessible 'New' accepts this number of arguments.

when trying to make a DLL debuggable by adding :
<Assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default , DebuggableAttribute.DebuggingModes.DisableOptimizations , DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints , DebuggableAttribute.DebuggingModes.EnableEditAndContinue)>

**Comment by 0xd4d** [comment]
Looks like you're missing the `|` operator, `Or` in VB, probably.
