### ISSUE TITLE
Debugger always breaks regardless where breakpoint is or if it was reached

### ISSUE THREAD

**Issue by Kein** [0xd4d/dnSpy#1257]
dnSpy 6.0.5
Unity 64b 2017.4.7, same debug mono lib used.

Here are my callstack and breakpoint:
![image](https://user-images.githubusercontent.com/623756/63937395-fa86e780-ca6a-11e9-97e6-b83aae322727.png)

They are absolutely not connected in any way yet breakpoint always being hit. Regardless where I place it.

**Comment by 0xd4d** [comment]
Try the latest build. If it still dosn't work, add a repro.

**Comment by Kein** [comment]
I did. Issue still happens but I cant pin-point why. The workaround if it happens is save the module, close dnSpy, restart and without doing ANY changes do the debug.
