### ISSUE TITLE
Please make `dnSpy.Console` buildable on mono.

### ISSUE THREAD

**Issue by PoroCYon** [0xd4d/dnSpy#126]
`dnSpy.Console` is not buildable on mono because it relies on WPF assemblies, even though they're (obviously) unused.

XBuild log: (command: `xbuild dnSpy.Console.csproj`)
https://transfer.sh/LxRkB/xbuild.log

~~Note: `dnSpy.Console` *built on Windows* appears to work on mono, but requiring Windows should be unnecessary.~~ *Wrong, GAC-related code is crashing (and I suspect it not being the only thing, just the first).*

**Comment by 0xd4d** [comment]
dnSpy.Console.exe should run on Linux/Mac, last time I checked it did, but I only use VS to build it, and won't update the code to support mono compiling it. You can grab the precompiled binaries from the build server.

**Comment by 0xd4d** [comment]
I've had a look,

- New mono ref asm paths (eg. `4.5-api`)
- mono doesn't support some WinForms ctors used by dnSpy
- GacInfo class doesn't work on mono

**Comment by 0xd4d** [comment]
Will be fixed in the next release.

**Comment by PoroCYon** [comment]
Ok, thanks!

**Comment by anthnyprschka** [comment]
Sorry n00b question but how do I execute a .exe file via the Terminal on Mac?

**Comment by 0xd4d** [comment]
[Tutorial](http://lmgtfy.com/?q=how+do+I+execute+a+.exe+file+via+the+Terminal+on+Mac)

**Comment by anthnyprschka** [comment]
Hey 0xd4d thanks for the hint ;) But i am still stuck. Running "./dnSpy.Console.exe" from the Terminal yields "cannot execute binary file". All other solutions I found involved setting up a VM which I do not plan on doing

**Comment by 0xd4d** [comment]
You need Mono to run this exe.

**Comment by sourceskyboxer** [comment]
Wait wait why do you not saythat? But dnSpy for Linux and Mac? Please remove stupid presentation frameworks!
