### ISSUE TITLE
 RoutedEventRecord has a bug

### ISSUE THREAD

**Issue by vmpsoft** [0xd4d/dnSpy#1262]
The order of fields in RoutedEventRecord::ReadData isn't equal of RoutedEventRecord::WriteData:

```
		protected override void ReadData(BamlBinaryReader reader, int size) {
			AttributeId = reader.ReadUInt16();
			Value = reader.ReadString();
		}

		protected override void WriteData(BamlBinaryWriter writer) {
			writer.Write(Value);
			writer.Write(AttributeId);
		}
```

**Comment by Kein** [comment]
You need to provide reproducible example

**Comment by vmpsoft** [comment]
Are you serious? Just look at the sources.

**Comment by 0xd4d** [comment]
Yes, and it also doesn't read and write `Reserved1`. You want to send a PR?

**Comment by vmpsoft** [comment]
https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Markup/BamlRecords.cs,cb7196ed823948a0

**Comment by josteink** [comment]
PR requested. PR provided.

Now can we close this silly bug? 😄

**Comment by 0xd4d** [comment]
It hasn't been fixed yet.
