### ISSUE TITLE
dnSpy fails to detect debug build of Unity if latter limited by firewall to local only scope

### ISSUE THREAD

**Issue by Kein** [0xd4d/dnSpy#1264]
**Info:**
- Using Latest master as of Septemer 03
- Unity game turned into debug build

**Issue**
Debugger fails to detect the debug build and connect

**Details**
I've limited the game to local scope/subnet so it can bind and send data locally but cannot do remote requests (outside of localhost). It works perfectly fine as I can find the port it opens for the debug data and **connect manually** via dnSpy, hovewer auto detection in the "Attach to Unity process" is unable to detect the game. This make no sense as there is nothing that limits the game broadcasting or binding ports and local addresses (it uses 0.0.0.0 which is essentially localhost here since it is all it can reach) and as i mentioned before I can connect manually just fine. So it must be something on dnSpy side failing to detect game properly.

Let me know if additional data required, I have setup for testing.

**Comment by 0xd4d** [comment]
It needs multicast to detect it, see https://github.com/0xd4d/dnSpy/blob/master/Extensions/dnSpy.Debugger/dnSpy.Debugger.DotNet.Mono/Dialogs/AttachToProcess/UnityPlayerAttachProgramOptionsProvider.cs#L61
