### ISSUE TITLE
Variables of type const are replaced by their value during decompilation

### ISSUE THREAD

**Issue by rlesch** [0xd4d/dnSpy#1266]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
latest at date of writing

-

it may be a noobish question but i have problems to track/find Variables of type const in the decompiled code when all of its occurencies are replaced with its value. And the value isnt updated anymore if the variable gets changed. (saved and reloaded)

is there any setting that prevents that and keep the variable instead of its content?

**Comment by 0x53A** [comment]
The variable is not replaced during **de**compilation, it is replaced during compilation by the C#/VB compiler.

**Comment by rlesch** [comment]
that makes ofc way more sense. thx.
