### ISSUE TITLE
Debugger: Support yield/async methods and lambdas

### ISSUE THREAD

**Issue by AxDSan** [0xd4d/dnSpy#127]
Replicate: Try to Debug through a TaskFactory Delegate. It will mark the whole area and stay pinned to that first Breakpoint and you won't be able to step through code.

Solution: Switch to IL, Debug a little bit, then back to C#/VB you will be able to Step Through.

**Comment by 0xd4d** [comment]
The debugger doesn't support yield/async methods yet. It's on my todo list. You're the only one who's mentioned it so far so most people don't notice it or don't care about this feature.

You can disable converting yield/async methods in the decompiler settings. That way you'll see C# code but it will look a little different.

**Comment by AxDSan** [comment]
Awesome, thanks for letting me know.

**Comment by DmitriyYukhanov** [comment]
Now at least 2 people here who would like to see yield/async methods debugging (including anonymous delegates debugging).

**Comment by ckhker** [comment]
need this too..

**Comment by ajqfju** [comment]
hi, I also want to know how to debug this

**Comment by tehNinth** [comment]
@Zhentar did this somehow, and the only differing ILSpy dll in his build and dnSpy is ICSharpCode.Decompiler -  
No idea if it's feasible to merge these two though...  
https://github.com/Zhentar/ILSpy/tree/master/ICSharpCode.Decompiler  
https://github.com/0xd4d/ILSpy/tree/d1fa0e682acb926b6d1c1757d1fec6c4e124e5c1/ICSharpCode.Decompiler

**Comment by 0xd4d** [comment]
@tehNinth That's not the issue. This is a about the debugger supporting iterators and async methods. It requires more debug info which I haven't added yet because I have to prioritize more important features. The decompiler iterator/async code was updated months ago, it now supports Unity assemblies (which uses mono C# compiler) and Roslyn iterators/async state machines.

**Comment by tehNinth** [comment]
@0xd4d  
Zhentar's version specifically adds support for iterators.

**Comment by 0xd4d** [comment]
>  I'm in the wrong issue aren't I...

Get the latest master build since it was updated in january to support mcs/roslyn iterators/async methods. I assume you're using the old v3.0.x build.

**Comment by tehNinth** [comment]
I'm running the latest build, I believe (x.x.558)

**Comment by 0xd4d** [comment]
If you have a problem with an iterator, open a new issue. It's possible that something's changed in the compiler generated code since last time I updated the decompiler.

**Comment by 0xd4d** [comment]
This has been fixed. Get the latest build from the build server
