### ISSUE TITLE
.ini Files And Debugging

### ISSUE THREAD

**Issue by Alois-xx** [0xd4d/dnSpy#1271]
The Wiki section about ini files is outdated. 
See https://aloiskraus.wordpress.com/2019/09/08/how-net-4-8-can-break-your-application/
how with a powershell script and disabling native images you can get the best of all worlds.

You are free to copy/adapt my script of course.

**Comment by 0xd4d** [comment]
Thanks! I've updated the wiki. The ini file also can't have a UTF8 BOM or it won't work.
