### ISSUE TITLE
Crashes on Win 1903

### ISSUE THREAD

**Issue by luka-dev** [0xd4d/dnSpy#1272]
**latest build** crashes on click '**File**', '**View**', e.t.c..., just instant close
OS: Windows 1903 18362.295
Tempory solution: delete update `KB4515384`

**Comment by InlineAsm** [comment]
Looks like this is something on your end. I have 1903 running on two computers with the latest patches and dnspy works as expected. I suggest you check your windows eventlog for exception information.

**Comment by sarbian** [comment]
If it helps I had a similar problem and the event log pointed me to d3d9.dll. It turns out that having MS Afterburner running crashes dnSpy. I added an exception in Riva Turner and now it works fine.

**Comment by 0xd4d** [comment]
I can't repro this either and I have installed KB4515384

**Comment by luka-dev** [comment]
Oh, its was really a problem of 'Riva Turner' and KB4515384.

Exception in 'Riva Turner' solve all problems.
