### ISSUE TITLE
Prevent DNspy from preventing you from saving edited code

### ISSUE THREAD

**Issue by Toxici11i** [0xd4d/dnSpy#1275]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
6.0.5
- Write down all steps needed to reproduce this issue. Also attach any needed files.
Write code that requires unityengine/other DLLs as functions (for example this.modDetails.OnlyContainsBugFixesOrUIChangesThatArentContriversial();).
Try to compile. Fail because software requires it to compile, and since you cant call it, you can never compile it

**Comment by Toxici11i** [comment]
The simple solution would just to add a "supress errors and save" option, but you dont seemingly want to do that according to https://github.com/0xd4d/dnSpy/issues/612

**Comment by 0xd4d** [comment]
If the compiler reports errors, there's nothing dnSpy can do about it. You just have to fix any errors. It's not possible to save (i.e., compile) without fixing all errors.

**Comment by 0xd4d** [comment]
If the method you want to call is declared in another assembly, include that assembly before compiling the code. Check the lower left corner of the editor, click the `add reference` icon, then compile the code.
