### ISSUE TITLE
[HowTo]Pasting instructions from outside of dnspy

### ISSUE THREAD

**Issue by omermumtazkaya** [0xd4d/dnSpy#128]
I couldn't understand which class you serialize and deserialize while copying and pasting instructions. I simply want to paste my custom instructions  that i copied from another exe to the "edit il instructions window" to make things easier for me. I will compile my own code. Turn it to the il code then i will paste it to the dnspy.

**Comment by 0xd4d** [comment]
The instructions aren't serializable, so you can't copy and paste instructions from some other process to dnSpy's process.
