### ISSUE TITLE
Reload All Assemblies & Saved Session fails to reload all Assemblies

### ISSUE THREAD

**Issue by Cyberbeing** [0xd4d/dnSpy#1282]
- What version did you use?

Issue seems to occur in all version of dnspy up to the latest cibuild.
Reproduced in 2.0.2.0, 3.0.0.0, 6.0.5.0, x.x.1095 ci build both normal and netcore builds.
Win7 SP1 x64 with .Net Framework 4.8

- Write down all steps needed to reproduce this issue.

**Currently Working as Expected**
* Drag all C# Assemblies from a Unity game `Managed` folder into dnspy window
* Drag the assembly you want to edit from a different folder, which is not a sub-folder of the first
* Edit C# code for an assemblies
* Functions from `using` modules are not in red and compiling succeeds

**Not Working as Expected (Saved Session)**
* Drag all C# Assemblies from a Unity game `Managed` folder into dnspy window
* Drag the assembly you want to edit from a different folder, which is not a sub-folder of the first
* Close and re-open dnspy
* Some assemblies previously loaded are not restored
* Edit C# code for a module
* If by chance `using` specifies a modules which dnspy failed to reload, as expected, some functions are in red and compiling fails with errors such as:
Type name " " could not be found in namespace " "
Type or namespace name " " does not exist in the namespace " "
The type " " is defined in an assembly which is not referenced
The name " " does not exist in the current context
and other similar errors.

**Not Working as Expected (Reload All Assemblies)**
* Drag all C# Assemblies from a Unity game `Managed` folder into dnspy window
* Drag the assembly you want to edit from a different folder, which is not a sub-folder of the first
* Reload All Assemblies
* Some assemblies previously loaded are not restored
* Edit C# code for a module
* If by chance `using` specifies a modules which dnspy failed to reload, as expected, some functions are in red and compiling fails with errors such as:
Type name " " could not be found in namespace " "
Type or namespace name " " does not exist in the namespace " "
The type " " is defined in an assembly which is not referenced
The name " " does not exist in the current context
and other similar errors.

**Workaround**
* Drag all C# Assemblies from a Unity game `Managed` folder into the dnspy window, once again
* Drag the assembly you want to edit from a different folder, which is not a sub-folder of the first (if by chance it also went missing)
* Edit C# code for a module
* Functions from `using` modules are not in red and compiling succeeds

**Comment by 0xd4d** [comment]
Can you attach all required assemblies?

**Comment by Cyberbeing** [comment]
After looking into this a bit more closely the bug is actually something more specific.

Rather than compile not finding assemblies, `Saved Session` & `Reload All Assemblies` are actually not reloading some assemblies at all. And since the assembly I'm editing is in a different folder then the dependencies, the ones which went missing do not get automatically loaded during dnspy decompile.  I didn't notice before, since it was below the scrollbar.

![before](https://user-images.githubusercontent.com/917535/65927322-24a33080-e3ae-11e9-86c3-3b4ff9d42667.png)

![after reloading](https://user-images.githubusercontent.com/917535/65927335-308ef280-e3ae-11e9-92df-990b9e50fc7b.png)

I don't have a good reduced test case for this at the moment. I'm basically dragging all 107 dll files from a Unity game's managed folder, plus an additional 10 from a different folder related to what I'm editing.

**Comment by Cyberbeing** [comment]
I've edited the reproduction steps, but I am having trouble figuring out the exact trigger for this. It seems to depend on what exactly I've dragged in, and what else is in the folder.

I seem to be able to reproduce it with the attached UnityEngine dlls:
[unityengine.zip](https://github.com/0xd4d/dnSpy/files/3674111/unityengine.zip)

**Comment by 0xd4d** [comment]
Should be fixed now, you can get the latest build from https://github.com/0xd4d/dnSpy/actions
