### ISSUE TITLE
How to change DnSpy Themes?

### ISSUE THREAD

**Issue by CharliezkieRBLX** [0xd4d/dnSpy#1289]
How to change DnSpy Themes? 

Please Comment..

- Thank You!

**Comment by SlowLogicBoy** [comment]
![Theme](https://user-images.githubusercontent.com/3121637/66374819-8702bf00-e9b4-11e9-82bd-c4200c6537eb.gif)

**Comment by SlowLogicBoy** [comment]
If you want to add another theme look [here](https://github.com/0xd4d/dnSpy/tree/master/dnSpy/dnSpy/Themes) `.dntheme` files
