### ISSUE TITLE
Setting COMPLUS_ZAPDISABLE=1 in the debugee (disable NGEN)

### ISSUE THREAD

**Issue by 0x53A** [0xd4d/dnSpy#129]
Hi,
first of all, thank you, dnSpy has saved me a few times already.

On one occasion I had the issue that Breakpoints were not hit inside System.Data.dll.
I think this was related to the DLL being NGENd.

What do you think about setting ``COMPLUS_ZAPDISABLE=1`` in the target process, so that NGEN gets disabled? As far as I know, the only downside is a one-time performance hit when it needs to JIT the code, so it could either be set by default, or just a checkbox added to the launch window.

The C# Team is considering the same for Visual Studio: https://github.com/dotnet/roslyn-project-system/issues/167

If you don't mind I can try to add this myself, but might take a bit until I have enough time.

**Comment by 0xd4d** [comment]
dnSpy's debugger disables optimizations when modules are loaded, and that seems to disable loading NGEN'd images except for a few cases (mscorlib, System, System.Core). Yes, If you want you can add a PR, assuming there's a checkbox to disable it in the debugger settings.

Breakpoint not being hit: do you remember where you put the breakpoint? One reason why a breakpoint isn't hit is that it's set at the wrong location, eg. in the middle of an "IL" statement.

```IL
ldc.i4.0
ldc.i4.0 ; can't set a BP here
call some method ; or here
```

**Comment by 0x53A** [comment]
Hm I can't actually reproduce the breakpoints not hitting, I just tried it again and now they are hit.

This is with the latest version, so either you fixed the issue in the meantime already (I think it was a few months ago) or maybe I had attached to an already running process (in which case this new setting wouldn't help anyway).

If I ever hit the issue again I will send a PR.
