### ISSUE TITLE
ILSpy 5.0.1 was released

### ISSUE THREAD

**Issue by arash88** [0xd4d/dnSpy#1290]
Hi guys, Thanks for all of your hard works.
As you my know ILSpy5 was released with lots of new perks! like new BAML decompiler and C# 8 Nullable Reference Types support!
Any news about integrating ILSpy5 into DnSpy?
Anyway Thanks a lot and godspeed.

**Comment by 0xd4d** [comment]
Duplicate of https://github.com/0xd4d/dnSpy/issues/936

**Comment by CreateAndInject** [comment]
@arash88 What's new BAML decompiler? Do you mean [Add BAML decompiler engine from dnSpy](https://github.com/icsharpcode/ILSpy/pull/1419)?
If that, the new BAML decompiler is converted from dnSpy, so why is this a reason for dnSpy to update to ILSpy5?

**Comment by 0xd4d** [comment]
@CreateAndInject I'm pretty sure he means the decompiler engine.

The BAML decompiler is open source (MIT licensed, written by Ki, the ConfuserEx author)

**Comment by CreateAndInject** [comment]
@0xd4d I don't find BAML decompiler in https://github.com/yck1509?tab=repositories
Do you mean BAML decompiler is a part of ConfuserEx?

**Comment by 0xd4d** [comment]
No he wrote it for dnSpy, see the original issue https://github.com/0xd4d/dnSpy/issues/1
