### ISSUE TITLE
Dll can't open in latest dnspy version

### ISSUE THREAD

**Issue by lyndmi** [0xd4d/dnSpy#1291]
- What version did you use? 6.0.5

- Write down all steps needed to reproduce this issue. Also attach any needed files.
latest dnspy won't open the file Assembly-CSharp-firstpass.dll. In older dnspy version 4.5.2 it can open it
So i checked in hex, it looks normal but something is not right. "This program cannot be run in DOS mode" is not there. I try to recover it, still won't open
I don't know why older version can open it so i created an issue

[Assembly-CSharp-firstpass.zip](https://github.com/0xd4d/dnSpy/files/3711057/Assembly-CSharp-firstpass.zip)

**Comment by SlowLogicBoy** [comment]
![image](https://user-images.githubusercontent.com/3121637/66548895-d2e76c80-eb4a-11e9-9721-c36515263458.png)

**Comment by 0xd4d** [comment]
Have you tried the latest build? https://github.com/0xd4d/dnSpy/actions

**Comment by 0xd4d** [comment]
Or the latest dnSpy build + the latest dnlib build: https://github.com/0xd4d/dnlib/actions

**Comment by CreateAndInject** [comment]
I test it, dnSpy really can't load it.

By the way, the dnSpy CI build contains 2 zip files, so I must unzip twice: dnSpy-net472.zip/dnSpy-net472.zip

**Comment by 0xd4d** [comment]
> By the way, the dnSpy CI build contains 2 zip files, so I must unzip twice: dnSpy-net472.zip/dnSpy-net472.zip

It's a github limitation, https://github.com/actions/upload-artifact/issues/3

**Comment by CreateAndInject** [comment]
But there's no such problem in de4dot CI build.

**Comment by 0xd4d** [comment]
> I test it, dnSpy really can't load it.

You didn't test the latest dnlib build. This was fixed a while ago.

**Comment by CreateAndInject** [comment]
Yes, I just load it with the lastest dnSpy. It uses dnlib nuget 3.2.
