### ISSUE TITLE
Switch numbers from Dec to Hex

### ISSUE THREAD

**Issue by gmgunderground** [0xd4d/dnSpy#1292]
Hi, compliments for the great work.
Is possible do show numbers in Hex or rapidly change from Dec To Hex and viceversa in the disassembler (c# code)? Sometimes hex representation is more intuitive than decimal.

Best regards

**Comment by 0xd4d** [comment]
There's no such option but you can hover over the number to see the hex string. Use the latest build.

**Comment by gmgunderground** [comment]
Yes, but you can't perform search in hex

**Comment by 0xd4d** [comment]
Feel free to send a PR

**Comment by GSPP** [comment]
It would be nice to have a toolbar button for quick switching. The Visual Studio debugger has a "hex" button that can be added to the toolbar.
