### ISSUE TITLE
Search should find inner types

### ISSUE THREAD

**Issue by GSPP** [0xd4d/dnSpy#1293]
The search feature should find inner types for example "iterator" should find `Enumerable.Iterator`.

**Comment by 0xd4d** [comment]
It does work, open mscorlib/system.private.corelib and search for Enumerator

**Comment by 0xd4d** [comment]
You should find eg. List<T>.Enumerator etc.

**Comment by GSPP** [comment]
Ah yes, it works. I looked in the wrong spot in the results list. I looked for "Iterator" and not "Enumerable.Iterator".
