### ISSUE TITLE
Can't build and several XDG0008 errors in Xaml

### ISSUE THREAD

**Issue by jmbyker** [0xd4d/dnSpy#1295]
I'm trying to build DNSPY, but keep getting errors. Mainly XDG0008 in XAML. I have visual studio updated. Can anyone help me?

**Comment by 0xd4d** [comment]
You need to add more info. What version of VS do you have installed, what did you try, what do you see, etc.

**Comment by jmbyker** [comment]
My version of VS is 2019 16.3.5. I've download the source code and run it.
![image](https://user-images.githubusercontent.com/23283696/67145325-a7662f80-f278-11e9-9bcb-189d2b4ea8dc.png)

This is the errors i get:
![image](https://user-images.githubusercontent.com/23283696/67145343-d2508380-f278-11e9-8378-d36be8ad5840.png)
72 errors in xaml.

**Comment by 0xd4d** [comment]
Those are warnings and this looks like a VS bug. Try restarting VS after building everything then build again.

**Comment by 0xd4d** [comment]
Make sure you have .NET Core 3.0 installed. And show the errors.

**Comment by jmbyker** [comment]
I have .NET Core 3.0
![image](https://user-images.githubusercontent.com/23283696/67164984-ecbd5680-f377-11e9-9a34-35e73687c888.png)

**Comment by jmbyker** [comment]
That type of errors are also showing in other codes that i have, specially codes that i have decompiled with DN or IL. I really need help, i'm stuck...

**Comment by 0xd4d** [comment]
Build instructions can be found in the Wiki.

If you still can't build it after following the wiki, show the errors.

**Comment by jmbyker** [comment]
I've downloaded again the source code. Unrar and open it. Try to build and get 79 errors. This is one of them:

![image](https://user-images.githubusercontent.com/23283696/67228541-5cdbe300-f431-11e9-9291-9e012152c60e.png)

This is other:
![image](https://user-images.githubusercontent.com/23283696/67228582-7c730b80-f431-11e9-9bfc-7693e14e0f5b.png)

I have visual studio up to date and .NET core 3 SDK.

**Comment by piratesephiroth** [comment]
check the wiki and tell me where does it say to download the zipped source code

https://github.com/0xd4d/dnSpy/wiki/Building-dnSpy

**Comment by jmbyker** [comment]
![image](https://user-images.githubusercontent.com/23283696/67272484-89850e80-f4b4-11e9-8248-bfc27ff49dbc.png)

Do i have to install Desktop?

**Comment by jmbyker** [comment]
Can't understand the issue:

- I've uninstall VS and reinstall it;
- I've downloaded again the zip
![image](https://user-images.githubusercontent.com/23283696/67285156-f5747080-f4ce-11e9-8a10-23c8d8c7bad0.png)

- Unlock the zip;
- Open sln in VS;
- Try to build and get lots of errors:
![image](https://user-images.githubusercontent.com/23283696/67285467-851a1f00-f4cf-11e9-8f7d-32edba976e73.png)

**Comment by 0xd4d** [comment]
You're not following the Wiki instructions.

This is not a dnSpy issue, you just need to learn how to do a clone of the repo that includes all submodules.

**Comment by manojdjoshi** [comment]
@jmbyker 
1 install Git from https://gitforwindows.org
2 install TortoiseGit from https://tortoisegit.org
3 
![Opera Snapshot_2019-10-24_071921_github com](https://user-images.githubusercontent.com/1886315/67446645-e3a9df00-f62e-11e9-8da7-1c5c5a0bfb26.png)
4 right click in any root drive or folder then click Git Clone on Context Menu new windows open from tortoisegit wait for complete action then click ok
5 right click on newly created folder(cloned repo folder) then click Git Sync on Context Menu 
6 click on submodule update  button on tortoisegit window  click close after Success message

**Comment by piratesephiroth** [comment]
Well, he can't even use git so I wonder why is he even trying to compile from source.

Shouldn't he just get the latest builds from https://github.com/0xd4d/dnSpy/actions instead?

**Comment by jmbyker** [comment]
Thanks @manojdjoshi for having the pacience to inlight those who do not master Git. Like in all things in life @piratesephiroth when we start, we do not have the knowledge needed to understand some issues that show up. Lukely, there's still some people who realize this and have no problem helping.
