### ISSUE TITLE
crash without dnSpy.exe.config

### ISSUE THREAD

**Issue by uragan1987** [0xd4d/dnSpy#1296]
- What version did you use?
last source
- Write down all steps needed to reproduce this issue. Also attach any needed files.
remove dnSpy.exe.config and start dnSpy.exe -> crash cause file is missed
works on dnspy3 fine

idea was, to hide dnSpy.exe from process scanners and just rename the application to 1.exe
after run 1.exe you get crash msgbox
add 1.exe.config will fix it, 
but why not check for settings file, and if there is no file, just create a new with default settings?

this will fix crash popup and you can rename exe how you want

**Comment by 0xd4d** [comment]
All binding redirects are in that file and are read by the runtime.

[This is the file](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy/MainApp/Constants.cs) that you should update before compiling your code.

**Comment by 0xd4d** [comment]
You should also update the assembly name in dnSpy.csproj and any other project files.
