### ISSUE TITLE
Where to report translate error?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#1298]
@UlyssesWu `分配者：`是不是打错字了？ `者`和`冒号`是不是都是打错了？
![image](https://user-images.githubusercontent.com/2529999/67513867-5027eb00-f6ce-11e9-8db1-e052bea5d30c.png)

**Comment by riQQ** [comment]
You can fix it here: https://crowdin.com/project/dnspy

**Comment by UlyssesWu** [comment]
There're always such guys who vote down for correct translations and append their inaccurate translations, and sadly we can do little thing about that - except vote up for correct translations.

This guy - https://crowdin.com/profile/15821317143 made 29 translations (including this) but they are either repeats or inaccurate (comparing to existed).

I've voted down for this translation and hopefully the corrected one will be shown in next version.

**Comment by 0xd4d** [comment]
Is that user's translations bad? If so I can delete them. I've made you a Proofreader so I guess you can approve translations now.

**Comment by UlyssesWu** [comment]
> they are either repeats or inaccurate (comparing to existed).

Thanks for the Proofreader approval. I've made the first translation approval for this string, now the translation is corrected to "被赋值于".

@CreateAndInject @riQQ 你们认为哪种翻译更好？或者还有更好的译法？
- 被读取于/被赋值于
- 被读取/被赋值

**Comment by CreateAndInject** [comment]
@UlyssesWu VS2019的`查找所有引用` 使用的是`读取`和`写入`
![image](https://user-images.githubusercontent.com/2529999/67548188-c9a5f480-f733-11e9-91e3-b5ab1405109f.png)

**Comment by CreateAndInject** [comment]
我觉得可以用 被读取/被赋值 或者 读取于/赋值于
而 被读取于/被赋值于 太长了且拗口

个人建议用 读取于/赋值于，因为“于”字隐含了：读取于(下列位置)

**Comment by UlyssesWu** [comment]
@CreateAndInject 已调整翻译为：
- Assigned by : 赋值于
- Read by : 读取于
- Used by : 被使用
- Uses : 使用
（如果Used by = 使用于，会和 Uses = 使用 更难区分）

如果有关于这几条文本的其他翻译建议请在 https://crowdin.com/translate/dnspy/11/en-zhcn#1883 讨论（欢迎at我）。

如果关于你指出的这几条文本没有问题了，别忘了关闭此issue。
If you're fine with these translations, don't forget to close this issue.

**Comment by CreateAndInject** [comment]
Thanks!

**Comment by CreateAndInject** [comment]
@UlyssesWu 
Overload => 重载
Override => 重写
![image](https://user-images.githubusercontent.com/2529999/69009663-9e10d580-0992-11ea-8d50-b5624cac8038.png)

**Comment by UlyssesWu** [comment]
Fixed in https://crowdin.com/translate/dnspy/11/en-zhcn#4727
