### ISSUE TITLE
dnSpy keeps adding bool flag = <example> and changes the if statement to use that flag instead of what i put in

### ISSUE THREAD

**Issue by christheboss894** [0xd4d/dnSpy#1299]
- What version did you use?

https://github.com/0xd4d/dnSpy/commit/2881dc8907fd8ff21d955421282dcd63c34afdd0/checks?check_suite_id=251879006
- Write down all steps needed to reproduce this issue. Also attach any needed files.

it was working fine before yesterday, but then it started to replace the if statements with
		bool flag2 = <example>
		if (flag2)
Edit Method > add an if statement > compile

**Comment by 0xd4d** [comment]
You're not using the latest build.

Looks like you disabled 'optimize code' in the compiler settings.

**Comment by CreateAndInject** [comment]
I found this a long time ago.
Just now, I test it:
```
            if (Environment.ProcessorCount == 8)
                Console.WriteLine("OK");
```
If build it with VS2010, no problem.
If build it with VS2017 (Roslyn?), dnSpy will decomiple it as:
```
	bool flag = Environment.ProcessorCount == 8;
	if (flag)
	{
		Console.WriteLine("OK");
	}
```
View IL:
```
	/* 0x0000025C 00           */ IL_0000: nop
	/* 0x0000025D 280F00000A   */ IL_0001: call      int32 [mscorlib]System.Environment::get_ProcessorCount()
	/* 0x00000262 1E           */ IL_0006: ldc.i4.8
	/* 0x00000263 FE01         */ IL_0007: ceq
	/* 0x00000265 0A           */ IL_0009: stloc.0
	/* 0x00000266 06           */ IL_000A: ldloc.0
	/* 0x00000267 2C0B         */ IL_000B: brfalse.s IL_0018

	/* 0x00000269 7201000070   */ IL_000D: ldstr     "OK"
	/* 0x0000026E 281000000A   */ IL_0012: call      void [mscorlib]System.Console::WriteLine(string)
	/* 0x00000273 00           */ IL_0017: nop

	/* 0x00000274 2A           */ IL_0018: ret
```
VS2017 will generate a bool variable.

There's no such issue, maybe need a transform in dnSpy.

**Comment by christheboss894** [comment]
@0xd4d that fixed it, thank you.
wdym im not using the latest build?
i downloaded it from the actions thingy
