### ISSUE TITLE
@operator decompilation error in C#

### ISSUE THREAD

**Issue by AboAnas1992** [0xd4d/dnSpy#13]
for example
// System.Drawing.Point
public static implicit @operator PointF(Point p)
{
	return new PointF((float)p.X, (float)p.Y);
}

noting that ILSpy 2.3 that dnSpy was forked from decompiles it as
public static implicit operator PointF(Point p)
{
	return new PointF((float)p.X, (float)p.Y);
}

**Comment by 0xd4d** [comment]
Should've been fixed 8 days ago. Have you tried latest build?

**Comment by AboAnas1992** [comment]
I only tested the latest release, I'll test the latest build and I'll close the issue
