### ISSUE TITLE
Unmanaged executable with embedded managed code

### ISSUE THREAD

**Issue by JillCrungus** [0xd4d/dnSpy#1302]
I'm trying to poke around in a game built on .NET Core and MonoGame. The problem is that the game's managed code is packed into an unmanaged EXE which dnSpy can't seem to deal with.

![image](https://user-images.githubusercontent.com/32760843/67678458-8be8dc00-f97e-11e9-8ec8-20b108ed01a5.png)

How would I go about decompiling something that's packed in this way?

**Comment by Symbai** [comment]
You cannot decompile an unmanaged executable with dnSpy. As you say its a mono game my guess is that it may be using il2cpp https://docs.unity3d.com/Manual/IL2CPP.html? In this case the source code is "gone" => has been converted to native code. There are il2cpp dumper but they don't decompile the source code instead under best circumstances only reconstruct the .NET structures for you as that's all the il2cpp has left for _you_ (for developers when generating crash reports).

DnSpy cannot help you.

**Comment by JillCrungus** [comment]
It's not a Unity game. It's built on the MonoGame framework.

The ".managed" section in the executable led me to believe the managed code
may still be present but embedded and wrapped by the unmanaged executable.

**Comment by 0xd4d** [comment]
Unless you can find the real .NET metadata, that's the only thing dnSpy can show you. Use the hex editor to check if the .managed section has the metadata.
