### ISSUE TITLE
Compile Bug

### ISSUE THREAD

**Issue by HokageHack** [0xd4d/dnSpy#1303]
i Use version v6.0.5. dnSpy-netcore-win64

Hi i have problem i compile and dnSpy Show This error
![image](https://user-images.githubusercontent.com/57195302/67894029-0a4ca600-fb58-11e9-9dd1-04b44a9cd722.png)

I Tried Everything But I Don't Know How To Fix The Bug Causes When I Want To Reload The Assembly This Is Null Empty

**Comment by 0xd4d** [comment]
Please provide a repro.

Are you using the latest version or the latest build? Try the latest build.
