### ISSUE TITLE
Assembly-CSharp.dll Issue

### ISSUE THREAD

**Issue by rings10** [0xd4d/dnSpy#1306]
please help me this issue im new using dnspy
![Untitled](https://user-images.githubusercontent.com/54752813/68072108-e1791a80-fdbc-11e9-93e3-e87a6d9fa729.jpg)

**Comment by Symbai** [comment]
This "issue" means that the file Assembly-CSharp.dll does not exist... if that's the "issue" you're reporting to us. Otherwise a bit more information would be required.

**Comment by papajohn9185** [comment]
i am really really really new to this as you can tell.  i am trying to crack a file that has ConfusedEx or something. you can find the type of file on youtube search up “Growtopia save.dat stealer”

**Comment by 0xd4d** [comment]
It's not a supported file so use some other program.
