### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by papajohn9185** [0xd4d/dnSpy#1307]
hello guys i am new to all of this. i am trying to hack a file that has anti tamper and on youtube it says i need dnSpy 3.0.0 or 1.0.0 x86. where can i find these files? please let me know thank you!!

**Comment by Symbai** [comment]
You can find the latest x86 releases here: https://github.com/0xd4d/dnSpy/releases/download/v6.0.5/dnSpy-netcore-win32.zip but I don't think they will help you that much. You may want to learn about anti tamper first and why dnSpy is recommended to you as when you don't understand why, dnSpy cannot help you at all.

**Comment by papajohn9185** [comment]
> You can find the latest x86 releases here: https://github.com/0xd4d/dnSpy/releases/download/v6.0.5/dnSpy-netcore-win32.zip but I don't think they will help you that much. You may want to learn about anti tamper first and why dnSpy is recommended to you as when you don't understand why, dnSpy cannot help you at all.

can you teach me how to crack a file that uses ConfuserEx?

**Comment by piratesephiroth** [comment]
This is a place for reporting problems or requesting features (that will probably be refused 🤣).
Please do not ask for tutorials.

**Comment by 0xd4d** [comment]
Only the latest release is available. If you want an older version, compile it yourself.
