### ISSUE TITLE
Locals -> Copy Value - Add support for arrays

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#1309]
I'm debugging an application and a local value is a byte array I chosen to display hex decimal values. I noticed that copying the value only copies the visual text which will be `{byte[0x00000040]}` but not the array content.

This is quite annoying because when I want to copy an array I usually want to copy the array content not the array count to clipboard. Do I miss something or can this be improved?

**Comment by XODE0** [comment]
You can use Memory window for that
1-Go to your local variable
2-Show In Memory window and select the window you want
the array content will be selected now copy it using "Copy Special" -> Copy C# Array

**Comment by 0xd4d** [comment]
You can also save the byte array to a file (right-click the variable and then `Save`)

**Comment by Symbai** [comment]
> 
> 
> You can also save the byte array to a file (right-click the variable and then `Save`)

Does this also work for any other array type like int, string, char? Byte array was just an example...

**Comment by 0xd4d** [comment]
byte[], int[] any[].
