### ISSUE TITLE
Roslyn GetDocumentationCommentId and dnSpy "/navigateTo" compatiblity

### ISSUE THREAD

**Issue by wangzq** [0xd4d/dnSpy#131]
Roslyn has an API that returns the xml documentation id for a symbol, which works for most cases when I just pass this to dnSpy "/navigateTo" parameter to accurately locate the symbol in dnSpy; however, for generic types' members, this doesn't seem to work.

If this can work, it can be very useful for tools like Omnisharp-Roslyn, which can directly jump to disassembled code in dnSpy from tools like Vim and Visual Studio Code.

**Comment by 0xd4d** [comment]
There's no `/navigateTo` command line option (there's a `--select`  though).

Which XML doc names aren't working, do you have an example? The current parser is here if you're interested in debugging it: https://github.com/0xd4d/dnSpy/blob/master/dnSpy.Shared/Languages/XmlDoc/XmlDocKeyProvider.cs

**Comment by wangzq** [comment]
My bad, I must be confused with the old switch from ilspy; yes I meant to say "--select" switch. 

The simplest example is `var x = new List<int>();` if I put cursor at the `List`, Roslyn's xml id will be `M:System.Collections.Generic.List{System.Int32}.#ctor`, which currently doesn't work in dnSpy:

    dnspy.exe "c:\windows\microsoft.net\framework64\v4.0.30319\mscorlib.dll" --select "M:System.Collections.Generic.List{System.Int32}.#ctor"

**Comment by wangzq** [comment]
FYI: my experiment in Omnisharp-Roslyn to jump to disassembled code in dnSpy, where you can find about the Roslyn symbol and xml id API: https://github.com/wangzq/omnisharp-roslyn/blob/dev/src/OmniSharp.Roslyn.CSharp/Services/Navigation/GotoDefinitionService.cs#L100

**Comment by wangzq** [comment]
Looks like more of Roslyn issue: dnSpy is correct to have the same xml id in documentation xml file, it seems Roslyn's implementation will include the actual data type which doesn't seem to be correct; and it seems this issue only occurs to the constructor, to static methods with generic parameters it is correct.

**Comment by wangzq** [comment]
FYI: I created an issue in Roslyn: https://github.com/dotnet/roslyn/issues/11687
