### ISSUE TITLE
Question: Does dnSpy use reflection for decompilation?

### ISSUE THREAD

**Issue by huettenhain** [0xd4d/dnSpy#1310]
I did not know where else to ask this question, I am sorry if this is the wrong spot. I also could not find a previous answer to this question; again, I am sorry if I missed it.

I use dnSpy to reverse engineer malware and contemplate teaching classes on how to do it. In order to better estimate the risks of doing this outside of a virtual machine on a Windows host (I am aware of many of the risks that _do_ exist), I would like to know whether the dnSpy decompilation _by itself_ uses any reflection, i.e. whether (untrusted) code from the source file is being executed at any point, in any way, when a file is loaded into dnSpy and navigated/edited in the decompiled view.

**Comment by 0xd4d** [comment]
The decompiler uses dnlib which only reads the metadata from the file. There was an option to deserialize the resources which could load the assemblies into memory but that option has been disabled.

But you should always use some virtual machine if you're analyzing malware.

**Comment by huettenhain** [comment]
I understand and agree with you 100%, but I have been asked the question of whether they "have to use a VM" before. I prefer to know the exact risks so I can explain them truthfully and not just talk around the issue vaguely; it tends to be more convincing. In the end, everyone must decide for themselves what risks to take. Also, I was curious to know whether my understanding of the code was correct - I did not find any signs of reflection being used, thanks for confirming this :-).
