### ISSUE TITLE
how do i do this?

### ISSUE THREAD

**Issue by papajohn9185** [0xd4d/dnSpy#1312]
how can i edit something like this?
![asdasda](https://user-images.githubusercontent.com/57297245/68446065-a191a900-01a9-11ea-985c-11e9c710bf3a.png)

**Comment by papajohn9185** [comment]
accident

**Comment by papajohn9185** [comment]
to become something like this
![Annotation 2019-11-07 220203](https://user-images.githubusercontent.com/57297245/68446268-47ddae80-01aa-11ea-98a1-9dc007be0604.png)

**Comment by papajohn9185** [comment]
edit: there is no assembly. how can i retrieve the assembly? is it possible to?

**Comment by papajohn9185** [comment]
edit: i think i got it

**Comment by papajohn9185** [comment]
okay now i need help. when i press "start" to debug, it gives me error saying it cant debug due to a virus or threat or whatever

**Comment by 0xd4d** [comment]
It warns you if the file doesn't have an exe extension, in case it's a renamed exe file. Just rename it or ignore the warning.
