### ISSUE TITLE
No Edit Method option

### ISSUE THREAD

**Issue by barankaplan7878** [0xd4d/dnSpy#1316]
I use 6.0.5

Edit Method option isn't there. How can i edit this code?
![image](https://user-images.githubusercontent.com/57641380/68618388-3e21b700-04da-11ea-8bd1-a264a760b9d7.png)

**Comment by 0xd4d** [comment]
That's a constant and not a method.

Constants are inlined when compiling code so even if you changed the value, any code that referenced the constant won't be updated to use the new value.

**Comment by barankaplan7878** [comment]
So even if i edit it will nothing change? And how can i edit the enum type?

**Comment by 0xd4d** [comment]
Edit the type. But it's not very useful since they're all inlined constants.

```C#
enum E { A, B }
...
var e = E.B;
```

will be compiled to:
```C#
E e = 1;
```

There's no reference to E.B in that code. Change B to 2 and the code will still set e to 1 until you recompile the code.

https://github.com/0xd4d/dnSpy/issues/1151
