### ISSUE TITLE
Feature: Replace method body with raw method bytes & more

### ISSUE THREAD

**Issue by Panthere** [0xd4d/dnSpy#132]
Would be super handy when restoring methods from dynamic calls to be able to simply replace the method from a (all in raw bytes) signature, body and exception handlers.

**Comment by 0xd4d** [comment]
The hex editor can do this. You won't see any changes until you save it and re-open the file, though.

You can right-click the method and use "Hex Paste Method Body". You won't see that command if the number of bytes you want to copy to the method is greater than the length of the method.

**Comment by Panthere** [comment]
Yeah, that's the problem, the method generally is way larger than the current one (which is ~5 instructions or so normally). I did try the hex way, didn't work out so great :)

**Comment by 0xd4d** [comment]
Do you have data from a dynamic method that you want to paste? If so, you can't just paste that data since its tokens are relative to some internal data structures. If however the tokens in those instructions are valid in the metadata of the module, then it should be possible to paste that into the IL editor, I'll just have to implement that code sometime.

**Comment by Panthere** [comment]
Yeah, it's for the current module, it's built from a dynamic method (setting the code, exceptions and local sig through DynamicILInfo).

**Comment by 0xd4d** [comment]
How did you get this data? During debugging?

You could use dnlib's [DynamicMethodBodyReader](https://github.com/0xd4d/dnlib/blob/master/src/DotNet/Emit/DynamicMethodBodyReader.cs) to do this programmatically.

**Comment by Panthere** [comment]
I've been looking at the reader, I'm quite sure it's just me but I cannot seem to actually get a valid method body out of it.
The instructions are always null even though the code size is 300+ bytes.

**Comment by 0xd4d** [comment]
Closing this. Seems to be of limited use, it's better to use dnlib for these kinds of tasks.
