### ISSUE TITLE
Virual Studio 19 Version 16.1.6 (Says its too old to open source)

### ISSUE THREAD

**Issue by bmgjet** [0xd4d/dnSpy#1320]
Trying to open in latest version of source and VS. Complains that its too old to open.
Edit the .sin to ignore the date.
Opens but then says its unloaded every project file.

**Comment by 0xd4d** [comment]
Did you follow this: https://github.com/0xd4d/dnSpy/wiki/Building-dnSpy

**Comment by syntroniks** [comment]
I had this issue with 16.4.0 Preview 6.0 after changing the core SDK from 3.0.100 to 3.1.
VS 2019 Community 16.3.10 works fine

**Comment by 0xd4d** [comment]
The latest stable version of VS is supported and it's currently 16.3.x. @bmgjet You need to update your VS.
