### ISSUE TITLE
VB.NET DLL - decompiler doesn't handle some expressiontrees and exits early

### ISSUE THREAD

**Issue by bgilbert6** [0xd4d/dnSpy#1321]
Some VB.net DLL code doesn't properly decompile the expressiontrees from EF:
![image](https://user-images.githubusercontent.com/10503884/69359864-13a8ca00-0c4f-11ea-8830-3efc08e1380f.png)

I have a pull request that fixes this issue in the ILspy submodule

**Comment by 0xd4d** [comment]
Was fixed yesterday so closing it.
