### ISSUE TITLE
Break on module load

### ISSUE THREAD

**Issue by Peridon** [0xd4d/dnSpy#1323]
Using dnSpy v6.0.5 (.NET Core), latest build as of 15.11.2019.

I can't find way to break on module load or unload when using debugger, however module window correctly updates when modules change.

**Comment by Gusted** [comment]
Easy to do this just set a breakpoint on the first code that the method execute unload? I don't know...

**Comment by 0xd4d** [comment]
Open the module breakpoint window and add the module name.
