### ISSUE TITLE
Values in locals tab in dnspy

### ISSUE THREAD

**Issue by Crisbyte** [0xd4d/dnSpy#1324]
Hi, since I was not able to unpack agiledotnet, I managed to solve the problem in this way, I put some breakpoints and then when I see the values with dnspy in the rooms I modify it manually according to the screenshot, I wonder , is there a way to make the change permanent? or in any case make the change automatically? it would be very useful if you could do some sort of command by creating a .bat file so that it inserts the breakpoints and then modifies the values as in the photos I attach.[Image 1](https://drive.google.com/file/d/1vvn0lBfgkhfvMa3KOwwqV3jX8yTIOmxP/view?usp=drivesdk) [Image2](https://drive.google.com/file/d/1lUg5QdtnexCcVm-dZn_u9eP8Nrh9LpNU/view?usp=drivesdk) [Image 3](https://drive.google.com/file/d/1tryTjk1TNNZKAbAyGIYdxfLLnoAryNEv/view?usp=drivesdk)

thanks

**Comment by 0xd4d** [comment]
This isn't a feature I'll add. You can write an extension to do it.

**Comment by Crisbyte** [comment]
Ok but you can send me an example please
