### ISSUE TITLE
It's something you have to write yourself.

### ISSUE THREAD

**Issue by Crisbyte** [0xd4d/dnSpy#1326]
It's something you have to write yourself.

_Originally posted by @0xd4d in https://github.com/0xd4d/dnSpy/issues/1325#issuecomment-558587035_

I am certainly convinced that I have to do it alone, I would like to understand just how to write the extension for dnspy ​​because there are no instructions on the net, and above all how to interact with breakpoints, even on this there are no guides on the internet.  thanks don't close the post please
how do I recall then the dos command extension without displaying dnspy?

**Comment by 0xd4d** [comment]
Don't open new posts. Reply to the original issue.

Check the examples directory and read the source code. That's the only way.

**Comment by Crisbyte** [comment]
Sorry i understand, where do I find the folder you are talking about?  there is some guidance on how to use extensions and how to interface with breakpoints?thanks
