### ISSUE TITLE
SmartScreen warning / code signing

### ISSUE THREAD

**Issue by RussKie** [0xd4d/dnSpy#1328]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?

v6.1.0

- Write down all steps needed to reproduce this issue. Also attach any needed files.

Download the latest https://github.com/0xd4d/dnSpy/releases/download/v6.1.0/dnSpy-netcore-win64.zip, unzip, run
![image](https://user-images.githubusercontent.com/4403806/69839259-e2617700-12aa-11ea-8ed4-d215c1e4c29c.png)

The SmarScreen hasn't built a reputation for this build, so users will see the warning.

I recommend to reach out to [SingPath.io folks](https://twitter.com/SignPathIO) and, I'm sure, they'll hook you up with a code signing cert for free.

/cc: @stefan-wenig

**Comment by 0xd4d** [comment]
`Windows protected your PC` :) MS trying to scare people from using open source software.

I don't want to sign it, I can wait until MS updates its SmartScreen software. There's nothing wrong with dnSpy.

**Comment by RussKie** [comment]
I'm puzzled as to why you wouldn't want sign it.
That's a way to alienate your users.

And Windows isn't working against OSS, I'm sorry you feel that way

**Comment by 0xd4d** [comment]
> That's a way to alienate your users.

MS is doing that already with their SmartScreen messages.

I only need to sign it because MS SmartScreen is claiming it protected their PC. Implying that dnSpy is malware.

Once again, there's nothing wrong with dnSpy. It's SmartScreen that needs to be fixed.

**Comment by 0xd4d** [comment]
I'll close this. I don't plan on signing dnSpy. It's open source software. The bug is in SmartScreen.
