### ISSUE TITLE
Could not create the breakpoint

### ISSUE THREAD

**Issue by vandurenm** [0xd4d/dnSpy#1329]
hi,

what's the reason my third breakpoint cannot not be created (see screenshot) in the HtmlEncode method of the System.Web.HttpUtility class? What do I need to do to be able to hit that line?
I'm using dnSpy v6.1.0 (.NET Framework)

![image](https://user-images.githubusercontent.com/30691026/69891754-35651980-12ff-11ea-90e7-eea8c4e9a0d7.png)
![image](https://user-images.githubusercontent.com/30691026/69891931-92ad9a80-1300-11ea-9db6-e20632efaa61.png)

thanks  (great tool!)

**Comment by 0xd4d** [comment]
It could be optimized code (either IL or machine code). You can try to switch to IL view and try to set a BP on  an instruction until it works. If it doesn't, it means the jitter never added a sequence point to any of the remaining instructions and you can't set a BP.
