### ISSUE TITLE
IL literals

### ISSUE THREAD

**Issue by justin-gerhardt** [0xd4d/dnSpy#133]
I would greatly appreciate the ability to display to display literals in the il instruction editor as decimal values

**Comment by 0xd4d** [comment]
An integer is shown in decimal if it's a number that was probably written in decimal, else it's shown in hex.

`0x2A9AD0C4` vs `714789060`, I prefer hex in these cases. `0x64` vs `100`, I prefer decimal.

Of course an option could be added to force hex or decimal.

**Comment by justin-gerhardt** [comment]
That would be greatly appreciated. How do you recognize if a number is written in hex or decimal?

**Comment by 0xd4d** [comment]
It's not possible, I've added checks for certain integers: if abs(x) <= 20 or if it's of the form 10^y +- 0 or 1 it's shown in decimal.
