### ISSUE TITLE
The max count of recent files is so small

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#1335]
dnSpy now just record the lastest 10 files, I think the screen height can contain at least 30 items without scrollbar and pruning, so I think dnSpy can adjust to 30

**Comment by 0xd4d** [comment]
20-30 should be enough

**Comment by CreateAndInject** [comment]
Why do you added `good first issue` label? I'm not a newcomer, I opened so many issues.

**Comment by 0xd4d** [comment]
It means it's an easy issue to fix.
