### ISSUE TITLE
CS0433: The type ValueTuple<T1,T2> exists in both dll....

### ISSUE THREAD

**Issue by allmyfantasy** [0xd4d/dnSpy#1337]
**version:** 
dnSpy v6.1.0(64-bit .Net Core)
**Steps:**
1.I installed the latest release of "System.ValueTuple" using nuget .
2.  I created a Console application. After it works properly, I want to use dnSpy to modify the program.Then I click "Builde", an error is reported.

**Errors are as follows:**
"error CS0433	The type 'ValueTuple<T1, T2>' exists in both 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'	main.cs	14
"

**erro capture and code:**

1.error capture:![error capture](https://user-images.githubusercontent.com/35585699/70373171-f0a23980-1921-11ea-8f88-ca3fc140e960.png)
2.code=>[ConsoleApp1.zip](https://github.com/0xd4d/dnSpy/files/3934972/ConsoleApp1.zip)

**Comment by 0xd4d** [comment]
Close all files, drag all .NET 4.x.x (use the correct version) reference assemblies to Assembly Explorer and then add your file and dnSpy should now use the correct .NET Framework assembly ref files instead of the current runtime's files.
