### ISSUE TITLE
Why removed all the binary releases?

### ISSUE THREAD

**Issue by doggy8088** [0xd4d/dnSpy#1341]
I was trying to install dnSpy by chocolatey. I realized that the binary releases has been deleted from GitHub. It can only be installed by building from source code. May I ask why?

**Comment by nl-n** [comment]
Seconded. Not the best decision, since it has nothing to with a dev environment, why require one just to use it. Doesn't help that each release deletes all the previous ones.

**Comment by 0xd4d** [comment]
It's to encourage more people to build it from source. Take a look at the # stars, then take a look at the # contributors. Something's not right.

Maintaining dnSpy is too much work.

**Comment by nl-n** [comment]
I don't mean to sound rude but, that kind of feels like a middle-finger situation to any non-devs that use this...
The source is only a git clone away, i don't see how doing that would change anything. Except maybe more people complaining in issues because they have never touched a compiler.

**Comment by doggy8088** [comment]
@0xd4d You are really do a very good job. Thanks for your contributing on this project. It helps me a lot sometimes.

To be honest, I'm rarely need to use dnSpy all the time. I probably use this tool only once per year. So I'll be very grateful if you can offer a binary version. That will benefit many people around the world who don't really want to build something from the ground up.

It's your project. I do respect your decision. Thanks anyway!
