### ISSUE TITLE
stackalloc is choking debugger

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#1342]
- What version did you use?
dnSpy v6.1.0 (.NET Framework)

- Write down all steps needed to reproduce this issue. Also attach any needed files.

debugging an executable (64 bit) and once stepping over stackalloc it is showing following error and if press "Continue" button dnSpy debugger is terminating

![image](https://user-images.githubusercontent.com/765343/70750948-12dbf300-1d38-11ea-9aaf-898216ad2a7f.png)

without debugger app is starting fine

**Comment by 0xd4d** [comment]
https://github.com/dotnet/coreclr/issues/27211

**Comment by greenozon** [comment]
well, looks like only the latest dot net core 3.1 has a fix for this?...

some details on my env:
Win7 x64 SP1

and following .net installed

![image](https://user-images.githubusercontent.com/765343/70753945-a9131780-1d3e-11ea-83a5-8cbd38e04977.png)

**Comment by 0xd4d** [comment]
You can set a BP after the stackalloc statement and hit F5.

**Comment by greenozon** [comment]
Yes, you are right,
it helped!

Feel free to close this issue
Thanks.
