### ISSUE TITLE
Are release binaries coming back?

### ISSUE THREAD

**Issue by jnm2** [0xd4d/dnSpy#1343]
Tried to install the Chocolatey package on a new machine and it failed. It appears that you've deleted all previous releases: https://github.com/0xd4d/dnSpy/releases

Is this a temporary thing? I'd be happy to help with https://github.com/0xd4d/dnSpy/blob/master/.github/workflows/build.yml if needed.

**Comment by stevemk14ebr** [comment]
Main readme has changed alot too?

**Comment by 0xd4d** [comment]
Binaries have been temporarily removed to encourage people to build it from source code. The # stars to # contributors ratio is pretty bad. Github stats says there were 5x as many clones yesterday as on a normal day. The binaries will come back in about a week. I might do this every time there's a new release.

**Comment by jnm2** [comment]
I would not expect a correlation between clones used to build from source and contributions. Interesting to hear what you find.

**Comment by jnm2** [comment]
I would not expect a correlation between clones used to build from source and contributions. Interesting to hear what you find.

My perspective: I have a task to perform and I'm deep in a given mental stack for that task. I go to use dnSpy as usual and am presented with an obstacle, something unusual that I haven't dealt with before.
In today's case, I made do with other tools. But even if I put in the time to overcome that obstacle, and ended up with a clone among the hundreds on disk, I'm pretty sure it would not occur to me to look at the project backlog and find something to contribute.

**Comment by 0xd4d** [comment]
The more people that clone it the more likely it is that someone will add code.

**Comment by jnm2** [comment]
GitHub directs people to `help-wanted` tags, and there are some sites that connect people with .NET repos that have issues that are up for grabs.  I bet that would combine really well toward this goal.
