### ISSUE TITLE
Hide "Derived Types" folder when it empty

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#1346]
No need to show derived type folder when its empty:

![image](https://user-images.githubusercontent.com/14368203/70870803-d6a2cf80-1f8f-11ea-80c0-2369c1e798ac.png)

**Comment by CreateAndInject** [comment]
But how do you know whether it's empty?
There's no easy way to know whether a type has derived types, when you click the triangle icon, dnSpy will enumerate all types in the list to check whether it's derived from the target type

**Comment by 0xd4d** [comment]
If it's sealed, we know instantly that it has no derived types.

Removing the folder will only lead to confusion. People will ask why it's not there.

**Comment by Symbai** [comment]
Good point, didn't thought about that.
