### ISSUE TITLE
Problems with decompiling code using COM

### ISSUE THREAD

**Issue by simpleperson123** [0xd4d/dnSpy#1347]
DnSpy has an issue with decompiling classes that include calls to COM objects. I tried that same assembly on ilSpy and the result was much better. The decompiler engine probably needs to be updated.
<img width="563" alt="dnspy-com-error" src="https://user-images.githubusercontent.com/45456776/71188424-3d223900-2281-11ea-8d5d-55c59993469c.PNG">

**Comment by 0xd4d** [comment]
> DnSpy has an issue with decompiling classes that include calls to COM objects. I tried that same assembly on ilSpy and the result was much better. The decompiler engine probably needs to be updated.

There's an issue about this already: https://github.com/0xd4d/dnSpy/issues/936
