### ISSUE TITLE
Unity debug DLL's are missing

### ISSUE THREAD

**Issue by flarn2006** [0xd4d/dnSpy#1348]
I mentioned this before but now that the issues page is working here, I thought I'd post it as a proper issue.

As a side note, I'm just curious, why delete old releases? Having them archived wouldn't do any harm, would it? If the older releases were still up, this wouldn't be an issue. I figure there's probably a good reason you're doing it, but I can't think of what it could be and I'm dying to know, lol.

(I hope none of this comes across as impolite—if so, please let me know, because it's the only way I can learn from my mistakes.)

**Comment by 0xd4d** [comment]
They've been uploaded now.

**Comment by 0xd4d** [comment]
The old releases are deleted because I don't see a good reason to keep them. Just use the latest release.

**Comment by flarn2006** [comment]
Much appreciated; thanks. :)
If you want my opinion, I think a better way to think of it is there's no real reason to delete them. Having the old releases wouldn't make anything more difficult for anyone. But deleting them might, and in fact has in my case. It's up to you though, of course.
