### ISSUE TITLE
Compilation problem on Unity build

### ISSUE THREAD

**Issue by n2n1** [0xd4d/dnSpy#1350]
on version 6.1.0 (and 6.1.1 also)

It was already in the code - i didn't change anything here. This throws errors at the start of compilation.
The compiler is having trouble with the switch statement so it's generating compiler code to handle it and the name is not allowed by the compiler (can't have angle brackets in a name).

https://i.imgur.com/skh3esO.jpg

**Comment by 0xd4d** [comment]
The code switched on strings and will probably be fixed once https://github.com/0xd4d/dnSpy/issues/936 is fixed.

**Comment by n2n1** [comment]
Thanks!

**Comment by n2n1** [comment]
On v6.1.3 (x64) - the same problem.

**Comment by 0xd4d** [comment]
It's because that issue I referenced hasn't been fixed yet.

**Comment by n2n1** [comment]
Sorry, i'm new to the git hub, so my actions may be incorrect.
I figured if the problem is not fixed - then i need to open issue. 
Thank You for Your Utility!
