### ISSUE TITLE
CS0246 DnSpy

### ISSUE THREAD

**Issue by Nikita107r** [0xd4d/dnSpy#1352]
![Безымянркрукрукрцупный](https://user-images.githubusercontent.com/59142773/71323811-6e507280-24e8-11ea-872b-e89f2303d2fe.png)
hi guys how to fix this error I want to make chams in the game
![Безымянный](https://user-images.githubusercontent.com/59142773/71323752-cd61b780-24e7-11ea-9c21-ab6553b08a65.png)

**Comment by 0xd4d** [comment]
Looks like MethodImplAttribute doesn't exist. You can decompile mscorlib.dll from .NET Core or .NET Framework and add the attribute to your assembly and it should compile.

**Comment by Nikita107r** [comment]
Thank you everything works i'm satisfied
