### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by Suchiman** [0xd4d/dnSpy#1353]
What happened to the readme? I'm a man of little words and like a concise description but i don't think dnSpy is popular enough that everyone already knows it by name what it can and can't do.

Was just promoting dnSpy, then got
> oooo dnspy looks fun (though i must say the repo isnt particularly descriptive,

as response and then noticed myself.

**Comment by 0xd4d** [comment]
Almost no-one reads a long readme, so it's shorter now. The 2 main features are listed and 2 pics, and the build instructions are there too.

**Comment by Suchiman** [comment]
I'd argue one keeps reading if interested and stops once you find what interests you, i don't see it as a deterrent, just order the essentials at top and move the details down below, pretty much perfect as it was.

**Comment by JakeSays** [comment]
I'd have to agree with @Suchiman - the more information the better, especially with a project of this complexity.

**Comment by 0xd4d** [comment]
I'll add a couple of more features later. I don't want the README to be too big.

**Comment by Suchiman** [comment]
I don't think there's a too big, just too many words without much meaning. The old readme was short and precise to the point, what is the problem that you're trying to solve? A README that contains no information and a README that isn't read contains effectively the same amount of information, except that i think you underestimate how many read a good README.

https://github.com/canton7/RestEase is a really long readme because it contains the entire documentation but i can just CTRL + F to find what i'm searching for.
