### ISSUE TITLE
Garbled character/code

### ISSUE THREAD

**Issue by lon91ong** [0xd4d/dnSpy#1354]
I'm using the latest version v6.1.1
I have scene below:
![Garbled character/code](https://user-images.githubusercontent.com/16462258/71346040-e890fd80-25a1-11ea-8195-b12bdb9c56a7.png)

help

**Comment by InlineAsm** [comment]
This is an obfuscated assembly. Try to run it through [de4dot](https://github.com/0xd4d/de4dot)
