### ISSUE TITLE
When saving module, exe doesnt run anymore

### ISSUE THREAD

**Issue by viris** [0xd4d/dnSpy#1356]
- What version did you use?
6.1.2 latest otne

- Write down all steps needed to reproduce this issue. Also attach any needed files.
wanted to save one simple executable.
changed only this:
Button1.enabled = true

Save module.
new exe doesnt run. just exits. Its GUI based.

**Comment by greenozon** [comment]
Probably, to ease the analysis and make things happen you have to provide your sample exe.. (attach here)
