### ISSUE TITLE
AntiAntiDebug - IsDebuggerPresent (kernelbase.dll) bypass

### ISSUE THREAD

**Issue by Autori** [0xd4d/dnSpy#1358]
- What version did you use?
dnspy v6.1.1 64bit

- Write down all steps needed to reproduce this issue. Also attach any needed files.
Dnspy bypasses IsDebuggerPresent from kernel32.dll but not from kernelbase.dll
Example exe attached

Please add kernelbase's IsDebuggerPresent to dnspy antiantidebuggers.

[AntiDebugTester.zip](https://github.com/0xd4d/dnSpy/files/4018829/AntiDebugTester.zip)

**Comment by Autori** [comment]
Please re-test, looks like it doesn't work right. I'm not sure if i builded it good, but it builded. (Builded 5.1.2020 19:13 from master)
It's not detected, but I can't breakpoint anywhere.
Attaching video:
https://youtu.be/GjXuTzIJvEk

**Comment by 0xd4d** [comment]
I've pushed an update.
