### ISSUE TITLE
Compiling multiple scripts at the same time

### ISSUE THREAD

**Issue by SpaceMatra** [0xd4d/dnSpy#1362]
I'm maintaining a small unity game mod with 20+ modified scripts. There is a lot of cross-references between them with custom fields and methods. If the game gets updated by the devs, all those scripts will need to be patched at the same time and any reference that doesnt exist will make compiling individual scripts not possible. 

Is there a way to to compile multiple scripts at the same time to ensure all references are recognized? Or is there a fast workaround for this issue? Thanks in advance, dnspy has been immensely helpful.

**Comment by 0xd4d** [comment]
Click the green C# icon in the lower left corner of the edit window and you can add more CS files.

**Comment by SpaceMatra** [comment]
Much appreciated, this is what I was looking for!

**Comment by SpaceMatra** [comment]
Re-opening the issue

**Comment by 0xd4d** [comment]
Could be compiler generated types which are added when you edit a method with `yield return` in it.

**Comment by SpaceMatra** [comment]
Thanks for the quick response! I checked the scripts and they dont have `yield return`. Maybe Im doing something incorrectly, the steps I follow are (this was done in dnSpy v6.1.6):
1- Right click one of the classes to edit and select "Edit Class (C#)"
2- Replace everything that is inside with the modified class
3- Click the "Add Source Code" button at the bottom and add all the other files to modify.
4- Compile  
This modifies the first script correctly, but the files that were added afterwards create duplicates classes with _0 at the end instead of modifying the already existing ones. I tried selecting "Add Class c#" instead of editing and also manually copying all the text from the other classes inside the "Edit class" window, but the results were the same.

**Comment by 0xd4d** [comment]
Sounds like you add types with the same names as existing types. The names of each type must be unique in each module so dnSpy will rename the new ones you add.

If each file you add is meant to replace an existing class, you have to choose 'Edit Class' for each class and paste in the source code.

**Comment by SpaceMatra** [comment]
> Sounds like you add types with the same names as existing types. The names of each type must be unique in each module so dnSpy will rename the new ones you add.
Makes sense, I will be careful with that from now on.

> If each file you add is meant to replace an existing class, you have to choose 'Edit Class' for each class and paste in the source code.
Thats what I have been doing so far, editing classes one by one being as careful as I can to not break the dll. Is it possible to edit multiple classes at the same time?

**Comment by 0xd4d** [comment]
> Is it possible to edit multiple classes at the same time?

No it's not possible at the moment.

**Comment by SpaceMatra** [comment]
Ah understandable. Thanks for your time answering my questions!

**Comment by liesauer** [comment]
> Sounds like you add types with the same names as existing types. The names of each type must be unique in each module so dnSpy will rename the new ones you add.
> 
> If each file you add is meant to replace an existing class, you have to choose 'Edit Class' for each class and paste in the source code.

how can i modify two classes at the same time?
let's say:
exists classes
```csharp
public class A
{
    public bool prop1;
}
public class B
{
    public bool prop1;
}
```

and i need to modify to

```csharp
public class A
{
    public bool prop1;
    public bool prop2;
    public void Test()
    {
        new B().prop2 = true;
    }
}
public class B
{
    public bool prop1;
    public bool prop2;
    public void Test()
    {
        new A().prop2 = true;
    }
}
```

is noway to do this now, unless i add the properties first and then add the methods. if i modify class A and add class B as source code, dnspy will generate a class B_1.
