### ISSUE TITLE
Issue when saving module, exe doesnt run anymore

### ISSUE THREAD

**Issue by ByteFader** [0xd4d/dnSpy#1363]
I try to edit an exe and everything looks fine but when i save the module even without any edit, the app crashes after a few seconds.

I have added the program i am talking about, it is the exe in it i try to edit
[trikker_icon.zip](https://github.com/0xd4d/dnSpy/files/4032019/trikker_icon.zip)

**Comment by 0xd4d** [comment]
Sounds like it could be obfuscated. What's the stack trace. Check if it has some protection.
