### ISSUE TITLE
how to disable auto shortcut and optimal code when compile

### ISSUE THREAD

**Issue by truongquangkien** [0xd4d/dnSpy#1365]
I want to disbale auto shortcut and optimal code when compile, because when dnspy auto shortcut and optimal, my program not work.
Thanks for reading.

**Comment by 0xd4d** [comment]
Options -> Compiler -> uncheck `Optimize code`.

**Comment by truongquangkien** [comment]
I did it and it have some problem when I compile. The program worked but dnSpy formatted code, add 'goto label' and cut som things. can dnSpy disable it ?
Thank you so much.

**Comment by 0xd4d** [comment]
The code is decompiled so the output won't look the same as the source code. Sometimes the decompiler adds gotos when it can't use normal if/else.
