### ISSUE TITLE
Dotnet won't open dnSpy

### ISSUE THREAD

**Issue by RasmusFey** [0xd4d/dnSpy#1366]
- What version did you use?
The newest one, at least the one automatically downloaded by git.

- Write down all steps needed to reproduce this issue. Also attach any needed files.
Well, I have a new installation of dnSpy and dotnet core for building(x64) As far as I know its version 3.0.100. when running dotnet build ./build.ps1 the cmd gives me this error:
A compatible installed .NET Core SDK for global.json version [3.0.100] from [D:\dnSpy\global.json] was not found
Install the [3.0.100] .NET Core SDK or update [D:\dnSpy\global.json] with an installed .NET Core SDK:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

**Comment by 0xd4d** [comment]
You can delete global.json or edit it and change the version number.
