### ISSUE TITLE
I have a question about API breakpoint

### ISSUE THREAD

**Issue by kismp123** [0xd4d/dnSpy#1367]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?
dnSpy v6.1.2 (.NET Framework)

- Write down all steps needed to reproduce this issue. Also attach any needed files.

I have been debugging a dotnet network server program. 
And I want to set breakpoint listening point which is system.Runtime.Remoting.Channels.Tcp.TcpServerSocketHandler.ReadHeader()

I got messages 
--------------------------------------------------
    .NET;System.Runtime.Remoting.RemotingException: TCP 梨꾨꼸 ?꾨줈?
좎퐳 ?꾨컲: ?꾨━?곕툝???꾩슂?⑸땲??
   ?꾩튂: System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPre
amble()
   ?꾩튂: System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndO
peration(UInt16& operation)
   ?꾩튂: System.Runtime.Remoting.Channels.Tcp.TcpServerSocketHandler.ReadHeade
rs()
   ?꾩튂: System.Runtime.Remoting.Channels.Tcp.TcpServerTransportSink.ServiceRe
quest(Object state)
   ?꾩튂: System.Runtime.Remoting.Channels.SocketHandler.ProcessRequestNow()
--------------------------------------------------
But I couldn't find that in dnspy APIs.
Can you explain me how to find dotnet APIs? or any advise for debugging network program?
I used "search" to find APIs but there is no specific API. 

I had never been debugging dotnet program. 
Thanks

**Comment by 0xd4d** [comment]
You must open the file in Assembly Explorer. Debug -> Windows -> Modules and right-click in the window and Open all modules. You can now search for the method.

**Comment by kismp123** [comment]
Thanks!
