### ISSUE TITLE
Syntax error while running ./build.ps1

### ISSUE THREAD

**Issue by gormleymark** [0xd4d/dnSpy#1368]
Followed instructions on front page of repo:

git clone --recursive https://github.com/0xd4d/dnSpy.git
cd dnSpy
./build.ps1

Get the following error

./build.ps1: line 1: syntax error near unexpected token `[string]$buildtfm'

./build.ps1: line 1: `param([string]$buildtfm = 'all', [switch]$NoMsbuild)'

**Comment by 0xd4d** [comment]
Make sure you use powershell.

**Comment by eric12109** [comment]
I'm having the same problem on Ubuntu (Pop!Os).

**Comment by 0xd4d** [comment]
The GUI is for Windows only since it's WPF so it will fail unless you build it on Windows.
