### ISSUE TITLE
can dynamically generated tokens be viewed while debugging?

### ISSUE THREAD

**Issue by sanikolov** [0xd4d/dnSpy#1370]
- What version did you use? dnSpy v6.1.3 (.NET Framework)
- Write down all steps needed to reproduce this issue. Also attach any needed files.

I am debugging a .NET app in which a profiler injects a few mdTypeDefs and mdMethodDefs shortly after module mscorlib finishes loading. However, when I choose "goto metadata", and specify the token ID, and then choose "method body", the token cannot be found. This leads me to believe that dynamically generated tokens are invisible to dnSpy. When I view metadata rows it shows me the existing tokens in the mscorlib.dll assembly and none of the rows contain any newly added (at runtime) type/method tokens. I can't find a generated method token in a memory window either, right after the last nearest token to the one I am looking for.
One thing is for sure, by the time I get to search for these tokens, they have already been emitted.
Any suggestions?

**Comment by 0xd4d** [comment]
dnSpy can show the metadata of on-disk, in-memory modules and also dynamic modules created by the reflection APIs. Profilers aren't supported.

**Comment by sanikolov** [comment]
Thanks. Is it feasible to make a debugger such as dnSpy (or windbg) aware of profiler added tokens, or is there some fundamental limitation in the CLR/ICorDebug/etc that makes this impossible? If the latter, then ticket can be closed.

**Comment by 0xd4d** [comment]
AFAIK, it's not possible but you could ask over at https://github.com/dotnet/coreclr/issues to be sure.
