### ISSUE TITLE
Question: How do I rename local variables?

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#1371]
- What version did you use? 6.1.3

How do I rename local variables in a method body without using "Edit Method C#"? (which won't work in obfuscated assemblies because it fail to compile)

The only way I found is:

- Right click in method body
- Edit IL
- Switch to "Locals" tab

But sadly all local names are empty. So I kinda have to guess / try&error which is the right variable. Is it possible for dnSpy to fill the window with the local variables it displays? Or is there any other way?

![image](https://user-images.githubusercontent.com/14368203/72637194-a5d00480-3958-11ea-85c1-91bd91de0634.png)

**Comment by 0xd4d** [comment]
That's the only way at the moment. See this issue https://github.com/0xd4d/dnSpy/issues/1072

**Comment by Symbai** [comment]
Thanks, I have missed this one. Closing as duplicate
