### ISSUE TITLE
How to remove DnSpy from the HD

### ISSUE THREAD

**Issue by cerolcs** [0xd4d/dnSpy#1375]
So I cant open an app because I have dnSpy at my pc, what do I have to do to remove fully archives of dnSpy

**Comment by 0xd4d** [comment]
There's no installer so just delete the folder.

**Comment by cerolcs** [comment]
but when i start an app with net guard, i cant run it because mine hd has dnspy, so i have to find a way to remove 100%

**Comment by ElektroKill** [comment]
Hi, I think netguard detects the dnSpy settings file

**Comment by 0xd4d** [comment]
Delete these dirs:

- %APPDATA%\dnSpy
- %LOCALAPPDATA%\dnSpy

**Comment by 0xd4d** [comment]
You can also compile dnSpy yourself and change the name in this file: https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy/MainApp/Constants.cs#L22

That should hide it from simple detections.
