### ISSUE TITLE
public List<GameObject> xxx= new List<GameObject>(); it change to public List<GameObject>??

### ISSUE THREAD

**Issue by superdragonball** [0xd4d/dnSpy#1376]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?

- Write down all steps needed to reproduce this issue. Also attach any needed files.
use this code and when you edit something 

  public List<GameObject> xxx= new List<GameObject>(); 
It will change to public List<GameObject> xxx; why ??

**Comment by 0xd4d** [comment]
The compiler adds that code to the constructor. The decompiler can usually do the right thing if all constructors initialize the first fields the same way. How many constructors does that class have?

**Comment by superdragonball** [comment]
hi i fix it there was a constructor but it was not using and hiding from me. 
After i change the options i can now edit it lul before i cant save it
