### ISSUE TITLE
private static List<xx1> xx2= new List<xx1>() will not working 

### ISSUE THREAD

**Issue by superdragonball** [0xd4d/dnSpy#1379]
when i use it like this 
 private static List<xx1> xx2= new List<xx1>()
        {
    xxx.xxxx.xxx..xxx ....
        };

my list is empty its only accept 
 private static List<xx1> xx2= new List<xx1>()
   
why?

**Comment by 0xd4d** [comment]
Why didn't you fill out the issue template?

It's impossible to help without more info.
