### ISSUE TITLE
Search (CTRL+SHIFT+K) not finding all instances / occurences (missing results).

### ISSUE THREAD

**Issue by grasmanek94** [0xd4d/dnSpy#1381]
- What version did you use?

v6.1.3 net472

- Write down all steps needed to reproduce this issue. Also attach any needed files.

1. Download, extract and launch dnSpy
2. Load assembly that you want to search through
3. Select the assembly (or assemblies) and press CTRL+SHIFT+K
4. Enter search term that occurs in the code multiple times
5. Check results by creating project from assembly and then search with a different program (e.g. AstroGrep)
6. The other program will show more results

See screenshots:

(dnSpy)
![image](https://user-images.githubusercontent.com/595329/73177313-0278af80-410f-11ea-96fa-5fc62ff0865c.png)

(AstroGrep)
![image](https://user-images.githubusercontent.com/595329/73177490-76b35300-410f-11ea-94c6-474036eec1d8.png)

By navigating to the file, dnSpy shows the entry is present:
![image](https://user-images.githubusercontent.com/595329/73177569-a6625b00-410f-11ea-8408-91ecc88ebf1d.png)

And the CTRL+SHIFT+K search still will not show the entry.

Searching for the full name `ServerManager.ServerSettingsData.NPCSettings.BuilderCooldownMultiplierSeconds` also does not work.

**Comment by 0xd4d** [comment]
Have you tried the `Analyzer`? Right click the field and then click `Analyze` or `Ctrl+Shift+R`.

The search window only searches for definitions, not usage.

**Comment by grasmanek94** [comment]
Oh that seems to work, thank you. Just wondering how I would find "BuilderCooldownMultiplierSeconds" in BaseGame.dll without Assembly-CSharp.dll? is that possible?

**Comment by 0xd4d** [comment]
Just put all files in the same folder or drag all dependencies to Assembly Explorer and the Analyzer will find them. If you edit the file, you need them when saving the file.
