### ISSUE TITLE
Struggling to make binary debuggable.

### ISSUE THREAD

**Issue by expend20** [0xd4d/dnSpy#1384]
Hi, I'm trying to make third party .exe debuggable. By debuggable I mean that I could see and modify local variables.

I've tried [this](https://github.com/risk-of-thunder/R2Wiki/wiki/Debugging-Your-Mods-With-dnSpy) and [that](https://github.com/0xd4d/dnSpy/issues/799) without any luck, meaning I can't see and modify `num` variable at the entry point.

![image](https://user-images.githubusercontent.com/36543551/73657716-84328500-469b-11ea-9c15-76b481445f93.png)

> What version did you use?

dnSpy-net472 / dnSpy v6.1.3 (.NET Framework)

> Write down all steps needed to reproduce this issue. Also attach any needed files.

1) I've created `PunchCardReader.ini`
```
[.NET Framework Debugging Control] 
GenerateTrackingInfo=1 
AllowOptimize=0
```

2) I've added and updated binary with assembly attributes:

```
using System.Diagnostics;

[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.DisableOptimizations | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue)]
```

However I can still see `Decompiler generated variables can't be evaluated`. How can I verify that the code is not optimized? Maybe it's not an optimization issue but rather decompilation error?

Here is the [sample](https://minio.tw1st.link/dump/temp/PunchCardReader.exe?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=NvaiSdSmTMFC0GmszEnE%2F20200203%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200203T135432Z&X-Amz-Expires=345600&X-Amz-SignedHeaders=host&X-Amz-Signature=f274a1b2c82cfcad732bbbd2c204ba79cd612fe631b610d65cf42a0b941befc2)

Thanks!

**Comment by 0xd4d** [comment]
That's a decompiler generated variable. Those variables don't exist in the metadata, it's just a temporary value on the IL stack which the debugger can't see.

**Comment by expend20** [comment]
Thanks for the answer! If you don't mind I'll ask one more quick question. Is there a way to debug dynamically created code with dnSpy? The code is created like that:
```
ILGenerator ilgenerator = dynamicMethod.GetILGenerator();
...
			ilgenerator.DeclareLocal(typeof(uint));
			ilgenerator.DeclareLocal(typeof(bool));
			ilgenerator.DeclareLocal(typeof(bool));
			Label label = ilgenerator.DefineLabel();
			Label label2 = ilgenerator.DefineLabel();
			ilgenerator.Emit(OpCodes.Nop);
			ilgenerator.Emit(OpCodes.Ldc_I4, 57005);
			ilgenerator.Emit(OpCodes.Stloc_0);
...
```

**Comment by expend20** [comment]
Oh, and one more... When I'm trying to edit and recompile sources, I'm getting errors about "PrivateImplemenation..." is there a way to avoid it?
![image](https://user-images.githubusercontent.com/36543551/73681410-f40a3500-46c6-11ea-956b-b2d4773b7058.png)

**Comment by Symbai** [comment]
> 
>PrivateImplemenation..." is there a way to avoid it?

Yes edit IL instead of C#. Last does not work properly if the source is obfuscated.

**Comment by expend20** [comment]
Ok then, thanks a lot guys @0xd4d & @Symbai! Please feel free to close the issue.
