### ISSUE TITLE
overloaded members compiler issue with mixed methods and variables

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [0xd4d/dnSpy#1385]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?
6.1.3 net 472
- Write down all steps needed to reproduce this issue. Also attach any needed files.
Exist some situations when compiler fail to rebuild library with error CS0102 The type '.....' already contains a definition for '....'

It happens in following situations : 
```
namespace Example.CM.SuperFile
{
	public static partial class SuperFileReader
	{
		private static bool a(byte[] A_0, byte[] A_1)
		{
			.....
		}

		private static byte[] a(byte[] A_0)
		{
			.....
		}

		private static bool a(byte[] A_0, byte[] A_1, string A_2)
		{
			....
		}

		private static byte[] a(byte[] A_0, byte[] A_1, byte[] A_2)
		{
			.....
		}

		private static void a(global::Example.CM.Common.SuperFileData A_0)
		{
		}

		private static int a;

	}
}
```
Compiler fail rebuild on line "private static int a;" with CS0102 : until manual rename static integer variable to unique one.

**Comment by 0xd4d** [comment]
Looks obfuscated, have you tried to use de4dot? It can auto-rename methods for you.

**Comment by jpVm5jYYRE1VIKL** [comment]
de4dot i used but prefer not to use it because it is breaking source and create much more problems for recompilation after changes done. Well if problem related not to dnspy then most probably can be closed.

**Comment by 0xd4d** [comment]
The C# compiler only accepts valid names and doesn't allow overloading on the return type, etc so there's not much dnSpy can do. You should fix the names, de4dot is one way of doing it. Manually fixing it is another (slower) option.
