### ISSUE TITLE
dnSpy edit method not working.

### ISSUE THREAD

**Issue by helpmelol7123** [0xd4d/dnSpy#1386]
So im trying to remove something from a dll, but it would just show me an error instead of edit. im trying to use edit method but then this pops up 
![uhoh](https://user-images.githubusercontent.com/60817702/74086448-c46a7c80-4a7a-11ea-956d-f36746004911.PNG) (i tried latest version but that didnt work, i got told to use v.6.1.0 and im using it rn.

**Comment by 0xd4d** [comment]
Redownload dnSpy, seems like you're missing files.
