### ISSUE TITLE
My programs is not change after I have edited the code being in dll files.

### ISSUE THREAD

**Issue by khatkhuong** [0xd4d/dnSpy#1388]
My program is change completely when I run it by debuging in dnSpy. However, when I run it practically (outside dnSpy), the changes being in .exe are effective, there are no changes with the modification in other .dll files?
Thank you for your support!

**Comment by 0xd4d** [comment]
Open the modules window when you're debugging it and check the path of the file. Make sure it's the same as you think it is.

**Comment by 0xd4d** [comment]
If you've edited a file that's in the GAC, make sure you re-install it.
