### ISSUE TITLE
I want to Attatch w3wp.exe, but I can not find it 

### ISSUE THREAD

**Issue by cyj380236628** [0xd4d/dnSpy#1391]
Version : dnSpy v6.0.5(64-bit\32-bit)  run as Administrator

My iis is running and I want to attatch the w3wp but I can find the process，so we can i do？

BTW :  I had added   'COMPLUS_ZapDisable:1 ' into my environment viriables.

I do some research but can not find a way to resolve it, so there are some one can help me, thanks a lot.

**Comment by 0xd4d** [comment]
You need 64-bit dnSpy to attach to 64-bit processes.
