### ISSUE TITLE
How to evaluate C# expressions while debugging?

### ISSUE THREAD

**Issue by SparkyTD** [0xd4d/dnSpy#1394]
On the project's home page, under the "Debugger" section, it says that "evaluating C# / Visual Basic expressions" is supported. However I can't seem to find the evaluation window while debugging. Can someone help me?

dnSpy v6.1.3 (.NET Framework)

**Comment by SparkyTD** [comment]
Just to clarify, I'm looking specifically for a feature similar to the Shift+F9 expression evaluation tool in Visual Studio, that lets me type in and evaluate a C# expression while the program is stopped at a break point.

**Comment by 0xd4d** [comment]
Use the watch window.

**Comment by SparkyTD** [comment]
Thanks! :)
