### ISSUE TITLE
Feature: isolate method(s) appearing in a class into separate tab

### ISSUE THREAD

**Issue by pardeike** [0xd4d/dnSpy#1395]
Very commonly I find myself searching in two different versions of a dll for the same method, trying to compare their code and IL instructions:

- I search
- I find two results (here, a nice way of knowing which dll the search result row is from instead of hovering over them would be a big improvement too)
- I open both in their tab
- Now I go to each tab and to isolate them and remove the rest of the (probably large) class that is shown, I open the Assembly Explorer to find the method in the tree to click on it
- I do that on both tabs to compare both methods

Is there a way to make this easier? Maybe a second context menu option to "Open in New Tab" called "Open Method Only in New Tab" that auto selects the method in the browser thus only showing the method alone?

Same goes for having a class shown and the context menu on the methods signature. Something like "Select in Assembly Explorer" would be great.

It drives me nuts when a game updates and I need to find out what has changed on the IL level.

**Comment by 0xd4d** [comment]
Uncheck: `Options -> General -> Decompile a mem....`

So when you double click or shift+dbl clicks it, it should only show that member (eg. method) in a new tab.

> I find two results (here, a nice way of knowing which dll the search result row is from instead of hovering over them would be a big improvement too)

The files would likely have the same name though so you'd still see eg. `mygame.dll`.

**Comment by pardeike** [comment]
Alright. That option works well for me. Regarding the search results, an extra column for the dll would be nice. Like "Assembly-CSharp.dll v1.0.2001.34112" or the path that you already have in the tooltip of each result line.
