### ISSUE TITLE
dnspy generates wrong logic

### ISSUE THREAD

**Issue by yangshuairocks** [0xd4d/dnSpy#1396]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?
v6.1.3 64 bit (GitHub CI compiled at 2/12/2020)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
I use Visual Studio 2019, in a .Net Console project, I created this method.
```
        public void do_something()
        {
            try
            {
                string a = "";
                if (String.IsNullOrEmpty(a))
                {
                    a = "1111111111111";
                }
                else if (!String.IsNullOrEmpty(a))
                {
                    a = "22222222222222";
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
            
        }
```

Compile it with release profile. Use dnspy to open it, I got:

```
		// Token: 0x06000002 RID: 2 RVA: 0x00002054 File Offset: 0x00000254
		public void do_something()
		{
			try
			{
				string a = "";
				if (!string.IsNullOrEmpty(a))
				{
					if (!string.IsNullOrEmpty(a))
					{
					}
				}
			}
			catch (Exception value)
			{
				Console.WriteLine(value);
				throw;
			}
		}
```
The generated result is not correct.

**Comment by 0xd4d** [comment]
You don't use `a` at all so the compiler may have optimized out storing any value in it. Add a Console.WriteLine() somewhere after assigning a value to it.

**Comment by yangshuairocks** [comment]
Thanks for the explanation.
