### ISSUE TITLE
Error:Reference to type"xxx"claims it is defined in 'Assembly-CSharp',but it could not be found

### ISSUE THREAD

**Issue by zcdxj** [0xd4d/dnSpy#1399]
When I try to edit the class"LootOnPickup"
，This error appears ,I just don't know why ,I used the latest version of Dnspy，still has this problem。 Please help me ! Thanks!

**Comment by zcdxj** [comment]
@0xd4d Dear Athor，Can you help me?

**Comment by 0xd4d** [comment]
It's not possible to answer this without more information. You didn't answer the questions in the issue template: https://github.com/0xd4d/dnSpy/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by zcdxj** [comment]
> It's not possible to answer this without more information. You didn't answer the questions in the issue template: https://github.com/0xd4d/dnSpy/blob/master/.github/ISSUE_TEMPLATE.md

I'm sorry!  @0xd4d 

1.  I use the version 6.1.3;
2.  The steps to reproduce the problem:
     1_ Download the [problem dll.zip]
[problem.dll.zip](https://github.com/0xd4d/dnSpy/files/4238227/problem.dll.zip)
 and open the "Assembly-CSharp.dll","UnityEngine.dll"and "Gmtool.dll" in Dnspy
     2_ Search "LootOnpickup" class in "Assembly-CSharp.dll",open it .
     3_ Edit the class "LootOnpickup",and just don't change anything then press the compile button,The the error appears:
![image](https://user-images.githubusercontent.com/48503846/75075776-86b92980-5539-11ea-9d05-c057e643a674.png)

**Comment by 0xd4d** [comment]
Did you search the issues? https://github.com/0xd4d/dnSpy/issues?q=is%3Aissue+is%3Aopen+claims
