### ISSUE TITLE
foreach on an Array extra label is not used: [IL_9B]

### ISSUE THREAD

**Issue by AboAnas1992** [0xd4d/dnSpy#14]
```C#
private static void LoadPlugIns(ContextMenuStrip cx)
{
	if (cx != null)
	{
		string dir = "Plugins";
		dir = Path.Combine(Path.GetDirectoryName(Application.ExecutablePath), dir);
		if (Directory.Exists(dir))
		{
			string[] files = Directory.GetFiles(dir, "*.dll");
			int i = 0;
			while (i < files.Length)
			{
				string f = files[i];
				try
				{
					if (!Program.loadedPlugins.Contains(f))
					{
						Program.loadedPlugins.Add(f);
						string pth = Path.Combine(Application.StartupPath, f);
						Assembly asm = Assembly.LoadFile(pth);
						Program.AddAssembly(cx, asm);
					}
				}
				catch (Exception)
				{
				}
				IL_9B:
				i++;
				continue;
				goto IL_9B;
			}
		}
	}
}
```

**Comment by AboAnas1992** [comment]
note: this is the original source code:

private static void LoadPlugIns(ContextMenuStrip cx)
{
    if (cx != null)
    {
        string str = "Plugins";
        str = Path.Combine(Path.GetDirectoryName(Application.ExecutablePath), str);
        if (Directory.Exists(str))
        {
            foreach (string str2 in Directory.GetFiles(str, "*.dll"))
            {
                try
                {
                    if (!loadedPlugins.Contains(str2))
                    {
                        loadedPlugins.Add(str2);
                        Assembly asm = Assembly.LoadFile(Path.Combine(Application.StartupPath, str2));
                        AddAssembly(cx, asm);
                    }
                }
                catch (Exception)
                {
                }
            }
        }
    }
}

 

 
  private static void LoadPlugIns(ContextMenuStrip cx)
{
    if (cx != null)
    {
        string str = "Plugins";
        str = Path.Combine(Path.GetDirectoryName(Application.ExecutablePath), str);
        if (Directory.Exists(str))
        {
            foreach (string str2 in Directory.GetFiles(str, "*.dll"))
            {
                try
                {
                    if (!loadedPlugins.Contains(str2))
                    {
                        loadedPlugins.Add(str2);
                        Assembly asm = Assembly.LoadFile(Path.Combine(Application.StartupPath, str2));
                        AddAssembly(cx, asm);
                    }
                }
                catch (Exception)
                {
                }
            }
        }
    }
}

**Comment by 0xd4d** [comment]
Seems like an ILSpy decompiler problem. It's probably better to report it to the ILSpy decompiler maintainers. It's difficult to get decompiler output completely 100% accurate so that a big project can be recompiled from decompiled code.
