### ISSUE TITLE
Issue modifying Unity DLL

### ISSUE THREAD

**Issue by LolHacksRule** [0xd4d/dnSpy#1400]
- What version did you use?
dnSpy 6.0.8 (64-bit)

- Write down all steps needed to reproduce this issue. Also attach any needed files.

I'm trying to modify an old version of a game's main assembly but when I modify and force the game to load it, the game doesn't advance beyond the loading screen, I found a lot of logcat errors relating to Unity being unable to load many types from the assembly, any advice?

Game: Sonic Dash
Version: 3.84.Go
Unity Version: 5.6.5.p3
Platform: Android

**Comment by 0xd4d** [comment]
It's impossible to answer this without more information. Try adding repro steps or at least show the errors.

**Comment by LolHacksRule** [comment]
Never mind problem solved, updating to 6.1.3 fixed it.
