### ISSUE TITLE
Prevent dnSpy from crashing when file/folder selection dialog crashes

### ISSUE THREAD

**Issue by LGLTeam** [0xd4d/dnSpy#1402]
- What version did you use? 6.1.3 (dc32a40)

- Write down all steps needed to reproduce this issue. Also attach any needed files.

This is very annoying when I was about to save the file (File -> Save or FIle -> Save all). Hours of work lost when a file/folder selection dialog freezes and crashes. As a workaround, I could have typed the path manually

This is very hard to reproduce crash because it's happen randomly and it's Win10 issue but is it possible to prevent dnspy crash when the selection dialog crashes?

Google Chrome has crash prevention. Even the selection dialog crashes, Chrome does not crash

**Comment by 0xd4d** [comment]
If it results in a .NET exception, then we could catch it. If the OS just terminates the app, it's not much we can do.

**Comment by LGLTeam** [comment]
Hmm ok. I have reinstalled my computer because it was quite messed up but it doesn't mean the issue will go away. I do rememeber that dialog crash was there since 1803 or 1809 windows build

Sadly this issue is very rare. I don't know if this issue should be closed or not

Does dnSpy log anything? if so, I could post it here in the future.

**Comment by 0xd4d** [comment]
You can check in your Windows event logs if you see a stack trace.

**Comment by LGLTeam** [comment]
Ok will check it next time

**Comment by 0xd4d** [comment]
I'll close this since it's not possible to repro. If you get a repro, just reply here and I'll re-open it.

**Comment by LGLTeam** [comment]
Not related to dnspy, but file selection crashed again on Google Chrome when i'm saving downloaded file which excatly happen on dnSpy. Maybe Windows issue

Kind of wish dnSpy have some sore of protection prevent itself crashing like Chrome have

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-04-15T09:19:08.811455700Z" /> 
  <EventRecordID>13394</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>xxx</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>chrome.exe</Data> 
  <Data>80.0.3987.149</Data> 
  <Data>5e6fcb14</Data> 
  <Data>ntdll.dll</Data> 
  <Data>10.0.18362.719</Data> 
  <Data>64d10ee0</Data> 
  <Data>c0000374</Data> 
  <Data>00000000000f92a9</Data> 
  <Data>3148</Data> 
  <Data>01d61306ea3e1de7</Data> 
  <Data>D:\Portable Apps\GoogleChromePortable64\App\Chrome-bin\chrome.exe</Data> 
  <Data>C:\Windows\SYSTEM32\ntdll.dll</Data> 
  <Data>d071ff22-2822-4fbc-a3f8-f4b099f39cba</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by LGLTeam** [comment]
File explore selections froze and cause dnSpy to crash again as soon as i try to extract source code.
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-07-09T13:20:01.739793100Z" /> 
  <EventRecordID>36342</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>xxx</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>dnSpy.exe</Data> 
  <Data>6.1.4.0</Data> 
  <Data>d77ef49b</Data> 
  <Data>ntdll.dll</Data> 
  <Data>10.0.18362.815</Data> 
  <Data>b29ecf52</Data> 
  <Data>c0000374</Data> 
  <Data>00000000000f9229</Data> 
  <Data>14f8</Data> 
  <Data>01d655f3a0b2b1fa</Data> 
  <Data>D:\dnSpy\dnSpy.exe</Data> 
  <Data>C:\Windows\SYSTEM32\ntdll.dll</Data> 
  <Data>4ba5b384-3b0a-49ef-ab2b-6a0790a779ed</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by Toshiba1127** [comment]
I'm getting the same problem, Instant crash when trying to save my work. I lost hours of my unsaved work T_T
