### ISSUE TITLE
(https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)]

### ISSUE THREAD

**Issue by puppydog2009** [0xd4d/dnSpy#1403]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?

- Write down all steps needed to reproduce this issue. Also attach any needed files.

**Comment by puppydog2009** [comment]
dnspy does not let me in

**Comment by 0xd4d** [comment]
Works for me, even when I'm not logged in.

https://github.com/0xd4d/dnSpy/actions
