### ISSUE TITLE
doesn't compile

### ISSUE THREAD

**Issue by ernstgruber** [0xd4d/dnSpy#1406]
downloaded zip, when i try to compile:

C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-master\build.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): r
Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 2.29 min for C:\Users\itmanager.SAFARI-HOTELS\Downloads\d
nSpy-master\dnSpy-master\Build\AppHostPatcher\AppHostPatcher.csproj.
  AppHostPatcher -> C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSp
y-master\Build\AppHostPatcher\bin\Release\net472\AppHostPatcher.exe

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.49
Building .NET Framework x86 and x64 binaries
Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\Libraries\ICSharpCode.TreeView\ICSharpCode.TreeView.csproj" was not found.
 [C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-master\dnSpy.sln
]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\
ICSharpCode.Decompiler.csproj" was not found. [C:\Users\itmanager.SAFARI-HOTELS\
Downloads\dnSpy-master\dnSpy-master\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory\ICSharpCode.
NRefactory.csproj" was not found. [C:\Users\itmanager.SAFARI-HOTELS\Downloads\dn
Spy-master\dnSpy-master\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\ICSha
rpCode.NRefactory.CSharp.csproj" was not found. [C:\Users\itmanager.SAFARI-HOTEL
S\Downloads\dnSpy-master\dnSpy-master\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\NRefactory.VB\ICSharpCo
de.NRefactory.VB\ICSharpCode.NRefactory.VB.csproj" was not found. [C:\Users\itma
nager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-master\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\dnSpy\dnSpy.Images\dnSpy.Images.csproj" was not found. [C:\Users\itmanager
.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-master\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\dnSpy\Roslyn\Roslyn.ExpressionCompiler\Core\ExpressionCompiler\ExpressionC
ompiler.csproj" was not found. [C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy
-master\dnSpy-master\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\dnSpy\Roslyn\Roslyn.ExpressionCompiler\CSharp\CSharpExpressionCompiler\CSh
arpExpressionCompiler.csproj" was not found. [C:\Users\itmanager.SAFARI-HOTELS\D
ownloads\dnSpy-master\dnSpy-master\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\Extensions\dnSpy.Debugger\Mono.Debugger.Soft\Mono.Debugger.Soft.csproj" wa
s not found. [C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-mast
er\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\dnSpy\Roslyn\Roslyn.ExpressionCompiler\VisualBasic\BasicExpressionCompiler
\BasicExpressionCompiler.vbproj" was not found. [C:\Users\itmanager.SAFARI-HOTEL
S\Downloads\dnSpy-master\dnSpy-master\dnSpy.sln]
PS C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-master>
PS C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-master> .\build
 -nomsbuild

Security warning
Run only scripts that you trust. While scripts from the internet can be useful,
 this script can potentially harm your computer. If you trust this script, use
the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run
C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-master\build.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): r
Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 132.47 ms for C:\Users\itmanager.SAFARI-HOTELS\Downloads\
dnSpy-master\dnSpy-master\Build\AppHostPatcher\AppHostPatcher.csproj.
  AppHostPatcher -> C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSp
y-master\Build\AppHostPatcher\bin\Release\net472\AppHostPatcher.exe

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.73
Building .NET Framework x86 and x64 binaries
Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\Libraries\ICSharpCode.TreeView\ICSharpCode.TreeView.csproj" was not found.
 [C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-master\dnSpy.sln
]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\
ICSharpCode.Decompiler.csproj" was not found. [C:\Users\itmanager.SAFARI-HOTELS\
Downloads\dnSpy-master\dnSpy-master\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory\ICSharpCode.
NRefactory.csproj" was not found. [C:\Users\itmanager.SAFARI-HOTELS\Downloads\dn
Spy-master\dnSpy-master\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\Extensions\ILSpy.Decompiler\NRefactory\ICSharpCode.NRefactory.CSharp\ICSha
rpCode.NRefactory.CSharp.csproj" was not found. [C:\Users\itmanager.SAFARI-HOTEL
S\Downloads\dnSpy-master\dnSpy-master\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\NRefactory.VB\ICSharpCo
de.NRefactory.VB\ICSharpCode.NRefactory.VB.csproj" was not found. [C:\Users\itma
nager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-master\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\dnSpy\dnSpy.Images\dnSpy.Images.csproj" was not found. [C:\Users\itmanager
.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-master\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\dnSpy\Roslyn\Roslyn.ExpressionCompiler\Core\ExpressionCompiler\ExpressionC
ompiler.csproj" was not found. [C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy
-master\dnSpy-master\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\dnSpy\Roslyn\Roslyn.ExpressionCompiler\CSharp\CSharpExpressionCompiler\CSh
arpExpressionCompiler.csproj" was not found. [C:\Users\itmanager.SAFARI-HOTELS\D
ownloads\dnSpy-master\dnSpy-master\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\Extensions\dnSpy.Debugger\Mono.Debugger.Soft\Mono.Debugger.Soft.csproj" wa
s not found. [C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-mast
er\dnSpy.sln]
C:\Program Files (x86)\dotnet\sdk\3.0.102\NuGet.targets(268,5): error MSB3202: T
he project file "C:\Users\itmanager.SAFARI-HOTELS\Downloads\dnSpy-master\dnSpy-m
aster\dnSpy\Roslyn\Roslyn.ExpressionCompiler\VisualBasic\BasicExpressionCompiler
\BasicExpressionCompiler.vbproj" was not found. [C:\Users\itmanager.SAFARI-HOTEL
S\Downloads\dnSpy-master\dnSpy-master\dnSpy.sln]

**Comment by vzarytovskii** [comment]
@ernstgruber By downloading a zip, do you mean that you have downloaded the repo using GitHub's "Download ZIP" feature? In this case, you're probably missing submodules. I would recommend recursively clone the repo (or clone and fetch submodules).

**Comment by ernstgruber** [comment]
Hallo Vlad,

thanks will try.

Greetings Ernst

**Comment by ernstgruber** [comment]
Hallo,

did recursive clone with git command line.
Compiled fine with dotnet build.

Do you guys have a howto / getting started for dnSpy?

Greetings Ernst

**Comment by 0xd4d** [comment]
There's no how-to, but maybe google or youtube has something.
