### ISSUE TITLE
DnSpy - AntiSave Protection? Saves Incorrect files (Iam propably dumb)

### ISSUE THREAD

**Issue by xD3T** [0xd4d/dnSpy#1407]
Iam using latest version (6.1.3 NET Core)
So i just dumped the file (bc was packed with Themida Winlicense 2x) using Extreme Dumper.
Dumped file was working . I wanted to edit in in DnSpy
Then i edited file a bit.
And the file that i saved wasnt working and had some weird stuff inside (i have never seen that before)
Screen when i open saved file in debugger
![wtf](https://user-images.githubusercontent.com/60032424/75562219-84c6fd00-5a48-11ea-808b-6b2031d37f0b.PNG)

All Files are here : https://anonfile.com/F0Xf26d1o1/ProxyKek_rar

I appreciate any help.

**Comment by 0xd4d** [comment]
Add more info eg. what is not working, etc.

**Comment by xD3T** [comment]
So i put dumped (working) assembly in DnSpy and edited it then i saved it , but the file which i saved looked like picture above which wasnt assembly that i put in But if you UNCHECK mixed mode module (i dont know real name, bc iam using other language than english) it will save the real assembly.

![real assembly](https://user-images.githubusercontent.com/60032424/76021015-cbbf6180-5f24-11ea-893c-b8523c759cba.PNG)

**Comment by xD3T** [comment]
![1](https://user-images.githubusercontent.com/60032424/76021094-e7c30300-5f24-11ea-902a-aab754bf6735.PNG)

This is the settings in czech :)

**Comment by 0xd4d** [comment]
Maybe the same as https://github.com/0xd4d/dnlib/issues/345

**Comment by 0xd4d** [comment]
Try downloading the latest dnlib from the CI here: https://github.com/0xd4d/dnlib/runs/524338684 and replace your file with that one and see if that solved your issue.
