### ISSUE TITLE
crashes during debug

### ISSUE THREAD

**Issue by ernstgruber** [0xd4d/dnSpy#1408]
used dnSpy v6.1.3 (.NET Core)
to try to debug an .Net Framework 4, 32 bit assembly
got exception, see attachment
[dnspy debug exception.zip](https://github.com/0xd4d/dnSpy/files/4275317/dnspy.debug.exception.zip)

**Comment by 0xd4d** [comment]
Add full repro steps and copy and paste the stack trace here.
