### ISSUE TITLE
Help Request: Extensions Not Loading

### ISSUE THREAD

**Issue by rocky1928** [0xd4d/dnSpy#1411]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?
Latest Build available 3/7/2020

- Write down all steps needed to reproduce this issue. Also attach any needed files.

1. Install via git.
2. Open dnSpy
3. Open any file via dnSpy.

Results: The decompiler extension wasn't built. Make sure you build every project before you press F5.
Uncheck: Settings -> Projects and Solutions -> Build and Run -> Only build startup projects and dependencies on Run

![image](https://user-images.githubusercontent.com/43506958/76151301-8cf2ee00-6081-11ea-8685-b19d4cb498fd.png)

**Comment by 0xd4d** [comment]
The message says you should compile everything and not just hit F5. VS defaults to only building the required projects for the currently selected executable project. dnSpy needs all projects to build since there are many extensions.
