### ISSUE TITLE
Does the debugger has an API for extensions?

### ISSUE THREAD

**Issue by Scorbie** [0xd4d/dnSpy#1412]
Hello and thank you for developing this.

- What version did you use?
    The version as of the time of this writing is 6.1.3.

- What I am trying to do:
    Make a class tracepoint for all classes in an assembly.

- My Questions are:
    1. Whether a certain part (making a tracepoint especially, so the debugger) has an exposed API.
    2. Scripting
        - When I script inside dnSpy, am I restricted to the same assemblies as in making extensions?
        - Can I use scripting to automate things as an extension does? (probably a no after viewing the structure of the application)

- `ClassBreakpointCommands.cs` grabs things from `dnSpy.Contracts.Debugger.Breakpoints.Code` but I'm assuming you shouldn't mess up with this?

**Comment by 0xd4d** [comment]
A script should be able to do anything an extension can do. You have to import stuff explicitly instead of relying on MEF doing that for you.

A tracepoint is just a breakpoint, and the debugger has an API to add/edit/remove those.

**Comment by Scorbie** [comment]
Thank you!
