### ISSUE TITLE
enum related compiling issue

### ISSUE THREAD

**Issue by RedFoxAttack** [0xd4d/dnSpy#1414]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?
6.1.3

- Write down all steps needed to reproduce this issue. Also attach any needed files.
	public enum ECheatType
	{
		NONE,
		IMMUNE,
		HIDDEN,
		UNLIMITED,
		TURBO,
		SHUFFLE,
		LUCKY_DIP,
		DOUBLE_STRAIN
	}

the following code piece
		switch (cheatType)
		{
		case Disease.ECheatType.SHUFFLE:
		case Disease.ECheatType.LUCKY_DIP:
		case Disease.ECheatType.DOUBLE_STRAIN:
			return localPlayerInfo.GetIntStat("UNLOCK_MEGA_CHEATS") == 1;
		default:
			return localPlayerInfo.GetIntStat("UNLOCK_BRUTAL_CHEATS") == 1;
		}
will be compiled to incorrect code
	if (cheatType - Disease.ECheatType.SHUFFLE <= 2)
	{
		return localPlayerInfo.GetIntStat("UNLOCK_MEGA_CHEATS") == 1;
	}
	return localPlayerInfo.GetIntStat("UNLOCK_BRUTAL_CHEATS") == 1;

**Comment by 0xd4d** [comment]
What's missing is the unsigned check, it's a known issue in ILSpy v2.x which dnSpy uses. See https://github.com/0xd4d/dnSpy/issues/936 which tracks upgrading to a newer version.
