### ISSUE TITLE
Chinese garbled 

### ISSUE THREAD

**Issue by Any3ite** [0xd4d/dnSpy#1417]
- What version did you use?

    6.1.3

- Write down all steps needed to reproduce this issue. Also attach any needed files.

After decompiling DLL with dnspy, it is found that there is disorder in Chinese. When setting font, you can only select font, not language code.

**Comment by Any3ite** [comment]
![1584348477336](https://user-images.githubusercontent.com/20638313/76738623-f374bc00-67a5-11ea-85d7-31edfea78dab.jpg)

**Comment by 0xd4d** [comment]
What's the issue here? Why would you need to know the language code when selecting a font?

What do you expect to see?

**Comment by HoLLy-HaCKeR** [comment]
These aren't just Chinese characters, there's Korean and probably others in there too. This is most likely just an obfuscation technique.

**Comment by UlyssesWu** [comment]
I believe he has little knowledge about obfuscation and thought it was some kind of Encoding issue. This issue should be closed.
