### ISSUE TITLE
Mouse Event Messages Not Propagating From DnSpy And App Under Debug

### ISSUE THREAD

**Issue by lukakoczorowski** [0xd4d/dnSpy#1421]
- What version did you use?
v6.1.4

- Write down all steps needed to reproduce this issue. Also attach any needed files.
1. Hook into Windows Message Queue and listen for mouse events
OR
1. Try to control DnSpy remotely (Zoom/Webex)

Are there any option(s) to allow windows event messages within DnSpy and any apps under debug, to propagate globally? Or is this expected behaviour? 

Thank you!

**Comment by 0xd4d** [comment]
Can you reproduce this with other WPF apps?
