### ISSUE TITLE
Int/string search not working for attribute parameters applied to interface

### ISSUE THREAD

**Issue by s809** [0xd4d/dnSpy#1422]
(Ver 6.1.4)
Search "10101010101010" (int/string selected) returns empty list for following:
```
class TestAttribute : Attribute
{
    public TestAttribute(long l) { }
}

[Test(10101010101010)]
interface TestInterface { }
```

**Comment by 0xd4d** [comment]
It happens because it has no members so it's filtered out here https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy/Search/FilterSearcher.cs#L407
