### ISSUE TITLE
<module> error!

### ISSUE THREAD

**Issue by bwmsdroid** [0xd4d/dnSpy#1423]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?
6.1.3
- Write down all steps needed to reproduce this issue. Also attach any needed files.
I just drag n drop the file on dnspy. Try to edit and compile. So give this error on compiling
![image](https://user-images.githubusercontent.com/53904508/77704051-06a03c80-6f9b-11ea-87e8-eeaeb2e31f8d.png)
cuz of this 
![image](https://user-images.githubusercontent.com/53904508/77704130-2d5e7300-6f9b-11ea-9621-7fabdd0a4496.png)
the \<module\> is invalid.

I already used the de4dot.
Thanks

**Comment by Symbai** [comment]
Compiling C# code does not work if the assembly is obfuscated (or poorly deobfuscated). Edit the IL instructions instead to achieve whatever you wanted to modify.

**Comment by bwmsdroid** [comment]
thanks, it use appfuscator. i will try to deob...
