### ISSUE TITLE
Inject managed DLL into debug target

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#1425]
Would be a great feature to inject a managed dll into a managed application when debugging it with dnSpy.

**Comment by 0xd4d** [comment]
You can call `Assembly.Load{File}()`/etc in the `Watch` window

**Comment by Symbai** [comment]
How can I do this? When i attach the watch window is empty and cannot be edit

**Comment by 0xd4d** [comment]
It's still running, you need to pause it.

Calling .NET functions most likely will fail unless you're stopped at a safe point, and that requires you to step once in some thread. If it's optimized code, it will most likely fail too so make sure you've read this: https://github.com/0xd4d/dnSpy/wiki/Making-an-Image-Easier-to-Debug

**Comment by Symbai** [comment]
After paused I still don't know how to call a function there. In "name" column I enter "Assembly.LoadFile" ? and in "Value" i enter the full path and then continue the paused application?!

Would be much easier and more obvious for users if the Modules window gets a context menu item "load/inject module...", prompt to pause the target application if not (or does it automatically) and then calls the method or whatsoever.

**Comment by 0xd4d** [comment]
You have to use reflection to find the method and call it. Just like you would need to do if you wrote a C# program to load an assembly at runtime.

**Comment by Symbai** [comment]
Either i misunderstand you or you misunderstood me. My original question was how do I inject a managed library into a managed **running process** and call its STAThread method. 

You said I could call Assembly.LoadFile to force the running process to load my managed library. For a NOT running process this makes sense and it's easily done by patching the source code and add a line, just like I would do it on my own C# program.

However the question was about a running process without patching any source code. It is still unclear for me **how** I can call a method remotely for a running process, as this is what you suggested unless you misunderstood me.

**Comment by riQQ** [comment]
The running process has to be stopped at a safe point and then you can input `System.Reflection.Assembly.Load("Microsoft.Deployment.Compression.Cab")` in the column `Name` of the Watch window. In the column `Value` you will see the return value on success or the exception or error on failure:

![grafik](https://user-images.githubusercontent.com/3404787/78046965-18f1f000-7378-11ea-9e46-639dd6bd29b6.png)

**Comment by Symbai** [comment]
@riQQ Thanks for the "how to".
