### ISSUE TITLE
File gets run when using the wrong bitness "flavor" of dnSpy to debug (possibly a Security issue?)

### ISSUE THREAD

**Issue by zsr2531** [0xd4d/dnSpy#1426]
### What version did you use?
> 6.1.4

### Repro
- Open a 64bit file in 32bit dnSpy
- Click debug

### Expected
- The file doesn't get run and an error message box appears that the invalid bitness "flavor" was used

### Actual
- The error box appears, but the file gets run without any warnings

**Comment by 0xd4d** [comment]
If you suspect the exe you want to debug/analyze is malware you should always use a VM.

dnSpy uses the normal ICorDebug API to debug .NET programs. If you think this is an issue, open an issue here: https://github.com/dotnet/runtime/issues
