### ISSUE TITLE
Lauch dnSpy from a developer mod to show a specific class member

### ISSUE THREAD

**Issue by pardeike** [0xd4d/dnSpy#1428]
Feature Request

How difficult would it be to make dnSpy jump to a specific member in, lets say an already loaded dll, triggered by an event from outside of dnSpy?

I just made a mod for my favorite game that lists the current rendering method when you click on it in the game and I would like to open dnSpy and let it jump right into displaying the method?

Imagined ways and thoughts:
- have a document open event and it contains the necessary information (like dll path and the full member info)
- load dll if not loaded already
- mainly for methods but I can see it for fields too
- minime version: just send a string that will auto-populate the search field and run the search with the right search type
- maybe extend https://github.com/0xd4d/dnSpy/wiki/Command-Line-Arguments

Is that a use case for an Extension?

**Comment by CreateAndInject** [comment]
Reflector can do it, command line:
`Reflector.exe /share /select:"code://......"`
Menu>Edit>Copy Code Identifier (Ctrl+Alt+C) can get the code.
I don't know whether dnSpy can do it or not.

**Comment by 0xd4d** [comment]
This should already be possible.

- Uncheck `Allow more than one instance (restart required)` in dnSpy settings
- `dnSpy "c:\path\to\your\file.dll" --select 0x06000002`

`0x06000002` is the metadata token of that member.

**Comment by pardeike** [comment]
Wheeeeee - nice!

**Comment by pardeike** [comment]
Just for fun, I made a small video with the new feature:
https://vimeo.com/403675075
