### ISSUE TITLE
Help - White horizontal lines. Can't find option to hide

### ISSUE THREAD

**Issue by erik9631** [0xd4d/dnSpy#1429]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?
472
- Write down all steps needed to reproduce this issue. Also attach any needed files.
I am not sure.

The issue is that I can not for the life of me find an option that would allow me to remove these white vertical separators of methods

![image](https://user-images.githubusercontent.com/20126561/78183290-f212e700-7467-11ea-9702-f06857fa5a4c.png)

Can someone help me to sort this out? Thanks!

**Comment by InlineAsm** [comment]
Try this:
![image](https://user-images.githubusercontent.com/6095763/78277137-4d9aae80-7514-11ea-88c8-64e2ad9b8f9c.png)

**Comment by erik9631** [comment]
Thanks, that did it.
