### ISSUE TITLE
Improve 'Go to MD Token'

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#1433]
I think it can be designed like this:
![image](https://user-images.githubusercontent.com/2529999/78654469-1d2d8880-78f7-11ea-9e9b-a1f7e4779436.png)

Notice:
1. If `Token` is checked, the ComboBox should be disabled.
2. No matter whether there's a `0x` prefix if `Hex` is checked.
3. Every time the user open this dialog, the default option is the same as last used, even if the user close and reopen dnSpy.
For example, if I checked `Rid` and select `Method` in ComboBox, checked `Hex`, when I open it next, it will keep these options.
4. When the user open this dialog, TextBox is focused so I can paste without clicking it, and `OK` is the AcceptButton so I can use `Enter` when the TextBox is focused (dnSpy does this already).

**Comment by 0xd4d** [comment]
That's too complicated. A field with the token is enough. I'll likely close this.

**Comment by piratesephiroth** [comment]
The dialog is called "Go to MD Token" so it should only have the textbox for the user to write the token.

Perhaps a reminder that it has to be a hex value could help but other changes seem unecessary.

**Comment by CreateAndInject** [comment]
The thing what I must do every time is : How many zeros I should insert?
Rid `d7` contains 2 numbers, so I should insert 4 zeros => `0x060000d7`
Rid `5d7` contains 3 numbers, so I should insert 3 zeros => `0x060003d7`
Rid `11d7` contains 4 numbers, so I should insert 2 zeros => `0x060011d7`

And I have to ceaselessly switch Hex & Dec when I debug in Visual Studio, since If I use `Hex`, I don't know how big a number is, and If I use `Dec`, and I want to view a TypeDef/MemberDef in dnSpy, I have to use Hex format.

In most time, the most important thing I care about is `MethodDef`, so I just remember the rid of a method in my brain when I debug in Visual Studio, and when I want to view in dnSpy, I have to insert appropriate zeros to convert a rid to token.

**Comment by 0xd4d** [comment]
I'll close this. The dialog box is too complicated. Sounds like the biggest problem you have is adding zeroes, and I just tried this, I could easily type eight 0s in 1 sec, so you'll lose at most 1 sec adding zeroes.

You can write an extension and add your own dialog box, or update dnSpy's code.
