### ISSUE TITLE
System.IndexOutOfRangeException when trying to edit the method

### ISSUE THREAD

**Issue by Rasko1** [0xd4d/dnSpy#1437]
I'm using the version 6.1.4

I am able to see an obfuscated method with it strings (which aren't obfuscated) but when I try to edit it  I get System.IndexOutOfRangeException 

en dnSpy.AsmEditor.Compiler.MDPatcherUtils.ReadCompressedUInt32(Byte*& data, Byte* end) en D:\a\dnSpy\dnSpy\Extensions\dnSpy.AsmEditor\Compiler\MDPatcherUtils.cs:línea 59

I don't know why is that path there I'm using it on C:\

Is this a bug of mine? Why am I able to see the code but I cant edit the method?

**Comment by 0xd4d** [comment]
It was thrown by dnSpy, it should throw its own type instead of IOOR.

**Comment by 0xd4d** [comment]
Since it's obfuscated you should try de4dot first.
