### ISSUE TITLE
Antivirus Detection - False Positive?

### ISSUE THREAD

**Issue by snorlax2** [0xd4d/dnSpy#1438]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?
v6.1.4

- Write down all steps needed to reproduce this issue. Also attach any needed files.
I downloaded **dnSpy-net472.zip** from the release page. Malwarebytes picked up the file **dnSpy-x86.exe** as **malware-generic-1290998494**.
[https://blog.malwarebytes.com/detections/malware-generic-1290998494](https://blog.malwarebytes.com/detections/malware-generic-1290998494)
SHA-256: 2EF2ACEFCC3D9F824B542C5B8CEC89CA8F68CD63EA0FEE3C16354558D62F867E

Malwarebytes on VirusTotal didn't detect it, probably outdated.
Screenshot from my local Malwarebytes installation:
![9iutQ0qH6C](https://user-images.githubusercontent.com/63527587/79059477-cd461d00-7c7a-11ea-8ddb-960833fa6f52.png)

**Comment by 0xd4d** [comment]
You should contact malwarebytes, I can't fix their code.

Always download dnSpy from the official link which is https://github.com/0xd4d/dnSpy/releases

It's built by GitHub Action and uploaded by the same GitHub Action. If you trust GitHub you can trust that download too.
