### ISSUE TITLE
Export To Project - Could Not Be Opened, Error "A numeric comparison was attempted on..."

### ISSUE THREAD

**Issue by metal450** [0xd4d/dnSpy#1439]
What version did you use? 
6.1.4 64-bit (.NET Framework)

Steps to reproduce:

* Open the attached dll
* File->Export To Project, Version= VS2019
* Open the project in VS

Visual Studio reports that the project could not be opened.  Error:

     A numeric comparison was attempted on "$(_TargetFrameworkVersionWithoutV)" that evaluates to "" instead of a number, in condition "('$(TargetFrameworkIdentifier)' != '.NETCoreApp' OR '$(_TargetFrameworkVersionWithoutV)' < '3.0') AND
                            ('$(TargetFrameworkIdentifier)' != '.NETStandard' OR '$(_TargetFrameworkVersionWithoutV)' < '2.1')".  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets

[MailClient.zip](https://github.com/0xd4d/dnSpy/files/4466813/MailClient.zip)

**Comment by 0xd4d** [comment]
Can you paste the generated csproj and show the full error message(s) including line numbers etc?

**Comment by metal450** [comment]
There's no line number - except for the filename, that is the full error message. Screenshot: https://lnk2.tk/snaps/2020-04-12_14.09.49.png

Project file attached.

[project.zip](https://github.com/0xd4d/dnSpy/files/4467122/project.zip)

**Comment by ChungYork** [comment]
@0xd4d 
I found out this promble too. Both I use 6.1.4 32-bit and 64-bit (.NET Core) to export a WPF Core project.

I think the problem is can not generated the .net core SDK-style csproj. 

@metal450 
 Manual change the csproj to SDK-style, it may work.

**Comment by 0xd4d** [comment]
I could repro it with a .NET Core project. It doesn't support generating new SDK csproj files, so you'll find something like this which you can remove/update.

```
    <TargetFrameworkVersion>v2.2</TargetFrameworkVersion>
    <TargetFrameworkIdentifier>.NETCoreApp</TargetFrameworkIdentifier>
```

**Comment by metal450** [comment]
I was able to fix the generated project file by replacing:

    <TargetFrameworkVersion>v3.1</TargetFrameworkVersion>
    <TargetFrameworkIdentifier>.NETCoreApp</TargetFrameworkIdentifier>

With

     <TargetFramework>netcoreapp3.2</TargetFramework>

...So I guess that's how the project generation code needs to be revised for it to output working projects :)

**Comment by 0xd4d** [comment]
That's not the only change that would be needed. There's already an issue about supporting the new SDK csproj format (https://github.com/0xd4d/dnSpy/issues/1185).
