### ISSUE TITLE
ARM Windows support?

### ISSUE THREAD

**Issue by Ranomez** [0xd4d/dnSpy#1442]
The .NET Framework 4.7.2 build being AnyCPU this should already run on ARM Windows (both ARM32 and ARM64) however I can not test that since I am using ARM32 Windows devices with jailbreak (Microsoft Surface RT and 2) and I have not fully updated Windows RT 8.1 and the ARM32 build of Windows 10 is stuck with .NET Framework 4.7.
But .NET Core exists for ARM32 (and .NET 5 promises ARM64 builds as well, in fact Preview 2 already has an ARM64 build of the runtime) so I would like to ask whether it would be possible to add support for ARM Windows (both ARM32 and ARM64) as well in the future?
I have already tried looking at it myself but I seem to be having issues with some missing packages that nuget doesn't seem to want to install so I can't even compile any version of it as of this moment (otherwise I'd have tried at least changing the .NET Framework requirement).

**Comment by 0xd4d** [comment]
Have you tried changing the TFM from net472 to net47 and recompiled it?

AFAIK, .NET 5 will support ARM64 + WPF/WinForms.

https://github.com/0xd4d/dnSpy/blob/12ddf66a3a71bfeeff9cc82febb37aa9bc7d8d80/DnSpyCommon.props#L9
https://github.com/0xd4d/dnSpy/blob/12ddf66a3a71bfeeff9cc82febb37aa9bc7d8d80/build.ps1#L4

Other changes for .NET Core

https://github.com/0xd4d/dnSpy/blob/12ddf66a3a71bfeeff9cc82febb37aa9bc7d8d80/DnSpyCommon.props#L24

add arm/arm64

https://github.com/0xd4d/dnSpy/blob/12ddf66a3a71bfeeff9cc82febb37aa9bc7d8d80/build.ps1#L93-L95
