### ISSUE TITLE
I can not compile

### ISSUE THREAD

**Issue by LUCA1337q** [0xd4d/dnSpy#1444]
- What version did you use?

Latest ( v6.1.4)

- Write down all steps needed to reproduce this issue. Also attach any needed files.

| I opened the file in DnSpy.exe 
| Went to where I needed to go (what code I wanted to change), in this case the Auth() class
| Went to compile after editing method
| Getting CS0246 errors even when not editing code and trying to compile.

**Comment by Itamai** [comment]
https://github.com/0xd4d/dnSpy/issues/363
https://github.com/0xd4d/dnSpy/issues/933
read the answers from 0xd4d on both issues that should answer your question.

**Comment by 0xd4d** [comment]
I think this has been answered.
