### ISSUE TITLE
How I can modify an image in Resources

### ISSUE THREAD

**Issue by Santy4tas** [0xd4d/dnSpy#1449]
I'm using dnSpy v6.1.6 and I was wonder how I can replace images in Resources. I want to change the visual interface of a .exe , actually I can see all the images I want to replace in the "Resources" folder, but I don't have idea how to do it? Can you help me please? Thank you ;)

**Comment by 0xd4d** [comment]
If you right-click on it Assembly Explorer you should see some edit commands.
