### ISSUE TITLE
Cannot build dnSpy

### ISSUE THREAD

**Issue by kentlow2002** [0xd4d/dnSpy#1451]
- What version did you use?
Latest (pulled from github on the day of this post)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
Pull the latest version.
Install .NET Framework version 4.8
Run ./build.ps -NoMsBuild in Powershell
Result is the following output.
![image](https://user-images.githubusercontent.com/6638924/80216382-8c81d700-8670-11ea-9878-c52202434d36.png)

**Comment by 0xd4d** [comment]
Try updating the .NET Core SDK version number in this file: https://github.com/0xd4d/dnSpy/blob/master/global.json

**Comment by kentlow2002** [comment]
Thanks for the help. I actually resolved it by installing .NET Framework 4.7.2 lol.
