### ISSUE TITLE
Can't decompile BCL of .Net Core?

### ISSUE THREAD

**Issue by akimusume** [0xd4d/dnSpy#1454]
6.1.4
I decompiled many libraries, and found most/all BCL library of .Net Core has no implementation. For example, the DateTime in System.Runtime(C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1). it should have been implemented, but it just "throw null;" in dnSpy. Why?

**Comment by 0x53A** [comment]
It's a "ref" assembly, it contains only the public interface but not the implementation

**Comment by 0xd4d** [comment]
Have a look in `C:\Program Files\dotnet\shared`, those should be normal runtime assemblies.
