### ISSUE TITLE
Adding non-static fields causes game to crash

### ISSUE THREAD

**Issue by Darkar25** [0xd4d/dnSpy#1456]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?
Dnspy 6.1.2
Unity 2019.3.2.27194

- Write down all steps needed to reproduce this issue. Also attach any needed files.
1.Open Dnspy
2.Open Assembly-CSharp of an Unity game
3.Add non-static field of any type with any name to any class
4.Run the game
5.See its crashing

In crash log it says that sharedassets0.assets is corrupted
Also it says "Attempt to request to invalid address"

**Comment by 0xd4d** [comment]
Is the class deserialized? If so adding new fields probably won't work.

**Comment by Darkar25** [comment]
> Is the class deserialized? If so adding new fields probably won't work.

how to deserialize a class?
