### ISSUE TITLE
Can you make ICSharpCode.Decompiler as a part of this repo rather than a sub module?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#1459]
I make some changes for ICSharpCode.Decompiler, everytime you update it, I'm hard to accept your changes, VS2019 can't update sub module if it' changed. I have to undo my changes, and accept your changes, and then redo my changes, I repeat this steps dozens of times, everytime I have to spend about half an hour.

**Comment by 0xd4d** [comment]
Sounds lik you need to learn how to merge. There are many git tutorials you can read.

**Comment by CreateAndInject** [comment]
![image](https://user-images.githubusercontent.com/2529999/82120953-221a0d80-97bc-11ea-9628-bb442ca8ed1b.png)

@0xd4d VS doesn't show the differeces of the conflicts for sub module
