### ISSUE TITLE
Can not decompile the .net framework library

### ISSUE THREAD

**Issue by chucklu** [0xd4d/dnSpy#1464]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?
6.1.4

- Write down all steps needed to reproduce this issue. Also attach any needed files.

Try to decompile C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\mscorlib.dll
The method body is empty
```C#
// System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>
/// <summary>Returns an enumerator that iterates through the <see cref="T:System.Collections.Concurrent.ConcurrentDictionary`2" />.</summary>
/// <returns>An enumerator for the <see cref="T:System.Collections.Concurrent.ConcurrentDictionary`2" />.</returns>
// Token: 0x06003033 RID: 12339 RVA: 0x00005333 File Offset: 0x00003533
public IEnumerator<KeyValuePair<TKey, TValue>> GetEnumerator()
{
}

```

**Comment by chucklu** [comment]
It's weird, I can check the source code with C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\Facades\System.Collections.Concurrent.dll.
![image](https://user-images.githubusercontent.com/3004057/81528688-de746d80-938f-11ea-8b46-8ee1163137b1.png)

**Comment by 0xd4d** [comment]
Reference assemblies should not have any code. Use `File -> Open from GAC` instead.

**Comment by chucklu** [comment]
Thanks, it works.
![image](https://user-images.githubusercontent.com/3004057/81540386-2b623f00-93a4-11ea-8837-1999ba51fc2a.png)
![image](https://user-images.githubusercontent.com/3004057/81540424-39b05b00-93a4-11ea-96ba-16c59e7b7df7.png)
