### ISSUE TITLE
DNSpy not opening!

### ISSUE THREAD

**Issue by burtoSUPERIOR** [0xd4d/dnSpy#1465]
I opened releases and downloaded new version whilst downloading ran into a little trouble to know that when i open in admin or anything else it doesnt appear or anything

**Comment by czghzc** [comment]
I also had this problem, nothing appeared after opening ...

I reinstalled the system (Win7x64), and then enabled dotNet3.5, installed dotNet4.0, dotNet4.5, vc2015_redist and dotNet-runtime, but none of them solved the problem

I want to know what is the reason ...
