### ISSUE TITLE
Add Note To Wiki (Debugging Unity Games)

### ISSUE THREAD

**Issue by Kr4ken-9** [0xd4d/dnSpy#1466]
- What version did you use?
N/A
- Write down all steps needed to reproduce this issue. Also attach any needed files.
N/A

Under `Turning a release build into a debug build` a note could be added that some versions of Unity will require the file `WinPixEventRuntime.dll` in addition to the WindowsPlayer.exe and UnityPlayer.dll

Specifically, this was encountered during debugging version `2018.4`

Example below:
![](https://i.imgur.com/qYsp69A.png)

**Comment by 0xd4d** [comment]
I've updated the wiki settings, you should be able to edit it now. Thanks!

**Comment by Kr4ken-9** [comment]
I have added the note to the wiki page. Thank you!
