### ISSUE TITLE
System.OverflowException: Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#1473]
- What version did you use?
6.1.4
- Write down all steps needed to reproduce this issue. Also attach any needed files.
`System.Array.SorterGenericArray.QuickSort`

Dec is no problem, Hex will occur : System.OverflowException: Arithmetic operation resulted in an overflow.

**Comment by 0xd4d** [comment]
How do you repro this?

**Comment by CreateAndInject** [comment]
1. Checked `Options->Decompiler->Hexadecimal numbers`
2. Decompile `System.Array.SorterGenericArray.QuickSort` (mscorlib.dll)

**Comment by 0xd4d** [comment]
Is it a debug build?

**Comment by CreateAndInject** [comment]
yes
