### ISSUE TITLE
wierd glitch

### ISSUE THREAD

**Issue by elephantshow** [0xd4d/dnSpy#1476]
I get 

IŔɫͮѮԦشܵࡩॹ੤ୢ౰൶๺ོဿᅳበ፣ᐢᕾᙪ᝽ᠦᥚᩒ᭯ᰳᵁṕ὆⁶

and stuff like that. Please help

**Comment by InlineAsm** [comment]
Sounds like you have an obfuscated assembly. Try to run it through de4dot.
If that doesn't solve the problem make sure you include MUCH more information than random garbage and 'stuff like that'.
