### ISSUE TITLE
no open

### ISSUE THREAD

**Issue by ReaperVoid** [0xd4d/dnSpy#1477]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?

- Write down all steps needed to reproduce this issue. Also attach any needed files.

**Comment by 0xd4d** [comment]
There's no info at all here. I'm going to close this.

Just a guess, install all .NET Core required Windows updates, see https://github.com/0xd4d/dnSpy/releases or get the .NET Framework build instead.
