### ISSUE TITLE
Unity Debugging version 2019.2.2

### ISSUE THREAD

**Issue by congtrung2k1** [0xd4d/dnSpy#1478]
Dear admin,

I debugged a couple hours ago on Unity platform game version 2019.2.2. But, on https://github.com/0xd4d/dnSpy/releases site, the version is only for 2019.1. Did version 2019.2 release somewhere else I didn't know?

Thanks for your time!

**Comment by 0xd4d** [comment]
`2019.2.1-mbe` exists in the source repo, you can compile it yourself if you have the tools.

https://github.com/0xd4d/dnSpy-Unity-mono

I'll close this, see also the other issue https://github.com/0xd4d/dnSpy/issues/1392
