### ISSUE TITLE
Feature request (kinda?): Ignore unrelated errors

### ISSUE THREAD

**Issue by SanicStudios** [0xd4d/dnSpy#1481]
A great addition would be to add the ability to compile with errors to code that you did not change. Have a checkbox or a warning message appear before compiling or something.

I don't have very much experience with coding and so when things start going wrong that I didn't change it's extremely frustrating, especially when I know what I should be doing.

**Comment by 0xd4d** [comment]
It's not possible. Edit a method instead of the whole class to get less errors (the less you decompile the less errors you'll get). If you get some errors in main.g.cs, the easiest solution is to just remove those methods/properties and try again.

**Comment by Toshiba1127** [comment]
^ I have been using this solution so far and it always went great :))
