### ISSUE TITLE
Path does not contain a definition for Combine

### ISSUE THREAD

**Issue by Arktiks** [0xd4d/dnSpy#1482]
**What version did you use?**
dnSpy v6.1.4 (.NET Core)

**Problem**
I'm trying to edit Assembly-CSharp.dll for an Unity game. "Edit Class" fails to compile because it can't find definition for Path.Combine. In viewer it seems to recognize the function ok. Viewer correctly links to mscorlib.dll (System.IO) that is part of the Managed game assets.

![Path does not contain a definition for Combine](https://i.imgur.com/qaTDOhL.jpg)

**Comment by 0xd4d** [comment]
Make sure the method exists. Maybe it was removed when the file was published.

**Comment by 0xd4d** [comment]
You can click on `Path.Combine` in the decompiler window. If it finds the method, figure out which DLL it's coming from and add it as a reference in the `Edit Class` window (BTW, you should use `Edit Method` most of the time).

**Comment by Arktiks** [comment]
Yeah the method should still exist in `mscorlib.dll`.
![mscorlib.dll](https://i.imgur.com/hrC7fkJ.png)

I tried `Edit Method` instead and the error persists. I tried adding a reference to `mscorlib.dll` via `Add Assembly Reference (Ctrl+O)` in the `Edit Code` window but it had no effect.
![Edit Method](https://i.imgur.com/NsOlVk7.png)

**Comment by 0xd4d** [comment]
Can you add a repro

**Comment by Arktiks** [comment]
Reproduction steps? Ok.

**Here are [Game DLL Files](https://drive.google.com/file/d/1fiJzVboACkqUkUSbZECtMd7zyB5vsima/view?usp=sharing).**

1. Open Data > Managed > Assembly-CSharp.dll with dnSpy.
2. Search `GameDirectory`.
3. Open result `get_GameDirectory`.
4. Edit `GameDirectory` **get**-method.
5. Add Assembly reference to `mscorlib.dll`.
6. Try to Compile method without making any changes.

If it's any help the game was compiled on Unity version 5.3.6p1.

**Comment by 0xd4d** [comment]
There are two `Path` classes, the workaround is to change those `Path` refs to `System.IO.Path` and then fix the error in main.g.cs by removing the property the compiler complains about.

**Comment by Arktiks** [comment]
Thank you for the workaround.
