### ISSUE TITLE
OnGUI crashes game

### ISSUE THREAD

**Issue by MeDiamondStar** [0xd4d/dnSpy#1486]
when i'm creating a void function with a gui line:

```
public void CreateConsole(float posx, float posy, float scalex, float scaley)
    {
        ConsoleText = GUI.TextArea(new Rect(posx + xdiffrence, posy + ydiffrence, scalex, scaley), ConsoleText);
    }
```

and then calling it in a OnGUI function:

```
void OnGUI()
{
      CreateConsole(150, 0, 600, 200);
}
```
the game crashes(when the specific scene with the script gets loaded)
i've tryed the code in unity and it works perfectly without any errors
any idea why?
i am using C# and dnSpy v6.1.4 (64 bit)
(i don't know if this is wrong where i am posting, i am new at github)

**Comment by 0xd4d** [comment]
> any idea why?

No, but try debugging it.
