### ISSUE TITLE
call <null> in IL

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#1487]
Generally speaking, dnSpy will show `call <null>` (IL language) for a `call` instruction with null operand
![image](https://user-images.githubusercontent.com/2529999/84590549-3fe59b80-ae6a-11ea-983d-0729e5032dd0.png)

But why there's just a `call`?
![image](https://user-images.githubusercontent.com/2529999/84590563-54299880-ae6a-11ea-8967-92a0866ffbd7.png)

I hope dnSpy show `call <null>`, so I can search `<null>` to find it quickly.

**Comment by 0xd4d** [comment]
The fix is probably somewhere in `DisassemblerHelpers.cs`, PRs are welcome.

**Comment by CreateAndInject** [comment]
I debug it, the operand isn't null, it's a `MethodSpec`, but its `Method` property is null.
I think it's because I delete a generic method but it's still referenced.
