### ISSUE TITLE
mono.dll 2018.4.22

### ISSUE THREAD

**Issue by mentalisit** [0xd4d/dnSpy#1489]
tell me where can I get the file version I need 
mono.dll 2018.4.22

**Comment by InlineAsm** [comment]
Read the Wiki:
https://github.com/0xd4d/dnSpy/wiki/Debugging-Unity-Games

In the 'worst' case you have to create a patched mono.dll yourself.

**Comment by 0xd4d** [comment]
DId you try 2018.4.3? It's possible that it works since it has the same major and minor version. I'll close this as dupe of https://github.com/0xd4d/dnSpy/issues/1392

**Comment by mentalisit** [comment]
> Вы пробовали 2018.4.3? Вполне возможно, что он работает, поскольку у него одинаковые старшая и младшая версии. Я закрою это как обман [# 1392](https://github.com/0xd4d/dnSpy/issues/1392)

Failed to load mono
