### ISSUE TITLE
Projects from dnSpy.sln wont load in visual studio 2019

### ISSUE THREAD

**Issue by sygmak** [0xd4d/dnSpy#1491]
![obraz](https://user-images.githubusercontent.com/67188142/85847448-adb58f80-b7a7-11ea-89d1-3bc4b39e19c0.png)
do you have any exe verision ?

**Comment by 0xd4d** [comment]
The README explains how to compile it yourself.

Releases are here: https://github.com/0xd4d/dnSpy/releases
