### ISSUE TITLE
dnspy will not open

### ISSUE THREAD

**Issue by K1TTY-K4T** [0xd4d/dnSpy#1494]
have not changed anything and dnspy was working a few days ago.

**Comment by philipbawn** [comment]
I have the same problem and fireeye at my organization seems to be detecting and deleting dnSpy.dll. Do you have that also?

Someone else with the same problem issue #1493

**Comment by 0xd4d** [comment]
Duplicate of https://github.com/0xd4d/dnSpy/issues/1493
