### ISSUE TITLE
Debugging modified Unity Mono DLL

### ISSUE THREAD

**Issue by xyx0826** [0xd4d/dnSpy#1496]
dnSpy version: 6.1.5
Target Unity version: 2019.3.9-mbe

I patched and compiled a Mono DLL for Unity 2019.3.9. The game works correctly with the patched DLL but dnSpy could not attach or connect to the game.

I patched the DLL by:
- Using Mono branch `unity-2019.3-mbe`
- Using commit [`c7e0dc11a6bb9c4ccc3d6346feee14cd95c6d55e`](https://github.com/Unity-Technologies/mono/commit/c7e0dc11a6bb9c4ccc3d6346feee14cd95c6d55e), two days after the DLL's build timestamp
- Compiling `dnSpy-Unity-mono-v2019.x-V40.sln` with VS2017 build tools running on VS2019

I tried debugging `libmono-dynamic` in VS by launching the game executable, but the game throws a Steam Application Error `0000065432`.

I also tried turning my copy of the game into a debug build, following the README in `dnSpy-Unity-mono` and replacing files from Unity editor, but the new executable exits immediately upon launch. Is there a correct way to debug the Mono DLL?

**Comment by KissMyLady** [comment]
May I ask, what is the game name ?

**Comment by xyx0826** [comment]
It is [Hardspace: Shipbreaker](https://steamdb.info/app/1161580/).

I'm able to debug build the DLL, and launch the game process through x64dbg. Still no luck with Visual Studio.

**Comment by xyx0826** [comment]
Never mind, it turns out the debug version of DLL works with dnSpy, while the release build will not. Closing this issue.
