### ISSUE TITLE
Writing an deobfuscation extension

### ISSUE THREAD

**Issue by SWW13** [0xd4d/dnSpy#1498]
I'm trying to write a deobfuscation extension which boils down to renaming methods/fields/properties/etc.

I can't find any Event/Action I could send to trigger a rename, so I tried to implement this based on other extensions.
I looked into the `dnSpy.Analyzer` extension on how to get references to the `TypeDef`/`MethodDef`/etc from context menu entry, this works and I can rename those: https://github.com/0xd4d/dnSpy/blob/8ed4e4c8790003c9e6613b77f78a2e28c47f1938/Extensions/dnSpy.Analyzer/TreeNodes/Commands.cs#L186-L195
Looking into `FieldDefCommands` in `dnSpy.AsmEditor` showed how to get a reference to the node and trigger a UI refresh, except it only refreshes the Assembly Explorer and not the decompiler output.
For the `FieldDefCommands` later seems to happen kind of magically trough the `IUndoCommand` interface (at least that's my guess), besides the need to update the decompiler output I'd also like to use the undo functionally - which isn't available for other extensions as far as I can tell.

The field rename looks for references and renames them also, but the `RefFinder` it uses is private and can't be reused:
```cs
if (nameChanged)
	memberRefInfos = RefFinder.FindMemberRefsToThisModule(fieldNode.GetModule()!).Where(a => RefFinder.Equals(a, fieldNode.FieldDef)).Select(a => new MemberRefInfo(a)).ToArray();
[...]
foreach (var info in memberRefInfos)
	info.MemberRef.Name = fieldNode.FieldDef.Name;
```
I'd guess this would also be needed for the other renames like methods, but I struggle to understand why.

Functionality like "Used by" from the Analyzer extension aren't accessible, at least not without patching the visibility of some classes and properties. This may work, but it's more than ugly.

Am I missing something or is the extension API not design for interacting with other extensions / components?
Currently the only solution I see is either continue on patching code (which defeats the purpose of extensions) or rewrite all the functionality I need in which case I can just write a standalone deobfuscator.

**Comment by 0xd4d** [comment]
Only the `AsmEditor` extension can rename stuff. You can try doing what it does, including `undo`.
