### ISSUE TITLE
Predefined type is not defined or imported

### ISSUE THREAD

**Issue by amshegarh** [0xd4d/dnSpy#1499]
Tried to recompile part of a method in a game (it doesn't use unity btw), but it fails with said error, types are pretty much generic .NET types such as System.Boolean, System.Int32 etc

![image](https://user-images.githubusercontent.com/11033958/86283508-e27f7780-bbe9-11ea-8b38-6cdfd7d1c98d.png)

This error is also worth mentioning

![image](https://user-images.githubusercontent.com/11033958/86283784-4c981c80-bbea-11ea-835b-a193f3c530a6.png)

as well as these, seemingly related to this problem of types

![image](https://user-images.githubusercontent.com/11033958/86283831-65a0cd80-bbea-11ea-8ad4-d7e832031bf9.png)

im using dnSpy v6.1.5 (.NET Core), literally downloaded it a few hours ago

**Comment by KissMyLady** [comment]
Mabley you cloudy use `Edit IL Instructions` command, this is in `right mouse click` then `menu`

**Comment by amshegarh** [comment]
It indeed works (it even runs after compiling and saving, tho effects of my edits will be hard to trace due to their nature)
unfortunate that i cant edit in c# and have to edit IL which is a mess
is there any way to make it work? i can provide any data you may need

**Comment by 0xd4d** [comment]
Make sure it can find all required DLL files. The easiest way is to make sure all required files are in the same directory as the file you're editing.

**Comment by amshegarh** [comment]
It has all dlls in the same folder

**Comment by seansaleh** [comment]
I had roughly the same issue and was able to solve it by clearing out all assemblies from the assembly explorer and reloading the .dll I wanted to change.

**Comment by amshegarh** [comment]
It helped (sort of)
Now it generates (not always, but most classes) various errors that i miss a namespace or something along the lines
I tried adding dll that should be responsible for functionality but it doesnt seem to work (Ctrl+O Add assembly during editing of source code)

**Comment by 0xd4d** [comment]
It could be encrypted so you'd have to decrypt it to view the .NET metadata.
