### ISSUE TITLE
Small problem with camelCase conversion

### ISSUE THREAD

**Issue by catester** [0xd4d/dnSpy#15]
Not so important but it may cause problems in the future, if you run dnSpy on a machine with Turkish locale, auto-generated property names which start with big I letter can be converted wrongly to ı (not i, in Turkish there is also the small i letter without dot). I guess you are using ToLower() somewhere, instead you should use ToLowerInvariant().
![dnspy-string-lowercase](https://cloud.githubusercontent.com/assets/3868141/9022549/e2ca415c-3881-11e5-96d8-3914f9ba9042.png)

**Comment by 0xd4d** [comment]
I've added char.ToLowerInvariant(). Let me know if it fixes your problem since I can't reproduce it on my machine.

**Comment by catester** [comment]
Perfect, it's fixed. Thanks.
