### ISSUE TITLE
Changing an Assembly-CSharp.dll to use .NET Framework 4 or later

### ISSUE THREAD

**Issue by edgitacc** [0xd4d/dnSpy#1500]
I loaded an Assembly-CSharp.dll that uses .NET Framework 3.5
I wanna use System.Threading.Tasks in my code but its says 
The type or namespace name 'Tasks' does not exist in the namespace 'System.Threading'
It happens Because this library is only exist in .NET Framework 4 or later versions. 
Is there anyway to change an Assembly-CSharp.dll so it use new .Net Frameworks?

**Comment by UlyssesWu** [comment]
Impossible, because unity games use embedded mono (in your case, it's .NET 3.5 equivalent) rather than .NET in your system.
