### ISSUE TITLE
breakpoint on depended dll not be hit!

### ISSUE THREAD

**Issue by moha19** [0xd4d/dnSpy#1501]
hello, 
I have an exe file with some depended dlls. i want to debug one of dlls. when i add the breakpoint within a dll to debugging, it doesn't hit into dll breakpoint!

**Comment by 0xd4d** [comment]
What's the error message?

**Comment by moha19** [comment]
it's doesn't show any message. it's just never hit within related dll.

**Comment by 0xd4d** [comment]
If it can't set a breakpoint you'll see the BP icon change. Hover over it to see the error message.

**Comment by moha19** [comment]
I want to debug a dll. This dll is loaded by running an exe program. When I add a breakpoint to the dll and run the exe program, it never stops on that breakpoint in the dll. what is the reason?
dnspy version: 6.1.5

**Comment by 0xd4d** [comment]
See my previous reply, did you not see it? https://github.com/0xd4d/dnSpy/issues/1501#issuecomment-653940046

**Comment by moha19** [comment]
it can set(add)  breakpoint inside the code line, but pointer never stops on that breakpoint. by the way, the breakpoint icon doesn't change!!!
I'm confused!  do u have any idea?

**Comment by 0xd4d** [comment]
Check the BP icon when the program has started. It's always a red circle when you're not debugging anything.

**Comment by moha19** [comment]
hi again,
I have a question. Why the pointer doesn't stop on BP what is set within a dll, related to running the exe file?
Do I apply it incorrect?

**Comment by 0xd4d** [comment]
I still don't see any answer to my question, eg. what's the error message, is the BP icon red?

**Comment by 0xd4d** [comment]
Show a pic of it, and any error message and add repro steps.
