### ISSUE TITLE
Compile issues in DnSpy v6.1.5

### ISSUE THREAD

**Issue by Userrr123** [0xd4d/dnSpy#1505]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?

- Write down all steps needed to reproduce this issue. Also attach any needed files.

**Comment by Userrr123** [comment]
By trying to create a "mod menu" for the game (WildAnimalsOnline), I always get to see issues, no matter what i try and change.
Are there any patches for compile eroors in DnSpy v6.1.5?

**Comment by 0xd4d** [comment]
You just have to fix them yourself. Edit one method instead of the whole class. IF you get errors in main.g.cs, try deleting the lines with errors.
