### ISSUE TITLE
Where can the previous version 6.1.4 be downloaded?

### ISSUE THREAD

**Issue by jwfx** [0xd4d/dnSpy#1506]
Is there a reason why all the tags and releases are always cleaned out for every new release?

I would like to download the previous version 6.1.4, because the current version is still detected as false positive by Trendmicro. Yes, we have already reported this to them, but the result it still pending..

In particular, I am looking for the dnSpy-netcore-win64.zip release of 6.1.4.

**Comment by 0xd4d** [comment]
It's already been explained before, search the issues.

You can get older downloads by checking the `Actions` tab.

**Comment by jwfx** [comment]
This feels like an odd practice to delete old versions just so links get invalidated and people are forced to download the latest version.

I'd rather make a big fat note in the bug report template for people to retry with the latest version before complaining about anything.

Also with deleting tags, the Actions tab becomes useless, because one cannot find the exact build of the previous release either...

Anyways, thanks for your time.

**Comment by 0xd4d** [comment]
Just search for 'Bump version' and you'll find the commit.
