### ISSUE TITLE
Can´t find anything under releases!

### ISSUE THREAD

**Issue by Userrr123** [0xd4d/dnSpy#1508]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?

- Write down all steps needed to reproduce this issue. Also attach any needed files.

**Comment by Userrr123** [comment]
Can´t find anything under releases!

**Comment by BryantSmithcom** [comment]
Same, nothing under releases at all.

**Comment by 0xThxmxs** [comment]
Same.
![Releases](https://user-images.githubusercontent.com/62804686/86614045-b3cf1b80-bfb2-11ea-9424-0d888efde94d.png)

**Comment by Jacellen** [comment]
fix release please!

**Comment by Jacellen** [comment]
You can get the latest release here.

https://github.com/0xd4d/dnSpy/actions/runs/145498282

**Comment by plokmijnuhby** [comment]
My antivirus said it had a trojan in it. Can someone double check?

**Comment by 0xd4d** [comment]
I've removed the releases because of false positives from antivirus software. See https://github.com/0xd4d/dnSpy/issues/1493

Since I don't know how to get in contact with these companies, there'll probably be no more binary releases.

**Comment by JPicko** [comment]
Please re-post the release, and just put the notice of false positives, at least we can help to notify the antivirus companies.

**Comment by 0xd4d** [comment]
The CI has all builds including that release (should be last build). https://github.com/0xd4d/dnSpy/actions

**Comment by 0xd4d** [comment]
BTW, a few years ago Kaspersky had a false positive. I reported it several times, nothing changed. The only thing they listen to is letters from lawyers.

**Comment by fredimachado** [comment]
Thanks @0xd4d! Is there a pipeline or actions with binaries for the mono.dll with debugging support for Unity?

**Comment by xprzemekw** [comment]
Unfortunately AV software marks this as *potentially* unwanted software because of some heuristics. It is because it is debugger and can be used to alter binaries. However since nowadays AV software is targeted for dumb users they block it by default instead of warn users and ask them. Today Windows Defender started complaining about my deployment of dnSpy.  Had to explicitly add exclusion :/

What helps to get better scoring is getting dll and exe files digitally signed using commercial certificate :/ Then AV knows some real entity is behind given software package.

**Comment by epikgit** [comment]
@0xd4d I can understand your regret but, really, when this happens to a legit software you can put a simple disclaimer on the main page explaining the problem with the dumb AVs and the users are no more allowed to complain.
Removing the program releases instead, cut out a great part of your users. It's like shooting on your own feet.

**Comment by helldragger** [comment]
@0xd4d The  link you gave (https://github.com/0xd4d/dnSpy/actions) do not seem to include mono binaries for unity debugging, specifically, those cited on the wiki: https://github.com/0xd4d/dnSpy/wiki/Debugging-Unity-Games . Is there a way to get a binary for it?
Also removing releases for something a simple disclaimer would have sufficed for is clearly overreacting.

**Comment by kgwood39** [comment]
Oh jeeze, please put it back with a disclaimer about the AV idiocy.  This is such an amazing tool!

**Comment by dss539** [comment]
This also breaks installation via chocolatey
_Please_ restore the binaries under releases.

Don't let stupid AV ruin a good thing. We can fight it together!

**Comment by liesauer** [comment]
> I've removed the releases because of false positives from antivirus software. See #1493
> 
> Since I don't know how to get in contact with these companies, there'll probably be no more binary releases.

there are no relevances between AV software and prebuild releases at all. just let users judge and make the decision. deleting everything just make it more like trying to hide "something".

**Comment by epikgit** [comment]
> there are no relevances between AV software and prebuild releases at all. just let users judge and make the decision. deleting everything just make it more like trying to hide "something".
Hide what? The code is still there.

**Comment by liesauer** [comment]
> > there are no relevances between AV software and prebuild releases at all. just let users judge and make the decision. deleting everything just make it more like trying to hide "something".
> 
> Hide what? The code is still there.

i don't mean really hiding something. i just want to say deleting every is definitely the wronnnng way. you did nothing wrong, why deleting then?

**Comment by 0xd4d** [comment]
The binaries are still there, check the Actions tab.

Seems like MS Defender has been fixed according to https://github.com/0xd4d/dnSpy/issues/1493#issuecomment-656421137 but I haven't checked myself.

**Comment by dss539** [comment]
> i don't mean really hiding something. i just want to say deleting every is definitely the wronnnng way. you did nothing wrong, **why deleting then**?

@liesauer The "why" is to avoid hassle. It sounds like the false positives were leading to too many issue reports. Avoiding those headaches and time sinks really make a lot of sense.  
  
However, I agree with you. I'd like to have the releases again... We can fight the AV together. :)

**Comment by 0xd4d** [comment]
The latest build is the latest release. Just use the `Actions` tab: https://github.com/0xd4d/dnSpy/actions

**Comment by kmahyyg** [comment]
You need to give a notice before you do this action and try to tell users why you do that. A lot of people and package manager use releases to track software update and download binaries for users. Since you did this, user hurt.
