### ISSUE TITLE
can't open dnSpy-x86.exe ,thrown System.BadImageFormatException HRESULT:0x8007000B

### ISSUE THREAD

**Issue by afowne** [0xd4d/dnSpy#1509]
my op system is windows7 x64.
i guess that there's some net framework x86 dll loaded wrong ,
 but i can't locate which one is,
hope some one can help me to fix  it or give me some methods to solve it.
ths very much~~~

System.BadlmageFormatException:试图加载格式不正确的程序(
异常来自 HRESULT:Ox8007000B)

dnSpy.Contracts.Controls.MetroWindow.GetDpiForMonitor(IntPtr
hmonitor, Int32 dpiType, Int32& dpiX, Int32& dpiY)
在 dnSpy.Contracts.Controls.MetroWindow.GetDpi_Win81(IntPtr
hWnd)
C:\projects\dnspy\dnSpy\dnSpy.Contracts.DnSpy\Controls\Metro
Window.cs:行号 99
在 dnSpy.Contracts.Controls.MetroWindow.GetDpi(IntPtr hWnd)

C:\projects\dnspy\dnSpy\dnSpy.Contracts.DnSpy\Controls\Metro
Window.cs:行号 82

dnSpy.Contracts.Controls.MetroWindow.OnSourceInitialized(Even
tArgs e)
C:\projects\dnspy\dnSpy\dnSpy.Contracts.DnSpy\Controls\Metro
Window.cs:行号 71
S System.Windows.Window.CreateSourceWindow(Boolean
duringShow)

System.Windows.Window.CreateSourceWindowDuringShowO
S System.Windows.Window.SafeCreateWindowDuringShowO
S System.Windows.Window.ShowHelper(Object booleanBox)
在 System.Windows.Window.Show〇
在 dnSpy.MainApp.App.OnStartup(StartupEventArgs e)
C:\projects\dnspy\dnSpy\dnSpy\MainApp\App.xaml.cs:行号 531
S System.Windows.Application.<.ctor>b_l_0(Object unused)
汪
System.WindoW5.Threading.ExceptionWrapper.InternalRealCall(D
elegate callback. Object args, Int32 numArgs)
汪
System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Ob
ject source, Oelegate callback. Object args, Int32 numArgs,
Oelegate catchHandler)

**Comment by 0xd4d** [comment]
Try the 32-bit version or the 64-bit version, whichever you didn't try and see if that helps.
