### ISSUE TITLE
Can't find Unity-debugging files on releases

### ISSUE THREAD

**Issue by BUTTERSKY11** [0xd4d/dnSpy#1510]
I need the files to be able to debug Rimworld
I need Unity-debugging-2019.x.zip

Also the wiki Still says I can find these files on releases, but you have hidden them

**Comment by ComputeShader** [comment]
Same problem

**Comment by ComputeShader** [comment]
Only dnSpy itselfs is on Actions

**Comment by 0xd4d** [comment]
You can compile it yourself: https://github.com/0xd4d/dnSpy-Unity-mono

**Comment by ComputeShader** [comment]
Yes but it would be nice if there is a precompiled version, because its huge and c++ compilation is ....

**Comment by Kriper1111** [comment]
> and c++ compilation is ....
a horrible summer activity. especially if done without the Studio.

having precompiled binaries is just more convenient. for users, at least.

**Comment by ComputeShader** [comment]
Here is the issue for precompiled mono builds: https://github.com/0xd4d/dnSpy/issues/1513
