### ISSUE TITLE
Please upload precompiled mono builds

### ISSUE THREAD

**Issue by ComputeShader** [0xd4d/dnSpy#1513]
I know because false antivirus positives you have removed the release tag.

But it would be nice to add the 3 precompiled mono build, because I have no clue about c++ and how to build a version from https://github.com/0xd4d/dnSpy-Unity-mono.

Yes I have read the instruction, but it just does not work and I have to install thousands of tools which I never need again.

**Comment by Kriper1111** [comment]
If you're fine with downloading off someone's Google Drive and trusing internet people with "worked for me" claims, you can get.. At least Unity 2019 libraries from [here](https://drive.google.com/drive/folders/1ZmqZsPdnBdI-2WVfOsboIG-TIr1-QUlO?usp=sharing). If you're not.. Well then, you either wait for the dev or figure out the compilation.

Yes they did work for me, I compiled them myself.

**Comment by ComputeShader** [comment]
Your profile picture looks ominous. So I don't know if I can trust you :)
Unfortunately I need x32 assemblies(2018) of mono.dll not mono-2.0-bdwgc.dll. But thanks a lot for uploading.

**Comment by Kriper1111** [comment]
>Your profile picture looks ominous.

Sorry if it looked uncanny to you, I drew it myself.

Anyways, compiling the libraries with VS requires only about half an hour and lots of sedatives. Shouldn't be that hard. But let's just wait for the dev, he could upload the libraries himself soon.

**Comment by BUTTERSKY11** [comment]
Compiling stuff causes me pain

**Comment by ComputeShader** [comment]
Yes especially if you are compiling c++. You need to download a ton of things to compile and 90% of the 5-hour compilation are waste because it exits with a wired error.

**Comment by BUTTERSKY11** [comment]
> Yes especially if you are compiling c++. You need to download a ton of things to compile and 90% of the 5-hour compilation are waste because it exits with a wired error.

EXACTLY

**Comment by liesauer** [comment]
i have uploaded the 2017.x dlls that was downloaded a few months ago. but unfortunately i don't have 2018.x dlls and i also need it too...
[check this out](https://github.com/liesauer/Unity-debugging-dlls/releases)

**Comment by liesauer** [comment]
if someone have others version's dlls, please contact me.

**Comment by Kriper1111** [comment]
> if someone have others version's dlls, please contact me.

I have self-compiled libraries for Unity 2018 and 2019 (x64, mbe). I allow you to go and transfer them over to your GitHub repo. You can find them in the Google Drive link somewhere above in this thread.

**Comment by liesauer** [comment]
> > if someone have others version's dlls, please contact me.
> 
> I have self-compiled libraries for Unity 2018 and 2019 (x64, mbe). I allow you to go and transfer them over to your GitHub repo. You can find them in the Google Drive link somewhere above in this thread.

thanks! already uploaded.

**Comment by 0xd4d** [comment]
https://github.com/0xd4d/dnSpy/releases/tag/unity

**Comment by liesauer** [comment]
> https://github.com/0xd4d/dnSpy/releases/tag/unity

thanks! i am glad that reupload unity debugging dlls again!
