### ISSUE TITLE
Please dev!

### ISSUE THREAD

**Issue by taylortek** [0xd4d/dnSpy#1514]
Please dev Im begging you I lost dnspy during a reset, and all I want is to get it back, please bring it back, thx

**Comment by Kriper1111** [comment]
You can get the tool itself from the "Artifacts" tab on here https://github.com/0xd4d/dnSpy/actions/runs/161798211
Unity libraries would require manual compilation, that requires Visual Studio and a couple of clicks. ~~Really painless~~
