### ISSUE TITLE
The type exists in both assemblies

### ISSUE THREAD

**Issue by Toshiba1127** [0xd4d/dnSpy#1516]
- What version did you use? 6.1.5.0

- Write down all steps needed to reproduce this issue. Also attach any needed files.
I try to modify a method in XMainClient.dll but i see the red, clicking on compile shows me an error
What should i do in this case? I looked for solution but they are for Visual Studio only

`Error	CS0433	The type 'WrappersManagerImpl' exists in both 'XMainClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'XUtliPoolLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'	main.cs	16`

[Managed.zip](https://github.com/0xd4d/dnSpy/files/4908368/Managed.zip)

![image](https://user-images.githubusercontent.com/64008639/87244684-3dfa0280-c43f-11ea-8e35-d2a67e2bceb7.png)

**Comment by 0xd4d** [comment]
There are two classes in two different assemblies with the same name. Rename one, save the file, reload everything.

**Comment by Toshiba1127** [comment]
Good idea, I renamed it from other .dll and it solved the problem
