### ISSUE TITLE
DnSpy debugging Unity editor has an exception

### ISSUE THREAD

**Issue by crazyshader** [0xd4d/dnSpy#1517]
Unity crashed while I was debugging the Unity 2018.4.23f1 editor with.NET 3.5.Unity log as follows:
========== OUTPUTTING STACK TRACE ==================

0x00007FFB0034A799 (KERNELBASE) RaiseException
0x00007FFAA5D61158 (mono) [c:\buildslave\mono\build\eglib\src\goutput.c:201] g_logv 
0x00007FFAA5D6117C (mono) [c:\buildslave\mono\build\eglib\src\goutput.c:211] g_log 
0x00007FFAA5E31D4E (mono) [c:\buildslave\mono\build\mono\mini\debugger-agent.c:6808] thread_commands 
0x00007FFAA5E36597 (mono) [c:\buildslave\mono\build\mono\mini\debugger-agent.c:7582] debugger_thread 
0x00007FFAA5EBA1AB (mono) [c:\buildslave\mono\build\libgc\win32_threads.c:585] thread_start 
0x00007FFB01977BD4 (KERNEL32) BaseThreadInitThunk
0x00007FFB02FECE51 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

Unity crashed while I was debugging the Unity  2018.4.23f1 editor with.NET 4.x,can't debug at all,Unity log as follows:

========== OUTPUTTING STACK TRACE ==================

0x00007FFA89DF2C16 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\class.c:5918] mono_generic_class_get_class 
0x00007FFA89FBBBEB (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\mini\mini-generic-sharing.c:3588] get_shared_inst 
0x00007FFA89FBF03F (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\mini\mini-generic-sharing.c:3673] mini_get_shared_method_full 
0x00007FFA89EE0391 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\mini\seq-points.c:261] mono_get_seq_points 
0x00007FFA89EE02C5 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\mini\seq-points.c:310] mono_find_prev_seq_point_for_native_offset 
0x00007FFA89FDE071 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\mini\debugger-agent.c:3294] process_frame 
0x00007FFA89FB3726 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\mini\mini-exceptions.c:1226] mono_walk_stack_full 
0x00007FFA89FB39BA (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\mini\mini-exceptions.c:1109] mono_walk_stack_with_state 
0x00007FFA89FD275C (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\mini\debugger-agent.c:3463] compute_frame_info 
0x00007FFA89FE2BA4 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\mini\debugger-agent.c:10922] thread_commands 
0x00007FFA89FD397B (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\mini\debugger-agent.c:12090] debugger_thread 
0x00007FFA89E84CA8 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\threads.c:1034] start_wrapper_internal 
0x00007FFA89E84A36 (mono-2.0-bdwgc) [c:\build\output\unity-technologies\mono\mono\metadata\threads.c:1093] start_wrapper 
0x00007FFB01977BD4 (KERNEL32) BaseThreadInitThunk
0x00007FFB02FECE51 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

Anyone help me?

**Comment by 0xd4d** [comment]
Re-install it? See the wiki on how to debug unity games.

I'll close this since this crash isn't in dnSpy.
