### ISSUE TITLE
I can't find the right mono.dll for a game I wanna debug in unity 

### ISSUE THREAD

**Issue by Jornker** [0xd4d/dnSpy#1518]
[wrongmono](https://user-images.githubusercontent.com/67780148/87343745-57707c80-c51b-11ea-9316-eac36f48a3ed.PNG)
I'm using the right mono file as far as I'm aware, but I keep getting a message whenever I start the game that says failed to load mono I'm 99% sure its a 32-bit game and I've tried the 64-bit mono as well

Please if you can help at all please do so

**Comment by 0xd4d** [comment]
Try compiling the correct version yourself, see https://github.com/dnSpy/dnSpy-Unity-mono . If it hasn't been added, see the README.
