### ISSUE TITLE
Where are the releases? Cant find the anywhere.

### ISSUE THREAD

**Issue by dhucul** [0xd4d/dnSpy#1520]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?

- Write down all steps needed to reproduce this issue. Also attach any needed files.

**Comment by 0xd4d** [comment]
See the README or search the issues.
