### ISSUE TITLE
Debugging Game with 2019.1.15 won't work. 

### ISSUE THREAD

**Issue by Dastano** [0xd4d/dnSpy#1521]
- What version did you use?
Latest from Github ( 4 days ago on point of writing?)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
I was able to debug the Game fine with DNSpy, as long as it used 2019.1.14 while using the 2019.1.8 DLL, but with the recent update, it got updated to 15.1.2019 if I start the Game now with the Mono File, it just return's it can't load the Mono-File anymore.

So I guess there was some bigger change going from 2019.1.14 to .15

Will you guys release Debugger Files for .15?

**Comment by 0xd4d** [comment]
See https://github.com/dnSpy/dnSpy-Unity-mono . The README explains how to compile your own file with the version number you need.
