### ISSUE TITLE
How to get binaries?

### ISSUE THREAD

**Issue by jfrank14** [0xd4d/dnSpy#1527]
I'm trying to use dnSpy but everything I try to get it installed fails. I downloaded the full project but powershell build failed. I opened the solution in VS2019, but projects are missing so the build fails. The install on Chocolatey fails. The binaries here on github have been removed. I'm sure I'm missing something about getting this thing installed, but I can't figure out what it is. Can anyone point me in the right direction?

**Comment by 0xd4d** [comment]
The README explains how to clone the repo so all sub modules are included.

It also explains how to get binaries (hint: `Actions` tab).

**Comment by PiBa-NL** [comment]
Is it possible to download these github artefacts without authenticating to github?
For example this one: https://github.com/0xd4d/dnSpy/actions/runs/164661515 shows the 3 artefact in gray, but doesn't allow to download them. (from my company workstation where i don't have my private github credentials remembered/cached/available..) (Same effect in a incognito browser.)

This while the https://github.com/0xd4d/dnSpy/releases does allow to download the Unity libraries. Can dnSpy binaries themselves perhaps be tagged/released the same way?
