### ISSUE TITLE
Add commandline flag to include extension directories

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [0xd4d/dnSpy#1528]
Adding a cli option to search a specific folder for extensions helps with their development, since they won't have to be manually copied.

**Comment by 0xd4d** [comment]
Sounds like a good idea. Would you like to send a PR? These files need to be updated:

- `IAppCommandLineArgs.cs.cs` (add a list of strings of dirs)
- `AppCommandLineArgs.cs` (implement the new API)
- `App.xaml.cs` (see `LoadExtensionAssemblies()` and `GetExtensionFiles()`)

**Comment by HoLLy-HaCKeR** [comment]
Will get on it
