### ISSUE TITLE
Doc suggestion: relationship to other debuggers

### ISSUE THREAD

**Issue by jazzdelightsme** [0xd4d/dnSpy#1529]
How does this debugger work? I see it looks like it uses the win32 `DebugActiveProcess` function, but not `WaitForDebugEvent`--how does that work? Does this debugger use any other win32 debugging APIs? Does this debugger primarily rely on debugging support libraries from the various .NET flavors it targets? Can it generate dump files, or load dump files? (such as from windbg/taskmanager)

I'm just trying to understand where this project fits in the world of debuggers, and having a hard time placing it. A few sentences in the ReadMe.md explaining what basic technology is used at least would be helpful. As would a brief compare/contrast with e.g. WinDbg and Visual Studio.

Thanks!

**Comment by 0xd4d** [comment]
It uses the ICorDebug APIs to debug .NET Framework and .NET Core apps and Mono's `Mono.Debugger.Soft` assembly to debug mono/unity assemblies. No Win32 debugging APIs are used although there are options to patch some of them to prevent detection of the debugger. Roslyn's expression evaluator is used to evaluate expressions in the watch window. It's also used by the locals window.

It doesn't support dump file debugging but the ICorDebug API supports it (AFAIK), there should be another issue about this already.

> A few sentences in the ReadMe.md explaining what basic technology is used at least would be helpful.

It's probably too technical for most people, but if you want to add something to the README, I will accept a PR.
