### ISSUE TITLE
DnSpy X86 .Net Core and full .NET Framework version doesn't work

### ISSUE THREAD

**Issue by PiotrKFtw** [0xd4d/dnSpy#1534]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?

- Write down all steps needed to reproduce this issue. Also attach any needed files.

I used latest.

How to reproduce?
Just download, extract and open, nothing will happen it will just close itself so fast that it might not even appear in task manager.
Only x64 .net core version work fine but i need x86 for debugging purposes..

**Comment by 0xd4d** [comment]
Do you have some buggy antivirus installed? If it's your antivirus, report it to them.

**Comment by PiotrKFtw** [comment]
> Do you have some buggy antivirus installed? If it's your antivirus, report it to them.

No i don't have, i even have windows defender disabled because it was messing with my software.

**Comment by 0xd4d** [comment]
If it's Win7, make sure you've installed all required Windows updates, etc. See the release notes.

**Comment by PiotrKFtw** [comment]
> If it's Win7, make sure you've installed all required Windows updates, etc. See the release notes.

It's Win 10

**Comment by 0xd4d** [comment]
It's possible that something is written to the console. You can change it to a 'CUI' app by changing `Subsystem` from `WindowsGui` to `WindowsCui`. You can use dnSpy: Assembly Explorer -> dnSpy.exe -> PE -> Optional Header (32/64-bit) -> Subsystem. Save it, then start it from cmd/wt.exe

**Comment by PiotrKFtw** [comment]
> It's possible that something is written to the console. You can change it to a 'CUI' app by changing `Subsystem` from `WindowsGui` to `WindowsCui`. You can use dnSpy: Assembly Explorer -> dnSpy.exe -> PE -> Optional Header (32/64-bit) -> Subsystem. Save it, then start it from cmd/wt.exe

The hell?
![image](https://user-images.githubusercontent.com/33489788/88449390-ded8bc80-ce46-11ea-9a3f-5e05e9283214.png)

**Comment by 0xd4d** [comment]
Check if the file is still there. Some buggy antivirus software can remove files.

**Comment by PiotrKFtw** [comment]
> Check if the file is still there. Some buggy antivirus software can remove files.

No it's not there, anti-virus didn't remove either because it's off (win defender).

**Comment by 0xd4d** [comment]
Re-download the zip file and extract again. If the file is still missing after extraction, you have some process that deletes your files.

**Comment by PiotrKFtw** [comment]
> Re-download the zip file and extract again. If the file is still missing after extraction, you have some process that deletes your files.

Re-download worked, previously downloaded zip files didn't contain the dnSpy.dll. I guess you repaired the downloads.

**Comment by 0xd4d** [comment]
> Re-download worked, previously downloaded zip files didn't contain the dnSpy.dll. I guess you repaired the downloads.

The .NET Framework build doesn't have a `dnSpy.dll` because it's called `dnSpy.exe` instead.
