### ISSUE TITLE
Code doesn't get added

### ISSUE THREAD

**Issue by nagomo17** [0xd4d/dnSpy#1536]
Issue: I tried to add a new class with dnspy to an assembly. However, some code doesn't even get added after I click "Compile".
For example, I add "using UnityEngine;", I click compile. The code edit window closes as if everything is alright, but then that line isn't even added. I have no idea what the cause of that is. No errors.
I try to edit the class again, adding "using UnityEngine;" again and click compile, but still nothing. Just using System; only there. And other code doesn't get added either, that's so frustrating as it was working before.

- What version did you use?
Tried latest version first, then also tried an older version.

- Write down all steps needed to reproduce this issue. Also attach any needed files.
Trying an older version and running as administrator.
![issue1](https://user-images.githubusercontent.com/34663826/88670079-ee753100-d0e4-11ea-8002-41aecbd3d041.PNG)
![issue2](https://user-images.githubusercontent.com/34663826/88670083-ef0dc780-d0e4-11ea-873a-fd8d7fa57ae0.PNG)

**Comment by 0xd4d** [comment]
The source code isn't saved, just the compiled IL code. And that IL code doesn't have any using statements. Add something that uses the namespace and you'll see that using statement in the decompiled code.
