### ISSUE TITLE
Add menu command to open all dlls in a hierarchy of folders

### ISSUE THREAD

**Issue by pardeike** [0xd4d/dnSpy#1546]
I commonly need to mass search through a lot of dll's for references to something. That works fine if the dlls are already added to dnSpy but opening 40 folders with each dlls in subfolders is cumbersome. A "Open all in Folder(s)" menu would really help.

**Comment by 0xd4d** [comment]
Dragging and dropping a directory to Assembly Explorer should work. Did you try that?

**Comment by pardeike** [comment]
I tried to open it via the menu and that did not work. Will get back to you.

**Comment by 0xd4d** [comment]
I assume it worked for you, so closing this.

**Comment by pardeike** [comment]
Sorry for the late response. Yes, works great.
