### ISSUE TITLE
[Question] How to get all references to the current function in my own plugin

### ISSUE THREAD

**Issue by Nemirtingas** [0xd4d/dnSpy#1547]
Hi, this is more of a HowTo than an issue.
1. Is there a place where people talk about dnSpy ? 
2. I'm trying to make my own plugin that will go through all the class methods and check if there is a reference to it. It there is no reference then I'll delete the method. I'd like to get all the references like the analyser does but I don't understand its code, any help would be appreciated.

**Comment by 0xd4d** [comment]
You don't need to write an extension, you can just use dnlib or mono.cecil.

**Comment by Nemirtingas** [comment]
Ok then. I'll take a look.
I'm trying to deobfuscate an old game. Its developpers has abandonned it and closed their servers. I'm trying to reverse it and build a private server.
