### ISSUE TITLE
Use order in a list of interfaces

### ISSUE THREAD

**Issue by helperman** [0xd4d/dnSpy#1548]
Could you please order a list of interfaces of a class?
For example, I have a class:
`public class MyClass : IMovable, IResizable, IGeneric`

When I export it into a project I get this one:
`public class MyClass : IResizable, IMovable, IGeneric`

And sometimes this one:
`public class MyClass : IGeneric, IResizable, IMovable`

What I suggest is always order them in the same order.
Why?
It's easier to compare changes in source files between two big assemblies when a list of interfaces matches.
What do you think about it?

**Comment by 0xd4d** [comment]
Did you check the decompiler options?
