### ISSUE TITLE
crash problem

### ISSUE THREAD

**Issue by shidolin** [0xd4d/dnSpy#1549]
Hello, im using everyday this program.
but today this program not opening?

program dont give me any error or message.

just auto closing.

im checking task manager and i see 1-2 sec  dnspy.exe and this is auto closing.

can you help me please.

**Comment by 0xd4d** [comment]
Re-download the zip file and try again, Could be the same as https://github.com/0xd4d/dnSpy/issues/1534

If you have a buggy antivirus software, report it to them.
