### ISSUE TITLE
Program:Win32/Uwasson.A!ml

### ISSUE THREAD

**Issue by wahmedswl** [0xd4d/dnSpy#1553]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?
dnSpy v6.1.6 (.NET Core)

- Write down all steps needed to reproduce this issue. Also attach any needed files.

Windows Defender has identified ```dnSpy-netcore-win64.zip``` as ```Program:Win32/Uwasson.A!ml```

![image](https://user-images.githubusercontent.com/15020561/90506038-16e4ce00-e16d-11ea-96ed-ac7d0338e422.png)

Thanks

**Comment by 0xd4d** [comment]
Report it to Microsoft. It's a false positive assuming you got it from the releases page or the Github Actions.
