### ISSUE TITLE
Compile error - how ignore them?

### ISSUE THREAD

**Issue by MateuszCOMP** [0xd4d/dnSpy#1555]
How ignore errors showing when try compile?
*.exe work fine with them so i dont want fix
When tried fix them (deleted "_") then *.exe get crashing
![errors](https://user-images.githubusercontent.com/70018410/90888982-80581d00-e3b7-11ea-83e2-3fcd19487594.png)

**Comment by MateuszCOMP** [comment]
What a gestapo app

**Comment by 0xd4d** [comment]
Answered already. ;)
