### ISSUE TITLE
Metadata Editor

### ISSUE THREAD

**Issue by saneki** [0xd4d/dnSpy#16]
A metadata editor/viewer would be nice, similar to what [dnExplorer] provides (although dnExplorer also lacks some features, such as displaying signatures in a friendly way).

[dnExplorer]:https://github.com/yck1509/dnExplorer

**Comment by 0xd4d** [comment]
I plan to add something similar to what CFF explorer shows.

**Comment by 0xd4d** [comment]
Latest build now has a simple editor. You can edit each everything, but requires knowledge of .NET MD.

**Comment by odinmillion** [comment]
@0xd4d Is it possible to edit MD from code? For example: change VersionString from "v4.0.30319" to "v2.0.50727". I looked at dnlib and found only low-level api. Maybe some a little bit more user-friendly possibilities exist?

**Comment by 0xd4d** [comment]
MD is low level so the API is too. You can get the offsets of the structs just like dnSpy does and then just overwrite the old value with the new value.
