### ISSUE TITLE
Remove all this space

### ISSUE THREAD

**Issue by CodeShark-Dev** [0xd4d/dnSpy#168]
http://image.prntscr.com/image/e02a2f4c53eb4b7f9009862536ab68e3.png

I think the picture says it all.

**Comment by 0xd4d** [comment]
There are only 5 lines so there's nothing that can be fixed.

**Comment by CodeShark-Dev** [comment]
That always happens.
http://image.prntscr.com/image/a051ff9eae3a4a51b6eac834c23c7c9b.png

**Comment by 0xd4d** [comment]
Being able to scroll so the last line is at the top is a feature. There are no plans to add an option to disable it.
