### ISSUE TITLE
CurrentHealth overflow

### ISSUE THREAD

**Issue by vsoderholm** [0xd4d/dnSpy#169]
This latest beta update is too damn awesome, my local biological processor can't handle this amount of awesome all-at-once. 👍 

Solution: Just let it run and process the new information and imagine all the possibilities for some time! In my case I guess at least a week.

**Comment by 0xd4d** [comment]
Thanks! :smile:

**Comment by SlowLogicBoy** [comment]
I imagine that soon enough dnSpy will be my primary IDE

**Comment by TiberiumPY** [comment]
Yep, me too.
