### ISSUE TITLE
Some types disappear when switching decompilation language

### ISSUE THREAD

**Issue by saneki** [0xd4d/dnSpy#17]
For some assemblies, certain types will disappear when switching the decompilation language (IL, C#, VB). It doesn't seem to be a decompilation/disassembly error, for example: If types disappear after switching from C# -> IL, re-opening the same assembly with IL already selected will display the types fine.

One example assembly that does this is [GenericExample3] from my personal dnlib examples repository. It also seems to happen commonly when analyzing obfuscated assemblies.

[GenericExample3]:https://github.com/saneki/dnlib-examples/blob/master/src/dnlib.MoreExamples/GenericExample3.cs

**Comment by 0xd4d** [comment]
Some types are compiler-generated types, eg. iterator types, and those aren't shown by default. Should be an option in the decompiler settings to show them.

**Comment by saneki** [comment]
I see, the "Show Internal Types and Members" option next to the language dropdown box toggles it. Still, it's misleading as even when it isn't enabled the internal types are visible until changing the language.

Is this enabled by default? I'm sure most people, after opening dnSpy for the first time, would assume they were being shown all types/members.
