### ISSUE TITLE
Nordic keyboard layout for '}' is borked in REPL

### ISSUE THREAD

**Issue by vsoderholm** [0xd4d/dnSpy#170]
Title says it all. 
Some vikings use Ctrl+Alt+0 for the brace, which does not insert a 'måsvinge', but instead shifts focus to the decompiled source code.. This is why they are so angry and strong, since coding work makes them move their arms all over the place in a berzerking fury without the desired amount of non-alphabetic characters of their envied english peers ending up in their documents.

![Swedish/Finnish keyboard](http://ascii-table.com/img/keyboard-153.png)

**Comment by 0xd4d** [comment]
This also happens in Visual Studio.

Right now it's not easy to fix without recompiling the source code, the code in question is [here](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy/Files/Tabs/Commands.cs#L207)

**Comment by vsoderholm** [comment]
Thanks, then I'll dirtypatch it for myself for now. 🍪

**Comment by 0xd4d** [comment]
Continued in  #243
