### ISSUE TITLE
Error while trying to edit C# code of Unity3D dll.

### ISSUE THREAD

**Issue by TiberiumPY** [0xd4d/dnSpy#174]
I had success editing Unity3D game dlls with Reflexil, but it does not have support for some delegates, and I need manually type almost all imports.
When I trying to press Compile button, there are many errors:
"Predefined type 'System.Boolean'" (or even int,string,object,void).
"The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.0.0"
By the way, Unity3d dll's almost perfectly decompiling by .NET Reflector and ILSpy(which is OpenSource too).
Can I fix that problem?

For some reason I can't attach ZIP file, so this is the link to dll's:

**Comment by 0xd4d** [comment]
Seems like Roslyn doesn't like it when there are two refs to different core libraries (mscorlib 2.0.0.0 and 2.0.5.0).

**Comment by TiberiumPY** [comment]
Can I bypass this?

**Comment by TiberiumPY** [comment]
By the way, editor have very good and clean design.. It feels like Visual Studio, how do you done this?

**Comment by 0xd4d** [comment]
See #173 for a hack to make it work by using `C# Interactive` from within dnSpy.

**Comment by 0xd4d** [comment]
Has been fixed, try latest beta build.

**Comment by TiberiumPY** [comment]
Build on AppVeyor failed

**Comment by 0xd4d** [comment]
Forgot to push the decompiler update. Wait a few seconds.

**Comment by TiberiumPY** [comment]
Successfully worked, thank you!

**Comment by hvann2000** [comment]
I am still having this issue. Do I need unity installed.
