### ISSUE TITLE
Edit code: Huge arrays are not complete.

### ISSUE THREAD

**Issue by SlowLogicBoy** [0xd4d/dnSpy#177]
![2016-08-26 14_26_25-server gudjonis lt_3214 - remote desktop connection](https://cloud.githubusercontent.com/assets/3121637/18003848/19ad33e6-6b99-11e6-875c-82a3f647c2e7.png)
Editor also shows:
![2016-08-26 14_27_13-server gudjonis lt_3214 - remote desktop connection](https://cloud.githubusercontent.com/assets/3121637/18003882/35a39c7a-6b99-11e6-99c4-e6d21c4c8596.png)

**Comment by 0xd4d** [comment]
Why would you even want to see the whole array? It's been cut off because of #87 . The command line decompiler has an option to show the whole thing if you really need it.

**Comment by 0xd4d** [comment]
The data is probably encrypted and you should just set a BP after the data has been decrypted then you can save it to disk.

**Comment by SlowLogicBoy** [comment]
Well the problem is that I can't compile it with Edit C#, the array is cut off. But I guess I can load that array from file to work around that.

**Comment by 0xd4d** [comment]
If you absolutely need to use the encrypted array, just set a BP somewhere in the method after it has loaded it to some local, then dump the local to disk from the locals window. You can then use File.ReadAllBytes() to read it from disk.

**Comment by SlowLogicBoy** [comment]
What I want to do is to get rid of that array and encryption cause I already have that decrypted array = file, but I also want to make as little changes as possible to the assembly.

**Comment by SlowLogicBoy** [comment]
Anyway now I need #165 to be fixed :)

**Comment by 0xd4d** [comment]
When you save an assembly, it will be completely rewritten, so if you want the least changes, you have to use your favorite hex editor.

**Comment by 0xd4d** [comment]
Closing this since this is a feature.
