### ISSUE TITLE
newobj opcode for generic types 

### ISSUE THREAD

**Issue by olcayseker** [0xd4d/dnSpy#179]
I am trying to instantiate DateTime? as follows from ILEditor window

`newobj  instance void valuetype [mscorlib]System.Nullable`1<valuetype [mscorlib]System.DateTime>::.ctor(!0)`

but i can only select type for ctor like  

`newobj	instance void [mscorlib]System.Nullable`1::.ctor<valuetype [mscorlib]System.DateTime>(!0)`

 from editor which causes error. Is it bug or i am doing someting wrong?

![operand](https://cloud.githubusercontent.com/assets/776387/18029003/9bbc22ba-6c94-11e6-9085-c37029c42258.PNG)

**Comment by olcayseker** [comment]
#70  issue has the answer. I should update the title more informative way.

**Comment by 0xd4d** [comment]
You can also use the latest beta version and just add C# or Visual Basic code.
