### ISSUE TITLE
Windows Defender positive

### ISSUE THREAD

**Issue by FrayxRulez** [0xd4d/dnSpy#186]
Windows Defender (on Windows 10 1607) identifies dnSpy-x86.exe as Trojan:Win32/Malture.C!cl

**Comment by SlowLogicBoy** [comment]
I don't have that problem. Also running Windows Defender on Windows 10. But I can see why it would detect as threat.

**Comment by TiberiumPY** [comment]
SlowLogicBoy - maybe you don't have Windows 10 1607 build?

**Comment by 0xd4d** [comment]
`dnSpy-x86.exe` literally contains [one line of code](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy-x86/Program.cs#L25). Don't know what I can do about the incompetence of certain anti-virus tools. dnSpy is not obfuscated at all, and yet, it flags a one-line assembly as a trojan?

**Comment by 0xd4d** [comment]
BTW, I scanned the latest build:

https://www.virustotal.com/en/file/a88b368b42d149891d4517797864f5889008bdfbc296590fb7011ada50fb3831/analysis/1472392682/

File: https://ci.appveyor.com/api/buildjobs/hkg9gheskkiphc86/artifacts/dnSpy%2FdnSpy%2Fbin%2FdnSpy.zip

Some anti-virus project called `TheHacker` thinks it's `Trojan/Agent.nre`

**Comment by 0xd4d** [comment]
I re-run the test again, this time without including the translation files (sub directories `de`, `pt-PT`, `ru`, and `zh-CN`, and got 0 / 54 detections (and 2 times outs): https://www.virustotal.com/en/file/bb1ce36dd1d968a2432f165d6b69e0b176774dbfd4187b082b454965f33dd918/analysis/1472393023/

Seems like these "professional" tools called `TheHacker` and `Windows Defender` don't like translated programs. Now which language have they decided is the virus-language?

**Comment by TiberiumPY** [comment]
I think it's "ru" :)

**Comment by TiberiumPY** [comment]
Just to clarify: I'm from Russia

**Comment by 0xd4d** [comment]
Closed, there's nothing I can do about anti-malware tools that flag string-only (no code) assemblies as malware.
