### ISSUE TITLE
Decompile assembly to a Visual Studio project

### ISSUE THREAD

**Issue by saneki** [0xd4d/dnSpy#19]
As far as I'm aware, currently only commercial/closed-source programs have this feature (Reflector, JustDecompile). Would be nice to have it.

**Comment by UlyssesWu** [comment]
In fact you can select a assembly and then choose "File"---"Save Code" to save it as a project. 
ILSpy (which dnSpy forked from) can also do it and it is free and open-source.

**Comment by 0xd4d** [comment]
Yes, this feature already exists. But you must first select the assembly / module in the treeview, otherwise it will only save the current window content (eg. a type or a method).

**Comment by tazotodua** [comment]
can you give a screenshot how to do that? I cant find that function.

**Comment by 0xd4d** [comment]
This is a 3 year old issue.

`File` -> `Export to Project`

**Comment by tazotodua** [comment]
ouh. shame on me.  sorry.

btw, excellent quick response , thanks!
