### ISSUE TITLE
Invoke method

### ISSUE THREAD

**Issue by CodeShark-Dev** [0xd4d/dnSpy#190]
Add an option for invoke a method with custom parameters and show the info in a console or something.
It would be pretty good.

![](http://image.prntscr.com/image/241ebe9dfaff4caa8f01d978c3ea3ad1.png)

**Comment by TiberiumPY** [comment]
Yes, that will be very useful.

**Comment by 0xd4d** [comment]
The `C# Interactive` window can already do this. The command could just slightly simplify the process, it would open the `C# Interactive` window and add the required reference(s). If it's a simple method, execute it. A simple method is defined as follows: non-generic declaring type; non-generic method; no params; static method or type with default constructor;

```C#
#r "c:\some\path\file.dll"
new Some.Type().SomeMethod()
```

or if it has params, the user has to add those and press enter

```C#
#r "c:\some\path\file.dll"
new Some.Type().SomeMethod(
```

**Comment by SlowLogicBoy** [comment]
`#r "c:\some\path\file.dll"`

Would be awesome if this would show if C# Interactive would be active and I ctrl + MouseClick an assembly/Module

**Comment by CodeShark-Dev** [comment]
A quick button would be pretty good, if is possible.
