### ISSUE TITLE
Cannot open Code window after close 

### ISSUE THREAD

**Issue by RustanovTimur** [0xd4d/dnSpy#192]
Hello, please look image. Regards
![1](https://cloud.githubusercontent.com/assets/21307007/18047226/72c54296-6de4-11e6-90fe-091adc99a101.png)

**Comment by RustanovTimur** [comment]
![1](https://cloud.githubusercontent.com/assets/21307007/18047244/877f2ecc-6de4-11e6-8e0d-04f81bc10114.png)

**Comment by TiberiumPY** [comment]
You need to select class or method first I think

**Comment by TiberiumPY** [comment]
You need to select class or method, otherwise it doesn't work.
And download latest beta version

**Comment by RustanovTimur** [comment]
After first click on Method then open Code window by default. I think can be deleted Code menuitem

**Comment by TiberiumPY** [comment]
Why? No

**Comment by TiberiumPY** [comment]
And please, (sorry,russian), редактируй перевот гугл транслейта, ты пишешь как индианин какой-то...

**Comment by 0xd4d** [comment]
If nothing is selected, the code window can't show any contents and is thus disabled. Just click on a method or type and it will automatically be made visible again.

**Comment by RustanovTimur** [comment]
Не могу я по анг. писать. Прошу прощения. А можно Вам на прямую задавать вопросы на русском. И куда писать? 29.08.2016, 13:32, "Daniil Yarancev" <notifications@github.com>:And please, (sorry,russian), редактируй перевот гугл транслейта, ты пишешь как индианин какой-то...—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by TiberiumPY** [comment]
Можете некоторые вопросы на tiberiumk12 собака gmail точка com .На все не отвечу, но на некоторые

**Comment by RustanovTimur** [comment]
Добрый день. Спасибо, что дали свою почту. Задача у меня такая есть одна небольшая среда разработки. Т.е. по сути ехе файл остается прежним, а часть скриптов в виде C# кода хранится в БД. В зависимости от параметров командной строки скачивается определенный набор скриптов. Эти скрипты компилируются в одну ДЛЛ и эта ДЛЛ загружается с файла в память и в итоге их неё вызываются методы классов. Иногда нужно отлаживать эти скрипты. Я ставлю Debugger.Break. Потом я через dnSpy открываю свою Среду разработки и отлаживаю. Но проблема в том, что у меня множество различных параметров начиная от параметров командной строки и до параметров в бд. Вот я бы хотел открывать dnSpy в режиме отладки в своем проекте и подключать сразу к своему проекту. Это значительно сократит время для меня. Можно ли такое сделать?

**Comment by TiberiumPY** [comment]
Вам уже ответили в другой ветке - да, можно подключить dnSpy к своему процессу

**Comment by RustanovTimur** [comment]
Это получается как внешняя программа. А я хочу из своего проекта.  29.08.2016, 21:52, "Daniil Yarancev" <notifications@github.com>:Вам уже ответили в другой ветке - да, можно подключить dnSpy к своему процессу—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by TiberiumPY** [comment]
Тогда я вам ничем не могу помочь.... Эту программу делает по сути 1 человек, на добровольной основе

**Comment by RustanovTimur** [comment]
Я понимаю. Но мне по сути нужен вызов при котором перед вызовом Application.Run открывается dnSpy в режиме отладчика. Я так понимаю там пару строк кода. Вот и хочется от создателя узнать как вызвать эти строки 30.08.2016, 09:41, "Daniil Yarancev" <notifications@github.com>:Тогда я вам ничем не могу помочь.... Эту программу делает по сути 1 человек, на добровольной основе—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by TiberiumPY** [comment]
Так какая разница. ВСЁ РАВНО ЖЕ запустится другая программа?!

**Comment by RustanovTimur** [comment]
Разница в том, что будет открыто окно dnSpy а потом открыта моя программа. Т.е. я получаю как в VS отладку. Когда студия на заднем плане а моя программа на переднем. И я сразу перехожу в режим отладки. Те мне не надо в диалоговом окне искать мою прогу, не надо задавать параметры. Сразу начинается отладка. Вот что мне нужно. Прости за надоедливость   30.08.2016, 17:24, "Daniil Yarancev" <notifications@github.com>:Так какая разница. ВСЁ РАВНО ЖЕ запустится другая программа?!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by TiberiumPY** [comment]
Пишите код сами... это не так сложно же должно быть
