### ISSUE TITLE
Need used dnSpy in my application

### ISSUE THREAD

**Issue by RustanovTimur** [0xd4d/dnSpy#193]
Hello, i have application which used CSharpCodeProvider and dynamic compilation of code snippets. I need to debug code snippets in my application. I want used dnSpy as part of my application.

For example i have code snippet.

 string code = @"
    using System;
    using System.Diagnostics;

    namespace First
    {
        public class FirstClass
        {
            public static void Run()
            {
                       Debugger.Break();
            }
        }
    }
";

In OnClick event i do Compilation and Execute of FirstClass.Run() method. I do follow

 private void button1_Click(object sender, EventArgs e)
 {
    string code = @"using System;
                    using System.Diagnostics;
                    namespace First
                    {
                      public class FirstClass
                      {
                        public static void Run()
                        {
                           Debugger.Break();
                        }
                      }
                    }";

    CSharpCodeProvider provider = new CSharpCodeProvider();
    CompilerParameters parameters = new CompilerParameters();

    parameters.ReferencedAssemblies.Add("System.Drawing.dll");
    parameters.OutputAssembly = @"D:\RunTime.dll";
    parameters.GenerateInMemory = false;
    parameters.GenerateExecutable = false;

    CompilerResults results = provider.CompileAssemblyFromSource(parameters, code);
    Assembly assembly = results.CompiledAssembly;
    Assembly.LoadFrom(parameters.OutputAssembly);

    Type firstClassType = assembly.GetType("First.FirstClass");
    MethodInfo runMethodInfo = firstClassType.GetMethod("Run");
    runMethodInfo.Invoke(null, null);
}

I want stopped debugger on code line Debugger.Break(); I think do follow steps.
1. Run dnSpy in Debug Mode before running my main form

 static class Program
    {
        [STAThread]
        static void Main()
        {
           //Run dnSpy in Debug Mode before running my main form
             dnSpy.MainApp.StartUpClass.Main();

            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);

            //Run my application 
            Application.Run(new Form1());
        }
    }

2. Do some action in my application while will be call Debugger.Break()
3. Debug application in dnSpy and load D:\RunTime.dll in dnSpy 

Is this possible? Can you show program code for open dnSpy in DebugMode?

**Comment by 0xd4d** [comment]
Just start your application from dnSpy or attach to it if it's already started.

**Comment by RustanovTimur** [comment]
I know about start process|attach, I need from My application. Can you provide example?
