### ISSUE TITLE
How can I build the dnSpy-Project?

### ISSUE THREAD

**Issue by SeppPenner** [0xd4d/dnSpy#195]
How can I build the dnSpy-Project? Doesn't work for me with .Net 4.6.2...
It says that libraries and projects are not found :/ Can anyone help me there, please?

**Comment by SlowLogicBoy** [comment]
1.  Check out project from github with submodules, 
2.  Then restore nuget packages 
3.  Build the solution (well ILSpy decompiler tests still doesn't compile for me)

**Comment by 0xd4d** [comment]
It's explained in the wiki: https://github.com/0xd4d/dnSpy/wiki/Building-dnSpy

Also, BETA binaries exist if you can't build it yourself: https://ci.appveyor.com/project/0xd4d/dnspy/build/artifacts

**Comment by SeppPenner** [comment]
> Check out project from github with submodules,
    Then restore nuget packages
    Build the solution (well ILSpy decompiler tests still doesn't compile for me but it's not necessary)

That's what I did... (I downloaded the .zip-file) I'm still getting these errors: 
![dnspy-error](https://cloud.githubusercontent.com/assets/9639361/18082937/3be21796-6ea1-11e6-8201-55d7cb73e60e.png)

In the build version: Is there the "Edit C# Code" command already implemented? Because that was what I'm actually looking for and I didn't find it in there...

**Comment by TiberiumPY** [comment]
SeppPenner, yes, just download beta-builds, Edit C# code is there

**Comment by TiberiumPY** [comment]
Sometimes it doesn't appear then you right-click, just try a few times

**Comment by SeppPenner** [comment]
Ok, Thank you, I will try it again. Can be closed than I guess.
