### ISSUE TITLE
Incorrect comparison

### ISSUE THREAD

**Issue by CodeShark-Dev** [0xd4d/dnSpy#206]
I found a posible mistake in the code:
It should be like that: `a.GetFontName() == b.GetFontName()` or I'm wrong?

https://github.com/0xd4d/dnSpy/blob/dad5039332e5f6218170d7b56ba3e570faa11155/dnSpy/dnSpy/Language/Intellisense/CompletionTextElementProvider.cs#L117

**Comment by TiberiumPY** [comment]
Just make a pull request

**Comment by 0xd4d** [comment]
Yes, that's a bug. :+1:
