### ISSUE TITLE
w3wp cannot attach by dnspy

### ISSUE THREAD

**Issue by richs2008** [0xd4d/dnSpy#209]
Hi,this tools is very good. I have debug for IIS web application ,standard asp.net web application. window10, IIS pool is using .net 4.0 . using vs2015 attach ,must using " all user "check bok, w3wp.exe can load . find w3wp.exe by netservice load no by administrator user. this project download in my computer, study c# source. 
![image](https://cloud.githubusercontent.com/assets/8036268/18311558/870dc52a-7537-11e6-8a06-3b3cd1d64c90.png)
my question is how attach in dnspy?

**Comment by 0xd4d** [comment]
Debug -> Attach to Process (`Ctrl+Alt+P`)

**Comment by skyyearxp** [comment]
After that， Debug->Modules to select dll to debug, or set breakpoint.
