### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by saneki** [0xd4d/dnSpy#21]
Would be nice to have dnSpy on [chocolatey].

I've setup the files needed to make a basic package for dnSpy at https://github.com/saneki/chocolatey-packages/tree/master/dnSpy

It currently doesn't do anything past installing the release zip with binaries from github (it doesn't add dnSpy to the start menu or anything like that, yet).

I wouldn't mind submitting/maintaining the package, but I thought it might be better for someone more active in the project to handle that.

[chocolatey]:https://chocolatey.org/

**Comment by 0xd4d** [comment]
If you want you can add it but I won't have enough time to do it myself.

**Comment by 0xd4d** [comment]
Closed since you've already added it there.
