### ISSUE TITLE
Feature Request: Search all strings in dotnet assembly

### ISSUE THREAD

**Issue by skypeaful** [0xd4d/dnSpy#210]
Is it possible to make dnSpy search all strings in dotnet assembly?
Dotnet Resolver have a similar plugin: https://github.com/JerreS/StringSearcherPlugin which can search all strings in .exe or .dll.
The image below is example:
https://s14.postimg.org/p768ncfwh/dump.png

**Comment by 0xd4d** [comment]
The search toolwindow can search for strings too (`Ctrl+K`):

![stringsearch](https://cloud.githubusercontent.com/assets/1060731/18376639/265b6fea-7661-11e6-842f-1315f5b1ebac.png)

**Comment by 0xd4d** [comment]
But the output could be better though, eg. include the found string.

**Comment by skypeaful** [comment]
But I think search all strings is better because we can't guess string to search in obfuscated executable.
List all strings and navigate to it make dnSpy more powerful.

**Comment by SlowLogicBoy** [comment]
Well we can always write plugin for dnSpy to do that.

**Comment by skypeaful** [comment]
@SlowLogicBoy: Can you help me write plugin to do that? I'm no idea in write plugin for dnSpy

**Comment by SlowLogicBoy** [comment]
There are [Examples](https://github.com/0xd4d/dnSpy/tree/master/Extensions) how to write a plugin, I learned most of it from these extensions. If I want something I look if one of the extensions do similar thing and copy from them. For your case you can look at [Analyzer Extension](https://github.com/0xd4d/dnSpy/tree/master/Extensions/dnSpy.Analyzer) cause this is an extension @0xd4d mentioned in previous [response](#issuecomment-245824830). 
Also to start there is a [wiki](https://github.com/0xd4d/dnSpy/wiki/Extensions) for extension dev

**Comment by AxDSan** [comment]
Hope you guys still need this! as I'm working on such plugin... just to mention I really needed this also so it's gonna be for sake of everyone :D
![Strings Analyzer](http://i.imgur.com/2NV6js8.png)

**Comment by skypeaful** [comment]
@: AxDSan: Awesome, I hope you will release this useful plugin soon.

**Comment by AxDSan** [comment]
## Little Update

---
![DnSpy Strings Analyzer - Plugin](http://i.imgur.com/G0Rh9ES.png)
---

The plugin is finally done, However right now as it is, it's only a developer build, and it's not mean to be released to the public just yet,[ I've documented most of the coding](https://www.livecoding.tv/0x90/playlists/RxzY2-coding-a-plugin-for-dnspy-strings-analyzer/) and I'm now starting to run into some problematic features I would like to develop:

*TODO*
[√] Fix scrolling bars not working properly...
[-] Add ContextMenu to each individual ListViewItem...
[-] Add Double Click & Goto Method Function...

Now as you can see on my TODO list, I fixed the scrolling bars, and that's done finally, the thing I wanna do is implement the DotNetImage to get the reference of the current image being analyzed, and not to have the user to Load Assembly image every time, as we all know that's utterly painful to do for every single thing we're going to analyze.

I will upload the project to github as we speak, I'm building this plugin heavily based on Example2 from the Extensions Samples, so don't bash on me if you see that some part of the code didn't changed.

**Comment by 0xd4d** [comment]
Ctx menu: have a look at the BP window

1. XAML: https://github.com/0xd4d/dnSpy/blob/master/Extensions/dnSpy.Debugger/dnSpy.Debugger/Breakpoints/BreakpointsControl.xaml#L37
  or in code: https://github.com/0xd4d/dnSpy/blob/master/Extensions/dnSpy.Analyzer/AnalyzerService.cs#L132

2. Command base class: https://github.com/0xd4d/dnSpy/blob/master/Extensions/dnSpy.Debugger/dnSpy.Debugger/Breakpoints/Commands.cs#L79

Go to method:

1. You need to do something similar to what this code does: https://github.com/0xd4d/dnSpy/blob/master/Extensions/dnSpy.Analyzer/AnalyzerService.cs#L253

**Comment by AxDSan** [comment]
@0xd4d Amazing, I was looking over the surface and trying to make sense and was kinda stuck, just needed someone to point me in the correct direction :+1:  thanks again! :D

**Comment by 0xd4d** [comment]
Closing it, extension exists.
