### ISSUE TITLE
Writing out compiler-generated get_/set_ method invocations instead of property access

### ISSUE THREAD

**Issue by Phrohdoh** [0xd4d/dnSpy#212]
`Target`, in this example, has a `TargetType Type { get { } }` member.

You can also see `get_CenterPosition()` which should be `.CenterPosition`.

I realize that the IL actually makes these calls which is why they are being written out this way.

Should someone/I instead of wanting this fixed write a plugin to transform get/set to property access? (This could of course be done with Roslyn or NRefactory).

![screen shot 2016-09-09 at 6 19 07 pm](https://cloud.githubusercontent.com/assets/4861023/18407519/5039e888-76d8-11e6-89be-11b2a5d22cbb.png)

**Comment by 0xd4d** [comment]
This happens when dnSpy can't find the assembly that's being referenced in the code. You can press Ctrl+O to load the assembly that contains `get_CenterPosition` etc and you should see normal property access code instead of `get_XXX` and `set_XXX` calls.

**Comment by Phrohdoh** [comment]
That makes sense, thank you.
For anyone reading this in the future you'll want to use `--asm-path path/to/dir`.

Example:
`$ dnspy OpenRA.Mods.D2k.dll -o output --asm-path ~/projects/play/openra`

It would be nice to be able to reference an assembly directly, but this certainly works.
