### ISSUE TITLE
Illegal class and member names from compiler-generated classes

### ISSUE THREAD

**Issue by Phrohdoh** [0xd4d/dnSpy#213]
```csharp
		// Token: 0x02000199 RID: 409
		[CompilerGenerated]
		[Serializable]
		private sealed class <>c
		{
		}

[..snip..]

			if ((arg_20E_1 = WorldGen.<>c.<>9__239_2) == null)
			{
				arg_20E_1 = (WorldGen.<>c.<>9__239_2 = new WorldGenLegacyMethod(WorldGen.<>c.<>9.<generateWorld>b__239_2));
			}

```

This is allowed by the compiler but not in user-code.
Is this something solvable or is it something that must be dealt with?

Perhaps I am not providing a flag that would alleviate this?

Thanks for the help!

**Comment by 0xd4d** [comment]
That's code generated by Roslyn and isn't always decompiled well enough by the decompiler. There's already an issue, #118, so I'll close this.
