### ISSUE TITLE
C#(VB) Interactive, AutoComplete and other features

### ISSUE THREAD

**Issue by SlowLogicBoy** [0xd4d/dnSpy#215]
1. I would like to have up arrow functionality that would bring last typed command
2. AutoComplete, well this mostly for dnSpy scripting, since I need to open dnSpy code to look what I can and can't use, and dnlib wiki.

**Comment by 0xd4d** [comment]
1. Alt+Up/Down arrow does that, same as in VS2015's `C# Interactive`

2. #197
