### ISSUE TITLE
Debugger step IL Command when in IL mode?

### ISSUE THREAD

**Issue by SlowLogicBoy** [0xd4d/dnSpy#216]
When I use Debugger in C#/VB mode debugger steps through one line of code, however in IL mode it steps through multiple IL commands if those commands make one line in C#/VB. Am I wrong? Am I missing some setting?

**Comment by 0xd4d** [comment]
It's not possible to set a BP (or step) at every IL instruction; it's a CLR debugger limitation.

**Comment by SlowLogicBoy** [comment]
So I guess the only way to do this is to debug natively with IDA, are there any plans to go from CLR debugger to native one?

**Comment by TiberiumPY** [comment]
@SlowLogicBoy native debugger is very hard to implement, because it's .NET

**Comment by 0xd4d** [comment]
Native debugging of IL methods is on my to do list but it's nowhere near the top of the list.

**Comment by 0xd4d** [comment]
Closed since it's not possible to always step just one IL instruction at a time.
