### ISSUE TITLE
Can't edit C#/VB Code. Stuck decompiling.

### ISSUE THREAD

**Issue by mscreations** [0xd4d/dnSpy#217]
I'm using the latest beta release (bb5c730c) and on both machines (One is 32 bit and other is 64 bit) I'm working on, this gets stuck on decompiling when I try to edit the C# code. Are there any prerequisite programs that have to be installed for this to work (Neither machine has Visual Studio or anything)?

**Comment by TiberiumPY** [comment]
Can you share the dll ?

**Comment by 0xd4d** [comment]
Visual Studio is not required to run it. Have you tried the prebuilt binaries? https://ci.appveyor.com/project/0xd4d/dnspy/build/artifacts

Does it always hang? What if you try to edit `dnSpy.exe`, does it also hang?

**Comment by mscreations** [comment]
Ok, here's some more information:

Computer 1 is running Windows 10 x64. I tried editing dnspy.exe while running both the 64 and 32 bit versions.

Computer 2 is running Windows 7 32bit. I tried editing dnspy.exe while running just the 32 bit version. 

On both machines, it hangs when I try to edit the C# code. It just displays Decompiling with a progress bar. I've let it run for over 2 hrs and it never finishes. 

Both machines are using the binaries produced by the build server.

**Comment by TiberiumPY** [comment]
@mscreations did you tried to run it with Admin rights (just for sure)?

**Comment by mscreations** [comment]
@TiberiumPY Yes. My work computer (the 32bit Windows 7 machine) is setup with UAC off and my user is full Administrator.

**Comment by 0xd4d** [comment]
Quick workaround: rename/delete `Microsoft.CodeAnalysis.Workspaces.Desktop.dll`. It has a dependency on `Microsoft.Build` and various other files that for some reason aren't included...
