### ISSUE TITLE
Should .NET assemblies running as service be listed when attaching to a process?

### ISSUE THREAD

**Issue by galaris** [0xd4d/dnSpy#220]
Hello,

So the question in the title.
I have a .NET binary running as a service, and it does not show up in the process list when Im tring to attach to a process in dnSpy. Is there any way to attach to a .NET service in dnSpy?

**Comment by TiberiumPY** [comment]
Did you tried both versions? x86 and standart dnSpy.exe ?

**Comment by 0x53A** [comment]
AFAIK dnSpy can attach to services, but it can't attach to processes running under another user.

I was able to attach to a service by

1) changing the service account to my domain account
![image](https://cloud.githubusercontent.com/assets/4236651/18552046/2fd649d8-7b5b-11e6-94cb-5fefa3ac9c91.png)

2) Starting dnSpy (with the correct bitness) as Administrator

**Comment by merces** [comment]
I'm curious... When you guys attach to a service that is already running, how do you debug that? Where to set a BP? I could imagine you could set a BP at OnStop() method and stop the service using sc/net Windows command-line tool, but I can't imagine how to break at OnStart() method for example.

**Comment by 0xd4d** [comment]
You just set a BP at the interesting method(s) once you've attached to it and loaded the correct module (check the Modules window).
