### ISSUE TITLE
Debugging a .NET DLL loaded by unmanaged C++ binary

### ISSUE THREAD

**Issue by rfrfrf** [0xd4d/dnSpy#221]
Is this possible right now or has this to be implemented?
cf. "Mixed Debugger Type" in VS (https://stackoverflow.com/questions/28871303/debugging-a-net-com-dll-loaded-by-unmanaged-c-binary-in-visual-studio)

**Comment by 0xd4d** [comment]
You could also attach to it, although you would get a worse debugging experience since the assemblies would probably be optimized once you attach to it so [read this](https://msdn.microsoft.com/en-us/library/9dd8z24x(v=vs.110).aspx).

**Comment by 0xd4d** [comment]
I'm closing this since there has been no reply, so I assume it worked...

**Comment by Jitnaught** [comment]
@0xd4d How would you attach to it if dnSpy is unable to attach to unmanaged process?

**Comment by 0xd4d** [comment]
dnSpy can only debug .NET code so try another debugger such as x64dbg.

**Comment by Jitnaught** [comment]
@0xd4d Yes I know that. What I'm wanting to do is debug a .NET assembly that's being loaded by an unmanaged assembly, and you said you could attach to it.

**Comment by UlyssesWu** [comment]
Usually dnspy will show all processes which contain CLR (even their main executable files are not managed, such as Visual Studio "devenv.exe" is attachable) in "Attach To Process" Window. You just need to use dnspy x86 for 32-bit exes and x64 for 64-bit exes.

But I don't know if some special programs are not shown in that list --- either x86 or x64 version dnspy.

**Comment by Jitnaught** [comment]
@UlyssesWu Thanks for the tip, helped me out, thanks! :)
