### ISSUE TITLE
Why have you copied ilspy code?

### ISSUE THREAD

**Issue by Alex141** [0xd4d/dnSpy#224]
You have copied all code from ilspy solution, including decompiler, original wpf components and other libs in first commits and then renamed solution: https://github.com/0xd4d/dnSpy/commit/678c9b9e9678fe6cd7ccd8b5f5825c2e03406b85. I have very respect author of these libs, Daniel Grunwald and I'm very disgusted that you simply copied results of his work and renamed it. You should use github "fork" for that goal or write all code by yourself. So, why did you do that?

**Comment by Alex141** [comment]
AvalonEdit, Decompiler, all NRefactory libs, TreeView - these all are components from ICSharpDevelop - you even didn't specify information about these components in help window! You must add info about it sush as it has done in IlSpy About page:

Included open-source libraries:
 Mono.Cecil: MIT License (thanks to Jb Evain)
 AvalonEdit: LGPL
 SharpTreeView: LGPL
 ICSharpCode.Decompiler: MIT License (developed as part of ILSpy)
 Ricciolo.StylesExplorer: MS-PL (part of ILSpy.BamlDecompiler.Plugin)

**Comment by 0xd4d** [comment]
There are too many errors in your two posts above.

ILSpy decompiler and various of its dependencies such as NRefactory are included. CREDITS.txt which you can see [here](https://github.com/0xd4d/dnSpy/tree/master/LicenseInfo) is shown if you click on Window | About.

dnSpy was a fork of ILSpy in the 1.x release, it was rewritten in 2.x. ILSpy's decompiler (and Analyzer) are still part of dnSpy, you can find them in the extensions sub directory.

**Comment by catester** [comment]
Thank you 0xd4d, you created the best .net tool. Personally I don't care which parts you borrowed because the end result is better than the owner of those parts, excellent composition. ILSpy or Reflector sucks :)

**Comment by 0xd4d** [comment]
Just to clarify, dnSpy uses many 3rd party open source code, ILSpy's decompiler and ILSpy's analyzer are a few of them, Roslyn is another one, etc. The licenses allow someone to use the code as long as the license info and other credits are included. And you can find that info in CREDITS.txt and the LicenseInfo folder (which btw, is also part of the binary distribution).
