### ISSUE TITLE
Saving an open module

### ISSUE THREAD

**Issue by glemsom** [0xd4d/dnSpy#228]
Currently you cannot save a module which has modifications (either breakpoints or IL fixes).
It would be very handy if this was somehow possible - so one could make modifications, and run the same module under the debugger again (while keeping the breakpoints).
Having to reopen the file, and locating the same breakpoints can be very difficult when troubleshooting large projects.

**Comment by 0xd4d** [comment]
Try the latest build and see if it works, I've added a fix for something that is perhaps the cause of your problem.
