### ISSUE TITLE
What is your donation information?

### ISSUE THREAD

**Issue by yzpopulation** [0xd4d/dnSpy#229]
I think he is very useful.

**Comment by 0xd4d** [comment]
There's no donate button because I don't accept donations. :)

**Comment by UlyssesWu** [comment]
No offense, but my poor Chinese-English friend, I suggest you pay for an English lesson 😂

**Comment by yzpopulation** [comment]
@UlyssesWu 我应该怎么说？我英语三级，我想支持一下1美元，虽然不多，略表心意

**Comment by UlyssesWu** [comment]
@yzpopulation 人家已经表示不接收捐款了，你就默默地从心里支持就行了（希望你不要加入我们的汉化工作……）。以作者的技术，我想他的收入应该不会比你少的。在我看来，0xd4d可是世界上最懂.NET的人之一了。**He is the top master in .NET** 🙏
P.S.你的两句英文表达都是错误的，建议你如不复习英语的话就在发帖前先用机翻参考吧。

**Comment by yzpopulation** [comment]
@UlyssesWu 非常赞同，个人仅仅是爱好，有稳定工作，主要是兴趣，dnspy 反编译太牛了，目前遇到PE 给c#加壳且c#混淆，运行时释放，dnspy dump出来文件还是有问题没搞定，壳太复杂了。

**Comment by pigfromChina** [comment]
:)
