### ISSUE TITLE
Cancel Decompile Doesn't Seem To Work

### ISSUE THREAD

**Issue by atom0s** [0xd4d/dnSpy#23]
Cancelling a decompilation request does not seem to do anything. The decompiling still continues until it is fully completed. 

An easy way to test this is try decompiling a binary obfuscated with ConfuserEx, the main module will take some time to decompile due to how the data is stored in an int[] array. This will take the decompiler a bit to do the work, and trying to cancel it does nothing.

**Comment by 0xd4d** [comment]
Do you have an example binary or a ConfuserEx config file used to generate something that will trigger this?

The ILSpy decompiler seems to be missing checks for the cancel event in various places.

**Comment by atom0s** [comment]
I don’t have any public files I can share currently that cause this, but it happens for any file that takes a while to decompile for me.


For ConfuserEx, just protect a file with the maximum settings, no special configuration is needed otherwise. And this should happen every time.






From: 0xd4d
Sent: ‎Sunday‎, ‎August‎ ‎9‎, ‎2015 ‎11‎:‎57‎ ‎AM
To: 0xd4d/dnSpy
Cc: atom0s





Do you have an example binary or a ConfuserEx config file used to generate something that will trigger this?

The ILSpy decompiler seems to be missing checks for the cancel event in various places.

**Comment by 0xd4d** [comment]
If this doesn't fix it for you, reopen this issue.

**Comment by atom0s** [comment]
Works great, thanks. :+1:
