### ISSUE TITLE
wcf debug program

### ISSUE THREAD

**Issue by richs2008** [0xd4d/dnSpy#230]
for many days study ,debug webapp for wcf is not success.where is setting error for me? fellow is five pic for vs2015 debug and dnspy.
![01](https://cloud.githubusercontent.com/assets/8036268/18897924/ca1cbb30-8560-11e6-9a89-c900abca553b.PNG)
run WCFClient.exe ，vs 2015 target  getdata method really.
but in dnspy ,GetData method was  not  intercepte and captured  ;
![04](https://cloud.githubusercontent.com/assets/8036268/18897761/86bd9982-855f-11e6-9eb4-11f9480f99c5.PNG)
![05--dnspy-result](https://cloud.githubusercontent.com/assets/8036268/18897766/8ca7a6e4-855f-11e6-8f40-96a4d521587d.PNG)
example is vs2015 create wcf template.

fellow is informat list:
[dnspy load w3wp --outwindow information.txt](https://github.com/0xd4d/dnSpy/files/497027/dnspy.load.w3wp.--outwindow.information.txt)
[vs2015 load w3wp --outwindow information.txt](https://github.com/0xd4d/dnSpy/files/497028/vs2015.load.w3wp.--outwindow.information.txt)

**Comment by 0xd4d** [comment]
Open the Modules window and locate the correct DLL file and open it, and then set the breakpoint. BPs only break if they're set in the correct file, and sometimes there are multiple identical files and only one of them is actually loaded in some process.

**Comment by richs2008** [comment]
Thanks.
The graph, example have two method ,only vs2015 self create wcf program. i have run vs2015 use the w3wp.exe ID is same as dnspy.  very very simple code.
![new01](https://cloud.githubusercontent.com/assets/8036268/18903656/e26defac-858c-11e6-931e-6ff711e1e9cb.PNG)
![new02](https://cloud.githubusercontent.com/assets/8036268/18903669/f315968e-858c-11e6-991c-5ca94dd0db7d.PNG)
code is here.

**Comment by richs2008** [comment]
![w01](https://cloud.githubusercontent.com/assets/8036268/18904949/4f6e7526-8593-11e6-9468-e735e4be8cd3.png)
yout told me "sometimes there are multiple identical files" means what? in dynspy ?or in progress ,attach w3wp.exe is only one ,i check with progress ID.

**Comment by richs2008** [comment]
![w02](https://cloud.githubusercontent.com/assets/8036268/18905514/170c8b20-8596-11e6-9671-c1cd02abe3e8.png)

**Comment by 0xd4d** [comment]
You should open it from the Modules window to make sure you're using the correct file. Ctrl+Alt+U
