### ISSUE TITLE
【Debugger Feature】: Watch Value

### ISSUE THREAD

**Issue by AxDSan** [0xd4d/dnSpy#232]
I would love to see such feature available, just like with olly or something down the line.

《NVM》
Didn't noticed this was requested several times already, please mark as duplicate and close!
Deeply sorry for the inconvenience!
o(>﹏<)o

**Comment by greenozon** [comment]
Yes, voting for this as well!
latest 3.0.0 beta still shows not user friendly data in the hint window for vars, example:

http://prntscr.com/cr8rjq
