### ISSUE TITLE
If local variable is missing and its index can't be resolved, IL operand error is not displayed 

### ISSUE THREAD

**Issue by pixellos** [0xd4d/dnSpy#237]
If LocalVariable is missing, index of load local variable instruction can't be resolved and IL operation is displayed without operand. No error is displayed. Same behaviour observed in IL Spy tool unfortunately.

[Debug.zip](https://github.com/0xd4d/dnSpy/files/517884/Debug.zip)

**Comment by 0xd4d** [comment]
You mean this:

```IL
	/* 0x00000263 1200         */ IL_0007: ldloca.s
```

(There are no locals in this method)

So you want an error message or some error color?

**Comment by 0xd4d** [comment]
As a workaround, you can have a look in the IL editor, it will show an error. ;)

**Comment by pixellos** [comment]
Thanks for response. I think il reader could introduce similar highlighting to il editor. What is your suggested approach?

**Comment by 0xd4d** [comment]
Using the error color and printing eg. V_XXX

**Comment by pixellos** [comment]
That sounds convenient :)
