### ISSUE TITLE
Decompile IEnumerator correctly

### ISSUE THREAD

**Issue by damh0503** [0xd4d/dnSpy#239]
Hi,
I'm trying to decompile IEnumerator, when I decompile it, it isn't show correctly like c__Iterator.
Is there any way to decompile IEnumerator correctly?
Thanks.

**Comment by 0xd4d** [comment]
Try the latest build.

**Comment by TiberiumPY** [comment]
@0xd4d WOW THANKS!!!!
this would make reversing unity 3d games so much easier

**Comment by maritaria** [comment]
I will test this too :) excited to see this

**Comment by FonzieMcCloud** [comment]
So... does decompiling of ienumerator work in the latest build?
I just tried ro decompile my own script with v 3.0.0 and the ienumerator part looks like in this example: https://github.com/icsharpcode/ILSpy/issues/575

**Comment by TiberiumN** [comment]
@FonzieMcCloud you should take latest build of `dbg` branch

**Comment by TiberiumN** [comment]
@FonzieMcCloud https://ci.appveyor.com/project/0xd4d/dnspy/branch/dbg/artifacts

**Comment by 0xd4d** [comment]
Use the master branch build, nothing else. The link is in the readme.

**Comment by TiberiumN** [comment]
@0xd4d why?

**Comment by 0xd4d** [comment]
@TiberiumN: The dbg branch is just a dev branch and isn't stable or ready for use, unlike master which should always compile and work.

**Comment by risheelk** [comment]
Hi i have tried the latest build
https://github.com/icsharpcode/ILSpy/releases/tag/v2.4
version 2.4 and i am not able to decompile ienumerator is there new version ?

**Comment by UlyssesWu** [comment]
@risheelk Obviously you didn't use _latest build_.  If you could have read `readme.md` carefully, it shows like this:

# Binaries

[Latest release](https://github.com/0xd4d/dnSpy/releases)

**Latest build**: [![Build status](https://ci.appveyor.com/api/projects/status/616rgr9ot3nvfjv5/branch/master?svg=true)](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts) <-Click Here
