### ISSUE TITLE
Hex Editor doesn't show bytes orderly...

### ISSUE THREAD

**Issue by XODE0** [0xd4d/dnSpy#24]
As i said in the title , hex editor doesn't show bytes orderly.
i am using Windows 7 x86 sp1,Professional 

![unnamed qq screenshot20150810053506](https://cloud.githubusercontent.com/assets/10565186/9159065/e4d8a71c-3f21-11e5-8b91-7b7c16b02ea9.png)

![unnamed qq screenshot20150810053818](https://cloud.githubusercontent.com/assets/10565186/9159081/0d85dc02-3f22-11e5-9fbc-05f7af00157c.png)

**Comment by 0xd4d** [comment]
That's clearly not a monospace font. What font are you using? View -> Options -> Hex Editor -> Font ?

**Comment by 0xd4d** [comment]
BTW, do you live in asia perhaps? Maybe Consolas / Lucida Console isn't present?

What fonts can you select from the Hex Editor tab?

**Comment by XODE0** [comment]
in the first time there wasn't a default font 

![unnamed qq screenshot20150810063159](https://cloud.githubusercontent.com/assets/10565186/9159486/9274ef0a-3f29-11e5-80d5-fd549b5e3905.png)


, but once i change to Lucida Console it fixed the problem 
thanks

**Comment by 0xd4d** [comment]
What fonts can you see in the list? Do you have Consolas? AFAIK, Windows 7 should have Consolas.

**Comment by XODE0** [comment]
yes i have
![unnamed qq screenshot20150810063446](https://cloud.githubusercontent.com/assets/10565186/9159514/fd412d1c-3f29-11e5-83b7-b1d419b62377.png)

**Comment by 0xd4d** [comment]
You don't have Consolas but you do have Lucida Console. I've added a fix where it now actually checks whether the default font exists before using it. It assumed Consolas was present if Windows 7 or later was used.
