### ISSUE TITLE
Why must press twice Ctrl+R?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#241]
private static void Main()
{
	Application.EnableVisualStyles();
	Application.SetCompatibleTextRenderingDefault(false);
	Application.Run(new Form1());
}

Click the method "EnableVisualStyles", then I want to analyze EnableVisualStyles method, I must press twice Ctrl+R .

**Comment by 0xd4d** [comment]
Because it's a beta and I haven't fixed everything yet. #151
