### ISSUE TITLE
Can't save last build

### ISSUE THREAD

**Issue by YuqseLx** [0xd4d/dnSpy#244]
i can't save files last build (3 hours ago now) here's error
`Writing C:\Users\Yüksel\Desktop\Microsoft.CSharp.dll...
An exception occurred

System.ArgumentOutOfRangeException: Dizin aralık dışındaydı. Negatif bir değer olmamalı ve koleksiyonun boyutundan daha küçük olmalıdır.
Parametre adı: index
   konum: System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   konum: System.SZArrayHelper.get_Item[T](Int32 index)
   konum: dnlib.DotNet.MD.DotNetTableSizes.GetSize(ColumnSize columnSize) C:\projects\dnspy\Libraries\dnlib\src\DotNet\MD\DotNetTableSizes.cs içinde: satır 44
   konum: dnlib.DotNet.MD.DotNetTableSizes.InitializeSizes(Boolean bigStrings, Boolean bigGuid, Boolean bigBlob, IList`1 rowCounts) C:\projects\dnspy\Libraries\dnlib\src\DotNet\MD\DotNetTableSizes.cs içinde: satır 34
   konum: dnlib.DotNet.Writer.TablesHeap.CalculateLength() C:\projects\dnspy\Libraries\dnlib\src\DotNet\Writer\TablesHeap.cs içinde: satır 308
   konum: dnlib.DotNet.Writer.TablesHeap.GetFileLength() C:\projects\dnspy\Libraries\dnlib\src\DotNet\Writer\TablesHeap.cs içinde: satır 281
   konum: dnlib.DotNet.Writer.MetaData.SetOffset(FileOffset offset, RVA rva) C:\projects\dnspy\Libraries\dnlib\src\DotNet\Writer\MetaData.cs içinde: satır 2692
   konum: dnlib.DotNet.Writer.ChunkListBase`1.SetOffset(FileOffset offset, RVA rva) C:\projects\dnspy\Libraries\dnlib\src\DotNet\Writer\ChunkListBase.cs içinde: satır 92
   konum: dnlib.DotNet.Writer.ModuleWriterBase.CalculateRvasAndFileOffsets(List`1 chunks, FileOffset offset, RVA rva, UInt32 fileAlignment, UInt32 sectionAlignment) C:\projects\dnspy\Libraries\dnlib\src\DotNet\Writer\ModuleWriterBase.cs içinde: satır 598
   konum: dnlib.DotNet.Writer.ModuleWriter.WriteFile() C:\projects\dnspy\Libraries\dnlib\src\DotNet\Writer\ModuleWriter.cs içinde: satır 251
   konum: dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest) C:\projects\dnspy\Libraries\dnlib\src\DotNet\Writer\ModuleWriterBase.cs içinde: satır 520
   konum: dnlib.DotNet.Writer.ModuleWriterBase.Write(String fileName) C:\projects\dnspy\Libraries\dnlib\src\DotNet\Writer\ModuleWriterBase.cs içinde: satır 487
   konum: dnSpy.AsmEditor.SaveModule.ModuleSaver.SaveAll() C:\projects\dnspy\Extensions\dnSpy.AsmEditor\SaveModule\ModuleSaver.cs içinde: satır 213
   konum: dnSpy.AsmEditor.SaveModule.SaveMultiModuleVM.SaveAsync(SaveOptionsVM[] mods) C:\projects\dnspy\Extensions\dnSpy.AsmEditor\SaveModule\SaveMultiModuleVM.cs içinde: satır 251
`

**Comment by 0xd4d** [comment]
Latest build should now work.
