### ISSUE TITLE
Feature Request：Double method

### ISSUE THREAD

**Issue by edwardnguyenbk** [0xd4d/dnSpy#246]
Idea: 
It's good to double method in any class. It would be very convenient when we create the dentures have similar functions. It helps us to use a lot of different purposes.
Thanks de4dot,

**Comment by 0xd4d** [comment]
You want to make a copy of a method?

You can already do this now, edit C# code, copy the method, change the name, compile.

**Comment by edwardnguyenbk** [comment]
No, I mean we can make a copy method in .NET assemblies file when we reverse engineer .NET assemblies. At the present, we have to "Create method.." and then "Edit method" and etc.
Examples: 
![image](https://cloud.githubusercontent.com/assets/13671408/19459483/72ce8672-94fd-11e6-8dc1-fb228ef9aff6.png)

**Comment by TiberiumPY** [comment]
@edwardnguyenbk close it then :)
