### ISSUE TITLE
Feature: Close non .net assembly files

### ISSUE THREAD

**Issue by SlowLogicBoy** [0xd4d/dnSpy#247]
I have loads of dll's in my project and easiest way to add them all to assembly browser is to select them all in directory (ctrl+a) and drag n drop to dnSpy assembly browser, however it also adds .config, .xml and other non dll and exe files.
It would be neat feature if I could close those files from context menu or to have some kind of setting that would allow to add only .net files to assembly browser.

![image](https://cloud.githubusercontent.com/assets/3121637/19520974/b9f52f7e-961a-11e6-9be9-021dbcf99e5f.png)

**Comment by 0xd4d** [comment]
Sounds like a good idea when dragging files from Windows Explorer. There should be an option to load all files though (it's off by default).

If you want to do this, have a look [here](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy/Documents/TreeView/DocumentTreeView.cs#L752) and check for `DsUnknownDocument`. Ignore those, but only if number of files dragged > 1 (if the user only drags one file, always load it even if it's a non-supported file).

**Comment by SlowLogicBoy** [comment]
Thanks, I'll probably look into this on weekend

**Comment by 0xd4d** [comment]
Fixed by #248
