### ISSUE TITLE
Feature: Simple IL byte editor

### ISSUE THREAD

**Issue by CodeShark-Dev** [0xd4d/dnSpy#249]
Is possible add a simple editor similar to ByteME(by Furious)? It doesn't need to be compiled/decompiled.

**Comment by 0xd4d** [comment]
There's already an IL editor. I assume you want something that doesn't require re-writing the full file?

**Comment by CodeShark-Dev** [comment]
Yes. Like this https://board.b-at-s.info/index.php?showtopic=8964

**Comment by 0xd4d** [comment]
It's not likely that I'll add this, no-one has sent a PR for a year either so it's not likely it will ever be implemented. Closing it.
