### ISSUE TITLE
Debug: variables hints are very flickering

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#25]
While debugging some .net code I've noticed a very strange and undesired flickering when mouse over some variables....
the example I've saved could be found here: xxxx

Note: the video shows somehow delayed frames, in reality the flickering is much much faster, so its almost not possible to use this very cool feature - values of var under mouse.......

Thanks

**Comment by 0xd4d** [comment]
I've never experienced this. Are you using a really old computer?

**Comment by greenozon** [comment]
yeah, always
its really annoying during debugging, believe me :)
its flickering much more faster than on video

**Comment by 0xd4d** [comment]
Seems like there's nothing I can do about this. Seems like a driver problem. I could reproduce it in VMWare running XP, see pic (see the bottom of the popup menu, there's a black square moving from left to right, flickering as it moves)

![pic](https://cloud.githubusercontent.com/assets/1060731/9287474/ad398ecc-4316-11e5-96b0-a7c33ec3bb4d.png)

**Comment by 0xd4d** [comment]
I've added a workaround for it that works when I tested it in VMWare XP. I can't reproduce it on my normal machine.

**Comment by greenozon** [comment]
Thank you very much
Appreciating your time and desire to investigate the issues specially taking into account that wxp are obsoleted bits.....

**Comment by 0xd4d** [comment]
Let me know if it works for you. It seems like (at least on my tested WinXP and .NET Framework version) that the indeterminate progressbar still draws its progressbar moving from left to right even though it's in a hidden control. There are two such progressbars and I had to set IsIndeterminate to false to fix this.

**Comment by greenozon** [comment]
It works great! (wxp @vm)
no flickering, very solid & stable

one more item (maybe worth new issue?) 
usually VS allows to show either decimal or hex decoded values in arrays, 
right now dnSpy shows decimal only, e.g.: http://prntscr.com/84u6zr
is it possible to add support for hex as well? 
Option 1: somehow in popup menu over var
option 2: in options:: debug GUI

Thanks

**Comment by 0xd4d** [comment]
Whenever I update the debugger, that's one thing I'll fix as well.
