### ISSUE TITLE
Feature: Show method body as bytes

### ISSUE THREAD

**Issue by Misiu** [0xd4d/dnSpy#250]
First of all: THANK YOU! Your application is awesome! It helped me so many times.
I'd like to ask for one feature: It would be awesome to see method body as bytes.
English is not my native language so it will be easier for me to show images showing functionality I'd like to see in dnSpy.
There is a plugin for Reflector called BytesViewer that allow viewing method body as Bytes:
![byteviewer](https://cloud.githubusercontent.com/assets/1741838/19626371/87463aa0-9930-11e6-8948-4e882004dba0.gif)

Right now we can right click and select `Show Instruction in Hex Editor`, but ideally I'd like to see whole body of method as bytes, just as shown on above picture.

**Comment by 0xd4d** [comment]
This is something that should be pretty easy to do with an extension.

Could you explain when this is useful? Is it just so you can easily copy the instruction bytes?

**Comment by Misiu** [comment]
@0xd4d Yes, exactly. It is easier to see bytes for single method and copy just those bytes than searching for it in hex editor - I'm unable to do that.
Ideally I'd like to be able to see method as bytes and be able to edit them and save changes without recompiling (just like hex editor - saving bytes).
Sometimes You need to quickly fix couple of bytes. This view (and editor if possible) would help a lot.
Thanks!

**Comment by 0xd4d** [comment]
You can already copy the method bytes by right clicking the method name and clicking on `Hex Copy Method Bytes`.

You can use the hex editor to edit the bytes as well so there's no point in duplicating that functionality. Right-click name and `Show Instruction (or Method) Bytes`.

**Comment by Misiu** [comment]
@0xd4d That's right, but there is one thing still missing. If for example I'll edit IL code I must compile assembly to be able so see changed bytes. Inside Reflector with Reflexil I can edit IL and view changed bytes (using `update Reflector object model` option).
It would be awesome to have this functionality inside dnSpy.
This way it would be easier to see what bytes changed (bytes diff).

Simple view to show original bytes and changed bytes (after IL updated) and show diff without recompiling. I don't know if this would be possible, but sometimes what I need it just to know what bytes changed.

If this is already possible forgive me, I wasn't able to find it.

**Comment by 0xd4d** [comment]
If you're using the hex editor you won't see any changes in the code the instant you modify something, you have to save and reload all assemblies (`File -> Reload All Assemblies`).

If you use the high-level assembly editor features, like IL editor, Edit C# Code, Edit Method etc, you'll see all changes instantly after you press OK.

**Comment by Misiu** [comment]
@0xd4d I've tried that just a second ago in dnSpy 3.0.0-beta.
I've created sample app in VS, compiled it and opened app in dnSpy.
Lets say I have below method:
```C#
private void button1_Click(object sender, EventArgs e)
{
    this.GetTable().ShowInNewWindow("Works?", null);
}
```
I right click on method name and select `Hex copy method body` I got: `13300300160000000100001100022805000006`
Then I right clicked on same method and using C# editor I erased method body, so now I only have this:
```C#
private void button1_Click(object sender, EventArgs e)
{
}
```
Once more I right clicked on method and after selecting `Hex copy method body` I got same result.

Ideally I'd like to be able to change method body using IL of C# editor and be able to copy changed method as bytes, without need to save changes to my application (without using File>Save Module...).

Sorry for terrible description, but hopefully You'll get my point.

**Comment by 0xd4d** [comment]
The hex editor uses its own data (raw files) and the normal editing features use high level structures. You can't mix them. The 'Hex' in menus is there to show that it's a hex editor command, perhaps it's confusing but I couldn't come up with anything better.

If you want to edit at the byte level you're going to have to use less advanced features. For example, you can only use references that already exist in the file, you can't create your own ones. You want to use List&lt;string&gt; but there's only a List&lt;int&gt; reference? Tough luck, if you're using the hex editor. To fix that you'd have to do more advanced changes to the image and then there's no point in using a hex editor, just use the high-level commands that end up rewriting the whole thing.

#249 tracks adding an IL editor for the hex editor. It would have limitations (no new refs etc).

**Comment by Misiu** [comment]
@0xd4d I'm aware of those limitations. Sometimes all You need is to change single line or even variable. Nothing fancy like new refs. 
With such simple edits having option to show byte diff would be helpful.
For one person editing single line is a small change, for others replacing whole class, so probably it won't be easy to have this working in all use cases, but please consider this.

**Comment by 0xd4d** [comment]
As a workaround, use the IL editor, then switch to IL mode and select all bytes in the method, and pick `Copy IL Bytes`. Diff that with the original one. And as said above, you can't add new strings / references since you'll be using the hex editor to make your changes.

I'll close this since the only thing you need now is already tracked in #249
