### ISSUE TITLE
Improved Local Viewing?

### ISSUE THREAD

**Issue by tandrews89** [0xd4d/dnSpy#252]
Perhaps its just me, but I was debugging an assembly and it didn't show all the defined locals. This became a problem because I needed to know the value of certain values. Thankfully some functions passed those values to other functions, so I just got it from there. But is this just me? I can provide pictures if it'd help.
BTW: Your software is f-ing amazing. Even visual studio + Reflector couldn't do 1/10 of what I wanted!!!

**Comment by SlowLogicBoy** [comment]
#39 This is being worked on.
It happens to me too, but I'm like you, find the way to find out value I need :)

**Comment by tandrews89** [comment]
I'm reversing something that uses data structures and stuff, so it's a big pain to just edit the source.

**Comment by 0xd4d** [comment]
All locals should be shown unless you attached to the process. The jitter will disable various optimizations if a debugger is attached, one of those things is keeping all locals and making sure they're on the stack instead of in registers.

**Comment by tandrews89** [comment]
I did attach since it's a service. I can create my own version of the service's file. should I debug that? Then I'll be able to see all the data?

**Comment by 0xd4d** [comment]
See [this article](https://msdn.microsoft.com/en-us/library/9dd8z24x(v=vs.110).aspx) on how to create a file that will disable optimizations so it will be easier to debug attached files.
