### ISSUE TITLE
Edit code: Add menu command to edit assembly and module attributes

### ISSUE THREAD

**Issue by Misiu** [0xd4d/dnSpy#254]
I'd like to add custom attribute to assembly  - `InternalsVisibleToAttribute` attribute.
Library that I'd like to modify already has couple of those attributes.
Right now hen adding new attributes we must specify constructor.
Having option to copy selected attribute would help, because this way all I'd have to do is to change constructor argument.
I can live without this option, but this would speed thing up.

**Comment by 0xd4d** [comment]
I think it would be better if you just edited that in C# or Visual Basic. I've updated the title.

**Comment by jamesqo** [comment]
@0xd4d Have you ever tried clicking on an assembly, selecting `Edit Assembly Attributes...`, making changes, and then saving them? It doesn't seem to work for me-- after I press 'Compile', I am taken back to the read-only editor screen with none of my changes applied. In contrast, editing methods and trying to save those work fine.

**Comment by 0xd4d** [comment]
@jamesqo It worked for me, used the [latest master build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)
