### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ivandrofly** [0xd4d/dnSpy#255]
1st of all thanks for this very useful tool :).

Here are the following useful feature I would like to see implemented in **dnSpy**:
- Sync with active document. ( can be seen in Visual Studio (Explorer))
- Remember search text (can be found in Visual Studio aswell).

**Comment by 0xd4d** [comment]
1. You can click on the `Assembly Explorer` text or press `Ctrl+Alt+L`
2. Ctrl+F: only the latest search text is currently remembered, could be improved though.
