### ISSUE TITLE
Features I want to see.

### ISSUE THREAD

**Issue by SlowLogicBoy** [0xd4d/dnSpy#257]
These are features I would like to see in dnSpy or separate extensions. Anyway maybe some of them could be introduced to this project instead of separate extension.
1. Support for NUnit (already started making as separate extension)
   
   > Helpful to debug external libraries since I don't have symbols for them
   > Work around is to run NUnit executable and attach dnspy to that.
   > I already have a runner for that, I just need cosmetic stuff.
2. "Notes" (#266)
   
   > Change variable/type/method names without actually changing .net module and save them somewhere where it could remember later
   > also add and save comments in code.
3. Remove duplicates from assembly explorer. (useful when debugging from memory and dragging multiple files multiple times) (#267)
4. Tab pinning (#251)
5. Open whole type instead of a member (#253)
6. Change key bindings (#243)
7. Injecting code changes (IL) into memory while debugging. (#268)
8. dnSpy updater. (#269)
9. de4dot integration (With Undo/Redo support, and also without changing assembly, reffering to 2. "Notes")
10. Collapse code (#270)
11. Replace code with custom templates

> Decompiler is not perfect. After decompilation it would go through your templates and change some code with your templates or something like that. 
> Example.:
> 
> ```
> bool flag = someargument == null
> if(flag)
> {
>     throw new ArgumentNullException("someargument")
> }
> ```
> 
> it chould be changed to:
> 
> ```
> if(someargument == null)
> {
>     throw new ArgumentNullException(nameof(someargument))
> }
> ```
> 
> Option to change variable types to var

**Comment by 0xd4d** [comment]
1: You use NUnit to debug DLL files?

2: I've been thinking about it myself too, we'll see when I have time to do it.

10: Outlining is an editor feature I never use, I like to see the code.

11: That's not the right thing to do it, the correct way is to update the decompiler.

**Comment by SlowLogicBoy** [comment]
>1: You use NUnit to debug DLL files?

I open NUnit app, open nunit project, attach dnspy to NUnit app and then debug tests, I do this to see how something works on external libs.

**Comment by 0xd4d** [comment]
I assume you have the source code to the tests so you could use VS to debug them instead.

**Comment by SlowLogicBoy** [comment]
I have source of tests and source of my project, but lets say I use nlog nuget without sources, I get only dll's and I want to debug them, you can't with visual studio unless you download source/debug files, so it's easier for me to just use dnSpy to do that.

**Comment by SlowLogicBoy** [comment]
* Quick Navigation (Improve Search)

>  Ctrl + Q / Ctrl + N / Ctrl + T to open dialog like this:
![Go To Everything](https://www.jetbrains.com/resharper/features/screenshots/100/go_to_everything.png)
Search and Navigate like in Search tab.

**Comment by SlowLogicBoy** [comment]
I think I should separate these in separate issues and close this one.

**Comment by 0xd4d** [comment]
Yes you can do that.

**Comment by SlowLogicBoy** [comment]
Split in separate issues.
