### ISSUE TITLE
Antivirus positive detection

### ISSUE THREAD

**Issue by DenJur** [0xd4d/dnSpy#258]
Kaspersky antivirus started detecting dnlib.dll as Trojan.MSIL.Agent.acdcq. But does not detect anything when dnlib.dll is built from source.

**Comment by 0xd4d** [comment]
Thanks for reporting.

The fix was to press `RE-BUILD COMMIT`.

Older builds (see appveyor site) don't report anything either.

**Comment by 0xd4d** [comment]
Kaspersky reporting false positives again. Could it be that someone is reporting it as a virus to fool Kaspersky? Is Kaspersky that easy to fool?

**Comment by DenJur** [comment]
Perhaps you should submit it as clean to https://newvirus.kaspersky.com and see if that helps. My local built still comes out as clean while appveyor build is detected as a virus.

**Comment by SlowLogicBoy** [comment]
I've seen some malware that came with dnlib namespaces in them so...

**Comment by 0xd4d** [comment]
That's probably not the reason because only the latest build is flagged by Kaspersky (false positive).

I think someone reports it as a virus to Kasperksy and Kaspersky believes it without verifying anything.

**Comment by 0xd4d** [comment]
Solution is to compile it yourself, closing it.
