### ISSUE TITLE
Possibility to copy/dump object values?

### ISSUE THREAD

**Issue by thinkv** [0xd4d/dnSpy#26]
Debugger works great, but when hovering over objects and viewing List items for example, I would like to be able to copy the whole object/list to the clipboard instead of copying one and then having the tree collapse and going back to do it again.

Would this be possible some how?

**Comment by 0xd4d** [comment]
That's probably not possible at the moment. I'm not prioritizing fixing the debugger at the moment so could take a while before I do something about this issue.

**Comment by Tajepe** [comment]
or a memory dump view providing copy option is good too

**Comment by idiMAN** [comment]
Please add ability to save string and array values to file

**Comment by 0xd4d** [comment]
Use the updated debugger and the locals window. Right-click and pick save.
