### ISSUE TITLE
It seems icons are blurry

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnSpy#261]
Thanks for great works.

![s](https://cloud.githubusercontent.com/assets/706507/19890350/64a398d0-9ff7-11e6-81d0-14a74baca2df.png)

**Comment by bprg** [comment]
It seems the problem resolved in the latest version.

**Comment by 0xd4d** [comment]
That's weird. If it happens again, re-open the issue (or create a new one).

**Comment by bprg** [comment]
I've tried **Windows 10 x64 Build 14393**

![2016-11-14_15-57-50](https://cloud.githubusercontent.com/assets/706507/20264995/3fc4e380-aa23-11e6-86aa-cf5145fbf7d6.png)

**Comment by 0xd4d** [comment]
Have you zoomed in the text editor or anything else eg. a tool window?

**Comment by bprg** [comment]
Yes when zoomed in the text editor icons blurred.
