### ISSUE TITLE
Impossible to modify IEnumerators

### ISSUE THREAD

**Issue by pikachuk** [0xd4d/dnSpy#262]
Hello, i don't know why everytime i try to modify the code of an IEnumerator, the code stil the same, so when i press compile,the code still unmodified (and sometimes do like it was the older version of this code) it would be awesome it this issue could be corrected

**Comment by 0xd4d** [comment]
It's a known bug, see #164

Temporary workaround: Create a new IEnumerable method with the same signature but a different name. Add a `return TheNewMethod(all, arguments);` to the original method.

**Comment by pikachuk** [comment]
ok i hope that you will find a way to solve it soon ^^

**Comment by 0xd4d** [comment]
I'll close this since it's a duplicate.
