### ISSUE TITLE
Problem of Assemblies duplicate mscorlib.dll

### ISSUE THREAD

**Issue by pikachuk** [0xd4d/dnSpy#263]
I post this second issue because it's a different problem that i've too
i'm always forced for the game that i modify with dnspy to remove mscorlib.dll from the folder while i'm modifying and replace it after saved modifications to play because i've always in dnspy a conflict with two mscorlib who are imported one from the system folders and one from the game folder, i don't know why but everytime it imports the two and i can't compile anything
removing from the list one of them hasn't any effect because it's automatically re-added
i don't know what to do, i can't tell if it's a but or something else

**Comment by 0xd4d** [comment]
Yes, that's a bug.

Could you email me a link to it to de4dot@gmail.com

**Comment by pikachuk** [comment]
what do you want  me to upload ? the folder ?

**Comment by pikachuk** [comment]
or a screenshot

**Comment by 0xd4d** [comment]
Email a link to the installer or a zip file of the files that can be used to reproduce this bug.

**Comment by pikachuk** [comment]
ok i'll send you that it's from the game yandere simulator, strangely i had not this bug before but it happens since some times
i tried to redownload the game and redownload dnspy i've always this bug so yes that's not a temporary problem, i'll upload a zip of the dll folder of the game

**Comment by pikachuk** [comment]
it's now sent to the email

**Comment by TiberiumPY** [comment]
@pikachuk did you used last version of dnSpy? Could probably be https://github.com/0xd4d/dnSpy/issues/174

**Comment by TiberiumPY** [comment]
@pikachuk if you're trying to edit unity3d assemblies, download latest beta of dnSpy and everything will be fine :)

**Comment by 0xd4d** [comment]
It's not #174, this assembly has two mscorlib refs:

```C#
// mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
```

Roslyn gets confused so we need to pick one over the other.

**Comment by TiberiumPY** [comment]
@0xd4d what's the name of the DLL? Assembly-CSharp.dll ?

**Comment by TiberiumPY** [comment]
@0xd4d your message in #174:
"Seems like Roslyn doesn't like when the assemblies contain references to two or more core libraries (mscorlib 2.0.0.0 and 2.0.5.0)"

**Comment by 0xd4d** [comment]
Well, seems like adding the desktop assembly comparer wasn't enough to fix all the cases. ;)

**Comment by 0xd4d** [comment]
I've checked the original file now, it does not contain multiple mscorlib references.

What did you do to get multiple mscorlib references? I compiled a new method and saved the file and couldn't reproduce it.

**Comment by pikachuk** [comment]
i don't know i just modified a script in unityscript, i've modified homedarkness added a IEnumerator to load a video with a coroutine nothing more

**Comment by pikachuk** [comment]
before this bug didn't appear it's only from some days when i try to modify the files
i think that it's probably a part of the IEnumerator problem in that case

**Comment by pikachuk** [comment]
because i never tried to add IEnumerators before

**Comment by 0xd4d** [comment]
It's difficult to fix something you can't reproduce. ;)

**Comment by 0xd4d** [comment]
I've had a look at the new file you emailed me (#293). It has two mscorlib references, but the duplicate desktop 2.0 reference is never referenced by any code.

Are you sure you only used dnSpy to create that file? dnlib doesn't add unnecessary assembly references unless you force it to do so some other way.

**Comment by 0xd4d** [comment]
A quick way to fix your file would be to force save it in dnSpy. The resulting file should have no duplicate references. Then reload all files or restart dnSpy.

**Comment by 0xd4d** [comment]
This appears to be caused by some other tool.

- The assembly is bigger than the one created by dnSpy (dnlib)
- dnSpy (dnlib) doesn't add unnecessary assembly references
