### ISSUE TITLE
Bug: dnSpy locks dll's

### ISSUE THREAD

**Issue by SlowLogicBoy** [0xd4d/dnSpy#265]
when I open dll with dnSpy, even if I don't modify or compile them, dnSpy locks them and Visual Studio compiler can't override them.
Visual Studio 2015 Professional - Running as an Administrator
dnSpy - running as regular user.

**Comment by 0xd4d** [comment]
You probably need to disable memory mapped I/O in the settings.

**Comment by SlowLogicBoy** [comment]
Thanks that helped.
