### ISSUE TITLE
Feature: Assembly Explorer - remove duplicates

### ISSUE THREAD

**Issue by SlowLogicBoy** [0xd4d/dnSpy#267]
Remove duplicates from assembly explorer. (useful when debugging from memory and dragging multiple files multiple times)

**Comment by 0xd4d** [comment]
Is it just the in-memory files you want to close? Perhaps all in-memory files that don't belong to the current debugging session.

**Comment by SlowLogicBoy** [comment]
I don't know exact details but there are times when I see multiple assemblies with same file path, those came up while debugging from memory, however I don't know if it is possible to add duplicate otherwise.

**Comment by 0xd4d** [comment]
A file on disk is always considered different from one in memory (because the one in memory could be decrypted or modified in other ways). Also, two in-memory modules from different debugging sessions are also considered different. I think what you want is to close all old in-memory modules.

**Comment by SlowLogicBoy** [comment]
Yes, you might be right

**Comment by 0xd4d** [comment]
About the diff, yes could be useful but it's already possible with external tools:

- Decompile assembly A
- Decompile assembly B, and use the same project GUID as A used
- Use `diff -u3 -r -N /path/to/old/ /path/to/new` to get the diff

**Comment by TiberiumPY** [comment]
@0xd4d are you using dnSpy on Linux?

**Comment by 0xd4d** [comment]
The GUI is for Windows only, so no.
