### ISSUE TITLE
Hide From Debugger support

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#27]
Taking into account that .net has very basic debugging detection, 
nevertheless it has it, e.g.: http://prntscr.com/84u172
and it stops the mind from moving forward ;)
are there any chances to add support for anti debug-detection?

I bet that would be the first market ever solution!

**Comment by 0xd4d** [comment]
Fixing the debugger isn't prioritized at the moment. I haven't even decided whether I'll keep it or rewrite it.

I do accept pull requests so if you or anyone else want to add a fix, do so. :)

**Comment by 0xd4d** [comment]
Fixed in latest code.
