### ISSUE TITLE
[question] How to build the CLI on Mac OS?

### ISSUE THREAD

**Issue by rraallvv** [0xd4d/dnSpy#272]
I'm getting the following errors in Xamarin Studio when building dnSpy.sln

![screen shot 2016-11-03 at 7 13 38 pm](https://cloud.githubusercontent.com/assets/1840524/19988983/d949aef0-a1f9-11e6-9121-016bd1bba6ed.png)

**Comment by 0xd4d** [comment]
Only dnSpy.Console and the decompiler can be built, the other projects are Windows only since they require WPF.

I'll update the Wiki with non-Windows build instructions later.

**Comment by rraallvv** [comment]
@0xd4d thanks for the info, I really appreciate it.
