### ISSUE TITLE
Error trying to compile dnSpy (nuget)

### ISSUE THREAD

**Issue by TiberiumPY** [0xd4d/dnSpy#274]
While compiling dnSpy from source (all submodules are inited)

> Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
System.ValueTuple 4.0.0-rc3-24212-01 is not compatible with .NETFramework,Version=v4.6.
Some packages are not compatible with .NETFramework,Version=v4.6.
System.ValueTuple 4.0.0-rc3-24212-01 is not compatible with .NETFramework,Version=v4.6 (win).
Some packages are not compatible with .NETFramework,Version=v4.6 (win).
NuGet package restore failed.

**Comment by SlowLogicBoy** [comment]
Have you updated your Visual Studio?

**Comment by TiberiumPY** [comment]
@SlowLogicBoy oh, forgot about it. I have Visual Studio 2015 update 1

**Comment by SlowLogicBoy** [comment]
I don't know if this will help, but I have Update 3 I think and everything is working fine.

**Comment by 0xd4d** [comment]
Did you get this working or did you accidentally click `Close`? I also use VS2015 Update 3 and haven't tested to compile it with any other version.
