### ISSUE TITLE
Cannot compile dnSpy-3.0.0-beta to a working build.

### ISSUE THREAD

**Issue by dagriderx** [0xd4d/dnSpy#275]
![dnspy](https://cloud.githubusercontent.com/assets/23298380/20040797/b9783b6c-a412-11e6-9479-78f084491b91.png)
New to Github, and learning to code,
First issue, I can't get dnSpy to compile to .exe

Using Visual Basic Community 15.
Have got a lot of reference issues, 
and dnSpy.exe does not exist.

What am I doing wrong?

Does someone have a compiled version?

FYI, I downloaded dnSpy-3.0.0-beta
.....Think it's missing a lot of files.

**Comment by cardinalwang** [comment]
It`s the same to me, it seems that we have to download the remaining lost files from the CODE page

**Comment by dagriderx** [comment]
I downloaded dnSpy-master (which should be from CODE page) looks like it's still missing those files, I think 2.0 had them.

**Comment by SlowLogicBoy** [comment]
[Building-dnSpy](https://github.com/0xd4d/dnSpy/wiki/Building-dnSpy)
open dnSpy.sln
build solution
everything works.

**Comment by 0xd4d** [comment]
If you can't build it, I suggest you wait a day. I'll release 3.0 tomorrow, Nov 8, and the download page will have a link to the 3.0 binaries.

**Comment by cardinalwang** [comment]
![oid](https://cloud.githubusercontent.com/assets/23306369/20054314/5bfca5b2-a517-11e6-89d3-5f845d64892f.png)
@dagriderx  download only download part of it, 
use "open in desktop" to download tool  and next time you click the same button will clone  it full.

It helps for me.

**Comment by TiberiumPY** [comment]
@cardinalwang no, it's not a good approach.
better to git clone and init all submodules

**Comment by cardinalwang** [comment]
@0xd4d TKS, This program is really a great work.  it solves a lot of problem for me.

**Comment by CreateAndInject** [comment]
@cardinalwang 
"use "open in desktop" to download tool"


These's nothing when clicking "open in desktop", does it because of great firewall of china?

**Comment by cardinalwang** [comment]
It`s possible firewall or browser problem, so please wait until 0xd4d release a compiled binary today, an easier and safely way.
or I can send you via wechat  (ID: wangxiaobin5393 ) from Taiwan. if you really need the whole source code.

**Comment by 0xd4d** [comment]
https://github.com/0xd4d/dnSpy/releases
