### ISSUE TITLE
c# support is missing instead there --- how do i add c# support?

### ISSUE THREAD

**Issue by friuns2** [0xd4d/dnSpy#277]
c# support is missing instead there --- how do i add c# support?
http://i.imgur.com/ksZT5EO.png

**Comment by SlowLogicBoy** [comment]
You didn't build everything. Try building whole solution.

**Comment by 0xd4d** [comment]
Yes, that's a clear sign that at least the decompiler extension wasn't built. ;)

**Comment by friuns2** [comment]
thanks working now
