### ISSUE TITLE
Class Compiling with hidden compiler generated classes

### ISSUE THREAD

**Issue by TheProxyRE** [0xd4d/dnSpy#279]
![image](https://cloud.githubusercontent.com/assets/12687236/20247992/0346d8ca-a9db-11e6-9cb0-4601d9500b7e.png)

Everything works when you disable show hidden compiler generated classes tho but still those could be important

**Comment by 0xd4d** [comment]
It's by design, it uses the current decompiler settings. You can remove the garbage and press F6 or you can disable the option before you edit a method.
