### ISSUE TITLE
debug no see local var and no to add to watch

### ISSUE THREAD

**Issue by richs2008** [0xd4d/dnSpy#281]
![locvarnotin](https://cloud.githubusercontent.com/assets/8036268/20288808/ff3fe7f8-ab10-11e6-89d9-8c247f5ad110.GIF)

**Comment by 0xd4d** [comment]
Seems like you have attached to the process. If possible, start it normally. If it's not possible, read this: https://msdn.microsoft.com/en-us/library/9dd8z24x(v=vs.110).aspx
