### ISSUE TITLE
Getting Stackoverflow upon analyzing new strands of Malware?

### ISSUE THREAD

**Issue by AxDSan** [0xd4d/dnSpy#282]
**Issue**: When I try to analyze a Malware in dnSpy 3.0 RC and upon switching to any language (C# or VB) dnSpy crashes with an EXCEPTION_STACK_OVERFLOW error, it's worth mentioning I don't have the same problem when only showing IL code.

**How to reproduce**: Download Malware [Sample](https://mega.nz/#!0d5hlZKL)(Key has been removed for security reasons) _[CAUTION! - Even though it was a demo-sample from a crypter, it is advised to run it inside a VM or Sandboxed, sample does not "calls home" (connects to the internet) and the payload settings does not uses "startup" options.]_, load Malware Sample in dnSpy 3.0 latest RC, and then enter the entrypoint, switch to any language C# or VB and your dnSpy will crash with EXCEPTION_STACK_OVERFLOW, re-do everything this time load with IL code and dnSpy will not crash.

P.S. Hope I can share links here, even further a malware link, even though it's a dormant malware, since it's just a sample, the payload it's just a messagebox that loads and doesn't do anything harmful to the system it's being deployed, still, I have removed the key needed to download the sample, 0xd4d, or any other collaborator please get in touch with me so I can share privately the Key.

**Comment by 0xd4d** [comment]
You can email me the password.

**Comment by AxDSan** [comment]
@0xd4d email sent!

**Comment by 0xd4d** [comment]
OK, I can reproduce it with the 64-bit version of dnSpy.
