### ISSUE TITLE
Cannot re-recompile modified source code!

### ISSUE THREAD

**Issue by lf94** [0xd4d/dnSpy#283]
When I go Menu -> Edit Method, I can change source code like normal. When I go to do it again, it fails on generics. Here is the line it fails at:

Func<string, bool> <>9__0;

And the error:
Error	CS1525	Invalid expression term 'string'	main.cs	52

dnSpy also reports errors on <>'s.

**Comment by 0xd4d** [comment]
Seems like the code uses a lambda. Roslyn generates different code which confuses the decompiler. There's already an issue that tracks improving Roslyn support, see #118
