### ISSUE TITLE
Errors about decompiling local variables and default for switch-cases

### ISSUE THREAD

**Issue by gyrodrill** [0xd4d/dnSpy#284]
```C#
switch (k)
{
	case 0:
	{
		IL_3D:
		bool flag2 = false;
		int maxValue = num3;
		break;
	}
	case 1:
	{
		bool flag2 = true;
		int maxValue = num;
		break;
	}
	case 2:
	{
		bool flag2 = false;
		int maxValue = num3;
		break;
	}
}
goto IL_3D;
IL_77:

A few lines of code...

int maxValue;
bool flag2;
```

It seems that the first label IL_3D should be default for this switch-case, and the local variable maxValue and flag2 are decleared many times.
Is it possible to automatically move the declear statment to the place where it is before all other using of this value, and turn the goto label into switch() { default: }?

This issue both appears in ILSpy and dnSpy.

**Comment by 0xd4d** [comment]
It's a bug in the decompiler, you can report it to ILSpy since it's their decompiler engine that dnSpy uses.

No decompiler is perfect, you could try another one and see if one of them produces better code for that method.
