### ISSUE TITLE
Add-on: Export meta-information to IDAPro

### ISSUE THREAD

**Issue by grimaz** [0xd4d/dnSpy#286]
Hello,
is it possible to add "Export..." feature for entries like
// Token: 0x04000009 RID: 2001 RVA: 0x00410010 File Offset: 0x00410010
public static method __m2mep@??_E?$AutoPtrArray@VStump@Builder@MyConstruction@@@MyBase@@$$FUEAAPEAXI@Z;
as .IDC or python script to import to IDA Pro?

BTW, may be some functions name undecoration to make them pretty reading?

**Comment by 0xd4d** [comment]
IDA Pro can already read .NET Metadata so it should already be able to show you that.

**Comment by grimaz** [comment]
When you reversing mixed assembly in native code, you do not have any .net meta information.
The information in managed part often has names and parameters of native functions which can be applied to native part instead of standard sub_xxxxx().

**Comment by 0xd4d** [comment]
Sounds like IDA Pro needs a new feature, have you asked Hex-Rays?

**Comment by grimaz** [comment]
It would be 'mission impossible' request )))

**Comment by 0xd4d** [comment]
This is an IDA Pro feature request, but I'll keep it open in case someone wants to add the code or write an extension to do it.

**Comment by 0xd4d** [comment]
It's not something I plan on doing. You could write an extension or have someone else do it for you.
