### ISSUE TITLE
Prevent code from detecting the debugger

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#288]
AFAIK dnSpy has some anti-debugging detection mechanism built-in
eg: System.Diagnostics.Debugger.IsAttached   returns false  in runtime during debug session,
but of course there are other means that might detect dnSpy
one of very simple is kernel32.dll::IsDebuggerPresent  API

are there any ways to instruct dnSpy to intercept this as well?
For the moment the concern is only regarding mentioned one....

Thank you

**Comment by TiberiumPY** [comment]
You can remove this checks from app itself using dnSpy :)

**Comment by greenozon** [comment]
agree, but you know, there are tons of these spread wide thoughought all the assemblies...
Generic mature aproach would be just great :)
I've already inspected how teh managed debugger was hidden in dnSpy - it's inside the module DisableSystemDebuggerDetection but its .NET based, it searches and works differently...
the thing I've raised is up to native old good dbg detection, so I assume one need to do the LoadLibrary/GPA then do the magic :)

**Comment by 0xd4d** [comment]
You can use eg. dnlib to replace all method calls with ldc.i4.0 or whatever return value indicates 'no debugger'.

**Comment by 0xd4d** [comment]
There are lots of ways to detect a debugger, dnSpy by default only disables managed debugger detection by patching calls to eg. Debugger.IsAttached.

A quick google search revealed: http://pferrie.host22.com/papers/antidebug.pdf

But I think dnSpy should at least prevent common debugger detections, so this could be improved.

**Comment by greenozon** [comment]
Thank you for your answers, @0xd4d 
Agree, there hundred +1 dbg detection tricks, but  patching each time the bodies is a bit time consuming...  I believe once a very basic example will be done - e.g. kernel32.dll::IsDebuggerPresent   I guess the rest would be a matter of  DIY (do it yourself) :)  Also I foresee this support as a separate plugin(s), I know you love this apprach, so the rest would just write their  code and solve the task on a high level generic approach.

**Comment by ViRb3** [comment]
Would the best approach be a plugin that hooks various anti-functions?

**Comment by 0xd4d** [comment]
@ViRb3: Yes just hooking various funcs that can be used to detect the debugger should be enough. There's no need to make it work 100% against any possible debugger-detection code.

**Comment by greenozon** [comment]
hi @0xd4d 
I'm trying to design some primitive native WinAPI  patching (eg kernel32.dll::IsDebuggerPresent) and during debugging I"ve colllected some questions to you.

am I right supposing that the good location to do this work is the 
dndbg.Engine::DisableSystemDebuggerDetection::Initialize() method that has the 1st input argument 
CorProcess process (btw, is it a child process that dnSpy is going to debug?)

Now, at the end of this method I'm calling my exported function from built native dll and passing the argument as value of process.Handle
I'm using it inside the native dll and passing it to diff WinAPI as well as  patching the debugger detection APIs, etc (using your approach I've seen in your .cs code)
but, for some reason after such an approch dnSpy refuses to stop on breakpoints and end app just runs...)

So main question is - is it correct to use the value of process.Handle in some native dll and pass it to WinAPIs?

Thank you.

PS I bet simpler and faster would be to do the hot patching of WinAPI inside the .cs module, but I've chosen the approach with external dll as more flexible..

**Comment by greenozon** [comment]
I've figured out that the issue started to happen after the WriteProcessMemory was called from my dll on the process handle passed from the dnSpy..
GetLastError is 0 (OK) and num of bts written is eq to the input len...

**Comment by 0xd4d** [comment]
If it's in the same process as dnSpy it should work. If you use it from some other process, it will probably fail. Get the pid and open a new handle.

You should be able to do this in C#, and it's the preferred programming language in dnSpy.

**Comment by greenozon** [comment]
Thanks for your reply, I've tried your suggestion, but it did not help...

during analysis I came to conclusion that native external dll is not that good idea to be called from dnSpy.... why? depending on OS I need to have two copies- x32 & x64 which of course is not nice...

Next thing I've tried is to do the same patching inside this method of dnSpy's class DisableSystemDebuggerDetection:

bool Initialize(CorProcess process, string debuggeeVersion)

I've added very basic code:

  //+
                IntPtr hModuleKernel32 = LoadLibrary("kernel32.dll");
                ulong pFunc = (ulong)GetProcAddress(hModuleKernel32, "IsDebuggerPresent");
                error |= !WriteReturnFalse(process, pFunc);
 //~

and these as well - 

        [DllImport("kernel32", CharSet = CharSet.Ansi, SetLastError = true)]
        public static extern IntPtr LoadLibrary([In, MarshalAs(UnmanagedType.LPStr)] string lpFileName);

        [DllImport("kernel32", CharSet = CharSet.Ansi, SetLastError = true)]
        public static extern IntPtr GetProcAddress([In] IntPtr hModule, [In, MarshalAs(UnmanagedType.LPStr)] string lpProcName);

I've observed right the same behaviour as with native x32 dll - dnSpy refused to stop on any breakpoint and this patch did not do the required - IsDebuggerPresent still returns the true..

**Comment by 0xd4d** [comment]
It could be that the CLR debugger uses that API as well and if it returns false, it doesn't send any events to the managed debugger. The only solution to fix that would be to check the stack, if it's within clr.dll/mscorwks.dll, pass through to original code, else return false.

**Comment by 0xd4d** [comment]
Diff of coreclr

```diff
$ grep -r IsDebuggerPresent
coreclr/hosts/coreconsole/coreconsole.cpp:        if(!IsDebuggerPresent())
coreclr/hosts/coreconsole/coreconsole.cpp:            if (IsDebuggerPresent())
coreclr/hosts/corerun/corerun.cpp:        if(!IsDebuggerPresent())
coreclr/hosts/corerun/corerun.cpp:            if (IsDebuggerPresent())
debug/di/windowspipeline.cpp:            BOOL fIsDebuggerPresent = FALSE;
debug/di/windowspipeline.cpp:            if (SUCCEEDED(IsRemoteDebuggerPresent(processId, &fIsDebuggerPresent)))
debug/di/windowspipeline.cpp:                if (fIsDebuggerPresent)
debug/ee/debugger.cpp:    if (!IsDebuggerPresent())
debug/ee/debugger.cpp:        else if (!CORDebuggerAttached() && IsDebuggerPresent())
debug/ee/debugger.cpp:    if (!IsDebuggerPresent())
debug/ee/debugger.cpp:    if (IsDebuggerPresent())
debug/ee/debugger.cpp:        if(IsDebuggerPresent())
debug/ee/debugger.cpp:    else if (IsDebuggerPresent())
dlls/mscordac/mscordac_unixexports.src:PAL_IsDebuggerPresent
inc/winwrap.h:    if (IsDebuggerPresent())
jit/error.h:        if (IsDebuggerPresent())                                                                                       \
pal/inc/pal.h:#define IsDebuggerPresent PAL_IsDebuggerPresent
pal/inc/pal.h:PAL_IsDebuggerPresent(VOID);
pal/src/exception/machexception.cpp:            if (PAL_IsDebuggerPresent())
pal/src/init/pal.cpp:PAL_IsDebuggerPresent
pal/src/init/pal.cpp:PAL_IsDebuggerPresent()
ToolBox/SOS/Strike/gcroot.cpp:    do { if (!(expr) ) { ExtErr("_ASSERTE fired:\n\t%s\n", #expr); if (IsDebuggerPresent()) DebugBreak(); } } while (0)
ToolBox/SOS/Strike/util.h:    do { if (!(expr) ) { ExtErr("_ASSERTE fired:\n\t%s\n", #expr); if (IsDebuggerPresent()) DebugBreak(); } } while (0)
ToolBox/superpmi/superpmi/jitdebugger.cpp:        if (IsDebuggerPresent())
ToolBox/superpmi/superpmi-shared/spmiutil.cpp:    if (IsDebuggerPresent())
utilcode/check.cpp:    if (IsInAssert() && IsDebuggerPresent())
utilcode/debug.cpp:        if (IsDebuggerPresent())
vm/appdomain.cpp:            // We cannot use IsDebuggerPresent() in the condition below because the
vm/comsynchronizable.cpp:        // We cannot use IsDebuggerPresent() in the condition below because the
vm/debugdebugger.cpp:    else if (IsDebuggerPresent())
vm/eeconfig.h:            if (IsDebuggerPresent()) DebugBreak();                      \
vm/eepolicy.cpp:    if (IsDebuggerPresent())
vm/eventreporter.cpp:    if ((CORDebuggerAttached() || IsDebuggerPresent())
vm/excep.cpp:    // scenario CORDebuggerAttached() will be TRUE, but IsDebuggerPresent() will be FALSE because from OS
vm/excep.cpp:    BOOL alreadyDebugging     = CORDebuggerAttached() || IsDebuggerPresent();
vm/excep.cpp:            if (IsDebuggerPresent())
vm/excep.cpp:    // a failfast error, CORDebuggerAttached() will be TRUE, but IsDebuggerPresent() will be FALSE.
vm/excep.cpp:    // If IsDebuggerPresent() is FALSE, do not try to notify the deubgger.
vm/excep.cpp:    else if (CORDebuggerAttached() && IsDebuggerPresent())
vm/excep.cpp:                if (!CORDebuggerAttached() && IsDebuggerPresent())
vm/excep.cpp:                    BOOL debuggerPresentBeforeAssert = IsDebuggerPresent();
vm/excep.cpp:                    if (!debuggerPresentBeforeAssert && IsDebuggerPresent())
vm/finalizerthread.cpp:        // We cannot use IsDebuggerPresent() in the condition below because the
vm/i386/gmsx86.cpp:                if (IsDebuggerPresent())
vm/mda.cpp:    if (IsDebuggerPresent())
vm/pefile.cpp:    BOOL fOutputToDebugger = (level == LL_ERROR && IsDebuggerPresent());
vm/pefile.cpp:    if (   ((level == LL_ERROR) && IsDebuggerPresent())
vm/pefile.cpp:    BOOL fOutputToDebugger = (level == LL_ERROR && IsDebuggerPresent());
vm/stackprobe.cpp:    //if (IsDebuggerPresent())
vm/stubmgr.cpp:    if (IsDebuggerPresent())
vm/util.cpp:    if (IsDebuggerPresent() && !CORDebuggerAttached())
```

**Comment by greenozon** [comment]
under this
>The only solution to fix that would be to check the stack, if it's within clr.dll/mscorwks.dll, pass through to original code, else return false.

you meant that one has to do that logic in the  changed bytes of (for example) IsDebuggerPresent() API?
that would definitely not be a 3 bytes as in your patched bytes...... I wonder if there would be that amount of space in orig API...

**Comment by ViRb3** [comment]
@greenozon You can use the 'trampoline' approach:
Overwrite as many bytes as needed in the beginning of IsDebuggerPresent() to jump to a 'trampoline function'. That function will contain the original bytes you replaced (not to break functionality), and then a jump to your detour function, which contains further logic like checking the stack and deciding whether to tamper the return value or not. Some great resources are available online. If you publish your source I may be able to take a look and help you in the next days.

**Comment by greenozon** [comment]
@ViRb3  thanks for commeting out!
Well, my approach is rather simple and straighforward.... as I wrote before - I switched to chaning the dnSpy sources, mainly this area:

namespace dndbg.Engine 
   public sealed class DisableSystemDebuggerDetection 

then at the end of this method:
bool Initialize(CorProcess process, string debuggeeVersion)

I've added this code:

                //+
                hModuleKernel32 = LoadLibrary("kernel32.dll");
                System.Diagnostics.Debugger.Log(0, "info1", Convert.ToString((int)hModuleKernel32));

                ulong pFunc = (ulong)GetProcAddress(hModuleKernel32, "IsDebuggerPresent");
                System.Diagnostics.Debugger.Log(0, "info2", Convert.ToString(pFunc));
                error |= !WriteReturnFalse(process, pFunc);
                //~


as you see I've reused the author's method WriteReturnFalse()

Now, I'm wondering how one would detect the upper layer that called the IsDebuggerPresent() API
as far as I understand for this you need to know the VA of the  CLR debugger module and then inspect the stack and compare each value with the CLR dbg range?  next question would be - how many records do you have to inspect. Next question - what if this is 64 bit process, then you have to operate wtih RSP/etc registers, not the 32 bits ones..

anyway, thank you for your interest, appreciating it very much.

**Comment by greenozon** [comment]
@0xd4d  Taking into account  that v4.0.0 was just released (great stuff!)
is it a good time to get back to the anti-debugging subject?
Specifically would be great to add support for hiding from old good basic native IsDebuggerPresent...

thanks!

**Comment by paulnd** [comment]
> Specifically would be great to add support for hiding from old good basic native IsDebuggerPresent...

+1 please

**Comment by 0xd4d** [comment]
@greenozon @paul You can write an extension to do it.

**Comment by paulnd** [comment]
Thanks for the suggestion of an extension but unfortunately my programming skills are not yet sufficient to this. 

I'll be very grateful if someone with the skills may consider this as a project?

**Comment by greenozon** [comment]
@0xd4d    
do you have some good example of dnSpy extension?
what is the API, in/out/rules/etc

thx

**Comment by paulnd** [comment]
There are some examples in the wiki

https://github.com/0xd4d/dnSpy/wiki/Extensions
