### ISSUE TITLE
Debugger issue detected

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#289]
While debugging some .net code (on dnSpy v3.0.0 release) I've got the following error:

http://prntscr.com/dc26yr

after it app closes.

PS the app was in touch by Confuser

**Comment by 0xd4d** [comment]
Email me the file or the ConfuserEx settings file used to generate it and steps on how to reproduce it.

**Comment by greenozon** [comment]
uploaded
https://www.sendspace.com/file/4dr8rh
https://www.sendspace.com/delete/4dr8rh/6c261a9837ea2d6b602581ddee9bd16f
pls del after get

there is one more issue - usually dnSpy stops on module .cctor() or EP  on a debug start,
but in this case smth strange happens - it stops, but no code highlighted (you could see where it stopped only if you switch to the IL view mode)...

**Comment by 0xd4d** [comment]
> there is one more issue - usually dnSpy stops on module .cctor() or EP on a debug start,
but in this case smth strange happens - it stops, but no code highlighted (you could see where it stopped only if you switch to the IL view mode)...

Go to settings and search for 'remove empty default constructors' and make sure it's unchecked. You could also try enabling 'show hidden compiler generated types and methods'
