### ISSUE TITLE
Decompiling Async Methods

### ISSUE THREAD

**Issue by cawk** [0xd4d/dnSpy#290]
when decompiling async methods dnspy doesnt like to show the correct code
for example
https://gyazo.com/a41b23ecff8027317c0e2e09b447b95f
where the real code should be 
https://gyazo.com/70ab4450e5db5245d97f48d09a2a5217

thanks in advance if you could fix this

**Comment by 0xd4d** [comment]
It's Roslyn code. #118 tracks this issue, so I'm closing this.
