### ISSUE TITLE
Question: String.Join List of int won't compile?

### ISSUE THREAD

**Issue by TheDistur** [0xd4d/dnSpy#291]
Probably out of my depth here, but trying to use [this](https://msdn.microsoft.com/en-us/library/dd992421.aspx) while editing a method but it says can't convert int to string.  Does the compiler not use .Net 4.0 or am I missing something simple? Thank you.

**Comment by 0xd4d** [comment]
Seems like your assembly is a .NET 2.0-3.5 assembly in which case that method doesn't exist. There are other string.Join methods you could use.

**Comment by TheDistur** [comment]
Ah. Yea I worked around it. Makes sense you'd have to go with the assembly's version. That explains it. Thank you!
