### ISSUE TITLE
Feature: allow name aliases

### ISSUE THREAD

**Issue by grimaz** [0xd4d/dnSpy#292]
Is it possible to add ability to "rename" the local variables (and other entities as well without meta information changes)?
For example:
int num3 = 0;
if (num3 > ...) {}

Press N (IDA way) and set alias for num3 as billNumber. dnSpy can store such mappings per project in xml in the same dir. Then show billNumber instead of num3 in the specified method.

**Comment by SlowLogicBoy** [comment]
#266 ?

**Comment by grimaz** [comment]
Exactly. Did not see it before. Thank you!
