### ISSUE TITLE
multiple assemblies bug still happening

### ISSUE THREAD

**Issue by pikachuk** [0xd4d/dnSpy#293]
The bug that i talked about before seems to really be a bug and not an error by me because modifying the dll of yandere sim can randomly make appear this error, even now i tried to modify the file since a clean dll, a totally new, and i've redownloaded dnspy but http://image.noelshack.com/fichiers/2016/48/1480504464-sans-titre-2.jpg
i still haven't imported any dll and my only change is adding an instantiate to the actual script

**Comment by 0xd4d** [comment]
Could you email it to me? de4dot@gmail.com

**Comment by 0xd4d** [comment]
I'll close this since it's identical to your original issue which is still open: #263

**Comment by 0xd4d** [comment]
See #263 for a way to fix that file (force saving it and restarting dnSpy)
