### ISSUE TITLE
System.NotSupportedException: ICSharpCode.Decompiler.ILAst.ILFixedStatement

### ISSUE THREAD

**Issue by kissstudio** [0xd4d/dnSpy#296]
meet the error when spy a method.

I was added a if statement , is it right?.

![qq 20161206225114](https://cloud.githubusercontent.com/assets/2771647/20929946/bc9609e4-bc06-11e6-9a02-b1bc0eb49a7f.png)

**Comment by kissstudio** [comment]
the file is here.
for the method, see m7wlCalQyGd6SCnMUP.gKqWGxVN5TpnSfBOO1.w2IJEISndF()
[SysFrame.zip](https://github.com/0xd4d/dnSpy/files/634166/SysFrame.zip)

**Comment by 0xd4d** [comment]
I had a quick look, I think it should first check all Initializers instead of BodyBlock? In your binary, it doesn't matter though.

I think you'll get a better answer if you ask the ILSpy developers.

BTW, the file is obfuscated, is there a reason you don't deobfuscate it?

**Comment by kissstudio** [comment]
thanks your advice , i m not good at it, I will submit a question to the official ICSharpCode.Decompiler issues page.
