### ISSUE TITLE
Loaded assembly is locked

### ISSUE THREAD

**Issue by yck1509** [0xd4d/dnSpy#3]
The loaded file is locked on disk, so it cannot be write to while dnSpy loaded it. Another problem would be dnSpy does not dispose the loaded modules, so there would be no reliable way to know when a loaded file would be unlocked after removing from dnSpy.

**Comment by li0nsar3c00l** [comment]
just wanted to report it as well

**Comment by 0xd4d** [comment]
I just pushed something that probably fixes it.

There's an option to disable it either globally or you can right-click a file and disable it.

**Comment by yck1509** [comment]
It is fixed now.
