### ISSUE TITLE
pointers in parameter cannot be shown

### ISSUE THREAD

**Issue by cobrce** [0xd4d/dnSpy#30]
when trying to see the value of a ptr (or any other parameter) it says  "Identifier "ptr" not found in this context"
the function looks like follow :
private unsafe static void FunctionName(ref byte* ptr, byte* ptr2, byte* ptr3)
{
 ...
}

**Comment by 0xd4d** [comment]
I can't reproduce it.

**Comment by 0xd4d** [comment]
Closed, can't reproduce, inactive, old debugger.
