### ISSUE TITLE
Option to create properties and events with backing methods and fields automatically

### ISSUE THREAD

**Issue by maritaria** [0xd4d/dnSpy#300]
*Suggestion issue*

Add options for creating properties & events with basic backing fields and accessors.

I recently started using this tool and tried to add some properties and events to an existing class. I noticed there wasn't a way to create properties with a backing field and standard get/set methods generated along with them. Same for events.

I feel this would be more userfriendly as it is much easier to edit/remove get/set/add/remove methods from properties/events than to add them all manually.

PS: Awesome tool; great work :)

**Comment by 0xd4d** [comment]
The 'create property' command only adds the property and nothing else.

It's much easier if you add extra methods/properties/events/fields by choosing `edit method (C#)` or `edit class (C#)`. Even if you just edit a method, it will add any new fields, properties, methods, classes, etc that it finds when you press Compile.

**Comment by 0xd4d** [comment]
See also #301
