### ISSUE TITLE
Add `Go to the C# code or IL code` command in hex editor

### ISSUE THREAD

**Issue by gagmeng** [0xd4d/dnSpy#303]
When we analyze other people's patch files,  the modify points can be easily positioned in dnspy's hex editor by the command “go to offset”. Is it possible to add a command "go to the C# code or IL code" in the right-click menu of hex editor window that jumps from the hex editor fixed offset to the corresponding IL code or C# code?

**Comment by 0xd4d** [comment]
Fixed in master, use F12 in hex editor.

**Comment by gagmeng** [comment]
Got it, thanks.
