### ISSUE TITLE
Search option suggestion

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#304]
Usually, we will search strings/types/memebers, if I want to search a string, I must scroll to the end
This order may be better:
Constant
All of the below
Type
Member
Method
Field
........

**Comment by 0xd4d** [comment]
There are keyboard shortcuts for the most useful search types:

https://github.com/0xd4d/dnSpy/blob/2860123bbc5c1422111818af49b355578ccf87e9/dnSpy/dnSpy/Search/SearchService.cs#L135
