### ISSUE TITLE
Obfuscated C# object names.

### ISSUE THREAD

**Issue by TiberiumPY** [0xd4d/dnSpy#307]
I have an obfuscated Unity3D assembly, method parameters or some method names looks like this:
"#=qaXocfeChbA$eDGSBPm_qRQ=="
![image](https://cloud.githubusercontent.com/assets/21169548/21152680/6ec4e5ce-c178-11e6-8f5d-cdc0842af0a0.png)
Can I still modify code without deobfuscating it? Because if I do it with de4dot, resulting .dll doesn't run well (e.g. you can't login in game)

**Comment by maritaria** [comment]
Unity does some weird stuff to initialize types from the assets. What I found is that adding new fields to types can cause problems. First only try making some static edits, this is one I used to test if it worked:

```
if (Input.KeyDown(KeyCode.P)) Application.Exit();
```
Add that to the update method of an behavior (replace P with button that has no action in-game).
If that works then that means you can succesfully edit the assembly, if not then let us know.

Assuming that worked, there is an approach to adding fields I haven't tested yet but maybe you can try it.
Make sure you use the option to "Preserve MD Tokens" after adding an instance field to something.
![Image](http://image.prntscr.com/image/af2350cff55849ab8da7d67b445ef063.png)

My theory is that it will keep the fields in the right order and positions; such that when unity loads it populates the fields correctly.

Let me know how that goes :)

**Comment by nkAlex** [comment]
You'll be fine editing anything in a class as long as you don't break Unity's serialization layout, i.e. add/remove serializable fields or change their order, or rename classes used in serialization. Serializable fields are any non-static **public** fields not marked with a **[NonSerialized]** attribute, or any non-static **public** or **private** fields marked with a **[SerializeField]** attribute.
As long as you don't rename/add/remove/reorder any of those types of fields in a class you're good to make any code changes, you can even compile a completely new assembly retaining source serialization structure, Unity won't care :)

**Comment by 0xd4d** [comment]
An obfuscator could have checks for modifications. Many obfuscators hard code metadata tokens, so what @maritaria said about preserving them could help. There are many other checks an obfuscator could add to an assembly to detect changes.

**Comment by 0xd4d** [comment]
BTW, here's the first link google shows when googling `unity serialization`: https://blogs.unity3d.com/2014/06/24/serialization-in-unity/ so as @nkAlex said, it could also be that you changed something so serialization failed.

**Comment by TiberiumPY** [comment]
@0xd4d I mean if I de-obfuscate assembly with de4dot, it doesn't work anymore.
And method names like "#=qaXocfeChbA$eDGSBPm_qRQ==" are not valid in dnSpy, but they're like this in assembly

**Comment by TiberiumPY** [comment]
@maritaria I simply can't modify any classes, if at least one method in them named like "#=qaXocfeChbA$eDGSBPm_qRQ==".

**Comment by TiberiumPY** [comment]
This is the link to the assembly (taken from Robocraft):
https://transfer.sh/IN49D/assembly-csharp.dll

**Comment by 0xd4d** [comment]
> And method names like "#=qaXocfeChbA$eDGSBPm_qRQ==" are not valid in dnSpy, but they're like this in assembly

See #165 or #231 

You could use the IL editor to edit such methods until this has been fixed.

**Comment by TiberiumPY** [comment]
@0xd4d interesting.... will you solve it in one month (just curious)?

**Comment by maritaria** [comment]
I think this problem originates from the C# compiler not accepting all IL valid tokens as valid C# tokens. Solving this would require a customized compiler.

**Comment by 0xd4d** [comment]
@TiberiumPY : there's no ETA, it'll be ready when it's ready.

Closing it, questions seem to have been answered.
