### ISSUE TITLE
Suggestion: Remember code after editing method in C#

### ISSUE THREAD

**Issue by maritaria** [0xd4d/dnSpy#309]
I find it frustrating when repeatedly editing a method that the code changes to something I'm not used to (especially after making a rather long switch-case and have it turn into a list of if-else's).
My suggestion is to add an option that embeds the original code that was compiled for a method and store it somewhere in the assembly. If that is not possible then even caching it for the duration of the application-lifetime would be a great improvement.

**Comment by 0xd4d** [comment]
The problem with caching it is that if you edit something else that the method depends on (eg. rename a method), the cached code wouldn't compile. dnSpy would then have to add very complex logic to track all changes that could affect the code and invalidate it that happened.

**Comment by 0xd4d** [comment]
No upvotes, no PR, and I don't need it -> closing it.
