### ISSUE TITLE
Feature Request: enable support for modification of local variables

### ISSUE THREAD

**Issue by xenocons** [0xd4d/dnSpy#31]
Hi,

It would be nice if we could modify the names of local variables, like which can be done for a method.

This will help when disassembling code that has been compiled with an obfuscator, or worse, VB!

**Comment by 0xd4d** [comment]
You can edit the method body and click the locals tab, where you can rename the locals. Save the file and make sure a PDB file is also created. The names of locals are stored in the PDB file, not the exe/dll.

**Comment by xenocons** [comment]
Aha! Thank you, sorry I forgot reply.
