### ISSUE TITLE
Inconsistent dialog questions

### ISSUE THREAD

**Issue by maritaria** [0xd4d/dnSpy#311]
Having an assembly open with unsaved edits, there is different behavior in the dialog questions asked in different scenarios:

- When removing the assembly from the assemblylist, answering **no** to the question means "**confirm**, dont save and continue"
- When closing the application, answering **no** to the question means "**cancel**, dont save, dont close app"
This struck me as inconsistent as I expected the same result in the second scenario as in the first.

My suggestion is to make the quesiton: "Save unsaved changes to {assemblyName}?" and have the buttons be: yes/no/cancel.

**Comment by SlowLogicBoy** [comment]
> My suggestion is to make the quesiton: "Save unsaved changes to {assemblyName}?" and have the buttons be: yes/no/cancel.

there might be mutiple unsaved assemblies

**Comment by maritaria** [comment]
@SlowLogicBoy yes, which is why i suggested to add the assembly name to the question.
Just checked the current behavior, which says "There are # unsaved files. Are you sure you want to exit?".
In which case the new question for closing the application could be "Save unsaved changes of # edited assemblies?".

My main point was that the answers have different meaning in the different scenarios.

**Comment by 0xd4d** [comment]
Fixed by #366
