### ISSUE TITLE
question: How to add an assembly reference to .NET dll?

### ISSUE THREAD

**Issue by TiberiumPY** [0xd4d/dnSpy#312]
Assume I have a Assembly-CSharp.dll, how can I add a reference to "IronPython.dll" to use it's methods in Assembly-CSharp.dll?
Is this possible?

**Comment by 0xd4d** [comment]
You just call the method or reference the type you need.

If you use the IL editor: make sure the assembly is in Assembly Explorer (or you can click on the Open icon when selecting a method or type and open the required assembly)

Code editor: click one of the icons to the right of the combo box to open from GAC or a file on disk, then you can use any type in the assembly.

**Comment by TiberiumPY** [comment]
@0xd4d so I need to write
"using IronPython" at the top of the code editor window?

**Comment by 0xd4d** [comment]
Yes, after you've added the reference to assembly, otherwise the compiler will complain about missing assembly.

**Comment by TiberiumPY** [comment]
@0xd4d was my bad. I assumed I need to add "using IronPython" but it was "using IronPython.Hosting;"

**Comment by TiberiumPY** [comment]
@0xd4d https://blogs.msdn.microsoft.com/charlie/2009/10/25/running-ironpython-scripts-from-a-c-4-0-program/

why it doesn't work for me?
Can this be because of a different .NET versions of .dll's ?
![image](https://cloud.githubusercontent.com/assets/21169548/21185043/28e09622-c220-11e6-850e-26082f551c1c.png)

**Comment by TiberiumPY** [comment]
@0xd4d I have all needed assemblies
![image](https://cloud.githubusercontent.com/assets/21169548/21185069/492bc866-c220-11e6-84c9-0d7fe5067647.png)

**Comment by TiberiumPY** [comment]
@0xd4d also there's IronPython.Hosting in IronPython's dll namespace
![image](https://cloud.githubusercontent.com/assets/21169548/21185201/c147eb90-c220-11e6-9d89-fd0d162ada69.png)

**Comment by TiberiumPY** [comment]
@0xd4d I got it to work other way:
merged IronPython into Assembly-CSharp.dll
saved and re-opened it..
And I can use IronPython namespace now

**Comment by TiberiumPY** [comment]
@0xd4d I'm so stupid, but I can't find it..

**Comment by 0xd4d** [comment]
Also, since you're editing a Unity assembly, you'll probably need the assembly that works with Unity since the one you use is probably compiled for .NET Framework.

**Comment by 0xd4d** [comment]
It's the icon next to "main.cs" in the first picture you posted above.

**Comment by TiberiumPY** [comment]
@0xd4d ah, nvm, got it, thanks!
