### ISSUE TITLE
Update analyzer to support assemblies

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#314]
Now, we can analyze type/member in dnSpy.

I hope dnSpy can analyze assembly like Reflector.

**Comment by 0xd4d** [comment]
Could you give some examples?

**Comment by CreateAndInject** [comment]
You can use Ctrl+R when the current selecteditem is an assembly in Reflector.
![image](https://cloud.githubusercontent.com/assets/2529999/21316389/716e3ca4-c63b-11e6-8b1d-dd2b63304f10.png)

**Comment by TiberiumPY** [comment]
@CreateAndInject RMB - analyze?

**Comment by maritaria** [comment]
Right-click something to do that; you can't do it on assembly, module or namespace level. Only on classes or deeper.
![](http://image.prntscr.com/image/6f6d210732c14271862de6bad9964cb4.png)

**Comment by 0xd4d** [comment]
No upvotes, no PR, and I don't need it -> closing it.
