### ISSUE TITLE
Decompiling assembly into IL?

### ISSUE THREAD

**Issue by minexew** [0xd4d/dnSpy#315]
First of all, I'd like to thank you for all your amazing work.

Now, it seems to me that dnSpy.Console either contains a bug, or something crucial is missing from the documentation. I've been trying to decompile a .NET executable into IL using the following command:
```
dnSpy.Console.exe -o dasm_il -l IL DemoApplication.exe
```
This, however, fails with `ERROR: Language IL doesn't support creating project files`.
I tried adding `--no-sln`, but that didn't change anything.
I thought maybe removing the `-o` argument would help (disassembling to stdout?), but that just throws `ERROR: Missing output directory`

Am I doing it wrong?

**Comment by 0xd4d** [comment]
The best tool to disassemble to IL is ILDASM. Open VS dev console and type ILDASM.

**Comment by minexew** [comment]
I guess I'll end up doing that, but what's wrong with the command above?

I'd still prefer using dnSpy because I can redistribute it per GPL terms, and it can be downloaded with a one-liner on any platform supported by Mono.

**Comment by 0xd4d** [comment]
To edit the text output, you'd need an IL assembler, and if you have one, you should already have an IL disassembler, which should be used to disassemble the assembly.

The IL output hasn't been tested to be 100% ILASM compatible so if you really have to edit .il files and can't use dnSpy's IL editor or C#/VB code editor, then you should use ILDASM/ILASM.
