### ISSUE TITLE
Templates for "Add Class (C#)..."

### ISSUE THREAD

**Issue by maritaria** [0xd4d/dnSpy#317]
When adding a class using "Add Class (C#)...", use a template that inserts something like:
```
namespace Selected.Namespace
{
	public class Class1
	{
	}
}
```
Where ```Class1``` is just a placeholder the user is supposed to change themselfs, but provides a compilable default. Also make sure to increment 1 in case ```Class1``` already exists (and repeat for 2, 3...).
As a setting, have the user specify a template they want to use. For example, someone who wants to have some default using statements would enter:
```
using System;
using UnityEngine;

namespace $namespace$
{
	public class $classname$
	{
	}
}
```
Where ```$namespace$``` is replaced by the user selected namespace.
Where ```$classname$``` is replaced by the generated ```Class#``` name.

Same idea can be applied to methods, properties, events, fields, etc.

**Comment by 0xd4d** [comment]
No upvotes, no PR, and I don't need it -> closing it.
