### ISSUE TITLE
Improve warning on type removal

### ISSUE THREAD

**Issue by maritaria** [0xd4d/dnSpy#319]
When removing a type from the assembly warn the user explicitly if there is code in the assembly that references it. Possibly async in the background and then updating the dialog message:

Initial: ```Checking for references in current assembly...```
Safe: ```Element can safely be removed...```
Unsafe: ```There are # references to this element in the current assembly...```

**Comment by 0xd4d** [comment]
It's not just the current assembly, it could be referenced from other assemblies, even assemblies not loaded in Assembly Explorer.

**Comment by maritaria** [comment]
@0xd4d yes, but I would considder those out of scope, references inside the same assembly should always resolve; my main issue is that the decompiler will from then on create errors when trying to decompile methods still referencing a deleted element.

**Comment by 0xd4d** [comment]
Looks like what you really want is a 'is this type / member' used feature so you can remove unwanted types/methods? I did a quick google search and it seems Mono.Linker can prune assemblies from unwanted code and types.

**Comment by maritaria** [comment]
@0xd4d I guess so, though now I need to do "analyse..." and manually remove the code. Though I don't know if I would actually use the feature you suggested because I don't know how it would fix the usages.

The issue I came accross was that I had some static code that was basically a util function for a single class. But I also used that function in another class, I forgot I had done that and this caused issues when trying to write the asm to disk after removal.

The feature I suggested would just do "analyse" in the background and give the warning if there are any results.

**Comment by 0xd4d** [comment]
Pretty much any normal-sized program contains unused methods and classes, I just wouldn't worry about a few extra methods or classes.

**Comment by maritaria** [comment]
Its because I was in progress of replacing the functionality with new code, but wanted to *safely* remove the old code first.

**Comment by 0xd4d** [comment]
No upvotes, no PR, and I don't need it -> closing it.
