### ISSUE TITLE
Can not show the content of some compiler-generated types

### ISSUE THREAD

**Issue by UlyssesWu** [0xd4d/dnSpy#32]
I have read #17 , but even with "Show Internal Types And Members" switched on, some compiler-generated types are still invisible, such as nested iterator classes generated by Unity (used by `StartCoroutine` method.)

Same as ILSpy, dnSpy can not show the detail of these nested compiler-generated iterator classes.
The class name here is unclickable. We can not see methods and variables in it, such as `MoveNext()`.
![dn](https://cloud.githubusercontent.com/assets/4312781/9598773/eb6cb8ba-50c0-11e5-9f09-90e69e5ce828.png)

JustDecompile is a bit better, although we can't see them at the treeview, we can still click the outer class and the code of nested classes will also be shown.
![jd](https://cloud.githubusercontent.com/assets/4312781/9598788/00008cde-50c1-11e5-9ffa-ce10676245d2.png)

Reflector is the best. It can display all compiler-generated types, just like other types.
![reflector](https://cloud.githubusercontent.com/assets/4312781/9598797/120ef280-50c1-11e5-8011-20fbf3808862.png)

**Comment by 0xd4d** [comment]
Options -> Decompiler -> Show hidden compiler generates types and members

The other one just shows non-hidden internal types and members.

**Comment by 0xd4d** [comment]
The "Show internal types and members" option is perhaps a little confusing. I've never liked it myself, just like the "Reload assemblies" command which previously had an F5 shortcut.

I might remove it or add "show hidden ...." next to it.

**Comment by UlyssesWu** [comment]
Oh yes.( In fact I can't find "Show hidden compiler generated types and members" selection? ) 

Seems that after switch "Show Internal Types And Members" on, I have to close the assembly and reload it, and then I can see those types. And once I switch it off and switch on again, those types just disappear. And I need to reload again. Is is a bug or not?

**Comment by 0xd4d** [comment]
It's in the latest build: https://ci.appveyor.com/project/0xd4d/dnspy/build/artifacts
