### ISSUE TITLE
Callstack & Values

### ISSUE THREAD

**Issue by TommyAndersen** [0xd4d/dnSpy#326]
The callstack shown does not match exactly the methods invoked.
System.Data.DataRow.EndEdit calls SetNewRecord()
but the callstack shown is
...
System.Data.DataRow.SetNewRecordWorker
System.Data.DataRow.EndEdit
...
SetNewRecord does however call SetNewRecordWorker.

Looking at the Locals I see some of the local variables, but not all. When I go backwards in the callstack (recursive calls) I get even fewer local variables.
It would also be nice too see the values of the variables on the tooltip in the editor like VS does.

**Comment by 0xd4d** [comment]
Did you attach to the process?

**Comment by TommyAndersen** [comment]
Yes.
The DLL is System.Data.

**Comment by 0xd4d** [comment]
The reason is that the CLR uses ngen'd images and optimizes the code. You can disable this, see https://msdn.microsoft.com/en-us/library/9dd8z24x(v=vs.110).aspx

**Comment by TommyAndersen** [comment]
Thank you soo much!!! The solution for me was just to start the application from dnSpy itself. If you're able to catch this information in dnSpy, you could maybe show an informational message with this information?

Thank you soo much for this awesome, awesome tool!!! :D
