### ISSUE TITLE
Compile Method error

### ISSUE THREAD

**Issue by richs2008** [0xd4d/dnSpy#327]
![image](https://cloud.githubusercontent.com/assets/8036268/21574509/cb7c776e-cf2e-11e6-81ca-dcd58da3432e.png)
![image](https://cloud.githubusercontent.com/assets/8036268/21574540/6854922e-cf2f-11e6-932e-476cc95cc176.png)

![Uploading image.png…]()

**Comment by 0xd4d** [comment]
Make sure you've added all the assemblies (see the first picture) to the same folder as the file you're trying to edit or load them in Assembly Explorer.
