### ISSUE TITLE
JIT exception on debug start

### ISSUE THREAD

**Issue by JavidX** [0xd4d/dnSpy#33]
There was this .NET exe file secured with crypto obfuscator and I used de4dot to clear it.
After saving the exe file I tried to execute it, but it was closed after a while (about 10 seconds) and nothing was shown (I could only see the process running in Task Manager).

I tried to debug it with dnSpy but as I click the Debug button it shows me the following error:
Unhandled: Message System.InvalidProgramException JIT Compiler encountered an internal limitation.CannotInterceptException
System.InvalidProgramException: JIT Compiler encountered an internal limitation.

Please fix this problem.
THANK YOU FOR THE HARD WORK!

**Comment by 0xd4d** [comment]
You'll get an exception like that if your program is corrupt. Doesn't seem to be a dnSpy issue so closing this.
