### ISSUE TITLE
proper immutable release binaries?

### ISSUE THREAD

**Issue by rgl** [0xd4d/dnSpy#332]
I'm installing from https://github.com/0xd4d/dnSpy/releases/download/v3.0.0/dnSpy.zip but from time to time that file changes and that breaks my installation script because the file checksum is different than it was before. Are there plans to start shipping proper immutable releases? This is somewhat needed for having the [chocolatey package issue resolved](https://github.com/0xd4d/dnSpy/issues/331).

**Comment by 0xd4d** [comment]
It gets updated after I add some smaller fixes or just recompile it. I only keep the latest release so the old ones are always deleted after uploading a new release.

**Comment by 0xd4d** [comment]
BTW, the releases I upload here are all from the appveyor site. Those releases are always there, AFAIK they never get deleted by appveyor, so you could just link your chocolatey install script to one of those. See https://ci.appveyor.com/project/0xd4d/dnspy/branch/v3.x/artifacts
