### ISSUE TITLE
view global field values

### ISSUE THREAD

**Issue by mrexodia** [0xd4d/dnSpy#334]
Is it somehow possible to show the value of global fields? I would like to see the value of `myGlobal` at runtime...

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace dnSpyGlobalTest
{
    class Program
    {
        private static string myGlobal = "blubber";

        static void Main(string[] args)
        {
            Console.ReadKey();
            myGlobal = "test";
            Console.WriteLine(myGlobal);
        }
    }
}
```

**Comment by 0xd4d** [comment]
It's not currently possible to view static fields in the locals window. It's something I plan to fix in 4.0.

It should be possible to do it using C# Interactive and scripting the debugger but it requires knowledge of the CLR debugging API.

**Comment by maritaria** [comment]
I remember that I usually solve this in Visual Studio by using watches, are those in dnSpy?

**Comment by 0xd4d** [comment]
Not yet, see #39

**Comment by 0xd4d** [comment]
Use latest beta.

**Comment by mrexodia** [comment]
Will definitely try it out!

**Comment by rolandh** [comment]
How can one view this variable in the current beta? If the metadata is missing (eg it has no name) there does not appear to be any way to add it to the watch or locals window.

**Comment by 0xd4d** [comment]
Roslyn is used (C#/VB) so if it has a weird name the compiler doesn't allow, you have to rename it or add it if it's missing.
