### ISSUE TITLE
Control compiler optimizations

### ISSUE THREAD

**Issue by DenJur** [0xd4d/dnSpy#335]
Is it possible to add a way to change/disable optimizations C# editor does? 
I was editing Unity library with some bigger string based switch statements that were not optimized in the original (?does Unity not do that I wonder?) but after editing dnSpy did full optimization turning that into string hash based "if" block. That's great but when testing/debugging becomes a pain to deal with.

**Comment by 0xd4d** [comment]
It's an implementation detail of the compiler, in this case Roslyn, and it's nothing I can control.

If you don't need to change a lot of code, try the IL editor instead.

**Comment by DenJur** [comment]
Damn was hoping for something like -O0.
Ended up writing code in VS and undo/paste it for testing. Then translated it into IL manually.

On a semi-related note then would it be possible to add "paste from text" to IL editor? I have done simple utility that did pattern-matching and code replacement from text with dnlib before but without complex cases. But even without dnSpy auto filling method calls or something it still would save a lot of time just by creating opcodes with null arguments if it can't link everything properly and throwing a warning to the user. (Should this have gone as separate issue?)

**Comment by 0xd4d** [comment]
Have you tried ILDASM? It can parse and compile IL code.

**Comment by DenJur** [comment]
I know about it but have not tried it.
My experiment was more of one evening project to try out dnlib.
And this was more of a suggestion for dnSpy as I remember being a little bit frustrated with it around v2beta when I tried to re-import my changes later from text file and was unable to find a way to do it quickly.
Anyway we have gone off topic and original issue is resolved so closing this thread.
