### ISSUE TITLE
Edit Method(C#) : keyword 'void' cannot be used in the context

### ISSUE THREAD

**Issue by vzsoft** [0xd4d/dnSpy#336]
Orginal Code:
```javascript
internal unsafe static bool smethod_3()
{
	void* ptr = stackalloc void[5];
	bool? flag = Class45.smethod_49();
	return flag.Value;
}
```
Edit Method(C#)  Change To
```javascript
internal unsafe static bool smethod_3()
{
	return true;
}
```

compile error:
keyword 'void' cannot be used in the context

**Comment by 0xd4d** [comment]
Are you sure the error is in `smethod_3` and not in some other method in `main.g.cs`?

**Comment by vzsoft** [comment]
sry edit code
Edit Method(C#) Change To
```javascript
internal unsafe static bool smethod_3()
{
	**void* ptr = stackalloc void[5];**
	bool? flag = Class45.smethod_49();
	return true;
}
```

if this line in the code. error :keyword 'void' cannot be used in the context
```javascript
	void* ptr = stackalloc void[5];
```

thanx

**Comment by vzsoft** [comment]
[screenshot](http://www.imagebam.com/image/6bd703524763327)

**Comment by 0xd4d** [comment]
It's a decompiler bug, you can manually change it to `void*[5]` and it should compile.

**Comment by vzsoft** [comment]
can not because used "ptr"
```javascript
				while (*(int*)ptr < 6)
				{
					char c = text4[*(int*)ptr];
					*(int*)((byte*)ptr + 4) = Convert.ToInt32(c.ToString());
					text3 += string_1[*(int*)((byte*)ptr + 4)].ToString();
					string_1 = string_1.Remove(*(int*)((byte*)ptr + 4), 1);
					*(int*)ptr = *(int*)ptr + 1;
				}
```

**Comment by 0xd4d** [comment]
The decompiler isn't perfect, especially when pointers are used, so you have to manually fix it (or use the IL editor which isn't sensitive to incorrectly decompiled code).

**Comment by vzsoft** [comment]
thanx
