### ISSUE TITLE
无法编译通过，添加了nuget包也没用，

### ISSUE THREAD

**Issue by danperor** [0xd4d/dnSpy#341]
新手不熟悉环境的话不太好编译

**Comment by maritaria** [comment]
Title: Can not compile through the addition of the nuget package is also useless
Body: 
Is not itself deliberately not let people through?
Tortured an afternoon, using Microsoft.CodeAnalysis; this in the end is what nuget on a lot of search results items

**Comment by UlyssesWu** [comment]
讲真，能不能态度友好一点，不要老想搞个大新闻。美国的0xd4d，真的比我们不知高到哪里去了，你根本无法和他谈笑风生。

关于你的问题——感觉是你是没装Roslyn吧你。
虽然我不知道到底是不是这个问题，不过装Roslyn的步骤如下：

> VS——工具——扩展和更新——联机——VisualStudio库——搜索“.NET Compiler Platform SDK”，安装。

I guess he haven't install Roslyn.

@maritaria  Thanks for the translation, and you can just @ me next time since I'm a native Chinese speaker and helped in dnSpy's translation.

**Comment by 0xd4d** [comment]
Build instructions: https://github.com/0xd4d/dnSpy/wiki/Building-dnSpy

Visual Studio 2015 is required (I use VS2015.3 and haven't tested anything older than that).

**Comment by danperor** [comment]
楼上的，对不起，0xd4d也是我膜拜的大神，昨天也是我折磨了一天这个环境，可能着急了，说话语气不对，我为此感到抱歉。我收回我说的话，并诚挚的向为这个项目贡献的所有人道歉，向0xd4d道歉！
 最后，感谢0xd4d及其伙伴们为社区的无私付出！
 and ,What I am saying is spur of the moment, I'm sorry, sincere thanks for your contribution, 0xd4d and your partner
 i'm so sorry!

**Comment by UlyssesWu** [comment]
下次最好还是用英语写issue，作者肯定是看不懂中文的，最好不要觉得 读懂这个issue 是他的义务。

当你能过编译了之后，别忘了关闭issue（Close issue）。

You can close this issue if you don't have question now.
