### ISSUE TITLE
Show inherited properties in assembly tree view

### ISSUE THREAD

**Issue by maritaria** [0xd4d/dnSpy#343]
If you have a class `X` it is not very user friendly to find out what properties/methods/events etc are exposed by it's base types. You have to goto those types and that can break (as in destroy old info of) your navigation history. Adding another folder named "Exposed by base" which lists all inherited properties/methods/events etc from the base types would be usefull.

**Comment by 0xd4d** [comment]
You want this added to the Analyzer window?

**Comment by 0xd4d** [comment]
Wouldn't it be better to use the Analyzer window instead of the Assembly Explorer?
