### ISSUE TITLE
Automatically express integers as enums when passed as argument

### ISSUE THREAD

**Issue by maritaria** [0xd4d/dnSpy#344]
![](http://image.prntscr.com/image/873f10b2671c473ba8dd1a5435654aae.png)

In some situations when an integer constant is passed to a method that is accepting it as a specific enum you could show the enum value, or combination when flags. Finally if it doesn't have a value to lookup that first show the value being cast, so the code becomes more expressive.

```csharp
[Flags]
public enum MyEnum { A = 1, B = 2 }

public static void Test(MyEnum arg){}

Test(0) -> Test((MyEnum)0)
Test(1) -> Test(MyEnum.A)
Test(2) -> Test(MyEnum.B)
Test(3) -> Test(MyEnum.A | MyEnum.B)//If flags is missing then show like with 0 and 4
Test(4) -> Test((MyEnum)4)
```

It would be fair to say that in the event that multiple values are assigned to the same value, prefer direct values over combinatory ones, and if multiple enum values fit the exact value then pick the first defined by the assembly.

**Comment by 0xd4d** [comment]
Do you have a repro? I Used the code above and it correctly decompiled it.

```C#
Program.Test((Program.MyEnum)0);
Program.Test(Program.MyEnum.A);
Program.Test(Program.MyEnum.B);
Program.Test(Program.MyEnum.A | Program.MyEnum.B);
Program.Test((Program.MyEnum)4);
Program.Test((Program.MyEnum)99);
```

**Comment by herix001** [comment]
it seems some codes compiled by mono(unity3d 5) couldnt decompiled correctly
I have no source code

[DebuggerHidden]
public IEnumerator PlayTrick(int d)
{
	CutinControl.<PlayTrick>c__Iterator7C <PlayTrick>c__Iterator7C = new CutinControl.<PlayTrick>c__Iterator7C();
	<PlayTrick>c__Iterator7C.d = d;
	<PlayTrick>c__Iterator7C.<$>d = d;
	<PlayTrick>c__Iterator7C.<>f__this = this;
	return <PlayTrick>c__Iterator7C;
}

**Comment by TiberiumPY** [comment]
@herix001 this is a known problem and it can't be fixed by dnSpy itself

**Comment by 0xd4d** [comment]
It's because the decompiler doesn't support Mono's yield return state machine. It just needs to be updated to support it.

**Comment by maritaria** [comment]
@0xd4d What lib do you use for decompiling IL to C#? And how is it compatible with dnlib?

**Comment by 0xd4d** [comment]
It's `ICSharpCode.Decompiler` (aka ILSpy).

**Comment by 0xd4d** [comment]
@maritaria : Do you have a repro?

@herix001, @TiberiumPY: try the latest build.

**Comment by herix001** [comment]
@0xd4d 
IEnumerator work well now,
There is a problem with delegate closure

{
	this.<>f__this.isPlay = false;
	global::Debug.Log("localScale=" + this. <>f__this.cutinBG.GetComponent<RectTransform>().localScale);
}

The "<>f__this" is redundant.Of Course,it can be fixed manually.

**Comment by 0xd4d** [comment]
@herix001 : Can you open a new issue? I'll delete the off topic posts here.

**Comment by 0xd4d** [comment]
Can't repro.
