### ISSUE TITLE
Locals window: add find function to specified local var in countless columns

### ISSUE THREAD

**Issue by gagmeng** [0xd4d/dnSpy#346]
When i debug App, sometimes countless columns is possible. So It is very difficult to find specified var.
Please add new this feature!
Thanks for reading

**Comment by maritaria** [comment]
You mean rows? Rows are horizontal, columns are vertical

**Comment by gagmeng** [comment]
Yes, it's rows.

**Comment by 0xd4d** [comment]
It's possible to sort the locals in the latest version (in fact it's available since v4.0)
