### ISSUE TITLE
Remove instruction from the decompiler

### ISSUE THREAD

**Issue by XenocodeRCE** [0xd4d/dnSpy#347]
Hello

It would be very nice to be able to remove il code from the decompiler window, NOT the MethodBodyDlg.
So as we would be able to remove code from this window

![](http://i.imgur.com/6sqoSE2.png)

I tried to implement it : 
In the **Execute** method there is some _Offset_ which correspond to our selected / underlined c#-syntax code.
In the ListBoxHelperBase class, the method **ShowContextMenu** contains a _parameter_ objet which correspond, if i'm not wrong, to these _Offset_, and therefore once the dialog is shown, it auto select these offsets
Also I noticed that the **AddRemoveItemHandlers**  function was somehow linked to the  delet  instructions reference i want to hack, but other than that i cannot find the method which takes these offset as parameter and delet them, sorry

**Comment by 0xd4d** [comment]
Yes a `Delete Statement` command could be useful. A workaround today is to right-click the statement and open the IL editor and press delete + OK. To get the statement info, see existing code, ge. [here](https://github.com/0xd4d/dnSpy/blob/master/Extensions/dnSpy.AsmEditor/Compiler/Commands.cs#L212)

**Comment by XenocodeRCE** [comment]
@0xd4d yes but it's not the feature I want. I know there is some workaround but still it demends some more tasks.
I'll try to work on it on my own, but I haven't got the concept of your project's structure yet, still have to deconstruct it.
