### ISSUE TITLE
Edit a assembly and save it (Patch it)

### ISSUE THREAD

**Issue by MSAyrese** [0xd4d/dnSpy#348]
Hello.
In .net reflector I can edit assembly and save it with "reflexil".

In "dnSpy" I edited a method and now I want to save the EXE file (Opened and edited by dnSpy) as patched file look like reflexil.
Is There any way to do this?

**Comment by UlyssesWu** [comment]
...Study the menu carefully and you will find "Save Module" in "File" menu is what you want.

**Comment by 0xd4d** [comment]
Or you can press `Ctrl+Shift+S` to save all modified modules (assemblies).
