### ISSUE TITLE
What wrong in my edit msil

### ISSUE THREAD

**Issue by kelalung** [0xd4d/dnSpy#349]
i have function:
num = Convert.ToInt32(this.GoodsNum.EditText);
```C#
			if (num >= 99)
			{
				num = 99;
			}
			if (num == 0)
			{
				num = 1;
			}
```
i use dnspy, edit above code by IL instructions at value 99, change it to 999 but button OK is not Enable and i cant save it or change it?
Whatis wrong value for this my case

**Comment by TiberiumPY** [comment]
you can edit c# code, compile and save it, save module with ctrl+shift+s

**Comment by 0xd4d** [comment]
Look for a red line somewhere, you perhaps deleted an instruction that is the target of a branch etc.

Since you're editing IL code, it's better to show the IL and not the decompiled code.

**Comment by kelalung** [comment]
please view this video for detail:https://youtu.be/ZTQTelHdHEo
i want to change 99 to 999 but it limit -128->+127

**Comment by 0xd4d** [comment]
-128..127 => it's a signed byte, and you can't store 999 in a signed byte.

**Comment by 0xd4d** [comment]
Closing this, you should change it from ldc.i4.s to ldc.i4 which can load a 32-bit integer, so 999 will fit.
