### ISSUE TITLE
Navigate to overriden implementation in derived class

### ISSUE THREAD

**Issue by 0x084E** [0xd4d/dnSpy#35]
When clicking on a method in the code editor you will always be directed to the class where the method is defined. If I'm currently in a derived class and one class in the inheritance chain overrides the clicked method it would be nice if I would be directed to the overriden method because this is what is actually called.

**Comment by 0xd4d** [comment]
C1: virtual M
C2: override M
C3: call M
C4: override M

C4 derives from C3 which derives from C2 etc.

C3 could then call C2.M or C4.M . The original virtual method is shown when you click on the call M instruction in C3 because that's what the compiler generates. The analyzer can show you which classes override M.

**Comment by 0x084E** [comment]
OK, this is a little bit more complicated than I thought.
I played a little with other decompilers and Reflector behaves exactly like dnSpy. JustDecompile and dotPeek do also with one exception:

C3: override M
C3: call this.M in M2

On a click to metod call this.M in M2 dnSpy navigates to C1.M but JustDecompile and dotPeek navigate to C3.M (which was what made me think they behave different generally). Even though I find this a little bit more intuitive I understand why dnSpy behaves different.

**Comment by 0xd4d** [comment]
Closing it, no-one seems to want it (no upvotes or PR) and I have never needed it either.

**Comment by SylwesterZarebski** [comment]
This should be reopened - DotPeek easily allows to go to any base/derived type or base/overridden method without using Analyze method which is tedious for simple actions.
