### ISSUE TITLE
NullReferenceExpression and "The call is ambiguous between the following methods or properties"

### ISSUE THREAD

**Issue by Albeoris** [0xd4d/dnSpy#351]
There is two overloads of method with same name and number of arguments.

```
public void SetAnchor(Transform t)
{
}

public void SetAnchor(GameObject go)
{
}
```

**And call:**
0	0000	ldarg.1
1	0001	**ldnull**
2	0002	callvirt	instance void UIRect::SetAnchor(class [UnityEngine]UnityEngine.Transform)

**As result:**
The call is ambiguous between the following methods or properties: 'SetAnchor(Transform)' and 'SetAnchor(GameObject)'

**Possible fix:**
AstMethodBodyBuilder.Ast.Expression Convert(Ast.Expression expr, TypeSig actualType, TypeSig reqType)
```
else if (expr is NullReferenceExpression && reqType is TypeDefOrRefSig)
{
    return expr.CastTo(AstBuilder.ConvertType(reqType, stringBuilder));
}
```

**Result:**
`emptySlotLabel.SetAnchor((Transform)null);`

**Comment by 0xd4d** [comment]
`null` is used a lot so this fix will cause tons of unneeded casts. Perhaps it's better to only do it if `TransformCall()` gets called.

```diff
-			bool flag12 = field != null;
+			bool flag12 = field != (FieldDef)null;

....

-			ArrayBuilder<T> arrayBuilder = null;
+			ArrayBuilder<T> arrayBuilder = (ArrayBuilder<T>)null;

...

-				return null;
+				return (byte[])null;
```
