### ISSUE TITLE
Restoring a specific patch/change

### ISSUE THREAD

**Issue by wk-952** [0xd4d/dnSpy#354]
I have a question please, but first i should mention that i'm very new to this debugger.
Consider the following simple function:
```
private static bool notChoice(bool choice)
{
	return !choice;
}
```

Assuming that i've changed the `return` statement to be always `true`/`false`, but then i changed my mind and wanted to restore it back to its original form, the only available solution seems to be selecting `File`->`Reload All Assemblies` but that resets all changes.

So my question is, how can i restore a specific change/patch without losing all other changes ?

**Comment by SlowLogicBoy** [comment]
Well there is Ctrl+Z that undo tasks, and it works like in all other apps, if you changed a lot after that and don't want to lose those changes, well your only options are to change it back yourself, or write your own extension that could do that.

**Comment by 0xd4d** [comment]
You could also edit the method and paste the original decompiled code.

**Comment by wk-952** [comment]
Alright, it's clear now.
Thanks a lot for your responses.
