### ISSUE TITLE
Unsaved file exit dialog

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#356]
If one have dozens of assemblies and there were some changes made the current dialog shown on exit is very un-informative.....  
Are there any chance to add the assembly(-ies) name into it?
Thanks

![screenshot_93](https://cloud.githubusercontent.com/assets/765343/22489699/b226030a-e821-11e6-9f6d-95c7232c656b.png)

**Comment by 0xd4d** [comment]
The names are shown in the save dialog if you press Yes. Is that not enough?

**Comment by greenozon** [comment]
Do you mean the "Save All..." menu item?
the issue (well human factor) is that if I've way too many assemblies in teh left tree (I really have 30 or 40 or so) and once I change smth and navigate to another  dll I'm lost but I definitely need to save that change.....

also, the above mentioned "Save All" - does it iterate over all the unsaved asemblies from the left tree list?

**Comment by 0xd4d** [comment]
If you press `Ctrl+Shift+S` it will show all modified assemblies. If there's just one, the simple dialog box is shown, else the multi-file dlg box. Both list the file names of the assemblies.

**Comment by greenozon** [comment]
THis is great!  thanks a lot for being patient and providing great  info!
