### ISSUE TITLE
Add new assembly reference 

### ISSUE THREAD

**Issue by pikachuk** [0xd4d/dnSpy#357]
Hello, i send this message because i don't know how i could do to add a reference to new assemblies not already included in the references, i tried opening the dll and add a using in the script but it didn't work, i tried to add the reference like in visual studio, right clic on "references" but no option "add reference" so i don't know how i should do

**Comment by 0xd4d** [comment]
In the 'edit code' window, in the lower left corner, there's a 'main.cs' combobox and to the right of it are two icons, the first one is most likely what you want. Add your file as a reference and you can then add usings at the top of the edited file.

Note that it seems that you're editing a Unity assembly, in which case you can't just add any reference. Eg. don't try to add assemblies compiled for .NET Framework, that will probably lead to crashes at runtime if it compiles.

**Comment by pikachuk** [comment]
the assembly that i want to add is a unity assembly from the exact same version of unity, it's the one that manages UI (UnityEngine.UI) it should work

**Comment by TiberiumPY** [comment]
@pikachuk then you can just add "using UnityEngine.UI" at the first line of code editor

**Comment by chucklu** [comment]
The edit code window will popup, when you edit the class.
![image](https://user-images.githubusercontent.com/3004057/62414116-69c71280-b64a-11e9-89b0-e26b75705763.png)

**Comment by chucklu** [comment]
@0xd4d  I find when I try to add  assembly reference, I got assembly list from GAC. 
Is it possible to browse an assembly, and reference it from a custom path?

**Comment by chucklu** [comment]
I got it, the first icon is used to add reference by browse path, thanks.

**Comment by chucklu** [comment]
Hi @0xd4d ,
    From my experience, if I only add the assembly and did not reference the type in it.
     When I save as module, the assembly reference seems ignored.
      I have to do something like `MessageBox.Show(typeof("type in new assembly"))`, then it will reference the assembly in saved new module.

**Comment by 0xd4d** [comment]
It's a feature, there's no need to include assembly references (or other refs) that the assembly doesn't reference.

**Comment by chucklu** [comment]
Sometimes, use [CSharpCodeProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.csharp.csharpcodeprovider?view=netframework-4.8) to load the plugins. It's possible that the assembly did not reference the third party library but the plugin referenced  the third party library.
