### ISSUE TITLE
Export to project error

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#358]
Encountered this kind of error never seen before:

![dnspy_export_error](https://cloud.githubusercontent.com/assets/765343/22625801/329398a8-eba7-11e6-9ab9-77320c2f6918.png)

Used default settins in export window on one of latest tool builds from appveryor

**Comment by 0xd4d** [comment]
I've seen this too about a week ago. Seems like the .NET Framework [resource reader](https://msdn.microsoft.com/en-us/library/system.resources.resourcereader(v=vs.110).aspx) doesn't support those types.

**Comment by greenozon** [comment]
OK, but from the error it's not obvious and I can't deduce whether the project was successfully exported (and this is just a warning) or it is a failure and abort...

BTW, other tools (ILSpy, Telerik) are exporting the target without this kind of issue...
So I just want to clarify why it is happening here
