### ISSUE TITLE
Native code that changes the stack results in PInvokeStackImbalance (MDA)

### ISSUE THREAD

**Issue by ViRb3** [0xd4d/dnSpy#359]
I'm not sure if this is a problem with dnSpy and its debugger, but when I am debugging a ConfuserEx 1.0 target with x86 switch predicates, the program falls into an endless loop, repeating the same 3-4 code blocks forever.

I tried obfuscating two apps with only x86 predicate cflow:
- a very simple "Hello World" app: dnSpy can successfully debug it until the end.
- an app with some light prime calculations: dnSpy seems to jump between 3-4 code blocks forever (not a part of original code). Never reaches first line of original code.

My alternative theory is that the debugging process makes calling the native code very slow, thus resulting in what looks like an infinite loop. dnSpy is running at 15% CPU constantly.

Could somebody please shed some light on this issue?
Thanks!

**Comment by 0xd4d** [comment]
Can you repro this with the latest build?

Is it an infinite loop (press F5) or does it only appear to be so?

**Comment by ViRb3** [comment]
Yes, I just build from latest source. It does loop forever when I debug (F5). I will post test files in a moment.

**Comment by 0xd4d** [comment]
Hint: open `output window`, could be a bug in the generated code.

**Comment by ViRb3** [comment]
@0xd4d I believe I tracked the issue. ConfuserEx x86 control flow obfuscation injects native code that performs math and returns a decrypted value. A call to that code is placed in the switch statement condition:

!()[https://i.imgur.com/fpmhPAf.png]

And here is its signature:
!()[https://i.imgur.com/1m2tPl8.png]

The native method pops an integer value off the stack (arg_1E_0), performs math, and returns the decrypted value. The issue lies in the "pop" part: that makes changes to the stack, thus Output Window's error:

Managed Debugging Assistant: "PInvokeStackImbalance" has detected a problem in 'assembly.exe'
Additional information: A call to PInvoke function 'native_function' has unbalanced the stack' ...

I don't think that the stack has been unbalanced, but rather just changed. Is there any solution to this problem?

Thanks!

**Comment by ViRb3** [comment]
After reading around, the issue seems to be unspecified calling convention. However I can't change that plus the assembly already works perfectly. Can I disable MDA?

**Comment by 0xd4d** [comment]
AFAIK, this exe can run as a 32-bit or a 64-bit program. The question then is whether the generated code works in both 32-bit and 64-bit modes. If you look at the disassembly, it uses [rsp+XXX] or [esp+XXX] but the offsets will be different if it's 32-bit or 64-bit.

**Comment by 0xd4d** [comment]
To disable MDA, see [this](https://msdn.microsoft.com/en-us/library/d21c150d.aspx)

Note, use the value '0', not '1' to disable it.

**Comment by 0xd4d** [comment]
I've added #362 that tracks adding an option to enable/disable MDA.

**Comment by ViRb3** [comment]
Many thanks! Disabled MDA using the environmental variable and everything works perfectly.
