### ISSUE TITLE
Add an analyzer "Overriden from"

### ISSUE THREAD

**Issue by 0x084E** [0xd4d/dnSpy#36]
I' not sure how to call this but what I mean is the opposite of "Overriden By" which shows the methods from base classes.

**Comment by 0xd4d** [comment]
I'm not sure how useful this is. What would you do with that information? Should it just show the first method it overrides or should it show every method it overrides C.M1 overrides B.M1 which overrides A.M1, and you want to see B.M1 and A.M1 in the result?

**Comment by 0x084E** [comment]
Maybe I'm missing something but when you have to navigate through inheritence chains I think it is extremly usefull when you can navigate in both directions, At the moment if you want to know which classes are overriding a member you have to navigate to the base class and look for 'Overridden By'.
This works, of course, but you have to leave C and goto A to get an information which C could have given you also.

I'm not sure how the result should look like. I've checked the behavior of 'Overridden By' and there it depends. It shows you B.M1 and C.M1 if called from A.M1 and only C.M1 if called from B.M1.
To be consistent I think it should show you B.M1 and A.M1 if called from C.M1 and only A.M1 if called from B.M1
