### ISSUE TITLE
[Question] How to decompile or watch the IL code of a dynamicmethod

### ISSUE THREAD

**Issue by funkvps** [0xd4d/dnSpy#360]
Dear 0xd4d, thanks for the powerful tool, it's very useful for.dealing with .net codes, when combined with de4net.

I'm current research targets protectet with sentinel envelope. This protector take some of method code out into dymanic decoded dynamicmethod. During debug, i can see the properties of the dynamicmethod. 

But the questions is is there any method to decode the content in the dynamicmethod？

**Comment by 0xd4d** [comment]
You can use [this class](https://github.com/0xd4d/dnlib/blob/master/src/DotNet/Emit/DynamicMethodBodyReader.cs) if you can inject your code into the process.

**Comment by funkvps** [comment]
What do you mean by inject? Is compile dnlib, into the target? The target is a protected .net exe. Currently I can inspect the ilbytes using dnspy, but can not get clear understanding with the help of decompilation.

**Comment by maritaria** [comment]
I think he means editting the code of the binary and passing the dynamic instance through the `DynamicMethodBodyReader`.

**Comment by funkvps** [comment]
Dear maritaria,

If my understanding is correct, this means
1. Compile.dnlib to ils
2. Edit the target to include dnlib ils
3. Call dynamicmethodbodyreader

May i ask, By doing this, how to show the codes in dnspy with the function of cross reference, decompiling, etc?

**Comment by nareshn2003** [comment]
I am also interested to know How DynamicMethodBodyReader used ? Did you able to use it ?
