### ISSUE TITLE
Slow performance when opening and closing

### ISSUE THREAD

**Issue by catester** [0xd4d/dnSpy#361]
dnSpy has good performance while browsing an assembly, however there are issues when opening or closing:

- Especially when you open a big assembly (like > 20MB), there can be a 1-3 seconds freeze. I understand that decompilation occurs but it should not freeze the whole system (100% CPU?). I suspect this is a UI related problem.

- Closing a single assembly is fast (right click and remove) but "Close All" command is very slow, it freezes the UI for many seconds. I suspect this is a UI related problem too, maybe TreeView tries to decompile the assemblies in the list mistakenly before closing them?

Maybe these are side-effects of MVVM pattern? It feels like there occurs some unnecessary UI updates.

**Comment by 0xd4d** [comment]
I suspect this is code calling `GC.Collect()` to make sure the old memory gets collected.

**Comment by catester** [comment]
Yes I agree, it's probably caused by `GC.Collect() `.
I was going to suggest calling `GC.Collect() ` in a background thread and not in the UI thread but it seems you are already doing so:
```
Dispatcher.CurrentDispatcher.BeginInvoke(DispatcherPriority.Background, new Action(() => {
	GC.Collect();
	GC.WaitForPendingFinalizers();
	foreach (var o in documentTabSerializer.Restore(tgws)) {
	}
	disableLoadAndReload = false;
}));
```

So you say we can not avoid calling `GC.Collect() `? For example, is only disposing ModuleDefs not enough?

**Comment by 0xd4d** [comment]
It's not safe to dispose of them since they could be used by a background decompiler thread.

**Comment by maritaria** [comment]
Why is GC being used directly, instead of trusting the runtime to trigger it? Since I learned that using GC yourself is bad practice I wonder what reason would warrant it.

**Comment by 0xd4d** [comment]
The modules could be memory mapped and must be closed. The current code doesn't know when there are no more users (eg. there could be a bg decompiler thread using the module). Adding some referencing counting could solve it.
