### ISSUE TITLE
Editing obfuscated assembly without de-obfuscating

### ISSUE THREAD

**Issue by TiberiumPY** [0xd4d/dnSpy#363]
Hi! I have an assembly obfuscated with unknown obfuscator.
Variable names are like in this image:
![image](https://cloud.githubusercontent.com/assets/21169548/22788569/596178b8-eef1-11e6-8bf2-03b9e71a8616.png)

Can I somehow still edit C# code (not IL) with all that obfuscated stuff?
Currently it fails:
![image](https://cloud.githubusercontent.com/assets/21169548/22788606/725b4146-eef1-11e6-8c07-35b3a47bf8a6.png)

(Yeah I'm using Wine, but it doesn't matter, because there's same issue on Windows 10)

**Comment by 0xd4d** [comment]
This is a dupe of #231 #165

Try to edit a small method that is easy to fix by hand, then add a new method and press Compile. Once you have the new method, use the IL editor and add a call from the obfuscated method to the new code.
