### ISSUE TITLE
Recompile Error: Type Conflict when there are Cyclic Dependencies between Classes

### ISSUE THREAD

**Issue by bert2** [0xd4d/dnSpy#365]
**Repro steps:**

1. Create a new class library project in Visual Studio 2013.
2. Add a class file to the project and insert the code shown below.
3. Compile and open the resulting DLL in dnSpy.
4. Navigate to `MyClass`, right-click and select "Edit Class (C#)..."
5. Without modifying anything, press the "Compile" button and check the errors and warnings.

**Expected:**

- Compile should succeed without any errors.

**Actual:**

- Compile fails with an error and a warning.

---

**Code of "MyClass.cs":**

```C#
namespace dnSpyBug {
    public class MyClass {
        public string ToId(MyEnum value) => MyStaticHelperClass.ToString(value);
        public enum MyEnum { MyEnumValue1, MyEnumValue2 }
    }

    public static class MyStaticHelperClass {
        public static string ToString(MyClass.MyEnum value) => ((int)value).ToString();
    }
}
```

**Output of dnSpy:**

![image](https://cloud.githubusercontent.com/assets/1454629/23037691/a49ec380-f487-11e6-96e8-b9175d7b4496.png)

**Errors & Warnings:**

Type | Code | Description | File | Line
------|-------|--------------|-----|------
Error | CS1503 | Argument 1: cannot convert from 'dnSpyBug.MyClass.MyEnum [main.cs(20)]' to 'dnSpyBug.MyClass.MyEnum [D:\DEV\dnSpyBug\dnSpyBug\bin\Release\dnSpyBug.dll]' | main.cs | 11
Warning | CS0436 | The type 'MyClass' in 'main.cs' conflicts with the imported type 'MyClass' in 'dnSpyBug, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'main.cs'. | main.cs | 9

**Additional Notes:**

- The warning seems to hint at the cause of the problem, but I really have no idea what's going on there.
- The issue persists when editing the method `ToId()` individually, instead of the editing the whole class.
- In theory the problem can also be repro'ed with VS 2015, however more steps are required to work around Roslyn and/or dnSpy's incomplete Roslyn support.

**Comment by 0xd4d** [comment]
Additional Note 3: try the latest build

The compiler gets confused because there are two MyClass classes, one in the source file and another one in the original assembly.

**Comment by bert2** [comment]
Additional note 3: Building dnSpy from source resolved this side issue (report was based on v3.0.1 of the pre-compiled binaries).

The repro code is confused as well. But unfortunately it's a simplification of a real-life example I had to work with. From your explanation I could simplify the repro code though, as lambdas actually weren't part of the problem. I updated the report accordingly.

**Comment by 0xd4d** [comment]
A possible solution which I haven't verified if it will work, could be to remove all references to MyClass and its members in the original assembly and replace all of those refs with references to the not-yet-compiled in-memory assembly (the code in the code window). The original MyClass class should also be renamed in memory.

**Comment by bert2** [comment]
Just for completeness: after further testing I understood that the issue occurs when there are cyclic dependencies between classes. Note that this effectively prevents re-compilation of implementations of the visitor design pattern. Try this code in the repro project for example:

```C#
namespace dnSpyBug {
    public interface Element {
        void Accept(Visitor v);
    }

    public class Foo : Element {
        public void Accept(Visitor v) => v.Visit(this);
    }

    public interface Visitor {
        void Visit(Foo foo);
    }

    public class Bar : Visitor {
        public void Visit(Foo foo) {}
    }
}
```

In the above example the class `Foo` cannot be recompiled.

**Comment by Nodens-** [comment]
Hello,
I believe I'm hitting the same or very similar issue. Here is my target for reproduction:
http://www.mediafire.com/file/mwkr2cdk83k8o2r/Managed.zip
Open Assembly-CSharp.dll and try to recompile any method member of BattleUnitController class without any change to the method whatsoever. I am getting an assortment of the same warnings and errors.
Worthy of note is that the same happens under Reflexil as well.

**Comment by 0xd4d** [comment]
@Nodens- : Remove the interfaces from the class declaration (main.cs) and most of the methods in main.g.cs

**Comment by Nodens-** [comment]
@0xd4d What is the logic behind what methods to remove in main.g.cs? I removed all of those referenced in the errors and I still can't get it to compile. I managed to reduce the number of compiler errors to these:
http://imgur.com/a/X6YMP

Yet the missing definitions errors make me think I removed method definitions that I should have?

**Comment by 0xd4d** [comment]
It's not going to work to edit all of those methods until this thing has been fixed. Try some other method or use the IL editor. If you have a lot of code, edit a simple method (eg. a property) and add a new method and press Compile. Then add a call to the new method in the IL editor.

**Comment by Nodens-** [comment]
Roger that. Adding methods anywhere within the class fails. Writing the entire thing in IL is going to be hectic. I was thinking on writing public static methods (so I don't even need to instantiate class objects) in another unrelated class and inject calls in the target method with IL. That should work..in theory.. :)

**Comment by 0xd4d** [comment]
Just pick a simple method or property, there are many of those, choose edit method, add your new method (don't modify the other one you 'edited'), press Compile. Works without a problem.

**Comment by Alien-AV** [comment]
I needed to add a call to a method from a different class, with "this" as a parameter.
Which hit the issue described here.

Here's a WA I used:

First of all, some methods in this class already had such an issue - "Edit Method" instead of "Edit Class" indeed does sidestep this issue.

Second, since I wanted to compile new code which would evoke this issue, namely call `OtherClass.ExternalMethod(this)`, I resorted to calling the same method with null `OtherClass.ExternalMethod(null)`, and then editing IL code, changing `ldnull` instruction to `ldarg.0` before the method call.

Lastly, I had an issue that the method was overloaded, and I couldn't provide the compiler a way to choose the correct signature in C#. I had to cast null to one of the random overloads with the same number of arguments `OtherClass.ExternalMethod((ThirdClass)null)` - and then change the method reference in the IL editor to the correct overload.

**Comment by softmgr** [comment]
@Alien-AV 
The solution is very good!

**Comment by 0xd4d** [comment]
This has now been fixed, get the latest build.

**Comment by 0xd4d** [comment]
It took me exactly one year to fix this. :)
