### ISSUE TITLE
How to debug the method with the properties of [MethodImpl(MethodImplOptions.NoInlining)]

### ISSUE THREAD

**Issue by gagmeng** [0xd4d/dnSpy#367]
There are a software which is packed with .NET Reactor(4.8-4.9), it can be unpacked by de4dot, but the unpacked file can't run correctly.
Open the unpacked file with dnspy, the method is display correctly like this.
```C#
private string O1sEp3LkLL()
{
	    string s = "XXXXXXXXXXXXXXXXXXXXXXXXXX";
	    byte[] array = Convert.FromBase64String(s);
	    for (int i = 0; i < array.Length; i++)
	    {
	    	    byte[] expr_18_cp_0 = array;
		    int expr_18_cp_1 = i;
		    expr_18_cp_0[expr_18_cp_1] ^= 85;
	    }
	    return Encoding.UTF8.GetString(array);
}
```
The method of the original file is display like this.
```C#
[MethodImpl(MethodImplOptions.NoInlining)]
private string O1sEp3LkLL()
{
	    return null;
}
```
So, how can i debug the method O1sEp3LkLL of the original file in dnspy? and how can i patch the string "s" in the original file? Thanks.

**Comment by 0xd4d** [comment]
Since methods are only decrypted at runtime, and dnSpy only reads method info from the metadata, you won't be able to see anything. You have to fix the unpacked file so it's runnable, then you can use dnSpy to debug it.

**Comment by gagmeng** [comment]
Is it possible to find the encrypted data of  method O1sEp3LkLL in the original file's metadata?

**Comment by 0xd4d** [comment]
You have to study the "protection" yourself to find the answer to that question.
