### ISSUE TITLE
After editing struct, edited structures will stop work without constructor

### ISSUE THREAD

**Issue by friuns2** [0xd4d/dnSpy#368]
if try edit structure and compile dll, structures will not work without constructor..

Vector3 test;
test.x =3;
return test;

Will throw error "Use of unassigned local variable", before it worked just fine..

**Comment by friuns2** [comment]
don't know if its related but part of il code disapears from edited struct

before
`.custom instance void [mscorlib]System.Reflection.DefaultMemberAttribute::.ctor(string) = (
		01 00 04 49 74 65 6d 00 00
	)`

after

`.custom instance void [mscorlib]System.Reflection.DefaultMemberAttribute::.ctor(string) = (
	)`
is there way to edit il code instead c#?

**Comment by 0xd4d** [comment]
1: Can you show the steps and before / after so I know what's wrong?

2: Could you create a new issue?

**Comment by friuns2** [comment]
1. sure i try to make some example and send you.
2. what do you mean by new issue?

**Comment by friuns2** [comment]
Here what i do
![image](https://cloud.githubusercontent.com/assets/16543239/23106366/0003cc38-f6f5-11e6-9554-aa71806d7da4.png)

results broken structure 
http://i.imgur.com/Cxm3qRG.png

i attached project 
there 2 dlls one modified that is broken.

http://www79.zippyshare.com/v/WUlxFyJW/file.html

**Comment by 0xd4d** [comment]
> 2. what do you mean by new issue? why

Because it's not related to the first issue.

You should use the built-in code editor in dnSpy instead of decompiling everything and then trying to compile it from VS. The decompiler doesn't always generate 100% correct code.

**Comment by friuns2** [comment]
i don't decompile everything, i just modify c# code inside dnspy and save DLL 

from VS i created original library for testing and then modified it inside dnspy. you seems missunderstood screenshots i sent..

**Comment by 0xd4d** [comment]
The code you showed compiles without a problem for me. If this is still a problem, write down the exact steps on how to reproduce it.

**Comment by friuns2** [comment]
hi make sure project using ConsoleLibrary2.dll not the original one ConsoleLibrary1

i made 1 minute video where i open project and try to compile it and it fails
https://www.youtube.com/watch?v=AakCJa603IU

**Comment by 0xd4d** [comment]
There's nothing dnSpy can do about this. You modified a struct and added a new field. Other code that assumed there was only one field compile successfully if the struct contains only one field, but fails when there are two fields. You have to add the init code yourself:

```C#
struct1.y = 3;// initialize new field
```

or

```C#
Struct1 struct1 = default(Struct1);
```

**Comment by friuns2** [comment]
ah too bad, cant do that, they don't initialize structures in unity3d, Thanks for your support
