### ISSUE TITLE
Breakpoints not being hit in ConfuserEx protected assembly loaded by Assembly.LoadFrom

### ISSUE THREAD

**Issue by Jitnaught** [0xd4d/dnSpy#369]
In other similar issues the OP was told to either debug the assembly instead of attaching to the process and/or make sure the breakpoint was set in the right module. In my situation I cannot use "Debug an Assembly", but I have made sure the right module was used by going to the Modules window and checking that the breakpoint was set in both the module and module in memory, which it was. I also switched to the IL instructions and set the breakpoint at the 0 offset, but it did not break there either.
If it's of any importance, I also made the ["Image Easier to Debug"](https://msdn.microsoft.com/en-us/library/9dd8z24x(v=vs.110).aspx), but it did not make a difference.

**Comment by 0xd4d** [comment]
Could you list the steps required to repro this?

**Comment by Jitnaught** [comment]
I just tested some more and it seems it only has this problem with an assembly that's protected with ConfuserEx 1.0.0. Is ConfuserEx blocking the debugging?

The exact steps to reproduce this would involve downloading some 60 GB. To reproduce I would suggest writing a .NET program that loads a .NET assembly on button press, run the program, attach to it with dnSpy, set the breakpoint in the ConfuserEx protected assembly that is going to be loaded, and then load the assembly in the program written earlier.

If you want I could send the ConfuserEx protected assembly. I could also write the program that loads the assembly if need be.

**Comment by 0xd4d** [comment]
If you can create a smaller (something a lot smaller than 60GB :) ) file then post it here.

**Comment by Jitnaught** [comment]
@0xd4d The file itself isn't 60 GB. What loads the file amounts to 60 GB. I'm not able to attach the ZIP of the assembly on here so I uploaded it on dropbox.
https://www.dropbox.com/s/vph8e2t69hk8szx/ConfuserExProtectedAssembly.zip?dl=1

**Comment by 0xd4d** [comment]
What are the steps to reproduce this once it's been loaded?

**Comment by Jitnaught** [comment]
Set a breakpoint anywhere and then load (or reload) it.

**Comment by 0xd4d** [comment]
I need more information. `Set a BP anywhere` won't work because not every method will immediately execute.

**Comment by Jitnaught** [comment]
Sorry, set the breakpoint on the first line of the <Module> cctor.

**Comment by Jitnaught** [comment]
If you happen to have the game Grand Theft Auto V on PC, then follow these instructions to reproduce. Otherwise I don't think it's possible to (at least easily) reproduce.

To reproduce you need Grand Theft Auto V on PC installed, with the modifications named Script Hook V and Script Hook V .NET installed, and the provided DLL placed in the /scripts/ folder that you have to create within the root Grand Theft Auto V directory. When everything is installed, run the game until it is fully loaded. Once fully loaded, attach to the GTA5.exe process in dnSpy (x64), open the provided DLL assembly in dnSpy or by right-clicking the assembly in the Modules window and clicking Go to Module, then set a breakpoint on the first line of the <Module>.cctor() of the assembly. Now go back into Grand Theft Auto V and press Insert on your keyboard to reload all .NET assemblies previously loaded by Script Hook V .NET. This is where the breakpoint should be hit, but is not. Breakpoints set in other .NET modifications _not_ protected by ConfuserEx are hit, but not in the one provided.

**Comment by Jitnaught** [comment]
So this is embarrassing. Turns out the assembly got an error while being loaded, so wasn't started, which is why the breakpoint wasn't hit. It is not a problem of your program, just my stupidity I guess.
Sorry for the confusion and any time I made you waste!
