### ISSUE TITLE
Debugger controls not working (step in/out/over)

### ISSUE THREAD

**Issue by thinkv** [0xd4d/dnSpy#37]
Seems that in the latest pull the debugger controls don't appear active even when it has reached a breakpoint.

**Comment by 0xd4d** [comment]
Is it the toolbar buttons you're talking about? If so CommandManager.InvalidateRequerySuggested() might need to be called somewhere. It's already called when a new debug event is received, but perhaps it's not enough.

**Comment by thinkv** [comment]
The toolbar buttons are disabled and the shortcut keys don't work. Only
options are pause and stop as if it hasn't actually hit a breakpoint. But
the breakpoint is highlighted and app is stopped.

**Comment by 0xd4d** [comment]
Could you tell me how to reproduce this because I'm not seeing it when I test debugging something.

**Comment by thinkv** [comment]
1. Run dnspy x86 as administrator
2. Press run debugger and pick the exe
3. Select break at entry point only on start
4. Search for method I want to debug whilst app is paused on entry point
5. Add breakpoint. And resume app
6. App hits breakpoint. But no debugging functions are available. App
thinks it's still running.

**Comment by thinkv** [comment]
Oh and after adding breakpoint I selected to view locals.

**Comment by 0xd4d** [comment]
I can still not reproduce it. Have you tested other executables? Is the debugged program running or is it just dnSpy that thinks it's running (since the controls are disabled)?

**Comment by 0xd4d** [comment]
Try to close the locals window or disable function evaluation in the settings. Does that help?

**Comment by thinkv** [comment]
The program is running. And I have no problems doing the same thing with an
older build of dnspy. Just the latest ones causing this issue :(

**Comment by 0xd4d** [comment]
It's new code, so needs testing. Anyway, I just posted something right before you posted, so try that suggestion first.

**Comment by thinkv** [comment]
Okay, when i hide the locals view, it works as expected.

**Comment by 0xd4d** [comment]
Could you email me the program you're debugging and what OS you're using? de4dot@gmail.com
