### ISSUE TITLE
Open assembly without locking file

### ISSUE THREAD

**Issue by maritaria** [0xd4d/dnSpy#371]
I've build a tool that uses dnlib to mod an assembly, and I want to run this tool while having an assembly open in dnSpy. This cannot be done easily as of now because dnSpy puts a lock on the file that prevents another application from writing to the dll.

To solve this problem I propose to not lock the file, but keep a watch on it and notify the user when the assembly has changed. Optionally reloading the assembly.

**Comment by 0xd4d** [comment]
Uncheck this: `Options -> Environment -> General -> Use memory mapped I/O`
