### ISSUE TITLE
An exception occurred when decompiling this method

### ISSUE THREAD

**Issue by Nuklon** [0xd4d/dnSpy#376]
Pretty much everything has that message.  Editing anything in code or IL results in build errors. I'm using the latest snapshot and I also tried the dev branch.

file.exe.txt
The file is from this setup here

(it seems to be protected by ConfuserEx)

**Comment by 0xd4d** [comment]
The methods are probably encrypted, so you need to decrypt them. Encrypted data = garbage unless you can decrypt them. Garbage in == garbage out.
