### ISSUE TITLE
DnSpy just work in first time open only

### ISSUE THREAD

**Issue by karmamaster** [0xd4d/dnSpy#377]
Hello,
As in the title, the problem here is: "DnSpy just work in first time open only". I tried to run the Dnspy x86.exe and it is working very good for the first time I open it. After I close and open Dnspy x86.exe again, it is not working (not open the application window) and then I tried to open DnSpy.exe, this exe is open the application window but I can not do anything on tool except of open an exe in tool by "Ctrl + O" (Can not drag the exe to DnSpy too), can not delete the exe file out of "Assembly Explorer" too!

I am using window 10 and this is a fresh installed window. This is a weird error of DnSpy which i have never seen before!
Thanks

**Comment by 0xd4d** [comment]
Redownload the files, compare if all the files are in the original folder.

**Comment by karmamaster** [comment]
I have tried to redownload the files but it not solve the problem! still can't work after the first time open. I firgure out that it just happen the same as extract the files again. I am trying to reinstall the window

**Comment by 0xd4d** [comment]
First check if it's your anti-virus software, some are worse than others and have many false positives.

You could also try deleting your dnSpy.xml file or compile dnSpy from source code.

**Comment by karmamaster** [comment]
I can make sure that it is not because AV because I don't use any AV on my PC. Tried to delete the xml file but the problem still there

**Comment by 0xd4d** [comment]
Windows Defender could still be running in the background, it's possible that it's the one causing problems.

Use [this link](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts) to download latest master build.

Verify that no file has been removed from the folder where you extracted the zip file.

If the dnSpy window doesn't show after you double click dnSpy, use task manager to check if dnSpy is running.
