### ISSUE TITLE
NullReferenceException when using a background image

### ISSUE THREAD

**Issue by TedHankey** [0xd4d/dnSpy#378]
1. Fresh install - no dnSpy.xml
2. View -> Options -> Background image -> use any image
3. Decode an assembly or close and reopen dnSpy

Result: null ref

**Comment by 0xd4d** [comment]
Download the fix here (once compilation has completed): https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts

**Comment by TedHankey** [comment]
Thanks for the great app and quick fix!
