### ISSUE TITLE
export to solution   compile error

### ISSUE THREAD

**Issue by gitlsl** [0xd4d/dnSpy#379]
now I can export an exe to solution, but there are some error when complie
1. generation code may be  if(xxEnum.a == 1) this will get error  may be  if(xxEnuma.a == (xxEnum)1) will better
2.some function need  `output`  but generation code is    `ref `

**Comment by TiberiumPY** [comment]
It's almost impossible to compile generated solution from decompiled code

**Comment by UlyssesWu** [comment]
It's almost impossible to **directly** compile generated solution from decompiled code

另外，DnSpy的反编译组件来源自ILSpy，如果你想提意见，可以去那边。不过我可以说的是，我对比过四五款同类工具，DnSpy（&ILSpy）的反编译代码可用性已经是比较好的了（虽然在可读性上较差），通常只需少量改动即可达到可编译状态。不劳而获搞人代码还想一步到位，懒也要有个限度……

**Comment by 0xd4d** [comment]
It's recommended to edit the assembly without creating a solution (eg. `Edit C# Code` or `Edit Visual Basic Code` or `Edit IL Instructions`)

**Comment by gitlsl** [comment]
@UlyssesWu  确实dnspy的反编译效果是比较好的，我原先不知道他是这个组件来是ilspy,我去那边看看
@0xd4d   yes ，it's very nice if we can `Edit Method (C#)` , but this app redirect dependence dll version in app.config, so I can not `Edit Method (C#)` due to `compile  error`
