### ISSUE TITLE
Property methods and async structs not visible

### ISSUE THREAD

**Issue by 0x63dev** [0xd4d/dnSpy#380]
Property methods and async structs that are compiler generated are only visible and can be navigated to if you switch from C#/VB to IL code.

Attempting to navigate to async structs otherwise will result in code view setting the caret on top of the file.
Also in the type list view on the left you can't expand properties to get_ and set_ methods if you dont switch to IL.

**Comment by 0xd4d** [comment]
Try the latest build or enable 'show all compiler generated classes' option.
