### ISSUE TITLE
Is it possible to target .NET Framework 4.5.2?

### ISSUE THREAD

**Issue by bert2** [0xd4d/dnSpy#381]
Can dnSpy be compiled to target .NET Framework 4.5.2? Unfortunately, installing 4.6 is not an option right now.

I tried changing the target framework of every project in `dnSpy.sln`, that targets 4.6, to 4.5.2. I also added an additional framework node to a bunch of `project.json`'s:

```json
"frameworks": {
  "net46": {},
  "net452": {}
},
```
But now I get lots of errors when the NuGet packages are restored. E.g.:

> Package Microsoft.CodeAnalysis.CSharp.Scripting 2.0.0 is not compatible with net452 (.NETFramework,Version=v4.5.2) / win. Package Microsoft.CodeAnalysis.CSharp.Scripting 2.0.0 supports: netstandard1.3 (.NETStandard,Version=v1.3)

**Comment by 0xd4d** [comment]
You can try removing everything that uses Roslyn and change Array.Empty<XXX>() calls to new XXX[0].

**Comment by 0xd4d** [comment]
BTW, Win7 SP1 and later OSes can install .NET Framework 4.6. I don't plan on supporting anything older than that.

**Comment by TiberiumPY** [comment]
Even Wine supports .NET Framework 4.6, so just update your system :)

**Comment by bert2** [comment]
@TiberiumPY, as said earlier, updating is not an option. Otherwise I obviously wouldn't bother to even try targeting net452.

>You can try removing everything that uses Roslyn

Could you please elaborate on that? Do you mean removing all references and usages of the `dnSpy.Roslyn.*` assemblies?

**Comment by TiberiumPY** [comment]
@bert2 but you can at least run Windows in VM or Linux with Wine :)

**Comment by 0xd4d** [comment]
@bert2 : All projects with a project.json that references roslyn are the roslyn assemblies.

**Comment by bert2** [comment]
@0xd4d, ok thanks. I got compiled against net452. Will test it later.

**Comment by 0xd4d** [comment]
Did it work or did it blow up your computer? 😃

**Comment by bert2** [comment]
@0xd4d Hey, sorry for the late reply.

As I said ealier compiling worked with your suggestions. I was able to run dnSpy on a net452 machine and could successfully decompile and debug some assemblies.

Thanks for the help!
