### ISSUE TITLE
Regression: "Attach to Process" no longer works in dbg branch

### ISSUE THREAD

**Issue by janbbeck** [0xd4d/dnSpy#382]
In the Master branch, Attach to Process works as expected, by bringing up a process window to chose from.
In the dbg branch, nothing happens after selecting Attach to Process.

I tested this by building fresh clones from github on Win8 x64 and Win7 x64 machines using VS 2017

**Comment by 0xd4d** [comment]
It's a work-in-progress branch and not yet finished. ;)

Use the master branch instead.

**Comment by janbbeck** [comment]
Ah. Sorry about that.
