### ISSUE TITLE
how can i get  Visual Studio SDK in VS 2017?

### ISSUE THREAD

**Issue by danperor** [0xd4d/dnSpy#384]
I know it is not suitable to ask this question here? But I recently installed VS2017 on a new machine, and when I compile the project  I encountered a problem, I do not know where to download vssdk? Microsoft's official VSSDK installation instructions are also based on VS2015! as follows：https://msdn.microsoft.com/zh-tw/library/mt683786.aspx

**Comment by 0xd4d** [comment]
Try this:

![vssdk](https://cloud.githubusercontent.com/assets/1060731/23936334/cf15e722-0951-11e7-9e57-e144d2900a3a.png)

**Comment by danperor** [comment]
thank U @0xd4d
