### ISSUE TITLE
Interface get lost in assembler editor

### ISSUE THREAD

**Issue by FickoDeLux** [0xd4d/dnSpy#386]
Hi!
First at all I am quite new to this tool but I do like it.
So, I do not want to shout "bug" but this may be one.

I am trying to compile a little class but the assembler editor do not recognize the interface definition:"Engine" in my case.

I did not modify anything jet this is how it is presented from dnspy.
![engine](https://cloud.githubusercontent.com/assets/19427606/24011625/95b4f34e-0a7b-11e7-8da5-2fd85dbbce54.jpg)

and here is the Interface definition:
![iengine](https://cloud.githubusercontent.com/assets/19427606/24011701/c36129f2-0a7b-11e7-9cc1-742c0b7c38f9.jpg)

I like to do to add an other: 
"Engine GetEngineObject()" with more parameters, which is implemented in the Type Library but missing as declearation.

How can I make the assembler to "see" what the dissassembler can "see" ?

**Comment by 0xd4d** [comment]
Seems like the compiler doesn't know about the assembly where the interface is defined. You can try adding that reference manually and see if it helps. Click the icon just to the right of the `main.cs` combobox in the lower left corner of the `Edit Code` window.

**Comment by FickoDeLux** [comment]
Thanks for Your input, sadly it doesn't realy helped.

Both declarations are in the same assembly (dll) listed one after the other, like:
> Engine
>IEngineLoader

You can see the namespace is the same.

I tried to copy/paste the interface into the assembler it had sort of worked but run into a "chain effect"
there were than other things were not able to find and so on.

Any other idea?

**Comment by 0xd4d** [comment]
Try to compile the code (without modifying any code) and paste the errors here

**Comment by FickoDeLux** [comment]
>CS0246 The type or namespace name "Engine" could not be found(are you missing a using directive or an assembly reference?)

Not realy on the point being both in the same namespace.

**Comment by FickoDeLux** [comment]
I have managed to put together a minimalistic test case may help:

[InterfaceBug.zip](https://github.com/0xd4d/dnSpy/files/851715/InterfaceBug.zip)

**Comment by 0xd4d** [comment]
The types are embedded COM types, see the `TypeIdentifier` attribute.

When dnSpy edits an assembly, it creates a temporary assembly that references the original assembly. However, since these are embedded COM types, you can't reference them from this new temporary assembly, even if they're public.

The only solution at the moment is to copy and paste those interfaces you need into the code editor.

**Comment by 0xd4d** [comment]
The fix is to paste the embedded COM types into the edit code dialog box.
