### ISSUE TITLE
Edit Code: don't add embedded COM types to original assembly if they already exist

### ISSUE THREAD

**Issue by 0xd4d** [0xd4d/dnSpy#388]
#386 

```C#
	[Guid("11001000-0000-1056-976E-008048D53AE3")]
	[TypeIdentifier]
	[ComImport]
	public interface IEngine {
		[DispId(97)]
		void LoadPredefinedProfile([MarshalAs(UnmanagedType.BStr)] [In] string ProfileName);
	}

	[TypeIdentifier]
	[Guid("110010EC-0000-1056-976E-008048D53AE3")]
	[ComImport]
	public interface IEngineLoader {
		[DispId(1)]
		[return: MarshalAs(UnmanagedType.Interface)]
		Engine GetEngineObject([MarshalAs(UnmanagedType.BStr)] [In] string ProjectId = "0");
	}

	[Guid("11001000-0000-1056-976E-008048D53AE3")]
	[CoClass(typeof(object))]
	[TypeIdentifier]
	[ComImport]
	public interface Engine : IEngine {
	}
```

Edit Class (`Engine`) and paste `IEngine` so it compiles. The duplicate `IEngine` shouldn't be renamed, but ignored since it already exists (it's type equivalent to an existing type in the original assembly)

**Comment by 0xd4d** [comment]
All referenced embedded COM types should be automatically included (added to main.g.cs)

**Comment by FickoDeLux** [comment]
Would be nice to have a more meanungful error message to this as well instead of "CS0246" with hint
what to do. IMO

**Comment by 0xd4d** [comment]
It's the compiler's error message that is shown. With this fix, it won't be shown at all.
