### ISSUE TITLE
Feature request: Add variable watch window

### ISSUE THREAD

**Issue by vanvleet** [0xd4d/dnSpy#39]
Please, please add a variable watch window so you can tag variables to be monitored throughout the debug process. It's the only flaw in an otherwise terrific app! Thank you!

**Comment by ylepikhov** [comment]
+1

**Comment by dealdiane** [comment]
+1 This is something that is invaluable when debugging. ATM, it's very hard to find out what the values are especially when expanding the object in the `Locals` window doesn't show everything you need.

**Comment by riwofeb** [comment]
+1

**Comment by jrt324** [comment]
+1 This feature is very useful !!

**Comment by galaris** [comment]
+1 Would be great to have :)

**Comment by Ferouden** [comment]
+1 And in the latest release I can't add a watch. Is it not complete yet?

**Comment by SlowLogicBoy** [comment]
As you can see issue is open so it's not completed :).

**Comment by 0xd4d** [comment]
Yes, it hasn't been finished yet. It will be in v4.0, see the milestone.
