### ISSUE TITLE
Make it optional to close the editor dialog on successful compilation

### ISSUE THREAD

**Issue by FickoDeLux** [0xd4d/dnSpy#390]
The current behavior (to close on succesful compile) is a little bit weird.
Like VS would close the current project after every accomplished compile would be anoying, woulden't it?

**Comment by 0xd4d** [comment]
I think it's the correct behavior. dnSpy's not an IDE. Everything you modify is stored in an assembly, not in source files.

**Comment by FickoDeLux** [comment]
I understand what You are saying I was just looking it from productivity point of view.
Mostly you are working "bottom up" in the editor, deleting almost everything and slowly bulding up
your code watching what can be compiled what not.

So if the dialog closes you can go back where you where with undo (sofar I observed) but it isn't a strait forward way to doing things. (IMO)
It would be more "conventional" to have undo button in the editor and having an option not to close it.
Like an optional editor behavior selectable by "options" preference.
- Just saying -

**Comment by 0xd4d** [comment]
This is not something I expect I'll ever implement so closing it.
