### ISSUE TITLE
Add support for Enums

### ISSUE THREAD

**Issue by J-kit** [0xd4d/dnSpy#392]
Hey,
Currently, dnspy doesn't decompile enums correctly, could you add this feature?
Thank you!

**Comment by 0xd4d** [comment]
Could you provide more info? Show current code and what you expect it to look like.

**Comment by J-kit** [comment]
Optimal solution: https://gist.github.com/J-kit/fd9af8aade2674997c1b454ee32d9b0a
DNSpy: https://gist.github.com/J-kit/b8e570b19a1d24cd4571ab3961d94ad1

**Comment by 0xd4d** [comment]
It's not an enum. Try the latest build since it has better Roslyn support, https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts

**Comment by J-kit** [comment]
Oh sorry I meant IEnumerables :P
Thanks
