### ISSUE TITLE
Can't attach to the Unity built executables

### ISSUE THREAD

**Issue by DmitriyYukhanov** [0xd4d/dnSpy#393]
Hey, 

Unity game engine produces unmanaged executables (both x86 and x64) which run managed (Mono) code inside.
But they are not visible at the "Attach to Process" window.
And looks like it's impossible to debug managed assemblies even if we run unmanaged executable directly from dnSpy using "Debug an Assembly" command.

Here are x86 and x64 builds for your reference (compressed with LZMA2):
http://codestage.net/dump/share/2017.03/builds.7z

Assemblies of interest are placed at the Managed folder.

**Comment by UlyssesWu** [comment]
Unity games use a built-in mono rather than CLR in your system. I'm afraid dnSpy only support CLR debugging for now.

> And looks like it's impossible to debug managed assemblies even if we run unmanaged executable directly from dnSpy using "Debug an Assembly" command.

Not exactly. You can debug them only if they runs on CLR, e.g. Visual Studio: "devenv.exe".

**Comment by TiberiumPY** [comment]
You can debug Unity assemblies if you will add support for it

**Comment by 0xd4d** [comment]
@DmitriyYukhanov 

Debugging assemblies loaded by Mono isn't currently supported. I plan to support this in some future version.

Since you probably already have the source code, why don't you use Visual Studio?

**Comment by TiberiumPY** [comment]
@0xd4d he probably made this build to test this feature and give this build to you. So he probably want to do this for some game

**Comment by DmitriyYukhanov** [comment]
Thanks for your reply, @0xd4d (and other guys)!

I don't have a source code in my case (I've created a sample project just to show you a problem).
Customer sent me a build to let me debug part of it on my side to catch a bug in my code since he can't send all sources.

For this case I'll find workaround hopefully (asked customer to make a debuggable build and will try to debug my code from the VS).

But in future, it would be great to be able to debug Mono assemblies in dnSpy out-of-the-box!
As a Unity plugins developer (which are often used in third-party builds I have no sources from), I'm eagerly looking forward to this feature.

P.S. thanks for all your priceless work on de4dot, dnLib, dnSpy and other .NET tools for reversers and hackers!

**Comment by Avatarchik** [comment]
Hi! Are there any updates on this topic?

**Comment by 0xd4d** [comment]
Try the latest master build and see #652
