### ISSUE TITLE
Not working: Options->Decompiler->IL (ILSpy)->Show IL opcode comments

### ISSUE THREAD

**Issue by qaqz111** [0xd4d/dnSpy#394]
No opcode comments came out whether enable this option or not in IL decompile mode.
Latest build from release page, dnSpy v3.0.0 6ed77d4 released on 8 Nov 2016.

**Comment by TiberiumPY** [comment]
This was probably fixed, download latest build from AppVeyor

**Comment by TiberiumPY** [comment]
https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts

**Comment by 0xd4d** [comment]
It shows the opcodes' XML doc comments, and those are located in mscorlib.xml. Perhaps you don't have this file? Enable 'show XML documentation in decompield code' in C# decompiler settings, and open mscorlib and check if you see comments.

**Comment by qaqz111** [comment]
Where does the program load from? My mscorlib.xml is located at localized sub dirs while installed with VS (with chinese language pack, my system is win10x64pro chinese version). I searched my disk and found 3 copies of different .NetFramework versions, they are located at:

C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\zh-Hans\mscorlib.xml
C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.X\zh-Hans\mscorlib.xml
C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.0\zh-Hans\mscorlib.xml

I'm sure the [Show XML documentation in decompiled code] for both C# and IL mode were enabled, and [Show IL opcode comments] for IL mode was enabled, but can not see comments both in C# mode and IL mode decompiled codes.

**Comment by qaqz111** [comment]
Well, I copied xmls out of localied sub dirs, the comments were showed correctly now. So it is obvious that the program does not search localized sub dirs so that the decompiled code can not display comments correctly. May be consider support this feature in next version?

**Comment by 0xd4d** [comment]
I believe the bug is [here](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy.Contracts.Logic/Decompiler/XmlDoc/XmlDocLoader.cs#L200) . It only checks for english language files.

**Comment by 0xd4d** [comment]
The bug is in [this method](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy.Contracts.Logic/Decompiler/XmlDoc/XmlDocLoader.cs#L184). It first checks the current language, then english.

It uses only the two-letter code, and your current language seems to be zh-Hans which is clearly not two letters.

**Comment by 0xd4d** [comment]
The fix should probably first try the `Name` property, and if it fails try `TwoLetterISOLanguageName`. I think that will solve your problem.

**Comment by qaqz111** [comment]
Thanks. I tried modify this method in dnSpy, but can not compile due to some compiler generated identifiers which named likes `<>c` or '<XXX>xxx` that lead to compiler errors. Fortunately, it's OK to make a copy of xml file at v4.6.2 directory for it working correctly. I'm looking forward to next version now. Great thanks to your works, this tool helped quiet a lot.

**Comment by 0xd4d** [comment]
Try the latest build, not latest version. Or better yet, modify the actual source code, it's open source. ;)

**Comment by qaqz111** [comment]
Do you mean this one?
https://ci.appveyor.com/project/0xd4d/dnspy/build/artifacts

I did tried this one, of dbg branch version x.x.457, but it seems that the bug is not fixed yet.

Besides, the debugger can not work, F9 got no response and no breakpoint set, and will stuck when run program in debug mode with `Break at` set to `Module .cctor or Entry Point`. So I rollbacked to x.x.444.

**Comment by qaqz111** [comment]
About the debugger's issue mentioned above, there are some detailed information.

- F9 got no response and no breakpoint set
- The `Debug->Windows->Breakpoints (Ctrl+Alt+B)` got no response and breakpoint list window do not appear
- If run program with `Break at` set to `Don't Break`, the program will run correctly, but the debugger will stuck if run program with `Break at` set to `First LoadClass Event` or `Exe's First LoadClass Event` or `Module .cctor or Entry Point` or `Entry Point`
- The debugger do not break with `Break at` set to any other event

And, there are some other UI problem on my machine:
- The initial info dialog window(This is a dev build of ...) cutted half of `OK` button due to the window's height is not enough
- The Debug Program windows cutted half of last line of controls(lable `Break at` and list box beside it) and the vertical scroll bar appears at right side of this window

**Comment by 0xd4d** [comment]
> About the debugger's issue mentioned above(build x.x.457), there are some detailed information.

Did you read the message box that popped up when dnSpy started? It's the one in the picture above? :)

About the windows, could you start a new issue about this and provide this info:

- OS + OS Version,
- .NET Framework version
- DPI (looks to be 96)

**Comment by qaqz111** [comment]
Yes of course I noticed that message box so that I'm not creating a new issue complaining about debugger but rollbacked to x.x.444 ;)

The new issue's thread with environment info: #399

**Comment by patricksadowski** [comment]
I've created and linked a pull request that should solve your issue. The artifacts are located here: https://ci.appveyor.com/project/0xd4d/dnspy/build/x.x.496/artifacts
