### ISSUE TITLE
How to debug hosted c++

### ISSUE THREAD

**Issue by ajqfju** [0xd4d/dnSpy#396]
I was doing a project "SCANIA" met c# and c++ mixed development, not to see the value of the variable c++ when debugging, can only see the memory address, this adjustment is not convenient to do not know how to solve. Because the company cannot access the Internet cannot capture image.

**Comment by UlyssesWu** [comment]
不好意思，您的英语我看得真的是有些醉了。。。 😭 

dnSpy仅可用于调试.NET代码（C#、VB、C++/CLI的托管部分），并不是用于C++的调试器。既然您是“逆向工程师”，何不使用IDA或OD来调试C++？

dnSpy only debugs .NET code, it's not designed for C++ debugging.

**Comment by ajqfju** [comment]
居然可以用中文。我调试的这个工程使用了托管c++和c#开发，在底层部分使用了托管c++，我现在想跟踪一些数据不知道如何在dnspy中查看，我现在的解决办法是，在dnspy中看内存地址，然后使用OD来跟踪。

**Comment by UlyssesWu** [comment]
> 居然可以用中文

不，尊重作者，应该使用英文。但是当我认为这是作者很难理解的中国式英语的时候，我才会给一些中文提示。以后还是请用（**更标准的**）英文提issue（建议酌情参考在线翻译，不要过于自信）。

托管C++（我相信您指的是C++/CLI，它是原“托管C++”【Managed C++】的进化）是本机（Native）代码和托管代码（IL）的融合，并不是把C++全部编译成了托管代码。对于已经编译成本机代码的部分，没有元数据信息，也就无从还原其数据结构，自然只能用C++的调试方式去调试（在托管的层面上，如您所见，只能得知地址），这不是本工具的缺陷，而是确实难以实现的。您多了解一下C++/CLI就会明白了。

_He is asking about how to get vars' values in C++/CLI code (I believe he means the native part) when debugging in dnSpy. AFAIK it's not that easy except inspecting the memory._

**Comment by ajqfju** [comment]
你好 UlyssesWu,非常感谢你，我的英语会努力改进。C++/CLI 问题目前已经用 Ollydbg 解决。非常感谢你的回答，这个答案令我非常满意。

Hi UlyssesWu, thank you very much, my English will improve. C++/CLI problem has been solved using Ollydbg。Thank you very much for your answer。

**Comment by UlyssesWu** [comment]
感谢您的肯定，如已无问题请关闭issue以告知作者。

Thanks. Don't forget to close issue if you are clear now.
