### ISSUE TITLE
Add a new class and compile problem

### ISSUE THREAD

**Issue by cz3kit** [0xd4d/dnSpy#398]
Hey :) I found your software and I think it is nice. I feel it is easy to modify code. There is one problem I have regarding adding new code into an application and it would be nice if someone could explain or help me out what I am doing wrong. 
I started [here](https://cybersecurity.cs.wright.edu/forums/viewtopic.php?t=11) to dig around and started to use  the password checker exe. He refers to ILSpy but I had been doing it dnSpy. 
In the next step I would like to add code to the exe.
Here is how the exe looks when I open it.
![step1](https://cloud.githubusercontent.com/assets/14347871/24296496/9144a7c8-105c-11e7-8d39-7df42e0aaeb3.PNG)
I copied the PasswordChecker Form1 Code and added a new class (Add class (C#)) and changed the name to Form2. 
![step2](https://cloud.githubusercontent.com/assets/14347871/24296551/c3bd1f50-105c-11e7-8604-1ebd1cda9721.PNG)
After that I changed the code in the main from form1 to form2 and wanted to compile it. The result is in the last picture.
![step3](https://cloud.githubusercontent.com/assets/14347871/24296672/4061b156-105d-11e7-8a64-b42c0fcdbda6.PNG)
What else do I have to change in order to make this work? I appreciate any help :)

**Comment by 0xd4d** [comment]
Try saving the file first. The compiler can't see any changes until you've saved it (your changes are only in-memory).

This issue looks like a dupe, see #316

**Comment by cz3kit** [comment]
Alright. I saved it and everything works like a charm. Thank you a lot :)
