### ISSUE TITLE
The UI window‘s size appears not correctly with dbg branch build

### ISSUE THREAD

**Issue by qaqz111** [0xd4d/dnSpy#399]
There are few UI problems on my machine.
The environment info:
- Win10x64pro chinese, Version 1607 (OS internal version 10.0.14393.953)
- .NET installed up to v4.6.2 with a VS2017 up to date installation
- The desktop DPI is 96(custom zoom level of 100% through Windows' control panel, this setting have not been manually changed)
- i7-4700MQ with intel HD Graphics 4600(plus a GTX765M GPU)

The presentations:
- The initial info dialog window(This is a dev build of ...) cutted half of `OK` button due to the window's height is not enough
![1](https://cloud.githubusercontent.com/assets/3367034/24321742/1d13fb36-118f-11e7-955f-d1326dace991.png)

- The Debug Program window also cutted half of last line of controls(lable `Break at` and list box beside it) and a vertical scroll bar appears at right side of this window due to the window's height is not enough
![2](https://cloud.githubusercontent.com/assets/3367034/24321748/2860f566-118f-11e7-8bac-94cc98431294.png)

**Comment by 0xd4d** [comment]
I can't repro the missing height, instead mine gets extra height. There's supposed to be a 5px margin below the button, just like it is on the right of it. The XAML uses `SizeToContent="Height"`, It's possible that it's a WPF bug but I have to verify it.

![pic1](https://cloud.githubusercontent.com/assets/1060731/24332803/0a011272-124d-11e7-93a3-23a2cb92b5ef.png)

BTW: Alt+PrtScn takes a picture of the current window only.

**Comment by 0xd4d** [comment]
Seems to be related to [this](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy.Contracts.DnSpy/Controls/MetroWindow.cs#L75)
