### ISSUE TITLE
Maybe add an option to show only single method's code when navigating to it

### ISSUE THREAD

**Issue by Uriel6575** [0xd4d/dnSpy#40]
I'm trying to switch from ILSpy to dnSpy and so far have found it quite handy and advanced. So thanks for a great job. But there are still a couple of nuisances that bother me.
One of them is that it feels inconvenient when you navigate to a method from code or analysis (not from a tree), a whole source code of a class is shown and a method is centered on the screen. When you try to grasp the program flow you'd like to see only one method you are working with, and not it's surroundings.
Though I understand it may be only my point of view. So it would be nice if you add such an option.

**Comment by li0nsar3c00l** [comment]
Options > Display > uncheck "Decompile the full type insted of a single field / method / etc"

**Comment by Uriel6575** [comment]
Works for me, thank you.
I was misled by the word "decompile", because in my mind it was like assembly already should have been decompiled when I jump from one class method to another. :)
