### ISSUE TITLE
Having problems debugging referenced .dll

### ISSUE THREAD

**Issue by kuskmen** [0xd4d/dnSpy#402]
Hi, I am using dnSpy for reverse engineering a lot really great tool , but now I am trying to debug some referenced dll in our company website solution. And I am trying to attach to the PID that is running our website , but when I try it says "Could not start debugger. Error: This process has already been attached." while it clearly isn't...

**Comment by 0xd4d** [comment]
That's an error message from the CLR. If what you're saying isn't true, I suggest you open an issue @ coreclr

**Comment by kuskmen** [comment]
Okay , but is this the right way to do it anyway? I am building one solution I am attaching to the process and debugging the referenced .dlls in this process ? Is this how it works?

**Comment by 0xd4d** [comment]
It's better to let dnSpy start the executable, if possible. If you attach to a process, it will most likely be optimized. If you can't start it from dnSpy, then you could [try this](https://msdn.microsoft.com/en-us/library/9dd8z24x(v=vs.110).aspx)

**Comment by kuskmen** [comment]
The thing is I am trying to debug class library and I don't have any executables, but I will try the link you sent me and I will let you know if it worked, thanks again!
