### ISSUE TITLE
Feature request: breakpoint that doesn't break but log

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [0xd4d/dnSpy#405]
I think it would be very useful to be able to put a breakpoint that, when hit, logs some variables and then (optionally?) continues. It would log this to a tool window where it can be later exported to a file, in JSON format or in plaintext.

Things that could be logged:
* values of local variables
* stacktrace
* a category
* time (since execution or system time)
* amount of times hit, see paragraph below

Optionally, don't log hits when there was already a hit with variables set to certain values. For example 
if a breakpoint is hit and variable A is 10 and variable B is 20, don't log the next hit where the variables are like this but maybe increase the hit counter.

The reason I'm proposing this is because I'm currently working with assemblies that are obfuscated with Eazfuscator, so all strings are replaced with a method call that gets the string from encrypted/compressed storage. This would be a good way to "map" these strings. It would also be useful to analyze methods and understand what they do based on the variables inside the methods.

**Comment by 0xd4d** [comment]
Tracepoints will be added in v4.0

**Comment by 0xd4d** [comment]
Get latest beta
