### ISSUE TITLE
Is it possible to read variables from a function cond on a breakpoint?

### ISSUE THREAD

**Issue by kcaswick** [0xd4d/dnSpy#408]
I'm trying to use the scripting, and it seems like the capabilities of a function passed to CreateBreakpoint() cond parameter are very restricted. When inside that function, IDebugger doesn't ever seem to have an ActiveFrame, or any way to read local variables.

Also, as an alternative, I don't see any events exposed to scripting that would let me set up an action to happen once execution is fully paused and ActiveFrame is available. 

Am I missing something, or is this really not possible from the Debugger's Scripting interface?

**Comment by 0xd4d** [comment]
To use it you need to know about the [CLR ICorDebug API](https://msdn.microsoft.com/en-us/library/ms404520(v=vs.110).aspx). This whole think will be removed in v4.0.

OnProcessStateChanged gets raised when the process gets paused or starts running again. You can inspect State/PauseStates to figure out what happened.

**Comment by kcaswick** [comment]
Thank! OnProcessStateChanged appears to be able to do most of what I want, just with a lot more hoops to jump through to detect if it is the breakpoint I want, and avoid infinite loops when evaluating inside the event.
