### ISSUE TITLE
How can I inject assembly reference into the assembly ?

### ISSUE THREAD

**Issue by jeason1997** [0xd4d/dnSpy#409]
Hi, dear 0xd4d, is there any way to inject assembly reference into the assembly ?
你好，请问dnSpy应该如何注入程序集？我现在都是先打开Reflector注入后再用dnSpy来编辑。

**Comment by CreateAndInject** [comment]
你应该是在dnSpy里用C#来修改吧，在窗口的左下方，"main.cs"框旁边，有两个按钮用来添加程序集引用

**Comment by jeason1997** [comment]
@CreateAndInject 感谢，我找到答案了，藏得有点深。
thanks, i found the answer : https://github.com/0xd4d/dnSpy/issues/357
