### ISSUE TITLE
Code Analysis Hangs

### ISSUE THREAD

**Issue by bryongloden** [0xd4d/dnSpy#411]
Greetings!

Enabling Code Analysis on Build (or Running Code Analysis from the drop-down Build menu) is causing our Visual Studio (VS) Professional 2015 with Update 3 to freeze and cease to respond to input while building the current master branch of dnSpy. From the Notification Area a Bubble is saying:

Microsoft Visual Studio is Busy
Microsoft Visual Studio is waiting for an internal operation to complete. If you regularly encounter this delay during normal usage, please report this problem to Microsoft

The freeze is unique to dnSpy. Running Code Analysis on other Solutions does not cause Code Analysis to hang. And, if we disable Code Analysis on Build for dnSpy, the problem goes away.

Our operating system is Windows 10 Pro (x64), and our .NET Framework version is 4.5.2. And yes, the hang also occurs for us on Windows 8.1 Pro (x64).

Signed-off-by: Bryon Gloden, CISSP® <cissp@bryongloden.com>

![screen shot 2017-04-11 at 4 03 06 pm](https://cloud.githubusercontent.com/assets/3155274/25049432/d367f7e0-210f-11e7-8197-a4078ce88c1e.png)
Image #1: Microsoft® Visual Studio® 2015 Code Analysis Spell Checker

![screen shot 2017-04-11 at 4 37 27 pm](https://cloud.githubusercontent.com/assets/3155274/25049431/d35f061c-210f-11e7-93d9-b46603323af1.png)
Image #2 Visual Studio 2015 Hang Bubble

**Comment by 0xd4d** [comment]
Seems to be a Visual Studio issue.
