### ISSUE TITLE
Nested Methods Invisible

### ISSUE THREAD

**Issue by asdfgasdfsafgsdfa** [0xd4d/dnSpy#412]
```
static void Main()
{

//... some removed code...
			Task.Run(async ()=>
			{
				TcpClient client = new TcpClient();
				await client.ConnectAsync("localhost", 30000);
				
//... some removed code...
				
				async ValueTask<byte[]> ReadBuffer(int length)
				{
					void ThrowClosed() => throw new Exception("Connection Closed.");

//... some removed code...
					return buffer;
				}
			});
}
```

All nested methods are invisible when opening an assembly.
You can click their name where they are used, but it will just scroll to the top.

![dnspy-x86_2017-04-16_07-19-14](https://cloud.githubusercontent.com/assets/3814727/25069023/33f96dd0-2275-11e7-9871-2a75b187277e.png)

edit: I'm using dnSpy "3.x.x", FileVersion says "3.0.1.0"
It's the latest ci build from a few hours ago.

**Comment by 0xd4d** [comment]
I haven't updated it to support C#7 local methods. You can enable 'Show hidden compiler generated types and methods' and you'll at least see the method.
