### ISSUE TITLE
Not compilein unityengine and others.

### ISSUE THREAD

**Issue by hvann2000** [0xd4d/dnSpy#415]
When I press compile, dnspy marks unityengine, and many others from unity as a error

**Comment by hvann2000** [comment]
Do I need unity installed to edit unity3d .dlls?

**Comment by 0xd4d** [comment]
Make sure the files are in the same dir as the file you're editing.

**Comment by hvann2000** [comment]
The apk is in the same folder as the dnspy folder.

**Comment by 0xd4d** [comment]
You should extract all the DLL files, otherwise they won't be found.

**Comment by hvann2000** [comment]
Ok thanks

**Comment by hvann2000** [comment]
It is still marking unity terms as errors.

**Comment by hvann2000** [comment]
Ok fixed thanks
