### ISSUE TITLE
Question: Empty Method Body (Xamarin.iOS)

### ISSUE THREAD

**Issue by ay-kay** [0xd4d/dnSpy#416]
I was trying to decompile Xamarin.iOS (Mono-based runtime) DLL files using dnSpy, however, while variable, class and method _signatures_ were displayed correctly, it seems that method _implementations_ could not be decompiled. Am I missing anything here?

Screenshot of randomly selected method:
![dnspy](https://cloud.githubusercontent.com/assets/7815422/25327025/dbac378e-28d2-11e7-85d5-0357c85cd10e.png)

**Comment by SlowLogicBoy** [comment]
https://github.com/oxyplot/oxyplot-xamarin/blob/develop/Source/OxyPlot.Xamarin.iOS/PanZoomGestureRecognizer.cs#L280

**Comment by ay-kay** [comment]
Thanks. My question was however why decompiling fails?
The same behavior is exhibited on individually developed code that is not available open source.

**Comment by 0xd4d** [comment]
It could be a reference assembly. Reference assemblies rarely contain code.

**Comment by ay-kay** [comment]
Is there a way to resolve an assembly reference and to determine the location of the actual implementation?

**Comment by 0xd4d** [comment]
Have you tried downloading the source code from the link above?

**Comment by ay-kay** [comment]
Please see https://github.com/0xd4d/dnSpy/issues/416#issuecomment-296569593. I was not looking for that particular library implementation (this was just a randomly selected example). I'm rather interested in decompiling proprietary DLL code that is also included in that Xamarin app package.

**Comment by ay-kay** [comment]
Using the Mono Disassembler `monodis` all methods are printed with the following IL code:

```
 // method line 2
    .method private hidebysig
           instance default bool IsProtocolAvailable ()  cil managed
    {
        // Method begins at RVA 0x2050
        // Code size 1 (0x1)
        .maxstack 8
        IL_0000:  ret
    } // end of method DetectionService::IsProtocolAvailable
```

**Comment by 0xd4d** [comment]
There you have it, there's no code. There's nothing dnSpy can do about that.

**Comment by ay-kay** [comment]
Thanks for your responsiveness! Turned out that unlike traditional Mono/.NET, code for iOS is statically compiled ahead of time (AOT) instead of being compiled on demand by a JIT compiler. This means that the IL is only needed for metadata which is why the method bodies are stripped out to save space. The actual implementation is then found in the corresponding _.aotdata_ files.
