### ISSUE TITLE
Debugger Question / Feature Request

### ISSUE THREAD

**Issue by atom0s** [0xd4d/dnSpy#417]
Do extensions have access to the debugged process while using dnSpy's debugger? Are there events called back to extensions for things such as when the process was launched, a module was loaded, a thread was created, etc? If not, can this be something that is added?

I only saw 3 events currently passed to the extensions in the main repo inside of 'ExtensionEvent'. Not sure if there is something else to look for or if I am missing something.

Ideally, I am looking for ways to match patches to a program when it first loads, ie. CreateProcess with CREATE_SUSPENDED, do patches within an extension and resume the debugger.

**Comment by 0xd4d** [comment]
The debugger API will be public in v4.0.

What will your code need? I'm guessing: Your code must be notified before the program has started (i.e., when it's still suspended), and your code will then patch the IL in memory?

**Comment by atom0s** [comment]
Ideally, most normal debugger events exposed/raised to extensions for much more extensive debugging abilities, such as being able to write unpackers, loader hotpatches, and similar all during debugging.

Some ideas:

**ExtensionEvent.DebugProcessCreated**
_Called when the debugger has first created the suspended process._

The OnEvent callback 'obj' parameter could hold useful information such as:

``` c#
public struct DebugProcessCreatedArgs
{
    // Full path to the file being debugged.
    public string FilePath;

    // Full arguments that were passed to the process on creation.
    public string Arguments;

    // Process id of the file being debugged.
    public IntPtr ProcessId;

    // Main handle to the process being debugged. (If using CreateProcess, the one returned in PROCESS_INFORMATION.)
    public IntPtr ProcessHandle;

    // Main thread handle to the process being debugged. (If using CreateProcess, the one returned in PROCESS_INFORMATION.)
    public IntPtr ThreadHandle;
}
```
**ExtensionEvent.DebugProcessModuleLoaded**
_Called when the debugger has loaded a new module._

The OnEvent callback 'obj' parameter could hold useful information such as:

``` c#
public struct DebugProcessModuleLoadedArgs
{
    // The full path on disk to the module thread was loaded. loaded.
    public string FilePath;

    // The base address to the module that was loaded.
    public IntPtr BaseAddress;
}
```

**ExtensionEvent.DebugProcessThreadCreated**
_Called when the debugger has created a new thread._

The OnEvent callback 'obj' parameter could hold useful information such as:

``` c#
public struct DebugProcessThreadCreatedArgs
{
    // The handle to the thread that was created.
    public IntPtr Handle;

    // The id of the thread that was created.
    public IntPtr Id;
}
```

I haven't looked into the debugger code personally yet, but I'd assume its using the standard debugging API. If so, perhaps passing the full DEBUG_EVENT structure to the extensions on a debugger event such as those listed above. (And any others you feel suitable to pass to extensions.) Doing this would fill in the obj data instead of what I showed above as that data is included in that struct when those events fire.

Alongside this, having functions available to the extensions such as:

    * Debugger.Resume(); _(Allows resuming the paused process.)_
    * Debugger.Pause(); _(Allows pausing the debugged process.)_
    * Debugger.StepInto(); _(Step into, just like the UI allows.)_
    * Debugger.StepOver(); _(Step over, just like the UI allows.)_
    * Debugger.StepOut(); _(Step out, just like the UI allows.)_
    * Debugger.SetBreakpoint( <some params here for this to work as needed> ); _(Sets a breakpoint from an extension.)_
    * Debugger.RemoveBreakpoint( <some params here to make this work as needed> ); _(Removes a breakpoint from an extension.)_
    * Debugger.RemoveAllBreakpoints(); _(Removes all breakpoints.)_
    * Debugger.Detach(); _(Detach the debugger from the process.)_

Callbacks for breakpoints as well exposed and raised in extensions when a breakpoint is hit. This way an extension can check if it is a breakpoint it personally set and handle what to do afterward, such as making any modifications, dumping modules, etc.

For pre-made convenience, perhaps wrappers and calls for things such as:

    * Debugger.GetThreadContext();
    * Debugger.SetThreadContext();

Sorry for this being long-winded, just some ideas to improve the debugger < > extension communications for an even better extension framework. :)

**Comment by 0xd4d** [comment]
Most of what you wrote above is already present. It's not something that will be sent to every extension, each extension has to import the DbgManager and add an event handler.

`GetThreadContext()`: is this even useful when debugging .NET code? I assume it will return the CPU registers and related info (i.e., similar to Win32 GetThreadContext())

**Comment by atom0s** [comment]
The context ideas were just more of an idea for convenience, doesn't need to be added though. _One purpose of it would be for mixed-mode assemblies if dnSpy even supports debugging them._

Is there by chance an example extension that shows making use of the debugger?

**Comment by 0xd4d** [comment]
The new API is not finished yet, see the dbg branch.

**Comment by atom0s** [comment]
> The new API is not finished yet, see the dbg branch.

Oh, thought you referred to the main branch for this stuff. I'll check it out, thanks. :)
