### ISSUE TITLE
How i get .net module dll entry point like option in exe with right click button and start debug it??

### ISSUE THREAD

**Issue by boodyman28** [0xd4d/dnSpy#419]
there is a lot of plugins load with an application i need to decompile it
first i need to get entry point of .net .dll
this option not found like get entry point with .exe when press mouse right click button
second i need to debug dll without option debug-> attach to process because the .dll itself already loaded with application when application start 
example
when visual studio version load external dll like extensions

**Comment by li0nsar3c00l** [comment]
dll's don't have an entrypoint

**Comment by boodyman28** [comment]
big thanks but you do not answer me about how i debug dll without exe that belong to it

**Comment by SlowLogicBoy** [comment]
There is no way to do that, you need to create executable that calls that dll, and that dll methods.

**Comment by 0xd4d** [comment]
Questions have been answered, closing it.
