### ISSUE TITLE
Managed C++ name decoding/demangling

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#42]
Hi 
Two (probably) related questions.

1. While exploring a mixed mode assembly, I've found out following fact: for some reason instead of space I see the "\u0020"  string
the assembly is not obfuscated, thats a purely generated clean code

Example1
<Module>.std.basic_string<char,std::char_traits<char>,std::allocator<char>\u0020>.__dtor(ref basic_string<char,std::char_traits<char>,std::allocator<char>\u0020>3);

Example2
<Module>.std.basic_ostringstream<char,std::char_traits<char>,std::allocator<char>\u0020>.__vbaseDtor(ref basic_ostringstream<char,std::char_traits<char>,std::allocator<char>\u0020>3);

Example3
				basic_string<char,std::char_traits<char>,std::allocator<char>\u0020> basic_string<char,std::char_traits<char>,std::allocator<char>\u0020>3;
						basic_string<char,std::char_traits<char>,std::allocator<char>\u0020>* ptr6 = <Module>.std.basic_ostringstream<char,std::char_traits<char>,std::allocator<char>\u0020>.str(ref basic_ostringstream<char,std::char_traits<char>,std::allocator<char>\u0020>3, &basic_string<char,std::char_traits<char>,std::allocator<char>\u0020>3);
		
Example4
	ushort* uInt16\u0020modopt(IsConstModifier)& = ptr2;
											<Module>.ATL.CStringT<char,StrTraitMFC_DLL<char,ATL::ChTraitsCRT<char>\u0020>\u0020>.=(ref cStringT<char,StrTraitMFC_DLL<char,ATL::ChTraitsCRT<char>\u0020>\u0020>4, uInt16\u0020modopt(IsConstModifier)&);
										}

Example5
		list<int,std::allocator<int>\u0020>.const_iterator last = num;
		list<int,std::allocator<int>\u0020>.const_iterator first = *num;
		list<int,std::allocator<int>\u0020>.const_iterator const_iterator;
		bool result = *<Module>.std.find<class\u0020std::list<int,class\u0020std::allocator<int>\u0020>::const_iterator,int>(&const_iterator, first, last, ref i) != num;

		
2. A proposal:
is it possible to add an option to demangle the mangled C++ names?
example of existing names in decompiled code:

Example 1
	<Module>.CWnd.__ctor(ptr8);
									try
									{
										*ptr8 = ref <Module>.??_7CEdit@@6B@;
									}
									catch
									{
										<Module>.__CxxCallUnwindDtor(<Module>.__unep@??1CWnd@@$$FUAE@XZ, ptr8);
										throw;
									}

Example 2
catch
				{
					<Module>.__CxxCallUnwindDtor(<Module>.__unep@??1?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@$$FQAE@XZ, (void*)(&cStringT<char,StrTraitMFC_DLL<char,ATL::ChTraitsCRT<char>\u0020>\u0020>));
					throw;
				}

**Comment by 0xd4d** [comment]
1st:

The spaces are added by the C++ compiler and is part of the names. Spaces aren't allowed in identifiers in C# so they're escaped. Yes, \u0020 is not valid in identifiers in C# (AFAIK), but at least then the reader knows that it's just one identifier and not 2+.

This is not likely to be fixed.

2nd:

C++ demangling could useful, but C++/.NET assemblies are so uncommon that this is not prioiritized.

**Comment by greenozon** [comment]
Hi
let me argue on 1st, 
here are some proofs how other industrial tools do it:

original ILSpy:
http://prntscr.com/8wd4fb

latest .NET Reflector:
http://prntscr.com/8wd4yf

so having \u0020 looks like come out of the dnSpy?...
the main goal (IMHO) is the user-friendliness = readability...
thats were it comes from + of course the 2nd item.

Thanks for understanding

There is another interesting topic related to mixed mode assemblies - it is decompiling the strings into code instead of some compiler generated vairable that points to a string....
for example .NET Reflector does it, but other tools (including ILSpy) - not.

**Comment by 0xd4d** [comment]
Try to open an obfuscated assembly with ILSpy, .NET Reflector, dotPeek etc. :scream:

The space is escaped because it's not allowed in C# identifiers. If we'd let that be considered valid, any obfuscator could add spaces to names and it would look like 2 or more identifiers.

I might add an option to disable this but it's not a priority since I'm mostly interested in obfuscated files not unpacked files.

About the last part, could you show a picture?

**Comment by greenozon** [comment]
Well, I still did not get why other tools put spaces and you are concerned about it....
anyway, let it be, you are the master :)

Now, about 2nd part - that's really interesting! just take a look 
how dnSpy shows it (mixed mode assembly) 
http://prntscr.com/8wey3j
and .NET Reflector
http://prntscr.com/8weyuv
that might be a superb feature on the market!

btw, Reflector not always finely decodes the strings..... usually it also shows that complier generated crap!

PS
long time ago I've modded the SAE tool to show the real strings in hints - eg
http://prntscr.com/8wf3x6
so if you be able to show in decompiled code the real strings  ("Unable to copy..." in this case) - you be a super star!
