### ISSUE TITLE
C# Edit Class Compilation Error: Cannot convert from Class[Main.cs(9)] to Class[DLL reference to same class]

### ISSUE THREAD

**Issue by beau101023** [0xd4d/dnSpy#420]
To reproduce, open ClassLibrary1.dll in REPRO.zip with dnSpy and attempt to edit and compile TestClass in the Test namespace. (source included)

Exact compilation error: `Argument 1: cannot convert from 'Test.TestClass [Main.cs(6)]' to 'Test.TestClass [ClassLibrary1.dll]'`

[REPRO.zip](https://github.com/0xd4d/dnSpy/files/963230/REPRO.zip)

**Comment by 0xd4d** [comment]
Seems to be the same as #365

**Comment by 0xd4d** [comment]
This has now been fixed, get the latest build.

**Comment by RobbieW69** [comment]
Hey I have the latest build yet still have get this error? 

Error	CS1503	Argument 4: cannot convert from 'PlayerStats.HitInfo [main.cs(368)]' to 'PlayerStats.HitInfo [C:\Users\Robbie\Desktop\SCP\SCPSL_Data\Managed\Assembly-CSharp.dll]'	main.cs	108

2-25-2018

**Comment by 0xd4d** [comment]
Based on that error message, it's not likely that you're using the latest build or v4.5.3. Get the latest build, make sure you start it and not some older build, and if you're still having problem, create a new issue.
