### ISSUE TITLE
de4dot integration

### ISSUE THREAD

**Issue by davidgiga1993** [0xd4d/dnSpy#421]
# Proposal
Integrate de4dot for easy assembly reverse engineering from one single application.
My initial idea would be to add a context menu entry or similar for the assemblies which provides access to the de4dot functionality such as deobfuscation and obfuscation detection.

**Comment by SlowLogicBoy** [comment]
You can write plugin for that. 
Basic howto:
https://github.com/0xd4d/dnSpy/wiki/Extensions
Examples:
https://github.com/0xd4d/dnSpy/tree/master/Extensions
