### ISSUE TITLE
Exception:System.BadImageFormatException when debug an application with dnspy

### ISSUE THREAD

**Issue by gagmeng** [0xd4d/dnSpy#422]
Repro steps:

1、download the awb-1.0.38.2.exe from the mega link: 
https://mega.nz/#!eRZ2yJrI!NDyCpaaXuAXBxC2R5c26_YrwB_AwSofWgH3u01p-ehE
2、Run the installer awb-1.0.38.2.exe to complete the software installation;
3、Use dnspy to load AvailabilityWorkbench.exe and run F5 to debug the assambly;
4、The error window pops up as shown below
http://uimg.in/images/2017/05/06/V9kKSCfs.jpg
The meaning of Chinese characters in the above picture is "The string tag is incorrect".

Expected:

Debug this application correctly.

**Comment by 0xd4d** [comment]
What happens when you debug it in VS? (open the exe file, press F5)

**Comment by gagmeng** [comment]
Sorry, I can't debug it correctly with VS.  My operation may be wrong.

**Comment by 0xd4d** [comment]
You won't see any code since you don't have the source code. Just open the exe and press F5.

**Comment by 0xd4d** [comment]
You can write a loader that calls its entry point and debug it using VS (you won't see its source code just your loader).

**Comment by gagmeng** [comment]
I can't locate its entry point.

**Comment by 0xd4d** [comment]
Paste the stack trace and the text in the output window.

**Comment by gagmeng** [comment]
The locals in the output window is as shown below, but the stack trace is null.
[http://uimg.in/images/2017/05/09/ODBuFs.jpg](url)

**Comment by 0xd4d** [comment]
What I'm looking for is the output in the `Call Stack` and the `Output` windows. Open them and copy and paste the text.

**Comment by gagmeng** [comment]
The call stack of the output window is null, the text is empty.

**Comment by 0xd4d** [comment]
The file is obfuscated and detects the debugger, just as I thought, and that's why I asked you to test it in VS.

**Comment by gagmeng** [comment]
The file is obfuscated and doesn't detect the debugger, because of  other applications of the same company can debug correctly.
