### ISSUE TITLE
Modules Tab Isn't Showing

### ISSUE THREAD

**Issue by whatashoah** [0xd4d/dnSpy#423]
I reformatted my computer and reinstalled Windows. Just installed dnSpy and went to go debug a program. The 'Modules' tab was not there. Only 'Locals'. I looked through all of the settings and couldn't seem to find a setting for the 'Modules' tab. I've seen multiple other people with this issue as well.

**Comment by AlejandroEsp** [comment]
How did you solve it

**Comment by 0xd4d** [comment]
Did you try:

`Debug` -> `Modules`

or

`Ctrl+Alt+U`

**Comment by AlejandroEsp** [comment]
ok, thanks

2017-07-30 5:00 GMT-05:00 0xd4d <notifications@github.com>:
