### ISSUE TITLE
Save C# changes in source files for tracking in source control

### ISSUE THREAD

**Issue by mikeparker** [0xd4d/dnSpy#424]
Hi, this might be already possible but I can't find it.

If I edit the C# code, can I export that file as a separate file, check it into source control such that dnSpy then reads that file whenever it decompiles an assembly?

Basically I want to keep track of changes I make to an assembly and share them with others without checking in the whole assembly every time.

Alternatively, is it possible to export the whole assembly as source files so I can check them all in, and recompile afterwards?

**Comment by 0xd4d** [comment]
Ctrl+S saves the current file or Ctrl+A, Ctrl+C to copy the whole thing.

Exporting everything isn't recommended since there will be too many compilation errors.

You can save your changes to ClassName.MethodName.cs so it'll be easier to update the assembly later or share your changes.

**Comment by mikeparker** [comment]
If I save the file, then reset the assembly back to how it was originally, is there any way of getting dnSpy to automatically re-load the edited source file when I re-open dnSpy?

**Comment by 0xd4d** [comment]
Try some macros software that can replay your UI actions.

**Comment by neoedmund** [comment]
I also have the same need:  Open a .dll, add references, apply method modifications by saved C# files.
"macros software" seems not reliable.
Can anyone add a scripting/macro feature to do the thing automatically? 
Thanks.
