### ISSUE TITLE
Scripting question: Override method return

### ISSUE THREAD

**Issue by judge2020** [0xd4d/dnSpy#428]
Hello, I discovered this project recently and have a question about scripting. My objective is a simple task when using DnSpy's gui. I have this class and method

```c#
class DoStuff
{
    public static int OnePlusOne(){
        return 2;
    }
}
```

Through scripting, how can I go about overriding the return value of this?

**Comment by 0xd4d** [comment]
The assembly editor doesn't have a public interface you can use to control it.
