### ISSUE TITLE
Incorrect overloaded method in generated C# code

### ISSUE THREAD

**Issue by mjmckp** [0xd4d/dnSpy#429]
The following bit of IL:
```
	IL_0011: ldfld class [mscorlib]System.IO.BinaryWriter MyClass::writer
	IL_0016: ldc.i4.3
	IL_0017: callvirt instance void [mscorlib]System.IO.BinaryWriter::Write(uint8)
	IL_001c: br IL_00fb
```
decompiles with dnSpy to the following bit of C#:
```
this.writer.Write(3);
```

The issue is that `System.IO.BinaryWriter` has an overloaded `Write` method, and the one that is being invoked in the IL is that for `uint8`, however the C# code as generated will invoke the `Write` method for `int32`.

This is quite a serious issue, as the de-compiled code compiles without any warnings, however the output of the program as written by the `BinaryWriter` will be incompatible with the original assembly.

**Comment by 0xd4d** [comment]
This is a known ILSpy decompiler issue (dnSpy uses the ILSpy decompiler engine) and is probably something that has been fixed in their newdecompiler branch (I haven't checked).

**Comment by mrexodia** [comment]
This issue still persists...
