### ISSUE TITLE
Naming of Compiler Generated Types/Methods/Properties etc

### ISSUE THREAD

**Issue by li0nsar3c00l** [0xd4d/dnSpy#434]
I got a small suggestion regarding decompiling: It seems like compiler generated members often have "<" or ">" within their name. These names produce errors in Visual Studio after decompiling, automatically renaming them would be nice.
![grafik](https://cloud.githubusercontent.com/assets/1358820/26472231/75d20c04-41a5-11e7-9ad3-31ae8063b085.png)

**Comment by 0xd4d** [comment]
Seems like you're using 3.0.x, try latest build instead.

**Comment by li0nsar3c00l** [comment]
Oh yeah, I'm still using that, haven't used dnSpy for quite a while. My bad!

**Comment by 0xd4d** [comment]
It has some decompiler updates that should fix the problems seen above.

**Comment by XenocodeRCE** [comment]
Using latest version, when you decompile a multithreading [CompilerGenerated] method, it does have these <> symbols, I don't see the issue though.
