### ISSUE TITLE
Placeholder Names for Variables to Improve Readability

### ISSUE THREAD

**Issue by beau101023** [0xd4d/dnSpy#436]
It would be helpful to be able to designate 'nicknames' or placeholder names for variables without existing name data. In this way it would be easier to keep track of what a variable is supposed to represent.

For example, nicknaming num2 'lifeCounter' in order to improve readability of the code.

**Comment by 0xd4d** [comment]
Related: #266

You can edit locals today: `Edit IL Instructions` -> `Locals` -> add your names.
