### ISSUE TITLE
on branch dbg,there has a little problem shoule be fixed.

### ISSUE THREAD

**Issue by kingxi82** [0xd4d/dnSpy#437]
( 5e99073  )
 in the file 
 "\dnSpy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Evaluation\DbgLanguageServiceImpl.cs":

using dnSpy.Contracts.Debugger.Evaluation.Engine;
should be 
using dnSpy.Contracts.Debugger.Engine.Evaluation;

**Comment by 0xd4d** [comment]
Yes, I noticed that yesterday but hasn't pushed the fix yet because it's just a WIP branch that shouldn't be used.
