### ISSUE TITLE
debugger not work when attach IISExpress

### ISSUE THREAD

**Issue by javafun** [0xd4d/dnSpy#439]
1. Run web application with debug (F5), try to attach process iisexpress with dnSpy, received an error said This process has been already attached.

2. Run web application without debug, try to attach to process iisexpress with dnSpy, set the dll decomplie code breakpints , the debugger never hit breakpoints

**Comment by 0xd4d** [comment]
1: If you're already debugging something, then dnSpy can't attach to it since only one debugger can debug a process.

2: Make sure you set breakpoints in the right module. For example, there are many `mscorlib.dll` files on your disk. Open the Modules window and double click the module, that way you'll set a breakpoint in the correct module.

**Comment by javafun** [comment]
Hi @0xd4d 

Thanks for your help. 

I understand the 1st point. However, I am still not able to debug the web application.  The following steps are what I was doing

1. Create a sample ASP.NET Mvc application by VS template named WebApplication1
2. Use the VS launch the site without debugging, so that IISExpress process will be available for attach
3. Open dnSpy, then drag the WebApplication1.dll to the Assembly explorer, set the breakpoint at Index method of the Home controller
4. Launch **Attache to process** from debug menu, choose the **iisexpress** process, then refresh the site home page, nothing hits the breakpoint.

It would be good if you can share some general guideline how to debug the web applications. 

Thanks,

Vincent

**Comment by 0xd4d** [comment]
This is a late reply but you have to use the correct DLL file. IIS will copy your files to some temporary location. To get the correct DLL to set a BP in, you have to open the Modules window. There's no search yet (wait for 4.0) so copy and paste all modules to some text file and search for WebApplication1 and you should see its path. Open this file and set a BP at Index() or any other method. (You can also double click it in the Modules window to open the file)
