### ISSUE TITLE
Mouse cursor lags while it loads dll

### ISSUE THREAD

**Issue by evildog1** [0xd4d/dnSpy#440]
When I click on a dll file, it loads another dll in assembly explorer but it makes the mouse cursor lag. It uses 30-60% of CPU usage. My CPU is Intel i7 4770k and my PC running Win10 Creators Update.
To reproduce this bug, click on System.Configuration (x.0.0.0) and it loads 3 other dlls

**Comment by 0xd4d** [comment]
I couldn't reproduce this, at most one extra file gets loaded.
