### ISSUE TITLE
Print the call stack in a log file

### ISSUE THREAD

**Issue by christoyork** [0xd4d/dnSpy#441]
Is there any way that i can print the whole "call stack" into a log file when debugging an executable. I have a program to debug which consists of many many lines? 
Thank you for your time and efford.

**Comment by gagmeng** [comment]
That's what I want.

**Comment by 0xd4d** [comment]
You can open the call stack window and copy and paste the call stack or do you want to do it automatically when it executes a certain statement?

**Comment by christoyork** [comment]
What i meant is to keep track of the various functions been called during the execution process (In a log file) so you can track back the road-map of the execution.
