### ISSUE TITLE
Process not start when debugging?

### ISSUE THREAD

**Issue by Radzhab** [0xd4d/dnSpy#442]
I have software written on net framework 1. When i try debug it - its not starting.

![image](https://user-images.githubusercontent.com/2556411/27224926-777246b2-52a0-11e7-99a4-7ace01c22ee8.png)
i see progress, but form is not showing.
![image](https://user-images.githubusercontent.com/2556411/27224943-887f9c52-52a0-11e7-9f44-5879cbd43193.png)

**Comment by Radzhab** [comment]
http://rgho.st/8VQsF8Y5z this is program

**Comment by XenocodeRCE** [comment]
![](http://i.imgur.com/H9TXi9x.png)

Please include further details

**Comment by Radzhab** [comment]
My OS Windows 10 x 64.  How you started it?

![image](https://user-images.githubusercontent.com/2556411/27429071-9f90b312-574c-11e7-8e94-c525dd808a86.png)

**Comment by Radzhab** [comment]
dnSpy (2.0.2.0) version

**Comment by SlowLogicBoy** [comment]
Use latest version of dnSpy

**Comment by 0xd4d** [comment]
dnSpy can only debug .NET Framework 2.0 or later assemblies, or .NET Core assemblies.

**Comment by 0xd4d** [comment]
You can force the program to use .NET Framework 2.0 or later by adding an app.config file.

**Comment by Radzhab** [comment]
I think i find issue. Software install hasp driver. I think its not get start soft under debugger

**Comment by SlowLogicBoy** [comment]
HASP is hard to go around since well.. assembly is hardware locked/obfuscated, unless you have hasp device itself
