### ISSUE TITLE
How is this not more popular?!

### ISSUE THREAD

**Issue by Fireboyd78** [0xd4d/dnSpy#445]
Hi guys, I wanted to leave you some positive feedback but wasn't quite sure where else this should go.

I just wanted to say that dnSpy is one of the greatest tools I've ever come across, and how I was unable to find it before is mind-blowing. I found something else called "DotNet IL Editor" from **2004** that _can't even do any actual editing!_ I almost gave up my search for a proper editor until I came across dnSpy by pure luck. I expected to boot up a simple program that was probably hacked together in a couple nights of drunken fury...but instead, I'm greeted with the most professional-looking **open-source** program I've ever seen!

My jaw hit the floor when I realized I could edit the disassembled C# code directly, and then recompile it and save a new version of the program in less than 5 minutes! I've been a faithful ILSpy user for quite a few years, but I didn't think we were at a point yet where editing disassembled C# code was even possible. I would've been grateful for a simple IL editor, which is all I was looking for in the first place.

I don't know how long this project has been going on for, but I am just absolutely astonished at how well this program looks, feels, and functions! Really, to all of you who have contributed to this project and made dnSpy possible, **thank you so much!** I will be uninstalling any other IL tools I have and primarily using this tool from now on. I'll definitely recommend this to as many people as I can!

Keep up the fantastic work!

**Comment by UlyssesWu** [comment]
In fact, before dnlib and dnSpy, you can use Mono.Cecil and Reflexil to do the samething. But of course, dnlib is much better than Mono.Cecil, thus dnSpy is also better than Reflexil. And dnSpy is the only choice for debugging.

**Comment by 0xd4d** [comment]
I'm the main dev of dnSpy, but I didn't write anywhere near all the code since dnSpy uses other open source libraries: ILSpy decompiler engine and Roslyn. They're 2 of the 4 important big parts of dnSpy (the other two are the assembly editor and debugger).

To answer your question in the title: I don't advertise it since it's meant to be an advanced tool for advanced users.

**Comment by SlowLogicBoy** [comment]
I also think this project is great, it helps me to find missing references, or errors in other libraries, that help me to make workarounds in my projects, analyze calls, differences in library versions etc.. 

It's popularity would introduce more contributors and would greatly improve it's stability.
Most people come here from reverse engineering background, like I did when I was learning .net internals / IL, so I could write more efficient and secure software.

However more and more people are coming here to use this tool not for good intentions, and I see more and more tutorials on how to "hack" that or/and that with this tool and after seeing screenshots in issues with software code which they clearly do not own, is concerning and I personally don't like that. 

I have got lots of requests asking for help how to do "something" with this tool on gitter.im...

I understand that they are responsible for themselves, but that just click my ethical gears in wrong ways.

What I want to say is that this tool is also getting a bad rep for what most people are doing with it, and increase in popularity might not be the best thing for it :).

**Comment by fireundubh** [comment]
I just came across dnSpy after struggling with dotPeek's output.

Wow. This is an incredible feat of engineering. I hope you're making bank wherever you're working.

**Comment by VicoErv** [comment]
I've been many years working with reflector and reflexil, refactor code using il opcodes make me confused, now it's simple using dnSpy

**Comment by sekhmetn** [comment]
I'm using WinDbg with sos, sosex, and psscor4. I'm using ILSpy. And, I'm comfortable with ildasm and ilasm to modify binaries, And yet, this tool (dnSpy) is still so so useful. My current project is learning how ConfuserEx works and using the set of tools mentioned above to bypass each technique. dnSpy helped visualize what was happening when I was trying to figure out how to move forward on each technique. Thanks for making dnSpy.

**Comment by LGuilhas** [comment]
I also have found out about DnSpy recently after years working with .net reflector and later with ILSpy. I’m supper impressed with the tool and what i can do with it.
I just hope the devs don’t turn into Lutz Roeder and sell your souls and great software to some greedy corp.
