### ISSUE TITLE
Change msdn links to point to microsoft docs

### ISSUE THREAD

**Issue by patricksadowski** [0xd4d/dnSpy#446]
Currently [OpCodeReferenceHandler](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy/Documents/Tabs/DocViewer/OpCodeReferenceHandler.cs) and [SearchMsdnCtxMenuCommand](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy/Documents/Tabs/SearchMsdnCommand.cs) point to https://msdn.microsoft.com/. Microsoft is moving the docs to https://docs.microsoft.com/. I would recommend to adjust the urls.

_OpCodeReferenceHandler_ should point to https://docs.microsoft.com/dotnet/api/system.reflection.emit.opcodes.{0}. _SearchMsdnCtxMenuCommand_ could use https://docs.microsoft.com/dotnet/api/{0}
Both urls support the parameter _view_ e.g. _view=netframework-4.7_

**Comment by 0xd4d** [comment]
Yes should be fixed, Want to send a PR? Otherwise I'll fix it at some later time.

**Comment by patricksadowski** [comment]
I will send a PR.
