### ISSUE TITLE
Wrong decompiled code about unsigned

### ISSUE THREAD

**Issue by EcoleKeine** [0xd4d/dnSpy#449]
example souce code:

            int type1 =381;
            Console.WriteLine((uint)(type1 - 381) <= 1U);
            Console.WriteLine(type1 - 381 <= 1);

            type1 = 370;
            Console.WriteLine((uint)(type1 - 381) <= 1U);
            Console.WriteLine(type1 - 381 <= 1);

output 
> TTFT

and decompiled code is:

            Console.WriteLine(expr_2D - 381 <= 1);//x4

when recompile the code, the Output will be:

> TTTT

-----
Sorry for my poor english

**Comment by 0xd4d** [comment]
This will probably be fixed upstream.
