### ISSUE TITLE
[Request] Disable auto-beautifier

### ISSUE THREAD

**Issue by Kein** [0xd4d/dnSpy#450]
I don't know if it is possible but every time I compile code compiler tries to be smart and adjusts it, making it unreadable. Is it possible to add the ability to compile it raw or c# sharp compiler just works that way?

https://pastebin.com/T4rKFDUa

**Comment by 0xd4d** [comment]
The link's not working.

dnSpy can't control the code the compiler generates. A switch could be compiled to ifs etc. The decompiler would need to be updated to guess that a bunch of ifs is really a switch in the source code.

**Comment by Kein** [comment]
Yeah, sorry, I understand, thanks for response.

While we are on the topic of compiler/decompiler - any ideas why this can't be decompiled properly:

`	// Token: 0x06001D38 RID: 7480 RVA: 0x000AB6C8 File Offset: 0x000A98C8
	[DebuggerHidden]
	public IEnumerator Respawn()
	{
		HeroController.<Respawn>c__Iterator12 <Respawn>c__Iterator = new HeroController.<Respawn>c__Iterator12();
		<Respawn>c__Iterator.<>f__this = this;
		return <Respawn>c__Iterator;
	}
`

**Comment by 0xd4d** [comment]
You're most likely not using the latest build and still using v3.0.2 or earlier.

**Comment by Kein** [comment]
Oh... yeah, thanks man!

**Comment by Kein** [comment]
I don't want to create another useless issue so I ask here if you still watch it?

Why does it throw the error:
https://imgur.com/a/CBsaM

**Comment by 0xd4d** [comment]
Upload the files somewhere and I'll have a look.

**Comment by Kein** [comment]
Basically I'm just trying to add new function (method) to existing class and takes an argument (bool or string) but it wont let me:
http://rgho.st/8RXLYdX6b

**Comment by 0xd4d** [comment]
I need all DLL files, and also the steps needed to reproduce this.

**Comment by Kein** [comment]
All files:


To reproduce:
1. Find OnScreenDebugInfo class
2. Make new copyFile() method through "Create Method" (see note below why Edit Class wont work)
3. Do manual editing of the new method (C#)
4. Try to make it private void that accepts arguments

Note about class editing - you can't edit OnScreenDebugInfo class as whole, this is also seems to be another bug. You can check for yourself what exactly goes wrong.

**Comment by 0xd4d** [comment]
Editing whole class: most likely a dupe of an already known issue.

I can't repro the other. I managed to create a new method with 'Create Method' followed by editing it with 'Edit Method'. I could also change public to private.

A tip: whenever you edit a method, you can always add more methods, fields, properties, events at the same time.  Find a small method, eg. `OnDisable()`, edit it (C#), then add your new method and press compile.

**Comment by 0xd4d** [comment]
1.

```C#
public extern void DoThings();
```

2. 

```C#
public void DoThings()
{
	Console.WriteLine("XXXXXXXX");
}
```

3.

```C#
void DoThings()
{
	Console.WriteLine("XXXXXXXX");
}
```

**Comment by Kein** [comment]
**0xd4d**

No no, the public /private is not relevant. It wasnt the issue, the issue to add params and parameters types because "Edit Method..." does not save them.

For example:

void DoThings(string arg)
{
	Console.WriteLine(arg.ToSting());
}

**Comment by 0xd4d** [comment]
So you're changing the method signature while editing C# code, and that's not supported. It matches against the exact signature and can't find it.

When you modify the method signature in 'Method Properties', you have to click on 'Add' followed by OK.

But this is all not necessary, see my tip above on how to add a new method by just using C#.

**Comment by Kein** [comment]
Hey **0xd4d**. I, uh, know that this is not the place to ask but lats few days I spent trying to find a way to work around the problem I mentioned before. I was curious if you could give me a hint how to handle it with dnSpy, after all you know it better.

So, long story short, I'm doing simple mod for Unity game. I try to keep it withing one class to minimize mundane work but the game updates very often and it turns into nightmare. Even though the class I'm working with not affected I have to redo ALL the stuff from scratch:  
- create dozens of functions manually through dnSpy dialogue, then apply the return type and parameters to each manually again, then paste the code
- create all variables
- change existing modified functions

I obviously can't just click edit class and paste all saved code. But I was curious if you know a  better way? May be it is possible to somehow make dnSpy at least load code partially or diff apply it? Or compile some kind of shared module with only changed stuff? Anything advice would be of use, but of course you don't have to answer.

**Comment by 0xd4d** [comment]
dnSpy can't automate this for you. Create a new issue if this is an important feature.
