### ISSUE TITLE
Fails to compile with error:

### ISSUE THREAD

**Issue by sunrunner20** [0xd4d/dnSpy#451]
Could not find file 'Microsoft.Windows.Common-Controls, Version=6.0.0.0, Culture=*, PublicKeyToken=6595b64144ccf1df, ProcessorArchitecture=*, Type=win32'.
Project:
dnSpy-x86

**Comment by 0xd4d** [comment]
Do you have some more information? How do I reproduce this?

**Comment by sunrunner20** [comment]
Clean VS2015 install, fresh clone of dnSpy master branch. Built DNspy-x86

**Comment by 0xd4d** [comment]
See the wiki: https://github.com/0xd4d/dnSpy/wiki/Building-dnSpy

**Comment by mattkemp** [comment]
I get the same issue using VS2017 and I've done a full recursive clone (both recommendations from the "Building dnSpy" page

**Comment by mattkemp** [comment]
Removing the following from the dnSpy/app.manifest file allowed it to build:
```
<!-- Enable themes for Windows common controls and dialogs (Windows XP and later) -->
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
          type="win32"
          name="Microsoft.Windows.Common-Controls"
          version="6.0.0.0"
          processorArchitecture="*"
          publicKeyToken="6595b64144ccf1df"
          language="*"
        />
    </dependentAssembly>
  </dependency>
```

**Comment by 0xd4d** [comment]
@mattkemp  Are you using Windows 7?

**Comment by mattkemp** [comment]
I got the same error on a Windows 7 machine and also a Windows 8

**Comment by BpArCuCTeMbI** [comment]
I can't open the project on Win10 x64, VS2015 update 3. It says to try newer VS version. However, the project compiles on Win7 x64, VS2015 update 1.

**Comment by 0xd4d** [comment]
@BpArCuCTeMbI : See the wiki, it says that you must use the latest version of VS which is VS2017 15.4. If you can compile it with VS2015, it means you're using old dnSpy source code.

**Comment by Norman01** [comment]
VS 15.5.7

'IQuickInfoBroker' is obsolete: 'Use IAsyncQuickInfoBroker instead'	dnSpy.Roslyn
dnSpy.Roslyn.dll' could not be found	dnSpy.Roslyn.EditorFeatures
dnSpy.Roslyn.dll' could not be found	dnSpy.Roslyn.CSharp.EditorFeatures\

Any suggestions?

**Comment by 0xd4d** [comment]
Download the source code again into a **new** directory, follow the wiki article, and compile. Sounds like you updated some nuget package version.

**Comment by Norman01** [comment]
Without repository update:
========== Build: 12 succeeded, 32 failed, 0 up-to-date, 0 skipped ==========

C:\Users\nam\Git\dnSpy\dnSpy\dnSpy.Contracts.Logic\bin\Debug\dnSpy.Contracts.Logic.dll' could not be found	dnSpy.Contracts.DnSpy

144 errors instead of 26. without PM> Install

I have walk through Wiki article many times.

For some silly reason, the copy The initial post was made from now compiles, but the newly created repository does not. Only difference is I am running a precompiled version (4.5.3) in the background.

Beats me???????

**Comment by Norman01** [comment]
Apparently it is a bug in the IDE.

What I did to successfully compile from the repository:
git clone -- recursive https://github.com/0xd4d/dnSpy.git

From IDE
Package manager console:
Install-Package CodeContracts.MSBuild -Version 1.12.0

Compiled to any CPU - failed
without cleaning
Changed to X64
compiled correctly

changed back to any CPU
compiled correctly

Output error showed fail to build 2 first compile, built properly on second.

**Comment by 0xd4d** [comment]
You shouldn't have to install any other nuget packages, it should just work. Maybe your nuget cache is corrupt or your .vs/ dir or bin/ or obj/ dirs contain corrupted cached files.

**Comment by MouthOfMadness** [comment]
Just FYI for everyone who navigates here from the WIKI.

Using VS2019 16.3.5
git clone -- recursive https://github.com/0xd4d/dnSpy.git

I had a successful build:

45>dnSpy-x86 -> D:\1d\dnSpy\dnSpy\dnSpy-x86\bin\Debug\netcoreapp3.0\dnSpy-x86.dll
========== Build: 45 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by dustinbrinegar** [comment]
On a fresh install of VS2019 it initially failed to build, but trying to build again without changing anything succeeded.

I tried Clean->Build but that worked, so not sure what was going on, but commenting in case anyone else has this problem.

**Comment by 0xd4d** [comment]
> On a fresh install of VS2019 it initially failed to build, but trying to build again without changing anything succeeded.
> 
> I tried Clean->Build but that worked, so not sure what was going on, but commenting in case anyone else has this problem.

If it failed the first time you compiled it, it's probably because VS hasn't had enough time to restore all nuget packages.

**Comment by StudioBlox3089** [comment]
I have an issue with compiling dnSpy & I have 302 errors & 2 warnings, How do I fix that?

And also when I was building the solution, many of them failed because the access is denied,
