### ISSUE TITLE
How to debug assembly loaded by InstallUtil?

### ISSUE THREAD

**Issue by Mefist0** [0xd4d/dnSpy#454]
Hello all!

Does anyone know how to debug an assembly that loaded via InstallUtil?
I tried to load both: my assembly and InstallUtil.exe to dnSpy. Then I had set breakpoints in my assembly entry point and on Installer class. Then I start InstallUtil and as argument I set full path to my assembly.
But debugger skips my breakpoints.
Any ideas how to debug this?

Thank you very much in advance!

**Comment by 0xd4d** [comment]
Make sure you set breakpoints in assemblies that get loaded at runtime. Attach to it, open the modules window and double click the module and you're sure to get the correct assembly.
