### ISSUE TITLE
Unity IEnumerators can only be changed once

### ISSUE THREAD

**Issue by Dummiesman** [0xd4d/dnSpy#455]
When using the "Edit Method" function, a Unity IEnumerable will only be successfully modified once. Any further attempts will result in no code change and no errors.

**Comment by 0xd4d** [comment]
I can reproduce it, probably similar to #164

**Comment by Dummiesman** [comment]
Ah yep, that's exactly it.

**Comment by Kein** [comment]
Is this fixed? I'm using build as of July 22, the relevant commit was July 4, however any attempt to edit  Unity IEnumerable results in the same outcome as in OP.

**Comment by 0xd4d** [comment]
Please open a new issue with repro steps.
