### ISSUE TITLE
How to create DLLs for Unity?

### ISSUE THREAD

**Issue by thienha1** [0xd4d/dnSpy#456]
How to compile dll without thousand errors??

**Comment by nxrighthere** [comment]
Try [this asset](https://github.com/gnatogryz/DDLLC) for this purpose.

**Comment by thienha1** [comment]
How to use it?

**Comment by nxrighthere** [comment]
Import it to your project and then open compiler configuration window from menu _Compiler -> Configure Compiler_.

**Comment by thienha1** [comment]
What software?

**Comment by nxrighthere** [comment]
It works right inside Unity editor.

**Comment by thienha1** [comment]
Just download UnityEditor and follow this instruction!?

**Comment by thienha1** [comment]
Just download UnityEditor and follow this instruction!?

**Comment by thienha1** [comment]
Just download UnityEditor and follow this instruction!?

**Comment by 0xd4d** [comment]
Ask questions in the other repo.
