### ISSUE TITLE
[Feature request] Partial or full class code import

### ISSUE THREAD

**Issue by Kein** [0xd4d/dnSpy#459]
So, sometimes there is a case when you can't edit whole class because DnSpy sees some ambiguity in code. or does not decompile properly all the stuff. Sometimes you need to update it. See more info: https://github.com/0xd4d/dnSpy/issues/450#issuecomment-313874210

What would be awesome is some kind of import code (saved by dnspy) feature (per class) or smart "partial" import (that only imports changed/non-existing stuff). This will save a LOT of time when migrating.

**Comment by Kein** [comment]
Now that I think about it - would be cool to have some kind of mini-local VC repository which  can be linked in dnSPy to specific assembly and loaded on the fly when you load assembly. This way you also can have comments in code stored...

**Comment by 0xd4d** [comment]
No upvotes, no PR, and I have no need for it -> closing it. It's too much work.
