### ISSUE TITLE
[Bug?] IEnumerator editing is bugged

### ISSUE THREAD

**Issue by Kein** [0xd4d/dnSpy#461]
**Original code:**

```C#
public IEnumerator Fade()
{
	this.GUIalpha = 1f;
	while (this.GUIalpha > 0f)
	{
		this.GUIalpha -= Time.deltaTime;
	        yield return null;
	}
}
```

**Changed to**

```C#
public IEnumerator Fade()
{
	this.GUIalpha = 1f;
	while (this.GUIalpha > 0f)
	{
		this.GUIalpha -= Time.deltaTime;
		yield return null;
	}
	yield break;
	yield break;
}
```

**It gets better, new code:**
```C#
public IEnumerator Fade()
{
	this.GUIalpha = 1f;
	while (this.GUIalpha > 0f)
	{
               yield return new WaitForSeconds(0.05f);
		this.GUIalpha -= Time.deltaTime;
		yield return null;
	}
	yield break;
	yield break;
}
```

**Changed to:**

```C#
public IEnumerator Fade()
{
	for (float f = 1f; f >= 0f; f -= 0.1f)
	{
		this.GUIalpha = f;
		yield return null;
	}
	yield break;
	yield break;
}
```

**wat**

**Comment by 0xd4d** [comment]
What output do you expect to see? Is it the unnecessary `yield break`s that's the problem?

**Comment by Kein** [comment]
That too yeah, but also last 2 are pretty  weird too, not sure what gives.

**Comment by 0xd4d** [comment]
BTW, use \`\`\`C# when adding C# code samples so they're readable.

How do I repro the last one? I assume the 3rd C# code is what you entered and the 4th C# code is what the decompiler showed?

**Comment by Kein** [comment]
3rd code is what I entered/typed, yeah and the 4th is what I saw once I clicked "Compile".

**Comment by Kein** [comment]
What do you mean not reproduceable, I can record a video showing the process happening lol

**Comment by 0xd4d** [comment]
No video is required, just write down exactly what I need to do to repro this.

**Comment by Kein** [comment]
Declare a dummy float var GUIalpha, create new method and just paste code form #3?

**Comment by 0xd4d** [comment]
Still not reproducible. Reopen it when you can write down repro steps that actually reproduces this issue.

**Comment by Kein** [comment]
These are literally the steps I just did and same thing happened

**Comment by 0xd4d** [comment]
I did that too and couldn't repro it. Could you email me all the files (zip them), including name of class + name of method (or just metadata token of the method) + name of assembly that you edited? de4dot@gmail.com

**Comment by Kein** [comment]
http://rgho.st/7c5L7JFcf

Open Assembly-CSharp.dll, find **OnScreenDebugInfo**. Create any/Fade() IEnumerator method.

Using "Edit C#" paste:

```C#
private float GUIalpha;
private IEnumerator Fade()
{
	this.GUIalpha = 1f;
	while (this.GUIalpha > 0f)
	{
		this.GUIalpha -= Time.deltaTime;
	        yield return null;
	}
}
```

See how it turns it into weird madness

**Comment by Kein** [comment]
Also, is this normal for IL body to display this nonsense for IEnum?

![image](https://user-images.githubusercontent.com/623756/28487823-73416ba4-6ea2-11e7-9b2f-048efbf1d131.png)

**Comment by 0xd4d** [comment]
There's nothing wrong with the code, it's the same as the code you showed above with useless yield breaks.

```C#
	IEnumerator Fade()
	{
		this.GUIalpha = 1f;
		while (this.GUIalpha > 0f)
		{
			this.GUIalpha -= Time.deltaTime;
			yield return null;
		}
		yield break;
		yield break;
	}
```

What you're seeing in the pic above is the code the compiler generates. The real logic is in a state machine class. I googled for you: http://csharpindepth.com/Articles/Chapter6/IteratorBlockImplementation.aspx

**Comment by Kein** [comment]
So, to come back to this: who is responsible for unreachable code block with extra `yield break` here - dnSpy or IL comp.?

**Comment by 0xd4d** [comment]
It's a known issue that no-one cares much about because it doesn't hurt having an extra yield break.

**Comment by Kein** [comment]
That's wasnt really the question, though.
