### ISSUE TITLE
[Feature Request] Mouse double-click on active Class or Method

### ISSUE THREAD

**Issue by Kein** [0xd4d/dnSpy#463]
...results in auto-opened "EDIT" tool.

That's all

**Comment by 0xd4d** [comment]
Edit C#/VB or IL code? Or Edit metadata?

For C#/VB there's already a shortcut Ctrl+Shift+E. Edit metadata, Alt+Enter.

**Comment by Kein** [comment]
Whatever is  selected in dropdown menu on toolbar.
I know there is  Ctrl+Shift+E but would be nice to either have MB1 support or ability to setup your own hotkeys

**Comment by XenocodeRCE** [comment]
An hotkey shortcut manager could be very handy, especially for repeated task

**Comment by 0xd4d** [comment]
No upvotes, no PR, and I have no need for it -> closing it.
