### ISSUE TITLE
[Feature Request] Pinned tabs and tabs auto-locate

### ISSUE THREAD

**Issue by Kein** [0xd4d/dnSpy#464]
If you are familiar with Total Commander tabs mechanism then basically this. If not:

- a specific tab can be "pinned", that means it is locked in place and any attempt to navigate inside it to a different location will open that location in new tab and sets it as active
- pinning mechanism can be limited to classes only but method would be nice.
- upon opening new assembly would be great if pinned tab tried to "auto-locate" the location. i.e. I clear assembly list and open the same assembly with the same hierarchy but different version - so it CAN auto-locate same method or class. If not - defaults to <empty>

**Comment by SlowLogicBoy** [comment]
#251 Similar to this?

**Comment by Kein** [comment]
Yeah i suppose

**Comment by 0xd4d** [comment]
No upvotes, no PR, and I have no need for it -> closing it. It's too much work.
