### ISSUE TITLE
Still having issues with IEnumerators (yield returns) on version 3.0.2

### ISSUE THREAD

**Issue by olie304** [0xd4d/dnSpy#466]
Hey, Still having the same problem as the guys in this thread https://github.com/0xd4d/dnSpy/issues/239. It turns out like this in the decompiler and the IL instructions show that there is a lot more going on `[DebuggerHidden]
		private IEnumerator teleport()
		{
			VolumeTeleporter.<teleport>c__Iterator0 <teleport>c__Iterator = new VolumeTeleporter.<teleport>c__Iterator0();
			<teleport>c__Iterator.$this = this;
			return <teleport>c__Iterator;
		}`

**Comment by 0xd4d** [comment]
I suggest you put on your reading glasses and read the thread you linked to.
