### ISSUE TITLE
Why some WPF applications will lost the events?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#467]
Create a wpf applications in Visual Studio, drag and drop a button, double click the button and write :

		private void button1_Click(object sender, RoutedEventArgs e)
		{
			MessageBox.Show("OK");
		}

build it , and decompile the output in dnSpy.
Export to Project, build and run, when click the button, there's nothing.

**Comment by 0xd4d** [comment]
I can't repro it, it shows the message box.

Have a look at the xaml files, compare the original files with the decompiled files. Seems like yours is missing a Click handler.

**Comment by CreateAndInject** [comment]
[WpfDemo.zip](https://github.com/0xd4d/dnSpy/files/1152890/WpfDemo.zip)
[DeWpfDemo.zip](https://github.com/0xd4d/dnSpy/files/1152892/DeWpfDemo.zip)

WpfDemo is the original project, DeWpfDemo is decompiled by dnSpy.

**Comment by 0xd4d** [comment]
Your files can't be downloaded. I'll paste the question from my previous reply again:

> Have a look at the xaml files, compare the original files to the decompiled files. Seems like yours is missing a Click handler.

**Comment by CreateAndInject** [comment]
So, you mean this happend in .net 2.0?

 But even if I compiled WpfDemo as .net 4.0, I can repro it also.

**Comment by escms** [comment]
winForm:
dnspy 2.0 :
`this.button1.Click += new EventHandler(this.button1_Click);`
dnspy 3.x :
`this.button1.Click += this.button1_Click;`

**Comment by 0xd4d** [comment]
@escms Is that a question?

**Comment by escms** [comment]
@0xd4d I'm sorry, I can not speak English, I use google translation：
如果没有生成EventHandler，在编辑界面时，双击按扭时会重新生成一个Click事件，原来的Click事件会被清除。
If the EventHandler is not generated, the click event will be regenerated when the button is double-clicked when the form is edited, and the original Click event will be cleared.
for example：
this.button1.Click += this.button1_Click; 
Edit the form and double-click the button  later：
this.button1.Click += new EventHandler(this.button1_Click_1); 
“this.button1.Click += this.button1_Click; ” is deleted，Will generate a new event method button1_Click_1。

**Comment by UlyssesWu** [comment]
I can reproduce this. `new EventHandler` should be used in `*.Designer.cs`.

**Comment by 0xd4d** [comment]
@escms Fixed in latest 'master' branch build. Binaries can be downloaded here: https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts

**Comment by escms** [comment]
@0xd4d this latest 'master' branch still has this problem.

**Comment by 0xd4d** [comment]
You have to export all code (`File` -> `Export to Project`)

```C#
this.button1.Click += new global::System.EventHandler(this.button1_Click);
```

otherwise you'll see this:

```C#
this.button1.Click += this.button1_Click;
```

**Comment by escms** [comment]
@0xd4d Understand, thank you very much for your reply.

**Comment by escms** [comment]
@0xd4d After testing the latest version, the UserControl still has this problem.

**Comment by 0xd4d** [comment]
@escms  It's impossible for me to reproduce it unless you write down the repro steps.

**Comment by escms** [comment]
@0xd4d  As with the winform problem above, when the Click event is present in the UserControl, the EventHandler is removed after the project is exported, and a new Click event is generated when the interface is edited again.


If the EventHandler is not generated, the click event will be regenerated when the button is double-clicked when the form is edited, and the original Click event will be cleared.
for example：
this.button1.Click += this.button1_Click;
Edit the form and double-click the button later：
this.button1.Click += new EventHandler(this.button1_Click_1);
“this.button1.Click += this.button1_Click; ” is deleted，Will generate a new event method button1_Click_1。

Winform in the previous version has been repaired, see the above reply. But the UserControl still has this problem.

**Comment by escms** [comment]
@0xd4d Whether it is necessary to further explain or prompt the sample program?

**Comment by 0xd4d** [comment]
Attach whatever is necessary to reproduce it.
