### ISSUE TITLE
Error in open dnSpy sometimes.

### ISSUE THREAD

**Issue by jclitwin** [0xd4d/dnSpy#468]
Yo,

Sometimes when I try to open dnSpy, give me error in some thread.

http://prntscr.com/fwpw1o

How I can fix that?

**Comment by 0xd4d** [comment]
Seems like you're using an old build, try the latest build: https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts

If it fails, re-open this issue or create a new issue.
