### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by li0nsar3c00l** [0xd4d/dnSpy#47]
I assume it's wanted, that you cannot start two instances of dnSpy at the same time, but i think, it would be handy, specially when trying to attach to a process, to start a 32bit and a 64bit instance at the same time.

**Comment by 0xd4d** [comment]
This command line argument can be used: https://github.com/0xd4d/dnSpy/blob/master/doc/Command%20Line.txt#L11

**Comment by 0blu** [comment]
The doc link is outdated.
See https://github.com/0xd4d/dnSpy/wiki/Command-Line-Arguments
``
--multiple
``
