### ISSUE TITLE
Unicode characters in identifiers turn into "?"

### ISSUE THREAD

**Issue by swbrown** [0xd4d/dnSpy#471]
Identifiers with unicode characters in them get mangled when decompiling and converted into unknown character "?".  The identifiers are likely going through an ASCII conversion at some point.

As an example, the letter that looks like "c" in this (via ildasm /utf8) is cyrillic character 0x0441 (if it comes through github ok):

IL_001c:  stfld      float32 SeaDragon::'сumulativeBurningChunkDamage'

but will wind up as this when decompiled via dnSpy:

private float ?umulativeBurningChunkDamage;

**Comment by 0xd4d** [comment]
I can't repro it. I created a simple .NET Framework 4.6 project and created a field with the name above. I viewed the decompiled code and didn't see a `?`. I also exported the file and opened the `*.cs` file and didn't see a `?`.

**Comment by 0xd4d** [comment]
BTW, check `View -> Options -> General -> Use the new text formatter`. Make sure it's UNchecked.
