### ISSUE TITLE
Failed to decompile.

### ISSUE THREAD

**Issue by jclitwin** [0xd4d/dnSpy#473]
Yo,

So, I have some problem for to decompile some class. I can read others classes from dll but when I try to decompile PlayZone, give me error and I can't to read.

***.dll download:**
https://mega.nz/#!ulY1ibIC!bUh-bYy445mxSW20Zg6kjuJ2_dyCXOy-xO9zFP5Frhk

**log in dnSpy:**
[log.txt](https://github.com/0xd4d/dnSpy/files/1179883/log.txt)

Cheers.

**Comment by 0xd4d** [comment]
Too much recursion in the decompiler. Fixing it is not trivial and would probably require rewriting a large part of it.
