### ISSUE TITLE
Unable to add method with complex custom parameters 

### ISSUE THREAD

**Issue by Kein** [0xd4d/dnSpy#474]
I'm trying to create:

`public void writeDGdata(Dictionary<string, Vector2> dictionary)`

But the dnSpy's "GUI toos" wont let me do it, I only can add generic type dictionary but cannot specify them. Nor can I add it directly via Edit Method.

This is what I want to achieve in EXISTING class:
![image](https://user-images.githubusercontent.com/623756/28789710-43de9258-762f-11e7-9157-09bb192dd1f4.png)

as of right now it is not possible by any means

**Comment by 0xd4d** [comment]
The signature in the picture matches the signature you wrote above.

As I've explained in some other post, you can always add extra members (eg. methods, fields, classes) when you edit a method. Just pick the simplest one-line method you can find, edit it, then add your new method.

**Comment by Kein** [comment]
No, I can't:
![image](https://user-images.githubusercontent.com/623756/28844358-0ab1b0ee-770d-11e7-9de6-bc766f034abb.png)
