### ISSUE TITLE
process.Kill() kill dnSpy at debugging

### ISSUE THREAD

**Issue by uragan1987** [0xd4d/dnSpy#478]
this kill whole debuger
-----------------------------------
Process process;
Killme.KillAll(process);

static void KillAll(Process process)
{
		process.Kill();
}

---------------------------------------

**Comment by 0xd4d** [comment]
There's nothing dnSpy can do to prevent some other process from killing it.

**Comment by uragan1987** [comment]
why not build an ignore for Process.Kill()?
check for command, jump over,

**Comment by 0xd4d** [comment]
There are many ways to kill a process or destroy memory in a process (causing it to crash).

Most script kiddie malware will just check the window title and kill all processes matching some pattern. Compile dnSpy yourself and change the `dnSpy` string in the title bar to something else.

**Comment by uragan1987** [comment]
thx, 
i have change the IL, for me, thats enough :)
just try to give you some tips
