### ISSUE TITLE
Can't attach to a child process

### ISSUE THREAD

**Issue by VladD2** [0xd4d/dnSpy#479]
I have the child 64-bit process (server) in the 32-bit application. dnSpy can't see a 64-bit child process.

[Nitra](https://github.com/rsdn/nitra)

**Comment by 0xd4d** [comment]
Use `dnSpy.exe` to debug 64-bit .NET applications, and `dnSpy-x86.exe` to debug 32-bit .NET applications.

**Comment by VladD2** [comment]
You not understand my. dnSpy.exe not show **child** processes. I can't choose my process. (This is not a question. This is a bug.)

**Comment by 0xd4d** [comment]
Explain how to repro this, step by step.

- 32-bit dnSpy only shows 32-bit processes since it can only debug 32-bit processes.
- 64-bit dnSpy only shows 64-bit processes since it can only debug 64-bit processes.

**Comment by thejoelpatrol** [comment]
32 vs. 64 bit issues aside, I think what the other commenter is saying is that it would be nice to be able to attach dnspy to a child process, period. AFAICT it is not possible to attach to another process while debugging one already. Right now I have a situation where I am debugging an assembly that launches a child, which itself launches a child, and then the parents quit. I would like to be able to follow the children immediately when they're created, without first detaching and letting the parents run freely; then the child also gets to run freely, but I need to start debugging it as soon as it's created. Apologies if this is already possible and I just don't understand how to do it.

**Comment by 0xd4d** [comment]
Debugging multiple processes will soon be possible but auto attaching to created child processes won't work if it's managed only debugging

https://blogs.msdn.microsoft.com/jmstall/2005/08/16/auto-attach-to-child-process-is-not-supported-in-managed-debugging/

It's possible if mixed mode debugging is used (which dnSpy doesn't enable at the moment), there's even an extension for VS: https://marketplace.visualstudio.com/items?itemName=GreggMiskelly.MicrosoftChildProcessDebuggingPowerTool

If this is important then create a new issue, or it will be forgotten.

**Comment by thejoelpatrol** [comment]
Thanks, even the ability to debug a second process would help a lot. I'll look forward to it.
