### ISSUE TITLE
Unity IEnumerators can only be changed once, part 2

### ISSUE THREAD

**Issue by Kein** [0xd4d/dnSpy#482]
Continuation #455 

Assembly to check:
http://rgho.st/78pKDqpqt

Repro steps:

**1.** Find any class, click "Edit method" for any method, try to add a new method while in edit mode:

```
public IEnumerator Fade()
{
	this.GUIalpha = 1f;
	while (this.GUIalpha > 0f)
	{
		this.GUIalpha -= Time.deltaTime;
		yield return null;
	}
}
```

Result:  
![image](https://user-images.githubusercontent.com/623756/29045236-7ec78ce8-7bcb-11e7-98fd-6bc624e445a7.png)

**2.** Find existing IEnumerator method, try to edit. 
Result: no changes saved/recoded.

https://docs.unity3d.com/Manual/Coroutines.html

lmk if I should take it to  IL rep

**Comment by 0xd4d** [comment]
See the first error message, you're using the generic class without a generic argument. Most likely you want the v1.0 iface, so use `System.Collections.IEnumerator`

**Comment by Kein** [comment]
Does not explain why cant I edit existing Enumerator method, I can reproduce it any time

**Comment by 0xd4d** [comment]
Works for me, so you need to make that assembly file public so someone can actually try to repro it with your assembly.

**Comment by Kein** [comment]
Hmm, alright, a bit later.
I have followup question.

Why explicit while loop with Enumerator:

```
public Dictionary<string,string> dict = new Dictionary<string,string> ();
{
    var enumerator = dict.GetEnumerator();
    while (enumerator.MoveNext())
    {
       //great stuff
    }
}
```

automatically being turned into:

```
public Dictionary<string,string> dict = new Dictionary<string,string> ();
{
foreach (KeyValuePair<string, string> keyValuePair in dict)
  {
       //great stuff
    }
}
```


Now, before you say it is the same in the end - it **ISNT**  actually:
https://forum.unity3d.com/threads/is-there-a-better-and-cleaner-way-then-foreach-c.451228/#post-2924273

I'm currently stuck with **Unity 5.4.2f1** and it has some issues with `foreach{}` allocation. It is [recommended](https://forum.unity3d.com/threads/is-there-a-better-and-cleaner-way-then-foreach-c.451228/#post-2923137) to explicitly use `while{}` to avoid this but apparently I can't?

**Comment by 0xd4d** [comment]
Hint: Add a foreach loop and check IL.
