### ISSUE TITLE
Can't build solution

### ISSUE THREAD

**Issue by vlatkosh** [0xd4d/dnSpy#485]
I downloaded the source, opened the solution in Visual Studio, right clicked on the Solution and clicked "Build Solution". It obviously didn't succeed. Here is the output VS gives me: [output.txt](https://github.com/0xd4d/dnSpy/files/1219706/output.txt)

Please excuse me if I missed anything simple, this is really my first time ever building another project. Also, why is it so hard to just upload a compiled version on the Releases page?

**Edit**
I tried compiling a new, untouched copy, this is the error upon loading the solution: [output1.txt](https://github.com/0xd4d/dnSpy/files/1219778/output1.txt)
Why can't it open the project files? As I said, it's newly downloaded and I haven't touched anything.

**Comment by 0xd4d** [comment]
> Also, why is it so hard to just upload a compiled version on the Releases page?

DId you read any of the text?

**Comment by riQQ** [comment]
Did you follow this guide https://github.com/0xd4d/dnSpy/wiki/Building-dnSpy?
Current builds are downloadable here: https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts
