### ISSUE TITLE
Error when trying to debug a .dll

### ISSUE THREAD

**Issue by ThruZZd** [0xd4d/dnSpy#486]
Hello! Whenever I import a .dll file (C#) and then debug it, I get an error (translated):

Could not start debugger. Make sure, that you have accessto the file "Path to my Desktop/MyFile.dll"
Error:  is not a vaild Win32-application.

Why does this happen?
Thanks!

**Comment by 0xd4d** [comment]
You cant debug DLL files. Debug an exe file that loads the DLL.

**Comment by ThruZZd** [comment]
How would I do that? I cant find a way to simply open the dll with an exe. Have you got a hint for me?

**Comment by 0xd4d** [comment]
http://lmgtfy.com/?q=debug+dll+files
