### ISSUE TITLE
possible to implement

### ISSUE THREAD

**Issue by uragan1987** [0xd4d/dnSpy#487]
hi

i try to deobfuscate a file, and change names from unicode to readable strings
Is it possible to remove the unicode letter (red) behind my string(green)
https://www2.pic-upload.de/img/33746970/Unbenannt.png

uragan

**Comment by SlowLogicBoy** [comment]
![editclassmethod](https://user-images.githubusercontent.com/3121637/29366305-63462456-82a2-11e7-8c38-7d5b8c5ea55c.gif)

**Comment by uragan1987** [comment]
thats my problem, 
i change method name, but old name is still there

**Comment by 0xd4d** [comment]
Try `Ctrl+A` (select all) and enter a new name

**Comment by uragan1987** [comment]
it works with Ctrl+A, thx

**Comment by uragan1987** [comment]
at change method -> Ctrl+A and type your string
