### ISSUE TITLE
Making MSBuild classes public

### ISSUE THREAD

**Issue by stefnotch** [0xd4d/dnSpy#491]
The MSBuild classes are rather useful ([dnspy.Console uses them](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy.Console/Program.cs#L741)), however, they are internal classes.

More specifically, those classes:
[MSBuildProjectCreator](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy.Decompiler/MSBuild/MSBuildProjectCreator.cs#L30)
[ProjectModuleOptions](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy.Decompiler/MSBuild/ProjectModuleOptions.cs#L28)
[ProjectCreatorOptions](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy.Decompiler/MSBuild/ProjectCreatorOptions.cs#L27)

Would it be possible to make them public?

**Comment by 0xd4d** [comment]
They're not public since it's just an internal API.

Do you need to use them in an extension?

**Comment by stefnotch** [comment]
Well, I'm trying to use dnSpy in some other C# application:
It decompiles a game and patches it. At the end, there should be a Visual Studio project that can be recompiled.

And, if I'm not mistaken, those internal APIs can be used to create a Visual Studio project.

**Comment by 0xd4d** [comment]
In that case, you can compile it yourself after making those classes public. Or you can just execute `dnSpy.Console.exe`
