### ISSUE TITLE
 Exception message: Node is already used in another tree. Parameter name: child

### ISSUE THREAD

**Issue by oooPhilippooo** [0xd4d/dnSpy#493]
When trying to "export as project" a C# dll (Target FrameWork .Net 4.6.1)
I get this error
 Exception message: Node is already used in another tree.
Parameter name: child

This is using the version https://ci.appveyor.com/project/0xd4d/dnspy/build/artifacts downloaded on 2017-08-23.

**Comment by 0xd4d** [comment]
How do I repro this?

**Comment by oooPhilippooo** [comment]
I suspect the problem is with Linq queries feeding static members, as that’s the only thing that looks out of the ordinary in the code.
Would it help if I send you one random dll of the sort that I’d get the problem with (your discretion provided)?

**Comment by 0xd4d** [comment]
Yes you can email it to me or just attach the file here.

**Comment by oooPhilippooo** [comment]
[Erp.Services.BO.TransferOrderEntry.dll.zip](https://github.com/0xd4d/dnSpy/files/1247497/Erp.Services.BO.TransferOrderEntry.dll.zip)
i.e. this would be a sample of a randomly choosen dll from my computer that can cause this issue. 
it appears this one is .NET 4.6.1, has Linq queries/lamda expressions , switch case statements and function expressions.
Those listed before seem to be the general downfall traps for most decompilation tools I can find. i.e. ILSpy, reflector.net and the like. I was hoping to find a tool that is more robust around these sort of tricky bits to be able to recompile decompiled code with less manual effort of fixing stuff that the decompiler didn't get right..but dnSpy it didn't even export to project and errored out.
Please beware of copyrights and remove the dll after your troubleshooting, (I'm sure you are always aware of these things with a tool like that..)
