### ISSUE TITLE
Console.WriteLine commands doesn't show in Output window

### ISSUE THREAD

**Issue by Youssef1313** [0xd4d/dnSpy#494]
Hello,
In VS, If I wrote Console.WriteLine("TEST") and debugged the application,"TEST" word should appear in Output window, but that doesn't happen in dnSpy. I think it's a bug ?

**Comment by 0xd4d** [comment]
Not a bug, the application has its own console window.

**Comment by 0xd4d** [comment]
Or perhaps you mean if it's a Windows application? In that case, yes, VS shows it in the Output window.

**Comment by Youssef1313** [comment]
Yes it's a windows application. VS shows it but dnSpy don't.
