### ISSUE TITLE
If there's an "endfinally" in IL, but no "try" in C# code, does it must be an error?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#495]
When I decompile an unpacked file in dnSpy, I find an endfinally instruction in someone method, and it contains an exception handler, but I can't find try finally in C# in dnSpy.

my unpacked file error?
dnSpy error?

**Comment by 0xd4d** [comment]
Have you tested [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)?

**Comment by CreateAndInject** [comment]
Yes, I use it.

here the file
url: http://u.163.com/LV7EIyVn 
code:  H37M29I7

SuperBet.Sin88.EarlyAnalyze

**Comment by UlyssesWu** [comment]
The compiler generate `try` for `foreach`.

https://msdn.microsoft.com/en-us/library/aa664754(v=vs.71).aspx

BTW, what a dirty gambling program...

**Comment by CreateAndInject** [comment]
I don't know, I just want to test my mod de4dot, so I find some example programs.

**Comment by CreateAndInject** [comment]
@UlyssesWu Thanks.
I use this:
using(Form frm=new Form())
{
}
Compile it ,and this code contains endfinally instructions.

So, it's normal if one method contains endfinally but don't contains try finally sentence.
