### ISSUE TITLE
Unity IEnumerators can only be added and seen each per class

### ISSUE THREAD

**Issue by Kein** [0xd4d/dnSpy#496]
So, we are back to this topic. Again and again. Will it be marked as invalid this time too? Will this issue be ever fixed?

I'm working a simple mod for Unity game. I'm using custom class which has added one IEnumerator that method that seems to be working, more or less.

```
public IEnumerator fixThatOneThing()
{
	Console.WriteLog("fixThatOneThing started! Thank god it works ffs!")
	yield return new WaitForSeconds(0.5f);
	//do few things
	yield return new WaitForSeconds(5.5f);
	//finish stuff
	yield break;
}
```

But now, I need another IEnumerator type. I literally clone existing one, change body to appropriate content:

```
public IEnumerator fixAnotherThing()
{
	Console.WriteLog("fixAnotherThing started! Or should be")
	yield return new WaitForSeconds(0.5f);
	//do few things
	yield return new WaitForSeconds(5.5f);
	//finish stuff
	Console.WriteLog("fixAnotherThing is done")
	yield break;
}
```

They both called as usual:

`base.StartCoroutine("coroutineName");`

It COMPLETELY ignores the `fixAnotherThing()`. Like, it does not exist at all. My code is literally:

```
if (condition1)
{
	base.StartCoroutine("fixAnotherThing");
	Console.WriteLog("fixAnotherThing was requested, supposedly");
}
```

I see the log message _"fixAnotherThing was requested, supposedly"_ but there is absolutely nothing from coroutine. Nothing being processed, nothing in log even though first thing it should do is log the execution. The first one, the very first I've made - works fine. But second one, made after that is like does not exist. 

I don't know how can you reproduce it, you probably need to own the game I'm modding for that. But it is goddamn annoying issue.

**Comment by 0xd4d** [comment]
> So, we are back to this topic.

You thinking something is a bug when it's not? I guess so.

> Again and again. Will it be marked as invalid this time too? Will this issue be ever fixed?

If it's a bug, I'll fix it.

You wrote a long post but I couldn't find any sort of evidence that there's something wrong with the assembly and not a runtime problem.
