### ISSUE TITLE
Same class name in diffierent namespace cause decompiled code get CS0146

### ISSUE THREAD

**Issue by gyrodrill** [0xd4d/dnSpy#499]
`namespace DemoNS {
    class Program {
        static void Main(string[] args) {
        }
    }
    class Demo : ns.Demo {
    }
    namespace ns {
        class Demo {
        }
    }
}`
When this snippet get decompiled, the class DemoNS.Demo will use code like
`using DemoNS.ns; class Demo : Demo { }`
and get CS0146 (Circular base class dependency, a class and itself)
Tested on latest [build from master branch](https://ci.appveyor.com/project/0xd4d/dnspy/build/x.x.537), with screenshot here.
![default](https://user-images.githubusercontent.com/9637711/30096616-475f0612-928e-11e7-8744-3035b49a07c3.png)

**Comment by 0xd4d** [comment]
It's a decompiler bug, just add the namespace.
