### ISSUE TITLE
Inconsistent forecolor on strip for dark theme

### ISSUE THREAD

**Issue by MrTrvp** [0xd4d/dnSpy#5]
http://i.imgur.com/wqZO95W.png
http://i.imgur.com/Hxkg3bC.png

**Comment by 0xd4d** [comment]
What OS are you using? I've tested it on Windows 7 and 8.1 with latest updates without seeing that.

Could you try this build: http://s000.tinyupload.com/index.php?file_id=04992091456559642830

**Comment by MrTrvp** [comment]
Yes, that build does work.

http://i.imgur.com/gBRnTQb.png

**Comment by 0xd4d** [comment]
What OS are you using? It's weird that the fg color wasn't inherited by the controls.

**Comment by MrTrvp** [comment]
I'm using Windows 8.1 with a theme from deviantart, which must have been the issue.
