### ISSUE TITLE
Debugging stack

### ISSUE THREAD

**Issue by TheProxyRE** [0xd4d/dnSpy#501]
Just want to request if its possible in locals to add Stacks tree where it would show all current stack objects.

For example this is useful when i'm trying to debug in IL mode and breakpoints on stsfld where parameter isn't possible to debug return value (some assembly ref call or something similar).

**Comment by 0xd4d** [comment]
No unfortunately this isn't possible. The JITter doesn't support it. Showing return values of method calls in the locals window is on my to do list (and the watch window).

**Comment by TheProxyRE** [comment]
Also if it's possible add support for debugging in GAC Modules

**Comment by 0xd4d** [comment]
It's already possible, just step into `Console.WriteLine("Hello, World!")` or any other method.
