### ISSUE TITLE
The translations of "AskExitUnsavedFile" and "AskExitUnsavedFiles" in zh-CN are wrong

### ISSUE THREAD

**Issue by bysdxt** [0xd4d/dnSpy#502]
"确定要退出吗？" means "Do you want to exit?", not "Do you want to save it before exiting?". It should be "退出前是否保存？"

**Comment by UlyssesWu** [comment]
Those translations were already changed to correct version - but not merged yet? 
The resx file was commited in Jan 19, and new translations for them were submitted in Feb 18 by me.
see: 
https://github.com/0xd4d/dnSpy/blob/master/Extensions/dnSpy.AsmEditor/Properties/dnSpy.AsmEditor.Resources.zh-CN.resx
https://crowdin.com/translate/dnspy/12/en-zhcn#4256

你说的这些翻译是上古时期的翻译（不是我干的），我早已提交了正确的翻译，但是一直没有合并进去。

P.S. Those wrong translations were very old and not made by me.

**Comment by CreateAndInject** [comment]
普通类型=>泛型类型
堆栈调用=>调用堆栈

**Comment by UlyssesWu** [comment]
@CreateAndInject Thanks. These are fixed just now.
"普通类型"那个也是上古时期的翻译错误（最近又来了一个这么翻的，就很难受）。
"堆栈调用"是我的锅。

**Comment by 0xd4d** [comment]
The strings haven't been added to the master branch yet, but should be before 4.0 is released.

**Comment by 0xd4d** [comment]
They've been added to the dbg branch but it isn't ready to be used yet.
