### ISSUE TITLE
Why there are so many types marked as "internal" and "InternalsVisibleTo".

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#503]
Why there are so many types marked as "internal", and use "InternalsVisibleTo" to call it.

If I want to use, I must modify the source, so I can't keep these dlls update.

Could you change these types to public?

**Comment by bysdxt** [comment]
I also want to ask the same question...
I want to make a extension to change code, but I can not access interface dnSpy.Contracts.Documents.IMethodAnnotations, and dnSpy.AsmEditor can...

**Comment by 0xd4d** [comment]
They're internal since they're either to specialized to be useful by someone else or the APIs aren't ready to be public.
