### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#504]
I create a plugin for dnSpy like this, when I call
new MyWindow().ShowDialog();
I will get an exception : System.ArgumentOutOfRangeException 

namespace Test.x
{
	[ExportMenuItem(Header = "Test", Group = "0,73BEBC37-387A-4004-8076-A1A90A17611B")]
	sealed class ExtensionCommand1 : MenuItemBase
	{
		public override void Execute(IMenuItemContext context)
		{
			new dnSpy.Contracts.Controls.MetroWindow().ShowDialog();// no problem
			new MyWindow().ShowDialog();//**_System.ArgumentOutOfRangeException in GetVisualChild(0), becuase VisualChildrenCount=0_**
		}
	}
}
class MyWindow: dnSpy.Contracts.Controls.MetroWindow
{
}

**Comment by 0xd4d** [comment]
Create a normal XAML window that derives from it.

**Comment by CreateAndInject** [comment]
It has the same problem:
<ctrls:MetroWindow x:Class="Test.x.MyWindow2"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
            Title="MyWindow2" Height="350" Width="525"
            xmlns:ctrls="clr-namespace:dnSpy.Contracts.Controls;assembly=dnSpy.Contracts.DnSpy">
    <Grid>
            
    </Grid>
</ctrls:MetroWindow>

namespace Test.x
{
	public partial class MyWindow2 
	{
		public MyWindow2()
		{
			InitializeComponent();
		}
	}
}



public override void Execute(IMenuItemContext context)
 {
 new dnSpy.Contracts.Controls.MetroWindow().ShowDialog();// no problem
 new MyWindow2().ShowDialog();//**_System.ArgumentOutOfRangeException in GetVisualChild(0), becuase VisualChildrenCount=0_**
 }
 }

**Comment by 0xd4d** [comment]
Have a look at working windows in dnSpy and add whatever things they do, especially the XAML attributes you haven't added yet, perhaps the style etc. Then remove one by one until it crashes and you know hiwhc one is required.
