### ISSUE TITLE
Spawn ironpython session at breakpoint

### ISSUE THREAD

**Issue by truekonrads** [0xd4d/dnSpy#508]
Hello,

I wanted to dynamically inspect content at breakpoints. I tried the C# compiler but it seemed unaware where the debug session was - not sure if it is meant to. What would be cool is if it would be possible to interact with local variables at breakpoint using IronPython

**Comment by 0xd4d** [comment]
The debugger API will be public in v4.0, you could then use C# scripting to control the debugger, inspect state etc (or you could add your own ironpython extension if you prefer ironpython).
