### ISSUE TITLE
Analyze does not show all call locations

### ISSUE THREAD

**Issue by pardeike** [0xd4d/dnSpy#509]
I am using dnSpy with dnSpy.Analyzer v3.0.1.0 on the mono dll of the game Rimworld. ILSpy and dnSpy do not show all references of methods. In example: Pawn.Kill() is shown to be used at

	RimWorld.Building_CrashedShipPart.HarmPlant() : void @06001C08
	RimWorld.CompExplosive.Detonate(Map) : void @06001EAD
	RimWorld.GameCondition_ToxicFallout.DoCellSteadyEffects(IntVec3) : void @060009C2
	Verse.DamageWorker.Apply(DamageInfo, Thing) : float @060031C2
	Verse.Dialog_DebugActionsMenu.DoListingItems_MapTools() : void @060043AC

but in fact this is the result of .NET Reflector or dotPeek:

	RimWorld.Building_CrashedShipPart.HarmPlant() : Void
	RimWorld.CompExplosive.Detonate(Map) : Void
	RimWorld.ExecutionUtility.DoExecutionByCut(Pawn, Pawn) : Void
	RimWorld.GameCondition_ToxicFallout.DoCellSteadyEffects(IntVec3) : Void
	RimWorld.Planet.Caravan+<GetGizmos>c__IteratorFF.<>m__3DA() : Void
	Verse.DamageWorker.Apply(DamageInfo, Thing) : Single
	Verse.Dialog_DebugActionsMenu.<DoListingItems_MapTools>m__ABA() : Void
	Verse.Hediff.Tick() : Void
	Verse.Pawn_HealthTracker.CheckForStateChange(Nullable<DamageInfo>, Hediff) : Void
	Verse.Pawn_HealthTracker.PostApplyDamage(DamageInfo, Single) : Void

Where, i.e. Verse.Pawn_HealthTracker.CheckForStateChange is an ordinary method:

```
private void CheckForStateChange(/*Parameter with token 08002EEC*/DamageInfo? dinfo, /*Parameter with token 08002EED*/Hediff hediff)
    {
      if (this.Dead)
        return;
      if (this.ShouldBeDead())
      {
        if (this.pawn.Destroyed)
          return;
        bool flag = PawnUtility.ShouldSendNotificationAbout(this.pawn);
        Caravan caravan = this.pawn.GetCaravan();
        this.pawn.Kill(dinfo);
        if (!flag)
          return;
        this.NotifyPlayerOfKilled(dinfo, hediff, caravan);
      }
      else if (!this.Downed)
      {
        if (this.ShouldBeDowned())
        {
          float num = !this.pawn.RaceProps.Animal ? 0.67f : 0.47f;
          if (!this.forceIncap && dinfo.HasValue && (dinfo.Value.Def.externalViolence && (this.pawn.Faction == null || !this.pawn.Faction.IsPlayer) && (!this.pawn.IsPrisonerOfColony && this.pawn.RaceProps.IsFlesh && (double) Rand.Value < (double) num)))
          {
            this.pawn.Kill(dinfo);
          }
          else
          {
            this.forceIncap = false;
            this.MakeDowned(dinfo, hediff);
          }
        }
        else
        {
          if (this.capacities.CapableOf(PawnCapacityDefOf.Manipulation))
            return;
          if (this.pawn.carryTracker != null && this.pawn.carryTracker.CarriedThing != null && (this.pawn.jobs != null && this.pawn.CurJob != null))
            this.pawn.jobs.EndCurrentJob(JobCondition.InterruptForced, true);
          if (this.pawn.equipment == null || this.pawn.equipment.Primary == null)
            return;
          if (this.pawn.InContainerEnclosed)
            this.pawn.equipment.TryTransferEquipmentToContainer(this.pawn.equipment.Primary, this.pawn.holdingOwner);
          else if (this.pawn.SpawnedOrAnyParentSpawned)
          {
            ThingWithComps resultingEq;
            this.pawn.equipment.TryDropEquipment(this.pawn.equipment.Primary, out resultingEq, this.pawn.PositionHeld, true);
          }
          else
            this.pawn.equipment.DestroyEquipment(this.pawn.equipment.Primary);
        }
      }
      else
      {
        if (this.ShouldBeDowned())
          return;
        this.MakeUndowned();
      }
    }
```

How can I make dnSpy show all references?

**Comment by 0xd4d** [comment]
It's possible that the other calls are through an interface method or a base method. The analyzer only shows calls to the exact same method.

**Comment by pardeike** [comment]
So lets just look at the details of the above example (everything in the same namespace and assembly):

```csharp
public class Verse.Pawn : Verse.ThingWithComps
{
	public override void Kill(DamageInfo? dinfo) { }
}

public class Verse.ThingWithComps : Verse.Thing
{
	// no Kill() here
}

public class Verse.Thing : Verse.Entity
{
	public virtual void Kill([Optional, DefaultParameterValue(null)] DamageInfo? dinfo) { }
}

public class Verse.Pawn_HealthTracker
{
	private Verse.Pawn pawn;

	private void CheckForStateChange(DamageInfo? dinfo, Hediff hediff)
	{
		// ...
		this.pawn.Kill(dinfo);
		// ...
	}
}
```
And I double-checked that I did the **Analiyze** on `Pawn.Kill()` and not on `Thing.Kill()`. Looks to me like a straight call to `Pawn.Kill()` but maybe I am missing something here.

**Comment by pardeike** [comment]
And .NET Refractor returns the shorter list:

	RimWorld.Building_CrashedShipPart.HarmPlant() : void @06001C08
	RimWorld.CompExplosive.Detonate(Map) : void @06001EAD
	RimWorld.GameCondition_ToxicFallout.DoCellSteadyEffects(IntVec3) : void @060009C2
	Verse.DamageWorker.Apply(DamageInfo, Thing) : float @060031C2
	Verse.Dialog_DebugActionsMenu.DoListingItems_MapTools() : void @060043AC

when I call *Analyze* on `Thing.Kill()` btw.

**Comment by pardeike** [comment]
After debugging this issue (or should we call it annoyance), I can easily make dnSpy list all methods by changing this line:

https://github.com/0xd4d/dnSpy/blob/959d124739a92e69bc0e0224bf2f55fcbeb1256c/Extensions/dnSpy.Analyzer/TreeNodes/VirtualMethodUsedByNode.cs#L92

to check for both: `Code.Call` or `Code.Callvirt`. Please see the comments in this stackoverflow answer for motivation: https://stackoverflow.com/a/193952/3351794

**Comment by 0xd4d** [comment]
Thanks for debugging this! The fix seems to be correct, both call and callvirt should be checked in that if statement. Do you want to add a fix in a PR?

**Comment by pardeike** [comment]
Pull request submitted
