### ISSUE TITLE
MethodOverridenNode.cs doesn't compile

### ISSUE THREAD

**Issue by stefnotch** [0xd4d/dnSpy#510]
This line: `if (baseType is TypeDef def) {` doesn't seem to compile. (And I doubt that it is valid C# code)

It was caused by this commit: https://github.com/0xd4d/dnSpy/commit/d7951672dec4d9f2664f282b7a2a1d31ab365d03
Here is the file: https://github.com/0xd4d/dnSpy/blob/master/Extensions/dnSpy.Analyzer/TreeNodes/MethodOverriddenNode.cs#L58

Also, the commit seems to have caused a few other compile time errors.

**Comment by UlyssesWu** [comment]
It's C#7 feature. Use **VS2017** to compile this project.
I think what you should doubt is whether you have learned enough about C#7 before asking this.

**Comment by stefnotch** [comment]
Oh, ok. (I checked the MDN docs, they don't mention anything about this.)

**Comment by HoLLy-HaCKeR** [comment]
To be honest, I didn't expect people to still be using VS2015 when committing this. The project's C# version is not forced to C# 6 so I assumed it was fine.

**Comment by 0x53A** [comment]
You could use the nuget package Microsoft.Net.Compilers.

This will replace the system-compilers, so that even people on VS2013 could compile C#7. (You would of course get squiggles at design-time, but build would work).

**Comment by 0xd4d** [comment]
@HoLLy-HaCKeR It was I who didn't notice that it was C#7 in that commit. I'm just too used to it, otherwise I would've mentioned that you shouldn't use C#7 in master yet. I'm using C# 7.1 in the dbg branch.

**Comment by 0xd4d** [comment]
@stefnotch You should now be able to compile the code in the master branch since @HoLLy-HaCKeR just added a fix.
