### ISSUE TITLE
Add support to see IL code and high level code side by side

### ISSUE THREAD

**Issue by pardeike** [0xd4d/dnSpy#514]
In my main open source project [Harmony](https://github.com/pardeike/Harmony) users work very closely with disassembled methods and their IL code. In order to find out how to design a transpiler, a good understanding of the method and the resulting IL code is required.

Copying from other popular but non-free alternatives, a split screen solution showing the original IL code with synchronous highlighting from either one to the other is a very elegant solution.

This suggestion might be the start of a discussion on how to implement this the best way within dnSpy.

Here's an example on how dotPeek is solving this:
![dotPeek example](https://www.jetbrains.com/help/img/dotnet/2017.2/using_il_viewer.png)

**Comment by pardeike** [comment]
To be clear, I am willing to implement this myself but since I am new to dnSpy, I would love to get some starting suggestions.

**Comment by 0xd4d** [comment]
The way dotPeek seems to do it in a different window is one way of doing it but perhaps showing the IL inline below the high level language is easier to understand (and implement).

```C#
			if (str1 == null)
		/* 0x0001106D 03           */ IL_0019: ldarg.1
		/* 0x0001106E 2D07         */ IL_001A: brtrue.s  IL_0023
			{
				str1 = string.Empty;
		/* 0x00011070 7E74020004   */ IL_001C: ldsfld    string System.String::Empty
		/* 0x00011075 1001         */ IL_0021: starg.s   str1
			}
```

It can be generalized to 2+ languages but using 3+ languages or any other 2nd language than IL doesn't seem to make much sense.

All languages write to a IDecompilerOutput, and it doesn't only get the text, but also colors and IL offsets and other debugging info. It should already contain all the info you need to implement this.

You could first call the C#/VB decompiler and get its output, then you could call the 2nd language (IL) and get the same data. A second method can then create a new result that adds the IL below all statements in lang1 to get the output seen above.

The class with all debug info is called dnSpy.Contracts.Decompiler.MethodDebugInfo

A non-decompiler option could enable this if the language isn't IL.

**Comment by maddinthegreat** [comment]
Please implement this.
Thanks
