### ISSUE TITLE
Search in Method Calls

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnSpy#515]
Is possible add Search in Method Calls feature ? Like JustDecompiler.

![s](https://user-images.githubusercontent.com/706507/30703995-2665fd66-9ea6-11e7-88a1-217302b9f3a3.png)

**Comment by 0xd4d** [comment]
Could you describe this feature. It's already possible to search for methods if you select Methods in the search window combo box.

**Comment by bprg** [comment]
For example I want search _ToCharArray_ contain method.

```
public void MyMethod()
{
  char[] charArray = "string".ToCharArray();
}
```

**Comment by 0xd4d** [comment]
You mean you want to find all calls that call a method called `ToCharArray`?

**Comment by bprg** [comment]
> You mean you want to find all call instructions that call a method called ToCharArray?

Yes.

**Comment by 0xd4d** [comment]
No upvotes, no PR, I've never needed it -> closing.

**Comment by mad2342** [comment]
a pity..., just found this and it would have been really helpful

**Comment by mad2342** [comment]
nevermind, right click on method and analyse is enough
