### ISSUE TITLE
Does not find string

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnSpy#516]
String search does not find **"\r55/?"** string.

`char[] charArray = "\r55/?".ToCharArray();`

**Comment by 0xd4d** [comment]
If you search for `\r55/?` it won't find it because it doesn't interpret `\` as an escape character. You could use regex search: `/\r55/?/`

**Comment by bprg** [comment]
Thanks now find the string, But I tried JustDecompiler find the string without using regex.
