### ISSUE TITLE
How to add my own transform?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#517]
I don't find the property AstTransforms or ILTransforms, how can I add my own transform without modifying the source of dnSpy?

**Comment by CreateAndInject** [comment]
I'm sorry, it's ILSpy3.0, and dnSpy is base on ILSpy2.x, maybe can't do that.

**Comment by CreateAndInject** [comment]
dnSpy is hard to modify the decompiled output, it seems we can only use IDecompilerOutput which is based on text rather than AST. I think dnSpy should support some way so we can use our own Transform or TextTokenWriter like ILSpy3.x.

**Comment by 0xd4d** [comment]
The implementation details of the decompilers aren't exposed.

I have no idea what you're trying to do but I'm guessing you want to fix some decompiler bug, in which case it's probably better to fix the bug in the decompiler instead of adding your own transforms.
