### ISSUE TITLE
trace into/over planned?

### ISSUE THREAD

**Issue by uragan1987** [0xd4d/dnSpy#523]
hi

is trace into/over feature planned?
Or maybe its possible now with addons?

cya
uragan1987

**Comment by 0xd4d** [comment]
The next verison will get an updated debugger. You'll be able to add tracepoints so you can log a message whenever code executes in a certain method. If you want to log every statement executed you'll have to write a plugin using the new debugger API.

**Comment by uragan1987** [comment]
👍

**Comment by 0xd4d** [comment]
Use latest beta.
