### ISSUE TITLE
 2 Error on debug compile

### ISSUE THREAD

**Issue by manojdjoshi** [0xd4d/dnSpy#53]
"L:\dnSpy\dnSpy.sln" (default target) (1) ->
      "L:\dnSpy\dnSpy\dnSpy.csproj" (default target) (5) ->
      "L:\dnSpy\dnSpy\0izcumkr.tmp_proj" (_CompileTemporaryAssembly target) (18) ->
      (CoreCompile target) ->
        Files\DnSpyFile.cs(146,16): error CS1502: The best overloaded method match for 'dnlib.PE.PEImage.PEImage(byte[], bool)' has some invalid arguments [L:\dnSpy\dnSpy\0izcumkr.tmp_proj]
        Files\DnSpyFile.cs(146,57): error CS1503: Argument 2: cannot convert from 'string' to 'bool' [L:\dnSpy\dnSpy\0izcumkr.tmp_proj]

   13 Warning(s)
   2 Error(s)

**Comment by 0xd4d** [comment]
You must update all submodules:

```sh
git submodule update --init --recursive
```
