### ISSUE TITLE
Regenerate NGEN image when saving assembly

### ISSUE THREAD

**Issue by cocoon** [0xd4d/dnSpy#543]
So I had an interesting effect while debugging and modify an assembly.

When runnig/debugging the program with the modified dll in dnspy, all was working as expected.
When running the program from windows explorer, it wasn't.

First I thougt about GAC, but it wasn't in the GAC.
Then I checked what assemblies are loaded when running from windows explorer and found out it used an ngen native image from 
`C:\Windows\assembly\NativeImages_v4.0.30319_64`
whilest dnspy was loading the one from the program folder.

I thought I just share it here, maybe dnSpy could detect and warn in such cases when starting debugging, 
and offer a selection and maybe add a management tool like for the GAC.

Additionally I wasn't able to "ngen uninstall" the old one anymore as it said, it isn't installed.
So I had to rename the folder containingthe orphaned native image.
If someone knows a way how to cleanup such orphaned native images "correctly" please let me know.

I read that references are aditionally kept in the registry so that ngen knows if it can delete a native image or if it is still in use by other programs:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Fusion\NativeImagesIndex\`

BTW: congratulations to the 4.0.0 Beta1 release, impressive work!

**Comment by 0xd4d** [comment]
dnSpy disables optimizations (to make debugging easier) so the native images shouldn't be used, which is what you were experiencing. It's possible to disable this but the debugging experience is so poor that it's almost useless.

**Comment by cocoon** [comment]
Thanks for answereing that quick.

Good point to not use the native image for debugging, makes totally sense of course.

Maybe when saving modified assemblies it could show a warning that makes aware of the possible problem, and make it possible to not show it again, just an idea, maybe same for GAC:

![nativeimages](https://user-images.githubusercontent.com/1071741/31398483-619e8b44-ade9-11e7-88c7-d164658ff323.png)

**Comment by 0xd4d** [comment]
I've updated the title since this is now a feature request.

**Comment by 0x53A** [comment]
As far as I know NGEN images are loaded based on the mvid, so another option would be to change the mvid when rewriting the assembly.

**Comment by 0xd4d** [comment]
@cocoon Did you try changing the MVID? You can change the MVID if you right click the module and click edit module.

**Comment by cocoon** [comment]
Thanks for that, tried it right now and I can confirm it is working then!

Still it might be good to make one aware of existing native images and maybe offer to change the MVID automatically instead of regenerate it.
