### ISSUE TITLE
InvalidOperationException 'Edit Class (C#)...'

### ISSUE THREAD

**Issue by DC4-SERGEY** [0xd4d/dnSpy#545]
Good evening.

After two changes in the class I get a stable error

InvalidOperationException : The operation is invalid due to the current state of the object

In the class added only import dll and function call

http://skrinshoter.ru/i/111017/kYycct7u.png
![kyycct7u](https://user-images.githubusercontent.com/32691168/31417702-f759f3e4-ae39-11e7-8620-ff04bb3335e2.png)

**Comment by 0xd4d** [comment]
How do I reproduce this?

**Comment by DC4-SERGEY** [comment]
@0xd4d I choose to edit the class - I edit and compile. And so 2 times with different edits and get an error

**Comment by DC4-SERGEY** [comment]
@0xd4d The code is working - in another dll the same code works fine

**Comment by 0xd4d** [comment]
You need to write down the steps so I can reproduce it, and upload the file somewhere or email it to me.

**Comment by DC4-SERGEY** [comment]
@0xd4d https://youtu.be/-fLyi9T0t0E

**Comment by 0xd4d** [comment]
I can't repro it, could you email me the file or upload it somewhere?

**Comment by 0xd4d** [comment]
Also make sure you're using the latest version https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts

**Comment by DC4-SERGEY** [comment]
@0xd4d v4.0.0-beta1

**Comment by 0xd4d** [comment]
I'll repeat this again:

> I can't repro it, could you email me the file or upload it somewhere?

**Comment by DC4-SERGEY** [comment]
@0xd4d I do not know how to send here in private messages

**Comment by 0xd4d** [comment]
My email is [here](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy/MainApp/StartUpClass.cs#L2)
