### ISSUE TITLE
Stop working when debug attach iisexpress (4.0.0beta1 )

### ISSUE THREAD

**Issue by jrt324** [0xd4d/dnSpy#546]
when i attached the iisexpress.exe and select Module dll, some times it will cause the dnSpy  stop working, but if i select a simply no dependency  Module (e.g: Autofac.dll) ，it working fine

Test environment:
dnspy-x86.exe
windows 10

**Comment by 0xd4d** [comment]
Does dnSpy crash?

How do I reproduce this? Do you have some files?

**Comment by jrt324** [comment]
it's a complicate project ,has 50+ dlls，
I will reduce them and send to you later.

**Comment by 0xd4d** [comment]
My email is [here](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy/MainApp/StartUpClass.cs#L2)

**Comment by 0xd4d** [comment]
Closing this for now. Re-open it if you send the files.
