### ISSUE TITLE
Is there any schedule to migrate the decompiler to ILSpy 3.x?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#547]

**Comment by 0xd4d** [comment]
No, there's no good enough reason to port the decompiler engine from cecil to dnlib when it's not even finished. This is not something I plan on doing this year but I do accept PRs.

**Comment by CreateAndInject** [comment]
So if ILSpy 3.x is stable sometime, is there any plan?

**Comment by fireundubh** [comment]
@0xd4d ILSpy 3.x is out of beta and now 3.0.1. The issues in #682 are largely gone in 3.x's output.
