### ISSUE TITLE
Add support for macOS.

### ISSUE THREAD

**Issue by feicong** [0xd4d/dnSpy#549]
is there a plan to support the dnSpy run on macOS system?

**Comment by 0xd4d** [comment]
No.

**Comment by nameszian** [comment]
- For Windows/Mac/Linux: [Visual Studio Code](https://code.visualstudio.com) + [ilSpy extension](https://marketplace.visualstudio.com/items?itemName=icsharpcode.ilspy-vscode)

Tested on MacOS 10.14.

**Comment by thecherrytree** [comment]
> * For Windows/Mac/Linux: [Visual Studio Code](https://code.visualstudio.com) + [ilSpy extension](https://marketplace.visualstudio.com/items?itemName=icsharpcode.ilspy-vscode)
> 
> Tested on MacOS 10.14.

This was so easy.
