### ISSUE TITLE
Recompile Events not Working

### ISSUE THREAD

**Issue by HurricanKai** [0xd4d/dnSpy#551]
Whats Happening:

The Decompiler decompiles
`public static event Action<string> xyz;`

to 2 actual fields, one of them hidden.

`        [field: CompilerGenerated, DebuggerBrowsable(0)]
        public static  event Action<InputDevice> OnActiveDeviceChanged;`
and
`public static event Action<InputDevice> OnActiveDeviceChanged;`
(this one is also the original)

Now when i recompile, he cant know what to use.

At least thats what i think. (And what is visible by using .Net Reflector 9.0

**Comment by 0xd4d** [comment]
Everything is made public so the compiler can have access to private members of the editing class, so it now gets confused when it sees a field and an event with the same name.
