### ISSUE TITLE
Inspect NuGet packages

### ISSUE THREAD

**Issue by wonea** [0xd4d/dnSpy#552]
Would it be possible to inspect NuGet packages (*.nupkg) using dnSpy? This would be incredibly helpful.

**Comment by 0xd4d** [comment]
There's no plan at the moment to support reading files from zip files in Assembly Explorer.

They're renamed zip files so current workaround is to extract the DLL file from it.

**Comment by wonea** [comment]
Thanks, it's just convenience that's all. I rarely work with just DLLs.
