### ISSUE TITLE
Generate a get-locals assembly if expression compiler fails to do so

### ISSUE THREAD

**Issue by n4p5ter** [0xd4d/dnSpy#555]
When entering this function , local variables disappear and instead of them this message appears 

> "error cs0570; '<>x.<>m0(?,?)' is not supported by the language"

 . But before entering,  everything is fine.
```
[return: MarshalAs(UnmanagedType.U1)]
	internal unsafe static bool Check(basic_string<char,std::char_traits<char>,std::allocator<char>\u0020>* a, basic_string<char,std::char_traits<char>,std::allocator<char>\u0020>* b)
	{
		bool result;
		try
		{
			try
			{
				basic_string<char,std::char_traits<char>,std::allocator<char>\u0020> basic_string<char,std::char_traits<char>,std::allocator<char>\u0020>;
				<Module>.std.basic_string<char,std::char_traits<char>,std::allocator<char>\u0020>.{ctor}(ref basic_string<char,std::char_traits<char>,std::allocator<char>\u0020>, (sbyte*)(&<Module>.??_C@_00CNPNBAHC@?$AA@));
				try
				{ 
......
```

**Comment by 0xd4d** [comment]
I added the debugger label since I think you're talking about the debugger, correct me if I'm wrong.

The code above is originally C++/.NET code and the only languages the debugger supports is C# and Visual Basic. The C#/VB compilers probably don't like the weird variable names.

**Comment by 0xd4d** [comment]
I added the bug label, something should be shown, even if the compilers fail.

**Comment by 0xd4d** [comment]
Latest build contains the fix. https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts
