### ISSUE TITLE
Multiple assemblies with equivalent identity have been imported

### ISSUE THREAD

**Issue by zemasa** [0xd4d/dnSpy#556]
Trying to edit a C# method of an assembly. As soon as I click on "Edit Method (C#)" dnSpy loads into the Assembly Explorer:

- System.Dynamic
- mscorlib
- System
- System.Core

The problem is that the assembly I am trying to patch already relies on it's own version of the last three assemblies.

**Comment by 0xd4d** [comment]
Are you trying to add a reference to a .NET Framework assembly to a Unity assembly?

**Comment by zemasa** [comment]
Not trying to add a reference at all. Just loading the DLL into dnSpy, find the class, find the method (by now dnSpy already added all the referenced assemblies which is very helpful - they are all in the same folder as the DLL I'm patching) but then when I click on "Edit Method (C#)" dnSpy loads the aforementioned assemblies - which were already loaded from the local versions - and when I edit and try to compile it fails due to having two assemblies with equivalent identities.

**Comment by 0xd4d** [comment]
Could you email it to me or upload it somewhere? My email is [here](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy/MainApp/StartUpClass.cs#L2)

**Comment by zemasa** [comment]
sorry, some tool had added a .config file to the directory. removing it solved the issue. my apologies for wasting your time.
