### ISSUE TITLE
Breakpoint issue

### ISSUE THREAD

**Issue by MrArting** [0xd4d/dnSpy#558]
I can't set breakpoints properly in dynamic assemblies which are loaded from memory.

![screenshot_2](https://user-images.githubusercontent.com/19289745/31652901-6ac30976-b329-11e7-95e3-ba7b49555407.png)
![screenshot_3](https://user-images.githubusercontent.com/19289745/31652910-6d44e552-b329-11e7-9efd-8d7e7374afbe.png)

**Comment by 0xd4d** [comment]
Latest build now has the fix: https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts
