### ISSUE TITLE
Can't view structs?

### ISSUE THREAD

**Issue by thinkv** [0xd4d/dnSpy#56]
Hi 0x, unsure how to describe this one.

But if you see in my screenshot, I can view and edit "Structs" in other viewers, however if I go to the same mdtoken in dnSpy it simply does not exist, and I cannot see structs in the tree.

Any ideas?
<img width="528" alt="screen shot 2015-11-19 at 1 23 55 pm" src="https://cloud.githubusercontent.com/assets/3784485/11260694/ae928b60-8ec1-11e5-9b78-4d840849eea7.png">

**Comment by 0xd4d** [comment]
That's probably because it's a compiler generated method. Options -> and make sure "Decompiler -> Show hidden compiler generated types and methods" is checked.

**Comment by Alcatraz3222** [comment]
Also the analyzer doesn't works when the method is inside it, not sure why but i analyzed a method which is called in this method and it doesn't appears in the analyzer.

http://prntscr.com/94ukqu

**Comment by 0xd4d** [comment]
You mean the analyzer can't analyze a lambda expression or what do you mean by "when the method is inside it?"

**Comment by Alcatraz3222** [comment]
Well, i'm not sure what kind of method is that one, but if you check the image bellow you will see the analyzer doesn't detects that the method is used in there

http://prntscr.com/94xyyw

**Comment by 0xd4d** [comment]
Does it work if you disable anonymous methods in the decompiler settings? If not, try to disable everything in decompiler settings and see what happens.

**Comment by Alcatraz3222** [comment]
I disabled every option and still doesn't appears

**Comment by 0xd4d** [comment]
Email me the unpacked program and I'll have a look.

**Comment by 0xd4d** [comment]
Fixed by latest commit.
