### ISSUE TITLE
Add a Mono debug engine

### ISSUE THREAD

**Issue by 0xd4d** [0xd4d/dnSpy#561]
Needed: https://github.com/mono/mono/tree/master/mcs/class/Mono.Debugger.Soft

**Comment by HoLLy-HaCKeR** [comment]
This would mean support for Unity games, since they use an embedded copy of Mono?

**Comment by 0xd4d** [comment]
Yes I think it will work with Unity too.

**Comment by 0xd4d** [comment]
Try the latest master build and see #652
