### ISSUE TITLE
Update assembly resolver to support .NET Core, Silverlight

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#564]
It seems dnlib add silverlight directory, dnSply is based on dnlib, why doesn't it load silverlight assemblies？

**Comment by 0xd4d** [comment]
I've updated the title. We need better .NET Core support too, the current assembly resolver prefers .NET Framework assemblies.

**Comment by 0xd4d** [comment]
.NET Core support was added. Silverlight is dead, and I didn't have it installed so there's currently no support for resolving those assemblies. Send a PR if this is important.
