### ISSUE TITLE
WPF bug

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#565]
Why does dnSpy sometimes use:
```
<ns:Window1...>
</ns:Window1>
```
rather than
```
<Window x:Class="ns.Window1"..>
</Window>
```

**Comment by 0xd4d** [comment]
Is it invalid XAML?

**Comment by CreateAndInject** [comment]
Create a wpf project build it and named "test1.exe"
Add a new Window(Window1.xaml) to the project, build it and named "test2.exe"

drag "test1.exe" to dnSpy, then drag "test2.exe" to dnSpy.
View "Window1.baml" in "test2.exe", it will show as I say.

If drag "test2.exe" first, it's normal.

When decompiling Window1.baml, dnSpy doesn't find type from the current module, instead, dnSpy uses AssemblyName to find the module, but these two files have the same AssemblyName, so dnSpy will find the first matched assembly in the treeview, this time, dnSpy can not find the type "Window1" in "test1.exe"

**Comment by 0xd4d** [comment]
It's not a WPF bug. You have two files with the same assembly name, which of course makes it impossible for any tool to know which assembly it should use. In this case, it just uses the first one.
