### ISSUE TITLE
Tell me what's wrong?

### ISSUE THREAD

**Issue by DC4-SERGEY** [0xd4d/dnSpy#566]
![kkwyxovq](https://user-images.githubusercontent.com/32691168/31863228-a17ca8e0-b753-11e7-900d-43007e009080.png)

**Comment by HoLLy-HaCKeR** [comment]
You probably want to be a bit more specific with what you want to do. Are you adding code to that class? Does the error occur even when you don't add any code? What have you tried so far to fix it?

You should post a description of the problem you're having, the list of errors you get (including why they shouldn't happen), and possibly steps to reproduce this issue.

**Comment by 0xd4d** [comment]
I'm still waiting for #545

**Comment by DC4-SERGEY** [comment]
@0xd4d Well wait - I solved that problem.

**Comment by DC4-SERGEY** [comment]
@HoLLy-HaCKeR I had nothing to rule - I opened the class and decided to compile it - complains about the T parameter

**Comment by 0xd4d** [comment]
> @0xd4d Well wait - I solved that problem.

The bug is still there, and I need the file to fix the bug.

**Comment by DC4-SERGEY** [comment]
try to edit the blueprintdatablock and see it

**Comment by DC4-SERGEY** [comment]
@0xd4d ?

**Comment by 0xd4d** [comment]
The compiler gets confused because the real class and the temporary class you're editing in is in two different assemblies. You can try editing just one method and removing as many methods, fields or interfaces as possible from main.g.cs and try again until it compiles.

**Comment by DC4-SERGEY** [comment]
@0xd4d I do not have main.g.cs
![image](https://user-images.githubusercontent.com/32691168/31994970-37af2ff2-b98b-11e7-8f43-b42561ee30c6.png)

**Comment by 0xd4d** [comment]
Edit just one method instead of the whole class.

**Comment by DC4-SERGEY** [comment]
@ thx
