### ISSUE TITLE
Why isn't "Enable All Filtered Exceptions" there in new version?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#567]

**Comment by 0xd4d** [comment]
It's possible to toggle all exceptions that are currently visible.

**Comment by CreateAndInject** [comment]
But how?

**Comment by CreateAndInject** [comment]
I can only check it one by one. If there are 500 exceptions, I must click 500 times.

**Comment by 0xd4d** [comment]
It's turned into a standard UI question now, "How do I toggle 500 checkboxes using the keyboard?" I think you know what to do now, I almost gave away the answer.

**Comment by CreateAndInject** [comment]
But I don't know, I use Ctrl+Click ,Shift+Click ,Right Click,Ctrl+A，but I can't do it

**Comment by CreateAndInject** [comment]
Sometimes, I want to break when occurs an exception, but I don't know which exception, so I must check all the exceptions

**Comment by 0xd4d** [comment]
I'm trying to [teach you how to fish](https://en.wiktionary.org/wiki/give_a_man_a_fish_and_you_feed_him_for_a_day;_teach_a_man_to_fish_and_you_feed_him_for_a_lifetime). Use your favorite search engine to search. It'll teach you how to toggle a checkbox with the keyboard. Now all you need to figure out how to select 500 checkboxes.

**Comment by CreateAndInject** [comment]
Er.. I get it , press "Space" can toggle the checkboxes, I've never used this shortcut before.
