### ISSUE TITLE
Assembly not Displayed in Assembly Explorer

### ISSUE THREAD

**Issue by ab-tools** [0xd4d/dnSpy#571]
I'm using the dnSpy 4.0.0 beta version and looking at a .NET 4.6 assembly.

The assembly has several satellite assembly references that are included as ressources (using Costura). This way I can not easily load these DLLs in dnSpy.

I would now expect that dnSpy shows these DLL assemblies in the "Assembly Explorer" when the program is running in the debugger, but it doesn't.

But if I e. g. add
`System.Reflection.Assembly.Load("SatelliteAssemblyName").GetTypes()`
to the watch window I can easily see all the types, methods and so on of this satellite assembly, so I would expect that it should be also possible for dnSpy to show the content of the assembly.

Therefore the question:
How can I force dnSpy to show an assembly in the assembly explorer that I can access "manually" via `Assembly.Load()` at runtime?

**Comment by SlowLogicBoy** [comment]
It is loaded, open loaded modules window, double click on your assembly and it will load to Assembly Explorer.

**Comment by ab-tools** [comment]
You're absolutely right, really sorry about that - for some reasons I missed it in the "Modules" window.

Thanks a lot for your very quick reply!
