### ISSUE TITLE
What's wrong with me? Debugger error...

### ISSUE THREAD

**Issue by YuqseLx** [0xd4d/dnSpy#572]
https://gyazo.com/ef0c1196cd3b8b568b2e7a782c06c39d

Thank you for check big master. Why i getting this error in Locals window?

**Comment by 0xd4d** [comment]
Could you upload the file here or email it to me? My email is [here](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy/MainApp/StartUpClass.cs#L2)

**Comment by SlowLogicBoy** [comment]
I can reproduce this by using ConfuserEx, with max security (no packer).

**Comment by YuqseLx** [comment]
I sended e-mail. And SlowLogicBoy if you can do that i want to test it another program. Thank you so much.

**Comment by 0xd4d** [comment]
@SlowLogicBoy Is it a decrypted method? The current code doesn't try to re-read the metadata when it gets decrypted.

**Comment by 0xd4d** [comment]
@YuqseLx Try the latest build: https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts

**Comment by YuqseLx** [comment]
@0xd4d, nothing changed. I'm trying debug and BP "0x06000024" address but in locals windows say error - internal debugger error.

**Comment by 0xd4d** [comment]
First of all, get the latest build if you haven't.

Don't set breakpoints in decrypted methods and restart. Always disable those breakpoints before starting again and enable them manually again when everything's been decrypted.

The CLR debugger or the CLR caches the metadata and returns "0 locals".
