### ISSUE TITLE
Display numbers as hexadecimal

### ISSUE THREAD

**Issue by DeltaCR** [0xd4d/dnSpy#574]
Wondering if you can add an option to display int/uint/bytes numbers as hexadecimal
For example
![hex1](https://user-images.githubusercontent.com/17389124/31993277-e9b72c38-b939-11e7-9c95-73ab4c376e5f.png)
Like how you did for the Hex Editor in the new 4.0 update 
BTW the new debugger works amazing thanks so much! Been waiting for the release!
![hex2](https://user-images.githubusercontent.com/17389124/31993423-51a9a3ac-b93a-11e7-9270-497d9e93ecb1.png)

**Comment by 0xd4d** [comment]
Which of the two windows above (text viewer (decompiler output) or IL editor) should have such an option?

**Comment by DeltaCR** [comment]
The decompiler output, in the IL editor I can use hex values but in the output only shows the decimal representation.
If possible the arrays too, because some times is a pain work with large arrays that only shows the bytes in the decimal

**Comment by 0xd4d** [comment]
Decompiler issue.
