### ISSUE TITLE
Adding a reference

### ISSUE THREAD

**Issue by RICKASHEYE** [0xd4d/dnSpy#577]
I got a script in dnSpy and its using System; and using System.Windows.*; it can find everything after System.Windows but not itself also with System they are both or just System is in the assembly explorer

**Comment by 0xd4d** [comment]
You must add a reference using the `#load` directive, see https://github.com/dotnet/roslyn/wiki/Interactive-Window

**Comment by 0xd4d** [comment]
EDIT: It's the `#r` directive
