### ISSUE TITLE
Why does the solution format auto?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#578]
Visual Studio will place "{" in the new line by default, and I don't change the setting.
When I download the repository "dnlib", and write my code, "{" will place in new line.
But when I download the repository "dnSpy", and write my code, "{" will place in the same line.
So I want to know, why my visual studio setting is invalid this time? Is there any setting in the solution/project file to control this?

**Comment by 0xd4d** [comment]
http://editorconfig.org/
