### ISSUE TITLE
Breaking on  <Module>.cctor

### ISSUE THREAD

**Issue by InlineAsm** [0xd4d/dnSpy#579]
Hi, I was testing your new version and I noticed there is no longer an option to break on the <Module>.cctor. Is there a reason why this is removed?

Another similar question is if it would be possible to define a default value for the Break at combobox. Right now the new version defaults to 'Don't break' but in my case the common case would be to break at the entry point.

Thanks for the great debugger. It has helped me many times.

**Comment by 0xd4d** [comment]
You can set a BP @ the cctor.

The option isn't included because I thought it wasn't used very often and the workaround with the BP was enough.

If you press F10 it will automatically select "entry point" and if you press F5 it won't stop at all.

**Comment by InlineAsm** [comment]
Okay, I guess that's more in line with how visual studio works. I'd still prefer to break on a module cctor when entrypoint is selected because that's where the meat is when you're reversing obfuscated files but if it's otherwise not much used I'll go with the manual breakpoint. Thanks!

**Comment by uragan1987** [comment]
it will be nice to get it back
