### ISSUE TITLE
how to add plugins

### ISSUE THREAD

**Issue by xy9144** [0xd4d/dnSpy#58]
Though dnspy  forked from ilspy，it is very hard for a beginner to add plugins under the condition of got enough useful information 。It is suggested that  master should share some experience ，and if it is convinent 。

**Comment by 0xd4d** [comment]
I'll add a wiki entry in about a month or so on what you need to do. Most interesting stuff already is a plugin: Baml decompiler by Ki, Debugger and AsmEditor, although the last two aren't separate assemblies, they will be later. The plugin code will be rewritten so if you write code now be prepared to update it later.

**Comment by 0xd4d** [comment]
If you want to add a context menu or main menu item, see eg. https://github.com/0xd4d/dnSpy/blob/master/dnSpy/AsmEditor/Hex/ContextMenuCommands.cs

You must add a ExportContextMenuEntry or  a ExportMainMenuCommand attribute to a class.

**Comment by xy9144** [comment]
Sorry , “under the condition of got enough useful information.” is not exact,and it should be  “under the condition of having not got enough useful information.”I mean to give a starving beggar a loaf of bread is much better than give a gold coin.Take the simplest  “test. plugin.dll” as example, if there is no detailed information, a beginner don't know how to add. Where is actually useful information is where to insert the code,which  to insert,how to insert. It will be good ,If there is a detailed example.

**Comment by UlyssesWu** [comment]
just a reply for @xy9144 ： 0xd4d巨巨已经表示会在一个月左右之后在wiki写教程展示怎么搞插件了。你的最后一段话想表达什么我都看不明白，唯一能看明白的是你肯定是国人吧（除了语法问题之外，你还使用了汉语标点 LOL）。

**Comment by xy9144** [comment]
@UlyssesWu 一楼是昨晚用手机写的，所以没注意标点问题。我想说的意思是：对新手（饥饿垂死的乞丐）不要讲高深的东西（金币），不如给个简单直观的实例（面包），因为新手没实例很难理解那些高深的知识。真正有用的给个详细的例子是告诉新手该在哪里加插件，该用那些代码，和怎么做的。
现在没问题了，关闭话题。
