### ISSUE TITLE
Failing to recompile unchanged decompiled code

### ISSUE THREAD

**Issue by e00E** [0xd4d/dnSpy#580]
Here are some simplified seemingly related examples I encountered:
```c#
this.<localData>__1 = foobar();
this.<onlineData>__2 = foobar();
foobar(this.<localData>__1);
this.<>f__this.foo = bar;
```
I am not sure what this syntax means but the identifier in the `<>` seems undeclared.
Error message for the first three examples was `CS1001 Identifier expected` and for the last one `CS1525 Invalid expression term = '>'`.
This happened with the current release.

**Comment by e00E** [comment]
Also happens on master.

**Comment by 0xd4d** [comment]
Is it a unity assembly? You have to fix this manually, I don't plan on fixing any decompiler v2 bugs.

**Comment by e00E** [comment]
It is a Unity game, yes.
If you don't mind, could elaborate what you mean with decompiler **v2**? Also could you explain what is going wrong here so I understand how to fix it manually? Are things like `localData` actually local variables? What is the decompiler trying to tell me by putting them in the `this.<...>` form?
