### ISSUE TITLE
Allow modifying Enum values

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [0xd4d/dnSpy#581]
I'm reversing a binary that is obfuscated by Eazfuscator 5.8. Eazfuscator (and a bunch of other obfuscators) remove all values from enums so the code using them will look like this:

    SomeEnum e = (SomeEnum)1;

As far as I could find, there is no way to modify the enum's values to give them sensible names. Ideally, I would be able to edit a list of values and enter my own names (similar to the Generic Parameters, Interfaces, Custom Attrs, ... tabs in Edit Type) and change the Enum from this:

    private enum SomeEnum
    {
    }

To this:

    private enum SomeEnum
    {
        None, //0
        Value1 //1
        //...
    }

This would make the code mentioned first look like this:

       SomeEnum e = SomeEnum.Value1;

**Comment by HoLLy-HaCKeR** [comment]
I'd also like to note that I cannot use the C# editor because this enum is in an obfuscated class which cannot be recompiled due to names being high or low unicode (eg. \u0002).

**Comment by 0xd4d** [comment]
Related to #165

The C#/VB compilers has to parse the code and can't always parse decompiled code unless it's been deobfuscated (renamed). In theory dnSpy could rename everything in memory, write new temporary assemblies and pass them to the compilers but that would take too long a time.

You can still add new fields to types if you right click the type and click "Create Field". I just created this enum from scratch and added three fields (the `value__` field isn't shown):

```C#
using System;

namespace dnSpy.MainApp
{
	// Token: 0x02000C1B RID: 3099
	public enum MyEnum
	{
		// Token: 0x04002307 RID: 8967
		MyField = 123,
		// Token: 0x04002308 RID: 8968
		MyField = 456
	}
}
```

If you haven't created the `value__` field, dnSpy will use that name and initialize the attributes accordingly. If it's already present, dnSpy will set Static, Literal and check the Constant checkbox, you just need to rename the field and initialize the constant.

**Comment by HoLLy-HaCKeR** [comment]
Ah, I wasn't aware that Enum members actually are fields, that works. Thanks!
