### ISSUE TITLE
CLI Export to Project

### ISSUE THREAD

**Issue by atillabyte** [0xd4d/dnSpy#583]
I think it'd be useful to have a command-line option for temporarily loading a module and then exporting the decompiled project to a given directory.

JustDecompile used to have something relatively similar to this apparently. ([cit](http://blog.jongallant.com/2011/11/decompile-dll-using-c/))

**Comment by 0xd4d** [comment]
I assume you mean a command line option for dnSpy.exe/dnSpy-x86.exe. A workaround at the moment is to use dnSpy.Console.exe.

**Comment by 0xd4d** [comment]
Use `dnSpy.Console.exe`.

**Comment by ttodua** [comment]
`dnSpy.Console.exe -o c:\file.dll c:\out_dir`
