### ISSUE TITLE
[Flags]

### ISSUE THREAD

**Issue by DC4-SERGEY** [0xd4d/dnSpy#585]
Good day - tell me how to mark enum as [Flags]?

![image](https://user-images.githubusercontent.com/32691168/32167365-b98ebb04-bd79-11e7-9af1-93d26a8c8c23.png)
bitwise operation on enum which is not marked by [Flags] attribute

![image](https://user-images.githubusercontent.com/32691168/32167389-c6b266aa-bd79-11e7-88d8-388afc7ef985.png)

**Comment by HoLLy-HaCKeR** [comment]
`Edit Type -> Custom Attributes -> Add -> Triple dots at top left -> mscorlib.dll -> System -> FlagsAttribute -> .ctor`

**Comment by 0xd4d** [comment]
You can also edit the class and add the `[Flags]` attribute.
