### ISSUE TITLE
Assemblies automatically populating

### ISSUE THREAD

**Issue by keenkrozzy** [0xd4d/dnSpy#586]
OK, I am not knowledgeable enough to explain this correctly, so I will review what is happening step-by-step.

1. I remove the assemblies that I am not interested in from the assembly browser.
![image](https://user-images.githubusercontent.com/16310971/32197476-d365036e-bd9a-11e7-87ea-745da18571e3.png)

2. I now have the two assemblies that I want to reference.
![image](https://user-images.githubusercontent.com/16310971/32197678-9000618a-bd9b-11e7-9683-aa1c55672440.png)

3. Everything that I view seems to automatically pull in any assemblies that are being used. This adds endless clutter to using the search tool.
![image](https://user-images.githubusercontent.com/16310971/32197937-8627b158-bd9c-11e7-945a-5a31b24cc962.png)

![image](https://user-images.githubusercontent.com/16310971/32197993-b9937f86-bd9c-11e7-970d-03ebdc918d6c.png)

So my question is: Is there a way to disable this behavior?

**Comment by keenkrozzy** [comment]
I now realise that I can change the Search Scope to "Selected Files", but my question still stands.

**Comment by 0xd4d** [comment]
The assemblies are referenced by at least one assembly and get added again because the dnSpy needed to read their metadata. There's no option to disable resolving assemblies.

**Comment by keenkrozzy** [comment]
Is there a way to keep assemblies "hidden"?

**Comment by 0xd4d** [comment]
No there's no such option at the moment.

**Comment by keenkrozzy** [comment]
Thank you for your time.
