### ISSUE TITLE
Loaded Module Tab

### ISSUE THREAD

**Issue by cawk** [0xd4d/dnSpy#587]
Where has the option gone to see the modules loaded in memory?

i only have these

https://gyazo.com/ac8340d898d812bdbc5ecae25f5780d6

and i have looked through the options and cant seem to spot it im probably just blind :D 

regards

**Comment by 0xd4d** [comment]
You probably haven't started debugging yet. :)

**Comment by cawk** [comment]
Even when debugging the tab doesnt appear

https://gyazo.com/3d9ee05a6d7af5fbad75ea1646621a34

as you can see by the orange strip im debugging but i still dont see it?

im using latest beta release

**Comment by cawk** [comment]
wait ive found it 

thank you
