### ISSUE TITLE
An error when decompile baml

### ISSUE THREAD

**Issue by YuqseLx** [0xd4d/dnSpy#59]
Hey thanks for tools of yours. I'm getting this error when i select .baml resource thank you
![error](https://cloud.githubusercontent.com/assets/5947161/11454799/d056a08a-9644-11e5-9342-ac17497ae7f2.jpg)
this resource showing under reflector v9
![error](https://cloud.githubusercontent.com/assets/5947161/11454804/e43f1578-9644-11e5-8f4a-b2aba9cf7988.jpg)

**Comment by 0xd4d** [comment]
Email me the program and I'll have a look: de4dot@gmail.com

**Comment by YuqseLx** [comment]
Sended thank you

**Comment by thinkv** [comment]
I want to jump in here and ask, how to view BAML in general? When I select a BAML resource it simply shows the size??

**Comment by 0xd4d** [comment]
You must use the latest version. Grab the one from the build server.

**Comment by thinkv** [comment]
That's the one I just downloaded to try with :0

**Comment by 0xd4d** [comment]
View -> Options: do you see a BAML tab? If not, the plugin isn't loaded. Make sure it's in the same folder as dnSpy.exe.

**Comment by thinkv** [comment]
Ah it's working now, thank you, is there any view on modifying the BAML in
the pipeline?
