### ISSUE TITLE
"Edit Method (Visual Basic)" doesn't work in modules

### ISSUE THREAD

**Issue by TymurGubayev** [0xd4d/dnSpy#592]
When trying to edit a single method of a module via "Edit Method (Visual Basic)", compile doesn't work even if no changes are made, due to Error `BC30179 module 'CommonRoutines' and class 'CommonRoutines' conflict in namespace 'myNameSpace'.`

Also, if there are extension methods in the module, Error `BC36551	Extension methods can be defined only in modules.` happens. This is also true for C#-recompiling, with Error `CS1106	Extension method must be defined in a non-generic static class`.

**Comment by 0xd4d** [comment]
Decompiler issue
