### ISSUE TITLE
Why is .editorconfig unuseful when git the source?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#593]
If I download dnSpy by "Clone or download"-"Download ZIP", when I write code, "{" will place in the same line.

If I clone "https://github.com/icsharpcode/ILSpy.git" by Visual Studio 2017, when I write code, "{" will place in the new line.

Why?

**Comment by 0xd4d** [comment]
Dupe of  #578, and off topic.

**Comment by 0xd4d** [comment]
VS has its own forum.
