### ISSUE TITLE
Breakpoint on .dll (The breakpoint will not currently be hit.)

### ISSUE THREAD

**Issue by kevinvdburgt** [0xd4d/dnSpy#594]
I am trying to set breakpoints inside .dll files. However, when i start the debugger and chose the .exe file that depends on the .dll i got the following message inside dnSpy:

`The breakpoint will not currently be hit. The module hasn't been loaded or no symbols have been loaded for this module.`

**Comment by gagmeng** [comment]
May be there are some same name dll is registered in GAC.

**Comment by 0xd4d** [comment]
You've probably set the breakpoint in the wrong file. If you open the Modules window, you can double click the module and go to the method and set a BP in it. It could be a file in the GAC, as @gagmeng already mentioned.
