### ISSUE TITLE
Dubious disassembly:@switch(ICSharpCode.Decompiler.ILAst.ILLabel[], num);

### ISSUE THREAD

**Issue by FickoDeLux** [0xd4d/dnSpy#595]
I have a complex methode dnspy fails to disassemble correctly.

Getting something like:
[ICSharpCode.Decompiler.ILAst.zip](https://github.com/0xd4d/dnSpy/files/1443266/ICSharpCode.Decompiler.ILAst.zip)

> _@switch(ICSharpCode.Decompiler.ILAst.ILLabel[], num);_

Attaching the disassembly & IL.

**Comment by 0xd4d** [comment]
That's some ugly code. Try running a deobfuscator on it first. The decompiler can't handle weird code. This is a won't fix.

**Comment by manojdjoshi** [comment]
https://github.com/icsharpcode/ILSpy/issues/1097
