### ISSUE TITLE
Single step when instantiating class without constructor

### ISSUE THREAD

**Issue by DonKonfetti** [0xd4d/dnSpy#598]
I've got a class without constructor (= compiler generated default constructor). When doing single step at the line `new MyClass().RunAwesomeMethod();`, dnySpy switches to MyClass source with cursor at the upper left corner. No source code line is highlighted as there's no constructor source code. Clicking the single step button or hitting F11 has no effect. I have to hit Shift-F11 to return to the caller. Hitting again F11, I land at RunAwesomeMethod() as expected.

I'd expect dnSpy to directly jump to RunAwesomeMethod() in case just the compiler generated default constructor is present.

**Comment by 0xd4d** [comment]
Should already be fixed https://github.com/0xd4d/dnSpy/blob/master/Extensions/dnSpy.Debugger/dnSpy.Debugger.DotNet.CorDebug/Steppers/DbgEngineStepperImpl.cs#L143
