### ISSUE TITLE
Decompilation trouble

### ISSUE THREAD

**Issue by Alcatraz3222** [0xd4d/dnSpy#6]
i have this issue when trying to decompile a program through dnSpy

http://i.imgur.com/s1cEWiD.png

**Comment by 0xd4d** [comment]
Could you copy the stack trace? I can only see the method name not the actual line.

**Comment by Alcatraz3222** [comment]
ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Void ns4.Form0::method_1(System.Object,System.EventArgs)
 ---> System.InvalidOperationException: Operación no válida dado el estado actual del objeto.


 en ICSharpCode.Decompiler.ILAst.ILAstOptimizer.HandlePointerArithmetic(ILNode method) en k:\Computer\Reversing\Disassemblers\NET\dnSpy-1.0.0.0\dnSpy-1.0.0.0\GIT\dnSpy\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:línea 716


 en ICSharpCode.Decompiler.ILAst.ILAstOptimizer.Optimize(DecompilerContext context, ILBlock method, ILAstOptimizationStep abortBeforeStep) en k:\Computer\Reversing\Disassemblers\NET\dnSpy-1.0.0.0\dnSpy-1.0.0.0\GIT\dnSpy\ICSharpCode.Decompiler\ILAst\ILAstOptimizer.cs:línea 129


 en ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(IEnumerable`1 parameters, MemberMapping& mm) en k:\Computer\Reversing\Disassemblers\NET\dnSpy-1.0.0.0\dnSpy-1.0.0.0\GIT\dnSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:línea 98


 en ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, IEnumerable`1 parameters, MemberMapping& mm) en k:\Computer\Reversing\Disassemblers\NET\dnSpy-1.0.0.0\dnSpy-1.0.0.0\GIT\dnSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:línea 72

 --- Fin del seguimiento de la pila de la excepción interna ---

 en ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.CreateMethodBody(MethodDef methodDef, DecompilerContext context, IEnumerable`1 parameters, MemberMapping& mm) en k:\Computer\Reversing\Disassemblers\NET\dnSpy-1.0.0.0\dnSpy-1.0.0.0\GIT\dnSpy\ICSharpCode.Decompiler\Ast\AstMethodBodyBuilder.cs:línea 76


 en ICSharpCode.Decompiler.Ast.AstBuilder.CreateMethodBody(MethodDef method, IEnumerable`1 parameters, MemberMapping& mm) en k:\Computer\Reversing\Disassemblers\NET\dnSpy-1.0.0.0\dnSpy-1.0.0.0\GIT\dnSpy\ICSharpCode.Decompiler\Ast\AstBuilder.cs:línea 1104

**Comment by 0xd4d** [comment]
Could you email me the file and I'll have a look at it: de4dot@gmail.com  Send the exact same file (I assume it's the deobfuscated file).
