### ISSUE TITLE
Bookmarks feature request

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#60]
Consider adding bookmakrs support (over methods/members/etc)
having an assembly with 1000+ of items it's a PITA to navigate to desired point again & again...
I like the way as SAE doing bookmarks..... but feel free to make it as you see it...
Of course created bookmakrs should be persisted between runs and easily to navigate after restart..

Thanks

**Comment by 0xd4d** [comment]
Will be added. In the meantime, you can use disabled breakpoints as a poor man's bookmark.

**Comment by galaris** [comment]
+1
