### ISSUE TITLE
Variables with same name, but different type - is it normal behavior?

### ISSUE THREAD

**Issue by Misiu** [0xd4d/dnSpy#600]
While trying to debug dll that throws me an error I've noticed weird thing.
When opened in dnSpy (4.0.0 beta3) I saw variables with same name but different type:
![snap 2017-11-08 at 10 24 17](https://user-images.githubusercontent.com/1741838/32541124-fdda34c2-c46e-11e7-8f71-1ef7c0f2578f.png)

and inside method:
![snap 2017-11-08 at 10 26 31](https://user-images.githubusercontent.com/1741838/32541414-eba7c002-c46f-11e7-82df-f54ec5069e5c.png)

as You can see string is assigned to variable `d` then integer is assigned to same variable (variable with same name).

because of that I'm unable to do any edits to any methods, because I get this error:
The type 'Encoder' already contains a definition for 'a'.

I'm aware I can right click on variable in assembly explorer and use `Edit Field` option (thank You for that 🏆 ), but I'd like to know is it normal behavior?
Normally we aren't allowed to declare variables with same name and different type.

**Comment by 0xd4d** [comment]
It's been obfuscated, try `de4dot` first.

**Comment by Misiu** [comment]
@0xd4d already did that. I've check in other tools (dotPeek, JustDecompile) and got same result.
I managed to rename symbols using `Edit Field` option, but it looked weird at first.
It might be some kind of protection, but for me it's weird it is working.

**Comment by 0xd4d** [comment]
You can use de4dot with certain command line options to rename only names matching a regex. That should fix your problem.

**Comment by Misiu** [comment]
@0xd4d I didn't knew this was possible with de4dot. Thanks for hint! I must check that right away 😄

**Comment by 0xd4d** [comment]
See doc here: https://github.com/0xd4d/de4dot#using-a-different-rename-regex
