### ISSUE TITLE
Cannot implictly convert type <class> main.cs to <class> assembly-csharp.dll

### ISSUE THREAD

**Issue by PiotrKFtw** [0xd4d/dnSpy#602]
![screenshot_42](https://user-images.githubusercontent.com/33489788/32554909-9712d816-c49b-11e7-9ad7-50aab92064b7.png)

Editing method body everytime to modify this method.. If you can fix it then.

**Comment by 0xd4d** [comment]
This is a dupe of a few existing issues.
