### ISSUE TITLE
After reset win10 can't open dnSpy

### ISSUE THREAD

**Issue by YuqseLx** [0xd4d/dnSpy#604]
https://image.prntscr.com/image/kcgyOVthRLyZqbH5l-sVHw.png

i do only reset windows 10 why it's happening? I download lastest build ( v4.0.0 not beta ) 
Thank you.

**Comment by HoLLy-HaCKeR** [comment]
Can you translate the error message on the first line of the stack trace? That would be helpful for trying to fix this, or help you fix it.

**Comment by 0xd4d** [comment]
Delete/rename these folders, replace `XXX` with your user name:

- C:\Users\XXX\AppData\Local\dnSpy
- C:\Users\XXX\AppData\Roaming\dnSpy

And redownload v4.0.0 and extract the files to a NEW folder (don't overwrite an existing folder)

**Comment by YuqseLx** [comment]
@HoLLy-HaCKeR, thanks for reply doesn't matter problem is solved.
@0xd4d, deleted Local/dnSpy and download again extract Desktop and problem is solved. Why it was heppened? I want copy it in D disk not C :/

**Comment by 0xd4d** [comment]
You should be able to run it from C: or D: or any other letter. ;)

**Comment by YuqseLx** [comment]
Thank you i mark it solved and close :)
