### ISSUE TITLE
How To Use dnspy programatically?

### ISSUE THREAD

**Issue by iamwyza** [0xd4d/dnSpy#605]
I'm wondering if, using the new scripting interface, we can do automated code changes.  What I am attempting to do is open an assembly, edit a given method, add some c#, then compile and save the resulting module.  

Ideally I'd do all this is pure c#.net, but after poking around in the dnspy code for the last couple days, I'm pretty sure there is far too much going on to do it directly.  So I'm hoping it can be scripted now with the new API stuff.  Thoughts?

**Comment by SlowLogicBoy** [comment]
Assembly modifications are done using [dnlib](https://github.com/0xd4d/dnlib) at least IL code ones.

**Comment by iamwyza** [comment]
Yeah, But you can right click a method, click "Edit Method" and you're presented with a csharp representation of the method which you can edit and hit "Compile".  What I want to do is try to automate those actions.

**Comment by 0xd4d** [comment]
The assembly editor has no public API at the moment.

**Comment by iamwyza** [comment]
Just something as simple as being able to open it, modify the body, and compile is all I'd really need.  Obviously there is a bunch of other stuff in the editor, but just the basics would be enough to start.
