### ISSUE TITLE
XAML Name property is missing namespace 'x'

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#606]
If the class is defined in the same assembly, must use "x:Name" instead of "Name"

Maybe you can allways use x:Name?

**Comment by 0xd4d** [comment]
I need more info, how do I reproduce this? What does the bad XAML look like and what should it look like?

**Comment by CreateAndInject** [comment]
Create a WPF project "WpfTest"
MainWindow.xaml:
```
<Window x:Class="WpfTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfTest"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="525">
    <Grid>
        <local:MyButton x:Name="btn"/>
    </Grid>
</Window>
```
MainWindow.xaml.cs:
```
using System.Windows;
using System.Windows.Controls;

namespace WpfTest
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }
    }
    public class MyButton : Button
    {
    }
}
```

dnSpy will decompile xaml as:
```
<local:MyButton Name="btn"/>
```
Build it with Visual Studio:
Error		Because 'MyButton' is implemented in the same assembly, you must set the x:Name attribute rather than the Name attribute. Line 8 Position 4.	WpfTest

**Comment by CreateAndInject** [comment]
Why close it without fixing?

**Comment by 0xd4d** [comment]
Because it's not something I plan on fixing and no-one else seems to care about it. If it's a problem for you, fix it and send a PR.
