### ISSUE TITLE
WordWrap

### ISSUE THREAD

**Issue by nonspin** [0xd4d/dnSpy#61]
dnSpy version 1.5.0.0

I guess the title gives it away, WordWrap is not wrapping text anymore.
Look into it please. TIA

**Comment by 0xd4d** [comment]
You probably enabled that new option right? Word wrapping isn't support if it's enabled, see https://github.com/0xd4d/dnSpy/releases/tag/v1.5.0.0

**Comment by nonspin** [comment]
Should've read the description first i guess. 
The main reason why i issued it, was the fact that the WordWrap toggle itself still
removed the scrollbars.
It is kinda misleading if you don't know what's what. 
Therefore, if the new setting is active, wouldn't it make sense to also disable to toggle in View menu?

Thanks, and really nice job ;D
