### ISSUE TITLE
Prevent dnSpy from detecting code errors?

### ISSUE THREAD

**Issue by ZexDex85127854** [0xd4d/dnSpy#612]
Is there a way to prevent dnSpy from detecting code errors and just make dnSpy compile the modified instruction with the errors?

What I do with dnSpy is make mods for games but sometimes I cant because after editing a instruction for example
`		public float CurrHP
		{
			get
			{
				if (this.Team is PlayerTeamManager)
				{ 
					this.Model.Hp.Value = 999999f; 
				}
				return this.Model.Hp.Value;
			}
		}`
and then click "compile" I get a bunch of errors which aren't related to my peace of code but to other parts of the code in the file/class. Is there a way to disable this and just force dnSpy to compile my stuff and all the game developers errors to go with it? I know that if I write my code using the IL editor then I wont get the errors but I have no idea how my code would look in IL.

**Comment by 0xd4d** [comment]
No, the compiler can't do that. You can however choose `Edit Method` instead of `Edit Class` since there should be less things that could go wrong. If there are compilation errors you can always try to remove the errors in `main.g.cs`, very often that will allow the compiler to compile it.

**Comment by ttodua** [comment]
would have been nice if that was possible : /
btw, what/where is `main.g.cs` ?
