### ISSUE TITLE
I want "LoadDll.exe" such as Ollydbg

### ISSUE THREAD

**Issue by diamond94618** [0xd4d/dnSpy#613]
This isn't issue of dnSpy. 
But I don't know where should I post this article. If it's trouble for you **0xd4d**, then very sorry.
What I wanna say is about the "**LoadDll.exe**" for .net dll debugging.
**Ollydbg** has "**loaddll.exe**" for dll debugging.
In my opinion, if **dnSpy** has also "**LoadDll.exe**" for .net dll debugging, then dnSpy will be more perfect than now.
Currently I made an "**loaddll.exe**" by myself, but It doesn't run successfully with some exceptions.
So I hope from the bottom of my heart that **dnSpy** will has "**loaddll.exe**"!!!
Thanks.
From a beginner

**Comment by HoLLy-HaCKeR** [comment]
Can't you just create a little application that will call the functions from your DLL?

**Comment by diamond94618** [comment]
I had try several times using several methods. Not packed dll can be loaded successfully, but packed files occurs exception.
And even if the dll is loaded without errors, but the breakpoint doesn't work in a dll. I can't know why is it..
Can you give me right source Code for my purpose?

**Comment by HoLLy-HaCKeR** [comment]
If your DLL you're inspecting is packed, use the dnSpy debugger to step into the module after it is unpacked and then put your breakpoints. If you can place breakpoints at all, your assembly may be obfuscated too much, so try running it through de4dot first then.

**Comment by 0xd4d** [comment]
It's not something I plan on adding, it has limited use and is very easy to write yourself.

About BPs and decrypted modules: https://github.com/0xd4d/dnSpy/issues/572#issuecomment-339510779
