### ISSUE TITLE
Extracting method call information [question]

### ISSUE THREAD

**Issue by Bert-Proesmans** [0xd4d/dnSpy#615]
Hi,

My intention is to extract parameter information from every call to a specified method within a certain assembly.
The process would roughly consist of the following steps:
1. Locate all calls to the specified method
2. For each found call location, detect used parameters
3. Dump collected information about these parameters

If i code this out by hand naively i would have to simulate each entire method body from start until i reach the call (target method) statement while processing the stack. 
Is there code within dnSpy which could do the heavy lifting for me and i'll (only) need to write an extension. I looked into the extension examples and there doesn't seem to be a component which interacts with the syntax tree or any other representation of .net code, but the dnSpy.Analyzer extension might be useful (on first look).

Should i instead interact with ilspy directly, or even Roslyn?
Any pointers would be appreciated, thank you in advance.

Bert

**Comment by 0xd4d** [comment]
I would decompile it to a project and then use Roslyn to analyze it, hoping that the decompiled code can be read by Roslyn without it throwing exceptions.

**Comment by Bert-Proesmans** [comment]
Thank you for the advice.
