### ISSUE TITLE
c__DisplayClass unknown token

### ISSUE THREAD

**Issue by vanderstack** [0xd4d/dnSpy#616]
In an assembly I am working with and do not have the source for I am seeing the following:

![image](https://user-images.githubusercontent.com/24641067/32750610-6a3fd13e-c880-11e7-8a53-43159cd4043c.png)

I believe c__DisplayClass is supposed to be translated into a nested class declaration, but that is not what I am seeing. When I click c__DisplayClass I am taken to the top of the file, and there is no declaration for it.

Can anyone clarify the functionality here, I expected to see a class declaration, the code here is not compilable?

**Comment by UlyssesWu** [comment]
Enable "Show compiler generated types" in Setting - Decompiler may solve your problem.

BTW, I don't think it's a good idea to ask the authors for implementation details for a _closed-source_ project (in the picture). Maybe you should work on your own or wait for its open-source.

**Comment by orbittwz** [comment]
Hello!
The issue still present in version 6.0.5...
FYI
