### ISSUE TITLE
circular base class dependency

### ISSUE THREAD

**Issue by mrexodia** [0xd4d/dnSpy#617]
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Test
{
    class Foo
    {

    }
}

namespace Inheritance
{
    class Foo : Test.Foo
    {

    }

    class Program
    {
        static void Main(string[] args)
        {
        }
    }
}
```

This code will decompile to:

```
using System;
using Test;

namespace Inheritance
{
	// Token: 0x02000002 RID: 2
	internal class Foo : Foo
	{
	}
}
```

Which will cause an error when trying to edit the class:

```
Severity	Code	Description	File	Line
Error	CS0146	Circular base class dependency involving 'Foo' and 'Foo'	main.cs	7
```

**Comment by 0xd4d** [comment]
It's a decompiler bug, the easiest workaround is to just add the namespace yourself.

**Comment by mrexodia** [comment]
What was happening recently with the repository being readonly?

**Comment by 0xd4d** [comment]
I set it to read-only because I didn't plan on updating it for a while and didn't want to get any more issues (you can't set it to read-only, just enable/disable it)

**Comment by mrexodia** [comment]
Alright! I asked because some weird gossip has been going around that the repository was compromised or something (https://pastebin.com/1dvUw4uA)...

**Comment by 0xd4d** [comment]
No, don't trust everything you read on the Internet. Some people are too paranoid.

**Comment by 0xd4d** [comment]
> All previous releases have been removed, and the repository is currently archived on GitHub.

I've never kept old releases. It's open source and free, just use the latest version.
