### ISSUE TITLE
Why doesn't load mscorlib v1.1 even if I have .net 1.1 installed?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#618]
If I explore an assembly based on .net 1.1, dnSpy will load all its dependency assembly, e.g System, System.Windows.Forms except mscorlib, why?

**Comment by 0xd4d** [comment]
I haven't tested it with .NET 1.x assemblies (or Silverlight :) ) because almost no-one uses .NET 1.x anymore. The debugger doesn't support .NET 1.x either because the CorDebug 1.x API was a little buggy.
