### ISSUE TITLE
Syntax Errors

### ISSUE THREAD

**Issue by Kerbs10** [0xd4d/dnSpy#619]
I got lots of syntax errors like this one:
static T GetValue<T>(ISettingsSection section, string name, ref bool failed) where T : struct {
			var v = section.Attribute<T?>(name);
			if (v == null) {
				failed = true;
				return default; //error here
			}
			return v.Value;
		}

And **Visual Studio 2017** says that it should be:
return default(T);

**Comment by 0xd4d** [comment]
Did you read the wiki? https://github.com/0xd4d/dnSpy/wiki/Building-dnSpy
