### ISSUE TITLE
dnSpy always crashed

### ISSUE THREAD

**Issue by CodeShark-Dev** [0xd4d/dnSpy#62]
When i select a type it show this message and i need finalize the process

http://i.imgur.com/Cjt8ZZV.png

**Comment by 0xd4d** [comment]
Have you tried the latest build: https://ci.appveyor.com/project/0xd4d/dnspy/build/artifacts

**Comment by 0xd4d** [comment]
I've updated some code, please try the latest build (again).

**Comment by CodeShark-Dev** [comment]
Fixed! Thanks :+1:
