### ISSUE TITLE
Show enum value

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#620]
If you click on a specific enum the decompiler shows the value for example:

`public const SomeEnum.Blabla whatever = 123;`

but if you click on the enum itself it hides the value in this example:

```
public enum Blabla
{
 none,
 whatever
}
```

But I would appeciate if it also shows the value there like this:

```
public enum Blabla
{
 none = 0,
 whatever = 123
}
```

Red Gate reflector does this and it's very useful to get an overview about enum values without clicking at each value itself.

**Comment by 0xd4d** [comment]
Should be fixed in the decompiler.

**Comment by chucklu** [comment]
@0xd4d  I am using version 6.0.5 and the enum value not shown when I go to the emum definition.

**Comment by Symbai** [comment]
@chucklu Same
