### ISSUE TITLE
Doesn't decompile auto property of VB.Net correctly.

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#623]
If unchecked "Show hidden compiler generated types and methods" 
C# auto property will show as:
`public string Text { get; set; }`
VB.Net auto property will show as:
```
public string Text
{
	[DebuggerNonUserCode]
	get
	{
		return this._Text;
	}
	[DebuggerNonUserCode]
	set
	{
		this._Text = value;
	}
}
```
But the filed "_Text" is hidden, so it should show as:
`public string Text { get; set; }`

**Comment by CreateAndInject** [comment]
BTW, ths option "Show hidden compiler generated types and ```methods```"
should be named as "Show hidden compiler generated types and ```members```"

**Comment by GSPP** [comment]
I just noticed this. Is this feature request declined?

**Comment by 0xd4d** [comment]
@GSPP Seems to be working

```VB
Module Module1

    Sub Main()

    End Sub

End Module

Class SomeClass
    Public Property Name As String
    Public Property Owner As String = "DefaultName"
    Public Property Items As New List(Of String) From {"M", "T", "W"}
    Public Property ID As New Guid()

    Public ReadOnly Property Tags As New List(Of String)
    Public ReadOnly Property Name2 As String = ""
    Public ReadOnly Property File As String
End Class
```

Decompiles to

```C#
using System;
using System.Collections.Generic;

namespace ConsoleApp2
{
	class SomeClass
	{
		public SomeClass()
		{
			this.Owner = "DefaultName";
			this.Items = new List<string>
			{
				"M",
				"T",
				"W"
			};
			this.ID = default(Guid);
			this._Tags = new List<string>();
			this._Name2 = "";
		}

		public string Name { get; set; }

		public string Owner { get; set; }

		public List<string> Items { get; set; }

		public Guid ID { get; set; }

		public List<string> Tags { get; }

		public string Name2 { get; }

		public string File { get; }
	}
}
```

and

```VB
Imports System
Imports System.Collections.Generic

Namespace ConsoleApp2
	Friend Class SomeClass
		Public Sub New()
			Me.Owner = "DefaultName"
			Me.Items = New List(Of String)() From { "M", "T", "W" }
			Me.ID = Nothing
			Me._Tags = New List(Of String)()
			Me._Name2 = ""
		End Sub

		Public Property Name As String

		Public Property Owner As String

		Public Property Items As List(Of String)

		Public Property ID As Guid

		Public ReadOnly Property Tags As List(Of String)

		Public ReadOnly Property Name2 As String

		Public ReadOnly Property File As String
	End Class
End Namespace
```

**Comment by GSPP** [comment]
I'm seeing this with NBitcoin:

![image](https://user-images.githubusercontent.com/12032350/61576351-7d666b00-aad9-11e9-8554-669e320e1270.png)

If you cannot reproduce this I can look into it.

**Comment by 0xd4d** [comment]
That looks like a C# auto property. Make sure you didn't enable 'show all types and members' option.

**Comment by GSPP** [comment]
I did enable that option in order to see local functions. It should be possible to see local functions (at all, and preferably decompiled inline into the parent function) while at the same time seeing auto properties in their original form.

**Comment by 0xd4d** [comment]
I pushed a hack fix that will show local functions assuming they're not in a display class, i.e., if they're just methods in the original class they will be shown. That should be enough until https://github.com/0xd4d/dnSpy/issues/936 is fixed.
