### ISSUE TITLE
switch decompilation

### ISSUE THREAD

**Issue by manojdjoshi** [0xd4d/dnSpy#624]
Latest build of dnSpy (dnSpy (4.0.0.0)) has some issues with switch decompilation

> Throw ProjectData.CreateProjectError(-2146828268)
		IL_650:
		GoTo IL_65B
		IL_652:
		GoTo IL_7FC
		IL_65B:
		Dim num23 As Integer = num22 + 1
		num22 = 0
		switch(ICSharpCode.Decompiler.ILAst.ILLabel[], num23)
		IL_7AB:
		GoTo IL_7F1
		IL_7AD:
		num22 = num2
		switch(ICSharpCode.Decompiler.ILAst.ILLabel[], If((num > -2), num, 1))
		IL_7CD:
	Catch obj2 When endfilter(TypeOf obj Is Exception And num <> 0 And num22 = 0)
		Dim ex As Exception = CType(obj2, Exception)
		GoTo IL_7AD
	End Try
	IL_7F1:
	Throw ProjectData.CreateProjectError(-2146828237)
	IL_7FC:
	If num22 <> 0 Then
		ProjectData.ClearProjectError()
	End If

**Comment by manojdjoshi** [comment]
**Spices.Net decompile** 
>               Throw ProjectData.CreateProjectError(-2146828268)
            End If
          Case Else
          ILO_0b9a:
            v_i1 = v_i2
            Select IIf(v_i > -2, v_i, 1)
              Case 0
                goto ILO_0bba

              Case 1
                goto ILO_0a44

              Case 2
                goto ILO_09f4
              Case Else
              ILO_0bba:
            End Select
        End Select
      Catch v_exception As System.Exception
        ProjectData.SetProjectError(v_exception)
        goto ILO_0b9a
      End Try
    ILO_0bde:
      Throw ProjectData.CreateProjectError(-2146828237)
    ILO_0be9:
      If v_i1 <> 0 Then
        ProjectData.ClearProjectError
      End If
    End Sub

**Comment by UlyssesWu** [comment]
I guess you should upload the dll file with a simple instruction for others to reproduce this issue.

**Comment by manojdjoshi** [comment]
issues not solved
