### ISSUE TITLE
DLL error messages with offset pointing

### ISSUE THREAD

**Issue by zoanthropy** [0xd4d/dnSpy#625]
Currently dnSpy does not tell me errors or only show PE header editor if it's avaliable if failed to read .dll correctly. Only Reflector tells me errors like this: 
![image](https://user-images.githubusercontent.com/20967118/33018270-011e8d8c-cdf6-11e7-8562-05534f47902f.png)

There are some .dll malwares that have modified MZ and BSJB header to prevent researchers from analyzing the malware.
What i want is dnSpy can tell me what type of error and point to offset where it caused failure. Example: I modify bytes of 0x4, dll will failed to read and tell me error "File is not a portable executable. DOS header does not contain 'MZ' signature (0x4)". That would be super useful and i would be able to fix it quicker with hex editor.

**Comment by 0xd4d** [comment]
This sounds like the job of a PE editor.

I'll close this since I don't plan on adding this feature and I don't expect anyone else to do it and send a PR.
