### ISSUE TITLE
dnSpy can not show the key of Hashtable and SortedList except expanding.

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#626]
Visual Studio:
![vs](https://user-images.githubusercontent.com/2529999/33124660-b5bc22ae-cfb8-11e7-96fa-b4ba9c5fcee3.jpg)

dnSpy:
![dnspy](https://user-images.githubusercontent.com/2529999/33124671-bfa43fb8-cfb8-11e7-8c65-e60c5c51dc17.jpg)

**Comment by 0xd4d** [comment]
It's because the debugger ignores the `Name` property.

```C#
	[DebuggerDisplay("{value}", Name = "[{key}]", Type = "")]
	class KeyValuePairs
```
