### ISSUE TITLE
Memory leak while exporting to project

### ISSUE THREAD

**Issue by ausgelegt** [0xd4d/dnSpy#628]
I have found a DLL file that will cause dnSpy to leak memory and slow down my computer if i export to project. It is the first time i ever seen it. 

DLL file to test

![image 1rr](https://user-images.githubusercontent.com/33931049/33174524-b63ad022-d058-11e7-82ce-83f34b610a69.png)

**Comment by 0xd4d** [comment]
The GC doesn't always collect the allocated memory. All the metadata has also been read from all files you decompiled and are cached. You can go to File -> Reload All, that will reload all files and GC will be forced to collect memory. Doing it once should collect most of it, but you can try a 2nd time and see if you free up more memory.
