### ISSUE TITLE
Mapped File Handle is kept open

### ISSUE THREAD

**Issue by 0x084E** [0xd4d/dnSpy#63]
If you add a file to the assembly list and then remove it the Mapped File Handle is kept open. You have to close dnSpy to release this handle. This is also true for atomatically loaded dependencies.

**Comment by 0xd4d** [comment]
Try the above commit and see if it helps.

**Comment by 0x084E** [comment]
For directly added assebmlies it works perfect. For dependend assemblies which are added automatically during decompilation the handle still stays open.

**Comment by 0xd4d** [comment]
Try the latest build.

**Comment by 0x084E** [comment]
Perfect. Thanks for taking the time!
