### ISSUE TITLE
switch bug

### ISSUE THREAD

**Issue by softmgr** [0xd4d/dnSpy#633]
[CSharp.zip](https://github.com/0xd4d/dnSpy/files/1504873/CSharp.zip)
解压CSharp.zip，并用dnSpy打开其中的CSharp.dll，定位到：JyGame/GameEngine
有如下代码：
`		public void SwitchGameScene(string type, string value)
		{
			if (RuntimeData.Instance.judgeFinishTask())
			{
				return;
			}
			if (this.CurrentSceneType.Equals("story"))
			{
				RuntimeData.Instance.PrevStory = this.CurrentSceneValue;
			}
			this.CurrentSceneType = type;
			this.CurrentSceneValue = value;
			switch (type)
			{
			case "story":
				if (Application.loadedLevelName == "Map")
				{
					RuntimeData.Instance.mapUI.LoadStory(value);
				}
				else
				{
					LoadingUI.Load("Map");
				}
				return;`

打开“编辑类”，不做任何修改，按“编译“，出现CS0136错误！
删除行：string item;  （此处为dnSpy错误添加）
再按“编译”，通过！
可是switch语句变成：
`		public void SwitchGameScene(string type, string value)
		{
			if (RuntimeData.Instance.judgeFinishTask())
			{
				return;
			}
			if (this.CurrentSceneType.Equals("story"))
			{
				RuntimeData.Instance.PrevStory = this.CurrentSceneValue;
			}
			this.CurrentSceneType = type;
			this.CurrentSceneValue = value;
			uint num = __0__<PrivateImplementationDetails>.ComputeStringHash(type);
			if (num <= 2671260646u)
			{
				if (num <= 1263289952u)
				{
					if (num <= 848251934u)
					{
						if (num <= 234353771u)
						{
							if (num != 60638767u)
							{
								if (num == 234353771u)
								{
									if (type == "menpai")
									{
										LoadingUI.Load("Menpai");
										return;
									}
								}
							}
							else if (type == "mainmenu")
							{
								Application.LoadLevel("MainMenu");
								return;
							}
						}
...................`

即switch语句被全部打乱！
再次进入“编辑类”界面，直接按“编译”按钮，会出现N处错误，程序不能继续编译！

**Comment by UlyssesWu** [comment]
@softmgr 请尊重作者，用英语提交issue，否则你的问题可能不会得到解答。
Please submit issues in English.

I can reproduce this issue. After re-compiling `JyGame.GameEngine.SwitchGameScene`, the decompiler seems doesn't recognize the logic as a `switch(string)` statement anymore. Instead, it shows the internal logic - compute hash for the string and jump to codes with the corresponding hash value.
