### ISSUE TITLE
if statement error

### ISSUE THREAD

**Issue by softmgr** [0xd4d/dnSpy#635]
C# Source code:

>         private bool if01(string type, string value)
>         {
>             if (type == "story")
>             {
>                 if (Application.loadedLevelName == "Map")
>                 {
>                     RuntimeData.Instance.mapUI.LoadStory(value);
>                 }
>                 else
>                 {
>                     LoadingUI.Load("Map");
>                 }
>                 return true;
>             }
>             if (type == "map")
>             {
>                 RuntimeData.Instance.ResetTeam();
>                 string text = RuntimeData.Instance.CheckTimeFlags();
>                 if (!text.Equals(string.Empty))
>                 {
>                     RuntimeData.Instance.mapUI.LoadStory(text);
>                     return true;
>                 }
>                 if (Application.loadedLevelName == "Map")
>                 {
>                     RuntimeData.Instance.mapUI.LoadMap(value);
>                 }
>                 else
>                 {
>                     LoadingUI.Load("Map");
>                 }
>                 if (Configer.IsAutoSave)
>                 {
>                     string content = RuntimeData.Instance.Save();
>                     SaveManager.SetSave("autosave", content);
>                 }
>                 return true;
>             }
>             return false;
>         }

After compiling, open with dnSpy 4.0.1 :

>         private bool if01(string type, string value)
>         {
>         	if (type == "story")
>         	{
>         		if (Application.loadedLevelName == "Map")
>         		{
>         			RuntimeData.Instance.mapUI.LoadStory(value);
>         		}
>         		else
>         		{
>         			LoadingUI.Load("Map");
>         		}
>         		return true;
>         	}
>         	if (!(type == "map"))
>         	{
>         		return false;  //??
>         	}
>         	RuntimeData.Instance.ResetTeam();
>         	string text = RuntimeData.Instance.CheckTimeFlags();
>         	if (!text.Equals(string.Empty))
>         	{
>         		RuntimeData.Instance.mapUI.LoadStory(text);
>         		return true;
>         	}
>         	if (Application.loadedLevelName == "Map")
>         	{
>         		RuntimeData.Instance.mapUI.LoadMap(value);
>         	}
>         	else
>         	{
>         		LoadingUI.Load("Map");
>         	}
>         	if (Configer.IsAutoSave)
>         	{
>         		string content = RuntimeData.Instance.Save();
>         		SaveManager.SetSave("autosave", content);
>         	}
>         	return true;  //??
>         }

**Comment by UlyssesWu** [comment]
I don't think there is any problem.
The decompiled code logic is totally same as the source code. Your code is optimized when compiling, so the decompile result is slightly different.

**Comment by HoLLy-HaCKeR** [comment]
Exactly what @UlyssesWu said, this is the expected output. If you look at the code, it functions the exact same way (the only difference being that the false branch of the if statement is shown first).

**Comment by softmgr** [comment]
@UlyssesWu @0xd4d 
本issue中的问题确实不影响使用，谢谢指正。该issue关闭了。
另一个issue中提的switch问题：确实有问题，
1.因为在“编辑方法”之后按"编译"，编译不通过(CS0136 错误)，需要手工删除一行: "string item;" 才能通过，实际上源码中并没有该定义，实际上 item是"ItemInstance item = obj as ItemInstance;"，这是dnSpy识别错误。
2.在删除"string item;"之后，按编译通过了。switch全部被替换成if ... if ... if ...，之后再次进入“编辑方法”，不做修改，直接按“编译”，会出现“uint num = __0__<PrivateImplementationDetails>.ComputeStringHash(type);” 这一句错误!!

**Comment by UlyssesWu** [comment]
@softmgr 关于switch，你还是没有理解我这一句

> 其显示的结果是switch(string)编译后的真正的内部实现方式

你所提到的1确实算是一个问题。
至于2，那是没有将代码表示为`switch(string)`，即使是显示为现在这样，代码本身依然没有问题。
`switch(string)`在编译之后的内部实现方式，就是计算字符串的哈希值并跳转到哈希值对应的代码块。
`ComputeStringHash(type)`是在计算哈希值。（至于你不了解的`0`，事实上是编译器生成的内部类`__0__<PrivateImplementationDetails>`，内含一个计算哈希值的方法，没毛病）
随后的`if`是在判断哈希值与哪个代码块相同。——是的，switch编译后产生的IL（字节码）与这样多个if产生的IL是 **相同** 的，所以即使显示为if也是正确的，只是反编译器做了一些工作以识别出哪些可以显示为switch。这方面还有待加强就是了。
最后，您at了原作者却没有用英文写回复，这是不礼貌的。除非只是写给我一个人看，否则请您注意使用英文，谢谢。

He is talking about #633 . It's a issue about decompiler.
1. The decompiler generates unnecessary statement `string item` which causes a name conflict.
2. After `Edit Method`, the decompiler couldn't show `switch(string)` correctly, instead it shows the internal implementation including `__0__<PrivateImplementationDetails>.ComputeStringHash(string)` and many `if`s.
