### ISSUE TITLE
Anyway to fix this variable issue?

### ISSUE THREAD

**Issue by ZexDex85127854** [0xd4d/dnSpy#637]
Is there a way to fix this issue? 1st pic is how it looks when not editing anything, second pic is when editing a function and clicking "compile".

(![how_it_looks_when_not_editing](https://user-images.githubusercontent.com/33598466/33510485-9c2f1b2c-d71d-11e7-8d49-f8e4ddae7050.png)
![issue](https://user-images.githubusercontent.com/33598466/33510486-9c54fa72-d71d-11e7-93e3-0c8086b1a512.png)

If there is no way now, will there be a fix for this in the future?

**Comment by ZexDex85127854** [comment]
Here is the issue in another scenario.

![screenshot 28](https://user-images.githubusercontent.com/33598466/33510566-72d21a4e-d71e-11e7-9067-0715958db32f.png)

**Comment by UlyssesWu** [comment]
If you won't use this vars (usually you won't), just remove these lines.

**Comment by HoLLy-HaCKeR** [comment]
This is just how lambda expressions are compiled. ILSpy would have to be updated, not dnSpy.

For now, just rewrite the code manually.
