### ISSUE TITLE
Error on assemblies list removal from left tree view

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#638]
Seen this error on dnSpy 4.0 release today - 

![screenshot_177](https://user-images.githubusercontent.com/765343/33514451-ec6abf08-d75c-11e7-95e1-782722d3cde5.png)

steps - CTRL +A (looks like there was some decompilation started & in progres0
Del
err box

**Comment by greenozon** [comment]
One more update - 
looks like there are some async operations used during assemblies removal, so even after CTRL+A / Del - tree view clean, then suddenly some dlls being appeared - like mscorlib.dll, etc

That is not expected..

**Comment by 0xd4d** [comment]
Did you use latest master sources?

**Comment by greenozon** [comment]
Nope,
that is 4.0 release bits

I'll give it a try latest bits from appveyor!
(if you say there is a chance to fix it out..)

**Comment by greenozon** [comment]
Just treid latest build - b625
I'm not able to reproduce the issue, but suddenly seen another interesting case -

when dnSpy ran as Admin - 
I can't drag-drop any assembly to the left tree view, eg:

![image](https://user-images.githubusercontent.com/765343/33517743-0e2986c6-d792-11e7-9eca-9dd9d8b334d2.png)

**Comment by 0xd4d** [comment]
It's not a dnSpy bug, I can reproduce it with eg. a text editor.

**Comment by riQQ** [comment]
See https://blogs.msdn.microsoft.com/patricka/2010/01/28/q-why-doesnt-drag-and-drop-work-when-my-application-is-running-elevated-a-mandatory-integrity-control-and-uipi/ for an explanation.
