### ISSUE TITLE
System.InvalidOperationException The operation is invalid due to the current state of the object

### ISSUE THREAD

**Issue by DC4-SERGEY** [0xd4d/dnSpy#648]
I no longer understand what the hell is going on here with the script - administrators are kind enough to check. Perhaps dnSpy is breaking dll

Assembly-CSharp.dll class ClientConnection void AuthorisationRoutine - Edit and Save

XXXXXXXXXX

Not only does it deteriorate, but others also sometimes

**Comment by DC4-SERGEY** [comment]
@0xd4d

**Comment by 0xd4d** [comment]
Upload the original files.

**Comment by 0xd4d** [comment]
Retry it with the original files or remove the unused duplicate compiler-generated classes.
