### ISSUE TITLE
option to break at TLS or system breakpoint

### ISSUE THREAD

**Issue by Ahmadmansoor** [0xd4d/dnSpy#649]
Hi my friend 
can you add an option to add BP at the specific address (like TLS or system breakpoint) before loading the process Like (break at) entry point option.
because sometimes we need to do some modification before the process load.
Thanks for the great work.
BR

**Comment by 0xd4d** [comment]
That's not possible with managed debugging. Should be possible with mixed debugging but it's not supported at the moment. You can stop at CreateProcess or you can add a module breakpoint or place a BP in some method you know will execute before Main()

**Comment by Ahmadmansoor** [comment]
Hi thanks for the reply , the problem here that the exe file is native code and it's packed and the other dll files are Dot net.
so what I am asking is an option to stop the process before the TLS (like suspend )so I can inject some dll files to hide the debugger.
could be this possible?
I really sorry I try to edit the code, but it was too difficult to do :( .
BR

**Comment by 0xd4d** [comment]
It's not possible with managed debugging. See my previous reply.
