### ISSUE TITLE
Can't analyze a Interface object

### ISSUE THREAD

**Issue by Alcatraz3222** [0xd4d/dnSpy#65]
I think this picture is worth a thousand words :)

http://prntscr.com/9etk2t

**Comment by 0xd4d** [comment]
Do you have some code? If it's private, you can email me it.

**Comment by Alcatraz3222** [comment]
the code of the image can be found at mscorlib.CommonLanguageRuntimeLibrary.System.Collections.Generic.Dictionary and in the method FindEntry

if you can't find it let me know and i'll send you the mscorlib file plus the MD Token
