### ISSUE TITLE
Debug Unity games

### ISSUE THREAD

**Issue by 0xd4d** [0xd4d/dnSpy#652]
Latest [master build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts) can now debug Unity games. See the wiki https://github.com/0xd4d/dnSpy/wiki/Debugging-Unity-Games since it's more complicated to set up than .NET Framework / .NET Core debugging.

I'll upload the patched mono.dll sometime, if you can't turn the game into a debug build.

**Comment by Yardanico** [comment]
You're literally a God

**Comment by Maximilian-Reuter** [comment]
Would be nice to have that modified mono dll since I do have a game that crashes after startup and want to find out what is going on.

**Comment by 0xd4d** [comment]
You can turn it into a debug build too.

I'll compile a bunch of different versions and then I'll upload them somewhere.

**Comment by Maximilian-Reuter** [comment]
maybe I didn't understand it correctly but don't you need the original unity project to do that ? The wiki wasn't really clear on that. Otherwise how are you gonna get a debug exe ?

**Comment by 0xd4d** [comment]
You get the debug build exe from the Unity Editor installer. Just make sure you install the correct version, see the wiki.

**Comment by Yardanico** [comment]
@Maximilian-Reuter mono is a .net runtime, it's doesn't contain game code, and also it's open-source.

**Comment by DC4-SERGEY** [comment]
where to find the correct mono.dll?

**Comment by Yardanico** [comment]
@DC4-SERGEY compile  by yourself for now

**Comment by DC4-SERGEY** [comment]
@Yardanico  Can you share the compiled dll?

**Comment by Yardanico** [comment]
@DC4-SERGEY I didn't compile it, because I don't currently need to debug Unity games

**Comment by DC4-SERGEY** [comment]
@Yardanico (

**Comment by 0xd4d** [comment]
4.5.0-beta has been released, you'll find the compiled mono.dll files on the release page.
