### ISSUE TITLE
ver 4.5beta: debugging mono bug

### ISSUE THREAD

**Issue by softmgr** [0xd4d/dnSpy#653]
0xd4d:
Thank you very much for your software!
According to your "Debugging Unity Games" article:
I put the file "mono.dll" into the game directory (replace the source file), and then run the unity game.
Start dnSpy and go to Debug -> Attach to Process (Unity) ->  I can't see it.
"wait until its intro is over and try again." -> I can't see it.
I press the refresh button -> I can't see it.
Retry again and again -> I still can't see it.

Known: the game is compiled with unity 5.2.4 x86.
Part of the file of the game program has been submitted in my last issue: 
https://github.com/0xd4d/dnSpy/issues/633
Is my operation incorrect?
Thank you again for your software!

**Comment by 0xd4d** [comment]
You're using a release build, read [this](https://github.com/0xd4d/dnSpy/wiki/Debugging-Unity-Games) again. You're using the wrong dialog box.
