### ISSUE TITLE
dnSpy x86 crash

### ISSUE THREAD

**Issue by lanzhiquan** [0xd4d/dnSpy#656]
See report file below
[Report.zip](https://github.com/0xd4d/dnSpy/files/1544620/Report.zip)

**Comment by 0xd4d** [comment]
What version of dnSpy are you using? Try the latest version. What is the error message?

**Comment by lanzhiquan** [comment]
dnSpy v4.5.0-beta
Crash happening when I'm trying to open a file (Ctrl+O or File→Open) after opening file dialog and trying switch to other directory.

**Comment by 0xd4d** [comment]
I can't reproduce it. Could you explain step by step how I can reproduce it.

**Comment by 0xd4d** [comment]
This is from another issue, but you could try this too:

Delete/rename these folders, replace XXX with your user name:

- C:\Users\XXX\AppData\Local\dnSpy
- C:\Users\XXX\AppData\Roaming\dnSpy

And redownload dnSpyand extract the files to a NEW folder (don't overwrite an existing folder)

**Comment by lanzhiquan** [comment]
Still the same problem.
See crash demo below, I think I should reinstall Window to solve this problem.

[crash_demo.zip](https://github.com/0xd4d/dnSpy/files/1544953/crash_demo.zip)
