### ISSUE TITLE
How do I debug?

### ISSUE THREAD

**Issue by DC4-SERGEY** [0xd4d/dnSpy#657]
![image](https://user-images.githubusercontent.com/32691168/33795582-505329c2-dcf5-11e7-824b-6c4820323001.png)

Process is not in the list

**Comment by 0xd4d** [comment]
So dark except for that blue button. Maybe a hint?

**Comment by 0xd4d** [comment]
Click the blue button and it will take you to the wiki.

**Comment by DC4-SERGEY** [comment]
@0xd4d I tried all the ways - the process does not appear

**Comment by 0xd4d** [comment]
"I tried all the ways" is obviously not true, or you'd be debugging by now, so if you want help you have to write down exactly what you've tried. I'm guessing you're still staring at the attach to process (unity) dialog box, which means you haven't read the wiki and didn't click the blue button. You have a release build so replace mono.dll with the patched one and the rest is in the wiki article.
