### ISSUE TITLE
dnspy can't edit "Iterator", By "Edit IL instructions".

### ISSUE THREAD

**Issue by softmgr** [0xd4d/dnSpy#659]
dnspy can't edit "Iterator", By "Edit IL instructions".
If I choose the menu "Edit class" or "Edit method", then a new iterator will be recreated, but the old iterator still cannot be edited.

**Comment by 0xd4d** [comment]
The compiler creates a state machine type that contains the actual code. You have to enable 'show all members' option to see the type. Or you can just edit C# Code and don't have to worry about any of that.

**Comment by RaTcHeT302** [comment]
I can't find this setting in the IL Edit window, where is it located?

**Comment by beppe9000** [comment]
right click individual instructions
