### ISSUE TITLE
Allow copying methods between different modules

### ISSUE THREAD

**Issue by kvozon** [0xd4d/dnSpy#66]
I would like to have an ability to copy cose between modules, for exampe,  if i create a new function and i want to add its code to other module. Thanks!

**Comment by Rottweiler** [comment]
I'm fairly sure it works if you remove the method from the original assembly before adding it to the new one

**Comment by 0xd4d** [comment]
Copying instructions from the method body editor to another method has been possible for some time now so I'm closing this.
