### ISSUE TITLE
Mixing long file name and short file name (8.3) will cause breakpoints not to be hit

### ISSUE THREAD

**Issue by wangzq** [0xd4d/dnSpy#661]
I know this is a rare scenario but it cost me quite some time to figure out why:

For some reason a Windows service installed at `c:\Program Files` is registered using short file name such as "c:\progra~1\..."; when using dnspy to attach I found some breakpoints were not hit while some of them will get hit. It turned out some of the dependent assemblies were loaded using long file name while the main module is still using short file name, I guess when comparing the path this is causing mismatch and hence the breakpoint was not set.

This is probably not worth the effort to fix from dnspy side, feel free to close it, just want to mention this in case someone else encounter this issue too.

**Comment by 0xd4d** [comment]
I've pushed a fix, could you test it? https://ci.appveyor.com/project/0xd4d/dnspy/build/x.x.640

**Comment by wangzq** [comment]
Verified and working! Thanks for the quick fix.
