### ISSUE TITLE
Cannot obtain value of the local variable or argument because it is not available at this instruction pointer, possibly because it has been optimized away.

### ISSUE THREAD

**Issue by wangzq** [0xd4d/dnSpy#663]
This is not an issue but a question, I am not familiar with debugger API so this might be by design behavior:

I have set the environment `COMPLUS_ZapDisable` to 1 in system environment variable list and verified using SysInternals' Process Explorer that a Windows service process does have the environment variable set to 1. After attaching to the process from DnSpy, I noticed that some of the local variables are able to show their values while some of them will show as `Cannot obtain value of the local variable or argument because it is not available at this instruction pointer, possibly because it has been optimized away.`, as well as the parameters. 

The assemblies are from release build and optimized.

**Comment by 0xd4d** [comment]
That's what happens in optimized code. You should try to use non-optimized code if possible. Click the blue info-icon next to the OK button in the `attach to process` dialog box for more info.

**Comment by wangzq** [comment]
Thanks
