### ISSUE TITLE
Error:DSBUG1	Exception: System.InvalidOperationException: Operation is not valid due to the current state of the object.

### ISSUE THREAD

**Issue by PureTrainer** [0xd4d/dnSpy#664]
I was trying to change something in Assembly-CSharp of a Unity game then when I hit compile it gave me an error:
![scr](https://user-images.githubusercontent.com/34469181/33922958-84f70a12-dff8-11e7-80f8-d8fc206ea231.png)
I don't know why this occurs. I didn't find any solution here please help.
I was editing this DLL(Assembly-CSharp):
XXXXXXXXXXXXXXXX
I gave you the whole directory. Hope you guys can help.

**Comment by PureTrainer** [comment]
@0xd4d

**Comment by 0xd4d** [comment]
What method did you edit?

**Comment by 0xd4d** [comment]
Upload the original files

**Comment by 0xd4d** [comment]
Retry it with the original files or remove the unused duplicate compiler-generated classes.

**Comment by E-v-o** [comment]
I am also getting this error after I edit a method two times. No matter what I do I have two attempts, weird.
