### ISSUE TITLE
[Bug] Namespace same as classname = error

### ISSUE THREAD

**Issue by PiotrKFtw** [0xd4d/dnSpy#668]
dnSpy put code like this after compiling
![screenshot_63](https://user-images.githubusercontent.com/33489788/34321251-90aabd76-e80a-11e7-8ed8-89bd004cff9e.png)

Result: Error CS0234 - The type or namespace does not exist in the namespace BlackMode (are you missing assembly reference?)
Original:
![screenshot_64](https://user-images.githubusercontent.com/33489788/34321256-a9da7fac-e80a-11e7-9280-1ceec68d8e40.png)

**Comment by 0xd4d** [comment]
Decompiler bug
