### ISSUE TITLE
Ambiguity between 'AppDomain.AssemblyLoad' and 'AppDomain.AssemblyLoad'

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#669]
Original code:
```
    class Program
    {
        static void Main(string[] args)
        {
            AppDomain.CurrentDomain.AssemblyLoad += CurrentDomain_AssemblyLoad;
        }

        static void CurrentDomain_AssemblyLoad(object sender, AssemblyLoadEventArgs args)
        {
        }
    }
```

use Edit Method(C#) to edit "Main" will get error:
Ambiguity between 'AppDomain.AssemblyLoad' and 'AppDomain.AssemblyLoad'

By the way, why do you disable issus in dnlib repository?

**Comment by UlyssesWu** [comment]
The `AssemblyLoad` event and private field in `System.AppDomain` conflicted. Should we just ignore private fields in this case? We shouldn't access private fields in other types anyway.

**Comment by CreateAndInject** [comment]
It seems dnSpy is able to access private members, such as:
```
	                string str="test";
			Console.WriteLine(str.m_firstChar);
			Console.ReadKey();
```
Visual Studio can not compile this code, but dnSpy can.
But the code can not run (ieldAccessException)

I don't know why does dnSpy allow this?

**Comment by HoLLy-HaCKeR** [comment]
It's actually pretty handy that dnSpy allows this, but an option to temporarily disable it would be nice.
