### ISSUE TITLE
Add support language C/C++

### ISSUE THREAD

**Issue by Wijaxu** [0xd4d/dnSpy#67]
Add support language C/C++ , It will be pretty cool!

**Comment by Nummer** [comment]
C/C++ - native language. =\

C++ CLI suppored

**Comment by UlyssesWu** [comment]
(Unmanaged)C/C++ is not a .NET language. Why "D(ot)N(et)Spy" have to support that?
C++/CLI assembly is supported but DnSpy lacks the function to decompile assembly to C++/CLI (That's not very difficult. A Reflector add-in can do that.)

**Comment by 0xd4d** [comment]
Closed, it's a .NET tool, not a native (C/C++) tool. IDA Pro is probably what you need.
