### ISSUE TITLE
Slow removing assembly from list

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#671]
The more assemblies, classes etc. you have expanded the longer it takes to remove all assemblies from list if you hit CTRL+A and then delete.

As a side note but not import I would like to request a hotkey to remove all assemblies. Maybe shift+delete or something?

**Comment by HoLLy-HaCKeR** [comment]
Selecting all tree nodes and pressing delete will run it for every item in the list, so just collapse them before deleting.

**Comment by 0xd4d** [comment]
File -> Close All

AFAIK it's the underlying listview that only can remove one element at a time (or remove all of them).
