### ISSUE TITLE
Fix locals value grabbing during debugging

### ISSUE THREAD

**Issue by XenocodeRCE** [0xd4d/dnSpy#672]
![](https://i.imgur.com/OYUq51V.png)

Always happens when debugging. 
No "antidnspy" trick or anything, some values are instanced in other methods, and it can't fetch the value. It's pretty annoying, but I don't want to sounds rude ! 

I can send you a sample if you provide me your mail.

**Comment by 0xd4d** [comment]
Decompiler generated variables don't exist in the metadata and can't be shown. Enable 'show compiler generated variables' and you'll see all variables.

**Comment by XenocodeRCE** [comment]
Why is it unchecked by default ? @0xd4d

**Comment by 0xd4d** [comment]
Because there's no such variable in the decompiled code. Can be confusing.

Decompiler generated variables are shown (with an error message) by default or some people will wonder why they can't see the variable in the locals window.
