### ISSUE TITLE
Toggle multiple breakpoints at once

### ISSUE THREAD

**Issue by FickoDeLux** [0xd4d/dnSpy#673]
I am not sure this should be considered a bug or feature request.

Currently you can select multiple nodes in the tree and set the break point but only one break point gets actually installed.

Missing implementation or bug ?

**Comment by 0xd4d** [comment]
F9 works in the text view only, not in assembly explorer.

**Comment by 0xd4d** [comment]
Try 'Class Breakpoint' if you want to set a BP in every method. (right-click the class def)
