### ISSUE TITLE
Is it possible to make switch (string) more nice?

### ISSUE THREAD

**Issue by FickoDeLux** [0xd4d/dnSpy#674]
This is just a question.
I have this kind of code:
```C#
 switch (name) {
     case "propDPI":
            break;
            case "MediaLoadTimeout":
...
..
.
```
And dnSpy decomplies it like this:
```C#
uint num = <PrivateImplementationDetails>.ComputeStringHash(name);
if (num <= 2126621877u)
	{
	if (num <= 588052352u)
		{
...
..
.
...
That's just too horrible.
Is it possible to make it more readable?

**Comment by HoLLy-HaCKeR** [comment]
You'll have to make an issue at the [ILSpy repo](https://github.com/icsharpcode/ILSpy) for that, since dnSpy uses its decompilation engine.

**Comment by FickoDeLux** [comment]
Ok, an additional info to this that it does adversly influences dnSpy search result as well.
It can not find this string literals at all.

**Comment by 0xd4d** [comment]
The searcher doesn't use the decompiler, it just checks the IL code and it should find all strings in the IL or in attributes.

**Comment by FickoDeLux** [comment]
Yeh, well....It dosn't find any literal string as far I can see.

See attachment.
![searchliteralstring](https://user-images.githubusercontent.com/19427606/34415849-128b97d6-ebf1-11e7-8668-f95bfdc69a75.jpg)

**Comment by 0xd4d** [comment]
Check your search settings, check the IL for the string, make sure you're searching all assemblies.

**Comment by FickoDeLux** [comment]
> make sure you're searching for strings and not for types/methods.

That hint helped, than you.

But I think there is something faulty there.
The selection:"All of the above"
 implies it would search with no filtering but it find strings only if I select:
"Number/String"

**Comment by DewiMorgan** [comment]
This issue appears fixed in current stable ILSpy, 4.01.
![dnSpy-bug](https://user-images.githubusercontent.com/5651448/55685620-f6bcc200-591d-11e9-9545-3414c4ade74d.jpg)
![ILSpy-OK](https://user-images.githubusercontent.com/5651448/55685623-fd4b3980-591d-11e9-9962-b0f2fd9c3aba.jpg)

**Comment by DewiMorgan** [comment]
I've no clue what modifications might be needed to get ILSpy to work with dnSpy, so am leery of trying to just "upgrade and recompile".

**Comment by DewiMorgan** [comment]
Should be resolved once https://github.com/0xd4d/dnSpy/issues/963 is done.
