### ISSUE TITLE
Cannot find the Modules tab when debugging

### ISSUE THREAD

**Issue by Prophesied** [0xd4d/dnSpy#675]
I just can't find it or enable the view in settings (where should I look?)

https://i.imgur.com/W4v1SGQ.png

Thanks for your help <3

**Comment by HoLLy-HaCKeR** [comment]
Debug -> Windows -> Modules, or use the CTRL+ALT+U shortcut

![image](https://i.imgur.com/PEblNKn.png)

**Comment by Prophesied** [comment]
Thank you!

**Comment by owaisnic** [comment]
I AM UNABLE TO FIND MODULE TAB WHEN DEBUGGING IN DNSPU 5.

**Comment by HoLLy-HaCKeR** [comment]
I think you should get your caps lock checked.

**Comment by owaisnic** [comment]
i tried with caps lock and without caps lock
![image](https://user-images.githubusercontent.com/33257750/39392087-a90fb8aa-4ac8-11e8-85c8-3cc81c143b1c.png)

**Comment by HoLLy-HaCKeR** [comment]
No, I was saying that you should not type a message entirely in caps. Also, don't hijack other issues but create your own.

The modules window/option allows you to look at all loaded modules in memory. For any modules to be loaded in memory in the first place, an application needs to be running. Thus, the modules option will only appear when you're debugging something. 

Please create a new issue next time.

**Comment by SukhmanjotDev** [comment]
Thank you finally I was so mad over nothing lol.
