### ISSUE TITLE
Scripting

### ISSUE THREAD

**Issue by anamezon** [0xd4d/dnSpy#676]
Good Day. Thank you for great instrument. Please help me to understand, how I will can write debugger scripts for them. I try to write tracing script. I open C# interactive window. I try example from wiki (using dnSpy.Contracts.Scripting.Debugger;). Result: error CS0234: The type or namespace name 'Debugger' does not exist in the namespace 'dnSpy.Contracts.Scripting' (are you missing an assembly reference?). Please tell me when I have find class usable for scripting (StepInto, StepOut). Thank you in advance.

**Comment by 0xd4d** [comment]
That document is out of date. Have a look in the debugger source code instead.
