### ISSUE TITLE
when debugging it cant break anymore

### ISSUE THREAD

**Issue by tmzaw** [0xd4d/dnSpy#677]
sorry to bother you,  but someting weird happened.
a few days ago i use this great tool to debug a program and it did worked smothly
but these days i dont know what has happened
when i debug the same program  it can only start up the program but cant break at the entry point and 
cant break at any breakpoints 
but when i use this to debugg another program it still could work
i dont know what has happend 
really really need your advice
thanks a lot

**Comment by 0xd4d** [comment]
Could be some antis or whatever. It's not a dnSpy issue since you say it's working with other programs.
