### ISSUE TITLE
Building dnSpy

### ISSUE THREAD

**Issue by VE-2016** [0xd4d/dnSpy#679]
I would like to build dnSpy from master branch, but during building, the namespace 
Microsoft.CodeAnalysis.ExpressionEvaluator.DnSpy
can't be found. Where are sources for that namespace?

JK

**Comment by riQQ** [comment]
You probably forgot to fetch the git submodules (see https://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules).

**Comment by 0xd4d** [comment]
https://github.com/0xd4d/dnSpy/wiki/Building-dnSpy
