### ISSUE TITLE
Decompile .NET Universal Apps

### ISSUE THREAD

**Issue by Nummer** [0xd4d/dnSpy#68]
The new Visual Studio 2015 adds the ability to create a universal .NET C# applications

dnSpy can not decompile the application.

**Comment by 0xd4d** [comment]
Aren't these native applications, i.e., compiled to native code using .NET Native?

**Comment by Nummer** [comment]
@0xd4d yep. Using .NET Native

**Comment by 0xd4d** [comment]
There's your problem. :) IDA Pro should probably be used in this case since it's all native code, and not .NET IL code.
