### ISSUE TITLE
Size of saved executable

### ISSUE THREAD

**Issue by FickoDeLux** [0xd4d/dnSpy#680]
What are the reasons that a saved executable size is bigger than the original?

Missing optimization?
Debug info included?

I tried some checkboxes (strip debug symboles etc.) but they do not seems to influence anything 
other than settings some flags.

**Comment by HoLLy-HaCKeR** [comment]
Possibly unrelated, but I noticed that replacing resources with dnlib makes them larger, even when they are the exact same. I only tested this with images, so it may just be a file format issue on my end.

**Comment by 0xd4d** [comment]
https://github.com/0xd4d/dnlib/issues/129
