### ISSUE TITLE
IL Viewer for invalid code?

### ISSUE THREAD

**Issue by bramhaag** [0xd4d/dnSpy#681]
Sometimes when writing IL instructions and injecting them into an assembly an error occurs. It's useful to see where it went wrong by looking at the IL, but if the method can't be decompiled the IL Editor is unavailable. I'm wondering if there's any way to view the malformed IL? My current "solution" is to use dotPeek which does offer such a feature, but I'd rather stick with dnSpy

**Comment by HoLLy-HaCKeR** [comment]
You can still rightclick the method name in C# view and press "Edit Method Body" to edit it. Otherwise, why not switch to IL view? You can open a tab with just the method you're inspecting so your view isn't bloated by other methods or type info.

**Comment by 0xd4d** [comment]
You can also right-click the method name in the text viewer or in assembly explorer.
