### ISSUE TITLE
Cannot decompile some variables

### ISSUE THREAD

**Issue by fireundubh** [0xd4d/dnSpy#682]
Some variables cannot be decompiled. I don't know how to articulate the issue, so here are some snippets:

dnSpy:
```csharp
if (Credits.<>f__switch$map0 == null)
{
	Credits.<>f__switch$map0 = new Dictionary<string, int>(2)
	{
		{
			"left",
			0
		},
		{
			"right",
			1
		}
	};
}
int num;
if (Credits.<>f__switch$map0.TryGetValue(text, out num))
{
```

JustDecompile:
```csharp
if (Credits.<>f__switch$map0 == null)
{
    Dictionary<string, int> strs = new Dictionary<string, int>(2)
    {
        { "left", 0 },
        { "right", 1 }
    };
    Credits.<>f__switch$map0 = strs;
}
if (Credits.<>f__switch$map0.TryGetValue(str, out num))
{
```

Both struggle with whatever `Credits.<>f__switch$map0` is supposed to be.

JustDecompile gets `Dictionary<string, int>` and its object initializer right.

dotPeek produces the same results here as dnSpy and with weird initializer formatting.

I don't have Reflector on my machine at home, but I can't imagine the output being much better.

**Comment by fireundubh** [comment]
All decompilers I tested have touble with some closures as well:

```csharp
[DebuggerHidden]
public static IEnumerable<MethodInfo> GetNonCheatMethods()
{
    CommandLineRun.<GetNonCheatMethods>c__Iterator70 variable = null;
    return variable;
}
```

**Comment by UlyssesWu** [comment]
if you think `Credits.<>f__switch$map0` is strange and there must be something wrong, you are wrong.

It's a compiler generated member and it's just named as `<>f__switch$map0` (by compiler). You can't name a var like that, but the compiler can. By this way the compiler generated members won't have same names as other members. There's nothing wrong.

**Comment by fireundubh** [comment]
> You can't name a var like that, but the compiler can.

The goal of decompiling is to produce source code that can be compiled. Source code with variable names like `<>f__switch$map0` cannot be compiled. When a decompiler produces source code that cannot be compiled, either the issue should be resolved, _if possible_, or the code should be annotated.

**Comment by UlyssesWu** [comment]
Sure, but it's also important to show the _real_ look of the assembly. For example, if decompiler just renamed `<>f__switch$map0` to `fswitchMap0`, and one day you manually searched the assembly (binary) for that string, then you found nothing.
JustDecompile has a option `Replace invalid characters in identifiers`, you can use that if you want something "can be compiled". Think about why it's not enabled by default.
Since it's an issue about decompiler and dnSpy uses ILSpy as decompiler, I don't think 0xd4d will solve this (he has mentioned for many times). You should ask ILSpy developers to improve it.

**Comment by 0xd4d** [comment]
Looks like mcs-compiled code, string switch probably.

@UlyssesWu is correct, I have no plan to fix this since there's no point in fixing the 2.x decompiler.

**Comment by fireundubh** [comment]
@UlyssesWu Is there a reference somewhere for what compilers name things and what those things are? Like, how do I interpret the string `<>f__switch$map0`?

@0xd4d 
> "There's no point in fixing the 2.x decompiler."

I'm guessing you're referencing ILSpy. Does dnSpy support 3.x yet? Working on it?

Happy New Year, guys.
