### ISSUE TITLE
issues 682 - revitalized

### ISSUE THREAD

**Issue by FickoDeLux** [0xd4d/dnSpy#683]
IMO
> https://github.com/0xd4d/dnSpy/issues/682

got closed too soon.

I am agree that just for the sake of "compiler generated members" it is not worth any consideration but
the mentioned functionality in "telerik"
> Replace invalid characters in identifiers

saved my ass sever times on obfuscated code that not even "De4Dot" was able to handle.

So I do like to have such functionality in DnSpy as well.
It is _definitely_ worthy.

**Comment by FickoDeLux** [comment]
It is actually ~%50 implemented already.

DnSpy renames invalid chars to "\uE000" format, which is readable but not compilable.
What needed is an option to output e.g. char 'A' in place of "\\" to get "Au000"

What remains is to implement the same conversion for the "*.cs" filenames at project creation. - "Au000.cs" - and that's it.

... I think....

**Comment by HoLLy-HaCKeR** [comment]
If your symbol names are high unicode, you probably want to run it through de4dot first. There is no reason to add generic deobfuscation features to dnSpy when there already is a very good tool available (by the same author, even).

**Comment by FickoDeLux** [comment]
> There is no reason to add generic deobfuscation features

It is allready there, just not implemented with the task in mind to make it compilable.

Like I sad above all what  it would take to replace one letter. "/" to something printable and run the "*.cs"
filename generator trough the same "\uE000" deobfuscation.

If we wanna be fancy could fix the IL output as well due to it dosn`t shows the renaming right now so
it is not in sync with C#.

**Comment by HoLLy-HaCKeR** [comment]
What is there is making the output readable. The high unicode characters are simply escaped so they don't appear as garbled mess or screw up text flow.

As for names starting with `<>`: these are types generated by the compiler for stuff like lambda expressions, LINQ, etc. It requires the decompiler to be updated, see issue #547.

**Comment by 0xd4d** [comment]
It's a hack option. It's better to fix the decompiler.

> saved my ass sever times on obfuscated code that not even "De4Dot" was able to handle.

Pass in the right regex and it will rename it. Shouldn't be difficult to rename types with `<` in their name.
