### ISSUE TITLE
Use "ildasm/ilasm" as an alternative engine

### ISSUE THREAD

**Issue by FickoDeLux** [0xd4d/dnSpy#684]
DotNet is steadily progressing and MS is keeping his tools up to date providing extensive cmd line control:

> Usage: ildasm [options] <file_name> [options]
Options for output redirection:
  /OUT=<file name>    Direct output to file rather than to GUI.
  /TEXT               Direct output to console window rather than to GUI.
  /HTML               Output in HTML format (valid with /OUT option only).
  /RTF                Output in rich text format (invalid with /TEXT option).
Options for GUI or file/console output (EXE and DLL files only):
  /BYTES              Show actual bytes (in hex) as instruction comments.
  /RAWEH              Show exception handling clauses in raw form.
  /TOKENS             Show metadata tokens of classes and members.
  /SOURCE             Show original source lines as comments.
  /LINENUM            Include references to original source lines.
  /VISIBILITY=<vis>[+<vis>...]    Only disassemble the items with specified
          visibility. (<vis> = PUB | PRI | FAM | ASM | FAA | FOA | PSC)
  /PUBONLY            Only disassemble the public items (same as /VIS=PUB).
  /QUOTEALLNAMES      Include all names into single quotes.
  /NOCA               Suppress output of custom attributes.
  /CAVERBAL           Output CA blobs in verbal form (default - in binary form).
  /NOBAR              Suppress disassembly progress bar window pop-up.
The following options are valid for file/console output only:
Options for EXE and DLL files:
  /UTF8               Use UTF-8 encoding for output (default - ANSI).
  /UNICODE            Use UNICODE encoding for output.
  /NOIL               Suppress IL assembler code output.
  /FORWARD            Use forward class declaration.
  /TYPELIST           Output full list of types (to preserve type ordering in round-trip).
  /PROJECT            Display .NET projection view if input is a .winmd file.
  /HEADERS            Include file headers information in the output.
  /ITEM=<class>[::<method>[(<sig>)]  Disassemble the specified item only
  /STATS              Include statistics on the image.
  /CLASSLIST          Include list of classes defined in the module.
  /ALL                Combination of /HEADER,/BYTES,/STATS,/CLASSLIST,/TOKENS

It can provide very nice detailed output not to speak about allaround compilation with resources.

It would be nice if DnSpy could use this tools as alternative.
Since they are cmd line tools as well I don't think any permission is needed for no distribution.

**Comment by HoLLy-HaCKeR** [comment]
How would it differ from the existing IL engine? All that ildasm does it converting the raw binary into IL, which is dnlib's job.

**Comment by FickoDeLux** [comment]
If it wouldn't differ than great, but at least would be a great comparison possibility for hidden bugs.

If the cmd line swithes would be exposed it would give the possibility to tailormade IL listing in DnSpy.
I do not know you have played with Ildasm recently but it is quite a tool for customized, 
optimized, debug etc. output.

And anyway it is allway better to have more options to fallback if any fails.

**Comment by HoLLy-HaCKeR** [comment]
I understand how ildasm works, I just don't see how it differs from the IL decompilation engine in dnSpy.
There is no way that it would produce a different output than dnlib because they just display the IL instructions in the assembly. You would be implementing the same thing, but relying on a native library/tool without having any of the essential functionality that dnlib provides.

As for ildasm-specific features: I don't see any that are useful that dnSpy doesn't already provide. If you do find one unmissable, though, why not write a plugin for it? I think it would be better to just use ildasm standalone, seperate from dnSpy, and not mix the two together.

**Comment by 0xd4d** [comment]
This is not something that I'll ever implement, and as @HoLLy-HaCKeR said, it's not needed.
