### ISSUE TITLE
Editing fields in generic types doesn't update references to that field.

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [0xd4d/dnSpy#685]
Take the following example code:
```cs
internal class Generic<T>
{
	private T t1;

	public Generic()
	{
		this.t1 = default(T);
	}
}
```

Attempting to edit the name of the `t1` field will not update the reference to the field in the constructor. 

This is a dnlib issue, as I've had the same problem when writing a private tool that also tried to update fields in generic types. Changing the opcode's operand to reference the new version of the field fixes the problem.

**Comment by 0xd4d** [comment]
It's not a dnlib issue. Whenever you rename a definition you have to fix all references too (MemberRefs).

**Comment by HoLLy-HaCKeR** [comment]
It doesn't happen in non-generic types, though. What's different?

**Comment by 0xd4d** [comment]
The compiler uses TypeDefs/FieldDefs/MethodDefs whenever possible.

**Comment by 0xd4d** [comment]
BTW, you can use `MemberFinder` to find those refs, just like dnSpy and de4dot do.

**Comment by HoLLy-HaCKeR** [comment]
Thanks, I think I can replace quite a bit of my code with that.

Although, that reminds me of something. Right now, editing the name of an interface's methods doesn't change the name of the implementations. Is this intended or will it change in the future? I'm currently trying to document Eazfuscator's VM and one of the interface has about 25 implementations, I'm not looking forward to changing 150 methods manually :P

**Comment by 0xd4d** [comment]
That's intended, it only renames the definitions. Finding all methods that override/implement a method requires a lot more code, de4dot can do it, though.

**Comment by HoLLy-HaCKeR** [comment]
Okay, perhaps I'll make an extension for it then. Thanks a lot!
