### ISSUE TITLE
[Question] Odd decompilation of async method?

### ISSUE THREAD

**Issue by kuskmen** [0xd4d/dnSpy#687]
So I have the following method decompiled:

```     
public async Task LockSelections(IEnumerable<string> selectionIds, string customerId)
{
      var selections = selectionIds.ToList();
       foreach (var selectionId in selections)
       {
            var selection = await StorageHelper.Get(GenerateCompoundKey(customerId, selectionId));
            if (selection != null)
           {
                 throw new InvalidOperationException($"The selection ${selectionId} is already locked!");
            }
       }

       foreach (var selectionId in selections)
       {
            var compoundKey = GenerateCompoundKey(customerId, selectionId);
            await StorageHelper.Set(compoundKey, compoundKey);
        }
}
```

And here is the decompiled code to C#:

```
public async Task LockSelections(IEnumerable<string> selectionIds, string customerId)
{
	List<string> selections = selectionIds.ToList<string>();
	foreach (string selectionId in selections)
	{
		TaskAwaiter<string> taskAwaiter = base.StorageHelper.Get(this.GenerateCompoundKey(customerId, selectionId)).GetAwaiter();
		if (!taskAwaiter.IsCompleted)
		{
			await taskAwaiter;
			TaskAwaiter<string> taskAwaiter2;                              <------
			taskAwaiter = taskAwaiter2;                                    <------  these lines are so questionable
			taskAwaiter2 = default(TaskAwaiter<string>);                   <------
		}
		if (taskAwaiter.GetResult() != null)                 <------ especially when we expect result after that
		{
			throw new InvalidOperationException(string.Format("The selection ${0} is already locked!", selectionId));
		}
		selectionId = null;
	}
	List<string>.Enumerator enumerator = default(List<string>.Enumerator);
	foreach (string selectionId2 in selections)
	{
		string text = this.GenerateCompoundKey(customerId, selectionId2);
		await base.StorageHelper.Set(text, text, null);
	}
	enumerator = default(List<string>.Enumerator);
}
```

I am not sure this is the audience to bring that question to, but since I am using this decompiler its my best shot.

**Comment by HoLLy-HaCKeR** [comment]
`await` is just synthetic sugar for what you see in the decompiled code. Usually ILSpy converts this back to what a programmer would normally write, but the version that dnSpy uses didn't have that implemented yet. You can find all implemented language features for the latest version of ILSpy [here](https://github.com/icsharpcode/ILSpy/issues/829), but keep in mind that dnSpy still uses ILSpy 2.x, not 3.x.

**Comment by kuskmen** [comment]
I see, thanks for clarification.

**Comment by chucklu** [comment]
> `await` is just synthetic sugar for what you see in the decompiled code. Usually ILSpy converts this back to what a programmer would normally write, but the version that dnSpy uses didn't have that implemented yet. You can find all implemented language features for the latest version of ILSpy [here](https://github.com/icsharpcode/ILSpy/issues/829), but keep in mind that dnSpy still uses ILSpy 2.x, not 3.x.

Did you add this feature to  a to do list?

**Comment by chucklu** [comment]
I got a different problem, "taskAwaiter  does not have definition of method GetAwaiter", and I did the trick as following
1. get the task first and store it in variable
2. task.GetAwaiter()
3. await task
```C#
Task task = base.StorageHelper.Get(this.GenerateCompoundKey(customerId, selectionId));
TaskAwaiter<string> taskAwaiter = task.GetAwaiter();
		if (!taskAwaiter.IsCompleted)
		{
			await task;
		}
```

**Comment by chucklu** [comment]
The above trick did not work

just make code simpler as following
```C#	
TaskAwaiter taskAwaiter = Client.MoveCursorHumanLike(cardPosition2).GetAwaiter();
				if (!taskAwaiter.IsCompleted)
				{
					await taskAwaiter;
					TaskAwaiter taskAwaiter2;
					taskAwaiter = taskAwaiter2;
					taskAwaiter2 = default(TaskAwaiter);
				}
				taskAwaiter.GetResult();
				taskAwaiter = default(TaskAwaiter);
```
replace with
```C#
await Client.MoveCursorHumanLike(cardPosition2);
```

**Comment by chucklu** [comment]
@kuskmen  You can get ILSpy version 5.0.0.5064-preview4-pr1633 from https://ci.appveyor.com/project/icsharpcode/ilspy/builds/26617584/job/blyf2m54wgvvh9vb/artifacts. This version has a fix for https://github.com/icsharpcode/ILSpy/issues/1632
Decompile the code in ILSpy and then replace the method with code in dnSpy.
