### ISSUE TITLE
Ability to use Variables inside DLL's in C# interactive console

### ISSUE THREAD

**Issue by RepublicofTexas** [0xd4d/dnSpy#689]
I would like to be able to use the Variables in the DLL's in the interactive console E.g a dll can have 
`string i = "g"`
And I can type in the console 
`Print(i);`
And I would get the output printed: g

**Comment by RepublicofTexas** [comment]
Okay I may be dumb but is there any way I can have the desired effect by doing something with 
`using DLLhere.dll;`?

**Comment by 0xd4d** [comment]
You can't do it since the variables are in another process. You can use the debugger API and read locals, examine them, modify them or evaluate expressions, etc.

**Comment by RepublicofTexas** [comment]
Are you able to modify them while the program is running or will you have to save the DLL's and then reload the program?

**Comment by 0xd4d** [comment]
Variables can be modified by pretty much any debugger, including this one. :)

**Comment by RepublicofTexas** [comment]
Are you able to modify then while the program is running or will you have to close and re-open for it to take effect?

**Comment by RepublicofTexas** [comment]
Nevermind, found out that a breakpoint can edit stuff while debugging live. Thanks for the help!
