### ISSUE TITLE
System.TypeInitializationException:““System.Windows.Media.Fonts”的类型初始值设定项引发异常。”

### ISSUE THREAD

**Issue by danperor** [0xd4d/dnSpy#692]
In a recent Microsoft update，By viewing the update history，Its name is "KB4055532",It contains a .netFramework 4.7.1 update called "KB4055002"
It is this update that throws an exception in dnSpy.
The following is an exception message：
System.TypeInitializationException
  HResult=0x80131534
  Message=“System.Windows.Media.Fonts”的类型初始值设定项引发异常。
  Source=PresentationCore
  StackTrace:
   在 System.Windows.Media.Fonts.get_SystemFontFamilies()
   在 dnSpy.Contracts.Controls.FontUtilities.Exists(String name) 在 D:\softDevelop\04-dnspy\dnSpy-master\dnSpy\dnSpy.Contracts.DnSpy\Controls\FontUtilities.cs 中: 第 123 行

内部异常 1:
FileFormatException: No FontFamily element found in FontFamilyCollection that matches current OS or greater: Windows7SP1

内部异常 2:
FileFormatException: No FontFamily element found in FontFamilyCollection that matches current OS or greater: Windows7SP1
Here is the picture for this:
![image](https://user-images.githubusercontent.com/18207964/34757919-528d2d68-f60f-11e7-91cd-92424195dcf2.png)
And:
![image](https://user-images.githubusercontent.com/18207964/34757967-ab83e7ae-f60f-11e7-88eb-46052c4d3583.png)

and When I uninstall this update, it works fine。
my OS Version is Windows 7 Ultimate sp1.
Whether this problem needs fixing, waiting for Microsoft's next update, or uninstall the update?

**Comment by 0xd4d** [comment]
Seems like there's nothing dnSpy can do about that since it just accesses `Fonts.SystemFontFamilies` which is part of .NET Framework.

I suspect that same exception will be thrown if you write your own little application that does the same thing:

```C#
static void Main() {
    var fontFamilies = Fonts.SystemFontFamilies.ToArray();
    Console.WriteLine(fontFamilies.Length);
}
```

**Comment by 0xd4d** [comment]
Could you show the call stack window and the thrown exception?

Do you have some non-standard fonts installed? It says there's no font family that matches Windows7SP1 or later. This is from `CompositeFontParser`

**Comment by 0xd4d** [comment]
BTW, the fonts are in `C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\Fonts`, you can diff them to see the differences if it updates them (they're xml files)

**Comment by 0xd4d** [comment]
I tried this in a VM, and I couldn't get the update you're mentiong above. I downloaded it from MS windows catalog and installed KB4055002, and I get that exception too.

The reason is that there's no entry for WindowsXPSP1 in `C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\Fonts\GlobalUserInterface.COMPOSITEFONT` (and possibly the other files in that same dir). There are only OS entries for Win8.1 and Win10. The older file had an entry for Win7SP1 too.

Can you uninstall the update from Windows Update, and then try Windows update again. Does it still say that the update is available?

**Comment by 0xd4d** [comment]
They changed WindowsXPSP2 to Windows8Point1, but it should've been Windows7SP1

**Comment by 0xd4d** [comment]
Latest build (or latest release) contains the fix.

**Comment by calbzam** [comment]
But do you mean last release of your tool or a new Windows update?

**Comment by HoLLy-HaCKeR** [comment]
Latest version of dnSpy. You find it in the [Releases](https://github.com/0xd4d/dnSpy/releases) page (latest release) or at [AppVeyor](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts) (latest build).

**Comment by danperor** [comment]
@0xd4d Because I'm not always online，I'm sorry for not interacting with you in time。
And thank you for your good work

**Comment by richlander** [comment]
Please see https://github.com/dotnet/announcements/issues/53

Please accept my apologies from the .NET team on this issue.

**Comment by daykun** [comment]
From what I have seen, this issue can be remediated by using the old C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\Fonts\GlobalUserInterface.COMPOSITEFONT and C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\Fonts\GlobalUserInterface.COMPOSITEFONT from before the update.

**Comment by richlander** [comment]
I just added instructions for copying the old font at https://github.com/dotnet/announcements/issues/53
