### ISSUE TITLE
BUG: Do not support the "this" keyword!

### ISSUE THREAD

**Issue by softmgr** [0xd4d/dnSpy#695]
The following code is compiled and passed in vs2013:

		private void Start()
		{
			AttackLogic.field = this;  //CS0029 error in dnspy
			//..........................
		}

After the program is compiled to exe by vs2013, the error CS0029 by dnspy decompile!

**Comment by 0xd4d** [comment]
There's not enough information to reproduce it.

**Comment by softmgr** [comment]
@0xd4d 
The above code is located:
#633 in CSharp.zip, after extracting files: CSharp.dll - > JyGame - > BattleField - > private void (Start)

**Comment by 0xd4d** [comment]
Seems to be a dupe of #365

**Comment by 0xd4d** [comment]
This has now been fixed, get the latest build.
