### ISSUE TITLE
Functional requirements:  about the button of the "Edit IL instructions" dialog

### ISSUE THREAD

**Issue by softmgr** [0xd4d/dnSpy#696]
The "OK" button of the "Edit IL instructions" dialog is the default state. 
After the input IL instruction, it is easy to mistakenly touch the Enter key. Please remove its "IsDefault" property.

**Comment by 0xd4d** [comment]
Ctrl+Z will undo anything you accidentally added.

**Comment by softmgr** [comment]
@0xd4d 
But after undo, the previous IL instruction was deleted...

**Comment by 0xd4d** [comment]
Open the IL editor again if you accidentally hit ENTER.
