### ISSUE TITLE
Severity	Code	Description	File	Line Error	CS0656	Missing compiler required member 'System.Runtime.CompilerServices.CompilationRelaxationsAttribute..ctor'		

### ISSUE THREAD

**Issue by thegreathacker** [0xd4d/dnSpy#699]
please fix it i am not understanding how to fix it 

![untitled](https://user-images.githubusercontent.com/28702511/35031438-f545eb0c-fb88-11e7-835a-4ca09f57fb8c.png)

**Comment by 0xd4d** [comment]
Attach the files here.

**Comment by thegreathacker** [comment]
what file should i attach

**Comment by thegreathacker** [comment]
please solve it plz it is urgent

**Comment by thegreathacker** [comment]
please help me

**Comment by HoLLy-HaCKeR** [comment]
Perhaps if you upload the sample, people can help. The `need-more-info` label or "Attach the files here." comment should have told you that.

**Comment by thegreathacker** [comment]
[dnSpy.zip](https://github.com/0xd4d/dnSpy/files/1649772/dnSpy.zip)

i am using this file 

still need any info

**Comment by HoLLy-HaCKeR** [comment]
Not dnSpy, the program you're reversing.

**Comment by thegreathacker** [comment]
[Managed.zip](https://github.com/0xd4d/dnSpy/files/1649821/Managed.zip)

extract the folder to get files

for every file it is saying like that

**Comment by HoLLy-HaCKeR** [comment]
Editing that class using the C# compiler won't compile because anonymous methods and iterators have illegal names and the ILSpy engine doesn't prettify it yet.

Not sure about the CS0656 in the screenshot though, I don't get it.

**Comment by thegreathacker** [comment]
but in youtube lots of members are edeting

to hack games it is very important

any solutation please

**Comment by 0xd4d** [comment]
The compiler apparently requires a ctor that takes an Int32 param, but the one in Unity's mscorlib doesn't have one, only a ctor that takes a CompilationRelaxations parameter.

You can create your own attribute and paste this at the end of the code when you edit a method:

```C#
namespace System.Runtime.CompilerServices
{
	[System.AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Module | AttributeTargets.Class | AttributeTargets.Method)]
	class CompilationRelaxationsAttribute : Attribute
	{
		public CompilationRelaxationsAttribute(int relaxations)
		{
			this.relax = (int)relaxations;
		}

		int relax;
	}
}
```

**Comment by thegreathacker** [comment]
can you please make a video on that

i am a begginer

**Comment by 0xd4d** [comment]
A video? No!

dnSpy shows you this:

```C#
<some code>
```

You change it to this:
```C#
<some code>

namespace System.Runtime.CompilerServices
{
	[System.AttributeUsage(System.AttributeTargets.Assembly | System.AttributeTargets.Module | System.AttributeTargets.Class | System.AttributeTargets.Method)]
	class CompilationRelaxationsAttribute : System.Attribute
	{
		public CompilationRelaxationsAttribute(int relaxations)
		{
			this.relax = (int)relaxations;
		}

		int relax;
	}
}
```

**Comment by thegreathacker** [comment]
bro please i am begging you what you want to say i am not understanding

**Comment by thegreathacker** [comment]
where dnspy shows
<some code>
