### ISSUE TITLE
Cannot Create "valuetypes" for Callvirt for Types

### ISSUE THREAD

**Issue by Panthere** [0xd4d/dnSpy#70]
Heya,

I noticed that I cannot create valuetypes for classes when in a callvirt, like HashSet`1\<valuetype MyClass.MyEnum\>::Add(!0)

Is it just me missing something in the complex setup of MethodSpec/MethodRef on a callvirt or an actual problem?

**Comment by 0xd4d** [comment]
I had no problem creating a callvirt to that method and use value types:

```
5	000A	callvirt	instance bool [System.Core]System.Collections.Generic.HashSet`1::Add<int32>(!0)
6	000F	callvirt	instance bool [System.Core]System.Collections.Generic.HashSet`1::Add<valuetype [dndbg]dndbg.COM.CorDebug.CorDebugExceptionObjectStackFrame>(!0)
```

First pick MethodSpec, then add the HashSet::Add method. Then you add the value type in the next tab, and click the Add button, followed by OK.

**Comment by Panthere** [comment]
Hey 0xd4d, yes, you can easily add valuetypes to the method, but what about the referenced type?

**Comment by 0xd4d** [comment]
I've updated my first reply since in this case you're supposed to use MemberRef's and not MethodSpecs. Does that solve your problem, if not, explain what you did, what you got and what you expected to get.

**Comment by Panthere** [comment]
Awesome, that is really good to know. Worked fine :)
