### ISSUE TITLE
Error calculating max stack value.

### ISSUE THREAD

**Issue by alan717** [0xd4d/dnSpy#700]
![screenshot_2018-01-18_17-34-39](https://user-images.githubusercontent.com/8288681/35090845-e7fe500e-fc75-11e7-9249-4bb32142a7fe.png)
 I add some il code at the entry of the method. i got this  when i save the dirty file .

**Comment by YuqseLx** [comment]
Is that obfuscated? It's not problem i think this is an warning only

**Comment by alan717** [comment]
After i ignore those warnning .I load my dirty dll files. all thing do work correctly. 
those dll doesn't  obfuscated . 
those is my c# program  dll file .
may be it will be occur again.I will record the more info to get a better explain.
thanks .

**Comment by ubden** [comment]
![MRYXVa](https://user-images.githubusercontent.com/44896964/79026170-9abff580-7b90-11ea-87f5-45286538f578.png)

This Problem ? I try all mod versions and lastest org version.
