### ISSUE TITLE
To determind Where the delegate code section

### ISSUE THREAD

**Issue by alan717** [0xd4d/dnSpy#701]
from this decompiled c# code . 
```
`Action<int, Dictionary<string, object>> action = delegate(int status, Dictionary<string, object> content)
	{
		try
		{
                        
			Console.WriteLine(content["keys"].value);
	
		}
		catch (Exception ex)
		{
                 ///null 
		}
	};`
```
I try to edit il instructions. but i got this 
```
`11	0023	ldloc.2
12	0024	ldftn	instance void com.mytest.test.CHandler/'<OnCon>c__AnonStoreyA8'::'<>m__86'(int32, class [mscorlib]System.Collections.Generic.Dictionary`2<string, object>)
13	002A	newobj	instance void class [System.Core]System.Action`2<int32, class [mscorlib]System.Collections.Generic.Dictionary`2<string, object>>::.ctor(object, native int)
14	002F	stloc.0
`
```
I didn't find the real Console.WriteLine function call IL instruction.
how can i find the Console.WriteLine of  mscrolib lib code

**Comment by HoLLy-HaCKeR** [comment]
It's in another method. If you create lambda methods, delegates, or inline methods in C# they all get moved to their own separate method when compiled.

Judging by your code, you should look for `com.mytest.test.CHandler/'<OnCon>c__AnonStoreyA8'::'<>m__86'`.

**Comment by alan717** [comment]
@HoLLy-HaCKeR yes. but where is those code ? i didn't find the separate code  #section

> '<OnCon>c__AnonStoreyA8'::'<>m__86'

**Comment by HoLLy-HaCKeR** [comment]
You'll have to turn off some setting related to decompiling lambda expressions

**Comment by kieranmenor** [comment]
Was anything done about this? I'm facing the same problem. If I right-click inside a delegate and select "Edit IL Instructions...", it shows the disassembly of where the delegate is called from, rather than the disassembly of the delegate.

As @HoLLy-HaCKeR mentioned, if "Decompile anonymous methods/lambdas" is disabled, the generated class containing the method body if the delegate shows up and you can edit it. This seems like a workaround, though.

**Comment by 0xd4d** [comment]
@kieranmenor There's no fix yet. I plan on fixing this so it works with async methods, iterators, delegates/lambdas. The workaround today is to temporarily uncheck the async/iterator/lamda options.
