### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by rolandh** [0xd4d/dnSpy#702]
When decompiling some very large classes (130,000 lines) the x86 version gets an out of memory exception. The x64 version is ok.

The issue is the executable is an x86 one so you constantly have to switch version to modify and debug. Is it possible to get the large memory aware flag to be set on the x86 version?

Can do this manually with the following command:
`editbin /largeaddressaware .\dnSpy-x86.exe`

**Comment by 0xd4d** [comment]
dnSpy-x86.exe should already have the large-address-aware bit set.

- Uncheck `Options -> Environment -> General -> Decompile a member's[....]`. It should only show the current method, so unless you step into a gigantic method, no OOM exceptions should be thrown

- Use dnSpy to edit the target exe so it becomes 64-bit or AnyCPU (64-bit preferred), or use a 64-bit loader exe that links to the target exe and invokes its Main() method. You'd then debug this loader with 64-bit dnSpy.

- Switch to IL language
