### ISSUE TITLE
Compare two DLLs for changes in code?

### ISSUE THREAD

**Issue by 4AsAnd1B** [0xd4d/dnSpy#703]
Given you have a old and a updated DLL how do you compare the two for changes with dnSpy or otherwise?

**Comment by 0xd4d** [comment]
decompile old dll to 'old' dir (remember the project GUID)

decompile new dll to 'new' dir (use the same project GUID as above)

diff -u3 -r -N old/ new/ > diff.txt

edit diff.txt
