### ISSUE TITLE
Anti-Debug

### ISSUE THREAD

**Issue by ComanGames** [0xd4d/dnSpy#704]
Hi man I am trying to write a Extension. For SycllaHide And it's a bit pain in the ass. Can you help a little bit please..

**Comment by 0xd4d** [comment]
I dont' see a question so I'm going to guess.

Export an instance implementing [this](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy.Contracts.Debugger/IDbgManagerStartListener.cs#L25). When it gets called you hook the events you need and modify the process memory/whatever it needs.

**Comment by ComanGames** [comment]
I just checked is it possible to contact with you.
And by the way .The tool is amazing the extensibility is awesome one.
Thank you so much.
Yeah I already did that.
But in very silly way.
`	[Export(typeof(IDbgManagerStartListener))]
	sealed class DebugStart:IDbgManagerStartListener {
		public static SynchronizationContext main;
		public static DbgManager dbg;
		public void OnStart(DbgManager dbgManager) {

			dbg = dbgManager;
			 main = SynchronizationContext.Current;
			dbgManager.DelayedIsRunningChanged += (sender, args) => { ShowCountOfProcesses(dbgManager); };
		}

		private static void ShowCountOfProcesses(DbgManager dbgManager) {
			if (dbgManager?.IsRunning == true && dbgManager.Processes.Length > 0) {
				ulong pid = dbgManager.Processes[0].Id;

				Task.Factory.StartNew(() => { StartScyllaDide(pid); });
			}

			void StartScyllaDide(ulong proccessId) {
				string scyllaProg = @"C:\MyPograms\ScyllaHide\InjectorCLIx64.exe";

				ProcessStartInfo startInfo = new ProcessStartInfo();
				startInfo.FileName = scyllaProg;
				string dll = @"C:\MyPograms\ScyllaHide\HookLibraryx64.dll";
				startInfo.Arguments = $"pid:{proccessId} {dll}";
				startInfo.CreateNoWindow = true;
				Process.Start(startInfo);
			}
		}
	}`
And it work. The only problem. 
Breakpoints stop working.
So currently I am trying to write 
Based on generic example from Scylla..
But c++ is a bit pain in ass for me. 
So probably I actually wanted to tell you that I am working on Anti-anti-debug. And thank you for this awesome tool.
Also I plan develop few other extensions like string search( beacause your search is awesome. It was multiple times when I need to find specific text but incide of string).

**Comment by 0xd4d** [comment]
You should hook ProcessesChanged, and don't forget that dnSpy can debug multiple processes so the array can have a length > 1.

**Comment by paulnd** [comment]
@ComanGames I'll be very interested in your anti-anti-debug extension and hope that you plan to publish it. My C++ skills are very limited but willing to help with testing if required.

**Comment by ComanGames** [comment]
It would be a great. By the way my skills is also limited. So what I am actually doing. Is using ready c++ dll. And calling it's functions using C#. I will publish new brunch soon . When the betta will be ready for testing.

**Comment by paulnd** [comment]
@ComanGames, just wondering how are you getting on with this?
