### ISSUE TITLE
The "this" keyword does have a problem!!

### ISSUE THREAD

**Issue by softmgr** [0xd4d/dnSpy#705]
Select the menu "Edit Method", there are two cases here:
1. Class.var = this;
    The corresponding IL instructions is:
    ldarg.0
    stsfld     ......
    "Edit Method"->"Compile"->  error code: CS0029

2. Class var1 = Class2.Create(this);   //Class2 is a subclass
    The corresponding IL instructions is:
    ldloc.0
    ldarg.0
    call  ......
    stloc.s  V_1
    "Edit Method"->"Compile"->  error code: CS1503

Although you can replace the parameters with "null" and use the "Edit IL instructions" to solve it, it's very inconvenient.

For example:
    Class.var = null;
    IL instructions is:
      ldnull
      stsfld  ......
    The Edit IL instruction is:
      ldarg.0
      stsfld     ......

   OK......

I hope the new version is instinctive to solve this problem, thanks!

**Comment by 0xd4d** [comment]
You posted something similar earlier, #695, I'll close this since #365 is still open
