### ISSUE TITLE
Using System.ValueTuple with .Net 4.6 assembly when .Net 4.7 is installed

### ISSUE THREAD

**Issue by megafinz** [0xd4d/dnSpy#706]
I have an assembly that targets .Net 4.6 an uses `System.ValueTuple` as NuGet package. dnSpy fails to compile code that uses the `ValueTuple<…>`, it compains that `ValueTuple<…>` type is defined both in `System.ValueTuple` and `mscorlib`.

My guess is that I have .Net 4.7 version of `mscorlib` installed in GAC (either because of .Net 4.7 SDK installed or Windows 10 Fall Creators Update which includes .Net 4.7), so dnSpy try to use GAC version during compilation instead of .Net 4.6 version.

**Comment by 0xd4d** [comment]
You could remove all assemblies from dnSpy (File -> Close All) and then load all .NET 4.6.1 reference assemblies into dnSpy. If you have them installed, you should find them in eg. `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1` (There are some facades in `Facades` that you might need to add too). Then add the file you wish to edit.

**Comment by megafinz** [comment]
Yep, that works, thanks. Wasn't aware that dnSpy resolves references this way.
