### ISSUE TITLE
I can not edit the method in the latest version 4.5.2

### ISSUE THREAD

**Issue by rhinoku** [0xd4d/dnSpy#707]
Hello everyone. I am new to this use of the program. I have used previous versions and had no problem. After I updated to the latest version and tried to edit the method, it appears in red and does not let me compile. I try to make a mod menu for a game. I thank everyone for your attention
![dnspy](https://user-images.githubusercontent.com/20838710/35364106-56b58106-013b-11e8-8894-2faf284665c3.png).
I already tried to write them manually, but they do not appear either. (in old versions, yes, but I deleted them)

**Comment by alan717** [comment]
You didn't import the red color lib file.
just import those red color file will be ok .

**Comment by 0xd4d** [comment]
The file looks obfuscated. There's probably one or more files that get decrypted and loaded at runtime. You can debug it and check the modules window, and dump any files that have InMemory = Yes.

**Comment by 0xd4d** [comment]
Or the other files it needs aren't in the same folder. Just load all files in the Managed folder into dnSpy.

**Comment by rhinoku** [comment]
thank you brother, you have helped me. a thousand thanks to you and your great tool.
