### ISSUE TITLE
Add C# code but doesn't work well.

### ISSUE THREAD

**Issue by alan717** [0xd4d/dnSpy#709]
I add some C# code below.
`
	 Dictionary<string, string> dictionary = Json.Deserialize(result) as Dictionary<string, string>;
					Logsystem.DEBUG(dictionary["status"]);
					Logsystem.DEBUG(dictionary["data"]);
                                        Https_Post(dictionary["Resp"]);
`
but when i run the save code ,i got this .
`
2018-01-27 21:05:13:225 Debug:JsonParse   at com.example.json.parse (UInt32 df, System.String result) [0x00000] in <filename unknown>:0 
`

I think this compile doesn't support compile    Action<Dictionary<string, string>>(this.jsondata)&
Dinary data struct code & delegate  code.

 Who has met this situation? thanks.

**Comment by 0xd4d** [comment]
Contact the developer of that JSON library and file a bug report.

**Comment by alan717** [comment]
i did a mistake.the right log record is this.
my code is this 

> public static void ExecCallback(uint id, string result)
> {// the result is a right json string .
>    ........ 
>   ........
>Dictionary<string, string> dictionary = Json.Deserialize(result) as Dictionary<string, string>; Logsystem.DEBUG(dictionary["status"]); Logsystem.DEBUG(dictionary["data"]); 
    


>  at com.my.test.Interface.ExecCallback (UInt32 callId, System.String result) [0x00000] in <filename unknown>:0 
>
 above this . I mean the the Dictionary data structure  doen't recompile the right position in the dll .
the json lib work well . I can use it very well .  if you doesn't trust me ,you can try compile a dll contain the Dictionary  code ,and try to edit it the var .run it and look what happen . my english is not well .but i try to explain my situation .it not a JSON lib question .
 
thank you for your patience

**Comment by 0xd4d** [comment]
Use the debugger to debug it.
