### ISSUE TITLE
collapsible panels

### ISSUE THREAD

**Issue by salafsoft** [0xd4d/dnSpy#71]
Is it possible to make the panels collapsible / dockable? When I am debugging I usually want the stack trace and locals windows visible, however its not possible to have both side by side or to collapse one. It would be a nice feature if it was possible. Thanks.

**Comment by 0xd4d** [comment]
Something like this?

![pic1](https://cloud.githubusercontent.com/assets/1060731/12577173/00899904-c419-11e5-91df-7fcdbfcfddc7.png)


If so, use the latest source code.

**Comment by salafsoft** [comment]
Yes that would solve the docking issue. You seem to be blessed with a big screen resolution, me however, not so. So this is when collapsing would come in handy, like in VS.

![capture](https://cloud.githubusercontent.com/assets/10601977/12577518/a348d558-c412-11e5-9d55-607568325891.PNG)

**Comment by 0xd4d** [comment]
With that screen size you can easily fit the locals and call stack on the bottom. The Assembly Explorer doesn't even have to be visible most of the time. If you need it, you can move it to the bottom, eg. ASM_EXPL | LOCALS | CALL_STACK. The ASM_EXPL doesn't need to be wide so would take up little space.

If you don't want the locals/call stack visible all the time, learn their keyboard shortcuts and press Shift+ESC to close them when you don't need them.
