### ISSUE TITLE
Chocolatey package outdated

### ISSUE THREAD

**Issue by matthiaslischka** [0xd4d/dnSpy#711]
Hi,
the current [chocolatey package](https://chocolatey.org/packages/dnspy) is v. 3.0.2.0. The current release version here on github is 4.5.2.

Any plans to update the chocolatey package? Is it even managed by you? Not sure.
BR Matthias

**Comment by 0xd4d** [comment]
I'm not the maintainer of it.

**Comment by jimdi** [comment]
@matthiaslischka https://chocolatey.org/profiles/saneki
