### ISSUE TITLE
[Scripting] Instance.Resolve<dnSpy.Contracts.TreeView.ITreeNodeDataProvider>()

### ISSUE THREAD

**Issue by wangzq** [0xd4d/dnSpy#712]
Is it supported now to access the currently selected tree node from C# Interactive?

I am trying out `Instance.Resolve<dnSpy.Contracts.TreeView.ITreeNodeDataProvider>()` but it fails because there are two implementations for the interface:
```
Expected 1 export(s) with contract name "dnSpy.Contracts.TreeView.ITreeNodeDataProvider" but found 2 after applying applicable constraints.
```

Thanks

**Comment by 0xd4d** [comment]
Try IDocumentTreeView

**Comment by 0xd4d** [comment]
BTW, it has to be accessed on the UI thread so use the UI() method.
