### ISSUE TITLE
Edited IL instructions not running

### ISSUE THREAD

**Issue by ianling** [0xd4d/dnSpy#717]
I am using the "Edit IL Instructions" feature on Windows, version 4.5.2 (x64).

I am editing the IL instructions in a DLL loaded by the program I am debugging.

I am able to edit the IL without any issues. I then restart the program I am debugging, but by examining the breakpoints and watching the call stack, I see that the problem is still executing the unedited version of the instructions, ignoring the changes I made.

Did I miss a step, or is this a bug?

**Comment by 0xd4d** [comment]
Save the file first.
