### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by halokaya67** [0xd4d/dnSpy#722]
I want to help this project by translating it into turkish. I'm turkish and 25 years old. I'm working as an english teacher in a school. I think i can help. Please just show me which file should i translate and you will see. You won't regret because i take my job serious.

**Comment by riQQ** [comment]
See https://crowdin.com/project/dnspy

**Comment by 0xd4d** [comment]
The Turkish translation is at 88% at the moment, so it's not much left before it can be added to this repo.

**Comment by halokaya67** [comment]
Ok thnx for your attention. i see it's almost finished.

**Comment by 0xd4d** [comment]
It's at 87% now, used to be 88%. This is not what I expected. :)

Seems like @halokaya67 didn't have time to add any translations.
