### ISSUE TITLE
Can`t find in menu "Call Stack", "Thread", "Modules"

### ISSUE THREAD

**Issue by Reriuqni** [0xd4d/dnSpy#728]
Hi,
First, thank for your great work!

I download source, compiled it in VisualStudio  2017 Community. Than start dnSpy, dubug proramm, but I can`t see in "Debug" menu "Call Stack", "Thread", "Modules" https://prnt.sc/iegv9g
Tell me please, how I can see "Call Stack", "Thread", "Modules". Like this image https://prnt.sc/iefill

**Comment by 0xd4d** [comment]
Check the `Windows` sub menu.

**Comment by Reriuqni** [comment]
Not this?
[http://prntscr.com/ieh0wx](url)

**Comment by 0xd4d** [comment]
No, it's `Debug` -> `Windows` -> `Call Stack`

**Comment by Reriuqni** [comment]
Shame on me
This is simple
Where is my eyes
Thank you!
