### ISSUE TITLE
Internal debugger error

### ISSUE THREAD

**Issue by davmys** [0xd4d/dnSpy#733]
Have the same problem as #572 
After dumping the second stage of a .NET malware packed with ConfuserEx I have no locals vars during the debugging session, but only a generic "Internal debugger error".
( I've desperately tried to add manually the local vars but apparently it didn't make the trick )

Assuming that I'm not doing something wrong during the dump ( and I am 90% confident that I'm not ), are there any additional information regarding possible causes of this problem in order to try to fix this by myself? ( the final answer of the mentioned closed issue is not so clear to me ) 

Thanks guys!

**Comment by 0xd4d** [comment]
Are you using the latest build?

> the final answer of the mentioned closed issue is not so clear to me 

You should disable all BPs set in decrypted methods before you restart the program. These BPs can be enabled once the methods have been decrypted.

**Comment by 0xd4d** [comment]
Does it also show some HR error code, eg. 0x8012345 or do you only see "Internal debugger error"?

**Comment by davmys** [comment]
Hi 0xd4d, yeah I'm using the latest build.
I've tried to disable all the BPs before restarting but nothing, I'm going to do further investigation later.
Only "internal debugger error", no HR code.
Do you have any clue about the direction to take to resolve this problem? I mean the reasons why it possibly fails. 

Also, you want to see the sample? Maybe I'm doing something terribly wrong without knowing.

**Comment by 0xd4d** [comment]
You could debug dnSpy and catch all exceptions it throws (see the exceptions window) and paste the callstack when an unexpected exception is thrown.

**Comment by davmys** [comment]
Did it, but I had some problems during the startup for unknown reasons. 
Will try again this evening.

**Comment by 0xd4d** [comment]
Also try the latest build, it has an updated app.config file. Perhaps you don't have .NET Framework 4.7.1 installed, in which case you could get errros like this.

**Comment by davmys** [comment]
Ok @0xd4d , using the latest build with the updated .NET Framework did the trick: I manage to debug dnspy and have this exceptions:

Exception thrown: 'System.BadImageFormatException' in dnlib.dll
06:30:45.279 Additional information: Invalid IMAGE_COR20_HEADER.cb value
06:30:45.294 Exception thrown: 'System.BadImageFormatException' in dnlib.dll
06:30:45.294 Additional information: Invalid IMAGE_COR20_HEADER.cb value
06:30:45.326 Exception thrown: 'System.BadImageFormatException' in dnlib.dll
06:30:45.326 Additional information: Invalid IMAGE_COR20_HEADER.cb value

Followed by:

06:30:46.185 Exception thrown: 'System.InvalidOperationException' in dnSpy.Debugger.DotNet.x.dll
06:30:46.185 Additional information: Operation is not valid due to the current state of the object.


Will investigate this.

**Comment by 0xd4d** [comment]
`Invalid IMAGE_COR20_HEADER.cb value` means that the `cb` value is less than 0x48, it's probably 0, in which case it's not a .NET file or the obfuscator overwrote the value with 0.

> I have a new internal error: error CS1525: Invalid expression term '<'

It's possible that it tries to parse the "expression" `<error>`.

> 06:30:46.185 Exception thrown: 'System.InvalidOperationException' in dnSpy.Debugger.DotNet.x.dll

Could be related to the previous `IMAGE_COR20_HEADER.cb` error. Break on `System.InvalidOperationException` and you should see which method and statement it is.

**Comment by davmys** [comment]
Gotcha, solved.
Problem was related to the obfuscation methods called inside the cctor.
Now I have all the variables.

Thanks!

**Comment by longlostbro** [comment]
@davmys I am having the same Invalid IMAGE_COR20_HEADER.cb issue. What did you do to fix it?

**Comment by JemoGlemo** [comment]
@davmys Can you please explain more? I've same issue

**Comment by quangnv97** [comment]
Can you please explain more???? @davmys  @0xd4d
