### ISSUE TITLE
Opening the "File", "View" or "Window" menus makes dnSpy from git freeze

### ISSUE THREAD

**Issue by wodim** [0xd4d/dnSpy#735]
![image](https://user-images.githubusercontent.com/1001553/36488126-fab7377a-1722-11e8-9dd9-402b25f666f8.png)

This only happens with the git version.

**Comment by 0xd4d** [comment]
How long does it hang?

What's the git version? Your own compiled binary?

**Comment by wodim** [comment]
It seemingly hangs forever. It's from AppVeyor, right now. 582ab6a

**Comment by 0xd4d** [comment]
Could be related to #734

Have you tried v4.5.3: https://github.com/0xd4d/dnSpy/releases

**Comment by wodim** [comment]
Yes, 4.5.3 works right.

**Comment by 0xd4d** [comment]
Could you try these builds:

https://ci.appveyor.com/project/0xd4d/dnspy/build/x.x.688

https://ci.appveyor.com/project/0xd4d/dnspy/build/x.x.685

**Comment by wodim** [comment]
Both of those freeze.

**Comment by 0xd4d** [comment]
I think this is related to #734, could you follow that issue instead so I don't have to post the same thing twice?

**Comment by wodim** [comment]
Looks like that guy is more experienced than I am with C# debugging, so I'll leave this issue here.

**Comment by 0xd4d** [comment]
But could you try the file, there's no debugging needed, just testing some builds.

**Comment by wodim** [comment]
I will, don't worry.
