### ISSUE TITLE
Something wrong with Local variable in Type

### ISSUE THREAD

**Issue by yzpopulation** [0xd4d/dnSpy#736]
![pic](https://user-images.githubusercontent.com/12810531/36541809-1167df7c-181a-11e8-8b01-e0f04b2320ff.PNG)
The Type real name is \u000F\u200A\u2001\u2002.

**Comment by 0xd4d** [comment]
The value you're seeing is the output of the properties `System.Type.Name` and `System.Type.FullName`. Those are strings and only a few characters are escaped. The decompiler escapes more characters than the value formatters.
