### ISSUE TITLE
(this) keyword (and reiterative) in IEnumarator

### ISSUE THREAD

**Issue by Dentrax** [0xd4d/dnSpy#737]
I know how the IEnumarator works, theoretically. Technically, the word "this." is right place. But it's complicated when you're doing a code review surf. The word "this." can be confusion with a variable within the current Class that where IEnumarator Void function in same class or inheritanced class.

And the IEnumarator's variables are written in "< and >", and ending postfix with "__0, __1, etc." from compiler-generated logic.

The second problem is; The dilemma/reiterative problem on IEnumarator, If it tries to reach the current Class. For example: Current Class have a var like: m_test, If I wan't to modify/access that var in the some code scope like delegate{...}, this keyword dilemma/reiterative problem occur.

It's breaking code readability and it doesn't look good. 

Testing with:
dnSpy v4.5.2 (x64)
Unity's Mono-AssemblyCSharp.dll

Image:

![uuuuuuuuuuuu](https://user-images.githubusercontent.com/16493751/36600935-cb185712-18c4-11e8-9edc-90eef8053fef.png)

(If not showing up: https://i.hizliresim.com/oOX0JX.png) @0xd4d

**Comment by 0xd4d** [comment]
It's a decompiler bug and can't be fixed unless you post some files.

Related: #694

**Comment by Dentrax** [comment]
If you mean ILCode:
-First: https://paste.ee/p/0ZqL6
-Second: https://paste.ee/p/3KVN8 
@0xd4d

**Comment by Dentrax** [comment]
Sure.
First CS: https://paste.ee/p/mJNgG
First IL: https://paste.ee/p/AbusQ

Second CS: https://paste.ee/p/b8CMK
Second IL: https://paste.ee/p/xJFAa

@0xd4d

**Comment by 0xd4d** [comment]
I need the assembly and all assemblies it depends on directly or indirectly (i.e., everything in the `Managed` folder). Also the names of the classes shown in the pictures.

**Comment by Dentrax** [comment]
Here is another assembly file that uses the same logic. This file belongs to the MergedIt! v1.6.4 game. I've written the location of this problem inside the file that name called README.txt.

MediaFire: http://www.mediafire.com/file/5lkwm20y7s8sp93/Merged.It_1.6.4.rar
(Base64 Link: aHR0cDovL3d3dy5tZWRpYWZpcmUuY29tL2ZpbGUvNWxrd20yMHk3czhzcDkzL01lcmdlZC5JdF8xLjYuNC5yYXI=)
@0xd4d
