### ISSUE TITLE
Export project: sort attributes

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#743]
I'd like to ask for a feature: 
during decompiling (and following export to project)
it'd be very convenient to have attributes sorted in some predefined order.

This will allow to easily compare exported projects and find the differences in between.

The current issue is that attributes might be written in a different order.
example:
http://prntscr.com/ij6krz

**Comment by 0xd4d** [comment]
There's a 'sort CAs' option in decompiler settings.

**Comment by greenozon** [comment]
Worked like a charm!
thanks a lot

One more idea/question:  I've observed just 1 case that in one project in case of multiple inheritance there was 1 order of base classes/interfaces, in another proj - different order.

Not sure if it worth spending your attention, just FYI
