### ISSUE TITLE
Option Request: Variable Locations for Text Editor Window

### ISSUE THREAD

**Issue by Dentrax** [0xd4d/dnSpy#744]
By default, variables are always at the bottom. There is no feature that I have control location manually. 

For Example: (such a feature can be added)
-Variable Location: Top, Bottom, After the constructor, etc.

![const](https://user-images.githubusercontent.com/16493751/36633790-60443508-19ac-11e8-9ae1-c3627afa663d.png)

(If not showing up: https://i.hizliresim.com/5DaW4L.png) @0xd4d

dnSpy v4.5.2 (x64)

**Comment by 0xd4d** [comment]
See decompiler settings
