### ISSUE TITLE
Option Request: Auto-Collapse-Control for Assembly Explorer Window

### ISSUE THREAD

**Issue by Dentrax** [0xd4d/dnSpy#745]
When I click on an object on the Assembly Explorer Window, it automatically expands. I don't like this feature and it's not handy. 
Could you add a Option in Settings Window to control this feature manually? If the feature is turned off, auto-expand should not work (needs to press the expand button next to it), else yes. I think it might be handy. :)

![cnam](https://user-images.githubusercontent.com/16493751/36633734-a7353fd0-19ab-11e8-8e7d-c1e5ec293db4.png)

(If not showing up: https://i.hizliresim.com/4aj624.png) @0xd4d

dnSpy v4.5.2 (x64)

**Comment by 0xd4d** [comment]
`View` -> `Options` -> `Assembly Explorer` - `Single-click expands nodes`
