### ISSUE TITLE
Add ability to replace multiple bitmap resources from a directory of resources with the same name

### ISSUE THREAD

**Issue by ClairelyClaire** [0xd4d/dnSpy#747]
Suggestion:

If an application uses image resources for text UI elements (like buttons and on-screen information), it would be great if dnSpy could replace all the bitmap resources in the selected program with a directory containing new resources of the same name.

I've been localizing a Japanese application to English, and there are nearly 500 images containing text that need to be replaced...it's slightly tedious.

**Comment by 0xd4d** [comment]
Doesn't this work for you:

- In the TreeView: Select all resources files you wish to remove and press delete
- Right-click Resources node and pick "Create File Resource..." and select all 500 files you want to add
