### ISSUE TITLE
dnSpy shows `vbCrLf ` instead of `\r\n` in VB

### ISSUE THREAD

**Issue by klukule** [0xd4d/dnSpy#748]
dnspy shows in VB mode `..." & vbCrLf & "...` instead of `...\r\n...` which probably also means that `vbCr` and `vbLf` are not "working" too

**Comment by 0xd4d** [comment]
VB doesn't have any string escape characters like C#

**Comment by klukule** [comment]
oh, funny it worked for me... it must be compiler thingy then...

**Comment by 0xd4d** [comment]
MS VB prints `Console.WriteLine("hello\r\nthere")` as the literal string `hello\r\nthere`

**Comment by klukule** [comment]
hmmm ok... it is probably because I'm using WinForms
