### ISSUE TITLE
Turn off generation of metadata comments in disassembled source

### ISSUE THREAD

**Issue by ActivistInvestor** [0xd4d/dnSpy#756]
I was wondering if there is a way to disable generation comments above each member showing metadata. For example:

```
// Token: 0x06000386 RID: 902 RVA: 0x000143A4 File Offset: 0x000125A4
protected override void WndProc(ref Message m)
{
   bool flag = m.Msg == 28929;
   if (flag)
   {
      m.Result = new IntPtr(1);
   }
   else
   {
      base.WndProc(ref m);
   }
}
```

The comment is generated for every member, and I would like to know if there is way to disable that.

Thanks in advance.

**Comment by ActivistInvestor** [comment]
Never mind, I found the setting.

**Comment by BullyWiiPlaza** [comment]
This is the option to disable by the way:
`Show tokens, RVAs and file offsets`

![image](https://user-images.githubusercontent.com/7620135/44301937-1fa52e00-a320-11e8-8496-9c7ef0f4eaf0.png)
