### ISSUE TITLE
Commandline option for attaching on existing pid

### ISSUE THREAD

**Issue by medoni** [0xd4d/dnSpy#757]
Is there a commandline option to automatically attach on existing pid?

I want to use dnspy as my default debugger. registry value:

HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AeDebug

**Comment by 0xd4d** [comment]
That key is for native debuggers, you don't want dnSpy to start whenever some native app crashes.

**Comment by medoni** [comment]
> you don't want dnSpy to start whenever some native app crashes.
I'm a .NET only developer. I cannot debug a native App with Windbg or VS

This is my currently active debugger:
```
"C:\Windows\system32\vsjitdebugger.exe" -p %ld -e %ld
```
Options:
```
---------------------------
Visual Studio Just-In-Time Debugger
---------------------------
Microsoft (R) Visual Studio Just-In-Time Debugger
Copyright (C) Microsoft Corporation. All rights reserved.

usage: VsJITDebugger [options]

options:

-p [process id] 	: Attach a debugger to [process id]

[AppName] [Args]	: Launch the specified executable and attach a debugger

-?		: Show this dialog
---------------------------
OK   
---------------------------
```

On Windows Server 2016 where only Visual Studio 2017 Community Edition is installed (Amazon EC2)

My first try was to register dnspy as a vsjitdebugger
<img width="428" alt="bildschirmfoto 2018-03-05 um 20 28 48" src="https://user-images.githubusercontent.com/1647126/36995330-0d0110c8-20b4-11e8-8252-8be64d80f718.png">

But i didn't find the location where the debuggers are registered.

**Comment by 0xd4d** [comment]
> But i didn't find the location where the debuggers are registered.

Did you try `procmon`?

**Comment by 0xd4d** [comment]
Did you get this to work, otherwise the command line option is less useful (though not completely useless)

**Comment by wangzq** [comment]
It would be really useful to be able to attach to a process via command line, I often need to attach to a LinqPad query to debug a library it is using. If this is supported maybe we can also file a feature request to LinqPad to integrate with dnSpy automatically.

**Comment by 0xd4d** [comment]
`-p / --pid <pid>` (also `-pn / --process-name <name-supports-wildcards>`) can be used to attach to the process from the command line.

**Comment by 0xd4d** [comment]
DId you try the latest build or did you try v5.0.12?

**Comment by philippseith** [comment]
I tried 5.0.10 and 5.0.12. Both are not working but latest works. Thanks!
