### ISSUE TITLE
adwCleaner quarantines dnSpy

### ISSUE THREAD

**Issue by ActivistInvestor** [0xd4d/dnSpy#758]
Has anyone else had this happen?

I ran adwCleaner and it quarantined dnSpy:

```
# AdwCleaner 7.0.8.0 - Logfile created on Tue Mar 06 04:31:55 2018
# Updated on 2018/08/02 by Malwarebytes 
# Database: 02-08-2018.1
# Running on Windows 7 Ultimate (X64)
# Mode: scan
# Support: https://www.malwarebytes.com/support

***** [ Folders ] *****
PUP.Adware.Heuristic, C:\Program Files\dnSpy
Deleted: C:\Program Files\dnSpy

```

**Comment by 0xd4d** [comment]
Report it to them, there's no adware in it.

**Comment by 0xd4d** [comment]
Always get dnSpy from either the official releases page or the official build server:

https://github.com/0xd4d/dnSpy/releases

https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts

**Comment by 0xd4d** [comment]
Seems like you used an installer since it's in the programs folder, There's no official dnSpy installer and there most likely never will be. Unzip and double click is all you need, assuming you got the zip file from the above links in my previous post.

**Comment by ActivistInvestor** [comment]
There was no installer used. I created the folder in the Program files folder. The software was downloaded from the releases page.

**Comment by 0xd4d** [comment]
Then do what I wrote above, report it to them. If they don't fix it, it's scareware and you can't trust them.

**Comment by ActivistInvestor** [comment]
> Then do what I wrote above, report it to them. If they don't fix it, it's scareware and you can't trust them.

No time to write reports. It's their problem.

The ironic part of it is this blog post, where they use dnSpy to do an analysis:

[https://blog.malwarebytes.com/threat-analysis/2016/07/unpacking-yet-another-net-crypter/](url)

**Comment by 0xd4d** [comment]
Hilarious, you can't make this shit up.

Someone needs to tell them they've got dnSpy on their computer, so they can remove it. It's apparently adware.
