### ISSUE TITLE
edit class c# error CS0656

### ISSUE THREAD

**Issue by Rostam300** [0xd4d/dnSpy#759]
HI
thank you for your help
when i edit class c# and click Compile give me error
Missing compiler required member 'System.Security.Permissions.SecurityPermissionAttribute..ctor'
i can edit il but cannot edit class c# code i want to edit is not on il . so i have to edit class C#
plz can you help me it is so important for me 
how solve that error? 
i upload dll you can see that
in android.os-->inf-->.cctor here i want change bellow codes 

53 49 52 51 48 49 .............

// Note: this type is marked as 'beforefieldinit'.
	inf.Array = new int[]
	{
		53,
		49,
		52,
		51,
		48,
		49,
		49,
		50,
		48,
		58,
		65,
		65,
		70,
		76,
		66,
		95,
		71,
		102,
		69,
		81,
		48,
		56,
		78,
		45,
		49,
		121,
		56,
		77,
		107,
		67,
		118,
		95,
		54,
		121,
		97,
		76,
		117,
		51,
		122,
		65,
		54,
		48,
		53,
		106,
		89
	};

dnspy v4.5.3 x64
[android.os.zip](https://github.com/0xd4d/dnSpy/files/1786334/android.os.zip)
also when i exteract as cs it is not possibale to recompile 
plz help me

**Comment by 0xd4d** [comment]
Try this, copy and paste this class at the bottom of main.cs:

```C#
namespace System.Security.Permissions
{
	[AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Constructor | AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
	[ComVisible(true)]
	[Serializable]
	public sealed class SecurityPermissionAttribute : CodeAccessSecurityAttribute
	{
		public SecurityPermissionAttribute(SecurityAction action) : base(action)
		{
		}
	}
}
```

**Comment by Rostam300** [comment]
not work more error after do that
thanks for your fast reply
I upload DLL file
download and try modify that part I wrote
and tell me what hapend you can or not

**Comment by Rostam300** [comment]
i add android.os.dll and all of references to a zip file 
now you can edit android.os.dll
let me no if you can edit that code 
and tell me how 
if you modified . upload that plz
[assemblies.zip](https://github.com/0xd4d/dnSpy/files/1787155/assemblies.zip)

**Comment by 0xd4d** [comment]
Write down exactly what you've done step by step, show the code you added, and show the errors.

**Comment by Rostam300** [comment]
hi thank you for your time
I open android.is.DLL with dnspy 
and go to android.os --> inf --> .cctor
and click on .cctor use edit class C# or edit method to edit code after that it is the original code

// Note: this type is marked as 'beforefieldinit'.
inf.Array = new int[]
{
53,
49,
52,
51,
48,
49,
49,
50,
48,
58,
65,
65,
70,
76,
66,
95,
71,
102,
69,
81,
48,
56,
78,
45,
49,
121,
56,
77,
107,
67,
118,
95,
54,
121,
97,
76,
117,
51,
122,
65,
54,
48,
53,
106,
89
};

and for example I edit 53, to 43,
and click compile
and give me this error

Missing compiler required member 'System.Security.Permissions.SecurityPermissionAttribute..ctor'

so how solve this 
sorry for my bad english
can you test it I uploaded files
it is a bug or something else
thank you again

**Comment by 0xd4d** [comment]
You either didn't show the whole code (ctrl+A and ctrl+c) or you didn't do what I wrote above, https://github.com/0xd4d/dnSpy/issues/759#issuecomment-370939874

**Comment by 0xd4d** [comment]
Here's an updated attribute with the required property. Paste it at the end of `main.cs`

```C#
namespace System.Security.Permissions
{
	[AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Constructor | AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
	[Serializable]
	public sealed class SecurityPermissionAttribute : CodeAccessSecurityAttribute
	{
		public SecurityPermissionAttribute(SecurityAction action) : base(action)
		{
		}

		public bool SkipVerification
		{
			get
			{
				return false;
			}
			set
			{
			}
		}
	}
}
```

**Comment by Rostam300** [comment]
ohhh my god . thank you my friend
that work best
thank you for your hard work 
really good work 
thank you again
I follow your github keep working coz of people

**Comment by johnkittz** [comment]
this solved the error but produced another "CS1729" it says "Codeaccesssecurityattribute does not contain a constructor that takes 1 argument.

**Comment by Rostam300** [comment]
johnkittz can you tell more about your problem? whta do you want to do? it is beter to open new issuse and write about yor problem completly . i hope can help you

**Comment by liuzhifeng** [comment]
hello,I can't find where to modify main.cs

**Comment by riQQ** [comment]
Use the action `Edit Class (C#)...` in the context menu. The 'file' displayed is named main.cs.
