### ISSUE TITLE
newly created breakpoints not hit after initial resume

### ISSUE THREAD

**Issue by salafsoft** [0xd4d/dnSpy#76]
I have an app that behaves strangely when debugging with dnSpy, ie. I would launch it, it hits the break-point, then I would resume. After a while I would identify a place to break-point but it would never hit that again, unless I restarted the application with debugging.

I have recorded the odd behavior, please see this video:
https://drive.google.com/file/d/0B6N5Vxp6CjC1VHRwbjJka2RDMWc/view?usp=sharing

IL when not hit:
![il bp not hit](https://cloud.githubusercontent.com/assets/10601977/12579560/bc24be6c-c420-11e5-93f3-3ae74299f31f.PNG)

IL when hit:
![il bp hit](https://cloud.githubusercontent.com/assets/10601977/12579566/d080c856-c420-11e5-84c0-3f855501f8ab.PNG)

It would be pretty hard for you reproduce this since this application requires a lot of files / installation etc. If you are interested however we could try it. The full application can be downloaded from XXX

**Comment by 0xd4d** [comment]
I can't reproduce this because the XP VMWare image I use doesn't show any buttons at all so I can't even click the about button, it's not there.

Is there another way to trigger this without having to click anything in the program?

You can also try removing your dnSpy.xml file and see if that helps, could possibly be some setting that is enabled that shouldn't be enabled.

**Comment by salafsoft** [comment]
Ok good news, I can replicate the problem using a very simple winforms app, with a single button, and a "hello world" message.

https://drive.google.com/file/d/0B6N5Vxp6CjC1akg5Rjl2VDQyNGs/view?usp=sharing

After the initial run and resume, just BP on the DoStuff() method, and see that the next time the button is clicked the BP is not hit.

![image](https://cloud.githubusercontent.com/assets/10601977/12615949/8bc6c2b6-c500-11e5-9a71-152655577fce.png)

I am using the latest CI build.

**Comment by 0xd4d** [comment]
It should be fixed now.

**Comment by salafsoft** [comment]
Tested fixed. many thanks!
