### ISSUE TITLE
Edit code: Automatically add required attributes the compiler needs

### ISSUE THREAD

**Issue by 0xd4d** [0xd4d/dnSpy#761]
Some Unity mscorlibs don't have the required ctors, so the compiler will fail to compile the code.

Related #699, #759, #788, #826

Example errors:

Severity|Code|Description
--------|----|-----------
Error|CS0656|Missing compiler required member 'System.Security.Permissions.SecurityPermissionAttribute.SkipVerification'
Error|CS0656|Missing compiler required member 'System.Security.UnverifiableCodeAttribute..ctor'
Error|CS0656|Missing compiler required member 'System.Security.Permissions.SecurityPermissionAttribute..ctor'
Error|CS0656|Missing compiler required member 'System.Runtime.CompilerServices.CompilationRelaxationsAttribute..ctor'
Error|CS0656|Missing compiler required member 'System.Runtime.CompilerServices.RuntimeCompatibilityAttribute..ctor'

**Comment by 0xd4d** [comment]
Workaround:

- Close all files (or open a new dnSpy instance)
- Open .NET Framework's `mscorlib.dll` (`File` -> `Open from GAC`, or `Ctrl+Shift+O`) and search for `mscorlib`. Open v4.0.0.0.
- Search for the attribute it complains about, eg. `CompilationRelaxationsAttribute`
- Copy the class, namespace and using statements
- Close all files
- Load your files again and edit
- Copy and paste the attribute without the using statements and paste it at the end of `main.cs`
- Copy and paste the using statements at the top of `main.cs`

**Comment by m1m2m3mr** [comment]
I came across a game that I got this error but this workaround doesn't work while other games work with this workaround
```
Severity	Code	Description	File	Line
Error	CS0656	Missing compiler required member 'System.Security.Permissions.SecurityPermissionAttribute..ctor'	
```

**Comment by 0xd4d** [comment]
Could you attach the files here?

**Comment by m1m2m3mr** [comment]
Here is the file. Only modify Assembly-CSharp
[Managed.zip](https://github.com/0xd4d/dnSpy/files/2036329/Managed.zip)
