### ISSUE TITLE
Compiler is having conflicts with itself in the console

### ISSUE THREAD

**Issue by RobbieW69** [0xd4d/dnSpy#762]
Error	CS0029	Cannot implicitly convert type 'Inventory [main.cs(8)]' to 'Inventory [C:\Users\Robbie\Desktop\SCP\SCPSL_Data\Managed\Assembly-CSharp.dll]'	main.cs	69

Conflicting with the same class?
Newest version by the way.

**Comment by RobbieW69** [comment]
![dnspy_2018-03-09_13-22-58](https://user-images.githubusercontent.com/20403126/37225686-0557fa62-239d-11e8-903b-025b36de03da.png)

**Comment by RobbieW69** [comment]
This is a default class, untouched by me, so why doesn't it compile properly?

**Comment by 0xd4d** [comment]
Looks like the MethodSpec table isn't updated. Could you attach the files here.

**Comment by RobbieW69** [comment]
Of the game or of DNSPY?

**Comment by 0xd4d** [comment]
The game files (all files in the `Managed` folder).

**Comment by RobbieW69** [comment]
[Managed.zip](https://github.com/0xd4d/dnSpy/files/1798341/Managed.zip)

**Comment by 0xd4d** [comment]
I can't reproduce this. Make sure you're using v4.5.3 or latest build.

**Comment by RobbieW69** [comment]
Thank you, I was actually running the wrong version.
