### ISSUE TITLE
Mono Bleeding Edge dll's

### ISSUE THREAD

**Issue by RepublicofTexas** [0xd4d/dnSpy#763]
Hi! I want to know if it is possible to compile the Mono Bleeding edge (mono-2.0-bdwgc.dll) DLL's for debugging Unity games? Thanks!

**Comment by 0xd4d** [comment]
See https://github.com/0xd4d/dnSpy-Unity-mono it has instructions on how to patch some random Unity/Mono branch

**Comment by RepublicofTexas** [comment]
Oh ok nice, do I just do all of that with mono bleeding edge?

**Comment by 0xd4d** [comment]
See the README, it contains all instructions needed for the normal Uinty branches. I've not tested bleeding edge branches.

**Comment by RepublicofTexas** [comment]
Ah ok, thanks for the help!

**Comment by 0xd4d** [comment]
I've updated the compiled binaries with the 2017 and 2018 MBE files, see the releases page.
