### ISSUE TITLE
invalid export to project

### ISSUE THREAD

**Issue by Rostam300** [0xd4d/dnSpy#766]
hi first thanks you for your time
when i export dll to project as vs2107 or vs2015 . vs cannot find references and target framework
there is no frame work to use
![2018-03-14 05_21_46-](https://user-images.githubusercontent.com/34222016/37402479-02c06a00-2749-11e8-8406-06ae927f2082.png)

even cannot add references when i add them this is no luck
i will upload screen shot
win 10 latset
dnspy 4.5.3 x64
.net 4.7.1
you can use my dll than upload to #759 for test
vs2107 full installed about 150Gb

**Comment by 0xd4d** [comment]
This is a VS question. You can edit the csproj file yourself or recreate it. You probably need some Android SDK installed etc.

**Comment by Rostam300** [comment]
thank you 
soory for my bad
