### ISSUE TITLE
Local vars sorting

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#768]
A quick q: is it possible to add sorting into "Locals" - "Name" column?
it turns out that having hundreds (yes, real use case) it is a PITA to locate the required var...

sorting would be just a super cool feature that will treat pain :)

example vision: http://prntscr.com/isi9ay

**Comment by 0xd4d** [comment]
Check the debugger settings

**Comment by greenozon** [comment]
Thanks for tip!
it really there (the option to sort locals...)
but for the future if you plan to add sorting into different windows - that would be much more easier and more user friendly!
