### ISSUE TITLE
Can't export project, hit 260 chars limit in path

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#769]
In some mixed mode assemblies there might be tons of STL based variables that are having mangled very very long names.

when dnSpy tries to save such a file, it hit an OS limit, eg:

File creation failed (d:/test\[trimmed]\-CppImplementationDetails-\$ArrayType$$$BY01V-$DynArray@V-$value_with_info@V-$CCoordinate3@M@[trimmed .... very very long mangled string here....]@@, 
Exception message: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

Expected behavior - well, somehow write the file to disk... maybe trim if filename too long

**Comment by 0xd4d** [comment]
I thought .NET Framework had support for longer filenames now. Of course, this should still be fixed since there's no reason for dnSpy to create filenames with 1000 characters in them.

**Comment by kdrapel** [comment]
@0xd4d I worked on a project where we had file functions on long names, we also thought that .NET was supporting extended length according to the documentation but that's not the case, we quickly ran into these limitations. We had to rely upon AlphaFS library to improve this. (https://github.com/alphaleonis/AlphaFS).

**Comment by medoni** [comment]
https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/

**Comment by 0xd4d** [comment]
It's not enabled by default, nice MS. You have to add an app.manifest with the right thing in it, and add an app.config with the right options unless you target 4.6.2 or later, and you have to ask your users to start gpedit and enable the option. MS doesn't want you to use long filenames.

**Comment by greenozon** [comment]
.net isnot java. 
so file name must not be 1:1 as class name!
lets trim filenames > 260 :)

**Comment by greenozon** [comment]
Are there any plans with supporting (trimming?) too long names?
