### ISSUE TITLE
Load dependencies & drag-drop no longer working

### ISSUE THREAD

**Issue by salafsoft** [0xd4d/dnSpy#77]
In the latest build from CI.

- Attempting to drag and drop a .dll or .exe file into the Assembly Explorer is no longer working, I just get a (/) no entry style cursor.
- There used to be a right click on the Assembly Explorer list items to load dependencies to quickly load related .dlls, but it no longer exists.

Are these regressions or "as designed"?

**Comment by 0xd4d** [comment]
Drag and drop from explorer.exe works for me. What OS are you using? If you want to debug it yourself, set a BP [here](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/Files/TreeView/RootNode.cs#L53) and [here](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/Files/TreeView/RootNode.cs#L68) and see what happens.
