### ISSUE TITLE
Difficult to find how to search strings

### ISSUE THREAD

**Issue by idealpersona** [0xd4d/dnSpy#774]
I was interested in searching strings, and I looked wherever I could think of for it, but eventually got frustrated and gave up, assuming DNSpy didn't support this feature.  But it does, and it took someone pointing it out the solution to me weeks later to find out.  When using the "search assembly" feature, I had "all of the above" checked, and I assumed that meant "everything".  I didn't think to check that there was anything below "all of the above".  When have you ever taken a multiple choice exam and had anything below an "all of the above" answer?

This should be clarified in some way and/or there should be a additional menu item near "search assembies" (possibly with its own hotkey) that provides an alternate path to this action.

One option is mutually exclusive selectors for data and for symbols as values for the "Search for:" field, - e.g. a button that says "Number/String", and the selection box labeled "Symbols" with the existing selection box minus "Number/String".  "Symbols" seems an accurate term for the rest of the search criteria.

**Comment by 0xd4d** [comment]
>  When have you ever taken a multiple choice exam and had anything below an "all of the above" answer?

dnSpy isn't an exam. All of the above means exactly what it means. But yes, it seems to confuse people so should be changed. The whole UI should be updated, but I don't have time to do it yet, it's working well enough.

**Comment by idealpersona** [comment]
I understand.  I don't mean to be condescending; I really appreciate your work and I am just explaining the context behind that - in my opinion, very reasonable - assumption.  Is there anything you have in mind as far as a simple change that I could contribute to mitigate this problem for others, including any ideas I've suggested above or even more simply a note on the wiki?

**Comment by 0xd4d** [comment]
No-one reads the wiki. ;)

Searching for strings in method bodies is slower and requires more memory, but most people only want to search for types or member names, so strings aren't enabled by default.

**Comment by 0xd4d** [comment]
I've added a new issue, #778

**Comment by kdrapel** [comment]
I understand what @idealpersona is meaning and I also understand why you decided to put the string search at the very end. I think the confusion comes from the fact that this dropdown could be a checkable dropdown where the "all of the above" would check all items but the strings. This would also allow people to finetune what they want to search (field + property only for example).

**Comment by beppe9000** [comment]
maybe the string option could be removed and a "search strings and numbers" checkbox could be added next to the dropdown. If the checkbox is enabled the dropdown is disable, allowing users to understand you are now searching for strings and numbers.

ps. i think also having a checkbox for strings and one for numbers could be a cool idea (if you check both you search both)
