### ISSUE TITLE
Assembly Explorer Tree Node Expansion

### ISSUE THREAD

**Issue by ActivistInvestor** [0xd4d/dnSpy#780]
Assembly Explorer expands nodes on a click on any part of the node rectangle, which conflicts with multiple selection of assemblies (using the shift key).

It could be made to only expand when the arrow is clicked, as per windows treeview control.

**Comment by 0xd4d** [comment]
There's an option you can uncheck: `Options -> Assembly Explorer -> Single-click.......`

I've been considering turning it off by default.
