### ISSUE TITLE
OOM on Export to Project

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#782]
hit an OOM (Out Of Memory) case on assembly export to project
using latest release 4.5.3
issue observed on both x32 & x64 builds
x32 shown some error, x64 eat all the the RAM (8G) & started to kill swap :)

x64
http://prntscr.com/ivfhfr

x86
http://prntscr.com/ivfiae

........

**Comment by greenozon** [comment]
That might be an old decompiler engine.... 
why?
fact #1 
ILSpy version 3.0.1.3459   did it in 2 seconds like a charm
fact #2 - there are lots of errors like
An exception occurred when decompiling this method (06000459)
.....
   at ICSharpCode.Decompiler.Ast.AstMethodBodyBuilder.TransformByteCode(ILExpression byteCode)
....


inside some of *.cs produced by the dnSPy..

**Comment by 0xd4d** [comment]
Looks like a decompiler bug that's been fixed.

**Comment by greenozon** [comment]
Do you have plans to migrate to newer decompiler engine?
