### ISSUE TITLE
Replace the Extension system to short way

### ISSUE THREAD

**Issue by Dentrax** [0xd4d/dnSpy#785]
When I use an Extension-based static class, The dnSpy is been translating the long way and reading is hard. Exactly how? Like that:

Original Code:

```csharp
this.m_imgMain.DOFade(1f, 0.7f).SetDelay(0.3f);
this.m_topFrame.DOLocalMoveY(this.m_topShownY, 0.5f).SetDelay(0.3f);
this.m_bottomFrame.DOLocalMoveY(this.m_bottomShownY, 0.5f).SetDelay(0.3f).OnComplete(delegate {
     this.m_isAnimating = false;
     this.m_isShowing = true;
     if (onDone != null) onDone();
});
```

Decompiled Code:

```csharp
TweenSettingsExtensions.SetDelay<Tweener>(ShortcutExtensions46.DOFade(this.m_imgMain, 1f, 0.7f), 0.3f);
TweenSettingsExtensions.SetDelay<Tweener>(ShortcutExtensions.DOLocalMoveY(this.m_topFrame, this.m_topShownY, 0.5f, false), 0.3f);
TweenSettingsExtensions.OnComplete<Tweener>(TweenSettingsExtensions.SetDelay<Tweener>(ShortcutExtensions.DOLocalMoveY(this.m_bottomFrame, this.m_bottomShownY, 0.5f, false), 0.3f), delegate
{
     this.m_isAnimating = false;
     this.m_isShowing = true;
     if (onDone != null)
     {
          onDone();
     }
});
```
Unity's Mono with DOTween (https://github.com/Demigiant/dotween)
Is there a setting for me to do it this way? And which class is doing this? (I mean auto Extension-class placement)

**Comment by 0xd4d** [comment]
Search the decompiler code for ExtensionAttribute, all extension methods should have this attribute.

**Comment by Dentrax** [comment]
Well, I don't know how to do that. The decompiler code so complex. Can you add a feature for this? (like a checkbox)

**Comment by 0xd4d** [comment]
I don't know how a checkbox could solve this problem.

You can debug the decompiler code responsible for this: https://github.com/0xd4d/ILSpy/blob/bf35674abf2936b7d9785855c4b8da04d7c1a90a/ICSharpCode.Decompiler/Ast/Transforms/IntroduceExtensionMethods.cs#L45

There are a few checks there. If they fail, the static method isn't converted to an extension method call. Eg. if it can't resolve the method (it can't find the assembly), you'll see the above failure.

**Comment by 0xd4d** [comment]
Did you try it? I have a feeling this isn't a decompiler bug, it just can't find your assembly.

**Comment by 0xd4d** [comment]
I'll take the silence as a 'not a bug, assembly could not be found'
