### ISSUE TITLE
Enum incorrectly decompiled as a class

### ISSUE THREAD

**Issue by Kyopaxa** [0xd4d/dnSpy#787]
The following IL code:

```
.class public auto ansi MyNamespace.MyEnum
	extends [mscorlib]System.Enum
{
	// Fields
	.field public specialname rtspecialname int32 value__
	.field public static literal valuetype MyNamespace.MyEnum Value1 = int32(0)
	.field public static literal valuetype MyNamespace.MyEnum Value2 = int32(1)
}
```

Should be decompiled as this (It works ok with ILSpy, for example):

```
public enum MyEnum
{
	Value1 = 0,
	Value2 = 1
}
```

But it is instead decompiled as a class:

```
public class MyEnum : Enum
{
	public int value__;

	public const MyEnum Value1 = 0;

	public const MyEnum Value2 = 1;
}
```

This breaks the code, giving compiler errors when trying to modify it, since you can't inherit from Enum. Also all comparisons made against that enum are converted to literal ints, instead of using the enum literals, thus giving compiler errors when modifying the code too.

Checking other assemblies where enums are correctly decompiled, I found out that they contain a "sealed" keyword in the IL .class line. Thus in the example above, 

```
.class public auto ansi sealed MyNamespace.MyEnum
	extends [mscorlib]System.Enum

```
will decompile to enum correctly.

**Comment by 0xd4d** [comment]
Get the latest build: https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts

**Comment by Kyopaxa** [comment]
Checked with latest build. The issue is still reproducible.

I attach an example DLL file containing only the enum. It still decompiles as a class:

using System;

```
namespace MyNamespace
{
	public class MyEnum : Enum
	{
		public int value__;

		public const MyEnum Value1 = 0;

		public const MyEnum Value2 = 1;
	}
}
```

[Example.zip](https://github.com/0xd4d/dnSpy/files/1852225/Example.zip)

**Comment by 0xd4d** [comment]
I don't think you tested the latest build which was built 24 minutes ago.

**Comment by Kyopaxa** [comment]
I did download the right one, but I didn't use the right shortcut (I have both release and latest together...).

My apologies. The issue is fixed now.
