### ISSUE TITLE
CS1729

### ISSUE THREAD

**Issue by johnkittz** [0xd4d/dnSpy#788]
I was getting an error while trying to recompile a unity dll. I search for the error and found something in the issues section once I tried it it produced another error the error is "Codeaccesssecurityattribute does not contain a constructor which takes 1 argument"

my original problem was a system.securtiy.permissions compiler missing error

**Comment by 0xd4d** [comment]
Is this an Android game?

Could you attach the files? (all files in the `Managed` folder)
