### ISSUE TITLE
Feature Request: "Disassembly View" of JIT'ed code

### ISSUE THREAD

**Issue by hypeartist** [0xd4d/dnSpy#792]
The title actually says it. 
Something similir to:
[https://github.com/ashmind/SharpLab/blob/master/source/Server/Decompilation/JitAsmDecompiler.cs](https://github.com/ashmind/SharpLab/blob/master/source/Server/Decompilation/JitAsmDecompiler.cs)

**Comment by 0xd4d** [comment]
Implemented on master: call stack window, right click a frame
