### ISSUE TITLE
Unknown metadata streams not preserved correctly

### ISSUE THREAD

**Issue by 766F6964** [0xd4d/dnSpy#795]
The recently added functionality #791 to copy unknown metadata streams seems not to preserve the order.
The streams have a different order in the saved file compared to the original one. 
The output crashes because it tries to read from the custom metadata stream and can't find them, most likely because of the different order?

**Comment by 766F6964** [comment]
Sorry, I think my message was unclear. I updated it.
The target file doesn't read from the streams, it iterates them by parsing the PE.
The question is why the order of the streams isn't preserved when the target files is saved.

**Comment by 766F6964** [comment]
> The feature request said nothing about order of streams.

It stated exactly this in my first post.

> he recently added functionality #791 to copy unknown metadata streams seems not to preserve the order.
The streams have a different order in the saved file compared to the original one.

Anyway, is there a way to preserve the exact order of the custom streams?

**Comment by 0xd4d** [comment]
Your issue is not the feature request, unless you have multiple accounts. This one is: #791

Could you explain why you think the order is important? You don't even know why your application crashes. Debug it, figure out why it crashes.

**Comment by cawk** [comment]
Hello, we are both looking at the same file that is why his question follows from my feature request
the reason it crashes i dont know if you have ever looked at confuserex anti tamper stream reader, when the custom stream is added at the end the method to find it fails to find the custom stream however i made a temporary fix by changing 

otherHeapsEnd to just OtherHeaps

**Comment by 0xd4d** [comment]
The order of the old heaps should now be preserved, try the latest build.

**Comment by 766F6964** [comment]
Yes, order of the streams is now preserved correctly.
