### ISSUE TITLE
Problem with Save Module

### ISSUE THREAD

**Issue by AhmedZero** [0xd4d/dnSpy#797]
i have program i decompile it by de4dot and patch it using dnspy then i save it (Save Module) but i don't see any changes in Executable file  when i open it.
but if i debug it , the changes i made it work.
is it require to install Visual Studio to work well?

**Comment by AhmedZero** [comment]
i make sure it's the same file ... when i edit file , the size of the file is changed but the changes don't work.

**Comment by 0xd4d** [comment]
It's impossible to help since you haven't given enough info. Write down all the steps you do so someone can reproduce it.

**Comment by AhmedZero** [comment]
i discovered something, when i remove DLL from the folder , my changes is worked , when i undo that file, my changes don't work.

**Comment by AhmedZero** [comment]
thank you, i found the problem, it's from native Image :D .
