### ISSUE TITLE
Can't add Debug.WriteLine to assembly.

### ISSUE THREAD

**Issue by rolandh** [0xd4d/dnSpy#799]
I have tried modifying an assembly to add Debug.WriteLine to the assembly and pressing compile, the line is simply optimised out.

If I put Console.WriteLine the line is left there.

I added the following lines to the assembly however it still optimises it away.

`[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.DisableOptimizations | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue)]`

How can I ensure the Debug.WriteLine calls are not optimised away?

edit: Even editing my own assembly that has been built with full debugging information/pdb present I still can't add Debug.Writeline to it. I'm assuming the "compile" function treats it as release mode code?

edit2: If I add Console.Writeline and manually edit the MSIL changing it to Debug.WriteLine the code persists.

**Comment by 0xd4d** [comment]
The compiler optimizes the code (i.e., it's Release configuration and I don't define `DEBUG`), so all Debug.WriteLine() calls will be removed.

**Comment by rolandh** [comment]
Any way to modify this in the future?

If you use the IL editor you can add it in fine.

**Comment by 0xd4d** [comment]
Could you explain why you're adding Debug.WriteLine() calls? You could add tracepoints for instance. Or you could add Console.WriteLine() method calls, it should be visible in the console, or if it's a UI app, in the debugger's output window.

**Comment by rolandh** [comment]
I did try both trace and console however only debug.writeline showed up.

**Comment by 0xd4d** [comment]
Tracepoints should always work.

Console.WriteLine() is shown in the output window if you're using the latest dnSpy build or VS' debugger.

Trace.WriteLine() is similar to Debug.WriteLine() and only works if TRACE is defined.

**Comment by rolandh** [comment]
Ok it seems windoes 10 was caching the assembly and ignored ignoring my changes. After deleting all copies on my pc debug and console both work. I'm not sure why the first console dll worked. 

Thanks

**Comment by 0xd4d** [comment]
Is the file in the GAC? If so you need to regenerate it or you could perhaps change the MVID when saving the file https://github.com/0xd4d/dnSpy/issues/543

**Comment by rolandh** [comment]
It was in the ngen cache.

**Comment by rolandh** [comment]
Thanks for your help by the way. #543 helped confirm my issue.
