### ISSUE TITLE
All unicode chars support

### ISSUE THREAD

**Issue by TheProxyRE** [0xd4d/dnSpy#8]
it should support all asci chars like you see in this picture http://prntscr.com/7pvfvq names of types/methods ,etc.. its not problem when have char or 2 but when its bigger name like here http://prntscr.com/7pvhrs it could make a small problem remembering name of type/ method etc..

**Comment by 0xd4d** [comment]
ASCII chars are bytes 00 .. 7F, and shouldn't be shown without being filtered.

\uXXXX is used when the character most likely is a random char, or if it's a special char like CR or LF. Which character in the above pictures do you think should be shown as is and not as \uXXXX?

You don't need to remember the names of types, methods etc. Just use the Ctrl+D command (go to MD token) and paste the MD token of the thing you wish to go to.

**Comment by CodeShark-Dev** [comment]
It would be possible to add an option to choose it? Please and thanks.

**Comment by beppe9000** [comment]
I am unable to recompile a method that has such identifiers in it. Can those methods be supported?
