### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by li0nsar3c00l** [0xd4d/dnSpy#80]
It would be nice to select the assemblies dnspy will search in. sometimes looking through the clr assemblies is quite annoying.

**Comment by Alcatraz3222** [comment]
+1 would be pretty helpful

**Comment by SlowLogicBoy** [comment]
Like in Visual Studio
* Current Type
* Opened Types
* Current Assembly
* All Opened Assemblies

**Comment by 0xd4d** [comment]
It's now possible to limit the search to just the current file or to all loaded files that exist in the same folder as the current file, or to just search the current type. Searching in files in the GAC can also be disabled.
