### ISSUE TITLE
Strange hints when show some generic method(infinite recursion here?)

### ISSUE THREAD

**Issue by yyjdelete** [0xd4d/dnSpy#800]
See the image below.
1. Jump to any public method in `System.Linq.Queryable`;
2. Hover mouse on `Queryable.GetMethodInfo`;(And the same for `Provider.CreateQuery` in `System.Linq.Queryable.GroupBy`)

Tested with both `4.0.0`,`4.5.3` and the lastest build 5db21a93.

![image](https://user-images.githubusercontent.com/1819074/38169655-7ea787cc-35a2-11e8-8d2e-c18e94d8f401.png)
![image](https://user-images.githubusercontent.com/1819074/38169730-8e9e5686-35a4-11e8-89c8-b15ec656e127.png)

**Comment by 0xd4d** [comment]
Should be fixed in the latest build
