### ISSUE TITLE
compiler bug

### ISSUE THREAD

**Issue by Rostam300** [0xd4d/dnSpy#803]
hi thank you for your time
there is an compiler bug i want to know how fix it
i open this path in dll 
android.os.dll -> _0x4a5s6gasdg._0xa5s4asdg -> _0xas6f6sadgasg and open .cctor edti method c#
change decimal number code:
```C#
static _0xas6f6sadgasg()
{
	_0xas6f6sadgasg._0x5a4sfasf = new int[]
	{
		53,
		49,
		52,
		51,
		48,
		49,
		49,
		50,
		48,
		58,
		65,
		65,
		70,
		76,
		66,
		95,
		71,
		102,
		69,
		81,
		48,
		56,
		78,
		45,
		49,
		121,
		56,
		77,
		107,
		67,
		118,
		95,
		54,
		121,
		97,
		76,
		117,
		51,
		122,
		65,
		54,
		48,
		53,
		106,
		89
	};
```
change that number and add this code you told me for compile at the end 
```C#
namespace System.Security.Permissions
{
	[AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Constructor | AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
	[Serializable]
	public sealed class SecurityPermissionAttribute : CodeAccessSecurityAttribute
	{
		public SecurityPermissionAttribute(SecurityAction action) : base(action)
		{
		}

		public bool SkipVerification
		{
			get
			{
				return false;
			}
			set
			{
			}
		}
	}
}
```
compile is ok but after save dll size grow up a bit and problem is not the size problem is
that decimal number change to text and if you open dll with note editor or notepad
you can find decimal converted to text and after any edite old decimal code saved to dll so if i edite that decimal code 10 time and save it all them convert to text and save to dll and you can easly see them!
but in orginal dll cannot see them 
![bandicam 2018-04-03 13-43-40-933](https://user-images.githubusercontent.com/34222016/38274957-36df11cc-3745-11e8-9d5a-95f85d629f90.jpg)
as you can see in photo decimal converted to text and it is visibality
i will upload orginall dll and edited dll to check it plz help me i need to solve it as soon as posibale
i add read text for more info about problem 
sorry for my bad english
[assemblies.zip](https://github.com/0xd4d/dnSpy/files/1873342/assemblies.zip)

**Comment by Rostam300** [comment]
hi sorry may it is not a compiler bug but edited dll show text than i converted to decimal and use in dll even it is converted to text agin!
how i can fix it?

**Comment by Rostam300** [comment]
this decimal number referanced to this path on dll android.os.dll  -->  -  -->  <PrivateImplementationDetails> 
if remove this its ok and code is not show on dll if open by note editor but dll not work any more 
coz <PrivateImplementationDetails> referanced to int64 . orginall dll have <PrivateImplementationDetails> but it dont show dcimal number in dll or converted to text on dll 
thanks for your time

**Comment by Rostam300** [comment]
i solve stored old code on dll by remove old  PrivateImplementationDetails
but new decimal code i add in dll show on dll as text and if i remove  PrivateImplementationDetails dll not work

**Comment by 0xd4d** [comment]
So you're wondering why the array data shown above is part of the executable? It's because the code needs it. This is not a bug.
