### ISSUE TITLE
Cant decompile ienumerator

### ISSUE THREAD

**Issue by whitelava3203** [0xd4d/dnSpy#810]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
4.5.3 and /branch/master/artifacts
- Write down all steps needed to reproduce this issue. Also attach any needed files.

```C#
public System.Collections.IEnumerator getAsyn(string id)
		{
			UnityEngine.Debug.Log(string.Format("DfwX LoadPkgAsync {0}", id));
			if (DfwX.CheckLoadAsyncHandleAvailable(id))
			{
				return this.getSpriteAsyn(id);
			}
			CLoadPkgMgr.CLoadPkgAsynOp<T>.<getAsyn>c__IteratorC <getAsyn>c__IteratorC = new CLoadPkgMgr.CLoadPkgAsynOp<T>.<getAsyn>c__IteratorC();
			<getAsyn>c__IteratorC.id = id;
			<getAsyn>c__IteratorC.<$>id = id;
			<getAsyn>c__IteratorC.<>f__this = this;
			return <getAsyn>c__IteratorC;
		}
```

//another class source which uses getAsyn

CLoadPkgMgr.CLoadPkgAsynOp<Sprite> load = new CLoadPkgMgr.CLoadPkgAsynOp<Sprite>();
				yield return base.StartCoroutine(load.getAsyn(s.loadCoverID));

still not support for some part of coroutine.

[CLoadPkgMgr.cs.txt](https://github.com/0xd4d/dnSpy/files/1907679/CLoadPkgMgr.cs.txt)
this is source including compilergenerated

**Comment by 0xd4d** [comment]
Seems like you've enabled 'show all compiler generated types and members' option. Try unchecking it. If that doesn't help, attach the assembly here (everything in the Managed folder)

**Comment by whitelava3203** [comment]
[Managed.zip](https://github.com/0xd4d/dnSpy/files/1911982/Managed.zip)
unchecking the option doesnt fix c__IteratorC

**Comment by whitelava3203** [comment]
that class is at Assembly-CSharp root namespace

**Comment by 0xd4d** [comment]
Has `getAsyn` been modified by you or someone else? The kickoff method should do nothing but create the state machine and return.

**Comment by 0xd4d** [comment]
Workaround: Remove the first code (everything up to `CLoadPkgMgr.CLoadPkgAsynOp<T>.<getAsyn>c__IteratorC <getAsyn.........`) using the IL editor. Then you'll see the iterator. You can then copy and paste it into the method above.

**Comment by whitelava3203** [comment]
thx you are a god
+ the source was edited by another person. i needed to view the edited code.
