### ISSUE TITLE
Use the latest version of ILSpy

### ISSUE THREAD

**Issue by stefnotch** [0xd4d/dnSpy#811]
ILSpy got some major improvements and can decompile things much faster. 

A test of ILSpy (latest version) vs dnSpy (latest version):
ILSpy: 2 minutes
dnSpy: 17 minutes
(Decompiling a rather large .exe)

**Comment by ThomasAunvik** [comment]
I dont see where that 2 minutes, and 17 minutes come from. It took a few seconds for me.

**Comment by stefnotch** [comment]
I decompiled a rather large .exe file (Terraria.exe) and timed it.

**Comment by whitelava3203** [comment]
ilspy is uncomfortable

**Comment by stefnotch** [comment]
@whitelava3203 This is why I created this issue. 😉 dnSpy internally uses a modified version of the ILSpy decompiler. However, that decompiler is outdated.

**Comment by 0xd4d** [comment]
Updating the decompiler would take a while and I don't have time to do that at the moment.

About the speed make sure you used release builds and the same bitness (32-bit vs 64-bit). Did you try JustDecompile, they claim to be 10x faster than the competitors :)

Decompiling everything to a project is possible but doesn't seem to be very useful since there'll be 1000s of errors you have to manually fix no matter what decompiler you use.

**Comment by stefnotch** [comment]
@0xd4d 
I used [ILSpy 3.1](https://github.com/icsharpcode/ILSpy/releases): 100 seconds
The [latest passing dnSpy build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts): 17 minutes
And [dnSpy v4.5.3](https://github.com/0xd4d/dnSpy/releases): 13 minutes 
In all instances, I used the x64 version. The time difference between the 2 dnSpy versions might be attributable to the fact that I used a bit different options. 

The last time I checked, JustDecompile just wasn't as good as the competitors. I'm not certain about the speed, but I'm pretty sure that the decompiled output was a lot worse.

And, there definitively are people who do decompile everything to a project. For example, video game modders. Yes, fixing the decompiled output takes a while, but that can be automated to a large degree.

**Comment by 0xd4d** [comment]
I can't repro your case since I don't have your exe so instead I tried decompiling dnSpy.exe since it's big, about 3MB. v2 decompiler is faster than v3 decompiler.

But it's posisble that your exe triggers some code paths in v2 decompiler that are much slower than in the v3 decompiler.

**Comment by stefnotch** [comment]
@0xd4d That's interesting.
I tried decompiling dnSpy.exe as well, here are my results:
- ILSpy v3: 12.5 seconds
- dnSpy (latest build): 10+ seconds
- dnSpy (latest release): less than 10 seconds
(Timing that is a bit hard)

One theory that could explain the speed difference when decompiling Terraria.exe could be that ILSpy now uses less RAM? (I'm not sure about this.) Decompiling Terraria requires you to have at least 8GB of RAM. And, when the RAM runs out or is close to running out, the OS has to use paging and stuff...

**Comment by 0xd4d** [comment]
Start x64 decompiler, decompile dnSpy.exe, stop timer. If you want to decompile again, exit it and start it again to prevent cached data from speeding it up. My test shows that v2 is ~2x faster than v3 when decompiling dnSpy.exe.

If you have a slow HDD that could be the bottleneck. I have an SSD.

**Comment by stefnotch** [comment]
@0xd4d 
> Timing that is a bit hard

My issue with timing it is that my laptop is almost too fast. And, I have an SSD. However, swapping things to a page file on an SSD is still way slower than having them in RAM.

Though, it's also possible that my "exe triggers some code paths in v2 decompiler that are much slower than in the v3 decompiler."

Anyways, I tried decompiling Terraria again and looked at the task manager. When using ILSpy, it used less than 1 GB of RAM and my CPU was mostly bored. (This time, decompilation took 77 seconds)

dnSpy on the other hand (~5 GB):
![image](https://user-images.githubusercontent.com/10220080/38751448-7548354a-3f58-11e8-8e53-7ac6555992a8.png)

**Comment by stefnotch** [comment]
Here is a task manager screenshot of ILSpy:
![image](https://user-images.githubusercontent.com/10220080/38751777-5d86a558-3f59-11e8-8aab-1fbb8b003dfe.png)

**Comment by stefnotch** [comment]
Oh, here is an issue related to this: https://github.com/icsharpcode/ILSpy/issues/631

**Comment by 0xd4d** [comment]
Yea seems like that Terraria.exe is an extreme example and seems to have been fixed in v3. However as I said, I don't have time to add it to dnSpy at the moment.

**Comment by stefnotch** [comment]
Well, it's not exactly a critical bug and it only appears in extreme and rare cases. It's more of a nice to have.

I suppose you could wait until the v3 decompiler is faster than the v2 decompiler and then, if you have time, improve this.

**Comment by 0xd4d** [comment]
The plan is to use it, but I don't know when.
