### ISSUE TITLE
InsufficientExecutionStackException when decompiling

### ISSUE THREAD

**Issue by Genteure** [0xd4d/dnSpy#812]
What version did you use?
v4.0.0-beta3 AND [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts) at the moment (df4e3de6)

I'm trying to debug my tool on a server running Windows 8.1, and a method cannot be decompiled.
```
An error occurred
System.AggregateException: One or more errors occurred. ---> ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Void BililiveRecorder.Core.RecordedRoom/<>c__DisplayClass48_1::<_StartRecord>g__callback|0(System.IAsyncResult)
 ---> System.InsufficientExecutionStackException: Insufficient stack to continue executing the program safely. This can happen from having too many functions on the call stack or function on the stack using too much stack space.
   At System.Runtime.CompilerServices.RuntimeHelpers.EnsureSufficientExecutionStack()
   At ICSharpCode.Decompiler.ILAst.TypeAnalysis.DoInferTypeForExpression(ILExpression expr, TypeSig expectedType, Boolean forceInferChildren) Location C:\projects\dnspy\Extensions\ILSpy.Decompiler\ICSharpCode.Decompiler\ICSharpCode.Decompiler\ILAst\TypeAnalysis.cs:Row 308
...(super long, total of 12324 line)
```
the full error message is available at [here (GitHub Gist)](https://gist.github.com/Genteure/bf97d52eeb565f6c7c433bad0fa6b168#file-traslated-txt).

The binary file I'm trying to debug is available at [appveyor](https://ci.appveyor.com/project/Genteure/bililiverecorder/build/1.0.2.0/artifacts).
Source code is available at [here](https://github.com/Bililive/BililiveRecorder/blob/v1.0.2/BililiveRecorder.Core/RecordedRoom.cs#L115-L225).

You might ask, why are you using dnSpy to debug. if you have the code, why not just use the code.
The answer is, I'm trying to debug a rare error, and the server I'm using don't have the resource to install & run a full Visual Studio.

**Comment by 0xd4d** [comment]
Workaround: Uncheck "Decompile anonymous methods/lambdas"

**Comment by 0xd4d** [comment]
The problem was that the decompiler tried to inline a local function recursively since it had a ref to itself. Fixed in latest build. Note however that local functions aren't supported so you have to enable 'show all compiler generated types and members' to step into it.
