### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by LearnSomethingNewEveryDay** [0xd4d/dnSpy#813]
Sorry since this isn't necessarily a issue with the program.

I was wondering if it's possible to search the whole decompiled code?  Like within the methods as well?

**Comment by 0xd4d** [comment]
Searching the decompiled text isn't possible at the moment. You can however search for constants (numbers or strings) in method bodies.

**Comment by 0xd4d** [comment]
Workaround: decompile the whole thing, open the project in VS, search the code.
