### ISSUE TITLE
Add Symbol Server

### ISSUE THREAD

**Issue by TheAifam5** [0xd4d/dnSpy#814]
IHMO would be nice feature to have :)

**Comment by 0xd4d** [comment]
dnSpy has a built-in debugger and you don't need a symbol server.

**Comment by enkephalin07** [comment]
dotPeek does an excellent job when it has debugger symbols available. Unfortunately you can assume release assemblies will optimize them out and exclude them, and dotPeek performs much worse then.

**Comment by 0xd4d** [comment]
I don't plan on adding this feature. You can always use dotPeek if you want a decompiler that is a symbol server.
