### ISSUE TITLE
HELP.

### ISSUE THREAD

**Issue by jiemto** [0xd4d/dnSpy#815]
https://prnt.sc/j5ti2w

i open the game dll but the left side is not showing up (where i can edit the dll of its files) it worked yesterday i got edited some in the game then today when i am editing some files in the dll again this shows up (the link)  idk what happened at the left side now i cant edit the game now ;-; (i even redownload it but its the same happening) help me plez

**Comment by SlowLogicBoy** [comment]
View -> Assembly Explorer...
