### ISSUE TITLE
How can I ignoring .Net PE Head

### ISSUE THREAD

**Issue by DorAEm0nKiNG** [0xd4d/dnSpy#818]
How can I ignoring .Net PE Head?
I want to know how to solve it for d4dot too.

**Comment by 0xd4d** [comment]
Explain some more what you're trying to do.

**Comment by DorAEm0nKiNG** [comment]
I'm trying to look source code of .dll (for apk) the Dlls has been modified manually by someone (isn't the game developer)
Some .dll files have been modified so the header can't be used for De4dot & dnSpy.
But Unity3D is much more relaxed when it comes to processing PE structures and .NET metadata. Some things are considered invalid by Windows and .NET Framework but still work in Unity3D.

**Comment by YuqseLx** [comment]
@DorAEm0nKiNG 
Can you check this?
https://www.andnixsh.com/2016/05/tutorial-how-to-get-around-invalid-rva.html
You need fix it manual

**Comment by DorAEm0nKiNG** [comment]
@YuqseLx Thankyou but doesn't work :'(
They have changed a lot.

**Comment by YuqseLx** [comment]
@DorAEm0nKiNG can you upload file?

**Comment by DorAEm0nKiNG** [comment]
@0xd4d Can I ask about PE file + mono of de4dot this topic? or should I new issue on de4dot?

**Comment by DorAEm0nKiNG** [comment]
@0xd4d Can I ask about PE file + mono of de4dot this topic? or should I new issue on de4dot?

**Comment by 0xd4d** [comment]
You can add a new issue there if you want. But you can also just drag the file to dnSpy, then File -> Save Module and it should be fixed. All other .NET tools should be able to read it.

**Comment by zoanthropy** [comment]
@DorAEm0nKiNG well done, you just destroyed the whole modding community. now i'm gonna leech all your stuff, post them everywhere and report all your hacks/trainers to game developer.

**Comment by thareleecher** [comment]
@DorAEm0nKiNG well done, you just destroyed the whole modding community. now i'm gonna leech all your stuff, post them everywhere and report all your hacks/trainers to game developers.

**Comment by DorAEm0nKiNG** [comment]
yeah i'm the biggest leecher ever. i leech everything hahahahahaha
