### ISSUE TITLE
Filtering by opcode with IL Instructions Editor

### ISSUE THREAD

**Issue by GravuTrad** [0xd4d/dnSpy#820]
Hi 0xd4d.

It's not a bug but more an ask about a feature.

Is it possible to filtering opcodes with the IL Instructions Editor?

I would filtering for example by ldstr (to facilitate translations). or at less order by. It seems not possible for the moment.

Thanks for your help.

**Comment by 0xd4d** [comment]
No, but you can copy a ldstr instruction and then paste paste paste.

**Comment by GravuTrad** [comment]
it's more to find them easily than a simple copy paste lol. if you say it's not possible ok noted. thanks for your really great tool.

**Comment by 0xd4d** [comment]
Once the combobox has focus, you can just type `ldst` to select it. No scrolling needed. But since you seem to use it a lot, pasting is the fastest way of doing it.

**Comment by GravuTrad** [comment]
Not pasting, find the ones which have the words to translate, edit it, than translate it.
