### ISSUE TITLE
Proper use of c# Interactive window

### ISSUE THREAD

**Issue by eng-marani** [0xd4d/dnSpy#821]
I'm confused about c# interactive window.

Typing this line
> Console.WriteLine("hello");
I expect the output to be emitted somewhere, but it displays nothing.
A simple expression , at the opposite, do works.
> 1 + 1
2

What is the proper use of c# Interactive to print in output ?
Is it possible, while debugging, to import the context and write expression using locals variables and their current values ?

**Comment by 0xd4d** [comment]
Stdout and Stderr are not redirected since scripts are loaded in the same process as dnSpy. See [here](https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy.Contracts.DnSpy/Scripting/Roslyn/IScriptGlobals.cs) for the methods in the script global class. There's a `Print` method you can use.

**Comment by 0xd4d** [comment]
> Is it possible, while debugging, to import the context and write expression using locals variables and their current values ?

You can do that, have a look at the public debugger API.
