### ISSUE TITLE
Conditional breakpoints

### ISSUE THREAD

**Issue by eng-marani** [0xd4d/dnSpy#822]
Is it possible while debugging to add a conditional breakpoint when a watched variable satisfy a given boolean expression ?
This would dramatically help debugging large for-each cycle.

**Comment by 0xd4d** [comment]
Breakpoint window -> right click a BP and edit its settings and add your own expression or hit count or log message etc.

**Comment by 0xd4d** [comment]
Note that evaluating is slow so you don't want to do it in a tight loop. In that case it's better to just edit the loop with dnSpy and add the condition and then add a Debugger.Break() call.
