### ISSUE TITLE
dnSpy will crash when clicking tool window "Call Stack"

### ISSUE THREAD

**Issue by 2365103939** [0xd4d/dnSpy#824]
When I debug a obfuscated exe and click tool window "Call Stack", dnSpy will throw exceptions and crash.
My english is not good, sorry.
![snipaste_20180422_133642](https://user-images.githubusercontent.com/27529558/39091934-4d3072f8-4632-11e8-8d51-609cbc1023af.png)
![snipaste_20180422_133648](https://user-images.githubusercontent.com/27529558/39091942-758bbcc6-4632-11e8-9a1a-c00b2edc5a72.png)
![snipaste_20180422_130926](https://user-images.githubusercontent.com/27529558/39091888-5a3dde32-4631-11e8-98a7-a2cf9c7cfec5.png)

[UnpackMe.Net[CLR40][ConfuserEx].exe.zip](https://github.com/0xd4d/dnSpy/files/1935243/UnpackMe.Net.CLR40.ConfuserEx.exe.zip)

**Comment by 0xd4d** [comment]
Quick bug report, too bad you didn't test it before I released v5.0.0 ;)

BTW, you can set the language to chinese `View` -> `Language` -> `中文(中国)`
