### ISSUE TITLE
Can't decompile local function.

### ISSUE THREAD

**Issue by lanzhiquan** [0xd4d/dnSpy#825]
- What version did you use?
  dnSpy v5.0.1 x86 or x64
- Write down all steps needed to reproduce this issue. Also attach any needed files.
![1](https://user-images.githubusercontent.com/11311878/39103030-f49aca7c-46da-11e8-90ba-7c97c67dfd48.png)
![2](https://user-images.githubusercontent.com/11311878/39103031-f52ebae8-46da-11e8-8294-9f1035b290f2.png)

**Comment by lanzhiquan** [comment]
I click <Main>g__LocalFunction|0_0 and it does not have any result!

**Comment by csftech** [comment]
Options -> Decompiler -> Show hidden compiler generated types and members

**Comment by lanzhiquan** [comment]
Oh, thanks.

**Comment by rolandh** [comment]
Could this be enabled by default? Or better yet when stepping code and you step into a hidden local function it turns it on temporarily? I got quite stuck with this until I found this issue.

**Comment by GSPP** [comment]
For usability, there could be a message box when the user tries to click on the name of a local function in the decompiler window. Currently, nothing happens.

It would be nice if local functions were included in the decompilation source code for the enclosing method.
