### ISSUE TITLE
CS0656 Missing compiler required member 'System.Runtime.CompilerServices.CompilationRelaxationsAttribute..ctor

### ISSUE THREAD

**Issue by barankaplan7878** [0xd4d/dnSpy#826]
![ekran alintisi](https://user-images.githubusercontent.com/38649180/39113740-4ede599a-46e5-11e8-8b8c-c696b68b5c9e.PNG)

When I'm trying to compile an edited method, I got an error that says "Missing compiler required member 'System.Runtime.CompilerServices.CompilationRelaxationsAttribute..ctor'" with CS0656 errorcode.

**Comment by barankaplan7878** [comment]
You said that on #759
![ekran alinatisi](https://user-images.githubusercontent.com/38649180/39123593-f48b6476-4700-11e8-9e3c-a4d53679e205.PNG)
But I don't know where is the main.cs

**Comment by 0xd4d** [comment]
The compiler's complaining about another attribute. You have to open the normal mscorlib from the GAC (Ctrl+Shift+O) and search for the attribute name. Once found, just copy and paste the class and add any necessary usings at the top.
