### ISSUE TITLE
[Help] Import C# file.

### ISSUE THREAD

**Issue by xp4xbox** [0xd4d/dnSpy#829]
I have been looking for a while, but I cannot figure out how to do this. I am able to export a .cs file, but how do I import one?

**Comment by SlowLogicBoy** [comment]
![howtoaddfile 1](https://user-images.githubusercontent.com/3121637/39307841-9c43f77e-496c-11e8-9a78-07eeeae5b0ca.gif)

**Comment by xp4xbox** [comment]
I mean is there a way to do it without copying/pasting the code, for example if you want to import multiple C# files at once.

**Comment by SlowLogicBoy** [comment]
Copy text from all files in the same editor window.

**Comment by SlowLogicBoy** [comment]
Oh right I didn't noticed that there is `Add Source Code` button.
![image](https://user-images.githubusercontent.com/3121637/39357112-823af16c-4a1a-11e8-901b-4e540dd1cc27.png)

**Comment by xp4xbox** [comment]
OK thanks, it would be cool if there was a command line option for this so I could create automated CI builds but that's a feature for another day.
