### ISSUE TITLE
C# code is not in english

### ISSUE THREAD

**Issue by Widgertius** [0xd4d/dnSpy#830]
Hello, I tried to find similar issues but could not find anything like it.

Basically when I open my dll file, the c# code is in chinese. A lot of the characters are symbols and some of them codes in them which makes the c# code unable to be compiled.

![image](https://user-images.githubusercontent.com/10050395/39277246-725cbda8-491f-11e8-8c86-fca8cbaccfd4.png)

Is there any way to change it to English or into a compilable format?

Thank you very much.

**Comment by UlyssesWu** [comment]
This assembly is obfuscated. Try to use [de4dot](https://github.com/0xd4d/de4dot#its-free-but-theres-no-support) (also by 0xd4d) to clean it.

**Comment by Widgertius** [comment]
Thank you so much. 0xd4d is amazing. these tools will be an awesome learning opportunity.
