### ISSUE TITLE
Can't load IEnumerator code in Edit Code

### ISSUE THREAD

**Issue by zoanthropy** [0xd4d/dnSpy#831]
Example I want to edit this code

![image](https://user-images.githubusercontent.com/20967118/39372510-e21febb2-4a44-11e8-9626-855e082b9e0e.png)

I right click and click "Edit Method (C#)", the code is empty and does not load.

![image](https://user-images.githubusercontent.com/20967118/39372617-27d92a42-4a45-11e8-8097-09a08837673d.png)
No problem when edit entire class instead but there is higher change to get compile error
I'm using dnSpy 5.0.1. This does not happen on 4.5.2

**Comment by 0xd4d** [comment]
dnSpy failed to find the kickoff method due to a missing attribute. The latest build has the fix.
