### ISSUE TITLE
MODULES TAB NOT SHOWN WHEN DEBUGGING IN VERSION 5XX

### ISSUE THREAD

**Issue by owaisnic** [0xd4d/dnSpy#832]
IN NEW VERSION MODULES TAB NOT SHOWN ALSO I TRY CTRL+ALT+U BUT NOT WORKING

**Comment by 0xd4d** [comment]
I can't repro it. Could be something wrong with your keyboard. Reopen it if you have more info on how to repro this.

Debug -> Windows -> Modules

Note that 'Windows' above is not the 'Window' menu next to 'Help'.

**Comment by owaisnic** [comment]
![4](https://user-images.githubusercontent.com/33257750/39392574-6f690e18-4ad1-11e8-8682-ee0fd42a15a7.png)

not shown

**Comment by pawlos** [comment]
@owaisnic you need to start debugging to see the `Modules` menu item. You're not debugging 'Start' button indicates that.
