### ISSUE TITLE
cANOT FIND modules tab when debugging

### ISSUE THREAD

**Issue by owaisnic** [0xd4d/dnSpy#833]
in version 4.5.2 x86 and latest versions i tried both module tab not show also tried with ctrl+alt+U
![4](https://user-images.githubusercontent.com/33257750/39392109-52d1ff88-4ac9-11e8-8dff-a5c8eda72b84.png)

**Comment by pawlos** [comment]
@owaisnic you're not debugging

**Comment by 0xd4d** [comment]
I can see in that picture that you didn't test the latest version. Were you too busy to read the text? It said you should try the latest build.

You're also not providing correct information. You say you're debugging but you're clearly not. If you give us wrong information, we can't help you.

And can you disable CAPS LOCK when posting here?
