### ISSUE TITLE
French ressources

### ISSUE THREAD

**Issue by kdrapel** [0xd4d/dnSpy#834]
Hello,

Just finished the french ressources on Crowdin, they can be integrated.

Mit freundlichen Grüssen,
K

**Comment by greenozon** [comment]
what is Crowdin, is it a place where people are localizing diff SW?
pls provide a link then!

**Comment by kdrapel** [comment]
Yes, there are many projects, each with a set of language to translate. People can pick any string and translate it + verify it. The link is present on the main page of dnspy -> https://crowdin.com/project/dnspy

**Comment by 0xd4d** [comment]
Thanks, I've added them now!
