### ISSUE TITLE
Empty if argument converted into something else causing error.

### ISSUE THREAD

**Issue by PiotrKFtw** [0xd4d/dnSpy#836]
I'm using latest version.
![image](https://user-images.githubusercontent.com/33489788/39397094-ba7e1c5e-4af9-11e8-9b0c-63fdcc09359b.png)
Thats what i put has been converted into
![image](https://user-images.githubusercontent.com/33489788/39397101-da637b40-4af9-11e8-93b2-1f7084388f96.png)
Causing error
![image](https://user-images.githubusercontent.com/33489788/39397102-e1511cb4-4af9-11e8-9c33-c80d8eb8f9e2.png)
I know that it's easy to fix but it's pretty annoying to change it everytime you put an empty if because you want to put something there later.

**Comment by PiotrKFtw** [comment]
Because i wanted to change it later.

**Comment by 0xd4d** [comment]
Solution is to remove the useless code. It does nothing. No need to keep it.
