### ISSUE TITLE
Export to project error "Can not find resource".

### ISSUE THREAD

**Issue by riverstore** [0xd4d/dnSpy#837]
Hi, I export an exe to project to both VS2015 and VS2017, checked/unchecked on "Unpack resources". I can build the project. But when I run it, I get this error message:

System.Resources.MissingManifestResourceException: 'Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "XXX.FormBase.resources" was correctly embedded or linked into assembly "XXX2" at compile time, or that all the satellite assemblies required are loadable and fully signed.'

I see the file "XXX.FormBase.resources" in the project.

- I use dnSpy 5.0.2.

Anyone please help me to solve this problem. Thanks in advance.

**Comment by greenozon** [comment]
Usually I do this simple step to understand whats going on:
1) inspect original exe in dnSpy - that resource under question - notice how it is placed/located inside the exe, etc
2) del it from assemblies tree and drop the 2nd exe  (buggy one) - 
3) compare and figure out the difference.

then go to VS and do hte magic - eg change resource type or place it in another dir/etc
