### ISSUE TITLE
Unexpected Treeview Crash "InvalidOperationException - Added item does not appear at given index 'n'" 

### ISSUE THREAD

**Issue by Panthere** [0xd4d/dnSpy#84]
Hey,

This happens randomly when I click on the expand arrow (not the name of the type). It mainly happens when I expand the root namespace, I have seen it happen rarely on other namespaces.
Below is a screenshot of what it looks like:

![image](https://cloud.githubusercontent.com/assets/11871649/13031619/e4dcd2ce-d323-11e5-96a6-21f889c8079c.png)

After this happens (the error is not the issue) whenever I scroll downwards on the treeview it will spam "Sorry we crashed" windows constantly until I kill the process.

![image](https://cloud.githubusercontent.com/assets/11871649/13031626/31a52908-d324-11e5-8b5d-dfa29a354fbe.png)

I'm currently on the 1.5.0.0 release.

**Comment by debug-hf** [comment]
I have the same issue. Currently on 2.0 beta have not had it happen yet.

**Comment by 0xd4d** [comment]
Yes, try the latest build. Lots of code have been rewritten, what you see is possibly something that has been fixed or didn't survive the refactoring.

https://ci.appveyor.com/project/0xd4d/dnspy/build/artifacts

**Comment by Panthere** [comment]
Hey 0xd4d,

Not had a crash with the latest yet, any eta on a stable release for 2.0 yet?

Will comment later if there is a crash the same as this.

**Comment by 0xd4d** [comment]
Probably sometime this month.
