### ISSUE TITLE
Generate solution

### ISSUE THREAD

**Issue by sunsl2018** [0xd4d/dnSpy#840]
命令“if not exist "D:\绩效管理资料整理\ILSpy_Master_2.4.0.1963_Binaries\dnspy-vmaster2018\dnSpy-master\dnSpy\dnSpy\bin\Debug\debug\core\x86" mkdir "D:\绩效管理资料整理\ILSpy_Master_2.4.0.1963_Binaries\dnspy-vmaster2018\dnSpy-master\dnSpy\dnSpy\bin\Debug\debug\core\x86"
if not exist "D:\绩效管理资料整理\ILSpy_Master_2.4.0.1963_Binaries\dnspy-vmaster2018\dnSpy-master\dnSpy\dnSpy\bin\Debug\debug\core\x64" mkdir "D:\绩效管理资料整理\ILSpy_Master_2.4.0.1963_Binaries\dnspy-vmaster2018\dnSpy-master\dnSpy\dnSpy\bin\Debug\debug\core\x64"
copy D:\绩效管理资料整理\ILSpy_Master_2.4.0.1963_Binaries\dnspy-vmaster2018\dnSpy-master\Extensions\dnSpy.Debugger\dnSpy.Debugger.DotNet.CorDebug\..\netcorefiles\x86\dbgshim.dll "D:\绩效管理资料整理\ILSpy_Master_2.4.0.1963_Binaries\dnspy-vmaster2018\dnSpy-master\dnSpy\dnSpy\bin\Debug\debug\core\x86" > NUL
copy D:\绩效管理资料整理\ILSpy_Master_2.4.0.1963_Binaries\dnspy-vmaster2018\dnSpy-master\Extensions\dnSpy.Debugger\dnSpy.Debugger.DotNet.CorDebug\..\netcorefiles\x64\dbgshim.dll "D:\绩效管理资料整理\ILSpy_Master_2.4.0.1963_Binaries\dnspy-vmaster2018\dnSpy-master\dnSpy\dnSpy\bin\Debug\debug\core\x64" > NUL
”已退出，代码为 1。	dnSpy.Debugger.DotNet.CorDebug

**Comment by sunsl2018** [comment]
dnSpy-master\Extensions\dnSpy.Debugger\dnSpy.Debugger.DotNet.CorDebug\..\netcorefiles\x86\dbgshim.dll

Generate a solution that does not find the file.

**Comment by UlyssesWu** [comment]
You should practice English harder since you actually mean "Building dnSpy solution". The title "Generate solution" is confusing because it can usually represent an issue about **generate** decompiled solution.

请努力提高英语水平，你的issue标题问题很大，“Generate solution”通常是指生成反编译的项目，而编译项目的“生成”（构建）对应的英文是“Build”。

To build dnSpy, you should read wiki carefully before asking:
https://github.com/0xd4d/dnSpy/wiki/Building-dnSpy

你应该在问问题之前仔细阅读wiki，里面有说明如何编译。网址见上。

You didn't get all submodules. The missing file exists [here](https://github.com/0xd4d/netcorefiles/tree/9b77ff87325e454cdf6fae536a11bfa382669d1a/x86).

问题出在你没有获取（下载）所有子模块。请使用wiki中写出的git命令，以确保获取到所有的子模块。
如果你只是要使用dnSpy，请直接下载[编译好的程序](https://github.com/0xd4d/dnSpy#binaries)使用，无需自己编译。

另：请尊重作者，使用英文提issue，且issue中不要出现中文。

**Comment by sunsl2018** [comment]
I'm a Java programmer and I'm not used to using compiled applications.
This is the problem I was having when building dnSpy.
And I used dnSpy 3 x version, is the program, click link to download the current module in addition to the question is: Extensions \ dnSpy Debugger \ dnSpy Debugger. DotNet. CorDebug
Thank you!

**Comment by UlyssesWu** [comment]
I still cannot totally understand your words... 😕

3.x is out-of-date. The current version is 5.x.

If there are no more questions, please close this issue by yourself.

抱歉，实在看不懂你的英语，特别是第三句。如果你已没有问题，请自行关闭此issue（close this issue）来向作者表明你的问题已经得到解决了。
如果你还有问题，请在发表之前用谷歌/百度翻译校正，机器翻译的英语可能都会比你上面写的易懂。或者你可以在英文下面附中文给我看（无奈之举）。

**Comment by sunsl2018** [comment]
I'am sorry!
那我直接用中文说吧，我用过dnSpy老版本的，而且研究过源码，非常好用！
这个问题就是我下载新版本后，编译报错的！

dnSpy-master\Extensions\dnSpy.Debugger\dnSpy.Debugger.DotNet.CorDebug..\netcorefiles\x86\dbgshim.dll
说这个文件不存在！

而且我们那疙瘩的人，说话儿，你更听不懂啦，建议你多学习中文，换角度思考问题！

这个英文，是我用有道翻译的，下次用google翻译试试！

还有啊，感觉你跟中国的大妈团风格很像，说话就像训人，呵呵！开个玩笑

虚心接受你的批评！

**Comment by UlyssesWu** [comment]
OK I understand what you mean now. You are probably using github's "Download ZIP" for source code. The zip you download is about 8,944kb and it somehow does NOT contain all submodules such as `netcorefiles`.

Please, use git (or tortoisegit which has GUI) for the source code.

你理解为“训人”也未尝不可，因为你问题出在**没有按照作者在wiki中说明的步骤**来操作（不使用git），这样导致的问题并不属于dnSpy本身的问题，只是在浪费你我的时间罢了。谢谢你的建议，我相信我的中文水平也不比您差。

**Comment by sunsl2018** [comment]
不好意思！我在重新下载试试，重技术角度来看，这是个小问题！我开个玩笑而已！不过说到浪费时间，我心里有点内疚！浪费时间等于杀人于无形，在开个玩笑！我自己解决，在次感谢你的建议！

**Comment by sunsl2018** [comment]
不得不说一句，新版本的问题确实比较多

**Comment by sunsl2018** [comment]
嗨！
   最后一次打搅，由于我的粗心，导致dbgshim.dll没有下载，编译错误，万分抱歉！
请允许我说明下：我所在的地方不允许直接访问，所以只好下载zip，一点一点的配置，请理解！
表达下我敬仰之情，我想深入学习您的源代码，如何开始？
