### ISSUE TITLE
Do not disallow write access to the assembly by other software like ILSpy/dotPeek

### ISSUE THREAD

**Issue by pavelkouril** [0xd4d/dnSpy#846]
- What version did you use?

5.0.x, but based on the commits, there is no change in this behavior since its release

- Write down all steps needed to reproduce this issue. Also attach any needed files.

Currently, when assembly is open for viewing in dnSpy and you try to write into it with Cecil, you will get the `UnauthorizedAccessException: Access to the path "Foo.WovenCode.dll" is denied.` error.

Other assembly viewers do not suffer from this, and it makes them much more usable during development of some weaving code, because you don't have to open&close dnSpy before every weaving.

Could you please make this locking configurable, or turned off completely? (Especially, when just browsing the assembly.)

**Comment by UlyssesWu** [comment]
Try: View - Options - General - (uncheck) Use memory mapped I/O
