### ISSUE TITLE
Analyzer can't read enums even it is readed by some code

### ISSUE THREAD

**Issue by m1m2m3mr** [0xd4d/dnSpy#847]
Read by is blank even some codes are reading it. I'm unsure if this is normal but i remember it does read enums before
I'm using dnSpy 5.0.3, 8 days latest build

![image](https://user-images.githubusercontent.com/20967118/40231141-3497b018-5a9a-11e8-8649-df92dc9fc0b1.png)

**Comment by 0xd4d** [comment]
It only analyzes the IL code and doesn't know that an integer value is really an enum value.

Workaround: decompile the whole thing, open it in Visual Studio and use Find All References in VS.

**Comment by m1m2m3mr** [comment]
Thanks, also you can use Notepad++ and search through all files.

**Comment by 0xd4d** [comment]
Yes and `grep` could be used too. ;)
