### ISSUE TITLE
Feature Request IL Code Debugging

### ISSUE THREAD

**Issue by cawk** [0xd4d/dnSpy#848]
A great feature would be to step through each individual instruction and have a stack view so you can see/edit the items on the stack

**Comment by 0xd4d** [comment]
You can already debug IL code, but you can't usually step over each IL instruction. The reason is that the CLR only adds sequence points at certain locations, usually when the stack is empty or after returning from methods etc.

**Comment by cawk** [comment]
oh i see, thank you for the clarification
