### ISSUE TITLE
Feature Request: Import/Export dnSpy settings

### ISSUE THREAD

**Issue by 2365103939** [0xd4d/dnSpy#849]
Sometimes I use dnSpy in another computer.I want to import settings from a exported settings-file.

Thanks!

**Comment by xp4xbox** [comment]
I am pretty sure they are all stored in the registry, so you could just export the .reg file.

**Comment by TheProxyRE** [comment]
it should be AppData\Local\dnSpy\Startup

**Comment by 0xd4d** [comment]
Close, it's `C:\Users\YOURNAME\AppData\Roaming\dnSpy`

The other one is just some cache to speed up startup perf.
