### ISSUE TITLE
Load plugins from their own directories

### ISSUE THREAD

**Issue by hmemcpy** [0xd4d/dnSpy#85]
Hello!

I was wondering if you'd accept a PR that also looks for plugins in a dedicated `Plugins` directory, rather than the root of dnSpy? It would make include plugins that depend on other libraries easier, without making a mess of the root dir.

**Comment by 0xd4d** [comment]
Sounds like a good idea, and yes I would accept it.

**Comment by hmemcpy** [comment]
Awesome! Will do.
I'm working on a ProcMon-style plugin for dnSpy, with a twist that will let you intercept any method in any running .NET process... wanted to call it DotNetSpy, but then someone told me dnSpy already existed :)

**Comment by 0xd4d** [comment]
Any progress on this feature?

**Comment by hmemcpy** [comment]
So sorry about not being able to work on that!
But it seems you've done it! Awesome, thanks so much!
