### ISSUE TITLE
'Array' does not implement interface member 'ICollection.CopyTo(Array,int)'

### ISSUE THREAD

**Issue by friuns2** [0xd4d/dnSpy#852]
- What version did you use?
5.0.4

- Write down all steps needed to reproduce this issue. Also attach any needed files.
Open Array class -> Edit Method -> try compile
![image](https://user-images.githubusercontent.com/16543239/40587927-bc7d17ac-61de-11e8-8a69-c167ce53ba44.png)

**Comment by 0xd4d** [comment]
Looks like #365 . mscorlib is special, we can't add any assembly refs to it so the trick dnSpy uses won't work.

**Comment by 0xd4d** [comment]
Closing this, it should only happen if you try to edit any of the special types in the core library.
