### ISSUE TITLE
Setting conditional compilation symbols permanently

### ISSUE THREAD

**Issue by LeaderEnemyBoss** [0xd4d/dnSpy#853]
Hey everyone,

I'm new to this stuff, I hope this is the right place to ask. I am modifying a unity game and need conditional compilation symbols  for some of the debugging code to compile. Currently I use the #define  preprocessor directive to define my symbol every time I modify something. This gets a bit tiresome after a while. Is there a good way in dnspy to permanently set a symbol?

Many thanks for this great tool

**Comment by 0xd4d** [comment]
This is not possible and doesn't seem to be useful in dnSpy. You can add a static boolean somewhere and add an if statement you really need something similar.

**Comment by LeaderEnemyBoss** [comment]
What do you mean with "not useful"? I'm using dnspy to create a community patch for a rather large unity game that is no longer supported by its developers. This involves lots of logging and trial and error in order to figure how everything works. So I edit many methods and add #define [symbol] every time I change something. Is there a better way to do what I am doing?

I know there is the command line option -define for the compiler, I thought maybe that could be added as an option to dnspy.

**Comment by 0xd4d** [comment]
It doesn't seem to be useful because you're not saving the source code so any `#ifdef` in the code will be gone once you compile it.

```C#
#ifdef something
throw null;
#else
Console.WriteLine("Hello");
#
```

Only one of those statements will be added to the assembly.

**Comment by LeaderEnemyBoss** [comment]
There are parts in the source code, that get deleted upon compilation, if I dont put #define UNITY_EDITOR at the start of the source code (I tested it!). Putting #define UNITY_EDITOR at the start of the source code every time I make changes is annoying. It would be easier to "tell" the compiler via Compileroption, that these symbols are always active ([see here](https://docs.microsoft.com/de-de/dotnet/csharp/language-reference/compiler-options/define-compiler-option)). Sorry if I have been unclear.

**Comment by 0x53A** [comment]
probably [ConditionalAttribute](https://msdn.microsoft.com/en-us/library/system.diagnostics.conditionalattribute(v=vs.110).aspx)?

dnspy could scan all methods, collect all symbols and then automatically ``#define`` them.

**Comment by LeaderEnemyBoss** [comment]
Yes, the method I am calling has [Conditional("UNITY_EDITOR")] infront of it. As per your link the 3 ways to deal with it are: 

1. using #define (which I did until now)
2. using the /define command line option for the compiler (what i wanted)
3. setting up an environment variable in the os - I tried that once, but couldnt get it to work ... maybe I should try again before bothering you ;p

**Comment by 0x53A** [comment]
Only compile-time is relevant, at run-time it is too late, and I doubt dnSpy reads the env vars.

**Comment by 0xd4d** [comment]
Use your favorite text editor and open all source files and replace `[Conditional("UNITY_EDITOR")]` and with `//[Conditional("UNITY_EDITOR")]`. Should take a few secs.

**Comment by 0x53A** [comment]
I think the issue is if a method in a reference-dll is decorated? e.g. inside mscrolib, or inside the unity runtime?

**Comment by 0xd4d** [comment]
Yeah in that case as a temporary workaround, he could add #define xxxx at the top of each file by using command line magic (eg. `sed`)

**Comment by LeaderEnemyBoss** [comment]
@0xd4d thanks for your workaround suggestions :)
