### ISSUE TITLE
Do not override object.Finalize instead provide a destructor

### ISSUE THREAD

**Issue by GamerSuper** [0xd4d/dnSpy#854]
![dnspy_2018-05-30_16-56-37](https://user-images.githubusercontent.com/39771233/40728531-99776e3a-642a-11e8-824d-0112c7cf2f38.png)

I got this error, when I try to edit the .exe file. (I'm using the latest version)
It worked some months ago, but now I try to edit it and I can't.

**Comment by 0xd4d** [comment]
You should edit a method instead of the whole class since ti's more likely that the compiler will complain if you edit every method at the same time.

In this case you can change it to the destructor syntax `~ClassName()`

**Comment by GamerSuper** [comment]
Still not works, but I'm editing the method now...
![dnspy_2018-05-30_19-19-55](https://user-images.githubusercontent.com/39771233/40736523-8b2099ec-643e-11e8-8d51-bbbe79d38254.png)

**Comment by 0xd4d** [comment]
Yes you can remove code in main.g.cs if you edit only one method at a time. You could've also changed it to the destructor syntax, `~SomeClassName()`

**Comment by 0xd4d** [comment]
> I got this error, when I try to edit the .exe file. (I'm using the latest version)

How do you know that you're using the latest version? What is the latest version? I can see in your picture that you're not using the latest version.
