### ISSUE TITLE
Is it possible to search for strings in certain assemblies?

### ISSUE THREAD

**Issue by TraGicCode** [0xd4d/dnSpy#856]
- What version did you use?
v5.0.0

Is it possible to search for a string in a certain assembly and/or certain assemblies matching a certain pattern:

Example 1
Find the string "MessageBox" in MyCompany.UI

Example 2
Find the string "MessageBox" in MyCompany.*

**Comment by 0xd4d** [comment]
Yes, search for `Number/string` and you can filter it so it only searches the selected assembly/assemblies and also exclude GAC assemblies. Use `/^hello.*bye$/` to use a regex

**Comment by TraGicCode** [comment]
Hey @0xd4d ,

Sorry i might be missing something but i don't see a text box in which i can enter an assembly filter with my target string to search for.

**Comment by 0xd4d** [comment]
The last combobox that says `All Files` can be changed to `Selected Files`, i.e., all assemblies you've selected in Assembly Explorer.

**Comment by TraGicCode** [comment]
Hmm, okay the terminology is a big confusing.  I thought it was talking about tabs ( C# files ) opened

**Comment by TraGicCode** [comment]
Hey @0xd4d ,

I'm still having some trouble with the searching and not really sure if i'm doing something wrong here.  I have the file brought up in dnspy and i'm simply trying to search for a class that is being utilized within the file Rfc2898DeriveBytes

![image](https://user-images.githubusercontent.com/6224270/40919128-346ec928-67ce-11e8-93f8-c38330dce2e3.png)

When i perform my search, as shown in the screenshot, it comes back with 0 results.

**Comment by 0xd4d** [comment]
Check your search settings, maybe you disabled searching in GAC files.

**Comment by TraGicCode** [comment]
I'm not wanting to search the gac.   The above is a program i'm decompiling that uses that class.  I would expect the search results to contain the above file i have opened.  Nothing got returned as shown in the screenshot.

**Comment by TraGicCode** [comment]
@0xd4d ,

Bumping this.  It kind of seems like Dnspy lazily analyzes/loads code which could be the reason strings are not showing up until it encounters them.  Can you confirm this?

**Comment by 0xd4d** [comment]
I don't understand what the problem is. If it's not finding a string that exists, make sure you've not disabled searching in that assembly and make sure other options don't prevent dnSpy from matching the string, eg. disable case sensitive searching.
