### ISSUE TITLE
Adding property to interface results in TypeLoadException at runtime

### ISSUE THREAD

**Issue by idealpersona** [0xd4d/dnSpy#857]
DNSpy 5.0.4

I had an interface and a class implementing that interface, Using "Add Class Members", I added the the property 

		public bool PropertyName { get; private set; }

To the class and then

		bool PropertyName { get; }

to the interface.  So after each step here the program should be well-typed.  But this results in a TypeLoadException at runtime after doing "Save Module" on the DLL and running the program.  This was also the case even if I ran "Save Module" after adding the full property to the class before adding it to the interface as well.  I was able to resolve the issue only by going to the implementing class, and recompiling it using "Edit Class" and hitting "Compile" without changing anything.

Sorry, I have not tried with the latest build yet, but I found no other related issues.

**Comment by 0xd4d** [comment]
The problem is that you added it in the wrong order. When you add just the property to the class and the property doesn't match an interface property, it will be non-virtual.

The solution is to first add the interface property, or if the class is not sealed, add a virtual property.

**Comment by 0xd4d** [comment]
Note that the metadata passed to the compiler is the last save of the file so if you modify the interface and try to add the property to the class, it will still be non-virtual since the compiler sees the original interface. Save the file first.
