### ISSUE TITLE
Improving hints and user experience

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#859]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
5.0.4
- Write down all steps needed to reproduce this issue. Also attach any needed files.

I'd like to propose a new micro feature: extend existing (duplicating) hint for current tab,
it'd be really user-friendly to print instead of current hint full path to class that the cursor is currently in.
Especially this will help to understand where am I - which assembly/namespace/class...
in order to get this info one has to go to left tree and check it out what is location.
Having that great hint will increase the user experience to the sky, I bet!

![tab_hint](https://user-images.githubusercontent.com/765343/40879854-8ccf15a2-66af-11e8-84d8-dca3b4246bb2.png)

**Comment by pawlos** [comment]
@0xd4d is it ok to work on this one?

**Comment by 0xd4d** [comment]
Absolutely! Thanks for the help!

**Comment by greenozon** [comment]
Well, my example window does not show all the benefits from the potential feature
here is another example - http://prntscr.com/lmd5zw

as you see, the hint is useless in this specific use-case, 
but once it'll start showing the assembly/namespace/parent class - that would help much much more! :)

@pawlos   any ideas if that's possible?

**Comment by pawlos** [comment]
@greenozon  I've looked at this but it's harder that I anticipated ;). Looks like there's not so much data that could be used when the tooltip is generated to provide much more meaningful text - but it might be that I'm missing something in the source code/project structure.

**Comment by 0xd4d** [comment]
The assembly treeview node has special case code for tooltips, the new code would do something similar (check `options`): https://github.com/0xd4d/dnSpy/blob/039405f69e60aa850e3770ea6cc94f84dde61dcf/dnSpy/dnSpy/Documents/TreeView/AssemblyDocumentNodeImpl.cs#L45

You probably need to override at least these nodes' WriteCore() method: TypeNodeImpl, PropertyNodeImpl, MethodNodeImpl, FieldNodeImpl, EventNodeImpl

DecompileDocumentTabContent is the one that creates the tooltip. Its `ToolTip` property just returns its `Title` property so it would need to be updated to do something new other than returning `Title`. Perhaps add a new `DocumentNodeWriteOptions.TabToolTip` bit and pass that option to the nodes.

Note that the tab's ToolTip property is cached by WPF and won't get updated when the caret moves. Recreating the tooltip every single time the caret moves is bad for perf and would need to be done lazily if it will even be supported.

**Comment by pawlos** [comment]
@0xd4d  thanks. Actually I was looking around those areas but dropped that as this was too much (let's call it) architectural change for such simple thing. But since this is the way you think it should be done then I'll have a look again (hopefully this week).

**Comment by 0xd4d** [comment]
The treeview nodes don't know much except their own type/method/etc so you can't use anything shown in the text viewer, it can update without them knowing about it. But it's probably still possible to show extra info eg. namespace + class.

**Comment by greenozon** [comment]
One more idea that is somehow related to the requested subject:
it's in Debug mode, when you having hundreds of breakpoints being set,
say one was hit and you don't know where exactly you landed,
so I propose to add this info to the status bar, eg:
basically it is same as I proposed to add into hint for tab head location

![screenshot_35](https://user-images.githubusercontent.com/765343/53678926-37497000-3cce-11e9-849d-a7acc3e8a40b.png)

**Comment by 0xd4d** [comment]
Fixed by https://github.com/0xd4d/dnSpy/issues/1155

**Comment by greenozon** [comment]
Thank you from the bottom of my heart!!!
super B killer feature, 

**so long-awaited and desirable**
