### ISSUE TITLE
Internal debugger error...

### ISSUE THREAD

**Issue by JemoGlemo** [0xd4d/dnSpy#861]
Hello,

Please, need your help to fix this error while trying to unpack a file packed with ConfuserEx 1.0.0. I've used the following steps:-
1. Using dnSpy(v5.0.5) latest build, setting a BP in .cctor of module.
2. Using NoFuserEX 1.1 version, Error !  (Screen shot of the error : https://imgur.com/a/yes7LIo).
3. checked .NET framework 4.5.2 is correct.
4. Using Win10 / Win7 same result.

Thanks
Jemo

**Comment by 0xd4d** [comment]
Provide some repro steps and also search the issues.

**Comment by JemoGlemo** [comment]
Very straight forward, I'm trying to manual unpack a file packed with ConfuserEx 1.0.0. My steps are:-

1. Lunch the exe in dnSpy ( See : https://imgur.com/a/6dULYVC)
2. Set a BP in .cctor of module ( See : https://imgur.com/a/QRyywCT)
3. Run.

After then, I could not find any variables in the (**local**) windows to start the unpacking process.

That's all bro.

**Comment by 0xd4d** [comment]
This has been asked before, you can search the issues, here's one: https://github.com/0xd4d/dnSpy/issues/572#issuecomment-339510779
