### ISSUE TITLE
In-place method assembling

### ISSUE THREAD

**Issue by DKingCN** [0xd4d/dnSpy#864]
Feature request:
in-place method assembling

- What version did you use?
5.0.5 from CI

In some situation reassembling will break the assembly file. (In my case it happens with throwing error related to `#ifdef Unity_Editor` but that's not the point). 
My point is, having an option **In-place assembling** in **method editor window**, that implement an inplace method bytecode replacement, without changing the other part.

It's ok to throw an error and cancel assembling if the translated bytes is bigger than method size. And it does not has to be a C#-to-Bytecode feature, IL-to-Bytecode is fine enough. It's just too complex to find the MD token and find the IL code translation, then find the file offset and change it in another hex editor. A feature of this will help a lot. 

Thanks in advance. Im considering to implement it on my own and commit back if you dont have time on it, just after I done my shit. lemme know if any assistance is needed.

**Comment by 0xd4d** [comment]
This is a feature that will fail a lot or most of the time and the user won't understand why. If we can't find the same token or string in the original file, then it will fail. If the method is too long, it will fail. If the compiler adds more types, it will fail.

It's better to figure out why your assembly fails after you've modified it. Most likely it will fail even if you hex edit a method.

**Comment by DKingCN** [comment]
I think strings will be the major problem...... I forgot about that, that need more hex hack.

Those bytecode translations took me a few days so just wondering if there will be any easier way... It's alright to not consider this feature if this brings too much failures.

by the way, my hex modification worked. Just calling a few methods. Basically user need to delete some original codes and replace them with their own short ones but any way it will work if they know what they are doing...

The assembly seems to be failing on class serialization in DLL, something related to Unity Editor (or not).
 It throws
```
A script behaviour has a different serialization layout when loading. (Read 24 bytes but expected 40 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?"
```
But I m not going to trouble you with this problem. just for your information if you curious...

**Comment by 0xd4d** [comment]
> But I m not going to trouble you with this problem. just for your information if you curious...

This is the real problem. Your solution is just a complicated workaround that can be spent fixing this issue instead.

Can you reproduce this with some free game? If not, could you attach the assembly files here and tell me how to reproduce this so I can compare the files.

**Comment by DKingCN** [comment]
Im afraid I cant reproduce it right now. The game I worked on has updated recently. 
Give me a few days, I will create a new project that reproduces the problem.

**Comment by 0xd4d** [comment]
Create a new issue if you can repro it.
