### ISSUE TITLE
ScyllaHide for dnSpy (anti anti debug IsDebuggerPresent) problem

### ISSUE THREAD

**Issue by ComanGames** [0xd4d/dnSpy#865]
So i implemented ScyllaHide for dnSpy 
https://github.com/x64dbg/ScyllaHide - scylla hide itself
https://github.com/ComanGames/dnSpy-ScyllaHideExtension - my extension
And it's looking like that.
![alt text](https://am3pap002files.storage.live.com/y4mXCxhb8yyG6bul8F4HjV3-q8SjOgVu6aOfvrc7M6XiuDIZIIs8_bncDnWZI7H2oueahSEE_N7rjAeibuqOZQ67TFTpDAOcGjIJ_MBos_pmNbZfEwpcXjPG499eHsQ_fZ2Fz9glPHplP_uqCHRvdLFjNwDReTAHH0j_r6fxX8gXeEtN4dtj5OYsrjvbyzqgUBr/DnSpyScyllaHideExtension.png?psid=1&width=874&height=651)
And it's injecting the process and kind of working
But when I enable 
IsDebuggerPrsent injection .
The breakpoints stops to work I am injecting directly from the process of dnSpy  using C++ dll created by me
Like that
https://github.com/ComanGames/dnSpy-ScyllaHideExtension/blob/master/dnSpy.ScyllaHide.Extenstion/DebugStart.cs

So the question why the debug points stop working after I inject the IsDebugPresent from kernal32.dll ??
And another one how can I get access to the dnSpy.Debugger.DotNet.CorDebug from extension
More specifily to dndbg.Engine namespaces and classes. Because there majic of injection is happning.

**Comment by 0xd4d** [comment]
It's probably the CLR that gets confused. Maybe it's not getting the breakpoint events.

**Comment by ComanGames** [comment]
The option that makes clr confused is PebBeingDebugged. That responsible  for kernal32.dll IsDebuggerPresent . The option itself became false but our  breakpoints in dnSpy stops working

**Comment by 0xd4d** [comment]
The CLR calls that method, check the coreclr source code.

**Comment by ComanGames** [comment]
Okay I kind of tried buy I have a tone of question about how debbuging work here .
 dnSpy.Debugger.DotNet.CorDebug is the way to communicate with that using MEF. Or I should implement some MEF for that by myself.  
Other one.
If I run scyllaHide test 
![alt text](https://am3pap002files.storage.live.com/y4mwChjgmQ8no6Y6P-D1wu6I4VX5qm3Gl2WYcBreAPJl-JSquJD3Cq1-K54Vfg6xO1Bwn3DnOww7ZL-FOdSxaOcIlBXCevfJxXOV-96Mr1eRTCWmFrcTGLrj8-4EnPeq0zbGDiaQXzIpGSKNGTndlEigg9IAcPTwLWZid1HSN17YCcorbyWtz77J6EdKjw2N9HO/ScyllaHideTest.png?psid=1&width=1642&height=923)
It see that it is under debugging. 
But I recive no events from debbug manager. 
How can I fix that? 
To make injection of any exe file

**Comment by 0xd4d** [comment]
The issues are for questions. I don't have time to figure out why ScyllaHide doesn't work with the CLR.

**Comment by ComanGames** [comment]
So I am not quite sure is the issue in CLR. Because ScyllaHide works perfect in x64dbg with clr Based software. Maybe problem is somewhere in dnSpy debugger?

**Comment by ComanGames** [comment]
Any place where it depends on PEB

**Comment by 0xd4d** [comment]
x64dbg debugs native code and doesn't use the CLR CorDebug API.

**Comment by 0xd4d** [comment]
You'll probably have to filter out the debugger detection, returning original value if caller is the CLR. This is not a dnSpy issue so closing.
