### ISSUE TITLE
Bak files 

### ISSUE THREAD

**Issue by OndrejPetrzilka** [0xd4d/dnSpy#867]
dnSpy creates .bak files next to dlls. I'm not sure when or why, but it causes some issues.
Some applications (e.g. Unity game engine) wants to delete all files, including .bak files when doing build and fails.

Would it be possible to:
a) disable this behavior in options
b) create .bak files in temp directory or some userdata dir
c) allow other applications to delete these files

- What version did you use?
5.0.4

- Write down all steps needed to reproduce this issue. Also attach any needed files.
Add dll file to AssemblyExplorer
Open it and browse some class
Notice .bak file was created next to dll

**Comment by 0xd4d** [comment]
dnSpy never creates bak files.

**Comment by OndrejPetrzilka** [comment]
Okay, but for some reason, keeps it locked?

![dnspy](https://user-images.githubusercontent.com/3371096/41537923-181d4c26-730a-11e8-98cf-028764ce02be.png)

**Comment by 0xd4d** [comment]
That means you either have it opened in Assembly Explorer or one of the files in Assembly Explorer has a reference to the file and dnSpy opened it. If it's locked it's probably because dnSpy uses memory mapped IO, you can disable that in the settings.

**Comment by OndrejPetrzilka** [comment]
Is it possible that files was named 'com.unity.postprocessing.Editor.dll', got renamed to 'com.unity.postprocessing.Editor.dll.bak' and dnSpy is okay with that?

**Comment by 0xd4d** [comment]
dnSpy doesn't detect .NET files by checking the file extension. You can name it anything, and dnSpy will just open it and check if it's a .NET file.

**Comment by OndrejPetrzilka** [comment]
Disabling Memory mapped I/O solved my issue, file can be deleted now.
Thanks
