### ISSUE TITLE
How To Transform This dnSpy-Master.zip Info An dnSpy.exe Or dnSpy32X/64X/86X/.exe ?

### ISSUE THREAD

**Issue by AmenTheRockATK** [0xd4d/dnSpy#868]
As The Title Explans I Just Downloaded The Master Folder But I Dont Know How To Use It Or Make It Info An .exe ? (Ps;My System 32X) Please Help Me.

**Comment by 0xd4d** [comment]
https://github.com/0xd4d/dnSpy/wiki/Building-dnSpy

**Comment by 0xd4d** [comment]
Or read the README, it has links to binaries.
