### ISSUE TITLE
How to change console decompiler settings

### ISSUE THREAD

**Issue by stevemk14ebr** [0xd4d/dnSpy#869]
I want to modify the Console decompiler's settings to turn off "Show tokens, RVA's, and file offsets". However i am confused on how it is even loading the decompilers.
```
var p = (IDecompilerProvider)Activator.CreateInstance(type);
foreach (var l in p.Create())
    yield return l;
```
what is the correct way for me to get access to the decompilers settings, i think i need access to the constructor that takes the DisassemblerOptions class

**Comment by 0xd4d** [comment]
Did you try `--help`

**Comment by stevemk14ebr** [comment]
im sorry, i didn't. Thanks
