### ISSUE TITLE
[Suggestion] Control flow graph

### ISSUE THREAD

**Issue by XenocodeRCE** [0xd4d/dnSpy#872]
Tittle says it all :-)

Would be nice to get access to CFG of the assembly.

Washi's projects https://github.com/Washi1337/Rivers can be easily used to do this.

However dnspy plugin sdk is way too complex as of now for me to work on it.

**Comment by 0xd4d** [comment]
Isn't the decompiled C# or VB code enough? Or do you need it with IL code?

**Comment by XenocodeRCE** [comment]
I just thought a call flow graph feature would be a nice thing to implement. 

Famous debugger all includes a diagram/graph features.


![](https://i.imgur.com/u6f5BY7.png)

It's very easy using Washi's project, hence why I allowed myself to post a link to it

**Comment by 0xd4d** [comment]
Those debuggers you're talking about are probably native debuggers, eg. x64dbg and usually show assembly language so showing a pic like that above could be useful. But if you already have decompiled code, it seems like such a feature isn't as useful.

It's not something I feel like I need so I'll probably not add it. You can write your own extension though.

**Comment by 0xd4d** [comment]
Closing it, I won't add this feature.

**Comment by MostafaNanticock** [comment]
Man! come on.. this feature is very handy when dealing with obfuscated assemblies. where you don't know which function does what. dnSpy is the only existing tool that can do this, it's a real life saver in such situations, & adding this feature to it would make it perfect.

**Comment by kfrajtak** [comment]
The graph can be constructed using `dnlib`, see [this](https://github.com/yck1509/ConfuserEx/blob/master/Confuser.Core/Helpers/ControlFlowGraph.cs). But `dnSpy` is not using `dnlib` ...

**Comment by UlyssesWu** [comment]
> The graph can be constructed using `dnlib`, see [this](https://github.com/yck1509/ConfuserEx/blob/master/Confuser.Core/Helpers/ControlFlowGraph.cs). But `dnSpy` is not using `dnlib` ...

I don't think you really understand "CFG" or "dnlib".

**Comment by kfrajtak** [comment]
Well, `dnlib` can read the IL code and convert into a something that is above the raw bytes. It creates the method body with instructions and their arguments, so they match and CGF can be constructed as per example.
With `dnSpy` I get the raw bytes and then I have to go over the bytes one by one, find out which one is instruction and which arguments and I don't the number of operands for each instruction type.
If you had something else in mind, please elaborate, thanks.

**Comment by SlowLogicBoy** [comment]
@kfrajtak 
> The graph can be constructed using dnlib, see this. But dnSpy is not using dnlib ...

Yes it does. dnSpy is built on top of dnlib.

If you need this feature, this is an opensource project, you can ether contribute, or create a plugin for dnSpy.

**Comment by kfrajtak** [comment]
@SlowLogicBoy it looks like it is, but not in the places I'd expected it to be, like `dnSpy.Debugger.DotNet.Interpreter` for example.

In case you know way around the bytes and instructions as per my post, could you help? Thanks
