### ISSUE TITLE
Provide old dnSpy 3.0.2.0 version

### ISSUE THREAD

**Issue by hellboy81** [0xd4d/dnSpy#875]
Please provide also old dnSpy 3.0.2.0 versions in order to make available for use with old .NET 4.6 versions

**Comment by AndnixSH** [comment]
Here you go :)
[dnspy_3.0.2.zip](https://github.com/0xd4d/dnSpy/files/2168031/dnspy_3.0.2.zip)

**Comment by 0xd4d** [comment]
You can compile it yourself. I delete old versions whenever I release a new version. .NET Framework 4.7.1 is available on Windows 7 SP1 and later operating systems so it should be no problem for you (or are you using Windows XP).

**Comment by tonysepia** [comment]
I can't compile it myself, sadly. Could you please provide a build for .NET Framework 4.6, just so it is available to users?

The developers of software that I am debugging claim that presence of .NET 7 affects the functionality of their software, so I can't install it on the debugging host.

**Comment by 0xd4d** [comment]
@tonysepia Use the .NET Core build instead.

**Comment by tonysepia** [comment]
@0xd4d thank you for the suggestion. Just so I understand better, will I still be able to debug .NET 4.6 assemblies using .NET Core build?

**Comment by 0xd4d** [comment]
> The developers of software that I am debugging claim that presence of .NET 4.7 affects the functionality of their software

IOW, it's buggy.

> Just so I understand better, will I still be able to debug .NET 4.6 assemblies using .NET Core build?

Yes it should work.
