### ISSUE TITLE
Feature Request [low priority]: Copy Analyzer pane content as text

### ISSUE THREAD

**Issue by tonyweb** [0xd4d/dnSpy#88]
Hi 0xd4d,
first I would like to thank you for your awesome work on this tool ... it's really fantastic and a great gift to the community (and to noobs like me).

If possible I'd like to see implemented a way to _copy the tree of Analyzer pane/window as text_ (keeping tree "structure"). My notes are always just simple text files and I'd like to paste also analyzer results. I know I could use rich editors and save screenshots of analyzer but I prefer the much more simple and small text files ... I hope you could understand (and agree :P).

Thanks in advance and Best Regards,
Tony

**P.S:** If the feature is already in place and I just can't see/use it, please point me in the right direction and, of course, shame on me !

**Comment by 0xd4d** [comment]
Yes, this is useful. Something like this maybe, one tab per level:

```
something
\tsome other thing
\t\tanother one
more
\tmore
```

**Comment by tonyweb** [comment]
Yeah. That would be good :+1:

Thanks again and Best Regards,
Tony

**Comment by tonyweb** [comment]
Fantastic! Tested and Working! You're really awesome.
Thank you so much ... now I can keep my notes small and clear :+1: 

Best Regards,
Tony
