### ISSUE TITLE
Decompiling takes forever

### ISSUE THREAD

**Issue by DJPop** [0xd4d/dnSpy#881]
The [latest build](https://github.com/0xd4d/dnSpy/commit/039405f69e60aa850e3770ea6cc94f84dde61dcf) also has this issue.

- What version did you use?
v5.0.5 (x64)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
[Assembly-CSharp.zip](https://mega.nz/#!TpsCTApC!Lq1Pidqe4rsokEbaJyIvUdtYUUFMeHcgF5T3fb0W9Qg)
Click on class "SoundData", the message "decompiling..." pops up but never complete.
I'm not sure about issue in other classes. At least this one blocks the export to project process.

**Comment by XenocodeRCE** [comment]
@DJPop File is obfuscated. And there is no "SoundData" class at all : 

![](https://i.imgur.com/haXw5kv.png)

**Comment by DJPop** [comment]
Are you sure you opened the correct file?

![0000](https://user-images.githubusercontent.com/14096822/42727183-03b48ae8-87cc-11e8-8d11-70fd02eba31c.png)
Works for me, no obfuscated data.

And here's SoundData class.
![0001](https://user-images.githubusercontent.com/14096822/42727184-08926670-87cc-11e8-85b6-241520a9c9b5.png)

**Comment by XenocodeRCE** [comment]
@DJPop my bad.

![](https://i.imgur.com/WzMz5GG.png)

works fine using IL view, I doubt anything can be done for that, wait for @0xd4d answer however

**Comment by 0xd4d** [comment]
You can also try other decompilers, ILSpy v3.x, dotPeek, JustDecompile.

**Comment by rolandh** [comment]
Is there anyway to cache the decompiled outputs? Large static constructors seem to need to be decompiled repeatedly despite the same debugging session.

**Comment by 0xd4d** [comment]
It's cached and IIRC it's removed from the cache after 5 mins unless there's a new hit.

**Comment by rolandh** [comment]
Where is the 5 minute cache timeout in the code?

**Comment by 0xd4d** [comment]
Search for `DecompilationCache.cs`. And it's 30s, after that it's turned into a weak ref so could still be alive after that.

**Comment by 0xd4d** [comment]
EDIT: it's 5mins, see `OLD_ITEM_MS`
