### ISSUE TITLE
I cant edit method

### ISSUE THREAD

**Issue by iiWhiteCatAshy** [0xd4d/dnSpy#884]
I am using the version 5.0.5 and whenever I try to edit a method, it gives me a system error.

any suggestions on how I could fix it?
![a](https://user-images.githubusercontent.com/41234145/42724471-40d52718-87b6-11e8-9f23-ece49d758fd3.png)

**Comment by XenocodeRCE** [comment]
Try using latest files : https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts
