### ISSUE TITLE
couldnt edit method

### ISSUE THREAD

**Issue by IDontHaveAnAUsernameXD** [0xd4d/dnSpy#885]
hello guys, i just tried making mods in a game today but got an issue i cant even begin to understand
https://cdn.discordapp.com/attachments/346259249304829962/467928466072010753/unknown.png
- 5.0.5

- if i just click edit method, and simply press compile for no reason without editing anything at all it still shows the error. though whenever i change main.gs *and* from C# to either visual basic or IL the "lines" change numbers in the error console. and there will be different variables looking to be fixed
im editing an UnityScript assembly file.
maybe i need to edit in unityscript even tho it doesnt exist on dnspy? or is there a way to fully and completely ignore errors while changing methods?

**Comment by UlyssesWu** [comment]
When I see '$', I guess this is yet another issue about #118

**Comment by 0xd4d** [comment]
It's impossible to help without the assembly and repro steps.

**Comment by IDontHaveAnAUsernameXD** [comment]
ok thanks! guess ill just wait for a C# version

**Comment by IDontHaveAnAUsernameXD** [comment]
ill close this issue
