### ISSUE TITLE
Issue in Watch window when evaluating DateTime? - DateTime.

### ISSUE THREAD

**Issue by pawlos** [0xd4d/dnSpy#887]
- What version did you use?

dnSpy **v5.0.5**; tested also on the **AppVeyor build**

- Write down all steps needed to reproduce this issue. Also attach any needed files.
1. Open the following [exe](https://www.dropbox.com/s/e3lfy74ao1waie0/ConsoleApp1.exe?dl=0) in dnSpy (64-bit)
2. Put a breakpoint at the end of `Main` (`Console.ReadLine`) & Run & Wait until breakpoint hit
3. Observe the console output is 4 lines containing 30.00:00:00
![output](https://user-images.githubusercontent.com/1296768/42947215-1f2f31c0-8b6d-11e8-91c4-dcf53097ed6b.png)
4. Go to Watch window and add the same expressions to be evaluated as the ones that are used in `Console.WriteLine`'s
   
    Watch:
    `dt - dt2`
    `dt.Value - dt2`
    `dth.Date1 - dt2`
    `dth.Date1.Value - dt2`

5. Observe that evaluating expression 3 & 4 is giving wrong result. 
![dnspy-error](https://user-images.githubusercontent.com/1296768/42947416-9108de68-8b6d-11e8-83b0-32bcb7e555c7.png)

I've tested this behavior on x86, 64bit - it is the same, yet the incorrect value is different (between x86 vs 64bit). Compiled for .net 4.6. 

Doing this the same in VisualStudio's 2017 debugger yielded correct result.
![vs-ok](https://user-images.githubusercontent.com/1296768/42947428-9834cfee-8b6d-11e8-98e2-91b6c92f7a1e.png)

Source code is [here](https://gist.github.com/pawlos/1e2f42db5f92f721349e1a87964db3d8).

**Comment by 0xd4d** [comment]
Seems to be a problem with nullables, shorter repro:

```C#
new int?(1234)
new int?(1234).Value
```
