### ISSUE TITLE
C# editor cant recognise obfuscator generated classes

### ISSUE THREAD

**Issue by gamehack36** [0xd4d/dnSpy#893]
Used Version: v5.0.5.790 (latest)
What's up bro. My issue is when I just look at the code in the browser I can click on classes or methods and the softwares jumps to it, but when I am in the C# editor it makes some classes (mostly obfuscator [here .net reactor] generated) red (which I could click before) and I cant even translate the code with/without any modifications. 
I am talking about de/obfuscated assemblies mostly.
I attached you some screens in a zip here: https://www79.zippyshare.com/v/gnt24GVG/file.html
Hope you can make it working. it really hardens my work.  Thanks.    peace

**Comment by gamehack36** [comment]
its not a question. its a bug.
you need to fix this, it wil be great. :)

using <PrivateImplementationDetails>{6AEEBE58-34E6-4DC7-9770-1D250A5B674E};
is the goat.

**Comment by jnm2** [comment]
@gamehack36 You hurt your chances by being pushy. Deobfuscation is a whole new ballgame.

**Comment by gamehack36** [comment]
@0xd4d I used your deobfuscator, and my renamer, I also tried to rename manually. it doesn't helped tho. if something does not work properly, its a bug, I think.. yeah you're right it is other kind of code but nearly referenceable. You must be somewhat better than me in this topic otherwise I could fix your software by myself. IL is much more work, but it's okay for now, hope you can make it working. Thanks for all your work!!
Sorry for this, @jnm2 you too. I would really need this one. Wish you further successful work.

**Comment by 0xd4d** [comment]
Closing it, it's a dupe.
