### ISSUE TITLE
Internal Debug Error

### ISSUE THREAD

**Issue by 7GrandDadPGN** [0xd4d/dnSpy#895]
Hi while trying to deobfuscate a Program that has ConfuserEx I get the generic Internal Debug Error.
I used the Latest Version of DnSpy and .NET.
![image](https://user-images.githubusercontent.com/29617380/43274044-44960fe4-90bb-11e8-8768-ca8675feb38a.png)
![image](https://user-images.githubusercontent.com/29617380/43274111-7852950a-90bb-11e8-9869-d9c0407bd377.png)

Please Help 
Thanks

7GrandDadPGN

**Comment by 0xd4d** [comment]
No verison number: CHECK

No repro steps: CHECK

Create a new issue when you have time to add the required information.

**Comment by 7GrandDadPGN** [comment]
lol whats a repro step?

**Comment by 0xd4d** [comment]
You write down all the steps required to reproduce the issue. Your post has a picture of an error message, but not how to reproduce it.

**Comment by 7GrandDadPGN** [comment]
..ok

**Comment by 0xd4d** [comment]
Search the issues too, there was a fix for a similar problem not long ago: https://github.com/0xd4d/dnSpy/issues/886

**Comment by 7GrandDadPGN** [comment]
about that idk how to get the latest build and also i reviewed those threads and they didnt help me

**Comment by 0xd4d** [comment]
The readme has a link to it:

Latest build: https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts

**Comment by 7GrandDadPGN** [comment]
mk trying the build out

**Comment by 7GrandDadPGN** [comment]
nope it didnt work is there any fix?

**Comment by 0xd4d** [comment]
How could there be a fix if I can't reproduce it?
