### ISSUE TITLE
How to replace a reference to an outdated DLL?

### ISSUE THREAD

**Issue by malagrond** [0xd4d/dnSpy#896]
I searched for a solution to this, but was unable to find one. I have a program that references multiple DLL files. For context, the old references are all version 10.1.400.0 and the current (updated) DLLs are version 10.1.600.0 . How can I go about replacing or editing those references?

Sorry if I managed to miss this somewhere. Thanks in advance.

**Comment by malagrond** [comment]
Nevermind. I think the easiest solution is going to be just exporting to a .proj and editing from there. Just in case someone else gets stuck on this, I'm going to leave it and close it, but feel free to delete this if you don't think it's necessary.

**Comment by 0xd4d** [comment]
An easier solution is to use the built in hex editor or the metadata editor (which uses the hex editor). Just go to the `AssemblyRef` row and update the version number, save it and reload all assemblies.
