### ISSUE TITLE
can't find mono.dll for a unity 2017.4.7 program

### ISSUE THREAD

**Issue by pikachuk** [0xd4d/dnSpy#897]
I used the dnspy release present on this github, in order to debug a unity app, but  i noticed that i can't find any mono.dll in the files
i found the directory "MonoBleedingEdge" though containing the directory "EmbedRuntime" and "etc"
these directories don't contain any mono.dll too
so i don't really know what i should do

**Comment by 0xd4d** [comment]
See here: https://github.com/0xd4d/dnSpy/releases

**Comment by pikachuk** [comment]
i did download it there, the last one was for 2017.4

but i ended up debugging by converting the release to a debug build instead of replacing the patched mono.dll

**Comment by 0xd4d** [comment]
I've updated the zip files with the missing mono.dll files

- unity-5.6.6
- unity-2017.1.4
- unity-2017.1.5
- unity-2017.2.2
- unity-2017.2.3
- unity-2017.3.1
- unity-2017.4.0 - unity-2017.4.8

2018.x is different so haven't been added yet.
