### ISSUE TITLE
Help Me 

### ISSUE THREAD

**Issue by emre1601** [0xd4d/dnSpy#899]
I'm editing the method, but I'm getting errors in variables and class names
I have the $ sign, I remove them, but this time I get these errors.

Error Images: 
https://i.hizliresim.com/j6gz4g.png

**Comment by SlowLogicBoy** [comment]
Edit IL instructions instead of C# code.

**Comment by 0xd4d** [comment]
You can also deobfuscate it, those names will probably be renamed.
