### ISSUE TITLE
Limit plugin to run on specific dnspy x86 or x64 only

### ISSUE THREAD

**Issue by computerline1z** [0xd4d/dnSpy#900]
I write a debugger plugin and only want it to load on dnspy x86 or dnspy x64, I read the extension example, but can't find way how to check if the dnspy instance is 32/64 bit, and how to prevent the plugin to load, anyone has any idea how to check that ?

**Comment by computerline1z** [comment]
I just want to load some native in dnspy before debug start, if I load the x86 assebmly on x64 dnspy, while debug, it just thown exception, so I want to control the plugin in specific case, I found that the ExtensionConfig class control the load condition of plugin, but it not support architecture condition, anyway, thanks for you support and aweasome product :)

**Comment by 0xd4d** [comment]
```C#
if (IntPtr.Size == 4)
  Load32bitDll();
else
  Load64bitDll();
```
