### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by RDIL** [0xd4d/dnSpy#902]
Why no license?

**Comment by 0xd4d** [comment]
https://github.com/0xd4d/dnSpy/blob/master/dnSpy/dnSpy/LicenseInfo/GPLv3.txt

**Comment by Kryptos-FR** [comment]
From GitHub perspective, it is recommended to have the license visible at the root level.
As you can see [here](https://github.com/0xd4d/dnSpy/community), GitHub is not able to detect the license terms.
