### ISSUE TITLE
Feature request: Allow to dump entire objects when debugging

### ISSUE THREAD

**Issue by Klocman** [0xd4d/dnSpy#905]
At the moment as far as I know it's only possible to copy/save only value of the selected objects, but not their children. This is not practical for dumping large dictionaries or complex objects.

Ideally it would be possible to right-click on an object and select "Dump" or "Save", and receive a file with fully expanded data of child objects, all the way down. In case of a reference loop just skip dumping the branch.

**Comment by 0xd4d** [comment]
It's not something I plan to implement. There's a workaround, serialize the data using any available serializer or your own serializer. You can use Assembly.Load/LoadFile from the watch window then call your method from there as well.
