### ISSUE TITLE
Add option for disable GOTO code.

### ISSUE THREAD

**Issue by jclitwin** [0xd4d/dnSpy#907]
- What version did you use?
5.0.7

Yo,

It's possible to add in options for we disable goto in decompiled goto?

**Comment by 0xd4d** [comment]
You'll get goto statements if the decompiler can't do a better job, so adding an option won't work.

**Comment by Kein** [comment]
This is what I see in ILSpy version 4.0.0.4295-beta1
https://ghostbin.com/paste/j65h9

This is what DNSpy outputs:
https://ghostbin.com/paste/vqpt2

From `About` page:
	dnSpy.Decompiler.ILSpy (5.0.5.0)
	Copyright 2011-2014 AlphaSierraPapa for the SharpDevelop Team
	ILSpy decompiler

???

**Comment by UlyssesWu** [comment]
@Kein 
`5.0.5.0` is a version number for **dnSpy.Decompiler**.ILSpy. From the `Copyright 2011-2014` you can infer it still comes from ILSpy2. 

I guess it might be a huge work to port the decompiler from ILSpy (changing the backend from the crippled mono.Cecil to dnlib). Sometimes I wonder if we should create an adapter - a mono.Cecil implemented by dnlib (or some kind of code analyzer powered by roslyn?) which allows migration from mono.Cecil to dnlib without too much manual work...

**Comment by Kein** [comment]
Fair enough. Would be nice to have get a better readability with latest decompiler tho

**Comment by 0xd4d** [comment]
That's the version number of the exxtension.

**Comment by Kein** [comment]
Is there any plans to update decompiler? The goto issue is just one of many, I have encountered multiple other issues like, override method not being taken into account and the reference points to base method of a base class and so on.

**Comment by 0xd4d** [comment]
It's on the to do list. Feel free to send a PR. :)
