### ISSUE TITLE
[Debugger] Unable to see private fields in current instance

### ISSUE THREAD

**Issue by Kein** [0xd4d/dnSpy#908]
- What version did you use?
dnSpy v5.0.5

- Write down all steps needed to reproduce this issue. Also attach any needed files.

Using .NET Framework instance debugger on a .NET compiled app (targeting 4.0) - I can see public properties and local variables in Call Stack but no private field reflected on for current instance.

**Comment by 0xd4d** [comment]
Make sure you haven't enabled 'Public Members' (right click in Locals window to see the option)

It's also possible that there are custom attributes that prevent showing those fields, see the debugger options, eg. "Hide compiler generated members", etc.

**Comment by Kein** [comment]
`"Hide compiler generated members"`
Looks like that was it.

**Comment by Kein** [comment]
The issue is back, this time old trick can't help:
![image](https://user-images.githubusercontent.com/623756/63933038-22714d80-ca61-11e9-8593-121059e27bcd.png)
![image](https://user-images.githubusercontent.com/623756/63933048-2a30f200-ca61-11e9-8945-8be770b1dab3.png)

**Comment by Kein** [comment]
I'm also not seeing local variables and arguments in locals

**Comment by 0xd4d** [comment]
No repro.
