### ISSUE TITLE
How did you archive the same GUI as Visual Studio?

### ISSUE THREAD

**Issue by RealAquilus** [0xd4d/dnSpy#909]
Hi, i'm sorry this is not a issues.
I would like to know how did you archive such a good ui like the one of VS, i searched for framework that make that possible (the most promising i found is MahApps.metro) but still not as equal as your.
Thank you!

**Comment by Symbai** [comment]
He made nearly everything himself, except for the core text editor which is based on VS text editor but even for this he wrote thousands of lines. Take a look at https://github.com/0xd4d/dnSpy/tree/master/dnSpy/dnSpy/Themes

**Comment by 0xd4d** [comment]
It's open source so have a look there. ;)

**Comment by RealAquilus** [comment]
Sorry for the late response, thanks i will check it out and try to implement it, thanks a lot!!
