### ISSUE TITLE
dnSpy crashes when attached to fsianycpu.exe

### ISSUE THREAD

**Issue by mrakgr** [0xd4d/dnSpy#91]
It also crashes the Interactive session. Here is the exception:

    Unhandled exception at 0x00007FFB5C3CE71C (ntdll.dll) in dnSpy.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFB5C4222B0).

The F# Interactive is from the latest VS2015 14.0.23413. The CLR I am using is 4.0.30319.

This is that comes off the top of my head. I am trying to use dnSpy to debug some [F# performance](https://github.com/Microsoft/visualfsharp/issues/965) issues as seen here and for that I need to see the dynamic modules it produces. I also have the previous version of VS. I'll try it now...

    Unhandled exception at 0x00007FFB5C3CE71C (ntdll.dll) in dnSpy.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFB5C4222B0).

The same thing it seems with the 64-bit variant.

I'll try building dnSpy and tracking down the bug myself though this is outside my expertise.

**Comment by 0xd4d** [comment]
Confirmed.

Temporary workaround: Start debugging from dnSpy instead of attaching to it. At least it passed my quick test.

**Comment by mrakgr** [comment]
I am not sure what you mean. Is there a different way to debug in memory modules apart from dnSpy menu Debug -> Attach To Process? Loading .exe files is no good, if that is what you meant, because there are performance differences which I am trying to figure out.

**Comment by mrakgr** [comment]
Also, this is not related to this issue, but I do not know how to build the dnSpy. I get around 16k errors, most of them related to missing XML tags. I think this is because the dnlib and AvalonEdit libraries are missing. I hoped the IDE would restore them automatically, but it seems that did not happen.

I do not really have any experience with large projects and build systems as I mostly use F# for scripting. Should I be doing anything like inserting the aforementioned libraries manually into the project or is it something else that I am missing?

**Comment by drvink** [comment]
They're git submodules. After you `git clone` the dnSpy repo, do `git submodule update --init --recursive` inside the repo directory, and you should be good to go.

**Comment by drvink** [comment]
Also, what he meant was that you can have dnSpy launch the FSI executable itself instead of attaching to the FSI process that VS launches when you start F# Interactive through VS.

**Comment by mrakgr** [comment]
Ok, I'll try both of the above. What I did was simply download the zip of the repository, I'll try forking it.

I see what you mean now. I've tried opening fsianycpu.exe from dnSpy and running it with debugging, but it crashes as soon as I try doing anything.

**Comment by 0xd4d** [comment]
Try the latest commit I pushed. It worked for me.

**Comment by 0xd4d** [comment]
Or wait for the [build server](https://ci.appveyor.com/project/0xd4d/dnspy/build/artifacts) to finish compiling it.

**Comment by mrakgr** [comment]
I am trying to do the first, but Github is failing to clone for some reason, so thanks for the heads up on the second option. I'll give it another half hour and then head to bed.

**Comment by 0xd4d** [comment]
The [build](https://ci.appveyor.com/project/0xd4d/dnspy/build/artifacts) has already finished so no need to wait. ;)

**Comment by mrakgr** [comment]
Ok, it seems to be working properly. Good work.
