### ISSUE TITLE
I'm not entirely sure whats going on there

### ISSUE THREAD

**Issue by StackDoubleFlow** [0xd4d/dnSpy#911]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
5.0.7
- Write down all steps needed to reproduce this issue. Also attach any needed files.
![image](https://user-images.githubusercontent.com/22183359/44248150-84d91200-a1ae-11e8-910b-e7b6c201a3e4.png)
![image](https://user-images.githubusercontent.com/22183359/44248163-93272e00-a1ae-11e8-87e9-b349b76c078b.png)
Like the title says, I'm not sure whats going on. This is a unity game if that helps, and it might have something to do with that switch statement.

**Comment by StackDoubleFlow** [comment]
there is also 
![image](https://user-images.githubusercontent.com/22183359/44250229-282f2480-a1b9-11e8-997c-f94f90bd7104.png)

**Comment by 0xd4d** [comment]
Looks like `switch (string)`
