### ISSUE TITLE
[featurerequest] Show hexadecimal representation (bytes) column in Edit IL instructions

### ISSUE THREAD

**Issue by npetrovski** [0xd4d/dnSpy#913]
It will be really useful if I can see the hex values along with the IL instruction in the "Edit IL instructions" widow. 
For the moment I can see columns "Offset", "OpCode" and "Operand". I would like to see another column "Bytes" giving me the hexadecimal values of the OpCode+Operand. It will be even better (and faster to me) if I could edit the hex values instead of picking up from the drop-down of available OpCodes.

**Comment by 0xd4d** [comment]
It's a high level IL editor, not a hex editor so this will never be implemented. One reason is the tokens that some instructions use, are only known when you save the assembly. You can open the built in hex editor and overwrite the method body bytes if you absolutely need to use hex.
