### ISSUE TITLE
Allow Remote Debugging

### ISSUE THREAD

**Issue by Dispersia** [0xd4d/dnSpy#914]
Visual Studio has a very powerful tool, https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging that allows us to debug well... remotely. Would be nice to have this available for dnSpy to remote debug environments, as with the update to 4.7.1, our servers do not have that version and it's not wanted to update .net framework until our application uses it, but I could remote debug these apps running from a dev box instead.

**Comment by 0xd4d** [comment]
You can also build older versions. I checked the git history and found these commits:

dnSpy version | commit | .NET Framework version
--------------|--------|-----------------------
dnSpy 4.5.1 | 276c129 | .NET Framework 4.6.2
dnSpy < 4.0 | a64ee93 | .NET Framework 4.6

Update the submodules after checking out the older commits.

**Comment by Dispersia** [comment]
That's what I'm doing currently just so I can keep using it, but thought it would be a useful feature :)

**Comment by 0xd4d** [comment]
The .NET Core builds don't have a dependency on .NET Framework and can also be used.

**Comment by dsolovay** [comment]
Is remote debugging now supported? If so, how is it engaged? There is no UI element on dnSpy comparable to the "Connection Target" of Visual Studio's "Attach to Process" command.

**Comment by danielecapursi** [comment]
> Is remote debugging now supported? If so, how is it engaged? There is no UI element on dnSpy comparable to the "Connection Target" of Visual Studio's "Attach to Process" command.

@0xd4d any news?
