### ISSUE TITLE
Is there have "pretty code" function?

### ISSUE THREAD

**Issue by HillCat** [0xd4d/dnSpy#915]
- What version did you use?
latest 20180822  v5.0.5 X64

there are too many  annotation in the code . obstruct reading the code. Is there any helpful method to clean these annotation? see the image: (red box)
![2018-08-22_134324](https://user-images.githubusercontent.com/41800196/44445040-1d89ea80-a612-11e8-92ae-3831b69a7834.jpg)

**Comment by Dispersia** [comment]
View > Options > Decompiler > IL (or C#)  and choose what you want, I guess you don't want show tokens, RVAs and file offsets, nor il instruction bytes.

 If you're having a hard time reading it, you can just put it into C# anyway, and it won't have most of it (just per method).

**Comment by HillCat** [comment]
Thanks very much! It worked!
