### ISSUE TITLE
Invalid names, feature request

### ISSUE THREAD

**Issue by Igie** [0xd4d/dnSpy#916]
Latest version used. dnSpy v5.0.7

Hello,
As some decompiled fields have invalid names, would it be possible to add an option to rename them to valid names? Or maybe add Find and Replace mechanic with regex?

**Comment by 0xd4d** [comment]
Have you tried a deobfuscator? It should be able to rename all invalid names.

**Comment by Igie** [comment]
tried de4dot but simple drag drop does not change invalid names, could you provide some instructions? Invalid names generally are: 
public <ActivateObjects>c__Iterator0() {}
private sealed class <ActivateObjects>c__Iterator0 {}
internal int <i>__1;
internal object $current;

or similar with < > symbols or starts with $

**Comment by 0xd4d** [comment]
Those are compiler generated names, and the decompiler should be able to detect that they're iterators and convert the state machine to normal looking C# code. Make sure you have unchecked `Show hidden compiler generated types and methods`.

**Comment by 0xd4d** [comment]
Also make sure you haven't unchecked `Decompile enumerators` and `Decompile async methods`

**Comment by Igie** [comment]
Done what you said, still same output:

<using System;
using System.Collections;
using System.Diagnostics;
using UnityEngine;

public class ActivateSceneObjectsOnLoad : MonoBehaviour
{
	[ContextMenu("Activate")]
	public void Activate()
	{
		if (this.ObjectsToActivate != null && this.ObjectsToActivate.Length > 0)
		{
			for (int i = 0; i < this.ObjectsToActivate.Length; i++)
			{
				if (!object.ReferenceEquals(this.ObjectsToActivate[i], null))
				{
					this.ObjectsToActivate[i].SetActive(true);
				}
			}
		}
	}

	[DebuggerHidden]
	private IEnumerator ActivateObjects()
	{
		ActivateSceneObjectsOnLoad.<ActivateObjects>c__Iterator0 <ActivateObjects>c__Iterator = new ActivateSceneObjectsOnLoad.<ActivateObjects>c__Iterator0();
		<ActivateObjects>c__Iterator.$this = this;
		return <ActivateObjects>c__Iterator;
	}

	[ContextMenu("Deactivate")]
	public void Deactivate()
	{
		if (this.ObjectsToActivate != null && this.ObjectsToActivate.Length > 0)
		{
			for (int i = 0; i < this.ObjectsToActivate.Length; i++)
			{
				if (!object.ReferenceEquals(this.ObjectsToActivate[i], null))
				{
					this.ObjectsToActivate[i].SetActive(false);
				}
			}
		}
	}

	private void Update()
	{
		if (!this._started)
		{
			this._started = true;
			base.StartCoroutine(this.ActivateObjects());
		}
		if (this._finished)
		{
			Object.Destroy(this);
		}
	}

	public GameObject[] ObjectsToActivate;

	public bool Simultaneous;

	private bool _finished;

	private bool _started;
}>

settings: http://prntscr.com/kln9ej

**Comment by Igie** [comment]
[Assembly-CSharp.zip](https://github.com/0xd4d/dnSpy/files/2310729/Assembly-CSharp.zip)

ActivateSceneObjectsOnLoad class in root namespace

**Comment by 0xd4d** [comment]
I can't repro it, make sure you didn't disable iterator (enumerator) decompilation, see my post above. I used v5.0.7.

**Comment by 0xd4d** [comment]
> some classes contain cache variables like in ArenaCheat class. Setting are the same as before. Such issue was meantioned before i think

Yes, at least one issue should be opened so closing this one now.
