### ISSUE TITLE
Can't decompile the C# ExpressionTree

### ISSUE THREAD

**Issue by HillCat** [0xd4d/dnSpy#917]
- What version did you use?
dnSpy 5.0.5   latest version
Under existing conditions,I found that dnSpy can't decompile the C# ExpressionTree.
ILSpy can decompile the C# ExpressionTree correctlly by select the C# version 2.0
I want to know that if dnSpy can provide similar function.
![expressiontree](https://user-images.githubusercontent.com/41800196/44455202-078b2280-a630-11e8-8fd5-89b52d3e1afb.jpg)
![1111](https://user-images.githubusercontent.com/41800196/44455246-24275a80-a630-11e8-9a78-083c966d4d3c.gif)

**Comment by 0xd4d** [comment]
I haven't updated to the latest ILSpy decompiler engine yet so that could be a reason. However I think the v2.0 decompiler should still be able decompile it, it's possible it can't detect the pattern.

**Comment by 0xd4d** [comment]
I think I misunderstood your question, you don't want to see the output in the dnSpy pic above, but the longer version? There are some compiler options you can disable to not decompile expression trees.

**Comment by HillCat** [comment]
I want dnSpy have the same result  :
![2018-08-22_200911](https://user-images.githubusercontent.com/41800196/44462477-4b3d5680-a647-11e8-926f-8c7fd3f1b72c.jpg)

**Comment by 0xd4d** [comment]
Have you unchecked `Decompile expression trees` in the decompiler options?

**Comment by UlyssesWu** [comment]
`Decompile expression trees` (zh-CN: `反编译表达式树`) should be what you want exactly.

**Comment by HillCat** [comment]
Decompile expression trees  ，I"m sure , the selection  is checked.  
![2018-08-22_212925](https://user-images.githubusercontent.com/41800196/44466282-78433680-a652-11e8-9125-b2a92d3732b6.jpg)
there have the same result in ILSpy ,But , ILSpy have a option , you can change csharp version to "2.0". But Dnspy have no option like ILSpy.

**Comment by 0xd4d** [comment]
You should UNcheck it not check it.

**Comment by HillCat** [comment]
perfect! It worked. Thanks every one!  I'm very embarrassed for that.

**Comment by UlyssesWu** [comment]
It's non meaningless to hide Chinese characters. Everyone knows you are using a Chinese interface. Please close the issue when you feel you are answered.

**Comment by HillCat** [comment]
resolve
