### ISSUE TITLE
About Unity debug problem

### ISSUE THREAD

**Issue by SixGodZhang** [0xd4d/dnSpy#919]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
v5.0.7
- Write down all steps needed to reproduce this issue. Also attach any needed files.
**my win pc:**
Unity: 2017.3.1f1
dnSpy:v5.0.7
**problem:**
after i overwrited the mono.dll, i begined to debug the Unity and got the Unity crash.
**steps:**
1. build a development build with script debugging enabled
2.use dnspy decompile Assembly-CSharp.dll
3.add some log to code
4.compile dll
5.overwrite the mono.dll
6.get crash problem

i check the 32 or 64,it's right.but i don't know what cause this problem?

**Comment by 0xd4d** [comment]
You don't have to patch mono.dll if it's already a debug build. https://github.com/0xd4d/dnSpy/wiki/Debugging-Unity-Games

**Comment by SixGodZhang** [comment]
very thx
