### ISSUE TITLE
Feature Request: Auto-rename invalid characters

### ISSUE THREAD

**Issue by PhoenixICE** [0xd4d/dnSpy#92]
Since obfuscators like to rename everything to random crap, and you can't export the classes due to invalid characters, can there be an option to just rename all failed exported file names to class#.cs

**Comment by 0xd4d** [comment]
Try de4dot first, it should rename such classes to human readable strings.

**Comment by PhoenixICE** [comment]
Yeah I had already tried de4dot before jumping to dnSpy, de4dot fails to decompile (its using Confuser 1.9 - doesn't look like its officially supported)

**Comment by 0xd4d** [comment]
You must compile it yourself to get the latest changes.

**Comment by PhoenixICE** [comment]
not sure if you are referring to this project or de4dot but I'm using the latest binaries from the build server - https://ci.appveyor.com/project/0xd4d/de4dot/build/x.x.10/artifacts
