### ISSUE TITLE
Request code to IL preview

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#920]
Some assemblies are protected and cannot be edited via code as dnSpy fails to compile the code so I have to fallback to IL editing. My problem is that for more complex code I dont know the IL representation.

It would be nice if there is any way to write a few lines in a code window and show us the IL preview code as preview without anything of it gets injected, so I can see the IL code and then try to rebuild it in the method I want to edit.

Since the method edit is a dialog so we cannot click outside of it, this preview would have to be in the same window.

**Comment by jnm2** [comment]
@Symbai This is not an answer to your question, but two other tools that might help here are [SharpLab](https://sharplab.io/#v2:EYLgHgbALANALiAlgGwD4AEAMACdBGAbgFgAoU9AZlwCZsBhUgb1O1dyvSmwFkAKAShZtmJNtgC+pSSSA===) and LINQPad.

**Comment by 0xd4d** [comment]
Tokens and string offsets aren't known until the module is saved. See #913
