### ISSUE TITLE
No search window

### ISSUE THREAD

**Issue by ajud123** [0xd4d/dnSpy#921]
So I wanted to search thru all of those things in the assembly file, and there is no search window, i watched some videos on how to do it, all of them have some sort of a search window/tab at the bottom of the main window, i tried using the combination of CTRL+F and still nothing happens, am I doing something wrong?
Software version is 5.0.7 (x64)

**Comment by riQQ** [comment]
Use the magnifier icon in the toolbar or the shortcut Ctrl + Shift + K.
