### ISSUE TITLE
Save module error

### ISSUE THREAD

**Issue by gagmeng** [0xd4d/dnSpy#922]
- What version did you use?
The latest build.

- Write down all steps needed to reproduce this issue. Also attach any needed files.
Open Mailbird.exe by dnspy, don't make any change, save moudle with option-keep old maxstack value.
Save module error as below:
`Writing C:\Program Files\Mailbird\Mailbird.exe...
Instruction operand is null
Instruction is null
Operand is not a local/arg
Target instruction is too far away for a short branch. Use the long branch or call CilBody.SimplifyBranches() and CilBody.OptimizeBranches()
All files written to disk.`

[Mailbird.zip](https://github.com/0xd4d/dnSpy/files/2335222/Mailbird.zip)

**Comment by Awware** [comment]
Hello, this file obfuscated, obfuscated by ConfuserEX

**Comment by 0xd4d** [comment]
Those are messages that you typically see if it's an obfuscated assembly, try cleaning it first.

**Comment by gagmeng** [comment]
It's really an obfuscated assembly.
