### ISSUE TITLE
I edited lot DLL and so on but now problems

### ISSUE THREAD

**Issue by Gamerios** [0xd4d/dnSpy#925]
- What version did you use?
3.0.1  and now 5.0.7

- Write down all steps needed to reproduce this issue. Also attach any needed files.

I edited changed etc much DLL and other Files with dnSpy but now have a problm and i cant find a solution at google or with testing.

I change that  with edit method 👍 

**### #
using System;
using SRE.Sred;

namespace SRE
{

	public static class SR
	{
		
		static SR()
		{
			int maxSRs= 5080;
			if (1 != 0)
			{
				SR.Ma = maxSRs;
			}
			bool isTrue = false;
			if (3 != 0)
			{
				SR.IsTrue = isTrue;
			}
			int maxSR = 1050;
			if (4 != 0)
			{
				SR.Max = maxSR;
			}
			SR.Max = 1050;
			SR.Ma = 1050;
			SR.M = 320;
		}
#**

to

#

#
using System;
using SRE.Sred;

namespace SRE
{

	public static class SR
	{
		
		static SR()
		{
			int maxSRs= 5080;
			if (1 != 0)
			{
				SR.Ma = maxSRs;
			}
			bool isTrue = true;   // only this value changed !!!
			if (3 != 0)
			{
				SR.IsTrue = isTrue;
			}
			int maxSR = 1050;
			if (4 != 0)
			{
				SR.Max = maxSR;
			}
			SR.Max = 1050;
			SR.Ma = 1050;
			SR.M = 320;
		}
#

#

when i click compile i then get this:   then dll not work anymore because it removes lines dont know why :( 

**
#
using System;
using SRE.Sred;

namespace SRE
{
      public static class SR
	{
		static SR()
		{
			int maxSRs= 5080;
			SR.Ma = maxSRs;
		        bool isTrue = **true;   // only this value changed !!!**
			SR.IsTrue = isTrue;
			int maxSR = 1050;
		        SR.Max = maxSR;
			SR.Max = 1050;
			SR.Ma = 1050;
			SR.M = 320;
		}

#
**

**So what is wron now tested with version dnSpy 3.0.1 and 5.0.7 

I dont know what i do now wrong because at other dll all work only at that dll not :(

Thank you for helping me out :)

regardssss**

**Comment by UlyssesWu** [comment]
For such a simple modification, try learn and Edit IL.

**Comment by Gamerios** [comment]
thanks but why it works at other dlls and at this not ?

**Comment by 0xd4d** [comment]
It contains garbage if statements that either evaluates to true or false. The compiler is smart enough and removes them.

**Comment by Gamerios** [comment]
> It contains garbage if statements that evaluate to true. The compiler is smart enough and removes them.

But when that is removed dll not works anymore :(

**Comment by 0xd4d** [comment]
Most likely it's some code that checks the file to see if you've modified it.

**Comment by Gamerios** [comment]
> Most likely there's some code that checks the file to see if you've modified it.

Hmm yeah i checked whole dlls and exe codes etc found nothing but yeah could be i thought that the problem is because i got dll from someone else where the change to true not removed the code like at me and that dll works but is older :(

**Comment by Gamerios** [comment]
?
