### ISSUE TITLE
Feature request search text

### ISSUE THREAD

**Issue by Igie** [0xd4d/dnSpy#927]
There is no option to search for text, only objects, fields, variables etc

**Comment by UlyssesWu** [comment]
![dnspy-search-string](https://user-images.githubusercontent.com/4312781/45143291-7306ef80-b1ed-11e8-9227-bd7236859aaf.png)

I don't know what "text" you're talking about. If you want to search anything in source code, you can also export the project.

**Comment by Igie** [comment]
Yes, I meant source code, exporting works too though
