### ISSUE TITLE
How to remove k__BackingField

### ISSUE THREAD

**Issue by IamSanjid** [0xd4d/dnSpy#928]
Used the latest build from https://ci.appveyor.com/project/0xd4d/dnspy/build/artifacts

The problem is it shows the Field correctly(Picture: http://prntscr.com/kr7r5t) but in a method, it shows something with k__BackingField. 

the DLL file:

[Assembly-CSharp.zip](https://github.com/0xd4d/dnSpy/files/2356258/Assembly-CSharp.zip)

**Comment by 0xd4d** [comment]
It's an obfuscated assembly, so you must use a deobfuscator or write a tool to fix it.

**Comment by IamSanjid** [comment]
Well what exactly I have to change I mean I just have to edit the method's body?

**Comment by 0xd4d** [comment]
You have to analyze the file and figure out how to fix it. Then write the code yourself. Have a look at de4dot.
