### ISSUE TITLE
Error PresentationFramework 

### ISSUE THREAD

**Issue by sourceskyboxer** [0xd4d/dnSpy#930]
I don't understand why do you ignore me since I reported here. Why do you not tell me but dnSpy supports Mono / Ubuntu? Hahaha You said that. How do I get fucking PresentationFramework?

PLEASE BUILD WITHOUT PRESENTATION-FRAMEWORKS!!!
Why do I need PresentationFramework? But I am using Ubuntu 16.04 + Mono 5.19.0

**Comment by UlyssesWu** [comment]
You can make an [Avalonia](https://github.com/AvaloniaUI/Avalonia) port by yourself rather than keep pushing others.

**Comment by 0xd4d** [comment]
dnSpy is a WPF app so it's Windows only. Feel free to port it to some other UI framework if you have time.

**Comment by sourceskyboxer** [comment]
Where is advanced library for dll or exe to c# or visual basic and il-disassembler? dnLib? Or I should write own? I don't find where is function since load exe or dll assembly? Thanks!

**Comment by sourceskyboxer** [comment]
Oh sorry my bad English. I mean dnLib is engine for disassembly with dll and exe from Mono or Net Frameworks. 

Is it correct or wrong?
I really want know how do I load net assemblies like you have made dnSpy application. like "File" -> "Load" -> open net assemblies -> loading into list and textbox.

That is why I want find like you made. Because I am working under Ubuntu 18.04 with Gtk Sharp 3.22.8 and under macOS with XamMac/AppKit

I would like to be happy with macOS- and linux-users. I feel sad because macOS- and linux-users wait longer for disassembles with net assemblies.

Thanks and I am sorry for my bad English...

**Comment by 0xd4d** [comment]
[dnlib](https://github.com/0xd4d/dnlib) is used to load the metadata, you can read its README on how to open an assembly.
