### ISSUE TITLE
using conv.i4 to convert bool into int

### ISSUE THREAD

**Issue by Neutron3529** [0xd4d/dnSpy#931]
version: dnSpy 5.0.3
while editing IL code, I could easily use `conv.i4` to convert bool into int
```
0	0000	ldsfld	bool Assets.StreamerEffects::Flag_TreeDoubleYield
1	0005	conv.i4
6	000A	ret
```
but when I finish editing, I got
```
		protected virtual int DoHarvest()
		{
			return StreamerEffects.Flag_TreeDoubleYield ? 1 : 0;
		}
```
The quesion is, when use Ctrl+shift+E and compile such code again, the IL code will change:
```
0	0000	ldsfld	bool Assets.StreamerEffects::Flag_TreeDoubleYield
1	0005	brtrue.s	4 (0009) ldc.i4.1 
2	0007	ldc.i4.0
3	0008	ret
4	0009	ldc.i4.1
5	000A	ret
```
As a result, the code also change:
```
		protected virtual int DoHarvest()
		{
			if (!StreamerEffects.Flag_TreeDoubleYield)
			{
				return 0;
			}
			return 1;
		}
```
actually such code is equivlent to `return StreamerEffects.Flag_TreeDoubleYield ? 1 : 0;`, but it is too complex for me.
I wonder that is there some better method to deal with conv.i4?

**Comment by 0xd4d** [comment]
The code does similar things, but the 2nd code forces the return value to be 0 or 1. A boolean should only be 0 or 1 but AFAIK the jitter doesn't enforce it so in the 1st example if the bool value is 2 (true), it will return 2 instead of 1.

**Comment by UlyssesWu** [comment]
Yes it will return 2 (tested).

And I will recommend remove `conv.i4` in the 1st example only if you are not using this `bool=2` trick,  since this instruction is unnecessary.

**Comment by Neutron3529** [comment]
I found it..
I learn C# by myself, I even don't know such thing:

> Conversions
> 
> In C++, a value of type bool can be converted to a value of type int; in other words, false is equivalent to zero and true is equivalent to nonzero values. In C#, there is no conversion between the bool type and other types. For example, the following if statement is invalid in C#:
