### ISSUE TITLE
fail to recompile class after no-change decompile

### ISSUE THREAD

**Issue by peddroelm** [0xd4d/dnSpy#933]
- What version did you use?

	dnSpy (5.0.7.0)

- Write down all steps needed to reproduce this issue. Also attach any needed files.

I'm trying to figure out some hidden game mechanics of Lords Of Xulima Steam game. 

Managed to edit a C# class with dnSpy and after saving it produced the expected feedback in the ingame combat damage log .  (YAY) .. 

However when I try to compile another class (I think its their custom game engine JXEngine) dnSpy fails to re-compile it 

save.Name = CS$<>8__locals3.name; 

endless  bunch of errors starting with the line above. (the original game DLL verified by steam with no change - dnSpy can't decompile and re-compile the class )

My work around for the moment was edit method C# instead of edit class C# .. Could do my change , re-compile, saved .dll restart game and now combat game log prints extra lines signaling when a new character's 'turn' begins (my change) .. 

![dnspy](https://user-images.githubusercontent.com/29655395/45318221-e89ff200-b544-11e8-994d-b9bf729c76d4.jpg)

**Comment by 0xd4d** [comment]
Edit Class is rarely needed, try to use Edit Method as much as possible since it changes less things. The more you try to change, the more likely it is that something goes wrong.

Your picture shows a decompiler failure, you can try fixing that yourself by changing `CS$<>8__locals3.name` to `name`.
