### ISSUE TITLE
[Question] How to add Comments / Rename functions & Members without editing assembly?

### ISSUE THREAD

**Issue by HurricanKai** [0xd4d/dnSpy#934]
i found #266 and found it fixed years ago, but i cant find the feature anywhere?
I love this software, but im really missing this, can someone explain to me how to add comments and rename stuff?

**Comment by SlowLogicBoy** [comment]
Duplicate of #266

**Comment by 0xd4d** [comment]
#266 hasn't been implemented yet since it's still open. So in other words, you can't do it at the moment.

**Comment by HurricanKai** [comment]
Oh :sweat_smile: I didn't notice, sorry ^^
