### ISSUE TITLE
[Question] How to "insert" a property?

### ISSUE THREAD

**Issue by jojorne** [0xd4d/dnSpy#935]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
v5.0.5

- Write down all steps needed to reproduce this issue. Also attach any needed files.

OK, I need to modify a class that is serialized and sent as packet.
The order of the members is important, since it is packed by their order.
And I cannot change the serialize method because I only have the Client.

Exemple:

```C#
public class Student
{
	public string Name { get; }
	public int Age { get; }
    
	public Student() { }
}
```

Now the class was updated to include "ID":

```C#
public class Student
{
	public int ID { get; }
	public string Name { get; }
	public int Age { get; }
    
	public Student() { }
}
```

but what I'm getting is this:

```C#
public class Student
{
	public string Name { get; }
	public int Age { get; }
   
	public Student() { }

	public int ID { get; }
}
```

So, how do I place the ID in first place?

**Comment by 0xd4d** [comment]
You can try enabling 'Preserve tokens' when saving the module. However it's possible that it won't work on Mono since I don't think it supports some of the undocumented .NET metadata tables.

**Comment by jojorne** [comment]
I got a "dummy_ptr" namespace by doing that and the ID is still last.
Is there a way to edit the MD Table to sort the members?

**Comment by 0xd4d** [comment]
It's not possible with dnSpy at the moment.

You could use eg. dnlib and change the order yourself and then save the module.
