### ISSUE TITLE
Debugging a unity game with release build

### ISSUE THREAD

**Issue by HasanAliKaraca** [0xd4d/dnSpy#937]
Hi i'm a first time user. I used newest version of dnspy and try to debug a release build. I tried all the combinations on the wiki (x86-x64 exe - x86-x64 dlls). I found one of the combination starts the game. 

My problem is game seems running in task manager but nothing happens on the screen. What is causing this issue? How can i solve it?

**Comment by 0xd4d** [comment]
Try switching to the game or check if it's breaked in the debugger (press run to continue).
