### ISSUE TITLE
.NetFramework 4.7.1 required!

### ISSUE THREAD

**Issue by CuteLeon** [0xd4d/dnSpy#938]
Version I use : V5.0.7.0;
This issue : I'm sure I haved Installed .Net Framework 4.7.1 on my PC (see in the Screenshot), but everytime when I launch the dnsSpy.exe, the program always show a MessageBox about ".Net Framework required" twice (see in the screenshot)，and I tried dnSpy 3.0.0, this version can run normally.

![tim 20180915185824](https://user-images.githubusercontent.com/17419770/45585643-5ddf3e80-b91a-11e8-868a-a52dafac73d9.jpg)
![tim 20180915185903](https://user-images.githubusercontent.com/17419770/45585644-5ddf3e80-b91a-11e8-90b1-89fd59522427.jpg)

**Comment by 0xd4d** [comment]
That only shows that you have the .NET Framework 4.7.1 developer pack installed. Try installing the latest version of the runtime.

**Comment by CuteLeon** [comment]
yeah, thx for your reply, I have got the problem, there was something wrong during I install VS2017. thank u and thank dnSpy.
