### ISSUE TITLE
Feature Request: Import - Export Instructions in Method Body to text file

### ISSUE THREAD

**Issue by skypeaful** [0xd4d/dnSpy#94]
Can 0xd4d update dnSpy Import - Export Text (which content operant and opcode) in right-click of Edit IL Instruction.
For example export code format like this to .txt
a.txt
---------------------------------------------------------------------------------------------------------------------
ldstr	"Test"
call	void [mscorlib]System.Console::WriteLine(string)
ldstr	"Hello"
call	void [mscorlib]System.Console::WriteLine(string)
ldstr	"What's up?"
call	valuetype [System.Windows.Forms]System.Windows.Forms.DialogResult [System.Windows.Forms]System.Windows.Forms.MessageBox::Show(string)
pop
ret
---------------------------------------------------------------------------------------------------------------------
It will be easy to edit IL in txt format, if il code so long, manual edit, delete opcode in Edit Method Body will take so much time than edit txt.
I hope 0xd4d will update soon. This way will made dnSpy more powerful :D
Thank

**Comment by li0nsar3c00l** [comment]
editing opcodes is much faster than editing text. i dont know, why editing the text should be faster

**Comment by 0xd4d** [comment]
This doesn't seem to be very useful, when compared to #4, so I'll close it.
