### ISSUE TITLE
Couldn't find the edited method. Make sure you didn't add or remove 'static' or 'Shared' or changed the parameter types, return type or method name

### ISSUE THREAD

**Issue by AndnixSH** [0xd4d/dnSpy#940]
Come across an dll that have some function names obfuscated but it still modifyable and game still works fine after modifying. There is one Class that dnSpy failed to compile, I got "Couldn't find the edited method" error when I try to compile code even unmodified in BaseFightObj class.

```
Severity	Code	Description	File	Line
Error	IM0002	Couldn't find the edited method. Make sure you didn't add or remove 'static' or 'Shared' or changed the parameter types, return type or method name: System.Boolean BaseFightObj::get_InContinuedCast()
```		

Here is the file:

[Managed.zip](https://github.com/0xd4d/dnSpy/files/2386671/Managed.zip)

![image](https://user-images.githubusercontent.com/40742924/45597705-6e51f080-b9d0-11e8-9895-33fbebe7195b.png)

**Comment by AndnixSH** [comment]
I only rename the getter to match the same name as the obfuscated name and it worked. de4dot does its job, rename all getter and setter to match with the obfuscated name but it will be harder to know which functions. I guess I'll have to write them all down.

**Comment by 0xd4d** [comment]
Here's the code, should be easy to fix: https://github.com/0xd4d/dnSpy/blob/master/Extensions/dnSpy.AsmEditor/Compiler/ModuleImporter.cs#L670

**Comment by AndnixSH** [comment]
Thanks. It's not a big deal, I'll do my way

**Comment by 0xd4d** [comment]
> And it's not really fun to add non-sense labels like that.

The labels are there so people know that it's up for grabs and easy to fix.

**Comment by AndnixSH** [comment]
oh ok.. should we close the issue or keep it open?

**Comment by 0xd4d** [comment]
Keep it open until it's fixed
