### ISSUE TITLE
Documentation for extending dnSpy with another backend.

### ISSUE THREAD

**Issue by kobi2187** [0xd4d/dnSpy#941]
Hello, is it possible to extend dnSpy with another language backend, just as there are for c# and vb?
I have a feeling it can ease in porting efforts.
Please add a little documentation or just point me to where in the code is the specific implementation for each language constructs.
I am thinking about Nim, which is pretty flexible. it's not dotnet based, but I hope I can match at least some of c#'s constructs, enough to help me port some valuable libraries.
Thank you for this cool product.
please reply with some information, Thanks!

**Comment by 0xd4d** [comment]
Have a look at the `IDecompiler` and `IDecompilerProvider` interfaces.
