### ISSUE TITLE
save code disabled in V5.x.xxx

### ISSUE THREAD

**Issue by gagmeng** [0xd4d/dnSpy#943]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
5.0.8
- Write down all steps needed to reproduce this issue. Also attach any needed files.
The save and save all function is disabled in dnspy 5.x.xxx，pls see the below snapshot.
[http://www.hostpic.org/images/1809211433310095.jpg](url)

**Comment by gagmeng** [comment]
But the save and save all function works fine in dnspy 4.5.X.

**Comment by 0xd4d** [comment]
Looks like a dupe of #946
