### ISSUE TITLE
Request to put back "Save code"

### ISSUE THREAD

**Issue by xp4xbox** [0xd4d/dnSpy#946]
In the older version of DNSpy that i have, you used to be able to save an individual code file. But in the recent versions you cannot do that anymore.

This feature was extremely useful and I would really like it back.
 
![untitled](https://user-images.githubusercontent.com/24964930/45931284-05bbc400-bf3a-11e8-9ff0-6e1622e6bbf0.png)

**Comment by 0xd4d** [comment]
It was removed because it was confusing. Does it save the whole project? Does it save the edited module? No, it did something much less useful. A workaround is to just copy and paste the text in the text viewer.

https://github.com/0xd4d/dnSpy/issues/817

**Comment by xp4xbox** [comment]
Too bad I am constantly saving code files with long names. What about adding a right click option to the file?

**Comment by 0xd4d** [comment]
The context menu is big enough already, so not likely to happen.

You can restore the code in your own private build or add your own extension with the old code. 6ca9aabb3199489475d91e7c8c98ddab28ad29ee
