### ISSUE TITLE
Does minor patch available?

### ISSUE THREAD

**Issue by Neutron3529** [0xd4d/dnSpy#947]
My English is poor, but the idea may not.

When using dnSpy, Save all(Ctrl+Shift+S) may always change the whole dll file.
I wonder are there some method to do just a minor patch.
e.g., edit 0x04 to 0x17 will change ldarg.2 into ldc.i4.1
It is very tough for me using hex editor to do this, so i wonder whether dnSpy could do such patch.
What's more, I wonder whether dnSpy could generate a patcher to patch C# .dll file to what we want.

that is because unity game may update, and dlls, especially Assembly-CSharp.dll will change after every update.
but, there compute logic remains the same.
so i wonder that whether dnSpy could generate a executable patch, which could patch different version of  .dll files into the same type(e.g., patch "int Player.money.get(value)" to "return 100000" or something like that.)

Again, sorry for my poor English.

**Comment by SlowLogicBoy** [comment]
dnSpy wont do that for you. You will have to write your own patcher by using some kind of assembly manipulation library like dnlib or Mono.Cecil.
https://github.com/ioncodes/dnpatch this library might help with that too.

**Comment by Neutron3529** [comment]
thx~
