### ISSUE TITLE
Right click context menu suggestion

### ISSUE THREAD

**Issue by fietronic** [0xd4d/dnSpy#954]
Isn't really a bug, just UI beautification suggestion. 

substring input text to the context menu so it doesn't take up the whole screen.

![image](https://user-images.githubusercontent.com/5356864/46241190-09a47780-c37a-11e8-9ada-a4942511d4d3.png)

It's really not necessary to show the whole text, the user knows what they clicked on.

I realize that it's not high priority because most strings passed to the context menu are not going to be that long... but it would be nice.

I tried to find the code to edit it myself but I'm not familiar enough with the project. Shouldn't be too hard to implement for anyone familiar with the code.

**Comment by pawlos** [comment]
@fietronic @0xd4d is it ok to take this? I can have a look and fix this one.

**Comment by 0xd4d** [comment]
Yes you can do that. No-one else seems to be working on it.

**Comment by 0xd4d** [comment]
Fix has been merged

**Comment by fietronic** [comment]
Great Job!
