### ISSUE TITLE
Instruction operand is null

### ISSUE THREAD

**Issue by manojdjoshi** [0xd4d/dnSpy#96]
edit obfuscated(without deobfuscat) exe  error show on save 
Instruction operand is null
All files written to disk.
exe not run and small size

**Comment by linquize** [comment]
Can you give sample code to decompile?

**Comment by linquize** [comment]
Can you give sample code to decompile?

**Comment by 0xd4d** [comment]
You have to deobfuscate it first. dnSpy isn't a deobfuscator.

**Comment by danperor** [comment]
would someone give me a deobfuscate tools?
