### ISSUE TITLE
Adding File Type Icons

### ISSUE THREAD

**Issue by InochiPM** [0xd4d/dnSpy#962]
I'm gonna post this here cause I have a question. I know how to add resources and i got some file type icons inside of this program im translating, But i have no clue how to execute them in the .dll's  or what i have to add in order to make them appear and work for the file types associated with this program.

Does anyone know how to do this that can show me what I need to do or can do it for me?  
All of the info for this program are inside of the dll's but the program icons are held inside the .exe files. 
Do i have to add them there?

**Comment by 0xd4d** [comment]
This doesn't seem to be dnSpy related.
