### ISSUE TITLE
Add COMPLUS_ZapDisable to Wiki

### ISSUE THREAD

**Issue by jogibear9988** [0xd4d/dnSpy#964]
add

     set COMPLUS_ZapDisable=1 

to wiki page https://github.com/0xd4d/dnSpy/wiki/Making-an-Image-Easier-to-Debug

see
https://blogs.msdn.microsoft.com/sburke/2008/01/29/how-to-disable-optimizations-when-debugging-reference-source/

it may also be helpfull when using dnSpy

**Comment by 0xd4d** [comment]
That's never worked for me, I still can't see all locals. The only solution is to patch the assembly attributes as explained in the wiki.

**Comment by 0xd4d** [comment]
I've added it to the wiki page. It doesn't seem to do much, but maybe it will help someone.
