### ISSUE TITLE
Error message when I try to debug.

### ISSUE THREAD

**Issue by absolutenothing** [0xd4d/dnSpy#965]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
v5.0.9
- Write down all steps needed to reproduce this issue. Also attach any needed files.
I keep getting these errors: https://vgy.me/NjlwGW.png

**Comment by 0xd4d** [comment]
Have you searched the issues? There are many similar questions, and a solution.

**Comment by 0xd4d** [comment]
https://github.com/0xd4d/dnSpy/issues/572#issuecomment-339510779
