### ISSUE TITLE
dySpy eats up all my 8 GB memory while choosing export to project

### ISSUE THREAD

**Issue by mindoff6502** [0xd4d/dnSpy#971]
I'm using dnSpy 5.0.4,it seems the newest 5.0.7 doesn't support drag file to open?
Anyway.

I'm trying to export a game called Two Point Hospital, a unity3d game,trying to export Assembly-CSharp.dll to export the source code to analyse more info.Then my computer stunned,nothing can move except the mouse.
After 2 minites I found it is because dnSpy eat up all my 8 GB memory.This is the first time I encounter this.

Then I try ILSpy,Successfully export same file and only costs 230 MB memory while working.

So will you  optimize some algorithm to be memory friendly?

Thanks.

**Comment by mindoff6502** [comment]
OK,try newest 5.0.9 version,the problem still exists.
Here are the dll files.
https://github.com/mindoff6502/CacheFiles/blob/master/7z/TPH.7z
download THP.7z

try to export Assembly-CSharp.dll
not Assembly-CSharp-firstpass.dll

see will that be a problem.I tried 5.0.4 and 5.0.9,both have same memory problem.

**Comment by 0xd4d** [comment]
It's still using the old ILSpy decompiler. Also try the 32-bit version to limit memory usage.

**Comment by 0xd4d** [comment]
I can't repro this with the latest build.

**Comment by 0xd4d** [comment]
BTW, you can attach files here, just drag and drop.

**Comment by 0xd4d** [comment]
I can repro it if I only open one file in dnSpy.

Workaround: close all files, drag all files to assembly explorer.

**Comment by 0xd4d** [comment]
The latest build has the fix.
