### ISSUE TITLE
Could not attach to process PID=3664 in dnSpy

### ISSUE THREAD

**Issue by Tianjiao** [0xd4d/dnSpy#975]
![capture](https://user-images.githubusercontent.com/1756057/47191797-f46ca880-d37b-11e8-998d-3d9b4d216746.PNG)

Hello, when I try to debug an .NET app in the dnSpy, it tells me that it could not attach to the process of the sample. Thanks for your help.

- What version did you use?
Latest version. (x86 build as the sample file and run dnSpy as Administrator)
- Write down all steps needed to reproduce this issue. Also attach any needed files.

1. Start the main .exe from the sample.
2. Open "Debug" menu(Alt + D) in dnSpy
3. Open "Attach to process" submenu(Ctrl + Alt + P) in dnSpy
4. Select the .exe of the sample in the process list, then press the "Attach" button.
5. The .exe will crash and dnSpy says "Could not attach to process PID=?"

Needed file:
[Sample.zip](https://github.com/0xd4d/dnSpy/files/2494074/Sample.zip)

**Comment by Tianjiao** [comment]
I think so.

But when I try to debug it in 2 debuggers, I find that one debugger provides built-in Anti-AntiDebug feature inside itself so that it can directly attach to the process, the other loads customized Anti-AntiDebug plugin to do the task.

So I ask for **2 feature requests** for dnSpy:

- [ ] built-in **Anti-AntiDebug feature** in dnSpy
- [ ] better **plugin documentation** and **plugin templates** to help user to develop Anti-AntiDebug plugin in dnSpy

I just want dnSpy to be strong enough to debug ANY assembly.
___________________________________________________________
If you want to patch it beforehand, you could use an unpacker to remove the AntiDebug DLL. There's an available tool, namely _de4dot_, but it has not been updated for this protector for long.
___________________________________________________________
So we should use either updated dnSpy or updated _de4dot_ to debug this assembly. Since this is the dnSpy thread, I expect dnSpy here.

**Comment by 0xd4d** [comment]
It's not dnSpy's job to hide itself from all anti-debug code. It provides basic protection, if you want extra you can write a plugin.

**Comment by 0xd4d** [comment]
It's not dnSpy's job to hide itself from all anti-debug detection code. If you want more than basic protection, write your own extension or use someone elses.

**Comment by 0xd4d** [comment]
I've added some hooking code that patches IsDebuggerPresent and CheckRemoteDebuggerPresent. You can check the code to see how it's done and implement your own extra fixes. Search for all uses of `ExportDbgNativeFunctionHookAttribute` in the source code.

**Comment by Tianjiao** [comment]
Thanks for your API.
Thanks again.
