### ISSUE TITLE
Analyzer doesn't find "loose" references

### ISSUE THREAD

**Issue by smourier** [0xd4d/dnSpy#976]
In the latest version, when using the Analyze function, the code does this (`ScopedWhereUsedAnalyzer.cs` line 250):

 ```
 if (AssemblyNameComparer.CompareAll.CompareTo(asm, reference) == 0) {
    found = true;
    break;
  }
```

The problem is, sometimes, we can load an assembly that has a reference to `mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089` for example, while the current `mscorlib` assembly loaded in dnSpy is `mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089`. In this case, the code will not match. I believe other tools like .NET reflector do the match.

I understand this behavior may be a by design decision today, but I think it should deserve one or more GUI options to be able to change the way it works.

**Comment by 0xd4d** [comment]
Fix has been merged
