### ISSUE TITLE
Why can't build the latest?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#978]
It seems dnSpy is hard to build from supporting .net core.
I can build succeed 5 times in 10 times without any editing.
Today, I update dnSpy to the lastest, and I can only build it succeed one time, and I allways failed now.

![x](https://user-images.githubusercontent.com/2529999/47264477-99d57700-d54a-11e8-8bc2-2ddbe5e58c32.jpg)

Please see my picture, Visual Studio allways skip building dnlib, but it tell me can not find dnlib.dll.
I try clean and rebuild more than 30 times, even if I right click the project "dnlib" and build it, I get:
```
1>------ Skipped Build: Project: dnlib ------
1> 
========== Build: 0 succeeded or up-to-date, 0 failed, 1 skipped ==========
```

**Comment by CreateAndInject** [comment]
Why do you use new SDK project?
All your project(dnSpy, de4dot) can't build in my pc after it.

**Comment by li0nsar3c00l** [comment]
Then you should update your sdk to support the new project template.

**Comment by 0xd4d** [comment]
It's probably because mbuild and VS cache various things in .vs and obj folders. Delete them all or clone the repo again into a new dir.
