### ISSUE TITLE
Target .NET Framework 4.5 or 4.6, maybe also switch to VS2015

### ISSUE THREAD

**Issue by 0xd4d** [0xd4d/dnSpy#98]
1. dnSpy still targets .NET Framework 4.0 because of XP but is anyone still using XP? .NET Framework 4.6 can be installed on Windows 7 and later OSes.

2. The projects (except for the Roslyn scripting module) can be compiled with VS2010. VS2015 is a free download so might upgrade to VS2015 and C#6 too. This only affects developers not users.

**Comment by 0x53A** [comment]
Regarding C#: If you reference the nuget https://www.nuget.org/packages/Microsoft.Net.Compilers/ you can use the C# 6 compiler without vs 2015.

A developer using vs 2013 (or lower) might see red squiggles when C#6 functions are used, but it will correctly compile.

**Comment by 0xd4d** [comment]
I will definitely target 4.6 (done) and probably switch to VS2015. I'll wait about a week and if I don't hear a good reason not to, I will do it.

**Comment by kao-was-here** [comment]
Because of this, it's impossible to run DNSpy on Win7 anymore, as .NET 4.6.1 refuses to install with "Blocking Issues: The .NET Framework 4.6.1 is not supported on this operating system."

May I respectfully ask you to reconsider this change?

**Comment by 0xd4d** [comment]
dnSpy only targets 4.6.1, and I have successfully run dnSpy on Windows 7 x64. I even think I used the 4.6.1 installer to install it.

**Comment by kao-was-here** [comment]
Latest build doesn't work on my machine (32bit Win7, .NET 2.0/3.5/4.0/4.5 installed, .NET verifier log attached). When executed, this message appears:

> ---------------------------
dnSpy.exe - This application could not be started.
---------------------------
This application requires one of the following versions of the .NET Framework:
 .NETFramework,Version=v4.6
Do you want to install this .NET Framework version now?

When pressing Yes, the following page appears: http://dotnetsocial.cloudapp.net/GetDotnet?tfm=.NETFramework,Version=v4.6&processName=dnSpy.exe&platform=0000&osver=5&isServer=0

Then http://download.microsoft.com/download/3/5/9/35980F81-60F4-4DE3-88FC-8F962B97253B/NDP461-KB3102438-Web.exe?amp;source=dotnet gets downloaded, which fails with an error message I mentioned earlier.

[setupverifier_main_03-29-16_23.50.48.txt](https://github.com/0xd4d/dnSpy/files/194389/setupverifier_main_03-29-16_23.50.48.txt)

**Comment by 0xd4d** [comment]
Is your OS fully updated? (try Windows update if possible). It's possible that the installer requires a later version of some OS component.

**Comment by 0xd4d** [comment]
I think the 4.6 installer (I think the 4.6 installer is still available from MS) also requires some updated Win7 build, eg. Win7 SP1. You could try grabbing the 4.6 installer and see if it gives the same error.

**Comment by kao-was-here** [comment]
No, my Windows 7 is not fully updated. It's a VMWare image, frozen in a tested and stable state and used exclusively for RE purposes. However, I doubt anyone wants to try to hunt for obscure Windows updates just to be able to run DNSpy.

Is there an actual technical reason to require .NET 4.6+? If not, I would ask you to reconsider and target 4.5 for the moment.

**Comment by 0xd4d** [comment]
.NET Framework 4.6 requires Windows 7 SP1, which I wouldn't call an obscure update to Win7RTM. Windows 7 SP1 was released in [2011, 5 years ago](https://en.wikipedia.org/wiki/Windows_7#Service_Pack_1).

The easiest solution for you would be to undo 44abd6117e64ad11427818334768c1639a1426be and compile it yourself. Right now only the scripting plugin requires DNF 4.6 but this is something I expect to change.

Or you could update your Win7 VM image. Aren't most Win7 installations already using SP1? It would be a more realistic VM image.
