### ISSUE TITLE
Would it be possible to add a Intermediate Window ? 

### ISSUE THREAD

**Issue by xXxTheDarkprogramerxXx** [0xd4d/dnSpy#980]
This is probably a really stupid question but would it at all be possible to add a intermediate window to dnSpy ? 
Similar to how we debug in Visual Studio? i have an obfuscated app which has a few methods that are not linked to any buttons which i would like to be able to fire

**Comment by 0xd4d** [comment]
You can call methods by using the watch window.

**Comment by xXxTheDarkprogramerxXx** [comment]
How exactly would i call the method ? 
https://i.imgur.com/WzNZllh.png

**Comment by 0xd4d** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0103

Make sure the method exists.
