### ISSUE TITLE
dnSpy generated invalid code

### ISSUE THREAD

**Issue by yangshuairocks** [0xd4d/dnSpy#981]
- What version did you use?
v5.0.6

- Write down all steps needed to reproduce this issue. Also attach any needed files.
1. Download this zip fill and extract. You get a dll file.
[test.zip](https://github.com/0xd4d/dnSpy/files/2516620/test.zip)

2. Search for `Class86` and you will find the method `method_3` which has the following content.
```
	// Token: 0x0600078D RID: 1933 RVA: 0x000178C0 File Offset: 0x00015AC0
	private bool method_3(Assembly assembly_0, string string_3)
	{
		string a = null;
		string[] array = assembly_0.FullName.Split(new char[]
		{
			','
		});
		string text = "PublicKeyToken=";
		foreach (string text2 in array)
		{
			string text3 = text2.Trim();
			if (text3.StartsWith(text))
			{
				a = text3.Substring(text.Length);
				IL_66:
				return a == string_3;
			}
		}
		goto IL_66;
	}
```

3. As you can see, the label `IL_66` is in the `if` block and is not accessible by the statement `goto IL_66;`. 

4. I also tried .NET Reflector which generates the following code:
![image](https://user-images.githubusercontent.com/39968/47528679-655e1400-d8d8-11e8-9d6d-20b5f716af92.png)

This is a potential bug. Hope someone can take a look. Thanks.

**Comment by chucklu** [comment]
Hi @0xd4d ,
      Currently I will try to do decompile the dll file with ILSpy and modify it with https://github.com/sailro/Reflexil/ .
      Although you marked this issue with label wontfix, I found the same issue in ILSpy https://github.com/icsharpcode/ILSpy/issues/480. It seems the ILSpy fix this problem.
