### ISSUE TITLE
Copy Unknown Metadata option does not work

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnSpy#982]
- What version did you use?
dnSpy (5.0.9.0)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
_Copy Unknown Metadata_ option does not work, If you want I can send file by email.

**Comment by 0xd4d** [comment]
Add some repro steps because it's impossible to help you with the info you've provided.

**Comment by 0xd4d** [comment]
You have to provide repro steps since that issue you've linked to was closed because the feature was added to dnSpy and confirmed working.
