### ISSUE TITLE
dnSpy keeps fetching Windows assemblies when I don't want it to.

### ISSUE THREAD

**Issue by DanteMele** [0xd4d/dnSpy#983]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use? 5.0.7(x64)

- Write down all steps needed to reproduce this issue. Also attach any needed files. Deleted them, kept coming back.

**Comment by 0xd4d** [comment]
I need more info, eg. add repro steps.

**Comment by DanteMele** [comment]
I'm trying to decompile a game's assembly and the Windows .NET DLLs keep coming back randomly.

**Comment by piratesephiroth** [comment]
It's not random, dsnpy will always list all the dlls the analyzed software requires.

**Comment by DanteMele** [comment]
Oh ok.

**Comment by 0xd4d** [comment]
Try the latest version first, you're using 5.0.7 which isn't the latest version.

You can also drag and drop all files to dnSpy, and it will use those files instead of searching other dirs.
