### ISSUE TITLE
Uncomfortable translated strings

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#984]
![pic](https://user-images.githubusercontent.com/2529999/47613530-d87bac00-dacb-11e8-8fb9-d29d91f1030b.jpg)

Main: 主要 常规 通用
Custom Attrs: 自定义特性
In: 输入

**Comment by 0xd4d** [comment]
You can fix it by going to https://crowdin.com/project/dnspy

**Comment by UlyssesWu** [comment]
@CreateAndInject 
Main: Now fixed as "主要"
Custom Attrs: Now fixed as "自定义特性"
In & Out: Already fixed as "传入" & "传出" (not yet merged)
