### ISSUE TITLE
DnSpy can't open a NET assembly which has invalid headers.

### ISSUE THREAD

**Issue by PiotrKFtw** [0xd4d/dnSpy#990]
I used latest version.
I noticed that dnspy can't open NET assemblies if their headers are modified by hex editor for example.
You can fix it by trying to load assembly even though it has invalid headers.

**Comment by 0xd4d** [comment]
It should be able to open the assembly if the CLR can read it. Sounds like your assembly isn't executable anymore.

**Comment by 0xd4d** [comment]
Can the CLR load that assembly?

**Comment by AntiLeecher** [comment]
Very very very nice issue. I know what you really want to do.

**Comment by piratesephiroth** [comment]
I suppose it's related to [cheats and mods in Unity](https://lifeinhex.com/tag/protection/)

**Comment by 0xd4d** [comment]
If it's encrypted, decrypt it. Closing this.

**Comment by AntiLeecher** [comment]
@piratesephiroth Wow you are such a faggot. Go get a fucking life. Hope you will get cursed one day

**Comment by 0xd4d** [comment]
Locking this one
