### ISSUE TITLE
Debugger setting to ignore exceptions

### ISSUE THREAD

**Issue by piratesephiroth** [0xd4d/dnSpy#993]
- What version did you use?
v5.0.9.0 (the latest build at the moment)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
debug crappy unity game, see unhandled exceptions being thrown left an right

Is there an option for the debugger not to break on specific exceptions (like Olly and x64dbg)?
I couldn't find anything like that.

**Comment by 0xd4d** [comment]
Check the exception settings window. Almost all exceptions are disabled by default so it only breaks when there's an unhandled exception.

**Comment by M-o-o** [comment]
I think @piratesephiroth may have meant unhandled exceptions. I currently have a similar problem, where dnSpy is paralyzed by continuous unhandled exceptions, which the target (unity game) seems to ignore.

**Comment by 0xd4d** [comment]
@M-o-o Can you open a new issue about that?

**Comment by M-o-o** [comment]
Why a new issue? It's the same problem as this one (he added a thumbs up on my previous comment, which I assume means he agrees).
You said "only breaks when there's an unhandled exception", and it is unhandled exceptions that are the problem (his "see unhandled exceptions"), as the debugger breaking again on one of these as soon as it resumes means nothing else can be debugged.
So, some way of telling it to not break on unhandled exceptions would help, at least for Unity.

**Comment by 0xd4d** [comment]
BTW, the latest build can now ignore unhnadled exceptions. You can enable the option in debugger settings.

**Comment by M-o-o** [comment]
Works well. Thanks!
