### ISSUE TITLE
System.TypeInitializationException when starting dnSpy

### ISSUE THREAD

**Issue by RaXorX** [0xd4d/dnSpy#994]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
v5.0.10.0 and v5.0.9.0

- Write down all steps needed to reproduce this issue. Also attach any needed files.
As soon as I start dnSpy it gives me that error. I don't think it's a dnSpy error perhaps, but hope to find a resolution here.

![snip_20181113064606](https://user-images.githubusercontent.com/44987810/48385200-79e13f80-e713-11e8-93a8-3780a330339b.png)

**Comment by 0xd4d** [comment]
Try this

- Install .NET Framework 4.7.2
- Delete %APPDATA%\dnSpy
- Download latest dnSpy and extract it to a new directory

**Comment by RaXorX** [comment]
Thanks, that did it. I thought .net framework 4.6.2 would be enough and it was due to .net framework 3.5 (and below) not being present on my system. I tried that but it didn't work. 

Installing 4.7.2 did it.
