### ISSUE TITLE
Encrypted DLL cant see inside DNSPY Make this everything Public inside DNSPY Please

### ISSUE THREAD

**Issue by blackmodteam** [0xd4d/dnSpy#995]
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use? 
latest version 
- Write down all steps needed to reproduce this issue. Also attach any needed files.
https://usersdownload.com/1gl9u3csrbhk.html

Please make everything Public in DNSPY . this is the file that cant be seen inside DNSPY and i wish it will be added to your dnspy to see inside codes. Thank You.

**Comment by UlyssesWu** [comment]
This file is an encrypted assembly. You should fix the file header by yourself, or try to dump things when the game is running. There is nothing wrong with dnSpy.

**Comment by blackmodteam** [comment]
But before DNSPY can reveal all of the code and now it cant be. i hope DNSPY can reveal everything again like the update before.

**Comment by 0xd4d** [comment]
There's no decrypter in dnSpy, so if you could see the code before, it was because nothing was encrypted.

**Comment by blackmodteam** [comment]
It has encrypted on it because the original had code but this one  didn't have. By the way you said it can use by fixing the header so how it will fix.

**Comment by blackmodteam** [comment]
> Fixed about 9~10 bad values in header and I can already see the internal clearly. But actually I found dnSpy (dnlib) a bit more _strict_ than other tools. For example, I missed to fix the `Cor20 Header 0x00000208 cb` from 0( ) to 0x48( ), so dnSpy refused to show any .NET types, but JD, Reflector and ILSpy4 all can ingore that wrong value and show decompiled results.
> 
> ![fixed-asm](https://user-images.githubusercontent.com/4312781/48472910-3f21f900-e832-11e8-8bba-c5199d6c5e9c.png)
> 
> I won't help you to cr4ck others' products by giving you the fixed assembly. It's not that easy to be a 1337 cr4ck3r, my friend. Please learn more and you can do it by yourself.
> 
> Here are first steps to fix it:
> 
> * NT Header: Signature
> * Optional Header: NumberOfRvaAndSizes
> * MetaData Header: NumberOfStreams, *Version(s)
> * MetaData Streams: Size(s)
> * Cor20 Header

this would be a great help for me but could you please help me fix this. This is i want to make it fix the header. Please only this thing could be really great help for me . 
https://usersdownload.com/1gl9u3csrbhk.html

**Comment by blackmodteam** [comment]
> Fixed about 9~10 bad values in header and I can already see the internal clearly. But actually I found dnSpy (dnlib) a bit more _strict_ than other tools. For example, I missed to fix the `Cor20 Header 0x00000208 cb` from 0( ) to 0x48( ), so dnSpy refused to show any .NET types, but JD, Reflector and ILSpy4 all can ingore that wrong value and show decompiled results.
> 
> ![fixed-asm](https://user-images.githubusercontent.com/4312781/48472910-3f21f900-e832-11e8-8bba-c5199d6c5e9c.png)
> 
> I won't help you to cr4ck others' products by giving you the fixed assembly. It's not that easy to be a 1337 cr4ck3r, my friend. Please learn more and you can do it by yourself.
> 
> Here are first steps to fix it:
> 
> * NT Header: Signature
> * Optional Header: NumberOfRvaAndSizes
> * MetaData Header: NumberOfStreams, *Version(s)
> * MetaData Streams: Size(s)
> * Cor20 Header

I send a you a message in gmail. please help me with the matters. only the dll i request need to fix. please

**Comment by UlyssesWu** [comment]
What you're asking is not a dnSpy related issue, as I have proved just now. Learn harder and save yourself. I have no time or motivation to help, sorry and good luck.

**Comment by blackmodteam** [comment]
> What you're asking is not a dnSpy related issue, as I have proved just now. Learn harder and save yourself. I have no time or motivation to help, sorry and good luck.

Really great help for me. Thank You and i will try this

**Comment by 0xd4d** [comment]
I haven't looked at the file yet but it seems that Unity can read it, i.e., it's not encrypted. That means dnSpy should also be able to read it.

**Comment by blackmodteam** [comment]
> I haven't looked at the file yet but it seems that a non-modified Unity can read it, i.e., it's not encrypted. That means dnSpy should also be able to read it.

Thanks for replying here author 0xd4d . If you have time to check that and share what you discover is a great for me. Also thanks for your tool updates. By the way ,UlyssesWu  also give me idea about this and notice something in file. but now his on business trip

**Comment by SlowLogicBoy** [comment]
> I haven't looked at the file yet but it seems that a non-modified Unity can read it, i.e., it's not encrypted. That means dnSpy should also be able to read it.

It is encrypted. This is a cheat for unity game that comes with libmono.so, that decrypts it. 
I was able to decrypt it (I found encryption method they used). Then dnSpy/dnlib was able to read it, however:
![image](https://user-images.githubusercontent.com/3121637/48535136-ee061980-e8b2-11e8-8704-7224bd38df21.png)
So I had to do what was suggested in @UlyssesWu fixing steps.

I don't want to paste links where I found this info, but 2 min of "googleing" and you might able to find it.
Hint: that link was already posted in one of the issues in one of @0xd4d repositories.

**Comment by 0xd4d** [comment]
In that case there's nothing to fix. Anyone who needs to decrypt encrypted assemblies should use another tool. dnSpy should however be able to read any assembly that can be read by Mono/Unity/.NET Framework/.NET Core.

**Comment by 0xd4d** [comment]
You misunderstood what I said: it's encrypted, so you have to decrypt it yourself or use someone else's tool. dnSpy is not an unpacker.

**Comment by blackmodteam** [comment]
> You misunderstood what I said: it's encrypted, so you have to decrypt it yourself or use someone else's tool. dnSpy is not an unpacker.

i understand what you mean. Now im focusing on the comment they suggested to me . like SlowLogicBoy  said i need to decrypt it. and he said it was already posted here in the issues section. im looking it now to check what he want to say. BTW thanks for your hard work for this update.

**Comment by 0xd4d** [comment]
Closing it, the issue you're looking for is https://github.com/0xd4d/dnSpy/issues/990

**Comment by SlowLogicBoy** [comment]
>dnSpy should however be able to read any assembly that can be read by Mono/Unity/.NET Framework/.NET Core.

Does this apply to old Mono versions?

if so it doesn't work, current "bugs" with dnSpy/dnlib (those are actually old mono bugs):
1. dnSpy incorrectly reads Storage Streams if Storage Signature iVersionString is incorrect, Mono doesn't read iVersionString it calculates iVersionString instead from version:
![image](https://user-images.githubusercontent.com/3121637/48542701-88bd2300-e8c8-11e8-8464-841d7ea7b426.png)
If I round length to multiples of 4: `iVersionString = (iVersionString + 3U) & ~3U` in this case `(0xA + 3U) & ~3U = 0xC` if I change that to `0xC`:
![image](https://user-images.githubusercontent.com/3121637/48542903-fc5f3000-e8c8-11e8-9e19-072f73ffef31.png)

Maybe I'm talking nonsence here since I'm not expert in this field. Now I'm trying to figure out why dnSpy "incorrectly" reads Storage Streams where old mono does.

I'm just reading those articles and trying to understand this. Probably I should open this issue on dnlib?

**Comment by 0xd4d** [comment]
Mono and .NET Framework read the files differently, and dnlib tries to read it the same way CLR reads the files. I added some fixes (https://github.com/0xd4d/dnSpy/issues/818) but it's not complete yet. You can open a new issue here if you want.

**Comment by blackmodteam** [comment]
> > dnSpy should however be able to read any assembly that can be read by Mono/Unity/.NET Framework/.NET Core.
> 
> Does this apply to old Mono versions?
> 
> if so it doesn't work, current "bugs" with dnSpy/dnlib (those are actually old mono bugs):
> 
> 1. dnSpy incorrectly reads Storage Streams if Storage Signature iVersionString is incorrect, Mono doesn't read iVersionString it calculates iVersionString instead from version:
>    ![image](https://user-images.githubusercontent.com/3121637/48542701-88bd2300-e8c8-11e8-8464-841d7ea7b426.png)
>    If I round length to multiples of 4: `iVersionString = (iVersionString + 3U) & ~3U` in this case `(0xA + 3U) & ~3U = 0xC` if I change that to `0xC`:
>    ![image](https://user-images.githubusercontent.com/3121637/48542903-fc5f3000-e8c8-11e8-9e19-072f73ffef31.png)
> 
> Maybe I'm talking nonsence here since I'm not expert in this field. Now I'm trying to figure out why dnSpy "incorrectly" reads Storage Streams where old mono does.
> 
> I'm just reading those articles and trying to understand this. Probably I should open this issue on dnlib?

did you have the fix dll of my post here? can you send me
