### ISSUE TITLE
Use separate releases for different versions

### ISSUE THREAD

**Issue by tylerszabo** [0xd4d/dnSpy#997]
I've noticed that this project seems to be using a single URL (https://github.com/0xd4d/dnSpy/releases/download/v5.0.0/dnSpy.zip) for all releases - updating that zip with the latest version. This is convenient for automatically downloading the latest version; unfortunately this causes problems for the [Chocolatey Package](https://chocolatey.org/packages/dnspy) mismatching hashes and makes rollback require stashing a local copy of old releases.

It's still possible to support linking to the latest release with https://github.com/0xd4d/dnSpy/releases/latest (it won't link directly to the asset, though).

**Comment by blackmodteam** [comment]
> I've noticed that this project seems to be using a single URL (https://github.com/0xd4d/dnSpy/releases/download/v5.0.0/dnSpy.zip) for all releases - updating that zip with the latest version. This is convenient for automatically downloading the latest version; unfortunately this causes problems for the [Chocolatey Package](https://chocolatey.org/packages/dnspy) mismatching hashes and makes rollback require stashing a local copy of old releases.
> 
> It's still possible to support linking to the latest release with https://github.com/0xd4d/dnSpy/releases/latest (it won't link directly to the asset, though).

what is the latest version of DNSPY ? what version

**Comment by tylerszabo** [comment]
`dnSpy-x86.exe` has file version `5.0.10.0` in dnSpy.zip with SHA256 hash `4571CCF630C408B0AF5E01ABC012C1B9354733C33DC1F5C70903169F0C0F065C`.

**Comment by blackmodteam** [comment]
> `dnSpy-x86.exe` has file version `5.0.10.0` in dnSpy.zip with SHA256 hash `4571CCF630C408B0AF5E01ABC012C1B9354733C33DC1F5C70903169F0C0F065C`.

can you send me the exe link for new update dnspy x64 version?

**Comment by tylerszabo** [comment]
It's all in that zip I linked in the first post: https://github.com/0xd4d/dnSpy/releases/download/v5.0.0/dnSpy.zip

**Comment by blackmodteam** [comment]
> It's all in that zip I linked in the first post: https://github.com/0xd4d/dnSpy/releases/download/v5.0.0/dnSpy.zip

i thought there is new version in dnspy? is this version 5.0.5?

**Comment by tylerszabo** [comment]
It appears to be 5.0.10.0; but the actual version isn't quite the point.

**Comment by blackmodteam** [comment]
> It appears to be 5.0.10.0; but the actual version isn't quite the point.

okay. does executed file inside the zip alreadY?

**Comment by 0xd4d** [comment]
I only keep the latest version anyway so whenever I release a new version, that old link would still not work.

Appveyor keeps the builds for 6 months. [Latest v5.0.x release](https://ci.appveyor.com/project/0xd4d/dnspy/branch/v5.0.x/artifacts) and [v5.0.10](https://ci.appveyor.com/project/0xd4d/dnspy/builds/19688497) (it's curently the same release)

**Comment by tylerszabo** [comment]
Would you consider using a unique link for each build to enable use cases like Chocolatey?

**Comment by 0xd4d** [comment]
A unique link would probably not help Chocolatey since I will still only keep the latest version.

**Comment by tylerszabo** [comment]
I suppose the question is then, why remove the old version? It'd be really handy (for the aforementioned reason) if they were still available - that way there would be stable links.

**Comment by 0xd4d** [comment]
The old versions are removed because I don't want people to download the old versions when a new one is available. Too many people click on a link in a forum and never know that there's a newer version available.

The appveyor link is stable for 6 months. You can use the github link as a backup if appveyor fails after 6 months and I still haven't released a new version.

**Comment by tylerszabo** [comment]
In this particular case users that install using a package manger are actually stuck using an older version (if the package is installed at the wrong time  then the hashes mismatch); would you consider having some stable links somewhere? Because it happens that if you release a new version and the package manger version is still undergoing validation (automated install test suite) or waiting for the maintainer to take an action such as fixing a packaging issue that we're unable to install a new version.

Unfortunately, for those of us using Chocolatey the pain is quite significant: the old version is uninstalled and then the new version fails a hash check and we're stuck with no version installed.

One option would be to maintain a release URL (like through a URL shortener) that always points to your most recent version via 302.

Of course it's entirely up to you how you choose to release your software but this makes it very hard for me to use it and I really like dnSpy.

**Comment by 0xd4d** [comment]
I'll keep the old version for another month before deleting it, that should be enough time to update Chocolatey, right?

**Comment by tylerszabo** [comment]
If the link for each version is stable then it'll likely help; though it'll still break rollback.

However I'd like to point out the option of using a URL shortener that allows editing of the destination URL and keeping artifacts in separate releases (like ILSpy).

**Comment by 0xd4d** [comment]
Just a heads up that 5.0.11 is up. I don't know if you subscribe to release notifications.

**Comment by 0xd4d** [comment]
@tylerszabo I now realize that you're not the maintainer of that package, I was waiting for you to update the it.
