### ISSUE TITLE
Can't view variables in Locals when build as Release

### ISSUE THREAD

**Issue by Misiu** [0xd4d/dnSpy#999]
- What version did you use?
5.0.9

When trying to debug DLL and when my breakpoint is hit I see this in Locals panel:

> Cannot obtain value of the local variable or argument because it is not available at this instruction pointer, possibly because it has been optimized away.

> Decompiler generated variables can't be evaluated

![locals_debug](https://user-images.githubusercontent.com/1741838/48843030-3c755580-ed96-11e8-84ef-dfdcccbaa5de.png)

DLL is built as a Release, so this might be the cause of this behaviour.
Is is possible to view those variables inside dnSpy. If Yes I'll be grateful for hint.

**Comment by 0xd4d** [comment]
If you've attached to the process, let dnSpy start it instead. If that's not possible, read [this](https://github.com/0xd4d/dnSpy/wiki/Making-an-Image-Easier-to-Debug)
